### ISSUE TITLE
No response to SUBSCRIBE containing more than 127 topic filters

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#10]
Compatibility testing `vernemq` on OS X with https://github.com/ckrey/MQTT-Client-Framework

>[MQTT-3.8.4-1]
>When the Server receives a SUBSCRIBE Packet from a Client, the Server MUST respond with a SUBACK Packet.

**Comment by dergraf** [comment]
Hello, is the limitation to 127 topic filters per SUBSCRIBE request specified within the standard or is it a de-facto standard?

**Comment by ckrey** [comment]
There is no limitation in the standard other than payload size.
My test tries to subscribe 256 topics, this is how I found your limitation

**Comment by dergraf** [comment]
interesting. ..

**Comment by dergraf** [comment]
is fixed in https://github.com/erlio/vmq_commons/commit/818c345795def117b5874b700c241853a0073440

**Comment by ckrey** [comment]
confirmed: fixed

**Comment by dergraf** [comment]
thanks!
