### ISSUE TITLE
VerneMQ 0.12.5 does not run on Ubuntu 15.10

### ISSUE THREAD

**Issue by tanpinsiang** [erlio/vernemq#101]
I tried VerneMQ 0.12.5 on Ubuntu 15.10 with official binary package from 
`https://bintray.com/artifact/download/erlio/vernemq/deb/trusty/vernemq_0.12.5-1_amd64.deb`

Install the deb file as below
> sudo dpkg -i vernemq_0.12.5-1_amd64.deb

`Selecting previously unselected package vernemq.
(Reading database ... 131695 files and directories currently installed.)
Preparing to unpack vernemq_0.12.5-1_amd64.deb ...
Unpacking vernemq (0.12.5-1) ...
Setting up vernemq (0.12.5-1) ...
Installing new version of config file /etc/vernemq/vernemq.conf ...
insserv: warning: script 'K01pritunl' missing LSB tags and overrides
insserv: warning: script 'pritunl' missing LSB tags and overrides
Processing triggers for systemd (225-1ubuntu9.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for man-db (2.7.4-1) ...
`

However VerneMQ does not run using default config.
> sudo vernemq console

>Error generating config with cuttlefish
    run `vernemq config generate -l debug` for more information.

more information on software versions:
Kernel: 4.2.0-16-generic
OS: Ubuntu 15.10
erlang: no

VerneMQ 0.12.4 works fine. 

Thanks

**Comment by dergraf** [comment]
we never tried the Ubuntu Trusty package on a Vivid machine, this could be related to this.
Can you share the output of `vernemq config generate -l debug` as well as anyother error log you get.

**Comment by tanpinsiang** [comment]
Thankyou for the fast reply!

This is the output from 'vernemq config generate -l debug'.

> vernemq config generate -l debug
>21:05:27.792 [debug] Lager installed handler error_logger_lager_h into error_logger
21:05:27.805 [debug] Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.51.0>
21:05:27.806 [debug] Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.52.0>
21:05:27.806 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.53.0>
21:05:27.806 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0}]) at pid <0.54.0>
21:05:28.004 [debug] Cuttlefish set to debug level logging
21:05:28.004 [info] Application lager started on node nonode@nohost
21:05:28.006 [info] Checking /etc/vernemq/app.config exists... false
21:05:28.006 [info] Checking /etc/vernemq/vm.args exists... false
21:05:28.006 [info] No app.config or vm.args detected in /etc/vernemq, activating cuttlefish
21:05:28.006 [debug] Generating config in: "/var/lib/vernemq/generated.configs/app.2016.03.19.21.05.28.config"
21:05:28.007 [debug] No Schema files found in specified

I found that vernemq does create a new directory in '/var/log/vernemq', however there is no file in the directory.

**Comment by dergraf** [comment]
this actually looks ok. (quite similar to the output on my Debian Jessie)

what happens if you run `sudo service vernemq start`

**Comment by tanpinsiang** [comment]
I also tried it on Ubuntu 14.04.4 LTS
I get same output on 
>sudo vernemq console
>vernemq config generate -l debug

**Comment by dergraf** [comment]
what is the output of `sudo vernemq console`?

**Comment by tanpinsiang** [comment]
on Ubuntu 14.04.4 LTS:

> sudo vernemq console
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.

> vernemq config generate -l debug
21:12:03.965 [debug] Lager installed handler error_logger_lager_h into error_logger
21:12:03.976 [debug] Supervisor gr_param_sup started gr_param:start_link(gr_lager_default_tracer_params) at pid <0.51.0>
21:12:03.976 [debug] Supervisor gr_counter_sup started gr_counter:start_link(gr_lager_default_tracer_counters) at pid <0.52.0>
21:12:03.976 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_params_mgr, gr_lager_default_tracer_params, []) at pid <0.53.0>
21:12:03.976 [debug] Supervisor gr_manager_sup started gr_manager:start_link(gr_lager_default_tracer_counters_mgr, gr_lager_default_tracer_counters, [{input,0},{filter,0},{output,0}]) at pid <0.54.0>
21:12:04.123 [debug] Cuttlefish set to debug level logging
21:12:04.123 [info] Application lager started on node nonode@nohost
21:12:04.125 [info] Checking /etc/vernemq/app.config exists... false
21:12:04.126 [info] Checking /etc/vernemq/vm.args exists... false
21:12:04.126 [info] No app.config or vm.args detected in /etc/vernemq, activating cuttlefish
21:12:04.126 [debug] Generating config in: "/var/lib/vernemq/generated.configs/app.2016.03.19.21.12.04.config"
21:12:04.126 [debug] No Schema files found in specified

For upstart 
> sudo service vernemq start
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.

> $cat erlang.log.1
=====
===== LOGGING STARTED Sat Mar 19 21:13:50 HKT 2016
=====
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
$ cat run_erl.log 
run_erl [18743] Sat Mar 19 21:13:50 2016
Args before exec of shell:
run_erl [18743] Sat Mar 19 21:13:50 2016
argv[0] = sh
run_erl [18743] Sat Mar 19 21:13:50 2016
argv[1] = -c
run_erl [18743] Sat Mar 19 21:13:50 2016
argv[2] = exec /usr/sbin/vernemq console

**Comment by dergraf** [comment]
I am able to reproduce it.
Interestingly I cannot reproduce it if using the `service vernemq start` .

**Comment by Benniu** [comment]
Had the same issue.

Unable to start VerneMQ no matter using 'vernemq start' or 'service vernemq start'.

I'm using Ubuntu 14.04.2 LTS with vernemq_0.12.5-1_amd64.deb

**Comment by ioolkos** [comment]
Thanks for reporting, @Benniu.
There seems to be an internal file path problem with the packages, we're going to update these.
Sorry for that!

Building the release should work though.

**Comment by tanpinsiang** [comment]
Thanks ioolkos, I wonder whether running VerneMQ on Erlang/OTP 18.3 or HiPE recommended in production? Or it is better to use deb/binary packages?

**Comment by ioolkos** [comment]
Hi @tanpinsiang, we have just made VerneMQ OTP18 compatible, so far nothing has come up against running it on 18 in production.
HiPE is not a priority for us right now; but we'd be very happy to hear from people playing around with HiPE and VerneMQ.

**Comment by dergraf** [comment]
We ve released a patch release 0.12.5p1 yesterday. Could you upgrade and recheck please? Thanks.

**Comment by Benniu** [comment]
@dergraf  Thanks for the fix. Yes, it works fine now.

**Comment by tanpinsiang** [comment]
@dergraf Yes, It does work. I saw the package is included with Erlang/OTP 17, is it originally included with Erlang/OTP 18? 
Thanks for the impressive work!

**Comment by dergraf** [comment]
The packages we currently ship are all based on 17.

**Comment by tanpinsiang** [comment]
Thanks for the information.
