### ISSUE TITLE
error using vmq-password on ubuntu 15.10

### ISSUE THREAD

**Issue by marianoguerra** [erlio/vernemq#109]
Just compiled master from source on ubuntu 15.10 and when trying to create a user I got this error

    $ ./bin/vmq-passwd -c etc/vmq.passwd mariano
    ./bin/vmq-passwd: error while loading shared libraries: libcrypto.so.10: cannot open shared object file: No such file or directory

I know the hacky solution (symlink libcrypto.so.1.0.0), but I'm posting this here in case you find a way to avoid this error altogether

**Comment by marianoguerra** [comment]
I think I was using a broken build, I will close it for now since after a clean build it works

**Comment by ioolkos** [comment]
Thanks, Mariano. It's still useful feedback! :)
