### ISSUE TITLE
Recomend a js library for mqtt over ws in the docs

### ISSUE THREAD

**Issue by marianoguerra** [erlio/vernemq#110]
in the docs here https://vernemq.com/docs/configuration/websockets.html you say:

    Keep in mind that you'll use MQTT-over-WebSocket, so you will need a Javascript library that implements the MQTT client behaviour. There are quite a lot to choose from.

I think it's a good idea to say, "we recommend/test paho, you can download it here" or something like that so people don't have "paralysis of choice" :)

**Comment by ioolkos** [comment]
Updated. Thanks!
