### ISSUE TITLE
Describe available $SYSTree topics and value for <NodeName>

### ISSUE THREAD

**Issue by marianoguerra** [erlio/vernemq#111]
in https://vernemq.com/docs/monitoring/systree.html it doesn't list what topics are available, from https://vernemq.com/docs/monitoring/ and playing with wildcards in the CLI I could find out that the format is $SYS/\<NodeName\>/ followed by the topics listed in monitoring.

it would be useful if a link to the list in monitoring was added in the systree section and also some sample topics, also showing an example of what NodeName is (like VerneMQ@127.0.0.1) and where it can be found (in the console prompt and in the config file "grep nodename vernemq.conf")

finally maybe an example on how to discover them via the cli like:

    mosquitto_sub -t \$SYS/<node-name>/\# -u <username> -P <password> -d

which will print received messages with the topic they come from (-d is for debug)

**Comment by ioolkos** [comment]
Thanks so much for identifying this kind of "friction"! very valuable.
I started updating the doc and will add examples.

**Comment by dergraf** [comment]
Hi @marianoguerra

We've extended the $SYS docs a bit. Of course we heavily appreciate your feedback on this. https://vernemq.com/docs/monitoring/systree.html

Let me close this issue for the moment.

Cheers,
Andre
