### ISSUE TITLE
Offline Messages

### ISSUE THREAD

**Issue by janshahid** [erlio/vernemq#112]
Hi,

This is regarding offline messaging.Please have a look at the below scenario.

A and B connected to the Broker .A sent a message to B and B received it.To test the offline messages,I disconnected the B and sent two messages from A. After some time I made B connection up before the keep alive time but B did not receive any messages from broker which were sent by A .As per this test,I think the offline messages implementation is not there.

Could you please let me know whether the implementation is there for offline messages or not .

If it is there then please let me know the module name and which database you are using for storing the offline messages.

Thank you in advance

**Comment by larshesel** [comment]
To make offline messages possible the client has to set the cleansession flag to false when connecting to the broker.

Does that solve your problem?

**Comment by janshahid** [comment]
Yes,I put clean session as false.Please have a look at the below parameters.

> {client_id, <<"Dhinesh">>},{clean_sess,false},{keepalive,600000}

**Comment by janshahid** [comment]
Yes,I already put clean session as false.Please have a look at the below parameters.

{client_id, <<"Dhinesh">>},{clean_sess,false},{keepalive,600000}

Is there any configurations I need to change to support offline messages ?

**Comment by ioolkos** [comment]
Quality of Service actually matters.
Messages have to be published with Qos 1 or 2; and subscriber have to subscribe with Qos 1 or 2.

**Comment by janshahid** [comment]
Now it is working with QOS1.Thank you very much for quick help.

I have the below questions.

1. Why are you not using the MNESIA DB for storing the customer information/topics/etc.I could see some of the ETS tables are present but not MNESIA.
2.I could see some RIAK DB staff in some of the modules.For what purpose you are using the RIAK DB.

Please let me know your answers.

Thank you once again

**Comment by ioolkos** [comment]
Good.

We don't use Mnesia for sharing information within the cluster because Mnesia is not clearly positioned related to CAP.
We want to have a clear position (eventual consistency) related to CAP.

We don't use RiakDB as a backend, but LevelDB.

Hope this makes sense.

**Comment by janshahid** [comment]
Thank you for the information.

Today,I am facing some new issue with the cluster.Please have a look at the below scenario.

In ubuntu AWS,I have started two vernemq servers with different ports.

```
1. server1@127.0.0.1      127.0.0.1:1883
2. server2@127.0.0.1     127.0.0.1:1884
```

A connected to server1 and B connected to server2.B sent a message to A and A received it and A sent a message to B but B did not received it.I am not sure what could be the issue.Please help me in this.

**Comment by ioolkos** [comment]
Is this still related to offline messages?
Supposing it's not:

- the connection could loose the message, if it's QoS 0 (unlikely case, if repeatable loss is there)
- B could be subscribed to the wrong topic
- B could issue the subscribe later than A published
