### ISSUE TITLE
Best practice for production use?

### ISSUE THREAD

**Issue by DawoonC** [erlio/vernemq#113]
Hi,

We're planning to use Vernemq for mobile notification in our service.
Currently we have approx. 2M users, and the most of them are on Android platform.

We've been successfully tested Vernemq on our development stage, but we have no idea how to configure/setup the vmq nodes for production use.

So, let's say if there are 1M connection, what would be the best practice?
- what would be appropriate max connection config for a single vmq node?
- how much memory would a single vmq node need?
- how many nodes should I have in the cluster?

I've tried with 50,000 max connection on m3.xlarge ec2 instance (15GB memory) and it consumed almost 90% of the memory.

I'm also curious if there is a way to reduce memory use of vernemq :)
(or more efficiently)

**Comment by ioolkos** [comment]
Hi @DawoonC thanks a lot for your interest! :)

I'm afraid we can't just give a quick best way to do it here. Can you get in touch with me via e-mail, to discuss your options? (info at vernemq.com)
