### ISSUE TITLE
vmq-admin script sub command not found

### ISSUE THREAD

**Issue by tkaarrela** [erlio/vernemq#114]
Hi,

I'm testing writing plugin with vmq_diversity on OSX but when I try to load lua script with 'vmq-admin script load'-command it lists vmq-admin usage instructions. Usage instruction does not contain 'script' sub command.

I have build vernemq myself from master branch and enabled vmq_diversity plugin. I can see that vmq_diversity plugin is installed by running 'vmq-admin plugin show'-command.

However, I got some errors when compiling vmq-diversity, not sure if those can cause issue that script sub command is not available.

$ rebar3 compile
===> Verifying dependencies...
===> Package <<"rebar_ct">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /Users/my_user_account/.cache/rebar3/hex/default/registry
===> Generating package index...
===> [cloudi_service_oauth1:1.5.1] Only existing version of cloudi_service_db_riak is 1.3.3 which does not match constraint ~> 1.5.1. Using anyway, but it is not guaranteed to work.
===> Writing index to /Users/my_user_account/.cache/rebar3/hex/default/packages.idx
===> Plugin rebar_ct not available. It will not be used.
===> Compiling vmq_diversity

**Comment by dergraf** [comment]
Hi there. Thanks for checking out VerneMQ and vmq_diversity. Can you post the exact commands please?

Cheers,
Andre

**Comment by tkaarrela** [comment]
**Building and starting VerneMQ**
1. Build VerneMQ => CFLAGS="-I /usr/local/Cellar/openssl/1.0.2d_1/include" make rel
2. Change directory to rel folder => {$VERNEMQ_PROJECT_ROOT}/_build/default/rel/vernemq/bin
3. Start vernemq => ./vernemq start

**Compile and load vmq_diversity**
1. Change directory to vmq_diversity root
2. Compile vmq_diversity => rebar3 compile
3. Load vqm_diversity plugin => ./vmq-admin plugin enable --name=vmq_diversity --path=${VMQ_DIVERSITY_ROOT}/_build/default/

**Restart VerneMQ**
1. Stop VerneMQ => ./vernemq stop
2. Start VerneMQ => ./vernemq start


**Show plugins**
1. Show plugins => ./vmq-admin plugin show
As result it will list "vmq_diversity|application|" for vmq_diversity plugin

**Load script**
1. ./vmq-admin script load ${VMQ_DIVERSITY_ROOT}/scripts/auth.lua
Usage: vmq-admin <sub-command>

  Administrate the cluster.

  Sub-commands:
    node        Manage this node
    cluster     Manage this node's cluster membership
    session     Retrieve session information
    plugin      Manage plugin system
    listener    Manage listener interfaces
  Use --help after a sub-command for more details.

**auth.lua content**
```
function my_auth_on_register(reg)
    log.info('auth on register called')
    return false
end

function my_auth_on_publish(pub)
    log.info('auth on publish called')
end

function my_auth_on_subscribe(sub)
    log.info('auth on subscribe subscribe called')
end

hooks = {
    auth_on_register = my_auth_on_register,
    auth_on_publish = my_auth_on_publish,
    auth_on_subscribe = my_auth_on_subscribe
}
```

**Comment by tkaarrela** [comment]
Not sure if related to this issue but following is logged to console.log

[warning] <0.154.0> OS_MON (cpu_sup), util/1 unavailable for this OS

**Comment by dergraf** [comment]
You're missing the path arg.
vmq-admin script load path=${VMQ_DIVERSITY_ROOT}/scripts/auth.lua

**Comment by dergraf** [comment]
@tkaarrela just figured that we have an error with the script command.. fixing it, and report back.

**Comment by dergraf** [comment]
@larshesel is looks like the custom application start function for the vmq_diversity plugin isn't called when used via the VerneMQ package... do you know what could be the reason for that. I am able to reproduce it.

**Comment by larshesel** [comment]
I think it's because in the vmq_diversity.app file have this: https://github.com/erlio/vmq_diversity/blob/master/src/vmq_diversity.app.src#L5

Shouldn't that be  ` {mod, {'vmq_diversity', []}},` instead?

**Comment by dergraf** [comment]
that's fine I guess, at least it's the same for vmq_acl and vmq_passwd

**Comment by larshesel** [comment]
There's more to it than that. In the vmq_plugin_mgr code it's assumed when looking for a custom start function that the start module is the same name as the application which is not always correct - in this case it's not! I'm creating a PR for vmq_plugin to handle this.

**Comment by larshesel** [comment]
Looking a bit closer it seems that it was actually working - we'd be calling the `vmq_diversity:start/0` as expected (I verified using `recon`), the issue has something to do with `vmq_diversity_cli:register_cli/0` function. `vmq-admin script` works for me if I call this function after the plugin has been loaded.

**Comment by tkaarrela** [comment]
Just to inform that I tested script load command with --path argument but didn't work for me.

./vmq-admin script load --path=${VMQ_DIVERSITY_ROOT}/scripts/auth.lua

**Comment by dergraf** [comment]
I was able to reproduce your problem.. and already fixed the bug in vmq_diversity. Please pull the newest changes and rebuild vmq_diversity

**Comment by tkaarrela** [comment]
I think it works now. Thanks for the fast fix!

./vmq-admin script load path=${VMQ_DIVERSITY_ROOT}/scripts/auth.lua
Script successfully loaded!

**Comment by dergraf** [comment]
Great! Let us know how it goes!
