### ISSUE TITLE
make rel error

### ISSUE THREAD

**Issue by Didan** [erlio/vernemq#115]
erlang version 18.0
vernermq version d5fe4b76e00c64ffeee6a188ebd20a8223d0eadb
make rel 
output error
===> Error loading package registry: {read_error,
                                             {file_error,
                                              "/home/daniel/.cache/rebar3/hex/default/registry",
                                              enoent}}
===> Package <<"rebar3_cuttlefish">> not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Fetching registry from "https://s3.amazonaws.com:443/s3.hex.pm/registry.ets.gz?"
===> error {badmatch,{error,{rebar_prv_update,package_index_download}}} [{rebar_packages,
                                                                                 handle_missing_package,
                                                                                 3,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_packages.erl"},
                                                                                  {line,
                                                                                   85}]},
                                                                                {rebar_app_utils,
                                                                                 get_package,
                                                                                 3,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                                  {line,
                                                                                   205}]},
                                                                                {rebar_app_utils,
                                                                                 update_source,
                                                                                 3,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                                  {line,
                                                                                   176}]},
                                                                                {rebar_app_utils,
                                                                                 dep_to_app,
                                                                                 7,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                                  {line,
                                                                                   162}]},
                                                                                {rebar_app_utils,
                                                                                 '-parse_deps/6-lc$^0/1-0-',
                                                                                 6,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                                                  {line,
                                                                                   98}]},
                                                                                {rebar_prv_install_deps,
                                                                                 handle_deps_as_profile,
                                                                                 4,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_prv_install_deps.erl"},
                                                                                  {line,
                                                                                   134}]},
                                                                                {rebar_plugins,
                                                                                 handle_plugin,
                                                                                 4,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                                                                                  {line,
                                                                                   94}]},
                                                                                {rebar_plugins,
                                                                                 '-handle_plugins/4-fun-0-',
                                                                                 4,
                                                                                 [{file,
                                                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_plugins.erl"},
                                                                                  {line,
                                                                                   83}]}]
===> Plugin rebar3_cuttlefish not available. It will not be used.
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile},
                                                  {default,release}]
===> Error loading package registry: {read_error,
                                             {file_error,
                                              "/home/daniel/.cache/rebar3/hex/default/registry",
                                              enoent}}
===> Package cuttlefish-2.0.7 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Fetching registry from "https://s3.amazonaws.com:443/s3.hex.pm/registry.ets.gz?"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {badmatch,
                             {error,
                              {rebar_prv_update,package_index_download}}}
===> Stack trace to the error location: [{rebar_packages,
                                                 handle_missing_package,3,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_packages.erl"},
                                                  {line,85}]},
                                                {rebar_app_utils,
                                                 update_source,3,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,184}]},
                                                {rebar_app_utils,dep_to_app,
                                                 7,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,162}]},
                                                {rebar_app_utils,
                                                 '-parse_deps/6-lc$^0/1-0-',6,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,98}]},
                                                {rebar_app_utils,
                                                 '-parse_deps/6-lc$^0/1-0-',6,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_utils.erl"},
                                                  {line,98}]},
                                                {rebar_app_discover,
                                                 '-do/2-fun-0-',3,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                                                  {line,31}]},
                                                {lists,foldl,3,
                                                 [{file,"lists.erl"},
                                                  {line,1262}]},
                                                {rebar_app_discover,do,2,
                                                 [{file,
                                                   "/home/opt/rebar3/_build/default/lib/rebar/src/rebar_app_discover.erl"},
                                                  {line,27}]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [rel] Error 1

**Comment by larshesel** [comment]
Hi, can you please try and run `./rebar3 update` and try again - that should fix the issue.

**Comment by Didan** [comment]
i have fixed it

**Comment by Didan** [comment]
wget https://s3.amazonaws.com:443/s3.hex.pm/tarballs/xxx-xxx.xxx.xxx.tar
mv xxx-xxx.xxx.xxx.tar .cache/rebar3/hex/default/packages/

**Comment by larshesel** [comment]
Great you got the issue resolved. I'm curious, did the `rebar3 update` command not solve the issue or had your found and applied your workaround first?

Let us know if you run into any other issues.

**Comment by Didan** [comment]
when fetching  package cuttlefish-2.0.7  failed, I use wget fetch the package from amazonaw
and then mv it to ~/.cache/rebar3/hex/default/packages/ 
go on meke rel

**Comment by Didan** [comment]
libssl-dev，
