### ISSUE TITLE
How to persist offline messages after broker restart

### ISSUE THREAD

**Issue by janshahid** [erlio/vernemq#116]
Hi,

I am working on vernemq for the offline message.Please have a look at the below scenario

Client A and Client B connected to the broker with clean session = false.After some time Client A sent a message to client B but he was offline.At this point of time,I restarted the broker.

When Client B came to online but he did not receive any messages from Client A.

Is this the behaviour of vernemq or Is there any configuration I missed it to store all the offline messages in the queue while restart ?

**Comment by ioolkos** [comment]
This should work. 
Note: 
1. you need to subscribe with clean session false (apparently you do that).
2. you need to subscribe with QoS > 0 and 
3. you need to publish with QoS > 0

**Comment by janshahid** [comment]
Thank you for the information.

**Comment by agenteDserrano** [comment]
Hello @ioolkos I am using 1.7.0 version. I have clean session both publisher and subscriber also QOS 1 on both.

I have publish a message with client offline. Then I check with command

webadmin@mqtt1:~$ sudo vmq-admin session show --client_id --offline_messages
+------------+----------------+
| client_id  |offline_messages|
+------------+----------------+
|test-client5|       1        |
|test-client3|       0        |
+------------+----------------+

Then I restart verneMQ 

webadmin@mqtt1:~$ sudo /etc/init.d/vernemq restart
[ ok ] Restarting vernemq (via systemctl): vernemq.service.

After restar I check again and the test-client5 is no more there. 
webadmin@mqtt1:~$ sudo vmq-admin session show --client_id --offline_messages
+------------+----------------+
| client_id  |offline_messages|
+------------+----------------+
|test-client3|       0        |
+------------+----------------+

I connect the test-client5 and I dont get any message.

So I think persis offline message after broker restart are not working for me.

**Comment by ioolkos** [comment]
Hi @agenteDserrano thansk... as I cannot reproduce the behaviour you describe, we'd need more information like the exact commands you use to subscribe and publish.

**Comment by agenteDserrano** [comment]
@ioolkos Nevermind... Was the client that I was use... not working clear session option. I test with mosquitto sub and work great.

Thanks.
