### ISSUE TITLE
syslogs

### ISSUE THREAD

**Issue by janshahid** [erlio/vernemq#117]
Hi Team,

I have the below questions.
1.How to enable syslogs for all the process ?
2.I tried to enable the DBG traces on one module but nothing is logged on the console.Do I need to change any configuration for this ?

dbg:tracer().
dbg:p(all, call).

dbg:tpl(vmq_mqtt_fsm,’_’, [{'_', [], [{return_trace}]}]).
dbg:tpl(vmq_lvldb_store,’_’, [{'_', [], [{return_trace}]}]).
dbg:tpl(vmq_queue,’_’, [{'_', [], [{return_trace}]}]).

3.Can we enable debug messages for some specific client Id's ?

Please let me know your answers..

Thank you...

**Comment by ioolkos** [comment]
Will look into your questions, but just a quick hint to the fantastic erlyberly tracing tool: https://github.com/andytill/erlyberly

It works well with VerneMQ, although of course if you over trace stuff, the tool will sometimes hang.

**Comment by janshahid** [comment]
Thank you for your suggestion. But the logs will be huge so Please let me know your answers for the above questions.

**Comment by ioolkos** [comment]
There's logging and there's tracing. The debug logging level can be configured with `log.console.level` in the vernemq.conf, but it's admittedly not as useful as it should be.

For tracing, you probably want to use recon_trace (http://ferd.github.io/recon/recon_trace.html), it's built into VerneMQ.

If you really want to trace all functions of a module, you can then at least limit the number of traces and printouts.

There's a lot of tricks you can do like tracing only new pids, tracing for specific pids, tracing for literal arguments etc, which I can't list all here.

Will be back, if I can figure out more concrete ways & example to explain better & help you better.

**Comment by janshahid** [comment]
HI ioolkos,

I am not comfortable with the 'recon_trace'.Could you please let me know how to enable dbg.erl module on the vernemq server ?

**Comment by larshesel** [comment]
Hi, you can find the dbg documentation here: http://erlang.org/doc/man/dbg.html. I've never liked using this directly and prefer `recon` because I find it easier to use and it includes a bunch of features making tracing safer in production systems.

**Comment by ioolkos** [comment]
Yes, dbg, recon, and redbug are all built-in to VerneMQ. You don't have to enable this or something.

But I realize that you may be running this from an attached console & you might want to start the tracer process with something like

```erlang
dbg:tracer(process, {fun(Msg, _) -> io:format("~p~n", [Msg]) end, []}).
```

**Comment by dergraf** [comment]
Please get in touch over email (info[@]vernemq.com) if you require further assistance with debugging and tracing VerneMQ or Erlang systems in general. 

Cheers,
Andre
