### ISSUE TITLE
something  about Dynamic Topics

### ISSUE THREAD

**Issue by sailingchen** [erlio/vernemq#118]
where is the doc  description for Dynamic Topics,  I think  some powerful like this:
1. auto subscription topic  for client .
2.  add/remove topic  api  for clientid .
3. Publish clientid,ip to $SYS topic when a client connected
Thanks.

**Comment by dergraf** [comment]
Hi there,

which docs are you looking for? We support the wildcard topics specified in the Mqtt spec.
1-3 would be additional features currently not implemented.

Cheers

**Comment by sailingchen** [comment]
Now, I use lua plugin send the clientid to redis list , and other read  redis  list get the clientid connect to vernemq , vernemq.conf must config:
allow_multiple_sessions = on

Thankyou for your reply.
