### ISSUE TITLE
Add published time into payload

### ISSUE THREAD

**Issue by hoangleanhtu** [erlio/vernemq#121]
Hello,

I’m developing messaging application that uses VerneMQ.

Subscriber must see the time that message is published from publisher.
This is the basic feature in any messaging application.

But in on_publish hook, I can’t modify payload to add published time.
on_deliver hook I can, but it’s really delivery time, not published time.

Do you have any solution for this?

Thank you very much.

**Comment by dergraf** [comment]
Hi there!

You have to use the auth_on_publish hook for changing the payload.

Returning ```{ok, NewPayload::binary()}``` is enough.

Cheers!

**Comment by hoangleanhtu** [comment]
Hi Dergraf,

It worked.

Thank you very much.
