### ISSUE TITLE
make rel error in ubuntu16.04

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#122]
Hi!
It works in ubuntu14.04;
But ubuntu16.04:

dcy@dcy-dcy:~/app/vernemq$ make rel
/home/dcy/app/vernemq/rebar3 release --overlay_vars vars.config
===> Verifying dependencies...
===> Running cuttlefish schema generator
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /home/dcy/app/vernemq/_build/default/lib
          /usr/lib/erlang/lib
          /home/dcy/app/vernemq/_build/default/rel
===> Resolved vernemq-0.12.5p2
===> Including Erts from /usr/lib/erlang
===> release successfully created!
===> Unable to copy from /home/dcy/app/vernemq/_build/default/lib/vmq_passwd/c_src/vmq_passwd to /home/dcy/app/vernemq/_build/default/rel/vernemq/bin/vmq-passwd because of {copy_failed,
                                                                                                                                                                        enoent}

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 127

**Comment by larshesel** [comment]
Thank you for the report.

Could you try with a clean build to see if you can reproduce the issue then? The above looks like it has already been compiled before (no deps fetched, and no compile output).

**Comment by larshesel** [comment]
btw - we just released vernemq-0.12.5p3 today with a number of important changes. We'll make an official announcement later.

**Comment by dcy** [comment]
I upgrade to the newest version, it works.
Don't know why it can not work before.
Maybe there is a changelog would be better.

**Comment by dcy** [comment]
In my another computer(ubuntu16.04), I try many times (make rel), The problem is always happening:
===> Unable to copy from /home/dcy/vernemq/_build/default/lib/vmq_passwd/c_src/vmq_passwd to /home/dcy/vernemq/_build/default/rel/vernemq/bin/vmq-passwd because of {copy_failed,
                                                                                                                                                                enoent}

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 127

I try in other path to git clone vernemq and "make rel", the same problem

**Comment by dcy** [comment]
I rm _build/defalut/lib/vmq_passwd and "make rel", it shows "fatal error: openssl/evp.h".
And i install libssl-dev, then it works.

**Comment by dergraf** [comment]
Great you figured it out, the error message are too cryptic unfortunately! :)
