### ISSUE TITLE
graphite configuration

### ISSUE THREAD

**Issue by janshahid** [erlio/vernemq#123]
HI,

I installed graphite using synthesize and able to see the dashboard with some system information.
I wanted to connect this graphite tool with vernemq (installed in the same aws).I updated the vernemq.conf file also.Please have a look at the below graphite configurations.

> graphite.interval = 15000
> graphite.port = 2003
> graphite.host = 172.31.12.205
> graphite.prefix = vmq
> graphite.api_key = UNDEFINED

The graphite cofigurations are 

> 172.31.12.205:2003 

But I am not able to find any vernemq statistics in graphite dashboard.Could you please help me in this?

Thank you in advance..

**Comment by dergraf** [comment]
Hi there,

Have you enabled the plugin via ```vmq-admin plugin enable -n vmq_graphite``` ?

Cheers!

**Comment by janshahid** [comment]
Thank you...Now it is working fine

**Comment by janshahid** [comment]
Hi Again,

How to reload the graphite configuration without restarting the server ?
I went through the documentation but did not find any commands to reload the configurations without restart.

**Comment by ioolkos** [comment]
Hi @janshahid ...good point.
@dergraf I think this is related to plugin load/unload we need to improve?

**Comment by janshahid** [comment]
Hi@ioolkos,

My question is ,How to reset the graphite values without restarting the server?
I found some examples from documentation but getting were unknown variable.
Please have a look at the below command

> ./vmq-admin set graphite.host=A.B.C.D 

> Result:Unknown variable: graphite.host

Currently,I want to configure these values on live server so i can't restart the server.I am checking the ways to configure these values without restarting the server
