### ISSUE TITLE
Cluster Node can not receive message from each other?

### ISSUE THREAD

**Issue by liucy2007975** [erlio/vernemq#124]
I setup three nodes ,
each node's vernemq.config file is ：
## 
## 
##   - on or off
allow_anonymous = on

## 
## 
##   - on or off
trade_consistency = on

## 
## 
##   - on or off
allow_multiple_sessions = on
queue_deliver_mode=balance

## 
## 
## 
## 
##   - an integer
max_client_id_size = 512

## 
## 
##   - text
persistent_client_expiration = 1w

## 
## 
##   - an integer
max_inflight_messages = 10000

## The maximum number of messages to hold in the queue above
##those messages that are currently in flight. Defaults to 1000. Set to 0 for
## client session can deal with message bursts. As a general rule of thumb set
##this number a bit higher than the expected message rate a single consumer is
##required to process.
## 
## 
##   - an integer
max_online_messages = 100000

## 
## 
##   - an integer
max_offline_messages = 100000

## 
## 
##   - an integer
message_size_limit = 0

## 
## 
##   - on or off
upgrade_outgoing_qos = off

## 
## 
##   - the text "infinity"
listener.max_connections = infinity

## 
## 
##   - an integer
listener.nr_of_acceptors = 1000

## 
## 
##   - an IP/port pair, e.g. 127.0.0.1:10011
listener.tcp.default = 192.168.1.101:1883

erlang.distribution.port_range.minimum=6000
erlang.distribution.port_range.maximum=7999

## 
## 
##   - an IP/port pair, e.g. 127.0.0.1:10011
listener.vmq.clustering = 0.0.0.0:44053

## 
## 
##   - text
##listener.mountpoint = on
##listener.tcp.mountpoint= test/my01

## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
##   - the path to a file
acl_file = /etc/vernemq/vmq.acl

## 
## 
##   - an integer
acl_reload_interval = 10

## 
## 
##   - the path to a file
password_file = /etc/vernemq/vmq.passwd

## 
## 
##   - an integer
password_reload_interval = 10

## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
## 
##   - an integer
sys_interval = 10

## 
## 
##   - an integer
graphite.interval = 15000

## 
## 
##   - an integer
graphite.port = 2003

## 
## 
##   - text
graphite.host = 192.168.1.101

## 
## 
## 
## 
## 
## 
##   - one of: off, file, console, both
log.console = file

## 
## 
##   - one of: debug, info, warning, error
log.console.level = error

## 
## 
##   - the path to a file
log.console.file = ./log/console.log

## 
## 
##   - the path to a file
log.error.file = ./log/error.log

## 
## 
##   - on or off
log.syslog = off

## 
## 
##   - on or off
log.crash = on

## 
## 
##   - the path to a file
log.crash.file = ./log/crash.log

## 
## 
##   - a byte size with units, e.g. 10GB
log.crash.maximum_message_size = 1MB

## 
## 
##   - a byte size with units, e.g. 10GB
log.crash.size = 500MB

## 
## 
##   - text
log.crash.rotation = $D0

## 
## 
##   - the text "current"
log.crash.rotation.keep = 5

## 
## 
##   - an integer
leveldb.maximum_memory.percent = 70

## 
## 
##   - text
nodename = VerneMQ_1@192.168.1.101

## 
## 
##   - text
distributed_cookie = vmq

## 
## 
##   - an integer
erlang.async_threads = 512

erlang.process_limit = 10000000

## 
## 
##   - an integer
erlang.max_ports = 10000000

## 
## 
## 
## erlang.schedulers.utilization_balancing = true

and I config cluster by the document:http://vernemq.com/docs/clustering/ ,http://vernemq.com/docs/clustering/communication.html

then I excute ' vmq-admin cluster status ' on each node ,they all display:
+-----------------------+-------+
|         Node          |Running|
+-----------------------+-------+
|VerneMQ_1@192.168.1.101| true  |
|VerneMQ_2@192.168.1.102| true  |
|VerneMQ_3@192.168.1.103| true  |
+-----------------------+-------+

I use two client A ,B and C  ,A connect to node 1:VerneMQ_1@192.168.1.101 B to VerneMQ_2@192.168.1.102 and C to VerneMQ_3@192.168.1.103
B and C sub topic test/#,
A public topic test/sdfs message 'xxxxx'
Then B and C can not receive any message form A
They Can Only receive message from there own node.
Am I make some mistake?

**Comment by liucy2007975** [comment]
The nodes can telnet from each others  for all the listening port  ,so  the network is ok~

**Comment by ioolkos** [comment]
The clustering port is open too? `listener.vmq.clustering = 0.0.0.0:44053`
Messages between the clustered nodes flow over these connections.

**Comment by liucy2007975** [comment]
Thank you for your reply!
I solve it by set listener.vmq.clustering = 192.168.1.101:44053 
now the cluster node can reacieve msg for each other
