### ISSUE TITLE
vmq_diversity: load Lua module

### ISSUE THREAD

**Issue by hoangleanhtu** [erlio/vernemq#125]
Hi,

Is there any way to load other Lua modules, such as https://github.com/umegaya/lua-aws?
I tried to put them in vmq_diversity but it doesn't work.

Thanks.

**Comment by dergraf** [comment]
Hi there,

wow lua-aws is quite a beast ;)

vmq_diversity uses a custom Lua interpreter implemented in Erlang. For this reason only a limited set of the 'real' Lua is supported. You'd find more here: https://github.com/rvirding/luerl/#currently-implemented-functions-in-the-libraries

From the quick look at lua-aws, it uses luasockets underneath, which for example is currently not supported. However, the lua-aws project looks very promising, and it would be great if we could support it in one form or the other, but for the moment we can't.

Best,
Andre

**Comment by hoangleanhtu** [comment]
Hi Andre,

Again, thank you very much for the prompt reply.

I develop plugin by Lua as the easiest way for me.
I understand that Erlang is still the most powerful way, so I spent more time to find out it.

Best Regards,
Tu.

**Comment by dergraf** [comment]
Cool! 

As most of the AWS calls are over HTTP you could try to use the vmq_diversity HTTP library.

**Comment by hoangleanhtu** [comment]
Yes, but it requires signing request: http://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html. It seems Luerl doesn't support HMAC.

So I'm going to use https://github.com/erlcloud/erlcloud to connect to AWS.
