### ISSUE TITLE
VerneMQ performance problem.

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#128]
Hi!
I test 30k sub connections, and VerneMQ consume 9G memory, and 36% cpu,
But the same benchmark of Emqttd, it only consume less 1G memory, and very little cpu.

[emqtt_benchmark](https://github.com/emqtt/emqtt_benchmark):
./emqtt_bench_sub -c 30000 -i 10 -t bench/%i -q 1 -h 192.168.2.82

**Comment by ioolkos** [comment]
Hi,
can you attach a console to VerneMQ and verify how many subscriptions you have by
`vmq_reg:total_subscriptions().`

**Comment by dcy** [comment]
mosquitto_sub -t \$SYS/VerneMQ@192.168.2.82/subscriptions/total -h 192.168.2.82
It shows 3000X.

By the way, 30k connections consume 9G memory is terrible and unusable.

**Comment by dergraf** [comment]
@dcy VerneMQ tunes it's internal TCP buffer sizes according to the settings in:  

    /proc/sys/net/ipv4/tcp_rmem
    /proc/sys/net/ipv4/tcp_wmem

Therefore it is possible if your buffer sizes are big that VerneMQ/Erlang reserves quite some internal buffers.

**Comment by dcy** [comment]
@dergraf Thanks. i will test later, and why consume so much cpu?

**Comment by dergraf** [comment]
We've experienced that the ```vmq_systree``` monitoring plugin, which is enabled by default, consumes quite some CPU as soon as thousands of queues exist in the system. As an experiment try to

    vmq-admin plugin disable -n vmq_systree

to see if it would make a difference if it is disabled.

**Comment by dcy** [comment]
@dergraf How much should i set the tcp_rmem and tcp_wmem?

**Comment by ioolkos** [comment]
Just want to make sure we understand it's not physical memory.
`free -m` will report what's used and free physically. It won't be 9 GB, right? 
I suspect some LevelDB memory map files counted as virtual memory, 'or something' :)

But yes, we'll have to double check the default config for LevelDB and TCP anyway.

**Comment by dcy** [comment]
I use htop, htop shows 9G.

**Comment by dcy** [comment]
I suggest you should test VerneMQ, and compare with emqttd.
VerneMQ is better, i like VerneMQ, but it seems VerneMQ's performance is unusable for now.
Hope it will be fixed later.

**Comment by ioolkos** [comment]
Sorry to hear your frustration! 

('VIRT' vs 'RES' in htop, right?) We are talking about the same thing?

**Comment by dcy** [comment]
5 line Mem shows 9.xG/15.xG in my test.
![2016-04-29-212127_919x128_scrot](https://cloud.githubusercontent.com/assets/1137238/14917294/e4801b52-0e50-11e6-9e63-aee69dbd76b7.png)

**Comment by ioolkos** [comment]
Thanks for reporting. I can "fix" the problem by setting the tcp_rmem and wmem very low, let's say 4096 4096 16384.
This is not what I want though on my machine, so maybe we should look into not doing the automatic tuning, and setting a fixed buffer size within VerneMQ. We'll see.

I can also run with much higher buffer sizes, and much higher VIRT memory then, not exhausting physical memory.

I'll need some time to find the best solution. 
Again, thank you so much for your testing so far!

**Comment by dcy** [comment]
Is htop[Mem] shows memory not the physical memory?
I have a little confusion. Does VerneMQ consume very much memory or not consume much memory?

**Comment by ioolkos** [comment]
Sure, line 5 htop shows physical memory use. 
All I'm saying is that, yes, VerneMQ can use a very low memory footprint, with small TCP buffers.
And it will be higher with higher buffers. 

Also, maybe we need to provide a way to configure buffer size manually.

**Comment by dcy** [comment]
I test in another computer today. 30k sub clients and VerneMQ in the same computer.
it did not consume 9G memory, it consume less 2G.
The result of
```
sysctl -w net.ipv4.tcp_rmem='1024 4096 16777216'
sysctl -w net.ipv4.tcp_wmem='1024 4096 16777216'
```
and
```
sysctl -w net.ipv4.tcp_rmem='4096 4096 16384'
sysctl -w net.ipv4.tcp_wmem='4096 4096 16384'
```
almost the same.

**Comment by dcy** [comment]
The same benchmark with emqttd in the same computer, it only consume less than 1G.

**Comment by ioolkos** [comment]
Same machine, different products, *differently configured*.

Instead of configuring sndbuf, recbuf and buffer (for the tcp_listen_options) manually, we take those values from the OS. (Basically the max values for tcp_rmem, and tcp_wmem respectively).

You can have 30k connections in 1GB RAM, if your want to.

**Comment by dcy** [comment]
Could you give me some tuning guide of VerneMQ or write here [VerneMO doc](https://vernemq.com/docs/)?
Thanks!

**Comment by ioolkos** [comment]
Agree we need a tuning guide.

If you want to optimise for RAM, the take away message is that you want to set `tcp_rmem` and `tcp_wmem` on your box. VerneMQ will calculate buffers from the max values there.

Note: this is not something we invented, it's the recommended way to set buffers within Erlangs TCP interface.

But it may be counter intuitive, and we're currently evaluating if we should allow sndbuf and recbuf as override config values, even if this would play against your OS settings.

**Comment by dergraf** [comment]
Hi @dcy

We added the Erlang TCP buffer size configuration option to our project backlog. We're going to release this fix soon, which would allow you to further fine tune the buffers and therefore control the overall memory consumption of VerneMQ. Please stay tuned for this fix.

Cheers,
Andre

**Comment by cabableking** [comment]
hey @dergraf , 

Was this closed? Which config can I use to manually set the buffer size ? What are the disadvantages to setting the buffer sizes to low values ? 

My vernemq machine maxes out at 10000 connections (pub) at 3.5 Gigs of memory. I feel this is really high. How do I control this ?

**Comment by dergraf** [comment]
Hi there

It's documented here http://vernemq.com/docs/misc/tuning-vernemq.html

Hope this helps
