### ISSUE TITLE
Dockerfile for VerneMQ

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#129]
In #54 @dergraf suggested a discussion on a generalized Dockerfile for VerneMQ, but I can't seem to find a follow-up on this so I thought I'd ask whether any effort has been made lately regarding this.

**Comment by dergraf** [comment]
Thanks for the follow-up @testark. I am personally quite involved with docker at the moment. So I'd be very happy to see a generalized Dockerile for VerneMQ... it's on our roadmap, but we haven't started with it.

**Comment by testark** [comment]
@dergraf thank you very much! Still regarding this, could you please tell me whether cluster joining/leaving order matters for VerneMQ (like it does, for instance, in RabbitMQ)?

**Comment by dergraf** [comment]
What ordering do you have in mind?

**Comment by ioolkos** [comment]
Takedown and startup order doesn't matter in the sense of RabbitMQ, as we don't have the same concept of disk nodes and RAM nodes.

**Comment by dergraf** [comment]
We started a public repo for VerneMQ on Docker, which is also available on the Docker hub. Please check it out! https://github.com/erlio/docker-vernemq

**Comment by dergraf** [comment]
Let's have the discussion on how to improve docker-vernemq at https://github.com/erlio/docker-vernemq
