### ISSUE TITLE
Must not accept UNSUBSCRIBE with zero topics

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#13]
>[MQTT-3.10.3-2]
>The Payload of an UNSUBSCRIBE packet MUST contain at least one Topic Filter. An UNSUBSCRIBE >packet with no payload is a protocol violation.

**Comment by dergraf** [comment]
@ioolkos please review, using iOS mqttinspector app.

**Comment by ckrey** [comment]
confirmed: fixed

**Comment by dergraf** [comment]
Thanks!
