### ISSUE TITLE
$SYS sub problem & Unable to connect (15). in mosquitto_pub

### ISSUE THREAD

**Issue by thkaw** [erlio/vernemq#130]
Hello, 
I installed vernemq on Ubuntu 14.04 by using deb download from official website.
which version is 0.12.5p4-1

and using dpkg -i to install it.

But I can sub/pub in localhost, but with other clients, it report Unable to connect (15).

Also change 
allow_anonymous = on

And
listener.tcp.default = 192.168.1.33:1883 (my client ip)

but still not working, keep report Unable to connect (15)..

And mosquitto_sub -t "$SYS/VerneMQ@127.0.0.1/#"  -d in the local didn't work either :(
had ping message but not receive any $SYS Message:
ntl@ubuntu:~$ mosquitto_sub -t "$SYS/VerneMQ@127.0.0.1/#"  -d -u ntl -P l
Received CONNACK
Received SUBACK
Subscribed (mid: 1): 0
Sending PINGREQ
Received PINGRESP

**Comment by dergraf** [comment]
Hi there,
thanks for reporting.

I had the same problem with the ```mosquitto_sub```. I think it isn't properly escaping the ```$``` sign.

    mosquitto_sub -t "\$SYS/VerneMQ@127.0.0.1/#" -d

should work.

**Comment by thkaw** [comment]
@dergraf Thanks!

And I make misunderstand for listener.tcp.default, which should setting broker address, not client.
