### ISSUE TITLE
Some VerneMQ questions

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#131]
Hi!

1. How to set client auto subscribe the topic:
I know to write a plugin, in on_register, but i don't know which api should i invoke?
I saw the code, found the vmq_req:subscribe/4, but it is difficult to invoke.
Maybe this question can be: What's the api for subscribe and publish?

1. How to get the client_id or username online status?

1. How to remote call?
Maybe it can rpc:call(Node, M, F, A), but is there an better way?
For example: i want to notify VerneMQ to publish the topic some message through Erlang or http way, not mqtt connect way

**Comment by dergraf** [comment]
Hi there,

1. we currently haven't a way to auto-subscribe a client to a topic. You can however change the subscriptions of a client in the ```auth_on_subscribe``` callback. E.g. if a client subscribes with ```a/b/c``` and QoS 0, you could change it to ```x/y/z``` and QoS 2 if you want.

2. Currently we only provide the ```vmq-admin session list``` command to list all sessions. This command is still quite limited, and will get a great rework soon.

3. Publishing a message by a VerneMQ plugin should be done using the ```vmq_reg:direct_plugin_exports``` mechanism. Please have a look at the https://github.com/erlio/vmq_systree/blob/master/src/vmq_report_systree.erl#L44-L47. As a convention we configured the {M,F,A} inside the plugin env, https://github.com/erlio/vmq_systree/blob/master/src/vmq_systree.app.src#L12 in order the plugin has no 'direct' dependency to a ```vmq_server``` module. 

I hope this helps!

Cheers

**Comment by dcy** [comment]
Thanks!
@dergraf Can i use  ```vmq_reg:subscrbe``` and ```vmq_reg:publish``` directly?

**Comment by dergraf** [comment]
You shouldn't

**Comment by dcy** [comment]
My app server want to tell VerneMQ to publish some topics some messages.
Which way is recommended? Should i use some mqtt clients to connect VerneMQ in my app server?
When my app server want to tell VerneMQ, use app server's mqtt clients to publish them to VerneMQ server, Am i right?

**Comment by larshesel** [comment]
For most uses cases what you suggest would probably be the correct choice to publish messages from withing your app using a standard MQTT client. It's simple and easy. In special cases would it be beneficial to hook straight into VerneMQ and publish something via plugins, but that gives the added complexity of having to write a custom plugin etc.

So if your use cases can be achieved by publishing messages with a normal client I would strongly recommend that.

**Comment by dcy** [comment]
I have another question:
How can the client get the server time when the client publish a msg to server?
I am developing an IM app, the reveived msg i can use plug(auth_on_publish) changed the payload, add a time field or change the time field, so the received msg has server time, but the msg which send to server can not get server time, How can i solve this problem?

**Comment by larshesel** [comment]
Hi

I'm not sure I understand your question, but it seems related to MQTT application architecture and not an issue with VerneMQ itself. Please contact us via email (info@vernemq.com) for commercial support.

Thanks

**Comment by falood** [comment]
Hi @dergraf , I have same questions with @dcy , I tried `vmq_reg:subscrbe` and it works well, why can't I use it? is there any risk?

**Comment by larshesel** [comment]
One reason that comes to mind is that those functions are internal functions and we've changed them several times over the last months. In fact, one of the pending pull requests will change them once more IIRC. In other words: It's not a public API and if you use them things may break unexpectedly

Maybe @dergraf has other reason for saying you shouldn't use them but that's my 2 cents.

**Comment by falood** [comment]
@larshesel 
Thank you for you answer.
I think it's ok, I'll use it under my own risk 🙂 
by the way, I notified that you're building HTTP API now, will you make a module with all public methods to provide same API with HTTP API?

**Comment by larshesel** [comment]
Hi @falood 

The HTTP API was just merged to Master. It's going to be in beta for a while until we're sure we've gotten it right. We're not planning on making a documented erlang API at the moment, but you can run all the vmq-admin commands directly from erlang using `clique_command:run(....)`, which is what the HTTP calls anyway (see https://github.com/erlio/vernemq/commit/59da5f9a75bf34c4c4ca0b590480ecc2e9cbb132#diff-1d067df655961dc8b3c5aafea087a4deR119)

**Comment by falood** [comment]
I think I may make it myself in my own plugin, I'm sure I can use all APIs you used in your http plugins 🙂 
for publishing message, I don't think it's a good idea to use mqtt client in my plugin, is there a similar  HTTP API do it?

**Comment by larshesel** [comment]
I'm not sure I understand your question, I'm afraid. Could we move the discussion to Slack?

**Comment by falood** [comment]
OK, I'll ping you on slack 🙂 
I think discuss here could help people who have same questions with me.
Thank you very much!

**Comment by leopucci** [comment]
@dcy have you suceeded on this? 

I was wondering if I could send messages and read responses via plugin, so when the client connects, i query him some info, and store into database. 

Any hints?

Thanks
Pucci

**Comment by dcy** [comment]
@leopucci You can send message by https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_reg.erl#L447
```
publish_direct(Topic, Payload) ->
    {_R, PubFun, _S}= vmq_reg:direct_plugin_exports(your_plugin),
    PubFun(Topic, Payload, #{qos => 1}).
```
But is is internal functio.

If you want to do something when the clinet connects, you can use plugin ```on_register```

**Comment by leopucci** [comment]
Thanks @dcy

**Comment by dcy** [comment]
@leopucci https://vernemq.com/docs/plugindevelopment/
You can use Erlang, Elixir, Lua or Webhook(HTTP).

**Comment by leopucci** [comment]
I know @dcy,  I am using lua, but in the docs I did not found the lua way of publishing messages
