### ISSUE TITLE
/etc/vmq.acl: clientID placeholder %c does not work if `allow_anonymous = on`

### ISSUE THREAD

**Issue by weitzj** [erlio/vernemq#132]
- I have `allow_anonymous = on` set in `vernemq.conf`
- My `vmq.acl` looks like:

```
pattern write clients/+/c/%c/info
pattern write clients/+/c/%c/status

user admin
topic #
```

- My clients connect with a clientId, e.g: `client1ID`, `client2ID`
- They should publish to `clients/+/client1ID/info`..., etc.
- An admin user can subscribe on `/#` and read the data

##### Current behaviour:

- Clients cannot connect and get an Authentication not Allowed error.
- e.g. for `clients/UUID/c/%c/status`

```
2016-05-03 12:38:14.843 [error] <0.409.0>@vmq_mqtt_fsm:auth_on_publish:614 can't
 auth publish [<<"unknown">>,{[],<<"client1ID">>},1,[<<"clients">>,<<"d4535b23-6b1a-464a-a2db-e46007949697">>,<<"c">>,<<"client1ID">>
,<<"status">>],<<"-1">>,true] due to [next]
```

- If I set the username (to the clientID) I can at least use the `%u` pattern 

##### Expected behaviour:

- Clients should be able to publish using their clientId event if `allow

Version: 0.12.5p4
Ubuntu: 14.04.4 (via Docker)
Kernel: Linux 0b9d4361e257 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016
x86_64 x86_64 x86_64 GNU/Linux

**Comment by dergraf** [comment]
hi there!

thanks for reporting!

Already isolated the bug, working on a fix!

**Comment by dergraf** [comment]
Hi again,

should be fixed in https://github.com/erlio/vmq_acl/commit/b619f4538aa29ebd20c5f90a2928c07dccaa0fca.

if you're building the VerneMQ release yourself, it should be enough to

    ./rebar3 upgrade vmq_acl && make rel

to upgrade vmq_acl and regenerate the release.

If you're relying on the binary package, you'd have to wait for the next patch release.

**Comment by weitzj** [comment]
Thank you

**Comment by dergraf** [comment]
I guess it is working for you. :)
