### ISSUE TITLE
vernemq failed to start within 15 seconds

### ISSUE THREAD

**Issue by liucy2007975** [erlio/vernemq#134]
I have a cluster with two nodes , after loadtest ,I stop the node, and when I use " vernemq start " to start the node ,it can not start with the message: " **vernemq failed to start within 15 seconds, see the output of 'vernemq console' for more information. If you want to wait longer, set the environment variable WAIT_FOR_ERLANG to the number of seconds to wait. **"

After that I used “vernemq console”，then show me:

15:57:25.757 [info] Application plumtree started on node 'VerneMQ_5@192.168.3.180'
15:57:25.806 [info] Application jobs started on node 'VerneMQ_5@192.168.3.180'
15:57:25.806 [info] Application asn1 started on node 'VerneMQ_5@192.168.3.180'
15:57:25.807 [info] Application public_key started on node 'VerneMQ_5@192.168.3.180'
15:57:25.839 [info] Application ssl started on node 'VerneMQ_5@192.168.3.180'
15:57:25.877 [info] Application sasl started on node 'VerneMQ_5@192.168.3.180'
15:57:25.893 [info] Application riak_sysmon started on node 'VerneMQ_5@192.168.3.180'
15:57:25.922 [info] Application os_mon started on node 'VerneMQ_5@192.168.3.180'
15:57:25.923 [info] Application cowlib started on node 'VerneMQ_5@192.168.3.180'
15:57:25.942 [info] Application ranch started on node 'VerneMQ_5@192.168.3.180'
15:57:25.972 [info] Application cowboy started on node 'VerneMQ_5@192.168.3.180'
15:57:25.991 [info] Setup running ...
15:57:25.992 [info] Directories verified. Res = ok
15:57:25.993 [info] Setup finished processing hooks (Mode=normal)...
15:57:25.993 [info] Application setup started on node 'VerneMQ_5@192.168.3.180'
15:57:26.109 [info] Starting reporters with []
15:57:26.109 [info] Application exometer_core started on node 'VerneMQ_5@192.168.3.180'
15:57:26.447 [info] Application vmq_systree started on node 'VerneMQ_5@192.168.3.180'
15:57:26.454 [info] Systree Reporter initialized; Opts: []
15:57:26.495 [info] Application vmq_passwd started on node 'VerneMQ_5@192.168.3.180'
15:57:26.523 [info] Application vmq_acl started on node 'VerneMQ_5@192.168.3.180'
16:00:33.226 [info] plumtree peer service event handler 'vmq_cluster' registered
16:00:38.979 [error] CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: {timeout,{gen_server,call,[exometer_report,{change_reporter_status,vmq_report_systree,disabled}]}} in application_master:init/4 line 133
16:00:38.982 [info] Application vmq_server exited with reason: {timeout,{gen_server,call,[exometer_report,{change_reporter_status,vmq_report_systree,disabled}]}}

I use "du -hs /var/lib/vernemq/meta/ /var/lib/vernemq/msgstore/" ，it shows:
 40M	/var/lib/vernemq/meta/
253M	/var/lib/vernemq/msgstore/
is it there have a lot of stored client & sub & offline msg that make it can't start??
or it can be start but it should take much more 15 sec.
so I use "vernemq console" agian, after wait a long time ,it start success with no error report,
and then I retry sometimes, I found many times it will report error and start failed. only one time start succssed.
when I delete the "/var/lib/vernemq/* " , it is started very fast.

so I guess if there have a lot of  client & sub & offline msg stored,the vernemq can hardly start. how to fix that? thank you!
and the "vmq-admin session list" also have problem ,when there have many sessions ,It always show:" RPC timeout... ..." can not list the sessions.

**Comment by ioolkos** [comment]
Thanks!

It's a bug we have to address quickly. I remember I have also seen it, after disabling the systree plugin and load testing.

@dergraf do you see what causes it?

**Comment by liucy2007975** [comment]
Thank you for your quick reply! wish it could be fixed later.

**Comment by larshesel** [comment]
Is related to erlio/vmq_server#18

**Comment by dergraf** [comment]
Closed due to not relevant anymore (the whole metric subsystem changed since 0.13.1). Also make sure to upgrade to the newest version 0.14.2.
