### ISSUE TITLE
VerneMQ can not start

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#135]
Hi!
I can not start VerneMQ:
```
dcy@dcy-dcy:~/vernemq/_build/default/rel/vernemq$ ./bin/vernemq console
config is OK
-config /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2016.05.05.13.51.46.config -args_file /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.05.05.13.51.46.args -vm_args /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.05.05.13.51.46.args
Exec:  /home/dcy/vernemq/_build/default/rel/vernemq/bin/../erts-7.3/bin/erlexec -boot /home/dcy/vernemq/_build/default/rel/vernemq/bin/../releases/0.12.5p3/vernemq               -config /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2016.05.05.13.51.46.config -args_file /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.05.05.13.51.46.args -vm_args /home/dcy/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.05.05.13.51.46.args              -pa /home/dcy/vernemq/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console
Root: /home/dcy/vernemq/_build/default/rel/vernemq/bin/..
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:64] [kernel-poll:true]

[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,plugin_not_found}},{gen_server,call,[vmq_plugin_mgr,{enable_module_plugin,change_config,vmq_config,change_config,1},infinity]}}}},{vmq_server_app,start,[normal,[]]}}}"}

Crash dump is being written to: /erl_crash.dump...Kernel pid terminated (application_controller) ({application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,plugin_not_found}},{gen_server,call,[vmq_p

```
Then i  ```rm -rf data```, it also can not start.

**Comment by dcy** [comment]
```make rel``` can start.

**Comment by larshesel** [comment]
Hi, in the error above there's a snippet: `{stop,plugin_not_found}` which indicates that a plugin cannot be found upon startup.

In normal circumstances this should not happen, but if a new/custom plugin was enabled and the code afterwards removed and VerneMQ then restarted, you would see this error. Could this be the case for you?

We should probably change this so the server can start without the plugin, but instead logs it to the log files.

**Comment by dcy** [comment]
Yes, it is the plugin.
But why i ```rm -rf data```, it also can not start.

**Comment by dcy** [comment]
I agree that ```We should probably change this so the server can start without the plugin, but instead logs it to the log files.```
Because now it can not start, only ```make rel``` again.

**Comment by larshesel** [comment]
Plugins are stored in the `lib/vmq_plugin.conf`file and not in the `data` directory, which explains why deleting the data directory doesn't have any effect on the issue.

**Comment by dcy** [comment]
Thanks!

**Comment by larshesel** [comment]
BTW - you can find the documentation about the `vmq_plugin.conf` file here: https://vernemq.com/docs/plugindevelopment/

**Comment by dcy** [comment]
Hi!
It happen at another situation.
I change the rebar.config of my plugin from
```
{erl_opts, [debug_info]}.
{deps, [
		{vmq_commons, {git, "git://github.com/erlio/vmq_commons.git"}}
	   ]}.
```
to
```
{erl_opts, [debug_info,
			{parse_transform, lager_transform}
		   ]}.
{deps, [
		{vmq_commons, {git, "git://github.com/erlio/vmq_commons.git"}},
		{lager, {git, "https://github.com/basho/lager"}}
	   ]}.

```
And ```rebar3 compile```, then VerneMQ can not start:
```
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,plugin_not_found}},{gen_server,call,[vmq_plugin_mgr,{enable_module_plugin,change_config,vmq_config,change_config,1},infinity]}}}},{vmq_server_app,start,[normal,[]]}}}"}

Crash dump is being written to: /erl_crash.dump...Kernel pid terminated (application_controller) ({application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{bad_return_value,{stop,plugin_not_found}},{gen_server,call,[vmq_p

```

**Comment by larshesel** [comment]
This seem to be because a plugin you have enabled can no longer be found. This can be seen from the `{stop,plugin_not_found}` in the error message.

**Comment by dcy** [comment]
The plugin and VerneMQ are in the same path, I just add lager to plugin's rebar.config, and compile, then i can not start VerneMQ.

**Comment by larshesel** [comment]
To be thorough, I created my own plugin which contains the two dependencies you use as well (`vmq_commons` and `lager`) and I was able to enable the plugin and restart vernemq with no problems. So `lager` as a plugin dependency does not seem to be the single cause of ot being able to start VerneMQ,

Could it be that you have compiled it with another version of rebar (rebar/rebar3) as when you enabled the plugin the first time? The beam files are written to a different location depending on which rebar you use. I think this is a weak point in our documentation and we should describe this better. On a sidenote, I would recommend using rebar3 (rebar has recently been deprecated).

If VerneMQ fails to start, could you please show us a your `vmq_plugin.conf` file as well as the location of your plugin and a `ls -1` of the contents of your plugin directory?

**Comment by dcy** [comment]
Not confirm this issue.
