### ISSUE TITLE
Bug: vernemq publishes LastWill on graceful disconnect

### ISSUE THREAD

**Issue by weitzj** [erlio/vernemq#138]
Hi,

### Current behaviour:

- vernemq publishes a LastWill, even if the client gracefully disconnected from the broker.

### Expected behaviour:

- vernemq should only publish the Last Will Testament, iff the client disconnected ungracefully.

##### See

http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament
http://www.ibm.com/support/knowledgecenter/#!/SSFKSJ_7.1.0/com.ibm.mq.doc/tt60360_.htm

### Example:

My clients publish to many topics, whereas the status topic is like the following:

`clients/UUID/c/CLIENT_ID/status`

Status can be in the following states:

- `1`: connected
- `0`: disconnected gracefully
- `-1`:  disconnected ungracefully (Last Will Testament)

Using this `status` topic, my server watchdog can clean up after all clients with status == `-1`.
But what happens in my case:

- Clients publish a `status = 0` and gracefully disconnects
- Watchdog sees `status = 0` of client
- VerneMQ publishes `status  = -1`  on behalf of the client
- Watchdog sees `status = -1`

So the last 2 steps should only happen, if the client disconnected ungracefully.

### System Specs:

- Version: https://github.com/erlio/vernemq/commit/13ee8085365f34c94eb77ab5702b544b4e48ba98
- + Upgraded vmq_acl plugin to https://github.com/erlio/vmq_acl/commit/b619f4538aa29ebd20c5f90a2928c07dccaa0fca
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
Kernel: 4.2.0-35-generic #40~14.04.1-Ubuntu SMP \
 Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ioolkos** [comment]
Jep, Server must *not* deliver a Will Message, if client has sent an MQTT DISCONNECT before closing.
Thanks, Jan!

**Comment by larshesel** [comment]
Hi, we've just merged a fix for this to the master branch of the `vmq_server` repo. If you're building VerneMQ from source you can do a `rebar3 upgrade vmq_server` and then build as normal (`make rel`). If not the fix will be included in our next release.

Thanks for reporting and making VerneMQ better!

**Comment by weitzj** [comment]
Thank you! My Earlang foo is... Non exitent
