### ISSUE TITLE
Feature request: Allow regex in vmq.acl

### ISSUE THREAD

**Issue by weitzj** [erlio/vernemq#139]
I do not know if this is feasible to implement:

Right now my clients publish to:
- `pattern write clients/+/c/%u/status`

It would be really nice, if I could harden this ACL by specifying the behaviour of the plus  `+` placeholder.
In my use-case this would be a UUID, e.g:

- `pattern write clients/123e4567-e89b-12d3-a456-426655440000/c/%u/status`

But I have many many UUIDs, so it would be nice to define a regex, e.g.:

- `pattern write clients/[\w]{8}(-[\w]{4}){3}-[\w]{12}/c/%u/status`

or 

- `pattern write clients/[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12}/c/%u/status`

There is probably a way if I depend on a database, but I am unsure what happens if a thundering herd of clients tries to connect to the broker.

Maybe you have another idea. 

Thank you for this great project.

**Comment by ioolkos** [comment]
Thanks for your input! 
Calling @dergraf for an opinion here.

**Comment by dergraf** [comment]
Would it be still interesting if the regex would match the whole topic instead of just the + wildcards? 

Have you thought about patterns with multiple wildcards e.g. +/+/+ ?

**Comment by weitzj** [comment]
- Yes of course. That would mean even more freedom in how to construct the acls.

- Some other pattern which would a nice to have is

pattern write clients/[\w]{8}(-[\w]{4}){3}-[\w]{12}/c/+/status
pattern write clients/[\w]{8}(-[\w]{4}){3}-[\w]{12}/c/%c/status

Whereas the  plus should validate the Format of the client Ids.


So what I am trying to solve is:

- I want to 'keep out' rogue clients using my broker and listening to published messages.
- I cannot use client certificates. There is an unknown number of devices connecting to the broker. I cannot create a certificate for each device, and using the same certificate on every device is a security risk for me.

So:

- All Clients communicate with an API-Server to get a shared UUID which they can use to communicate to each other.
- Using this uuid they connect to the broker.
- The API server is hardly rate limited and uses authentication. So it is 'tough' to find a good UUID by scripting
- UUIDs get vended every few hours

So a roughe client might still be able to communicate with the broker, but is 'alone'  in the sense that finding a good UUID is hard.

Once in a while a server watchdog comes along and cleans up old messages from the broker for UUIDs which cannot be found in the database.

Background:

I actually did the UUId validation against a MySQL database using mosquitto. But it was just too slow. Maybe VerneMQ's connection pooling helps here

**Comment by weitzj** [comment]
So I guess I could do a lot of this with the lua plugin.

But maybe Erlang's pattern matching is of great benefit here?!

**Comment by ioolkos** [comment]
It would certainly be interesting to see if Lua can provide the needed performance too.

**Comment by weitzj** [comment]
So I will close this for now and check out Lua.

Thanks

**Comment by ioolkos** [comment]
Thanks, don't hesitate to let us know if you run into issues with the Lua plugin.

Also, I think we're going to have more discussions on your ideas!
