### ISSUE TITLE
Must not match $ Topic Names with Topic Filters starting with wildcards

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#14]
>[MQTT-4.7.2-1]
>The Server MUST NOT match Topic Filters starting with a wildcard character (# or +) with Topic Names >beginning with a $ character.

**Comment by ckrey** [comment]
not fixed

subscription to '#' still subscribes to $SYS/#

**Comment by dergraf** [comment]
fixed in newest vmq_server

**Comment by ckrey** [comment]
confirmed: fixed

**Comment by dergraf** [comment]
Thanks!
