### ISSUE TITLE
Question : MQTT Bridge 

### ISSUE THREAD

**Issue by taemin77** [erlio/vernemq#140]
Hi, 
I have a question about Bridge config of VerneMQ.
I did bridge functionality tests with two VerneMQ brokers.
The goal of test is to share only a topic[/path] between two brokers.

-------------------------------------------------------------
case 1:
A broker config : none
B broker config :
bridge.tcp.br0 = 192.168.1.12:1883
bridge.tcp.br0.cleansession = on
bridge.tcp.br0.client_id = auto
bridge.tcp.br0.keepalive_interval = 60
bridge.tcp.br0.username = vernemq1
bridge.tcp.br0.password = password
bridge.tcp.br0.restart_timeout = 10
bridge.tcp.br0.try_private = off
**bridge.tcp.br0.topic.1 = /path both**
-------------------------------------------------------------
case 2:
A broker config :
bridge.tcp.br0 = 192.168.1.11:1883
bridge.tcp.br0.cleansession = on
bridge.tcp.br0.client_id = auto
bridge.tcp.br0.keepalive_interval = 60
bridge.tcp.br0.username = vernemq1
bridge.tcp.br0.password = password
bridge.tcp.br0.restart_timeout = 10
bridge.tcp.br0.try_private = off
**bridge.tcp.br0.topic.1 = /path in**

B broker VerneMQ config :
bridge.tcp.br0 = 192.168.1.12:1883
bridge.tcp.br0.cleansession = on
bridge.tcp.br0.client_id = auto
bridge.tcp.br0.keepalive_interval = 60
bridge.tcp.br0.username = vernemq2
bridge.tcp.br0.password = password
bridge.tcp.br0.restart_timeout = 10
bridge.tcp.br0.try_private = off
**bridge.tcp.br0.topic.1 = /path in**
-------------------------------------------------------------

the result is that if A broker get a publish message, A broker send the message to B broker, and B broker send the message to A broker again, and ping pong ...

-------------------------------------------------------------
case 3:
A broker config : none
B broker config :
bridge.tcp.br0 = 192.168.1.12:1883
bridge.tcp.br0.cleansession = on
bridge.tcp.br0.client_id = auto
bridge.tcp.br0.keepalive_interval = 60
bridge.tcp.br0.username = vernemq1
bridge.tcp.br0.password = password
bridge.tcp.br0.restart_timeout = 10
bridge.tcp.br0.try_private = off
**bridge.tcp.br0.topic.1 = /path in**
-------------------------------------------------------------
case 3 works well.
if A broker get a publish message, A broker send the message to B broker and End.
but I want when B broker also get a publish message, B broker send the message to A broker too.
Could you check this?

**Comment by ioolkos** [comment]
Thanks!
You only need to configure and enable the plugin on one broker.
You'll want to use "both" as a direction (which is just "in" and "out").

But I have the suspicion that one of the last commits to vmq_commons broke the "out" path. 
Hold on, we'll look into it.

**Comment by taemin77** [comment]
case 4:
A broker plugin : disable
A broker config : none

B broker plugin : enable                 
B broker config :
bridge.tcp.br0.topic.1 = /inside in
bridge.tcp.br0.topic.2 = /outside out
bridge.tcp.br0.topic.3 = /bothside both

test 1.
 If A broker get a message, A broker send the message to B broker. and B broker get the message well. done
test 2.
 If B broker get a message, B broker send the message to A broker. and A broker get the message well. done
test 3.
 If B broker get a message, B broker send the message to A broker. and A broker get the message. and A broker send the message to B broker again.
 If A broker get a message, A broker send the message to B broker. and B broker get the message. and B broker send the message to A broker again.

**Comment by taemin77** [comment]
Hi,
Can you let me know this is bug? or I set wrong config?
If bug, when is this fixed?

**Comment by ioolkos** [comment]
Apologies for my delay in answering.

For the bridge loop in 0.12.4, I'm afraid there won't be a backfix. (@dergraf what is your take on this?)

For the current build there seems to be the error I mentioned above (with the 'out' path). This will be fixed.

**Comment by taemin77** [comment]
Thank for reply.
I looking forward to fix it well.

**Comment by taemin77** [comment]
Could I know when I download the updated version?
I'd like to know the expected date.

**Comment by ioolkos** [comment]
@taemin77 thanks for your reminder :)
I'll take another try at analysing and fixing this tomorrow.

**Comment by ioolkos** [comment]
Fixed the internal interface, but not yet loop prevention. @dergraf: can/will be add loop prevention at all?

**Comment by dergraf** [comment]
The question is how to do it... let's discuss it.

**Comment by hbahn** [comment]
Hi all,  (I am a Coworker of @taemin77)
Is there any update for this issue?
Thanks in advance.

**Comment by ioolkos** [comment]
Hi, thanks for getting back! 
just to make sure: Is your open problem the looping?
Do you have a way to avoid loops by your architecture, or use the remapping prefixes as a fix?

The other bug should be fixed, if you build the current release yourself, run `./rebar3 upgrade vmq_bridge` after building VerneMQ.

**Comment by larshesel** [comment]
Closing this for now  due to inactivity - please feel free to re-open. I've added the task of looking into MQTT bridge loop detection into our backlog.
