### ISSUE TITLE
Lua Scripting with MysqlDB

### ISSUE THREAD

**Issue by taemin77** [erlio/vernemq#142]
Hi,
I developing VerneMQ plugin in Erlang.
I did a connection test with mongoDB. It works well.
But I couldn't connect with mysqlDB because of timetamp error.
It seems to not get timestamp data.

2016-05-17 11:27:12.777 [error] <0.256.0>@vmq_diversity_script:init:85 can't load script 
"/home/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/priv/../scripts/init.lua" due to 
{throw,{undef,[{erlang,timestamp,[],[]},{emysql_conn,now_seconds,0,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/emysql/src/emysql_conn.erl"},{line,337}]},
                                    {emysql_conn,open_connection,1,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/emysql/src/emysql_conn.erl"},{line,208}]},
                                   {emysql_conn,open_connections,1,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/emysql/src/emysql_conn.erl"},{line,170}]},
                                                     {emysql,add_pool,1,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/emysql/src/emysql.erl"},{line,311}]}
                 ,{vmq_diversity_sup,start_all_pools,2,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/src/vm_diversity_sup.erl"},{line,71}]},
                 {vmq_diversity_mysql,ensure_pool,2,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/src/vmq_diversity_mysql.erl"},{line,93}]},
                                          {luerl_emul,functioncall,4,[{file,"/home/vernemq/vmq_diversity/_build/default/lib/luerl/src/luerl_emul.erl"},{line,838}]}]}}

**Comment by dergraf** [comment]
Hi there,

which Erlang version are you using?

Cheers,
Andre

**Comment by taemin77** [comment]
-bash-4.2$ ./rebar3 version
rebar 3.0.0-beta.4+build.3362.refb47839e on Erlang/OTP 18 Erts 7.3

**Comment by dergraf** [comment]
Are you using the packaged VerneMQ release, or are you building it yourself. It looks like vmq_diversity is compiled with a different version than VerneMQ.

**Comment by taemin77** [comment]
Below commands are all for I set
---------------------------------------------------
> wget http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
> rpm -Uvh erlang-solutions-1.0-1.noarch.rpm
> rpm --import http://packages.erlang-solutions.com/rpm/erlang_solutions.asc
> rpm -Uvh ./wxBase-2.8.12-20.el7.x86_64.rpm
> rpm -Uvh ./wxGTK-2.8.12-20.el7.x86_64.rpm
> rpm -Uvh ./wxGTK-gl-2.8.12-20.el7.x86_64.rpm
> rpm -Uvh ./unixODBC-2.3.1-11.el7.x86_64.rpm
> rpm -Uvh ./esl-erlang_18.3-1-centos-7_amd64.rpm
> git clone git://github.com/erlio/vmq_diversity && cd vmq_diversity
> rebar3 compile
> /usr/sbin/vmq-admin plugin enable --name=vmq_diversity --path=/home/vernemq/vmq_diversity/_build/default/
>vi vmq_diversity/scripts/init.lua 
------------------  init.lua  ---------------------
config = {
    pool_id = "test_id",
    size = 20,
    user = "userid",
    password = "abcd",
    host = "127.0.0.1",
    port = 3305,
    database = "databaseID",
    encoding = "UTF-8"
}
mysql.ensure_pool(config)
--------------------------------------------------------

Is there something wrong?

**Comment by dergraf** [comment]
Download and install Erlang 17.5 instead of 18.3 from https://www.erlang.org/downloads/17.5
then recompile vmq_diversity, and try again.

**Comment by taemin77** [comment]
Thank! :)
It takes two days to find the cause.
