### ISSUE TITLE
Unable to receive offline messages

### ISSUE THREAD

**Issue by dreson4** [erlio/vernemq#143]
I have built vernemq on Ubuntu and so far everything is running just fine, I can send a receive messages.
My problem is I can't receive offline messages.

I connect using a Java client with the same client id, clean session set to false,  I have tried subscribing and publishing messages with QoS 1 and 2 both failed. 

If I send a message when a client is online, it works. But if i turn off that client, send couple of messages then connect the client and subscribe again to the same topics, the client gets connected but doesn't receive anything. Is there any extra configurations needed to enable offline messaging?

**Comment by ioolkos** [comment]
Hi @dreson4 
You need to subscribe with QoS 1 or 2 also.

To send messages to the offline client, you then have to need another ClientID. (which is probably what you do, just want to make sure).

**Comment by dreson4** [comment]
Thanks, I see the problem is a bug in the client that I'm using, I have tried with a different client now and It works.
