### ISSUE TITLE
How to publish the payload to another topic in "auth_on_publish"?

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#144]
Hi!
I write a plugin , i want to publish the payload to another topic too in ```auth_on_publish```.
How can i do this? Is there a method or api?

**Comment by dcy** [comment]
Can anyone help me with this?

**Comment by dergraf** [comment]
You can use so called msg-modifiers in auth_on_publish for that. Seethe type specs in http://vernemq.com/docs/plugindevelopment/publshflow.html 

E.g returning `{ok, [{topic, [<<"my">>, <<"new">>, <"topic">>]}]}.` will publish the message to `my/new/topic` instead of the on used by the client. 

Hope this helps.

**Comment by dcy** [comment]
Thanks, I want to publish the message to the new topic too, not only publish to the new tipic.
How can i do it?

**Comment by larshesel** [comment]
Hi @dcy I think this may be what you're looking for: https://github.com/erlio/vernemq/issues/62#issuecomment-152671584

But please note the disclaimer: This is not (yet) a public/documented functionality, so it is subject to change.

**Comment by dcy** [comment]
Thanks!
By the way, could you offer an api to get the user client online status?

**Comment by larshesel** [comment]
That's not a feature that's planned at the moment, but you should be able to build something yourself using retained messages / last will testament.

**Comment by dcy** [comment]
@larshesel Can i change qos=1 when i use ```PublishFun(Topic, BinaryPayload)```?

**Comment by larshesel** [comment]
You can do something like this:

```
{_R, P, _S} = vmq_reg:direct_plugin_exports(MYPLUGIN),
P([<<"Topic">>], <<"msg">>, #{qos => 2 }).
```

But again, please be aware that these functions are subject to change and cannot be considered stable.

**Comment by dcy** [comment]
@larshesel Could you offer me an api to get user clinet status? I want to do different things for online and offline?

**Comment by larshesel** [comment]
We will be happy to provide commercial support for such use cases. Please contact us on info@vernemq.com. Thanks!
