### ISSUE TITLE
logging: should have proper error message on protocol errors

### ISSUE THREAD

**Issue by aep** [erlio/vernemq#145]
when a clients gets disconnected because of invalid mqtt headers, verne should log something in a way that let's us understand the reason.

**Comment by ioolkos** [comment]
Absolutely. 
We'll take this as a +1 and motivation on adding detailled DEBUG logging. 
Thanks @aep!

**Comment by ioolkos** [comment]
As a preliminary info: Currently the parser makes the following errors explicit with debug logging enabled.
```
cant_parse_fixed_header
unknown_protocol_magic
invalid_rest_of_binary
cant_parse_variable_header
cant_validate_last_will_topic
cant_parse_username
username_flag_not_set
cant_parse_password
no_topic_provided
cant_parse_topics
```
