### ISSUE TITLE
OS X file limit problem

### ISSUE THREAD

**Issue by TangMonk** [erlio/vernemq#148]
I following [documentation](https://vernemq.com/docs/misc/change-open-file-limits.html) for tune file limit, I run command `launchctl limit`, show following:

```
	cpu         unlimited      unlimited
	filesize    unlimited      unlimited
	data        unlimited      unlimited
	stack       8388608        67104768
	core        0              unlimited
	rss         unlimited      unlimited
	memlock     unlimited      unlimited
	maxproc     709            1064
	maxfiles    256            unlimited
```

seems my soft and hard limit is 256 and unlimited, Then I create a file `/etc/launchd.conf `, and paste `limit maxfiles 16384 32768` to the file, and restart my computer.

then run `launchctl limit`, show same limit, not changed.

then I run `vernemq start`, warring again:

```
$ vernemq start
!!!!
!!!! WARNING: ulimit -n is 4864; 65536 is the recommended minimum.
!!!!
```

In OS X 10.10

**Comment by ioolkos** [comment]
Aha, seems Apple changed this with Yosemite, we need to update our doc then. 
Have a look here:
http://docs.basho.com/riak/kv/2.1.4/using/performance/open-files-limit/#adjusting-open-file-limits-in-yosemite

Thanks, @TangMonk !

**Comment by TangMonk** [comment]
Thanks!
