### ISSUE TITLE
How to use graphite plugin?

### ISSUE THREAD

**Issue by TangMonk** [erlio/vernemq#149]
In vernemq.conf : 

```
graphite.interval = 15000

graphite.port = 2003

graphite.host = localhost
```

I try to visit localhost:2003, but not works.

**Comment by ioolkos** [comment]
2003 is just the port here, where VerneMQ will publish the metrics data to Graphite. What Graphite does with it, is then up to Graphite and Graphite configuration. (ie relay it to Grafana, or plot in its own webview etc)

Also, the vmq_graphite plugin still has to be started manually, even if the basic config is done in the `vernemq.conf`file.

**Comment by TangMonk** [comment]
I am sorry, I misunderstand vernemq provide a UI interface for me

**Comment by larshesel** [comment]
Hi @TangMonk I suppose you got graphite/graphite plugin running, otherwise let us and reopen this issue or create a new one. Thanks.
