### ISSUE TITLE
Must not accept zero byte Client ID with clean session NO

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#15]
>[MQTT-3.1.3-8]
>If the Client supplies a zero-byte ClientId with CleanSession set to 0, the Server MUST respond to the >CONNECT Packet with a CONNACK return code 0x02 (Identifier rejected) and then close the Network >Connection.
>[MQTT-3.1.3-9]
>If the Server rejects the ClientId it MUST respond to the CONNECT Packet with a CONNACK return >code 0x02 (Identifier rejected) and then close the Network Connection.

**Comment by dergraf** [comment]
fixed in erlio/vmq_server

**Comment by dergraf** [comment]
@ioolkos please review, using iOS mqttinspector app.

**Comment by ckrey** [comment]
confirmed: fixed

**Comment by dergraf** [comment]
Thanks
