### ISSUE TITLE
Can't add syn to plugin.

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#152]
I want to send something to another node in my plugin, instease of use ```gen_server:cast({PidName, Node}```, I use [syn](https://github.com/ostinelli/syn)
My plugin's app.src:
```
  {applications,
   [kernel,
    stdlib,
	hackney,
	syn
   ]},
```
When add [syn](https://github.com/ostinelli/syn), start vernemq will be:
```
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{shutdown,{failed_to_start_child,vmq_config,{{{badmatch,{error,{mnesia,{\"no such file or directory\",\"mnesia.app\"}}}},[{vmq_plugin_mgr,start_plugin,1,[{file,\"/home/dcy/vernemq/_build/default/lib/vmq_plugin/src/vmq_plugin_mgr.erl\"},{line,492}]},{vmq_plugin_mgr,start_plugins,1,[{file,\"/home/dcy/vernemq/_build/default/lib/vmq_plugin/src/vmq_plugin_mgr.erl\"},{line,471}]},{vmq_plugin_mgr,load_plugins,2,[{file,\"/home/dcy/vernemq/_build/default/lib/vmq_plugin/src/vmq_plugin_mgr.erl\"},{line,410}]},{vmq_plugin_mgr,handle_info,2,[{file,\"/home/dcy/vernemq/_build/default/lib/vmq_plugin/src/vmq_plugin_mgr.erl\"},{line,242}]},{gen_server,try_dispatch,4,[{file,\"gen_server.erl\"},{line,615}]},{gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,681}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]},{gen_server,call,[vmq_plugin_mgr,{enable_module_plugin,change_config,vmq_config,change_config,1},infinity]}}}},{vmq_server_app,start,[normal,[]]}}}"}
```
It seem's something about Mnesia.

**Comment by ioolkos** [comment]
What happens if you add 'mnesia' to the app.src to the 'applications' tuple?

**Comment by dcy** [comment]
Add ```mnesia``` is the same.
```./bin/vernemq console``` and input ```applicaion:start(mnesia)```:
```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:64] [kernel-poll:true]

Eshell V7.3  (abort with ^G)
(VerneMQ@127.0.0.1)1> application:start(mnesia).
{error,{"no such file or directory","mnesia.app"}}
```

**Comment by ioolkos** [comment]
Jep, this is with a stock VerneMQ release, where we exclude what we don't need (like Mnesia).

You could add Mnesia to the vernemq `rebar.config` or copy mnesia and deps into the `_build/default/libs` directory.

Both is a bit cumbersome. Apologies for not having an elegant way to do this right now.

**Comment by dcy** [comment]
@ioolkos It is a little difficult to maintain.

**Comment by dcy** [comment]
@ioolkos How can i add Mnesia to rebar.config, Mnesia is not a individual dep or lib.

**Comment by ioolkos** [comment]
Apologies... yes, that was complete nonsense information from me :)

What you could do is add mnesia to the vmq_server.app.src file in the applications tuple (and rebuild the release).

A quick general remark: we deliberately choose to not use Mnesia for any cluster related mechanism. Not sure what you are building, do you add a layer of clustering to the plugins themselves?

**Comment by dcy** [comment]
[syn](https://github.com/ostinelli/syn) use Mnesia.
if there is no convinient way I will change to ```gproc```.
