### ISSUE TITLE
How to add custom config?

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#153]
Hi!
In my plugin, i want to add my custom config, not macro. Something like another node name or ip.
Because plugin has not ```sys.config``` to define the config.
How to add custom config in vernemq or plugin?

**Comment by ioolkos** [comment]
@dergraf @larshesel any takes on this? wasn't there some discussion about this lately?

**Comment by ioolkos** [comment]
Adding to the application environment, by adding to the app.src file is probably the simplest and fastest way right now.

**Comment by ioolkos** [comment]
There is the possibility to have an `advanced.config` in `vernemq/etc` which could be used for application/plugin configs. Can you elaborate on this @dergraf ?

**Comment by dergraf** [comment]
Yes, add an `advanced.config` file next to your `vernemq.conf` file (same folder eg. `/etc/vernemq`). This config file has the form of ```[{myapp, [{key, value}]}].``` 

Once your plugin is started you can access your config value via. `application:get_env(myapp, key).`.

Hope this helps.

**Comment by dcy** [comment]
@ioolkos @dergraf I tried, it works for ```advanced.config```.
Maybe should add something about ```advanced.config``` to http://vernemq.com/docs/plugindevelopment/

**Comment by ioolkos** [comment]
@dcy ok, great. Thanks for the doc suggestion, we only recenctly realized that the advanced config is useful for plugins too.
