### ISSUE TITLE
Publishing an empty retained message

### ISSUE THREAD

**Issue by mtappler** [erlio/vernemq#156]
I have noticed that the VerneMQ-broker does not forward PUBLISH-packets with empty message and retain set to 1 to subscribed clients.  According to the MQTT-specfication, this would be an error. See also: 

> [MQTT-3.3.1-10]  A PUBLISH Packet with a RETAIN flag set to 1 and a payload containing zero bytes will be processed as normal by the Server and sent to Clients with a subscription matching the topic name. Additionally any existing retained message with the same topic name MUST be removed and any future subscribers for the topic will not receive a retained message.

**Comment by ioolkos** [comment]
Thanks for reporting this! with the latest release, I understand.
We'll confirm & fix this.

**Comment by mtappler** [comment]
Sorry, forgot about that. I actually tested it with the release before the latest, i.e. 0.12.5p4, on Ubuntu.

**Comment by larshesel** [comment]
Hi @mtappler thanks for reporting these issues. There's no a fix waiting review and merging in PR erlio/vmq_server#72.
