### ISSUE TITLE
Session management CLI/API

### ISSUE THREAD

**Issue by manifest** [erlio/vernemq#158]
It would be really interested to be able to:
- disconnect the particular client
- unsubscribe a client from the particular topic

programmatically (by external request and/or within a plugin) and using `vmq-admin`.

**Comment by ioolkos** [comment]
Thanks for your input, @manifest! Agree on that.

We'll see if, how & when we can do something about it ;)

**Comment by manifest** [comment]
I just hoped there is some work around on those issues :-)
I'm also wondering, is there a better way to maintain a session state then putting it into an ets table and controlling it from hooks `{auth_}on_register` and `on_client_{offline,gone}`?

**Comment by ioolkos** [comment]
@dergraf we talked about session management lately, for a round of adaptations for a Web GUI.

Would those adaptations address the needs above?

**Comment by manifest** [comment]
Looks like there is a way to disconnect a user by its id. Not efficient one but better then nothing :-)
```erlang
f(Find), Find =
	fun(Id) ->
		hd(vmq_mqtt_fsm:list_sessions(
			[pid, client_id],
			fun(_, St, Acc) ->
				case proplists:get_value(client_id, St) of 
					Id -> [proplists:get_value(pid, St)|Acc];
					_  -> Acc
				end
			end,
			[]))
	end.

Find(<<"i1">>) ! disconnect.
```

**Comment by ioolkos** [comment]
Hehe, okay :)
hope this works for you short term, with the current `list_session` functionality, it just can't be efficient... 

@dergraf  any comments?

**Comment by larshesel** [comment]
Since this issue was opened it's now possible to use `vmq-admin session` to disconnect clients by client-id. There's also an API for it: https://github.com/erlio/vernemq_dev/blob/master/src/vernemq_dev_api.erl#L27. Administratively unsubscribing clients is still not supported.

Closing this for now.

**Comment by manifest** [comment]
@larshesel Is it possible to get a current status of client's connection: conected / disconected. It's currently the main hindrance that stopping us from using VerneMQ.

**Comment by larshesel** [comment]
You can use the `vmq-admin session` to check if there is a connected client or not.

**Comment by manifest** [comment]
I meant using an API. We need it in our application. Some efficient way to know status (connected / disconnected) for the particular client.

**Comment by larshesel** [comment]
One way would be to use the HTTP API which exposes the CLI commands. There isn't an official Erlang API for it, but it would be possible to build a plugin which keeps track of this.

May I ask how this API looks for the broker you went with?

**Comment by manifest** [comment]
We haven't decided yet on which broker to use. emqttd for instance has REST API and subtopic under $SYS for such events.

http://emqtt.io/docs/v2/rest.html#clients
https://github.com/emqtt/emqttd/wiki/$SYS-Topics

**Comment by ioolkos** [comment]
This is the closest to an API call we can do right now out of the box. 
```
➜  ~ curl "http://4wHGbWVRE2fECxZDOz3RgY87Fz3SI@localhost:8888/api/v1/session/show/?--client_id=mosqsub/14524-capo&--is_online"
{"table":[{"is_online":true}],"type":"table"}%  
```
A presence service could be done as a plugin.
