### ISSUE TITLE
ACL file example

### ISSUE THREAD

**Issue by Koen76** [erlio/vernemq#160]
Hi,

Can someone give me an example of an ACL file with multiple topic on which different users are able to subscribe, some allowed to publish and some can do both?

The documentation on the website doesn't give me enough info.

Thanks,
Koen

**Comment by dergraf** [comment]
Hi there,

thanks for your question.
It's actually pretty simple:

    # ACL for user 'john'
    user john
    topic foo
    topic read bar
    topic write all

    # ACL for user 'jane'
    user jane
    topic bar
    topic read foo
    topic write all

User `john` is allowed to publish & subscribe to topic `foo`.
User `john` is allowed to subscribe to topic `bar`.
User `john` is allowed to publish to topic `all`.

User `jane` is allowed to publish & subscribe to topic `bar`.
User `jane` is allowed to subscribe to topic `foo`.
User `jane` is allowed to publish to topic `all`.

**Comment by larshesel** [comment]
Added a simple ACL example to our docs, see: http://vernemq.com/docs/configuration/authorization.html.

**Comment by dergraf** [comment]
@YahiaZZ it looks like you've copy-pasted too much whitespace... at least your comment shows a space character before `topic bar`.

**Comment by YahiaZZ** [comment]
Thank you dergraf for your quick answer
Yes, it's working now
By the way where can I autorize publish I have this error:
vmq_mqtt_fsm:auth_on_publish:662 can't auth publish ... due to chain_exhausted

Thanks

**Comment by larshesel** [comment]
Hi, `chain_exhausted`  when publishing means that no plugin was able to authorize the topic published to. In your case this means that either the ACL or the topic published to by the client is incorrect.

**Comment by YahiaZZ** [comment]
Thank you @larshesel for your answer.
I'm new to VerneQM and I not find a simple scenario to test with, could you please put a useful link other than the official one
Thanks

**Comment by YahiaZZ** [comment]
When I execute "vmq-admin plugin show", it returns:
![image](https://user-images.githubusercontent.com/13751183/38996056-40b9321e-43e2-11e8-9208-1a618c1f3e71.png)

**Comment by larshesel** [comment]
What's in your ACL file and what's the topic you're publishing to?

**Comment by YahiaZZ** [comment]
In ACL file, I have:
user test
topic World
topic write all

and I want to publish in World

**Comment by YahiaZZ** [comment]
Hi @larshesel 
I set `plugins.vmq_webhooks = on` 
and ```
vmq_webhooks.webhook1.hook = auth_on_publish
vmq_webhooks.webhook1.endpoint = http://127.0.0.1/myendpoints
```
in config file, and the error disappear. but where can I find the history of a topic (a saved file of all publications)

Thanks

**Comment by larshesel** [comment]
There is no log of everything which has been published. To achieve that you'd have to build a plugin and log what you want from the hooks.
