### ISSUE TITLE
Erlang: Can't set long node name!

### ISSUE THREAD

**Issue by georgepoenaru** [erlio/vernemq#161]
Hi, 

I'm trying to deploy a containerized vernemq cluster over kubernetes. Unfortunately I can't retrieve the cluster status with vmq-admin because erlang doesn't like long hostnames and I can't control the kubernetes pod name in replica controller scenario. 

Running vmq-admin I get this:

`=INFO REPORT==== 27-Jun-2016::17:35:43 ===
Can't set long node name!
Please check your configuration
escript: exception error: no match of right hand side value 
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [['VerneMQ_maint_22162',longnames]]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}`  

I wonder is you can't you just use sname instead name when you retrieve hostname ?

This is how my hostename look's like. I only can controll the "mqtt-node" name in Kubernetes

> cat /etc/hostname
`mqtt-node-2151733443-54gsy
`

**Comment by ioolkos** [comment]
Well, who was at a Kubernetes workshop today, @dergraf ? ;)

Thanks for asking, @georgepoenaru !

**Comment by dergraf** [comment]
Longnames are currently required.
Can't you do something similar we do in erlio/docker-erlang where we automatically assign the nodename via a script prior starting the VerneMQ service?

**Comment by dergraf** [comment]
Snames I meant

**Comment by georgepoenaru** [comment]
@ioolkos , @dergraf  Thank you for for fast support ! If you want I can contribute to a cluster deployment example in kubernetes.  

@dergraf  I was prepared to try this but I was concerned about the fact that Kubernetes DNS will be affected by this hack. I want to use dns names instead IPs for discovering nodes. But I'll do the cluster discovery through a service not through a pod. (Eg.: my-service.development.svs.kubernetes.default)

I'll try this today and I came back with feedback.

**Comment by georgepoenaru** [comment]
It was strange problem. In the end I found out the problem came from the fact that I was trying to build conatiner FROM ubuntu instead of FROM debian:jessie

**Comment by ioolkos** [comment]
OK, thanks for letting us know!
Very interested to see where you go with this Kubernetes project.

**Comment by georgepoenaru** [comment]
@ioolkos I managed to make it work. I didn't make it work in minikube on my laptop because the service was not reachable from inside pod (VPN). I'll put on my github account these days and send you link. Thank you.

**Comment by georgepoenaru** [comment]
Hi @ioolkos 

I promise to came back with the implementation of vernemq cluster on kubernetes. 

Here is my implementation: 
https://github.com/georgepoenaru/vernemqube

Make sure your Kubernetes DNS is running

**Comment by dergraf** [comment]
that's great! thank you so much! we appreciate your efforts! :)

**Comment by georgepoenaru** [comment]
Thank you too for Verne. If doesn't work first thing you should check is if your container can resolve services host as dns over curl and nslookup

**Comment by larshesel** [comment]
I guess we can close this. Thanks again for making vernemqube!

**Comment by rokka-n** [comment]
#150
