### ISSUE TITLE
Too Many Publish messages and Publish Timeout when Load test

### ISSUE THREAD

**Issue by hbahn** [erlio/vernemq#163]
Hi there, 

It is me again.
When we had a load test with VerneMQ, we got the those messages from client side,

1) Too Many Publish Messages
2) Publish Time-Out 

Configuration:
1. Clustered set with 2 nodes
2. Relevant Configurations
   a. max_inflight_messages = 20
   b. max_online_messages = 1000
   c. max_offline_messages = 1000
3. Load : AVG. 400 TPS

if we change the configurations to as follow,
  a. max_inflight_messages = 0
  b. max_online_messages = -1 
  c. max_offline_messages = -1

is the modified configuration okay for the this high capacity system?
or is this client issues?
Thanks in advance.

**Comment by ioolkos** [comment]
Hello @hbahn 
we wouldn't recommend disabling those 3 configs totally (you can set them very high though).
They are likely not your problem here anyway.

So the client says it receives too much messages? can the client consume 400 TPS? what is the test setup actually?

**Comment by ioolkos** [comment]
I might have misunderstood this. It's your publishing client telling you that it has 'too many publishes', right?

Any information on your test scenario (how many publishers etc) would help us.

Thanks!

**Comment by hbahn** [comment]
I suspect that this is our client issues for queuing QoS 1 Publish messages.

We are looking into it.

Plus, if a client sets the keep alive time 20secs, if the client sends PINGREQ after 23 secs the latest one sent. The session is closed. what is the keep alive validation margin? 10 %

**Comment by hbahn** [comment]
one more question,

if we configure,
a. max_inflight_messages = 1000
b. max_online_messages = 100000
c. max_offline_messages = 100000

for a million device connections.

is it still overconfiguration?

**Comment by hbahn** [comment]
Plus could you give any addtional tips for this target system capacity (a million connections not simultaneous) within a clustered set?

**Comment by ioolkos** [comment]
RE:
> if we configure,
a. max_inflight_messages = 1000
b. max_online_messages = 100000
c. max_offline_messages = 100000

a: Ok, `max_inflight_messages` protects sessions from the incoming side of the broker. Do you want to protect against more than 1000 messages (QoS > 0) in a session? Then this setting is for you.

b. and c: do you have single consumers that need to cope with an extreme amount of messages?
then `max_online_messages` is for you. Keep in mind that this could massively add up, if you allow 100k messages online per consumer. Any consumer would only start dropping messages if the online queue goes over 100k. 
Take your maximum expected consumer rate (msg/s) for your biggest single consumer and configure `max_online_messages` a littler higher than that. 

Also keep in mind that a single MQTT consumer is overloaded pretty easily anyway...

**Comment by hbahn** [comment]
Thanks for your response.

We have mainly two gateways and the gateways create two sessions. There are a million devices behind the gateways. so we have two big sessions and over the sessions actual devices' (not connected with MQTT connectios) messages are passed.

Anyway as you mentioned then a consumer can be overloaded.

Another question, if we set the configuration, can our system be a robust ( not going to CPU overload)?

Our system 12 cores × 2 CPU and 64GB

**Comment by ioolkos** [comment]
Hello @hbahn 
I think it would be very useful at this point, if we could discuss architectural details per mail. I don't have a clear view of your architecture right now.
Thanks :)

**Comment by AymanElarian** [comment]
@hbahn how did you solve that , do you stay with MQTT or go to other scenario like kafka ?
