### ISSUE TITLE
is it possible Allow_multiple_session=on and queue_deliver_mode = balance for clustered set

### ISSUE THREAD

**Issue by hbahn** [erlio/vernemq#165]
Hi there again, 

As you know, maybe, we have two nodes in a cluster
each cluster sets the configuration as follow,

1) allow_multiple_session = on
2) queue_deliver_mode = balance

and two clients connects to the clustered broker with the same clientID, cleansession = true, 
and the two client gets the message  
I think the queue is not balanced at all within a clustered system.

is it normal behavior, these two options are not applied to clustered system....?

**Comment by ioolkos** [comment]
`allow_multiple_sessions` is to allow multiple sessions (locally and in the cluster)
`queue_deliver_mode` is to balance a single queue, so it doesn't balance over multiple cluster nodes. A queue lives only on one node at a time.

**Comment by hbahn** [comment]
okay! Thanks a lot.
