### ISSUE TITLE
problem of exported metrics

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#171]
Hi!
There are some metrics in http://vernemq.com/docs/monitoring/ does not received message, such as "/clients/total", "/cluster/bytes/sent/last_5min/value".
There are some metrics publish wrong value, such as "/cluster/bytes/received/last_5min/value"(alwarys 0).

**Comment by dergraf** [comment]
@dcy, the metrics system got a complete rewrite in upcoming 0.13.1. We won't fix this for 0.12.5.
