### ISSUE TITLE
vmq_diversity: auth_on_register username/password are "undefined"

### ISSUE THREAD

**Issue by baranga** [erlio/vernemq#173]
https://github.com/erlio/vmq_diversity/issues/5

Already reported the issue in [vmq_diversity](https://github.com/erlio/vmq_diversity) but looks like it got lost.

**Comment by larshesel** [comment]
Hi, thanks for opening here as well and remind us. The issue hasn't been lost and is still on our radar, but hasn't yet had the priority it deserves. We'll look into it soon, but I can't give any estimates. I apologize for not having acknowledged the issue sooner.

**Comment by dergraf** [comment]
Let's close this issue here, as it's tracked in erlio/vmq_diversity#5
