### ISSUE TITLE
Vernemq can't start

### ISSUE THREAD

**Issue by landy5661** [erlio/vernemq#174]
Hello,
I'm trying Vernemq cluster, testing environment is Ubuntu14.04 in vmware.
I have 2 questions about this.

1. I edit /etc/vernemq/vernemq.conf and only change nodename (ex: VerneMQ@192.168.253.166) then restart vernemq but failed. I use sudo vernemq console and find the error:
`{error_logger,{{2016,7,22},{18,21,4}},"Protocol: ~tp: the name VerneMQ@192.168.253.166 seems to be in use by another Erlang node",["inet_tcp"]}`

2. I change nodename again (ex. VerneMQ1@192.168.253.166), run "sudo vernemq console" and get the following error:
```
config is OK
-config /var/lib/vernemq/generated.configs/app.2016.07.22.18.31.54.config -args_file /var/lib/vernemq/generated.configs/vm.2016.07.22.18.31.54.args -vm_args /var/lib/vernemq/generated.configs/vm.2016.07.22.18.31.54.args
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
Exec:  /usr/lib/vernemq/erts-7.3/bin/erlexec -boot /usr/lib/vernemq/releases/0.13.1/vernemq               -config /var/lib/vernemq/generated.configs/app.2016.07.22.18.31.54.config -args_file /var/lib/vernemq/generated.configs/vm.2016.07.22.18.31.54.args -vm_args /var/lib/vernemq/generated.configs/vm.2016.07.22.18.31.54.args              -pa /usr/lib/vernemq/lib/erlio-patches -- console
Root: /usr/lib/vernemq
{error_logger,{{2016,7,22},{18,31,55}},"Protocol: ~tp: the name VerneMQ0@192.168.253.166 seems to be in use by another Erlang node",["inet_tcp"]}
{error_logger,{{2016,7,22},{18,31,55}},crash_report,[[{initial_call,{net_kernel,init,['Argument__1']}},{pid,<0.23.0>},{registered_name,[]},{error_info,{exit,{error,badarg},[{gen_server,init_it,6,[{file,"gen_server.erl"},{line,344}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[net_sup,kernel_sup,<0.10.0>]},{messages,[]},{links,[#Port<0.502>,<0.20.0>]},{dictionary,[{longnames,true}]},{trap_exit,true},{status,running},{heap_size,610},{stack_size,27},{reductions,837}],[]]}
{error_logger,{{2016,7,22},{18,31,55}},supervisor_report,[{supervisor,{local,net_sup}},{errorContext,start_error},{reason,{'EXIT',nodistribution}},{offender,[{pid,undefined},{id,net_kernel},{mfargs,{net_kernel,start_link,[['VerneMQ0@192.168.253.166',longnames]]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]}]}
{error_logger,{{2016,7,22},{18,31,55}},supervisor_report,[{supervisor,{local,kernel_sup}},{errorContext,start_error},{reason,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}},{offender,[{pid,undefined},{id,net_sup},{mfargs,{erl_distribution,start_link,[]}},{restart_type,permanent},{shutdown,infinity},{child_type,supervisor}]}]}
{error_logger,{{2016,7,22},{18,31,55}},crash_report,[[{initial_call,{application_master,init,['Argument__1','Argument__2','Argument__3','Argument__4']}},{pid,<0.9.0>},{registered_name,[]},{error_info,{exit,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,134}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}},{ancestors,[<0.8.0>]},{messages,[{'EXIT',<0.10.0>,normal}]},{links,[<0.8.0>,<0.7.0>]},{dictionary,[]},{trap_exit,true},{status,running},{heap_size,376},{stack_size,27},{reductions,164}],[]]}
{error_logger,{{2016,7,22},{18,31,55}},std_info,[{application,kernel},{exited,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}},{type,permanent}]}
{"Kernel pid terminated",application_controller,"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{kernel,start,[normal,[]]}}}"}

Crash dump is being written to: /erl_crash.dump...Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
```

If I change nodename to default VerneMQ@127.0.0.1, vernemq will start ok. Did I miss some configuration for cluster setting?

**Comment by ioolkos** [comment]
Hi @landy5661 
Thanks for your problem description!
The most important thing here, is to define what you actually are trying to do and what your expectations are.

How did you set up the cluster? if you have a cluster, renaming and rebooting single nodes in it won't just work like that. 
It looks like you are editing the same config file in `/etc/vernemq/vernemq.conf` and try to start different nodes from that? (this won't work)

**Comment by landy5661** [comment]
Hi ioolkos,
Thanks for your reply, I try to describ what I want to do.

Im looking for a MQTT broker which support cluster. I do some search google and find this url: [https://github.com/mqtt/mqtt.github.io/wiki/server-support](url), then I select Vernemq and try it.

I want to create 2 VM with Ubuntu 14.04, install VerneMQ on both, and then set up a cluster.
I edit vernemq.conf and change the nodename > vernemq restart > make the new nodename work > but failed. I want to make each nodename is unique, so I change the nodename in vernemq.conf.

After some research I found this issue: [https://github.com/erlio/vernemq/issues/134](url). 
I delete the folder "/var/lib/vernemq/" and restart vernemq > still failed.
Then I reinstall vernemq and use the same config file > restart vernemq > it works.

Did I do something wrong at first step?
[https://vernemq.com/docs/clustering/](url)

**Comment by ioolkos** [comment]
You most probably created a cluster, and then changed nodenames. Do it the other way around ;)
(VerneMQ registers the cluster nodenames in its metadata, and then complains, if you want to boot a cluster node with a new name)
Hope this helps!

**Comment by landy5661** [comment]
Hi ioolkos,
Thanks for your explanation. I change my steps and the 2 clusters are all ok.

in single node
old:  node is running -> change nodename -> vernemq restart -> fail.
new: vernemq stop -> change nodename -> vernemq start -> success.
