### ISSUE TITLE
Facing Broker Hang after series of invalid Username/Password connection trials and recover after a valid Username/Password Connection

### ISSUE THREAD

**Issue by hbahn** [erlio/vernemq#176]
Hi there,

We faced a VerneMQ hang issue under the certain situation.
Before I describe detail issues and phenomenon, I would like to explain how our system works regarding authentication.

Authentication: our system has a Portal and it stores user's credentials(ID and PW). when a MQTT client connects to the Broker a modified lua script (please find the first attachment) to refer the credential whether the client is member of our system or not.

Here is Cause and Behaviour

_1) a invalid user (Client **0**) tried to connect to Broker (without ID/PW, no username/password) and please see the log below_
```
2016-07-22 17:09:29.154 [error] <0.243.0>@vmq_diversity_script:handle_call:124 can't call function auth_on_register with args [{addr,<<"218.36.252.2">>},{port,46120},{mountpoint,<<>>},{client_id,<<"100001">>},{username,undefined},{password,undefined},{clean_session,true}] in "/etc/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/priv/../scripts/init.lua" due to {illegal_index,nil,<<"CERT_CLIENT_ID">>}
2016-07-22 17:09:30.171 [error] <0.243.0>@vmq_diversity_script:handle_call:124 can't call function auth_on_register with args [{addr,<<"218.36.252.2">>},{port,46150},{mountpoint,<<>>},{client_id,<<"100001">>},{username,undefined},{password,undefined},{clean_session,true}] in "/etc/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/priv/../scripts/init.lua" due to {illegal_index,nil,<<"CERT_CLIENT_ID">>}
2016-07-22 17:09:31.188 [error] <0.243.0>@vmq_diversity_script:handle_call:124 can't call function auth_on_register with args [{addr,<<"218.36.252.2">>},{port,46185},{mountpoint,<<>>},{client_id,<<"100001">>},{username,undefined},{password,undefined},{clean_session,true}] in "/etc/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/priv/../scripts/init.lua" due to {illegal_index,nil,<<"CERT_CLIENT_ID">>}
```
_2) After step 1) Broker can receive Publish message and send PUBACK message from Client **A** but Broker cannot send this message to Client **B** (who is a receiver and subscribes proper topic, Client **A** sends the message toward Client **B**). It is like system hang._

_3) After step 2) another client **C** tried to connect with invalid credential (no username/password), the hang phenomenon was no recovered. (the Client **B** could not receive any message from Broker, however the Client **A** kept publishing messages toward Broker and intened to send to Client **B**)_
```
2016-07-24 10:03:03.023 [error] <0.243.0>@vmq_diversity_script:handle_call:124 can't call function auth_on_register with args [{addr,<<"94.102.49.190">>},{port,36461},{mountpoint,<<>>},{client_id,<<"paho/D33AC37DEFA35CD7CD">>},{username,undefined},{password,undefined},{clean_session,true}] in "/etc/vernemq/vmq_diversity/_build/default/lib/vmq_diversity/priv/../scripts/init.lua" due to {illegal_index,nil,<<"CERT_CLIENT_ID">>}
```
_3) After step 3) another client **D** tried to connect with proper credential (username/password) and the hang was suddenly recovered which means that  (the Client **B** could receive message sent Client **A**)_

Sorry for this long description.
I would ask you that Is this bug of VerneMQ or our Lua script for refering credential from 3rd party entity?
Appreciated in advance.

Hongbeom.

**Comment by hbahn** [comment]
Here is the "init.lua"
```
config = {
 -- configuration information
}

mysql.ensure_pool(config)

function my_auth_on_register(args)
    if pcall(con_check) then
       print("")
    else
      print("DB Connect Fail & uKey authentification Skipped")
      mysql.ensure_pool(config)
      return true
    end

    ret = mysql.execute("table",[[SELECT CERT_CLIENT_ID FROM PP_CERT_KEY WHERE CERT_TYPE = 'K01002' AND CERT_ID = ? AND EXPIRE_DATE >= (SELECT NOW()) AND CERT_DATE = (SELECT MAX(CERT_DATE) FROM PP_CERT_KEY WHERE CERT_TYPE = 'K01002' AND CERT_ID = ? AND EXPIRE_DATE >= (SELECT NOW()))]], args.username, args.username)
    if #ret then
        if enc(ret[1].CERT_CLIENT_ID) == args.password then
            return true
        else
            return false
        end
    end
end

hooks = {
    auth_on_register = my_auth_on_register
}


-- character table string
local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

function enc(data)
    return ((data:gsub('.', function(x)
        local r,b='',x:byte()
        for i=8,1,-1 do r=r..(b%2^i-b%2^(i-1)>0 and '1' or '0') end
        return r;
    end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
        if (#x < 6) then return '' end
        local c=0
        for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
        return b:sub(c+1,c+1)
    end)..({ '', '==', '=' })[#data%3+1])
end

function con_check()
   con = mysql.execute("table", [[SELECT 'test' FROM PP_CERT_KEY WHERE 1=1]])
end
```

**Comment by larshesel** [comment]
Hi Hongbeom,

I was just going to ask if you could make the lua plugin available to us - I'll see if I can find some time today to look into this.

Are there any crashes in the vernemq logs? Also which version of VerneMQ are you running?

Thanks

**Comment by hbahn** [comment]
Actually, the Broker was not broken down we do not have any crash log. As I mentioned without any failover and Broker was recoved.
The version is 0.12.5 and we "off" the allow_anonymous configuration.

Thanks

**Comment by larshesel** [comment]
Hi @hbahn I didn't mean VerneMQ itself crashing and stopping. If something inside VerneMQ stops working, there's a good chance that it will be recorded in the VerneMQ log files: log/crash.log, log/error.log, log/console.log. Could you check them for any traces of abnormal activity?

**Comment by larshesel** [comment]
Hi, I looked a bit into this - and the errors you see are because of an exception in the lua code. I believe it's because the mysql driver cannot handle the case where the username/password are undefined and then errors out.

I tried to reproduce your scenario where I made the auth_on_register throw an error if the username was 'error' but otherwise allow all users.

I had a client subscribe to topic T and another publish to topic T as well. Then I tried to connect a client using username 'error' causing the crash like you see above, but that didn't cause any problems with the client I had subscribed - it could still receive messages.

I think, but can of course not be certain, that the subscriber does not receive the messages is not directly related to the crashes you see. Have you implemented other hooks in the system?

Is this scenario reproducible for you?

**Comment by hbahn** [comment]
I looked into the crash log files again, but there is no log message in log/crash.log. So I did not mention about the log. 

auth_on_register hook is only hook we are using in our system.

Now we have been trying to reproduce the same error situation, but it has not been reproduced so far. 

Is there any questionable behaviours or doubts for the situation that a client subscribes to Topic T and another publishes to the topic T but the client cannot receive messages?

**Comment by larshesel** [comment]
Hi,

Regarding a client not receiving messages for a topic that it has subscribed to we do not know of any issues on the broker side. My guess, without anything to suggest otherwise, would be a client issue, but without more to go on it's hard to tell.

Let us know if you discover how to reproduce this.
