### ISSUE TITLE
Passing the "peer" argument to all session's lifecycle hooks

### ISSUE THREAD

**Issue by manifest** [erlio/vernemq#182]
Currently, it's imposible to determine a peer that calls `on_client_wakeup`, `on_client_offline` or `on_client_gone` hook when **allow_multiple_sessions** option is enabled. In this case, there can be more than one active client with the same **client_id** (the only parameter passed to the hooks).

It's become a problem when implementing per-peer session (state), because we need some identifier to operate with.

Another solution is to have a state passed through session's lifecycle hooks.

**Comment by larshesel** [comment]
For now you can use the Pid (`self()`) to distinguish the different sessions for the same client_id. We can't guarantee that this won't change in the future, but we currently have no plan to change it.

**Comment by manifest** [comment]
Thanks. It should work for me.

**Comment by manifest** [comment]
@larshesel looks like it doesn't work this way. One client's session - different pids.

```erlang
2016-08-19 18:43:53.667 [info] <0.347.0> {vmq_session,auth_on_register,5}, []: <<"user/joe">>, <0.347.0>
2016-08-19 18:44:06.147 [info] <0.291.0> {vmq_session,on_client_offline,1}, []: <<"user/joe">>, <0.291.0>
```

VerneMQ rev. 13ee808 "bump latest_version to 0.12.5p4"

**Comment by manifest** [comment]
I'm trying to implement a plugin limiting the amount of client's connections.
I might have accomplish that by:
- In the `auth_on_register` hook: incrementing connections` counter and checking if its value isn't exceeding a limit.
- In the `on_client_offline` and `on_client_gone` hooks: decrementing the counter.

But there is a problem. While `on_client_wakeup`, `on_client_offline`, `on_client_gone` share the same process, `auth_on_register` is executed in another one. So that, I can't use `pid` as a per-peer session's key (id).

I also can't check the limit in the `on_client_wakeup`, and increment the counter in the `auth_on_register` because the operation must be atomic.

@larshesel , is there a way I can solve this problem?
