### ISSUE TITLE
VerneMQ doesn't load /etc/vernemq/vernemq.conf

### ISSUE THREAD

**Issue by vladbabii** [erlio/vernemq#183]
I've compiled VerneMQ but the issue I have is that every time I start it, it generates a new config and uses it:

vernemq chkconfig
config is OK
-config /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2016.08.09.18.59.43.config -args_file /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.08.09.18.59.43.args -vm_args /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.08.09.18.59.43.args

vernemq chkconfig
config is OK
-config /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2016.08.09.19.02.02.config -args_file /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.08.09.19.02.02.args -vm_args /var/src/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.08.09.19.02.02.args

but if in run "ls /etc/vernemq/" I get "vernemq.conf  vmq.acl" so the files exist in that location. Is there somehting i need to configure to load the configuration file from there ?

Thank you!

**Comment by dergraf** [comment]
Hi there,

This is normal behaviour. The config files in generated.configs are automatically generated (at startup) by what it finds in etc/vernemq.conf even if this file hasn't changed. 

I hope this helps

**Comment by vladbabii** [comment]
It wasn't listening to the ports I was setting it to. But after a full restart it seems to work fine. Weird. Anyway, thank you for the quick reply!
