### ISSUE TITLE
Bridge Two Clusters

### ISSUE THREAD

**Issue by Debdutto** [erlio/vernemq#185]
Hi,

I'm running a vernemq cluster and was thinking of setting up another one and bridging the two clusters.

What would be the best way to go about this?

Also, I'm not just considering adding them to the same cluster because they are servers at two geographically separated locations.

Thanks in advance.

**Comment by ioolkos** [comment]
I can only ambivalently answer this:

To implement full cluster replication for a multi site setup, MQTT bridges are not an optimal instrument. But we have nothing better currently.

MQTT bridges are basically a way of hooking a MQTT topic tree into another, so they are great to shovel some messages to the other cluster (taking 2 respective cluster nodes).
