### ISSUE TITLE
./bin/vernemq stop error

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#187]
Hi!
I want to stop VerneMQ, it tells me node is not running, but the client can connect it.
```
dcy@dcy-dcy:~/coding/vernemq/_build/default/rel/vernemq$ ./bin/vernemq stop
Node 'VerneMQ@192.168.3.236' not responding to pings.
Node is not running!
```
And
```
dcy@dcy-dcy:~/coding/vernemq/_build/default/rel/vernemq$ ps -ef | grep VerneMQ@192.168.3.236
dcy      10940 10937  0 10:56 pts/7    00:00:09 /home/dcy/coding/vernemq/_build/default/rel/vernemq/bin/../erts-7.3/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /home/dcy/coding/vernemq/_build/default/rel/vernemq/bin/.. -progname vernemq -- -home /home/dcy -- -boot /home/dcy/coding/vernemq/_build/default/rel/vernemq/bin/../releases/0.13.1/vernemq -config /home/dcy/coding/vernemq/_build/default/rel/vernemq/data/generated.configs/app.2016.08.19.10.56.58.config -setcookie hisir -name VerneMQ@192.168.3.236 -smp enable -vm_args /home/dcy/coding/vernemq/_build/default/rel/vernemq/data/generated.configs/vm.2016.08.19.10.56.58.args -pa /home/dcy/coding/vernemq/_build/default/rel/vernemq/bin/../lib/erlio-patches -- console
dcy      25283  4949  0 13:58 pts/3    00:00:00 grep --color=auto VerneMQ@192.168.3.236
```
I ```kill -15 10940``` and not reproduce this issue.

**Comment by dcy** [comment]
By the way, I develop my own Erlang node, not VerneMQ broker, and ```net_kernel:connect_node``` the VerneMQ brokers, so i can use ```gen_server:cast``` to send msg to my own Erlang node in plugin.
I did this, not found problem. Will it cause some problems?

**Comment by larshesel** [comment]
To answer you first question: that sounds strange - can you tell us some more about what you had been doing before you experienced this? This is not a problem that we've encountered before.

Regarding your second question: I think connecting more erlang non-vernemq nodes to VerneMQ-nodes should be fine - but YMMV. Note, that any code which interfaces directly to the internals of VerneMQ can potentially be causing problems - it depends entirely on what you're doing.

**Comment by dcy** [comment]
Hi! @larshesel I wrote a plugin to send(gen_server:cast) the publish msg to my non-vernemq node to backup. I use gproc. I found my non-erlang node have not receive the msg suddenly, so i restart my non-vernemq node and not receive still, But in the shell ```nodes()``` shows my non-vernemq node connecting vernemq node. So i want to restart vernemq node, but ```./bin/vernemq stop``` show node not running.

**Comment by larshesel** [comment]
As I said this is not an issue that we've seen, so I think the first step is to disable your custom plugins and see if you can reproduce it without them.
