### ISSUE TITLE
VerneMQ website Prometheus configuration out of date?

### ISSUE THREAD

**Issue by radekg** [erlio/vernemq#191]
From this page: https://vernemq.com/docs/monitoring/prometheus.html

```
scrape_configs:
  - job_name: 'vernemq'
    scrape_interval: 5s
    scrape_timeout: 5s
    target_groups:
      - targets: ['localhost:8888']
```

gives:

```
INFO[0000] Starting prometheus (version=1.0.1, branch=master, revision=be40190)  source=main.go:73
INFO[0000] Build context (go=go1.6.2, user=root@e881b289ce76, date=20160722-19:54:46)  source=main.go:74
INFO[0000] Loading configuration file /etc/prometheus/prometheus.yaml  source=main.go:206
ERRO[0000] Couldn't load configuration (-config.file=/etc/prometheus/prometheus.yaml): unknown fields in scrape_config: target_groups  source=main.go:218
```

with Prometheus 1.0.1. I believe `target_groups` has been replaced with `static_configs`.

```
scrape_configs:
  - job_name: 'vernemq'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:8888']
```

works fine for me.

**Comment by ioolkos** [comment]
Yes, that's exactly how it is. I forgot to update this in docs.
Thanks for your reminder @radekg :+1:

**Comment by radekg** [comment]
BTW, would it be worth adding a `metrics prefix` setting for prometheus? Similar to `graphite_prefix`? Maybe just a generic `metric_prefix`? WDYT?

**Comment by ioolkos** [comment]
I think so. Or rather:  I have to ask @dergraf what the `graphite_prefix` is all about? :) doesn't seem mandatory at least.

**Comment by radekg** [comment]
Would be really nice if one could prefix metrics just for export.

**Comment by dergraf** [comment]
Yeah would be definitely good to have. Distinguishing all the metrics without the prefix becomes quite hard.

**Comment by radekg** [comment]
If that's a nice to have, I could try preparing a PR.

**Comment by ioolkos** [comment]
That's awesome & very welcome!  thank you :)

**Comment by radekg** [comment]
I see the page has been updated. Great stuff. I'll create a separate issue for the metrics thingie.
