### ISSUE TITLE
Can auth_on_publish not allow to publish msg but not stop the client?

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#196]
Hi!
if ```auth_on_publish``` not return ```ok```, it will disconnect the client.
Can ```auth_on_publish``` not allow to publish msg but not stop the client?
Maybe only return ```stop``` will stop the client.

**Comment by ioolkos** [comment]
Thanks @dcy, very good question!
The problem lies in the spec:

> If a Server implementation does not authorize a PUBLISH to be performed by a Client; it has no way of informing that Client. It MUST either make a positive acknowledgement, according to the normal QoS rules, or close the Network Connection [MQTT-3.3.5-2].

We find that ACKING a non-authorized message without telling the publisher it was rejected, is kind of weird. Hence the network close.

**Comment by dergraf** [comment]
Closing. We think it makes sense to stick to the specification regarding authorization of publish messages.

**Comment by dcy** [comment]
Could you tell me how to solve this problem?
A sub ```/chat/a```, B sub ```/chat/b```, A send a msg to B, so A pub a msg to the topic ```/chat/b```. When B add A to his blacklist, A can not send msg to B.
In plugin, I stop A send msg to B by ```auth_on_publish``` not return ```ok```, but it will disconnect A.
