### ISSUE TITLE
MQTT Scaling Single Subscriber for Firehose Backend Message Store

### ISSUE THREAD

**Issue by drasko** [erlio/vernemq#197]
Hello,
I would like to use MQTT and also save all messages via backend to MongoDB.

One evident approach would be to subscribe my store backend to `#` topic - this wildcard will pick up all the messagess on every topic. However, based on this: http://www.hivemq.com/blog/mqtt-sql-database it is a bad practice. It is mentioned here also: http://stackoverflow.com/questions/27572676/rabbitmq-mqtt-architecture-for-a-cluster-of-clients

The biggest problem I see is not the speed of backend client, but rather the routing within the cluster - if backend client subscribed on topic `#` is subscribed to Node A, then all other nodes will have to send the MQTT messages to Node A and this defeats the purpose of clustering.

Solution with Kafka is explained here: https://www.youtube.com/watch?v=VoTclkxSago. Basically, backend does not do MQTT subscription at all. Rather than that, MQTT messages are taken from within the MQTT brokers, and pushed to Kafka (I guess by the MQTT brokers them self).

Here is a nice plugin for eMQTT that takes MQTT messages from within a broker (not from the MQTT topic) and publishes them to Kafka: https://github.com/vowstar/emqttd_plugin_kafka_bridge. As you can see here: https://github.com/vowstar/emqttd_plugin_kafka_bridge#messages, besides MQTT payload these messages have some extra useful administrative info.

Is there a similar way to take MQTT messages (plus sime adminitrative info as a bonus) from VeneMQ (like some kind of plugin) without subscribing to `#` topic - which will route all the traffic to a single node. I.e. directly from some queue, not by subscribing to a MQTT topic?

If something like this does not exist- how do we handle high scalability without forcing `#` subscription

**Comment by ioolkos** [comment]
Hi @drasko 
thanks for your remarks!
You're spot on with this, subscribing to `#` has all the drawbacks you mention, especially the cluster having to route to the subscriber in the first place.

That means we have to catch the messages at their incoming side with the `on_publish` hook for example.
For MongoDB integration, have a look at the MongoDB vmq_diversity plugin. You can use the `on_publish` hook there and publish to MongoDB from every cluster node. You'll have to see if the performance of the plugin works for you (I guess it would).

We have no Kafka plugin OTOH at the moment. 
Other ideas that come to my mind are some sort of ZeroMQ plugin, or integration with Apache Nifi.

**Comment by dergraf** [comment]
Close due to inactivity.
