### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by keepexploring** [erlio/vernemq#200]
Hi there,

Just for your info, noticed a small mistake in the documentation:

In the section Authorisation it says:
"VerneMQ periodically checks the specified ACL file.
acl_file = /etc/vmq.acl "

but should be (according to the config file): acl_file = /etc/vernemq/vmq.acl

Thanks for the great work! Vernemq is such a great piece of software.

Joel

**Comment by dergraf** [comment]
@keepexploring thanks for reporting, you're right of course!

**Comment by dergraf** [comment]
Done
