### ISSUE TITLE
Clustered Mode: Connecting with clean session does not wipe the session.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#202]
I have a three node setup of VerneMQ and when I connect a client with clean session equal to `true` after having previously established a session I'm receiving enqueued messages. Can you reproduce this?

**Comment by ioolkos** [comment]
@dergraf @larshesel Protocol error?!

**Comment by dergraf** [comment]
Sounds like a allow_multiple_session mistake.

Am 27.09.2016 6:59 nachm. schrieb "ioolkos" <notifications@github.com>:

**Comment by ioolkos** [comment]
@dergraf why does this sound like an allow_multiple_session mistake? can you elaborate? (you're probably saying #201 and #202 are related?). 

VerneMQ does in fact deliver messages for a incoming clean session if there was state saved before. This is probably a misunderstanding on how the behaviour should be from our side. Related: [MQTT-3.1.2-6]

**Comment by testark** [comment]
> VerneMQ does in fact deliver messages for a incoming clean session if there was state saved before.

@ioolkos is there any way this can be turned off (perhaps via a setting)?

**Comment by dergraf** [comment]
I was wrong. Sounds like a bug to me. Queue migration is triggered whether clean session was true or false. Looks like an easy fix.

**Comment by testark** [comment]
@dergraf do you have any ETA for a fix?

**Comment by dergraf** [comment]
No not yet. But you can expect something soon.

**Comment by dergraf** [comment]
Let's track the progress over here https://github.com/erlio/vmq_server/issues/100
