### ISSUE TITLE
Problems bridging messages to RabbitMQ 

### ISSUE THREAD

**Issue by lucastorri** [erlio/vernemq#205]
Hi!

My company has been trying to benchmark a few MQTT brokers and we decided to give VerneMQ a try. I have been compiling VerneMQ from the source on a Mac OS. I can get it running and, by using `mosquitto_(pub/sub)`, I'm able to publish messages and get them when subscribed.

As part of our current use case, we would need to route all received messages to a same RabbitMQ queue. Therefore, I was trying to set up the bridge functionality to interact with Rabbit.

I have my RabbitMQ MQTT Broker running on port **1889** and, based on the documentation available [here](https://vernemq.com/docs/configuration/bridge.html), was trying the following configuration for Verne:

```
bridge.tcp.br0 = 127.0.0.1:1889
bridge.tcp.br0.cleansession = on
bridge.tcp.br0.client_id = auto
bridge.tcp.br0.keepalive_interval = 10
bridge.tcp.br0.username = guest
bridge.tcp.br0.password = guest
bridge.tcp.br0.restart_timeout = 3
bridge.tcp.br0.try_private = off

bridge.tcp.br0.topic.1 = * out
```

Unfortunately, this setup is not working as I would expect. I can see that the connection between the systems is stablished, but messages published to Verne are not pushed to Rabbit.

I've tried a few different settings for `bridge.tcp.br0.topic.1`, and learned the following:

* `in` rules work correctly. When I set one up, and publish something to RabbitMQ MQTT, I get that back on VerneMQ;
* `$SYS/* out remote`, the example provided on the documentation, works.

I've seen a few [related](https://github.com/erlio/vernemq/issues/91) [issues](https://github.com/erlio/vernemq/issues/185), but from [one of them](https://github.com/erlio/vernemq/issues/140) I'm unsure if a related bug exists. Most probably, though, I am doing something wrong with my configuration.

Any ideas what could be the problem here?

Thanks

**Comment by ioolkos** [comment]
Hi @lucastorri 

great you're checking out VerneMQ & thanks for your report :)

It seems regardless whether you configure
`bridge.tcp.br0.topic.1 = * out`or `bridge.tcp.br0.topic.1 = /* out`, you'll only get the topics after the first level `/`.

In fact, in mosquitto_sub, you can only subscribe like that:
`mosquitto_sub -h 127.0.0.1 -p 1889 -t /#` (subscriber to RabbitMQ)

This way, things works for me. Kinda inconsistent. Normally one would only export a sub tree of the whole topic tree, or work with aliases.

**Comment by dergraf** [comment]
Hi @lucastorri,
Thanks for the report and great you're giving VerneMQ a spin. 
It's interesting that you see the $SYS/# messages arriving in Rabbit and none of the others. Are your messages routed and not rejected by an auth plugin?

**Comment by lucastorri** [comment]
Hey @ioolkos and @dergraf,

thank you for your help.

I have a small nodejs application running locally for authentication, and I've registered a few webhooks to interact with it:

```javascript
var http = require('http');

const PORT = 8080;

function handler(request, response) {
  let content = {};

  switch (request.url) {
    case '/on-register':
      content = {
        "result": "ok",
        "modifiers": {
          "mountpoint": "newmountpoint",
          "subscriber_id": "subscriber_id",
          "reg_view": "reg_view",
          "clean_session": false,
          "max_message_size": 65535,
          "max_message_rate": 10000,
          "max_inflight_messages": 100,
          "retry_interval": 100,
          "upgrade_qos": false,
          "trade_consistency": false
        }
      }
      break;
      case '/on-subscribe':
        content = {
          "result": "ok",
          "topics": [{"topic": "rewritten/topic", "qos": 0}]
        }
        break;
      case '/on-publish':
        content = {
          "result": "ok",
          "modifiers": {
            "topic": "rewritten/topic",
            "qos": 2,
            "payload": "rewritten payload",
            "retain": true,
            "reg_view": "reg_view",
            "mountpoint": "newmountpoint"
          }
        }
        break;
  }

  withData(request, (data) => {
    console.log(`${request.url}:${response.statusCode} => ${data}`);
    console.log(`res: ${JSON.stringify(content)}`)
    response.end(JSON.stringify(content));
  });
}

function withData(request, cb) {
  let body = [];
  request.on('data', function(chunk) {
    body.push(chunk);
  }).on('end', function() {
    body = Buffer.concat(body).toString();
    cb(body);
  });
}

var server = http.createServer(handler);

server.listen(PORT, function() {
  console.log(`Listening on: http://localhost:${PORT}`);
});
```

```bash
vmq-admin webhooks register hook=auth_on_register endpoint="http://localhost:8080/on-register"
vmq-admin webhooks register hook=auth_on_publish endpoint="http://localhost:8080/on-publish"
vmq-admin webhooks register hook=auth_on_subscribe endpoint="http://localhost:8080/on-subscribe"
```

I can see that the endpoints are being used through the logs, i.e. I would see something similar to the following whenever I subscribe/publish to VerneMQ:

```
/on-register:200 => {"peer_addr":"127.0.0.1","peer_port":50503,"mountpoint":"","subscriber_id":"mosqsub/26465-lucass-mb","username":"undefined","password":"undefined","clean_session":true}
res: {"result":"ok","modifiers":{"mountpoint":"newmountpoint","subscriber_id":"subscriber_id","reg_view":"reg_view","clean_session":false,"max_message_size":65535,"max_message_rate":10000,"max_inflight_messages":100,"retry_interval":100,"upgrade_qos":false,"trade_consistency":false}}
```

Then I have a couple of shell sessions, and when I publish something, I get the following on the connected subscriber:

```bash
# shell #1
mosquitto_pub -q 0 -m "Hello, MQTT" -t /data

# shell #2
mosquitto_sub -t '#'
Hello, MQTT
```

So, as far I can tell, authentication seems to be fine. BTW, I can also check that RabbitMQ MQTT is also working by publishing the following and see the message on the queue I bound to the MQTT related exchange:

```bash
# shell #1
mosquitto_pub -q 0 -m "Hello, MQTT" -t /data -u guest -P guest -p 1889

# shell #2
mosquitto_sub -t '/#' -u guest -P guest -p 1889
Hello, MQTT
```

VerneMQ authentication with RabbitMQ also looks fine, since, like I said before, I can see the connection stablished through the RabbitMQ web UI.

I've tried to set `bridge.tcp.br0.topic.1` to a few different options: 
- `* out`
- `/* out`
- `/+ out`
- `+ out`

... and to publish it with different topics:

```bash
mosquitto_pub -q 0 -m "Hello, MQTT" -t /
mosquitto_pub -q 0 -m "Hello, MQTT" -t /data
mosquitto_pub -q 0 -m "Hello, MQTT" -t /data/1
mosquitto_pub -q 0 -m "Hello, MQTT" -t /data/1/2
```

..., but none of the combinations worked.


Once again, thank you for your support.

**Comment by dergraf** [comment]
The reg_view modifier in your on_register handler looks suspicious. Can you remove this modifier and test again. Also is the VerneMQ error.log showing any errors?

**Comment by lucastorri** [comment]
@dergraf I've removed the `reg_view` and there are no errors that I can see (files or console). For reference, here are the log entries I get when running `vernemq console`: https://gist.github.com/lucastorri/9200f3143e4cac10c3e183f70108f88d

By the end you can see that I add the webhooks and also send a single message with `mosquito_pub`, where the clients connects and disconnects in the sequence.

**Comment by dergraf** [comment]
Ah I missed something. The modifier `mountpoint` is telling the router to use a different routing tree (similar to the vhosts in Rabbit). So you could change the vhost of a simgle publish msg (no shoveling around anymore ;)). However, our bridge plugin currently only supports the default mountpoint `""`so the messages are never picked up by the bridge. Please remove the mountpoint modifier and retest. Thanks.

**Comment by dergraf** [comment]
And for the notice the modifier `subscriber_id` in `auth_on_register` doesn't exist. If your intention is to rewrite the client_id use the `client_id` modifier. Please note that modifying the client_id to the same value for every connection (as you would do in your webhook) is only useful if you're dealing with one single client. Otherwise every connect would kick out any other established client.

**Comment by lucastorri** [comment]
Hey @dergraf, removing `mountpoint` did the trick 😃

I was using the templates available [here](https://github.com/erlio/vmq_webhooks/blob/master/README.md) for the auth response. To be honest, I have very little idea of what most of those fields do.

Anyway, I'm glad to see it working. Thanks a lot for your help!
