### ISSUE TITLE
ld: library not found for -lcrypto on macOS Sierra with OpenSSL installed via Homebrew

### ISSUE THREAD

**Issue by ralfr** [erlio/vernemq#206]
Trying to build VerneMQ on macOS Sierra. OpenSSL installed via Homebrew. Command line to make: `CFLAGS="-I /usr/local/Cellar/openssl/1.0.2j/include/" make rel`

However, fails with the following:

`===> Compiling lager_syslog
===> Compiling vmq_acl
===> Compiling eper
===> Compiling vmq_passwd
gcc -I /usr/local/Cellar/openssl/1.0.2j/include/ vmq_passwd.c -lcrypto -o vmq_passwd
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [compile] Error 1
===> Hook for compile failed!`

Any help is greatly appreciated!

**Comment by ioolkos** [comment]
oh, thanks @ralfr 
Does this comment help?
https://github.com/erlio/vernemq/issues/192#issuecomment-242922573

VerneMQ should be running on OS X, but there were different issues for the SSL thing. I hope Apple did not change something there with Sierra AGAIN! :)

**Comment by ralfr** [comment]
Unfortunately, the issue persists.

**Comment by ioolkos** [comment]
Also, this & this maybe help? it's basically all about the same thing OpenSSL and linking to it
https://github.com/erlio/vernemq/issues/119#issuecomment-214714457
https://github.com/erlio/vernemq/issues/88#issue-134900688

**Comment by ioolkos** [comment]
Maybe the -L option is missing? (example from a user for his CFLAGS:  `-L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include`)

**Comment by ralfr** [comment]
That did the trick! I'm one step closer. However, now it fails with this:

```./libtool: line 983: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8)
./libtool: line 984: g++: command not found
Makefile:419: recipe for target 'snappy.lo' failed
make[2]: *** [snappy.lo] Error 1
make[2]: Leaving directory '/home/rrottmann/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
Makefile:286: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/rrottmann/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
===> Hook for compile failed!```

**Comment by ralfr** [comment]
I should maybe add that `g++` is available on the Mac:

```➜  vernemq git:(master) ✗ g++
clang: error: no input files```

(VerneMQ deservers to become a Homebrew package..._

**Comment by ioolkos** [comment]
Ok, weird. But do you have Apple's XCode installed? or possibly something called the "Command Line Tools".
Or maybe there's some leaner way to get `g++` on Mac?

Yes, we need this as a Homebrew package... & give more love to OS X :)

**Comment by ralfr** [comment]
Yes. Xcode and Command Line Tools are there. And typing `g++ ` is available:

```
➜  ~ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
➜  ~
```

**Comment by ioolkos** [comment]
Oh noes, then we seem to have a real problem on Sierra? @dergraf any idea there?

Just to make sure, can you run the `make rel` command again? (possibly after also deleting the _build directory).
Thank you so much for your help & patience! 

on a sunday, no less... :)

**Comment by dergraf** [comment]
No idea.. I d require a mac to be able to debug this. Are you on Sierra on your mb air @afa?

**Comment by ioolkos** [comment]
no, one version behind.

**Comment by ralfr** [comment]
It worked!

Here is what I did:

`cd /usr/local/include`
`ln -s ../opt/openssl/include/openssl .`

In the `vernemq` repo root:
`rm -rf _build`
`CFLAGS="-L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include" make rel`

**Comment by ralfr** [comment]
@ioolkos Are you on Twitter?

**Comment by ioolkos** [comment]
Ha, awesome. Many thanks @ralfr ! :)
We'll make note of those steps.

(my personal twitter name is @frescosecco)

**Comment by codeadict** [comment]
This issue is persisting on Sierra, have you upgraded @ralfr , im making a Formula for homebrew but don't have any success it fails compiling eleveldb

**Comment by chimit** [comment]
The above commands by @ralfr return another error:
```
$ CFLAGS="-L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include" make rel

...

===> Resolved vernemq-1.0.0rc2
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
make: *** [rel] Error 1
```

**Comment by larshesel** [comment]
Hi @chimit 

The `eacces` error points to a file system permission issue. Can you see if the file mentioned `/home/tristan/Devel/rebar3/_build/default/lib/relx/src/relx.erl` is available for your user to read?

**Comment by larshesel** [comment]
hi @chimit forget the above. It looks to me like you're not using the rebar3 file supplied with vernemq. If the `REBAR` environment variable has been set the makefile will use the rebar specified there. Maybe that is what is causing this issue?

**Comment by chimit** [comment]
Hi, @larshesel 
Sorry, I'm not familiar with Erlang. I don't see `REBAR` in the environment vars list (`printenv`).

After I start `make rel` I see:
```
$ make rel
/Users/user/vernemq/rebar3  release --overlay_vars vars.config
```

**Comment by larshesel** [comment]
hi @chimit 

It looks like this might be your issue: https://github.com/erlware/relx/issues/564.

If you're feeling adventurous you could try to build rebar3 yourself: https://github.com/erlang/rebar3 and drop the rebar3 file into the vernemq folder

From what I understood v3.3.2 should not have this issue.

It would be great if you could confirm if this works for you as I don't have access to an OSX machine to test - if it does I'd downgrade the package we ship with vernemq.

**Comment by larshesel** [comment]
hi @chimit did you solve your issue? Otherwise I just saw that there's a new version of rebar3 available (3.3.6) on http://www.rebar3.org/.

We would probably upgrade to this version on master soon anyway - but it would be great if you could try it out and verify if it solves the problem! To test it you would only have to drop the new version into a new clone of vernemq (overwriting the old rebar3 version) and run `make rel`.

Cheers!

**Comment by chimit** [comment]
Hi, @larshesel!
Sorry for the late reply. I just tried to install VerneMQ on my macOS Sierra (10.12.4 (16E195)) again and got the same error:
```
===> Compiling epgsql
===> Compiling vernemq_dev
===> Compiling eredis
===> Compiling vmq_ql
===> Running neotoma...
===> Compiling vmq_plugin
===> Compiling vmq_commons
apps/vmq_commons/src/vmq_parser.erl:70: Warning: variable 'Fixed' is unused

===> Compiling vmq_server
===> Compiling vmq_webhooks
===> Compiling vmq_acl
===> Compiling vmq_passwd
gcc  vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
vmq_passwd.c:32:10: fatal error: 'openssl/evp.h' file not found
#include <openssl/evp.h>
         ^
1 error generated.
make[1]: *** [compile] Error 1
===> Hook for compile failed!

make: *** [rel] Error 1
```

I replaced Rebar3 in the vernemq directory, but have the same result.

**Comment by larshesel** [comment]
ok - I don't know about the sudo issue - but I'll recommend we upgrade our rebar3 version. Thanks for testing it out!

**Comment by dergraf** [comment]
@codeadict want to step in with your homebrew formula?

**Comment by codeadict** [comment]
@chimit ^^ https://github.com/codeadict/homebrew-vernemq
