### ISSUE TITLE
Idea / Question: Take username from CN in client certificate

### ISSUE THREAD

**Issue by ralfr** [erlio/vernemq#207]
Hi there,

I'm new to VerneMQ and love what I saw so far. Supporting Prometheus is superb, as we monitor most of our services with Prometheus.

Here is a question or idea for a feature, that would set VerneMQ apart from many of the other MQTT Brokers. If the core contributors would consider it, I'd feel flattered. For now, I'd also like to understand whether what I'm suggesting would be do-able with a plug-in.

We'd love to be able to extract the CN in a client certificate and allow to auth based on that.

For example, if the client cert provided by a client would have 

`/C=DE/ST=NRW/L=Cologne/O=ACME Inc/CN=John Foo`

it would be awesome if we could auth on a pattern like

`topic write /changes/%n/#`

where `%n` would be replaced with `John Foo`.

This could turn out to be extremely useful in many IoT cases, where we might even allow anonymous access, but have client certificate based security on the transport layer.

What do you guys think? Is this tough to do? Could this be done by a plug-in?

**Comment by dergraf** [comment]
We already support CN extraction from client certificates. Use `listener.ssl.use_identity_as_username = on` and you should get the CN as the username in your plugin. Instead of the `%n` you should be able to use `%u` for substituting the username.

**Comment by ralfr** [comment]
Wow! That's awesome. Is that anywhere in the docs? Not that explicitly I guess, or? It's a huge differentiator. We were looking into RabbitMQ but VerneMQ seems much more powerful. (Our platforms are mostly built in Elixir.)

**Comment by dergraf** [comment]
You can find it in the TLS section of the listener configuration page http://vernemq.com/docs/configuration/listeners.html

Great you like our approach of building a MQTT broker. ;) I like RabbitMQ too, but prefer to terminate MQTT in VerneMQ and use Rabbit for what it was build for, AMQP. 

Btw, check out our Elixir bridge erlio/vmq_elixir if you want to implement custom plugins in Elixir.

**Comment by dergraf** [comment]
Please reopen if required.
