### ISSUE TITLE
Usage of custom authentication

### ISSUE THREAD

**Issue by timbuchwaldt** [erlio/vernemq#208]
Hey! 
Thanks for the great work you do - I was checking out VerneMQ for an upcoming project (working with @ralfr btw) and stumbled upon a problem.
I started to write an authentication plugin to achieve the following: 
- Take the username (extracted from TLS cert), modify by removing some parts (long story, summary: Due to an issue our client certs have a wrong CN that I need to fix in order to use %u in the ACL)

My problem then is: As I can only return `next` but not modify, `ok` (and modify) or an `error` I am unable to pass the ACL checking to the existing ACL plugin, but modify the username in my custom one. Are there plans to extend the auth callback to `{next,  [{ModifierKey, NewVal}...]}` ? 
Would the right way to do it currently just be to implement all the checking in my custom plugin?

**Comment by ioolkos** [comment]
Hi @timbuchwaldt 
Aha, I see the problem. I guess we were just not thinking that one would want to modify the username or CN. 
I don't know what the best solution here is, but I'm sure @dergraf will have some creative ideas on this! :)

**Comment by timbuchwaldt** [comment]
Hey @ioolkos 
Thanks for the quick reply.
I have to admit our usecase is.. yeah. Rather special :D I might look into actually just submitting a PR for this to allow `next` to also alter the data, so one could setup chains of auth plugins - although judging by the `plugin show` output there seems to be no super strict concept of ordering the plugins yet.

**Comment by dergraf** [comment]
Hi @timbuchwaldt,
we have actually seen a similar requirement a while ago (here https://github.com/erlio/vernemq/issues/178) and we voted against the ability to chain plugins that return anything else then `next`. I think in the end it was a rather philosophical decision. 

While such a solution could solve your problem, we might fix it at different place. Namely, at the place where we extract data from the client certificate.

What do you think?

**Comment by timbuchwaldt** [comment]
Hi @dergraf,
I see your point. Coming from Elixir I have a tendency to view everything as a pipe, so not being able to pipe auth seemed wrong, especially since there is a way to modify the info on `ok`.

You are right, we could fix it in the part the extracts the CN from the cert and uses it as a username. Do you suggest just patching VerneMQ locally or a "proper" way to hook into this part of Verne?
It might be useful for other purposes to allow one to do custom extractions from the client cert, other parts of our system e.g. use the certificates hash for identifying stuff. I would be totally willing to extend VerneMQ by adding a plugin interface to this part.

**Comment by dergraf** [comment]
Roger that.

Every contribution is welcome! :)

Currently we have a very simplistic `use_identity_as_username = on|off` flag, which we should keep for 99.9% of our TLS users. However, we could change the backing functionality for it to translate the flag into an `{M,F,A}` which returns an `{ok, Proplist}`. The proplist could contain `username`, `client_id`, maybe `password` that could be a retrieved token. Not sure if this should be a hook that is controlled via `vmq_plugin` though. What do you think?

The place to start is https://github.com/erlio/vmq_server/blob/master/src/vmq_ranch.erl#L49. To find other places where we do relevant actions grep the code for `preauth`.

I think this is the way to go, however having plugins that pass some data to a susequent plugin in the chain in a safe way might be useful as well. I opened a PR over here https://github.com/erlio/vmq_plugin/pull/20  which is waiting for suggestions from everyone, especially @larshesel ;). This PR won't solve your issue @timbuchwaldt, but could be interesting for different purposes.

**Comment by dergraf** [comment]
On another note, we are currently discussing to support the PROXY protocol by HAProxy, which would allow to terminate TLS in HAProxy and pass specific fields, including the CN from the client certificate, to the upstream server over plain TCP. It would be great if the approach is generic enough to be easily ported. ;)

**Comment by timbuchwaldt** [comment]
Yeah, saw the current feature :)
Not sure about the vmq_plugin, sounds like a good idea in general, especially because it provides an easy way to link externally compiled beam files and is already proven. Would it maybe make sense to extract the current functionality to a small plugin and allow using a custom one? Not sure if overkill, though.

I will look into this further once we actually start deploying VerneMQ, sadly some other work is scheduled before this.

The PROXY protocol sure sounds interesting, too :)

**Comment by dergraf** [comment]
Hi @timbuchwaldt how are things rolling, or should we close this issue for the moment. Please ping us over email, if we can be of any other help regarding your VerneMQ evaluation or setup ;) cc: @ralfr

**Comment by timbuchwaldt** [comment]
Hey @dergraf 
we are currently working on another part of the project and would love to come back to you once we are into actually setting up the cluster and integrating it :)

**Comment by dergraf** [comment]
Closing this for the moment. let us know if there is anything we can do for you!
