### ISSUE TITLE
Topic queue management [ Questions ]

### ISSUE THREAD

**Issue by incarosegit** [erlio/vernemq#209]
( topics with qos 1 or 2 )
How can I setup a max numbers of messages in a topic queue before it starts dropping old messages in favor to new ones ?

If a topic has 1000s of messages waiting and a client subscribes, how can we control the number of messages the client will receive ? Sending the 1000s messages all at once will not be the best.

Can I remove or drain topic queues from the command line ? This is good for housekeeping if I know this topic is orphan or the messages are no longer relevant.

( is this the best place to post questions and requirements ? )

Thanks

**Comment by ioolkos** [comment]
Hello @incarosegit, thanks for your questions and remarks.

There is no such thing as a topic queue. Each client has its own queue. Each client also sets its own QoS settings, and sets Clean Session to false or true. 
Your questions still hold for that queue. Currently there is no exposed functionality to empty a client queue on behalf of a client. 
You note that sending all the offline messages from the queue to the client at once is not ideal. But how should one do that? a delivery rate? that would be rather cumbersome to configure.

Are your subscribers regularly overwhelmed with messages? 

(it's fine to ask questions here. there's also the public mailing list: http://vernemq.com/mailman/listinfo/vernemq-list_verne.mq)

**Comment by dergraf** [comment]
Hi there.

VerneMQ manages a queue per clientid, not per topic.
In order to do load-shedding on a queue, you've to configure the `max_offline_messages` and `max_online_messages` parameters. in order to drop old in favor of new messages, you've to configure `queue_type=lifo`. And last but not least to control the inflight message window set the `max_inflight_messages` to an appropriate value.

The mentioned tooling isn't available at the moment.

**Comment by incarosegit** [comment]
Thanks for the responses.
I may be using the wrong terms, sorry for that.

For "topic queue", I mean the internal memory the "topic" has to store messages, ( sent with qos 1 or 2 ) until a client subscribes to the "topic".

@dergraf Thanks for your answer.
So, if multiple clients publish to topic T in qos 2, and no one is subscribed to the topic, where the messages are stored ?
Then client 1 connects with cleanSession==false, and subscribes to topic T with qos 2
and client 2 connects with cleanSession==false, and subscribes to topic T with qos 2.
Does those clients get the messages published before ?
And next. client1 and client2 disconnect. More messages are published to topic T. Those new messages got stored in ... ? client1 and client2 "queues" ?
Thanks

**Comment by dergraf** [comment]
Am 16.10.2016 12:43 vorm. schrieb "incarosegit" <notifications@github.com>:
>
> Thanks for the responses.
> I may be using the wrong terms, sorry for that.
>
> For "topic queue", I mean the internal memory the "topic" has to store
messages, ( sent with qos 1 or 2 ) until a client subscribes to the "topic".
>
> @dergraf Thanks for your answer.
> So, if multiple clients publish to topic T in qos 2, and no one is
subscribed to the topic, where the messages are stored ?
In this case the messages are not stored.
> Then client 1 connects with cleanSession==false, and subscribes to topic
T with qos 2
> and client 2 connects with cleanSession==false, and subscribes to topic T
with qos 2.
> Does those clients get the messages published before ?
No.
> And next. client1 and client2 disconnect. More messages are published to
topic T. Those new messages got stored in ... ? client1 and client2
"queues" ?
The messages are stored in both queues.

**Comment by incarosegit** [comment]
@dergraf  Thanks, now its clear.
queues are created only when a client subscribes to a topic with qos > 0, and created per client.
