### ISSUE TITLE
What about the offline storage?

### ISSUE THREAD

**Issue by w3hacker** [erlio/vernemq#21]
I want to store offline message to disk, like leveldb or mysql. What should I do?

**Comment by dergraf** [comment]
Currently everything is stored in LevelDB (Subscriptions and persisted messages). Currently missing is a way to replicate the offline messages among the nodes in the cluster.

**Comment by w3hacker** [comment]
Thanks. That's great.

**Comment by dergraf** [comment]
you're welcome! :)
