### ISSUE TITLE
WebHooks questions

### ISSUE THREAD

**Issue by incarosegit** [erlio/vernemq#210]
Hi;
Some of the WebHooks includes the "payload" field in the json requests and response.
MQTT "payload" is defined as binary, but on json we cannot send binary data ( only if we base64 it ).
How the webhook will represent the payload if it is binary ?

The webhook content-type is application/octet-stream, it should be application/json ( or similar ) if it carries json structure data.

Thanks

**Comment by larshesel** [comment]
Thanks for reporting - I just pushed a commit changing the content-type to 'json/application' to the master branch of the webhooks repo. We'll track the payload question there to avoid duplicate discussions.
