### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by amolm-cuelogic** [erlio/vernemq#211]
Hi Guys,

I have set up vernemq broker on AWS EC2 instance. I'm doing load testing on vernemq using mqq malaria. But its giving me **"[Errno 104] Connection reset by peer"** error for following mqtt malaria command. 

I checked with EC2 CPU usage but it is under the threshold limit. As per mqtt command it should publish 2500 messages to vernemq broker (500 * 5) but On vernemq its logging around 2000 messages only. 

**MQTT malaria Command -** 
./malaria publish -P 5 -n 500 -H <host> -p <port>  -s 100  -T 1 -q 0

**I have changed some of vernemq configuration settings to following -** 
listener.nr_of_acceptors = 1000
max_online_messages = -1
listener.max_connections = 10000
listener.nr_of_acceptors = 1000

VerneMQ is running on single node. I tried with custom pythin mqtt code but still its same.

It would be really helpful if you guys can share your thoughts on this issue.

Thanks,
Amol

**Comment by ioolkos** [comment]
Hi @amolm-cuelogic thanks for testing.
I just tried to make MQTT malaria work on my Linux laptop without luck, so currently I cannot investigate this (but I will later).

**Comment by ioolkos** [comment]
Ok, made MQTT malaria work (have to use the -t option apparently).

Your command works for me (sending 5msg/s). So I don't know what causes the [Errno 104] right now for you on EC2.
Maybe you see sth in the VerneMQ logs?

**Comment by amolm-cuelogic** [comment]
Thanks @ioolkos for looking into this. I really appreciate your help. 

I will check with mqtt malaria and vernemq logs again. I will update this thread with my findings.

**Comment by amolm-cuelogic** [comment]
One more thing, I want to setup vernemq for 20K concurrent connections. Can you please share your thoughts on which things I need to change at vernemq to achieve 20K concurrent connections. Do I need to play around nodes or cluster to achieve it.

**Comment by larshesel** [comment]
Hi @amolm-cuelogic a single vernemq node can (depending on the hardware, message rates and sizes of course) support hundreds of thousands of connections, so there should be no need for clustering to achieve it.

Besides configuring VerneMQ, you may need to tune some things in your OS to support that number of connections (file limits etc), you can see how here: http://vernemq.com/docs/misc/change-open-file-limits.html

On the VerneMQ side I think you just need to set `listener.max_connections` high enough.

**Comment by amolm-cuelogic** [comment]
I resolved the "connection reset by peer" issue. It was due to "Change Open Files Limit" , I made it to suggested by vernemq. I followed instructions from https://vernemq.com/docs/misc/change-open-file-limits.html . 

By fixing  "Change Open Files Limit" issue , Now I am very much able to test EC2 vernemq message broker load/performance.

 @ioolkos , @larshesel  - Thank you guys.

**Comment by ioolkos** [comment]
@amolm-cuelogic great, I'll close this issue then.
Let us know how your further testing goes! :)
