### ISSUE TITLE
Leaving the cluster originates error message.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#212]
I have two nodes, named

```
vmq@vernemq-0.default.svc.cluster.local
vmq@vernemq-1.default.svc.cluster.local
```

When I execute `vmq-admin cluster join discovery-node="vmq@vernemq-0.default.svc.cluster.local"` everything runs OK and the nodes form a cluster. However, when I run `vmq-admin cluster leave node="vmq@vernemq-1.default.svc.cluster.local" -k -i 5 -t 120` I get the message

> Node 'vmq@vernemq-1.default.svc.cluster.local' is not responding to pings.

Both nodes are running in Docker containers in a Kubernetes cluster, and clustering works OK because I can cluster the nodes in the first place. The error message only shows up when I try to make `vernemq-1` leave the cluster. @dergraf @ioolkos do you have any idea of what can be causing this?

**Comment by ioolkos** [comment]
Hi @testark 
so is vernemq-1 effectively stopped at that point?

**Comment by testark** [comment]
@ioolkos I can't really say... `vmq-admin` says the node is stopped, but there are running processes (`ps aux` shows all the processes originally spanned by `vernemq start`).

**Comment by testark** [comment]
Just found out this was a problem caused by me forcibly killing the wrong process, so it's not an issue with VerneMQ. I apologize (I'm running 0.14.2, BTW) :-)
