### ISSUE TITLE
vmq_bridge does not accept hostnames, only IPs

### ISSUE THREAD

**Issue by drf** [erlio/vernemq#215]
In vernemq.conf, bridge.ssl.br0 or bridge.tcp.br0 accepts a host:port map to connect to a bridge. Unfortunately, it appears this field accepts an IP only instead of a hostname. The following error is logged.

> 16:41:14.955 [error] Error generating configuration in phase transform_datatypes
> 16:41:14.955 [error] Error transforming datatype for: bridge.ssl.br0
> 16:41:14.955 [error] "rabbit:1883" cannot be converted to a(n) IP

As you can see already, this is especially a problem in load-balanced environments or (even worse) when using docker networking.

**Comment by ioolkos** [comment]
Hi @drf, thanks, yes that's true. The cuttlefish (config lib) datatype is currently an IP/Port combo.
@dergraf is there some way out of this, or some trick?

**Comment by drf** [comment]
@ioolkos , I had a quick look at cuttlefish and they don't have any datatype for a hostname+port combination. I think the only sensible solution might be converting the datatype from "ip" to "string", and maybe check during the plugin startup if it matches a hostname/ip:port with a regexp. Don't see many other ways out of this tbh

**Comment by dergraf** [comment]
This should be a string, makes more sense.

**Comment by drf** [comment]
@dergraf Will be on it tomorrow then! :)

**Comment by drf** [comment]
Ok, I admit my limited knowledge of Erlang won't get me past changing the schema :/ so if anybody else could pick this up, it would be awesome.

**Comment by drf** [comment]
Nevermind, I should have made it.
