### ISSUE TITLE
support for Pin64

### ISSUE THREAD

**Issue by njordr** [erlio/vernemq#219]
Hi.

I know Pine64 is not supported, but it would be great to have it running also on that board (I want to use it for an home automation system)

I try several way to compile the vernemq source code. With the following I can reach the end of the compilation phase, but it gives me an issue with the nif library when I try to start it (probably it's for a path misconfiguration, but I don't know erlang):

Install the following packages (ubuntu xenial):
    
```
libssl-dev 
libncurses5-dev
openjdk-8-jre-headless
openjdk-8-jdk-headless
git
libsnappy-dev
erlang erlang-dev
```

```
git clone git://github.com/erlio/vernemq.git
cd vernemq
make rel
```

```
vi _build/default/lib/eleveldb/c_src/build_deps.sh (commented the following lines to avoid an issue with libsnappy)
# if [ ! -d snappy-$SNAPPY_VSN ]; then
#     tar -xzf snappy-$SNAPPY_VSN.tar.gz
#     (cd snappy-$SNAPPY_VSN && ./configure --prefix=$BASEDIR/system --libdir=$BASEDIR/system/lib --with-pic)
# fi

# (cd snappy-$SNAPPY_VSN && $MAKE && $MAKE install)

# export CFLAGS="$CFLAGS -I $BASEDIR/system/include"
# export CXXFLAGS="$CXXFLAGS -I $BASEDIR/system/include"
# export LDFLAGS="$LDFLAGS -L$BASEDIR/system/lib"
# export LD_LIBRARY_PATH="$BASEDIR/system/lib:$LD_LIBRARY_PATH"
```

```
vi _build/default/lib/eleveldb/c_src/eleveldb.cc
line 243
from
size_t memory_sz;
to
unsigned long memory_sz;
```

```
make rel
```

```
vi _build/default/lib/eleveldb/c_src/leveldb/port/atomic_pointer.h
line 96 add (otherwise it can compile for the Pine64 arch)
inline void MemoryBarrier() {
  // See http://gcc.gnu.org/ml/gcc/2003-04/msg01180.html for a discussion on
  // this idiom. Also see http://en.wikipedia.org/wiki/Memory_ordering.
  __asm__ __volatile__("" : : : "memory");
}
#define LEVELDB_HAVE_MEMORY_BARRIER
```

```
vi _build/default/lib/eleveldb/c_src/Makefile
line 38
# LDFLAGS += -shared leveldb/libleveldb.a system/lib/libsnappy.a -lstdc++
LDFLAGS += -shared leveldb/libleveldb.a -lstdc++
```

```
vi _build/default/lib/mzmetrics/c_src/mzmetrics_nif.c
line 67
// unsigned int align_num_resources(unsigned int num)
static unsigned int align_num_resources(unsigned int num)
```

```
vi _build/default/lib/mzmetrics/c_src/mzmetrics_counters_no_preallocation.c
line 6
// #include <cpuid.h>
line 36
// #ifdef __linux__
from line 38
/* #else
    unsigned int eax, ebx, ecx, edx;
    if (!__get_cpuid(1, &eax, &ebx, &ecx, &edx))
        return 0;
    return 0;
#endif */
```

When I run it I've got the following error:

```
cd _build/default/rel/vernemq/
./bin/vernemq console

08:02:32.188 [warning] The on_load function for module eleveldb returned {error,{load_failed,"Failed to load NIF library: '/usr/src/apps/vernemq/vernemq/_build/default/rel/vernemq/bin/../lib/eleveldb-2.0.2+build.498.refbc30c2c/priv/eleveldb.so: undefined symbol: _ZN6snappy13RawUncompressEPKcmPc'"}}
08:02:32.189 [error] CRASH REPORT Process <0.97.0> with 0 neighbours exited with reason: call to undefined function eleveldb:validate_options(open, [{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,...},...]) in gen_server:init_it/6 line 352
```

Hope you can help me

**Comment by ioolkos** [comment]
Hi @njordr great effort! :+1: 

Have you compared this against the build on Raspberry ('make rpi32')?
I have the strange feeling that I have seen this error, in playing around on the RPi. 

@larshesel does this ring a bell?

**Comment by larshesel** [comment]
This error doesn't ring a bell, I'm afraid. But I did notice this:

```shell
vi _build/default/lib/eleveldb/c_src/Makefile
line 38
# LDFLAGS += -shared leveldb/libleveldb.a system/lib/libsnappy.a -lstdc++
LDFLAGS += -shared leveldb/libleveldb.a -lstdc++
```

This means you're not linking against snappy which explains that the symbols for snappy are not found at runtime. Try and re-add the `system/lib/libsnappy.a` to the LDFLAGS.

**Comment by njordr** [comment]
Hi @larshesel 

This is why I commented the link to snappy lib:

cc: error: system/lib/libsnappy.a: No such file or directory
Makefile:58: recipe for target '/usr/src/apps/vernemq/vernemq/_build/rpi32/lib/eleveldb/c_src/../priv/eleveldb.so' failed
make[1]: *** [/usr/src/apps/vernemq/vernemq/_build/rpi32/lib/eleveldb/c_src/../priv/eleveldb.so] Error 1
make[1]: Leaving directory '/usr/src/apps/vernemq/vernemq/_build/rpi32/lib/eleveldb/c_src'
===> Hook for compile failed!

@ioolkos I try to copile for rpi32 but I've got the same error. This is why a bell ring in your head https://github.com/erlio/vernemq/issues/175 :)

**Comment by larshesel** [comment]
Could you do a fresh build without any changes and post the entire compile output so we can see what the problem with compiling libsnappy (or other things) is?

**Comment by njordr** [comment]
I'm going to try in few minutes

In the meantime I try to totally disable link to snappy lib, modifying the files above and the file:
_build/rpi32/lib/eleveldb/c_src/leveldb/build_detect_platform
line 175 changed to
if [ "$?" = 355 ]; then

in this way I've got vernemq up & running:
09:39 [root@cerbero:vernemq] 15s # ./bin/vernemq ping 
pong

But I don't know if I broke everything :D 

I'll send the clena compilation logs in few minutes

**Comment by njordr** [comment]
Attached the make rpi32 output.

The error is related to an old build_detect_platform script. If you update it, it fails because it cannot recognize the platform

[make.txt](https://github.com/erlio/vernemq/files/566069/make.txt)

**Comment by larshesel** [comment]
alright - since we don't have a pine64 board we're in a bad position to fix this and support that board in general. We would of course be happy to accept a PR fixing this issue.

I suppose you, by disabling snappy completely, have a working solution?

**Comment by njordr** [comment]
it seems, I want to make the benchmarking tests to sign it off

Which is the role of snappy libraries?

**Comment by larshesel** [comment]
Snappy is a compression/decompression library used by leveldb. Without it I suppose none of the data stored in leveldb is compressed in any way (neither in-mem or on disk). What that means for performance I have no idea, but in any case I wouldn't expect too much in terms of performance on any arm board using sd-cards as storage ;-)

**Comment by njordr** [comment]
ahahahahahah, great and thanks for the support

**Comment by larshesel** [comment]
You're welcome, let's know if you run into other issues!
