### ISSUE TITLE
auth plugin for SQL databases?

### ISSUE THREAD

**Issue by xros** [erlio/vernemq#22]
Is there any auth plug for SQL databases, such as postgresql, mysql, couchbase, and even mongodb. 

Because with username/password stored only in a file that is so insecure. 

the table for user credentials may look like this:
> username | password
> someone  | 342EWRfsdofuik.qewr#@%@$

The password is encrypted. In the auth plug should be a procedure of encryption when comparing two hashed passwords.

I haven't found any for vernemq yet.

**Comment by ioolkos** [comment]
Sorry to have kept you waiting! We're certainly planning a postgres auth plugin, and we'll use this as a plugin development example. Blog post  forthcoming (but not immediate).
