### ISSUE TITLE
Extracting common name from client certificate is not working

### ISSUE THREAD

**Issue by erikvda** [erlio/vernemq#220]
I would like to use vernemq using client certificate authentication. Therefore I created the necessary CA certificate, server certificate and client certificate for testing purposes. 

According to the documentation I expect when setting both options below to "on" it would extract the common name from my client certificate en replace the original username (blank) with it. So that afterwards vmq-passwd and vmq-acl use the common name for authentication and authorization.

_listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on_

However I experience a different behaviour:

Correct username & password & valid client certficate:
==> Success

valid client certficate & blank username password
==> 2016-11-03 11:42:20.082 [warning] <0.330.0>@vmq_mqtt_fsm:check_user:516 can't authenticate client {[],<<"MQTT_FX_Client">>} due to [{error,not_authorized}]

Correct username & password & no client certficate: ==>
==> 2016-11-03 11:44:11.594 [error] <0.383.0> SSL: certify: ssl_alert.erl:93:Fatal error: certificate unknown

So it looks like the replacing is not happening. 

vernemq version: 0.14.2
OS: Ubuntu 16.04.1 LTS

**vernemq config:**
allow_anonymous = off

listener.tcp.default = 0.0.0.0:1883

listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile = /etc/vernemq/cacerts.pem
listener.ssl.certfile = /etc/vernemq/cert.pem
listener.ssl.keyfile = /etc/vernemq/key.pem
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on

**Comment by dergraf** [comment]
hi @erikvda 
Thanks for reporting! Your expectations are correct. However I don't see a reason why it shouldn't work for you as the logs you're seeing indicate that it took the right path, but it failed to extract the common name . (https://github.com/erlio/vmq_server/blob/master/src/vmq_ssl.erl#L20)

Can you validate yourself or send us the client certificate so we can check if the extraction works as expected? 

Cheers,
Andre

**Comment by dergraf** [comment]
Is a bug, fixed in the PR https://github.com/erlio/vmq_server/pull/111

**Comment by larshesel** [comment]
This is included in current master and is part of the next release.
