### ISSUE TITLE
Timeline to support consumer session balancing across different cluster nodes

### ISSUE THREAD

**Issue by hijklmno** [erlio/vernemq#221]
Hi VerneMQ team,

Is support for consumer session balancing across different cluster nodes on the roadmap? As in, if I subscribe on node 1 with clientId `subber1` and subscribe on node 2 with clientId `subber2` on the same topic, will the message be distributed between `subber1` and `subber2`?

Thanks again!

**Comment by larshesel** [comment]
Hi @hijklmno, sorry for the slow response. we were working on a feature like this but we haven't had time to finish it yet, as we've had to prioritize other things. For the the moment it doesn't have too high priority, so it's hard to say when it will be completed.

May I ask why you need this feature? It is already possible to do session sharing on a single node (i.e., connecting multiple clients using the same client-id by setting the `allow_multiple_sessions = true` and `queue_deliver_mode = balance` in the vernemq.config - or for a specific client in a plugin). This should work fine for message flows up to about 20-25K msgs/s, depending on the hardware of course.

**Comment by hijklmno** [comment]
No worries, thank you for your response @larshesel. 

The biggest reason is uptime. We run our infra on AWS, and for production ready systems, we require at least two running instances of anything, in different availability zones. Hosting on cloud providers biggest downside is that their servers can go down at any time, for any reason. While it is possible to only have one instance of verne with session sharing on a single node, and auto launch a new instance in case the instance goes down, the downtime in between does not fit our SLA.

**Comment by dergraf** [comment]
duplicate #230

**Comment by larshesel** [comment]
Hi - we just merged this feature into master and it's available in the nightly builds. See http://vernemq.com/docs/configuration/shared_subscriptions.html and https://github.com/erlio/vernemq/blob/master/changelog.md#nightly-will-become-next-release
