### ISSUE TITLE
Make SSL Certificate verification Depth configurable to support intermediate CA

### ISSUE THREAD

**Issue by drf** [erlio/vernemq#222]
When dealing with some setups, it is common to have a Root+Intermediate CA signing client certificates for peer verification. Instructions on how to generate one can be found here: https://jamielinux.com/docs/openssl-certificate-authority/index.html

In RabbitMQ, when dealing with these kind of setups, it is possible to configure the verification depth of the client certificate (see https://www.rabbitmq.com/ssl.html , section "Certificate Chains and Verification Depth") to allow the CA chain to work correctly. In VerneMQ this is not possible, and generating a server/client certificate pair with the aforementioned guide results in

`[error] SSL: certify: ssl_alert.erl:93:Fatal error: unknown ca`

VerneMQ should expose a similar configuration option to allow these setups to work.

**Comment by larshesel** [comment]
Hi @drf thanks a lot for opening the issue and creating a PR - it's very much appreciated. We're a bit busy at the moment but will take a look at this as soon as possible.

**Comment by namjithwisilica** [comment]
Shall we use any third party Signed certificate like godaddy?
