### ISSUE TITLE
About on_offline_message

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#225]
Hi!
When the mqtt client offline, I want to send the payload to the client's mobile by using apple apns or google gcm/fcm.
But ```on_offline_message/1``` only have SubId, does not have other info.
I add ```on_offline_message5/5```,  Could you review this pr:
https://github.com/erlio/vmq_server/pull/116
https://github.com/erlio/vmq_commons/pull/19
The plugin:
```
on_offline_message5({_MountPoint, ClientId}, QoS, Topic, Payload, IsRetain) ->
    apns:send_message(apns, ClientId, Payload),
    %%Or Google Fcm Gcm
    ok.
```
Or maybe you can give some advice about this issue.

**Comment by larshesel** [comment]
Hi @dcy sorry for not getting back to you earlier. 

I like the idea of passing more data to the callback - I don't think we'd want to introduce a new hook, though.

I would think there are a couple of other hooks where we could add these extra parameters as well.

One way forward as I see it would be to deprecate the `on_offline_message/1` and add the `on_offline_message/5` callback definition in vmq_commons and call both versions from the relevant call sites in vmq_server. Alternatively we could just do this as a breaking change before 1.0. @dergraf what do you think?

**Comment by dcy** [comment]
I don't change ```on_offline_message/1``` to ```on_offline_message/5``` because maybe some people are using ```on_offline_message/1```. This change will make their old code does not work

**Comment by dergraf** [comment]
@dcy, @larshesel i am for removing `on_offline_message/1` in favor of `on_offline_message/5`.

**Comment by dcy** [comment]
@dergraf I changed my pr to ```on_offline_message/5```, maybe you can review it.
https://github.com/erlio/vmq_server/pull/116
https://github.com/erlio/vmq_commons/pull/19
