### ISSUE TITLE
vernemq-0.15.1 ssl config file error

### ISSUE THREAD

**Issue by tanpinsiang** [erlio/vernemq#226]
I compiled vernemq-0.15.1 on Erlang 19, the default config file work fine under `/bin/vernemq config generate -l debug` but after changing `listener.tcp.default` to `listener.ssl.default`, it does not work. This work on version 0.14.2.

Original config line:
listener.tcp.default = 127.0.0.1:1883
> ./bin/vernemq config generate -l debug
`16:20:42.920 [debug] Running translation for vmq_bridge.registry_mfa`
`16:20:42.920 [debug] Running translation for vmq_bridge.config`
`16:20:42.949 [debug] Running translation for vmq_plugin.default_schema_dir`
`16:20:42.949 [debug] Running translation for vmq_server.queue_deliver_mode`
`16:20:42.949 [debug] Running translation for vmq_server.queue_type`
`16:20:42.949 [debug] Running translation for vmq_server.reg_views`
`16:20:42.949 [debug] Running translation for vmq_server.persistent_client_expiration`
`16:20:42.949 [debug] Running translation for vmq_server.listeners`
`16:20:43.049 [debug] Running translation for vmq_server.tcp_listen_options`
`16:20:43.049 [debug] Applied Translations`

after replacing that line with
listener.ssl.default = 127.0.0.1:1883
> ./bin/vernemq config generate -l debug
`16:24:45.248 [debug] Running translation for vmq_bridge.registry_mfa`
`16:24:45.248 [debug] Running translation for vmq_bridge.config`
`16:24:45.277 [debug] Running translation for vmq_plugin.default_schema_dir`
`16:24:45.277 [debug] Running translation for vmq_server.queue_deliver_mode`
`16:24:45.277 [debug] Running translation for vmq_server.queue_type`
`16:24:45.277 [debug] Running translation for vmq_server.reg_views`
`16:24:45.277 [debug] Running translation for vmq_server.persistent_client_expiration`
`16:24:45.277 [debug] Running translation for vmq_server.listeners`
`16:24:45.318 [debug] Running translation for vmq_server.tcp_listen_options`
`16:24:45.319 [error] Error generating configuration in phase apply_translations`
`16:24:45.319 [error] Error running translation for vmq_server.listeners, [error, function_clause]`

more information on software versions:
Kernel: 4.4.0-47-generic
OS: Ubuntu 16.04
Erlang: Erlang/OTP 19 [erts-8.1] [source-e7be63d] [64-bit] 

Edit: Does not work on Erlang 18 too. (recompiled and run)
Erlang: Erlang/OTP 18 [erts-7.3.1] [source-25741fd] [64-bit]

Thank you 
Have a great weekend! :)

**Comment by ioolkos** [comment]
Hi @tanpinsiang thanks a lot for testing! :)
Apparantly yes, there is some config error for wss and ssl listeners. I currently do not know why.
We'll look into it.

cc. @dergraf @larshesel

**Comment by dergraf** [comment]
It's certainly related to the introduction of `listener.ssl.depth`. working on it.
