### ISSUE TITLE
suggestion: MQTT Client Load Balancing with Shared Subscriptions

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#230]
Hi!
http://www.hivemq.com/blog/mqtt-client-load-balancing-with-shared-subscriptions/
Shared Subscriptions are a non-standard-MQTT feature, but it is usefull for some use cases.
Maybe it is good for VerneMQ to support this feature.

**Comment by larshesel** [comment]
Hi @dcy this is something we've been considering and may well introduce in the future. It doesn't have super high priority at the moment, but if someone would like to sponsor or contribute this feature that would be fantastic.

**Comment by mmindenhall** [comment]
In case it matters, this isn't something that Hive is doing in isolation...this feature has been added to a recent working draft of the MQTT v5 standard: https://issues.oasis-open.org/browse/MQTT-234.

**Comment by larshesel** [comment]
Hi all! Good news, we've been discussing this internally again and we'll be working on bringing shared subscriptions to VerneMQ in the near future ;)

**Comment by perotom** [comment]
@larshesel i think this feature is highly important for distributed systems. Any updates when this feature will be available? I am really looking forward in using your broker in production with this feature.

**Comment by larshesel** [comment]
Hi @perotom the feature is being worked on as we speak. With some luck it'll go into review this week.

**Comment by larshesel** [comment]
Hi - we just merged this feature into master and it's available in the nightly builds. See http://vernemq.com/docs/configuration/shared_subscriptions.html and https://github.com/erlio/vernemq/blob/master/changelog.md#nightly-will-become-next-release

**Comment by dcy** [comment]
@larshesel Thank for the effort.
In the document, ```currently only members of a shared subscription that are online are considered for for delivery```. Maybe there is an plugin hook to tell me this msg has no online member to dilivery, so i can handle it by another way.

**Comment by larshesel** [comment]
Hi @dcy there are currently no hooks for that. As mentioned, this behaviour may change (and be made configurable). Do you need the messages to be stored in the offline queue?

**Comment by dcy** [comment]
It is better to choose by configure.
Because when i send msg to another server by ```shared subscriptions```,  if there is no online clients(myabe the server restart or crash), it will lost the msg.
It is better to have offline msgs; 
Or a hook to tell me then i can send it to another topic(not shared subscriptions) or handle it by another way. 
Then the msg will not lost

**Comment by larshesel** [comment]
Yes, you're of course right that the ability to store the messages in offline queues should be possible. It does have some other implications on for instance the ordering of the messages. I'm sure we'll make it configurable.

**Comment by larshesel** [comment]
@dcy we just merged a change to the subscriber groups so we now by default first deliver the message to online queues, then if that fails we deliver to offline queues (if any are present).

**Comment by Llorx** [comment]
@larshesel Which VerneMQ version has that feature? Because I had a weird problem and not having that feature will explain it.

**Comment by larshesel** [comment]
@Llorx VerneMQ has has Shared Subscriptions since before version 1.0.

**Comment by Llorx** [comment]
@larshesel Thank you for the answer, but I was talking about the "online groups" feature you mention on Jan 22, 2017 xD

**Comment by larshesel** [comment]
That has been there since before 1.0 (1.0.0rc1 to be specific) as well. Delivery is first attempted to any online queues and afterwards to offline queues.

**Comment by Llorx** [comment]
Ok, then I must look further into the problem I had. Thank you!
