### ISSUE TITLE
Force Client Session Expiration

### ISSUE THREAD

**Issue by drf** [erlio/vernemq#234]
Hi,

we are facing a use case where we want to force the Client Session expiration from the server side when a specific event happens. Is this a planned feature? Would it be material for a plugin? If so, does the server already expose primitives for expiring the session or would the plugin need to interact with the persistence DB directly?

We'd be happy to contribute this feature given some guidance!

**Comment by prettynatty** [comment]
I have the same questions for force client unsubscribe.

**Comment by ioolkos** [comment]
Thanks @drf and @prettynatty, those are very interesting questions/remarks.
I think this could be some sort of "on behalf of" functionality, where some authority can issue unsubscribes or disconnects for any given clients. 

The other possibility is some sort of full blown continuous access control, that could revoke access given certain conditions.

I can't say this is a planned feature right now, but I really think it's worth reflecting on that and develop a general solution that can cover more than just one use case.

@dergraf, @larshesel  can you comment on specifically expiring a session & on how to layout this as a plugin?

**Comment by dergraf** [comment]
Hi @drf, cc: @prettynatty 

First, the functionality isn't there yet. I can give you an idea on how we've planned to implement such 'administrative' features:

As you might have seen we're using `clique` for building the CLI tool `vmq-admin`. We think such commands belong into `clique` and therefore will be accessible via `vmq-admin` right away. Quite some time ago I was working on a `clique` wrapper that exposes all functionality registered in `clique` to an HTTP endpoint. This enables that VerneMQ can be completely controlled via HTTP and JSON. At this point I struggled with some automatic transformations of `clique` responses (mainly tables) into JSON format. 

If you think that using HTTP could be interesting for your usecase, and you want to go down that route of implementing the functionality in clique, and improving the clique-json-transformators, we'd certainly appreciate your contribution. :) I could start a new branch here on erlio/vernemq which includes the old stuff I did a while back and we can start from there.

What do you think?

**Comment by drf** [comment]
Hi @dergraf ,

I think your solution makes complete sense and it's the way to go - in the end, it's pretty obvious the best idea is to expose management features both to external automations and manual interventions.

If you could open that branch it would be great I think, then we can find out who wants to work on this and start giving out some contributions.

**Comment by dergraf** [comment]
@drf I haven't had time yet to create a clean branch on erlio/vernemq.
https://github.com/dergraf/vmq_server/tree/vmq-admin-http-json is the old branch on my personal fork, which we would have to incorporate into erlio/vernemq .

**Comment by dcy** [comment]
It is better if there are api for there user case:

1. get client online state

1. get the topics which clinet subscript

1. make client subscript or unsubscript topics

1. publish something to topic

**Comment by dergraf** [comment]
@dcy eventually we're getting there, currently you've to do it the way you're doing it right now ;)

**Comment by drf** [comment]
@dergraf I'll give it a try over the next days, maybe I'll get your previous work suitable for a PR, and we can move it from there.

**Comment by dergraf** [comment]
@drf I think the foundation of the HTTP API is here! #246 :)

**Comment by drf** [comment]
Great, thanks a lot! :) This means I'll take the vacations to get going with adding more features to vmq-admin then... ;)

**Comment by drf** [comment]
Ok so - this has become a hot topic again, but we'd like to tackle it from a different perspective. Paging @rbino as I'm working together with him on this one.

Basically, having an explicit cache invalidation doesn't sound a good idea when you repeat it often enough, especially because Verne already allows forcing a clean session in the authentication hook. In our view, the workflow should be

* Make sure the hook forces a clean session next time the client attempts a connection
* If a client is connected, disconnect it to make sure we're starting on the right page

In this scenario, what's missing is the capability of forcing a disconnection from a plugin, and this is what we'd like to add in the end. The plan could be exposing it from Verne's public APIs (which would allow this to be added to the HTTP API if deemed useful).

@larshesel , @dergraf what do you think?

**Comment by drf** [comment]
Just to expand what I've written - in our view every hard decision on several things (topic ACLs, session management, etc...) should be taken during the connection phase, in which we're in a sort of safe space where we're not losing data or in between in flight messages. And given how you guys implemented the authorisation hook, I guess we're quite on the same page :)

The rationale is that any harsh decision (e.g.: forcing topic unsubscription, changing ACLs, etc...) should be taken upon a connection, hence by adding an explicit disconnect function we can force the broker to reevaluate the client's policies/status in the safest and possibly best way while staying safe - e.g.: what would happen if I force unsubscribe a client while a message is in flight? The disconnect + clean cache scenario would make this an entirely predictable scenario where data is lost, but the disconnect decision can be taken with no unintended side effects.

**Comment by trarbr** [comment]
I am also interested in something like this: When some event happens, I want to force a client to disconnect. Having an HTTP hook would be nice, but I would also like to be able to trigger it from inside a plugin. My current solution sends a `:disconnect` message to the session process. I don't believe this is an official API though, but having some way to do it from a plugin would be nice.

**Comment by larshesel** [comment]
Hi @drf thanks for the proposal.

A disconnect feature is something which has been requested for a long time. So I think we should build this - and I think it's a good, simple and solid way to 'reevaluate' auth data instead of dynamically changing things without the knowledge of the client. To support the `clean_session=false` case the disconnect should be able to discard all state, which would also mean that upon the subsequent connect the client would receive connection flag `session_present=false`.

To do this we'd need to build (I think):

1. A API to find the session pid / queue pid based on mountpoint and client-id. This can be done using `vmq_ql`.
2. An API which tells the client to disconnect with optional parameters telling if the state should be discarded or not. If the state should be discarded then it I think the easiest is to set the queue state to `clean_session=true` and disconnect the session process which should cause all state to be cleaned out.

This API should be added to the https://github.com/erlio/vernemq_dev repo and be exposed as a proper API.

Does that make sense? I could make a prototype tomorrow, maybe - the hard part would be to make the API as this of course can't be changed later...

**Comment by drf** [comment]
Hi @larshesel , I entirely agree with what you said - especially the "discard state" on disconnection would make everything way easier and remove the requirement for a specific authorization hook, so definitely an improvement over what I planned. The implementation plan is sound as well, at least to me.

We're of course happy to help (even though we're more Alchemists than Erlang guys :D), so if you plan on crafting a more detailed action plan and there's some items you'd like to give out, we can try and do something.

**Comment by rbino** [comment]
I agree with @drf, the implementation plan is sound, if you have tasks to assign I'd be glad to help, I have more experience with Elixir but I wouldn't mind looking under the hood in the Erlang world

**Comment by larshesel** [comment]
Hey - I created a WIP PR erlio/vernemq_dev#2. As mentioned within we should discuss:

* is the API good - could it be improved? Should it be more general? ...
* how can we add the missing pieces to discard the state
* other things??

The code is in this https://github.com/larshesel/vernemq_dev/blob/new_api_functionality/src/vernemq_dev_api.erl file.

I generated edoc for this as well, see the doc directory on the PR branch.

**Comment by larshesel** [comment]
Guess this can be closed after we added the disconnect by client-id into `vernemq_dev` a while ago.
