### ISSUE TITLE
Subscribing to certain topics crashes the client connection

### ISSUE THREAD

**Issue by hennejg** [erlio/vernemq#236]
We are using a topic called monitoring/warnleuchte/state. If we subscribe to this topic (e.g. using MQTTSpy), the client connection is immediately terminated and the following messages are logged:

> 2016-12-05 18:22:05.481 [error] <0.1629.0> Ranch listener {{0,0,0,0},1883} terminated with reason: {case_clause,[{{[],[<<"monitoring">>,<<"warnleuchte">>,<<"state">>]},<<"off">>,false}]}
> 2016-12-05 18:22:10.991 [error] <0.1636.0> CRASH REPORT Process <0.1636.0> with 0 neighbours crashed with reason: no case clause matching [{{[],[<<"monitoring">>,<<"warnleuchte">>,<<"state">>]},<<"off">>,false}] in vmq_retain_srv:match_fold/4 line 91

Subscribing to monitoring/warnleuchte/#, monitoring/warnleuchte/foobar or any other topic (as far as I can tell) etc. works flawlessly. However, I cannot tell what exactly makes this topic problematic.

**Comment by ioolkos** [comment]
@hennejg Thanks for reporting this 'interesting' behaviour/bug...!
@dergraf do we crash the retain_srv fine here? Root cause has to be some retain message behaviour?

**Comment by dergraf** [comment]
@ioolkos yep, it's related to the retain server. Looking into it. 

@hennejg what version are you using?

**Comment by hennejg** [comment]
@dergraf Thanks for your quick response! I am running 0.15.2 on Ubuntu 16.04.1 x64, installed from the package provided on your web page. What I failed to mention yesterday: vernemq is configured to run in a two-node cluster. 
Please let me know if there is anything else I can do to help you track down this bug.

**Comment by wayglem** [comment]
Hello guys,

We are experiencing the same issue here with retained messages. version 0.15.2-1 on Mint 18. 
Please let me know if I can help you to reproduce

**Comment by dergraf** [comment]
bug isolated, @larshesel is on it!

**Comment by hennejg** [comment]
You rock!

**Comment by dergraf** [comment]
Guys, I just enabled our nightly builds again, so you should be able to download the package containing this fix from: http://vernemq.com/downloads/

**Comment by wayglem** [comment]
Thanks a lot @larshesel and @dergraf it works now :-)

**Comment by dergraf** [comment]
Don't hesitate to get in touch with us over Slack http://slack-invite.vernemq.com/ or IRC! :)
