### ISSUE TITLE
Plans for ACL?

### ISSUE THREAD

**Issue by jfernstad** [erlio/vernemq#24]
Hi there, 

VerneMQ looks interesting and promising. Are there any plans to include ACL functionality, to allow access control to specific topics? 

Preferably implemented with hooks to external scripts or executables so I could e.g run a Python script to check for access when someone publish or subscribe to a topic. 

Suggestion:
The hooks would provide: user, topic and action (subscribe/publish or alternatively one hook per action)
The script would send back: True/False
For publish: Broker would ignore message on False
For subscribe: Broker would cut connection on False 

I'd write a plugin myself but I don't know Erlang (yet). ;) 

Thanks

**Comment by dergraf** [comment]
Hi there,

VerneMQ currently ships a basic file based ACL plugin named ``vmq_acl``. You could find the source code in https://github.com/erlio/vmq_acl. But yeah, you're right for larger deployments with more complex access rules you might want to implement your own plugin. 

As you might know our company is also providing commercial services for VerneMQ plugin development and support, just saying. ;)

Let me know if you need further guidance!

**Comment by jfernstad** [comment]
Thanks. File-base ACL won't work for me. 

I'll keep your support suggestion in mind. 

Thanks
