### ISSUE TITLE
Change nodename's error

### ISSUE THREAD

**Issue by dcy** [erlio/vernemq#241]
Hi!
When i change nodename and start it,
```
(VerneMQ@192.168.3.236)1> {"Kernel pid terminated",application_controller,"{application_start_failure,vmq_server,{{undef,[{vmq_subscriber,change_node_all,[[{'VerneMQ@127.0.0.1',false,[]}],'VerneMQ@192.168.3.236'],[]},{vmq_server_sup,'-maybe_change_nodename/0-fun-2-',3,[{file,\"/home/dcy/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_server_sup.erl\"},{line,70}]},{plumtree_metadata,fold_it,3,[{file,\"/home/dcy/hisir/vernemq/_build/default/lib/plumtree/src/plumtree_metadata.erl\"},{line,130}]},{vmq_server_sup,init,1,[{file,\"/home/dcy/hisir/vernemq/_build/default/lib/vmq_server/src/vmq_server_sup.erl\"},{line,46}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,287}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]},{vmq_server_app,start,[normal,[]]}}}"}
```
https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_server_sup.erl#L70
There is no function ```vmq_subscriber:change_node_all/2```
I tried to fix this by ```vmq_subscriber:change_node_all(Subs, node(), false)```
Here ```Subs``` is tuple, but https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_subscriber.erl#L162 and https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_reg.erl#L587 treat it as list.

**Comment by dergraf** [comment]
you're right that's a bug we should call `vmq_subscriber:change_node_all(Subs, node(), false)` instead. Can you submit a PR, please? 
`Subs` should be of type `[{node(),boolean(),[{topic(), qos()}]}]` which it is in both files you've mentioned.

**Comment by dcy** [comment]
@dergraf I found that changed node's Subs is tuple(```{[{node(),boolean(),[{topic(), qos()}]}], nodes()}```), and not changed node's Subs is list(```[{node(),boolean(),[{topic(), qos()}]}]```). Why would be so strange?

**Comment by dergraf** [comment]
It's not strange ;) it makes perfect sense if you think about `allow_multiple_sessions=on` which would allow the same client id to be connected to multiple nodes. In such a case the Subs would look like:
```erlang
[
  {node_a, false, [{topic(), qos()}]},
  {node_b, false, [{topic(), qos()}]}
]
```
