### ISSUE TITLE
Problem when publish large file

### ISSUE THREAD

**Issue by congbv** [erlio/vernemq#245]
Dear sir,
I have problem when try to publish text file 1.6MB by script python while true
`
#!/usr/bin/python
import paho.mqtt.client as mqtt
import time
import datetime
import threading
import os
def push_mqtt(val):
    mqttc = mqtt.Client("py_"+datetime.datetime.now().strftime('%M%S')+"_No_"+str(val))
    mqttc.connect
    mqttc.connect('10.1.10.112',1883)
    f = open("photo")
    imagestring = f.read()
    byteArray = bytes(imagestring)
    print 'starting topic '+str(val)+'\n'
    while True:
        mqttc.publish('photo', byteArray , 0)
        time.sleep(10)
thread_list = []
for i in range(1, 2):
    t = threading.Thread(target=push_mqtt, args=(i,))
    thread_list.append(t)
for thread in thread_list:
    thread.start()
`
with photo is text file 1.6MB
but It just work once, netxt time have error 
`
[Errno 104] Connection reset by peer
`

**Comment by dergraf** [comment]
Hello @congbv 

I tried to reproduce with a similar script you've posted:

```python
#!/usr/bin/python
import paho.mqtt.client as mqtt
import time
import datetime
import string
import random


N = 2097152
payload = ''.join(random.SystemRandom().choice(
    string.ascii_uppercase
    + string.digits) for _ in range(N))
payload = bytes(payload)


def push_mqtt(val):
    client_id = "py_" + datetime.datetime.now().strftime('%M%S') \
        + "_No_" + str(val)
    mqttc = mqtt.Client(client_id)

    mqttc.connect('127.0.0.1', 1883)
    print(client_id, val)
    while True:
        mqttc.publish('photo', payload, 0)
        time.sleep(10)

push_mqtt(1)
```

However I removed your threading code as this doesn't worked on my machine (??), and started the same script in two separate terminal shells. VerneMQ (current master) can handle the 2 MB payload without a problem.

**Comment by dergraf** [comment]
For the notice the `[Errno 104] Connection reset by peer` is produced by the paho MQTT client, when it loses the connection to the broker.

**Comment by congbv** [comment]
I just rebuild from master, It's Ok, 
and I use cluster throught HAProxy, It's also Ok
but I seems slow,
