### ISSUE TITLE
Publish sub-apps to hex

### ISSUE THREAD

**Issue by tsloughter** [erlio/vernemq#249]
Since you've moved all the apps to a single repo it would be great if they were each individually published to hex (or at least vmq_commons :) so that they are still able to be used as dependencies.

**Comment by ioolkos** [comment]
Thanks @tsloughter! :)
@dergraf as I understood it, vernemq_dev is new, so that it can be included for plugin development.
Does that mean we wouldn't have to publish vmq_commons to hex?

**Comment by tsloughter** [comment]
Oh interesting, i hadn't looked at that repo. But it removes the `gen_emqtt` behavior?

**Comment by larshesel** [comment]
hi @tsloughter yes, you're right - `gen_emqtt` isn't currently a part of `vernemq_dev` as we wanted the dependency to include only what is needed to build plugins for VerneMQ. To be honest, I'm not sure what we'll be doing regarding `gen_emqtt` and the `vmq_commons` we already pushed to hex.pm in june. I don't think we'll be maintaining that repo going forward. @dergraf any thoughts?

**Comment by larshesel** [comment]
Hi @tsloughter 

I don't think anything will happen about this anytime soon - the vmq_commons repo is deprecated and we won't be using resources on moving out in the foreseeable future.

We do have a wish of building a proper, better more MQTT client at some point, but at the moment it's wishful thinking: https://github.com/erlio/cptnemo

Closing this for now.
