### ISSUE TITLE
[Cluster] Node Disaster Recovery

### ISSUE THREAD

**Issue by joliveira1991** [erlio/vernemq#251]
Hi everyone,
I'm working with VerneMQ in a cluster environment. So, i have two nodes and it's really important to understand the way to migrate publishers, subscribers and messages from a node (that crashes) to another node when disaster occurs.
How can i do it? I'm using the version _vernemq_0.15.2-1_amd64.deb_.
Thanks for the support,
Best Regards,

--
João Oliveira

**Comment by larshesel** [comment]
Hi @joliveira1991 

How to do this depends on the type of crash. If a node is only temporarily crashed and comes back then things should recover automatically. If it is a non-recoverable cases where the persisted data is lost - you'd need consistent backups of the persisted data which can be restored on a new server. As this is not a per se a technical issue with VerneMQ but more a of a support/documentation question, could you get in touch with us at info@vernemq.com or by filling out the form over here for support: http://vernemq.com/services.html

Cheers,
Lars

**Comment by larshesel** [comment]
Closing this for now. Feel free to reopen or open another issue if needed.
