### ISSUE TITLE
Monitoring vernemq 

### ISSUE THREAD

**Issue by shailendra12345** [erlio/vernemq#257]
Hi,

I have setup a VerneMQ cluster and trying to monitor it. I tried with Prometheus but it doesn't show the cluster health , number of active clients etc. Next i tried grafana but it works with vmq_graphite (https://github.com/erlio/vmq_graphite) but it is obsolete package and not able to install the same. I am trying to find a proper UI where I can see all the details about cluster and nodes.
So please help regarding the issue.

**Comment by larshesel** [comment]
Hi @shailendra12345 

You get the number of active clients subtracting the `socket_close` counter from the `socket_open` counter. 

Regarding `vmq_graphite` then it's built into VerneMQ and you don't need to install any plugin to use it, just follow the docs: http://vernemq.com/docs/monitoring/graphite.html

Building a dashboard UI showing the general state of the cluster is something that we want to do, but haven't had the opportunity to give enough priority yet. We just recently released a JSON/HTTP admin interface (which basically exposes everything you can do with the `vmq_admin` command), and that can be used to query the cluster state. Until we get that properly documented you can see a demo of it over here: https://asciinema.org/a/by17s5dpitqi7qp1blm7zh2bx

Maybe @dergraf or @ioolkos want to chime in with thoughts on monitoring the cluster state?

**Comment by shailendra12345** [comment]
@larshesel 

Thanks for the reply.
One more question Can I send connect request to a cluster and cluster internally decide which node to connect rather than sending request  to particular node.

**Comment by ioolkos** [comment]
Hi @shailendra12345 
This is typically the job of a load balancer (and its configured balancing strategy). A VerneMQ cluster won't do this by itself.

**Comment by shailendra12345** [comment]
thanks @ioolkos

**Comment by codeadict** [comment]
@shailendra12345 if it is helpful i use graphite like:

```
graphite_enabled = on
graphite_host = grafana.host.com
graphite_port = 2003
graphite_interval = 20000
graphite_prefix = stats.VerneMQ
graphite_connect_timeout = 10000
```

**Comment by larshesel** [comment]
Hi @shailendra12345, I suppose I can close this issue then. Let us know if you have any other questions or issues!
