### ISSUE TITLE
Cannot compile 0.10.1

### ISSUE THREAD

**Issue by bmcustodio** [erlio/vernemq#26]
Trying to compile the `0.10.1` tag fails with the following message:

```make
===> Compiling edown
===> Compiling /home/user/tmp/vernemq/_build/default/lib/edown/src/edown_doclet.erl failed
/home/user/tmp/vernemq/_build/default/lib/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/home/user/tmp/vernemq/_build/default/lib/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen

make: *** [rel] Error 1
```

In case it helps, compilation was being made in an Ubuntu 14.04 box with

```
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
```

**Comment by dergraf** [comment]
I think* this is coming from Erlang 18, which we currently don't officially support. Could you fallback to 17.5?

* haven't verified it...

**Comment by bmcustodio** [comment]
@dergraf Just tried on my Arch Linux box with Erlang 17.5, the problem persists.

**Comment by dergraf** [comment]
Can you try with master instead of the tag? I've just seen that 0.10.1 is one commit behind master.

**Comment by bmcustodio** [comment]
@dergraf Same. The only difference was a version bump.

**Comment by dergraf** [comment]
yes you're right. just tried it on my Debian laptop with Erlang 17.5 (from Kerl) and it worked.
Is it possible that you're using the Erlang Solutions Erlang package?

**Comment by bmcustodio** [comment]
@dergraf I am, indeed.

**Comment by dergraf** [comment]
ok, for now I think the following workaround should work.
change the overrides in your ``rebar.config`` file to look like this:

    {overrides, [{override, exometer_core, [{edoc_opts, []}]},
             {override, setup, [{post_hooks, []}]},
             {override, vmq_passwd, [{post_hooks, [{compile, "make -C c_src"}]}]}]}.

This will disable the doc generation for the exometer_core application which was causing the problem. Make sure to delete ``_build/default/lib/exometer_core`` and redo a ``make rel``.

Hopefully this works.

**Comment by dergraf** [comment]
How did it go?

**Comment by bmcustodio** [comment]
@dergraf I still can't. Using both 17.5 and 18.0 from Kerl, this is what I get now as soon as I run `make rel`:

```
escript: exception error: no match of right hand side value undefined
  in function  rebar_log:log/3 (/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_log.erl, line 59)
  in call from rebar3:handle_error/1 (/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl, line 254)
  in call from escript:run/2 (escript.erl, line 752)
  in call from escript:start/1 (escript.erl, line 276)
  in call from init:start_it/1 
  in call from init:start_em/1 
make: *** [rel] Error 127
```

**Comment by dergraf** [comment]
@bmcustodio how is it going, do you think we can close this issue? How did your benchmarks go?

**Comment by joaohf** [comment]
Hi,

I think that jobs dependecy is using esl/edown 0.4 but https://github.com/uwiger/edown/commit/b7c8eb0ac1859f8fce11cbfe3526f5ec83194776 fix it.

**Comment by dergraf** [comment]
we've to check in which order rebar3 is pulling in the deps. several dependencies are having a sub dependency on edown, but all using a different version of edown. It's a mess! As we're not using edown directly (only used for documentation generation) I could live with that. But if it hinders people to properly compile VerneMQ this is a problem. @bmcustodio what is the status here? anyone else having the same problem?

**Comment by WizardLiang** [comment]
I can't build on my mac either with the same error as other guys. 
Another question:
Is there any way to install verneMQ package on Mac OS X? The official document didn't mention that.

Regards

**Comment by dergraf** [comment]
@WizardLiang is it the version 18 problem or another one?

**Comment by WizardLiang** [comment]
my erlang is version 17

**Comment by dergraf** [comment]
can you open a separate issue please... I am quite sure the error is related to MacOS. and please also make sure to use the latest 0.11.1
