### ISSUE TITLE
TLS username from CN authentication failing

### ISSUE THREAD

**Issue by gdhgdhgdh** [erlio/vernemq#262]
### Environment

- VerneMQ Version: 0.15.3
- OS: Debian Jessie (docker container)
- Erlang/OTP version (if building from source):

### Expected behavior

- `mosquitto_pub` should be able to correctly authenticate on port 8883 and publish to a topic

### Actual behaviour

```
13:29 $ mosquitto_pub -h 172.17.0.2 --cafile ca.crt --cert mosquitto_client01.crt --key mosquitto_client01-dec.key -t gdhtopic -m my_message -p 8883 --insecure -d
Client mosqpub/27332-gdh-x260 sending CONNECT
Client mosqpub/27332-gdh-x260 received CONNACK
Connection Refused: bad user name or password.
Error: The connection was refused.
```

```
2017-01-23 13:29:31.644 [warning] <0.660.0>@vmq_mqtt_fsm:check_user:527 can't authenticate client {[],<<"mosqpub/27332-gdh-x260">>} due to
                              invalid_credentials
```

Adding the CN name of `mosquitto_client01` to the `/etc/vernemq/vmq.acl` does not change the behaviour.

```
echo >>vmq.acl "user mosquitto_client01"
```

Setting `debug` logging level does not add anything useful :(

The Docker container is being launched with

```docker run -v /home/gdh/pres/vmq:/ssl -e "DOCKER_VERNEMQ_LISTENER.SSL.REQUIRE_CERTIFICATE=on" -e "DOCKER_VERNEMQ_LISTENER.SSL.CAFILE=/ssl/ca.crt" -e "DOCKER_VERNEMQ_LISTENER.SSL.CERTFILE=/ssl/vernemq.pem" -e "DOCKER_VERNEMQ_LISTENER.SSL.KEYFILE=/ssl/vernemq-key.pem" -e "DOCKER_VERNEMQ_LISTENER.SSL.REQUIRE_CERTIFICATE=on" -e "DOCKER_VERNEMQ_LISTENER.SSL.DEFAULT=0.0.0.0:8883" -e "DOCKER_VERNEMQ_LISTENER.SSL.USE_IDENTITY_AS_USERNAME=on" -e "DOCKER_VERNEMQ_LOG.CONSOLE.LEVEL=debug" --name vernemq1 -it erlio/docker-vernemq:0.15.3```

N.B. the `latest` tag on the public Docker Hub image seems to still link to 0.15.2 (and hence an older version of the init script)

I'm surely doing something wrong - can you help?

**Comment by larshesel** [comment]
Hi there - thanks for using VerneMQ and thanks for reminding us about the older version on docker hub!

I assume you have set `allow_anonymous=off`, but the plugins `vmq_acl` and `vmq_passwd` are both active. Then you need to have both authentication and authorization in place. To add user credentials so the `vmq_passwd` plugin is happy you can use the `vmq_passwd` command, see more about that over here: https://vernemq.com/docs/configuration/authentication.html. For authorization / acl you're almost there, but besides adding the user you'd need to add the allowed topics. See more about that over here: https://vernemq.com/docs/configuration/authorization.html

Let us know if this helps!

**Comment by gdhgdhgdh** [comment]
Thanks for the turbo response :) Yep I have been reading both of those pages a great deal today.

You are right that `allow_anonymous=off`:

```
root@f2b1ee33c73f:/etc/vernemq# grep -i allow_anon /etc/vernemq/vernemq.conf 
allow_anonymous = off
```

I definitely do want `vmq_acl` because the goal is to allow the user only to access a topic whose name matches their username.

Can you explain the purpose of the `vmq_passwd` command even though we are using certificates and the Common Name becomes the username? Does there still need to be a 'placeholder' user with a random / dummy password for each connecting user? Does the value of the password matter?

**Comment by larshesel** [comment]
What you can do is to set `allow_anonymous=on` and disable the `vmq_passwd` plugin. This will have the effect that VerneMQ will completely skip the `auth_on_register` hook which takes care of authenticating clients. The hooks responsible for authorizing the client will still be called as `vmq_acl` is still in place (you can see detailed information about this by running `vmq-admin plugin show`.

Note, that since the above will completely disable authentication and rely solely on client certificates, it is important to make sure that *all* untrusted clients connect using client certificates.

The purpose of `vmq_passwd` is to provide some basic authentication mechanism out of the box - which of course may not fit all use cases.

I hope that clears things up a bit!

In case you require a more complex setup, don't hesitate to get in touch regarding our development and support services. See https://vernemq.com/pricing.html.

**Comment by larshesel** [comment]
Hi, let us know if that did work for you or if you have other issues. Closing this for now.

**Comment by gdhgdhgdh** [comment]
Hullo,

Yes, thankyou - my bad for not following up. I initially implemented the `vmq_webhooks` plugin with a Python external app which worked fine, and then upgraded the approach to a trivial Erlang plugin doing the same thing with fewer moving parts.

Now both the `vmq_acl` and `vmq_passwd` plugins are disabled and things are working as expected :) It's been an interesting couple of days.

**Comment by larshesel** [comment]
Wow, that sounds great! Nice to hear that you first started out with `vmq_webhooks` as one of the intentions with that is to be able to quickly prototype stuff (or just use it if it is sufficient for the use-case).

Are you running already running Verne in production or are you planning to anytime soon? It would be really interesting for us to hear more about your use case and how you're using VerneMQ.

**Comment by gdhgdhgdh** [comment]
Not yet in production, but the numbers should be large.... I can't talk about it publicly but feel free to drop me a line. (the email address on my GitHub profile does work)
