### ISSUE TITLE
Upgrade rebar3 to newest version

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#266]
At some point we should upgrade to a newer version of rebar3. The one we're using is a pre-3.0 beta version and it seems that it is somewhat incompatible with the 3.x releases which causes issues when users are building with their own rebar3 ( for whatever reason they're doing that).

Currently almost everything seems to work with rebar 3.3.5 - except the packages we build (`make package`) seem to be broken - in particular it seems to have something to do with the `node_package` dependency.

When installing the generated package  (.deb) on and trying to start vernemq I get:

```
 /usr/sbin/vernemq: 8: .: Can't open /usr/sbin/../lib/env.sh
```

This has to be resolved before we can upgrade rebar3 to the 3.x series.

**Comment by larshesel** [comment]
being handled in #274

**Comment by larshesel** [comment]
Closed via  #274

**Comment by KnolBee** [comment]
@larshesel  still getting this issue when trying to use image built from the master, am I missing anything here?

**Comment by larshesel** [comment]
hi @KnolBee I haven't heard about anyone having this issue in quite a while. Can you open up an issue with all the details?

**Comment by KnolBee** [comment]
I may be doing wrong, correct me if I am wrong. I am trying to build the binary locally and copying it over to an ec2 system which already has 1.0.1 installed from Debian package running. I stop the existing service and run the built binary as bin/vernemq start which is giving the error. However, it works like charm on the local machine on which it was built. Do I need to copy more files to test in addition to vernemq?

**Comment by larshesel** [comment]
The `bin/vernemq` file is just a shell script for starting and interacting with vernemq - you need to copy the entire release over to the new machine, so that would be the entire `_build/default/rel/vernemq` folder.
