### ISSUE TITLE
LevelDB write sync option config

### ISSUE THREAD

**Issue by kerber** [erlio/vernemq#268]
Good day,
Can you please verify whether VerneMQ uses the sync option when writing to LevelDB, as explained by the LevelDB developer here: https://news.ycombinator.com/item?id=2526311? I've dug through the source a bit and it looks like write options can be passed in, though it is not being set directly. This makes me think the LevelDB default of sync=false is being used. If that is the case, how can I go about passing in this option? I understand that enabling this option would decrease performance, but it is important to us for the data to be durable in the event of a server crash. Thank you.

**Comment by dergraf** [comment]
Hi there,

the current default configuration is the following:
```erlang
application:get_all_env(eleveldb).
[{block_cache_threshold,33554432},
 {verify_compaction,true},
 {included_applications,[]},
 {fadvise_willneed,false},
 {eleveldb_threads,71},
 {write_buffer_size_max,62914560},
 {use_bloomfilter,true},
 {data_root,"./data/leveldb"},
 {block_size_steps,16},
 {limited_developer_mem,false},
 {total_leveldb_mem_percent,70},
 {verify_checksums,true},
 {sst_block_size,4096},
 {block_restart_interval,16},
 {sync,false},
 {compression,true},
 {tiered_slow_level,0},
 {write_buffer_size_min,31457280},
 {data,[{dir,"./data"}]},
 {delete_threshold,1000}]
```

As you can see `{sync, false}`  is the default. To configure this setting you can pass 

```ini
leveldb.sync_on_write = on
```

I hope this helps!

Cheers,
Andre

**Comment by kerber** [comment]
Thank you for the speedy response. This is exactly what I'm looking for!
