### ISSUE TITLE
Losing messages when in cluster mode

### ISSUE THREAD

**Issue by andrehp** [erlio/vernemq#272]
### Environment

- VerneMQ Version: docker-vernemq:0.15.3
- OS: Docker
- Erlang/OTP version (if building from source):

### Expected behavior

All messages sent using QoS2 should be received by the single consumer.

### Actual behaviour

Less than a third of all the messages are received by the consumer when in cluster mode with 3 nodes. If the test is run with a single node the messages are received properly.

### Test scenario

Cluster with 3 instances of VerneMQ, running a test using vmq_mzbench with 500 publishers and 1 subscriber.

Output from vmq-admin cluster status:
```
+--------------------+-------+
|        Node        |Running|
+--------------------+-------+
|VerneMQ@100.96.3.124| true  |
|VerneMQ@100.96.4.185| true  |
|VerneMQ@100.96.4.186| true  |
+--------------------+-------+
```

Script ran during tests:

```
#!benchDL

make_install(git = "https://github.com/erlio/vmq_mzbench.git",
             branch = "master")

defaults("pool_size" = 500)

pool(size = 1,
     worker_type = mqtt_worker):
            connect([t(host,"elasticloadbalancer"),
                    t(port,1883),
										t(username,"User"),
										t(password,"Password"),
                    t(client,fixed_client_id("subscriber1", worker_id())),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])
            wait(1 sec)
            subscribe("test/clients/#", 2)


pool(size = numvar("pool_size"),
     worker_type = mqtt_worker,
     worker_start = linear(200 rps)):
            connect([t(host,"elasticloadbalancer"),
                    t(port,1883),
										t(username,"User"),
										t(password,"Password"),
                    t(client,fixed_client_id("pool1", worker_id())),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])
            wait(10 sec)
            set_signal(connect1, 1)
            wait_signal(connect1, numvar("pool_size"))
            wait(5 sec)
            loop(time = 10 min, rate = 60 rpm):
                publish_to_self("test/clients/", random_binary(150), 2)
            disconnect()
```

Where elasticloadbalancer is the address of our elastic load balancer pointing to the VerneMQ instances. We are running the nodes in Kubernetes.

But if I change the parameters pool_size from 500 to 100 and rate from 60 to 10 rpm the subscriber receives all messages.

This problem really baffles me, I don't know if there is something wrong with my configuration, and I find it curious that a little under a third of the messages are received by the subscriber.

**Comment by ioolkos** [comment]
Hi @andrehp thanks for reporting!
Do you observe anything in the VerneMQ log? dropped messages?
Also: do you have any special configuration changes in vernemq.conf? 
what is the disk speed/situation for those VMs?

I'll try to test for this tomorrow.

**Comment by andrehp** [comment]
Hi ioolkos,

Thanks for the fast reply, I changed only two configurations over the default:
DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
DOCKER_VERNEMQ_MAX_ONLINE_MESSAGES=5000

The second one was a try to at least mitigate the loss of messages. The containers are running on top of a self-hosted Kubernetes cluster composed of m4.xlarge machines using standard EBS disks.

What logs should I try to look at for signals of problems?

**Comment by ioolkos** [comment]
Have a look on the `console.log`, preferably on the server where the Subscriber is connected to. Depending on how you installed VerneMQ, it's in `/var/log/vernemq` or not.

Let me know what you see there.

**Comment by andrehp** [comment]
Ok, the logs didn't show anything. But I did test the same scenario again today and there was no loss of packets. So I guess something in the environment affected the communication between the machines.

Sorry for the trouble, if I discover anything else I will update here.
