### ISSUE TITLE
is there a way for developer to add custom plugin to authorize topic access control?

### ISSUE THREAD

**Issue by zhongjin616** [erlio/vernemq#28]
currently, verneMQ do the access contol through a ACL file. but what i want is that i can control a client to write or read a topic dynamicly.  generally, i want to put the ACL in Redis instead of a file. Is verneMQ has a interface that i can use my own acl plugin?

**Comment by dergraf** [comment]
Hi there!

Sure, you've to implement a custom Redis plugin. Please have a look at this sample plugin
https://github.com/dergraf/vernemq_demo_plugin

**Comment by Assem-Hafez** [comment]
Is there any way around to allow the client to send a Http request with clients id and a message that passes through the authorization plugin  then make the broker handle sending the message to those clients?

**Comment by dergraf** [comment]
Hi there.
this is something we've on our roadmap.

**Comment by tosheer** [comment]
@Assem-Hafez are you able to get any solution to the problem you described above ? Any pointers will be helpfull.

**Comment by Assem-Hafez** [comment]
@tosheer unfortunately i didn't

**Comment by larshesel** [comment]
@tosheer what is it you would like to do? Maybe there's another way to achieve your goal. We still would like to do an HTTP api for publishing/injecting messages it just doesn't have high prio at the moment.
