### ISSUE TITLE
vmq.acl definition sensitive to formatting

### ISSUE THREAD

**Issue by hcimdea** [erlio/vernemq#284]
### Environment

- VerneMQ Version: 0.15.3
- OS: Linux (Ubuntu 16.04) from official package
- Erlang/OTP version (if building from source): N/A

### Expected behavior

- When defining topics in vmq.acl as it is a text file I expected the parsing to be insensitive to extra or the type of spaces between different tokens or values.
Example of two different entries with the same expected behaviour:

topic read myhome/myroom/mylight
topic read &nbsp; myhome/myroom/mylight

### Actual behaviour

- It seems that the extra leading space is been used as part of the topic string and clients are unable to address it unless the extra spacing is deleted.

If this is working as designed, although the documentation is rigorously correct (showing just one blank character), I think a note on this matter would be nice.

**Comment by larshesel** [comment]
Hi @hcimdea thanks for bringing the discussion here. I've been thinking a bit about the right thing to do. I guess strictly a topic should be allowed to contain spaces (IIRC any non-astral utf-8 character is allowed) and if we allow for more than one space as delimiter we can no longer say what belongs to the delimiter or to the topic. So I think either introducing string quotes or documenting our way of of this would be the best way. For now I'll go with adding a note to the docs in this case as it's the cheapest solution that won't break existing configs.

I've added a note to the docs: https://vernemq.com/docs/configuration/file-auth.html#authorization

Thanks again for reporting!

**Comment by hcimdea** [comment]
Cool. 

Thank you! 

On 2017-03-02 08:18, Lars Hesel Christensen
wrote: 

> Hi @hcimdea [1] thanks for bringing the discussion here. I've
been thinking a bit about the right thing to do. I guess strictly a
topic should be allowed to contain spaces (IIRC any non-astral utf-8
character is allowed) and if we allow for more than one space as
delimiter we can no longer say what belongs to the delimiter or to the
topic. So I think either introducing string quotes or documenting our
way of of this would be the best way. For now I'll go with adding a note
to the docs in this case as it's the cheapest solution that won't break
existing configs. 
> 
> I've added a note to the docs:
https://vernemq.com/docs/configuration/file-auth.html#authorization [2]

> 
> Thanks again for reporting! 
> 
> --
> You are receiving this
because you were mentioned.
> Reply to this email directly, view it on
GitHub [3], or mute the thread [4].
 

Links:
------
[1]
https://github.com/hcimdea
[2]
https://vernemq.com/docs/configuration/file-auth.html#authorization
[3]
https://github.com/erlio/vernemq/issues/284#issuecomment-283576179
[4]
