### ISSUE TITLE
how is the cluster forward the message across the nodes?

### ISSUE THREAD

**Issue by zhongjin616** [erlio/vernemq#29]
hi, there:

i did not find docs which explain how the vernemq cluster works. so i wonder that is vernemq meets these two strategies: 

1. A message only gets forwarded to other cluster nodes if a cluster node is interested in it。this reduces the network traffic tremendously, because it prevents nodes from forwarding unnecessary messages
2. As soon as a client on a node subscribes to a topic it becomes known within the cluster. If one of the clients somewhere in the cluster is publishing to this topic, the message will be delivered to its subscriber no matter to which cluster node it is connected.

thanks.

**Comment by dergraf** [comment]
Hi there,

you're right the documentation still needs to be improved!

This is exactly the way VerneMQ distributes the messages! :)

**Comment by zhongjin616** [comment]
great！ thanks for your active development. :)

**Comment by dergraf** [comment]
:+1:
