### ISSUE TITLE
HTTP health check

### ISSUE THREAD

**Issue by rpavlovs** [erlio/vernemq#290]
Hi,

Is there a way to do a basic health check of a node with http request?
Something like `GET /healthcheck` that returns 200 if node is up, and does not require api key.

**Comment by dergraf** [comment]
The default `/metrics` endpoint works without authentication, just make sure to configure the firewall properly.

**Comment by rpavlovs** [comment]
It works, awesome.
Worth mentioning that the default port is `8888`.

Thanks
