### ISSUE TITLE
vmq_webhooks' retry_interval is in milliseconds rather than seconds

### ISSUE THREAD

**Issue by drf** [erlio/vernemq#298]
### Environment

- VerneMQ Version: 0.15.3
- OS: Linux
- Erlang/OTP version (if building from source): Package

### Expected behavior

- When VerneMQ is sending a PUBLISH message to a QoS2 subscriber, it should wait retry_interval before sending another retry

### Actual behaviour

- This is what happens when receiving the message through libmosquitto:

> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient received PUBLISH (d0, q2, r0, m2, 'my/topic', ... (129 bytes))
> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient sending PUBREC (Mid: 2)
> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient received PUBLISH (d1, q2, r0, m2, 'my/topic', ... (129 bytes))
> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient sending PUBREC (Mid: 2)
> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient received PUBREL (Mid: 2)
> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient sending PUBCOMP (Mid: 2)

The behavior happens _most of the times_, but it's non deterministic - a few times the second publish doesn't come over and everything works as expected. Furthermore, this behavior triggers a bug in mosquitto (we're reporting/solving it as well) which screws up everything happening afterwards on the QoS2 queue.

**Comment by dergraf** [comment]
Thanks for reporting @drf!

What is your `retry_interval` config in `vernemq.conf`?

**Comment by drf** [comment]
Hi @dergraf , thanks for the quick reply :)

> retry_interval = 20

**Comment by rbino** [comment]
@ioolkos the second message is flagged as DUP (d0 is "not dup", d1 is dup)

**Comment by drf** [comment]
> Is there a way to see if the second message is actually flagged as DUP?

Yes - mosquitto gives this information, and in fact:

> Mar 07 16:09:32 localhost hyperdrive-tran[301]: MOSQUITTO LOG! 16 Client myclient received PUBLISH (d1, q2, r0, m2, 'my/topic', ... (129 bytes))

_d1_ means the message was a DUP message, so the second message was indeed flagged

> I'm also thinking in the direction of possible multiple subscriptions to that topic?

We ruled this out as we tried with clean/dirty sessions and made sure there was only one subscription ongoing.

> as we certainly should not "screw up QoS2 queues".

This is 99.9% mosquitto's fault by the way, and this issue probably just exposes a bug over there

**Comment by ioolkos** [comment]
@drf: Hi Dario, have you been able to resolve this? (just wondering, no pressure)

**Comment by drf** [comment]
To be fairly honest we're dying to reproduce this consistently, as it appears it requires a number of steps on both client side to be exposed, and we're still stuck on being able to reproduce it only on one installation. We confirmed libmosquitto's bug which basically *totally* disregards the dup flag when receiving a message (and I'm personally quite surprised nobody ever noticed this, but anyway), and that would be enough to mark this as "solved" on the flow side, but still I'd like to find out what triggers Verne to have that behavior.

**Comment by drf** [comment]
And there goes the cause of the bug. We had vmq_webhooks authentication hook enabled. Now, the example reports this as a valid response:

> {
>     "result": "ok",
>     "modifiers": {
>         "mountpoint": "newmountpoint"
>         "client_id": "clientid",
>         "reg_view": "reg_view",
>         "clean_session": false,
>         "max_message_size": 65535,
>         "max_message_rate": 10000,
>         "max_inflight_messages": 100,
>         "retry_interval": 100,
>         "upgrade_qos": false
>     }
> }

retry_interval is key here. Apparently, in vmq_webhooks this interval is in *milliseconds* rather than seconds. And there goes the reason why it was random, not locally reproducible, and more frequent on less capable devices.

So - vmq_webhooks is either bugged in the code or in the docs, whereas libmosquitto still remains bugged as it is affected by this weird corner case.

Additional thanks to @rbino who helped me triage this

**Comment by ioolkos** [comment]
Wow, thanks for hunting this down!

**Comment by drf** [comment]
Thinking about it twice, everything in Verne is in seconds rather milliseconds, and I doubt anybody has interest in a retry interval <1s, so maybe it makes sense to get the hooks to use seconds rather than doing the other way round. @dergraf , waiting for your input here

**Comment by larshesel** [comment]
I can't think of a real use case where you'd want sub-second retry intervals, but I'm leaning to just document the examples better instead of removing this possibility. I know it's not possible to specify directly in the `vernemq.conf` but I think one of the benefits when writing plugins is that you're not limited to the default behaviour from the config files etc but have maximal freedom and flexibility.

Just my 2 cents.

**Comment by larshesel** [comment]
Until we decide on some other action, I've, for now, changed the example from `100` to `20000` and added a note that it's in milliseconds.

**Comment by rbino** [comment]
I've made a diagram of what was happening, with my InsaneDiagramSkills™, maybe it could be useful to understand if this misconfiguration triggered some corner-case that is effectively bugged.

![diagram-crash](https://cloud.githubusercontent.com/assets/2528778/24146602/b05a149a-0e36-11e7-935d-8158d6e2eb56.png)


Mosquitto was crashing with this message (the first crash)
```
CRASH REPORT Process <0.586.0> with 0 neighbours crashed with reason: no case clause matching <<98,2,0,2>> in vmq_mqtt_fsm:connected/2 line 341
```
The line it refers to is inside the ```connected(#mqtt_pubcomp{message_id=MessageId}, State)``` function, so I guess the PUBCOMP was received.

From then on, all hell breaks lose after the reconnection.

**Comment by larshesel** [comment]
Hi @rbino thanks for this detailed description - we have some ideas which causes this and are investigating. Insane diagram! :-)

**Comment by drf** [comment]
@larshesel I pretty much agree with you all over the line, your argument is more than valid. If this is something we want to keep overall I suggest the following approach (entirely brainstorming here):

 * Update the documentation for plugins/hooks to reflect this change
 * Adding a warning on Verne's startup/device connection in case the retry_interval is below reasonable values (<5s?) to prevent configuration issues
OR
 * Add a tracing mechanism which exposes information about a connected client with its properties and proper units of measure.

**Comment by larshesel** [comment]
Hi @drf, great input and I think all of your points make sense. We're actually working on a tracing mechanism which should be able to show exactly these kinds of things (although it does not yet report on the plugin hooks and the return values there, that is planned), but it's still very much a WIP, see #309.

**Comment by drf** [comment]
@larshesel sounds great! I mentioned that point exactly because I was lurking on that MR :) I'd say - let's leave this bug open for now if you agree, so when you guys are off with preparations for 1.0 we can discuss this in more depth and find the best solution. Potentially, if tracing is implemented to that point, I believe just updating documentation would do it.

**Comment by drf** [comment]
Hi everyone, given I was in triaging mode I found this being still open :) I guess this is good timing to take a final decision on this issue - @larshesel , what do you think could be done to declare this closed?

**Comment by larshesel** [comment]
I think the main points were fixed: documentation and tracing, though we didn't add any warnings for when the interval is too small as it's hard to decide when something is too small... Closing for now!

**Comment by richard-scott** [comment]
I've just spent a while troubleshooting a similar issue.... It's confusing that "retry_interval" is documented to require a different format depending on which part of the system is using it in.

In one section you need to use [seconds](https://docs.vernemq.com/configuration/options#retry-interval), and the other uses [milli-seconds](https://docs.vernemq.com/plugindevelopment/webhookplugins#auth_on_register).
