### ISSUE TITLE
Subscription downgrade does not work with QoS2

### ISSUE THREAD

**Issue by drf** [erlio/vernemq#299]
### Environment

- VerneMQ Version: 0.15.3
- OS: Linux
- Erlang/OTP version (if building from source): package

### Expected behavior

- When a subscriber subscribes to a topic with QoS X and a publisher publishes to that topic with QoS Y>X, the subscriber should receive the message with QoS X every time (as per MQTT spec).

### Actual behaviour

- While investigating #298, we accidentally found out that whenever something is published with QoS2, the subscription QoS is disregarded on the subscriber end, and the message is always delivered with QoS2. It might somehow be related to the other bug, for sure there is something going on when handling QoS2 in general.

**Comment by ioolkos** [comment]
Thanks, Dario! 
So this looks like `upgrade_outgoing_qos` is somehow on, maybe even as a fault.
But yeah, this really calls for some more testing. I'll try to do that tomorrow.

Keep us posted if you happen to find more info on that.

**Comment by drf** [comment]
Yup, we'll keep actively debugging the issue, if we figure something out we'll keep you posted or try hacking up a patch :)

**Comment by drf** [comment]
After further investigation, it might as well be that there is a bug, but in a different area: with a different installation we couldn't reproduce the described behavior, and we found out the root cause might be the fact that if a client is subscribed to /topic with QoS X, and after a reconnection with a dirty session it re-subscribes to /topic with QoS Y, the subscription remains still with QoS X (the MQTT spec, instead, says it should turn into Y). We'll keep on investigating.

**Comment by ioolkos** [comment]
Aha!
Thanks for investigating this so far. If possible can you give the exact series of mosquitto client commands that lead to the behaviour?
I think I can't reproduce the described behaviour, but i only tested with current master quickly.

darn, this is exactly what QuickCheck is for.

**Comment by dergraf** [comment]
Is clustering involved?

Am 08.03.2017 12:17 vorm. schrieb "ioolkos" <notifications@github.com>:

**Comment by drf** [comment]
@dergraf nope, only a single node

@ioolkos we'll try reproducing with mosquitto pub/sub and be back to you!

**Comment by larshesel** [comment]
It's not clear to me, but was the question in this issue answered (it seems the discussion for this is also being done in #298 ) or is there still something to investigate here?

**Comment by drf** [comment]
I think we can close this bug for now as it's most likely related to #298  bad behaviour . I'll reopen it if we ever find out they're decoupled.
