### ISSUE TITLE
compile error: snappy_unittest-snappy-test.o

### ISSUE THREAD

**Issue by zhongjin616** [erlio/vernemq#30]
hi there:
i try to compile vernemq from source. `gcc version 4.8.4`  `Ubuntu14.04 64bit`.
 i install Erlang/OPT  from `erlang-solutions.com` as you suggest.  and `erl --version` says:
`Erlang/OTP 17 [erts-6.4] [source-2e19e2f] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]`

 just as you said:
`git clone git://github.com/erlio/vernemq.git`
`cd vernemq`
`make rel`
 
and then i got the error output:
/home/vagrant/vernemq/rebar3 release --overlay_vars vars.config
===> Verifying dependencies...
===> Compiling eleveldb
make[1]: Entering directory `/home/vagrant/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
make  all-am
make[2]: Entering directory `/home/vagrant/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
source='snappy-test.cc' object='snappy_unittest-snappy-test.o' libtool=no \
	DEPDIR=.deps depmode=none /bin/bash ./depcomp \
	g++ -DHAVE_CONFIG_H -I.       -c -o snappy_unittest-snappy-test.o `test -f 'snappy-test.cc' || echo './'`snappy-test.cc
snappy-test.cc:82:15: error: aggregate ‘snappy::rusage snappy::benchmark_start_cpu’ has incomplete type and cannot be defined
 struct rusage benchmark_start_cpu;
               ^
snappy-test.cc: In function ‘void snappy::StartBenchmarkTiming()’:
snappy-test.cc:93:17: error: ‘RUSAGE_SELF’ was not declared in this scope
   if (getrusage(RUSAGE_SELF, &benchmark_start_cpu) == -1) {
                 ^
snappy-test.cc:93:50: error: ‘getrusage’ was not declared in this scope
   if (getrusage(RUSAGE_SELF, &benchmark_start_cpu) == -1) {
                                                  ^
snappy-test.cc: In function ‘void snappy::StopBenchmarkTiming()’:
snappy-test.cc:139:17: error: aggregate ‘snappy::rusage benchmark_stop_cpu’ has incomplete type and cannot be defined
   struct rusage benchmark_stop_cpu;
                 ^
snappy-test.cc:140:17: error: ‘RUSAGE_SELF’ was not declared in this scope
   if (getrusage(RUSAGE_SELF, &benchmark_stop_cpu) == -1) {
                 ^
snappy-test.cc:140:49: error: ‘getrusage’ was not declared in this scope
   if (getrusage(RUSAGE_SELF, &benchmark_stop_cpu) == -1) {
                                                 ^
make[2]: *** [snappy_unittest-snappy-test.o] Error 1
make[2]: Leaving directory `/home/vagrant/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/vagrant/vernemq/_build/default/lib/eleveldb/c_src/snappy-1.0.4'
===> Hook for compile failed!

make: *** [rel] Error 1

thanks.

**Comment by dergraf** [comment]
have you installed the build-essential package from the ubuntu repo?
before you retry, delete the _build/default/lib/eleveldb folder just to make sure that it will fetch it again and the ./configure steps are done properly.

**Comment by zhongjin616** [comment]
Yes. i use a new vagrant virtual machine and forget to install `build-essential` and `openssl`.
and these are the cmd to solve this issue:

`sudo apt-get install build-essential`
`sudo apt-get install libssl-dev`

thanks again.

**Comment by weikent** [comment]
i have the same issue.  my machine is centos7 64bit.
and
i have installed build-essential and libssl-dev. use this command:
yum install "Development Tools"  and   yum install  openssl-devel

but can't solve this issue.

please help. 
thanks

**Comment by larshesel** [comment]
Hi @weikent, just to make sure, can you please show us the exact error message you get. I suppose you're building from directly from our current vernemq master branch?
