### ISSUE TITLE
Mongo collection name for auth

### ISSUE THREAD

**Issue by ig0r** [erlio/vernemq#302]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04LTS
- Erlang/OTP version (if building from source):

### Expected behavior

Hi guys,

The collection name `vmq_acl_auth` for storing auth data in mongo is [hardcoded](https://github.com/erlio/vernemq/blob/a5aefa7bde1c16848ec4bce1196334b00ddc188b/apps/vmq_diversity/priv/auth/mongodb.lua#L68) now.

And `vernemq.conf` doesn't have it as a param.
```
## 
## Default: off
## 
## Acceptable values:
##   - on or off
vmq_diversity.auth_mongodb.enabled = off

## 
## Default: localhost
## 
## Acceptable values:
##   - text
## vmq_diversity.mongodb.host = localhost

## 
## Default: 27017
## 
## Acceptable values:
##   - an integer
## vmq_diversity.mongodb.port = 27017

## 
## Acceptable values:
##   - text
## vmq_diversity.mongodb.login = 

## 
## Acceptable values:
##   - text
## vmq_diversity.mongodb.password = 

## 
## Acceptable values:
##   - text
## vmq_diversity.mongodb.database = 
```

Shouldn't it be as param, something like `vmq_diversity.mongodb.collection` with the  `vmq_acl_auth` as default?

Thanks!

**Comment by larshesel** [comment]
Hi @ig0r 

Yes, I agree that it would probably make sense to make this configurable, but as a workaround you can easily change this in the `mongodb.lua` script.

Would that work for you?

**Comment by ig0r** [comment]
Yes, it would. Even the default value is enough. The only thing I'd like to know it won't change in the future - so, it's good there's a way I can customise its name.

**Comment by larshesel** [comment]
We might make it configurable in the future and if we do then it will keep the current value.
