### ISSUE TITLE
Documentation on auth with mongo

### ISSUE THREAD

**Issue by ig0r** [erlio/vernemq#307]
### Environment

- VerneMQ Version: 1.0.0rc2

Hi guys,

It'd be awesome if you could slightly improve documentation on mongo db auth fields and their possible values.

For instance, here's a sample from the documentation:
```
db.vmq_acl_auth.insert({
    mountpoint: '', 
    client_id: 'test-client', 
    username: 'test-user', 
    passhash: '$2a$12$WDzmynWSMRVzfszQkB2MsOWYQK9qGtfjVpO8iBdimTOjCK/u6CzJK', 
    publish_acl: [
        {pattern: 'a/b/c'}, 
        {pattern: 'a/+/d'}
    ], 
    subscribe_acl: [
        {pattern: 'a/#'}
    ]
})
```

`mountpoint` - what happens when it has an empty value, or otherwise.
`client_id` - what happens if it's empty, or has a value - can't a client with different id authenticate or just won't be authorised to topics in pattern, etc.?
`passhash` - if only `$2a$ `bcrypt hashes supported

**Comment by larshesel** [comment]
Hi @ig0r 

Thanks for the feedback.

The mountpoint is a VerneMQ specific extension which allows to have completely separate topic trees. The default is the empty string mountpoint.

I'm not completely sure what your question concerning the client id is about. Each client which want to connect will have a client-id and this needs to be specified here. Clients which do not have an entry with a matching client id will be rejected (also if the password does not match, of course).

currently only bcrypt password hashes are supported.

Let me know if this helps - we'll see if we can improve the docs somehow.

**Comment by ig0r** [comment]
@larshesel thanks for explanation!

Re the `client id` - if I want the broker to ignore it, is it possible to provide an empty field? So, only a username and password will be used for auth. Another question - are wildcards allowed?

Re bcrypt hashes I'll probably get back to you once I'll try mongo integration.

Thanks!

**Comment by larshesel** [comment]
you can't ignore the client-id - the client-id is *the* identifier for a client in MQTT. If you don't really 'care' about the client-id then you should just set it to be the same as the username.

wildcards are not allowed or supported in usernames, clientids or passwords.

**Comment by ig0r** [comment]
yes, that's what I'd like clients (as an option at least) to have any client id they want - random probably.

thanks!
