### ISSUE TITLE
vmq-admin commands could be more consistent

### ISSUE THREAD

**Issue by kellycampbell** [erlio/vernemq#310]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: ubuntu 16.04

### Expected behavior

It would be nice if some of the vmq-admin commands had more consistent sub-commands.

Example:
    * vmq-admin plugin show
    * vmq-admin script status
    * vmq-admin session list
    * vmq-admin listener show
    * vmq-admin api list-keys

It would be easier to remember just one form of 'status', 'show', or 'list'. Right now I have to look at the help (or receive the help by accident) each time I use these.

**Comment by larshesel** [comment]
Hi - thanks for bringing that into focus - we'll see if we can't agree on something more uniform before release 1.0.

**Comment by larshesel** [comment]
I'm leaning toward using `show` and it would then look something like this:

- vmq-admin plugin show
- vmq-admin script show
- vmq-admin session show
- vmq-admin listener show

For the api-keys I'm not so sure how to change it. One option would be something like this:
- vmq-admin api key show
- vmq-admin api key create
- vmq-admin api key delete

Or something like this:
- vmq-admin api-keys show
- vmq-admin api-keys create
- vmq-admin api-keys delete

What do you think? I'll try and see if I can find other places where we might not be entirely consistent.

Comments @ioolkos @dergraf  ?

**Comment by dergraf** [comment]
+1

**Comment by ioolkos** [comment]
I think the most consistent we can be for the `api` subcommand is to change it to sth like the following:

    vmq-admin api-key show
    vmq-admin api-key create
    vmq-admin api-key delete
