### ISSUE TITLE
User can't auth with mongo stored creds

### ISSUE THREAD

**Issue by ig0r** [erlio/vernemq#314]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04 LTS

### Expected behavior

To authenticate an mqtt user with creds stored in mongodb.

### Actual behaviour

1. Adding user creds to mongo.

```
db.vmq_acl_auth.insert({
    mountpoint: '', 
    client_id: 'test0', 
    username: 'test0', 
    passhash: '$2a$10$tMUbM1Y/crxU3h4BRgVI8OR3wh3rL0oOOTURvEbKIPtOg3LLk8Wia', 
    publish_acl: [
        {pattern: '/test/#'}, 
        {pattern: '/test2/#'}
    ], 
    subscribe_acl: [
        {pattern: '/test/#'}
    ]
})
```
2. Connecting using mosquitto_sub:

```
mosquitto_sub -d -h vernehost -p 1883 -t /test -u test0 -P somepass_0 -i test0
```

3. Getting the `Connection Refused: not authorised.` error.

4. Verne mq has the following messages in logs:

- `error.log`

```
2017-03-20 11:48:37.665 [error] <0.346.0>@vmq_diversity_script:handle_call:128 can't call function auth_on_register with args [{addr,<<"xx.yyy.zzz.www">>},{port,47291},{mountpoint,<<>>},{client_id,<<"test0">>},{username,<<"test0">>},{password,<<"somepass_0">>},{clean_session,true}] in "/usr/share/vernemq/lua/auth/mongodb.lua" due to {error,{badmatch,{error,"bcrypt failed"}}}
```

- `console.log`

```
2017-03-20 11:48:37.665 [error] <0.346.0>@vmq_diversity_script:handle_call:128 can't call function auth_on_register with args [{addr,<<"xx.yyy.zzz.www">>},{port,47291},{mountpoint,<<>>},{client_id,<<"test0">>},{username,<<"test0">>},{password,<<"somepass_0">>},{clean_session,true}] in "/usr/share/vernemq/lua/auth/mongodb.lua" due to {error,{badmatch,{error,"bcrypt failed"}}}
2017-03-20 11:48:37.665 [warning] <0.660.0>@vmq_mqtt_fsm:check_user:536 can't authenticate client {[],<<"test0">>} due to [error]
2017-03-20 11:48:37.665 [debug] <0.660.0>@vmq_ranch:teardown:123 session normally stopped
```

Could you please give me a hint what's wrong here?

Thanks!

**Comment by larshesel** [comment]
Hi @ig0r 

I just checked this and using your entry above and the mosquitto sub command I could subscribe without any issues (on my Debian Testing machine). This seems to indicate that the bcrypt library itself is having some issues on Ubuntu 16.04LTS. 

I'll try and test and see if I can reproduce in a virtual machine when I get some free time. Just to double check, you're sure you installed the Xenial Xerus package and not by accident (if at all possible) one of the older ones (Trusty or Precise)?

Thanks for reporting!

**Comment by ig0r** [comment]
For the rc I'm using the following:

```
root@verne-rc:/var/log/vernemq# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
root@verne-rc:/var/log/vernemq# 
```

I tried two `$2a$` hashes (with the 10 and 12 rounds) which were generated with the java jBCrypt library and one `$2b$` hash generated with the python bcrypt library. I got the same results for all those hashes.

Could it be that you expect a different number of rounds? I looked at the [erlang-bcrypt](https://github.com/chef/erlang-bcrypt) and it seems it uses 12 rounds as default. In the doc you also has a hash with 12 rounds.

**Comment by larshesel** [comment]
Hi @ig0r 

I don't believe it's anything to do with the number of rounds. It should just work as it's encoded into the passhash.

I just tried to reproduce the problem with your password and hash on a Xenial virtual machine (Ubuntu 16.04.02 LTS) where I installed the 1.0.0rc2 package and didn't have any issues.

Can you try the following:

```
ubuntu@ubuntu-xenial:~$ sudo service vernemq start
ubuntu@ubuntu-xenial:~$ sudo vernemq attach
Remote Shell: Use "Ctrl-G q" to quit.
q() or init:stop() will terminate the vernemq node.
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2  (abort with ^G)
(VerneMQ@127.0.0.1)1> S1 = <<"$2a$10$tMUbM1Y/crxU3h4BRgVI8O">>.
<<"$2a$10$tMUbM1Y/crxU3h4BRgVI8O">>
(VerneMQ@127.0.0.1)2> bcrypt:hashpw(<<"somepass_0">>, S1).   
{ok,"$2a$10$tMUbM1Y/crxU3h4BRgVI8OR3wh3rL0oOOTURvEbKIPtOg3LLk8Wia"}
```

(basically inputting first the line `S1 = <<"$2a$10$tMUbM1Y/crxU3h4BRgVI8O">>.` and then the line `bcrypt:hashpw(<<"somepass_0">>, S1).` and see if you get the correct hash or `{error, "bcrypt failed"}` (which you get if the salt is incorrect).

**Comment by ig0r** [comment]
Hi @larshesel 

Thanks, I checked it - it seems to be working.

```
root@verne-rc:~# service vernemq start
root@verne-rc:~# sudo vernemq attach
Remote Shell: Use "Ctrl-G q" to quit.
q() or init:stop() will terminate the vernemq node.
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2  (abort with ^G)
(VerneMQ@127.0.0.1)1> S1 = <<"$2a$10$tMUbM1Y/crxU3h4BRgVI8O">>.
<<"$2a$10$tMUbM1Y/crxU3h4BRgVI8O">>
(VerneMQ@127.0.0.1)2> bcrypt:hashpw(<<"somepass_0">>, S1).
{ok,"$2a$10$tMUbM1Y/crxU3h4BRgVI8OR3wh3rL0oOOTURvEbKIPtOg3LLk8Wia"}
(VerneMQ@127.0.0.1)3>   
```

The problem was that initially I used a different bcrypt scheme `$2b$` (which you seem do not support) and during the creds update updated a wrong field.

**Comment by larshesel** [comment]
Ok - great it's working then - I'll see if we it's possible to add support for `$2b$` but for now add a note that we only support version `$2a$`.

Thanks again for testing and reporting this - it's much appreciated and very good feedback!

**Comment by larshesel** [comment]
Right, I missed that, sorry!
