### ISSUE TITLE
HTTP messaging interface

### ISSUE THREAD

**Issue by rpavlovs** [erlio/vernemq#318]
Hi,

Is there a way to send messages through HTTP interface?

I'm thinking of using Verne as a push notification service, which means that I will have a cluster of brokers that will relay messages from a server to a number of clients.

This means that the server will be connected to only one cluster node at a time, and all notifications will have to go through a single node potentially overloading it and causing cascading failures.

The only solution I can think of is balancing the load with HTTP load balancer. Do you know if it's possible or maybe you have any other approaches in mind?

Thanks

**Comment by larshesel** [comment]
Hi @rpavlovs 

There currently does not exist an HTTP interface for publishing messages. Such a feature could be built as a plugin, though.

I'm not sure I understand your design limitations of why the (notification) server can only connect to a single node or why you can't have more than one servers doing the push-notifications.

Maybe you could explain a bit more in detail?

**Comment by rpavlovs** [comment]
I see.

The problem with multiple notification servers here is that I'm hosted on AWS, and rely on a load balancer to connect to broker nodes. When multiple notification servers connect to the cluster there is a chance they will get the same node from the balancer and crash it.

It is also possible that a single notification server will send more MQTT messages than a broker node can handle.

I was hoping I could sent notifications with HTTP requests, this way they will be evenly balanced among all broker nodes.

Do you know if there are HTTP interface plugins that are already available (maybe for purchase)?

**Comment by waliferus** [comment]
@rpavlovs what is your expected message throughput?  i recently discovered that due to an issue with the paho mqtt client, i'm currently sending 15-20k qos0 messages per second through 1 vernemq broker in 3 node cluster.

**Comment by larshesel** [comment]
Hi @rpavlovs 

I do not know of any existing HTTP interface plugins at the moment. We do have a HTTP interface on our roadmap, and even though it's kind of a low-hanging fruit we have a bunch of other stuff we need to get done first, so I can't say when we'll get to it.
