### ISSUE TITLE
Allow to connect clients with any random generated client id when using auth with mongo

### ISSUE THREAD

**Issue by ig0r** [erlio/vernemq#319]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04.LTS

### Expected behavior

- To be able to connect with any random generated client-id as long as the creds are correct

### Actual behaviour

1. A database has the following record for the user creds:

```
{ "_id" : ObjectId("58d0f9ddd1b5627145e1a71b"), "mountpoint" : "", "client_id" : "test0", "username" : "test0", "passhash" : "$2a$10$tMUbM1Y/crxU3h4BRgVI8OR3wh3rL0oOOTURvEbKIPtOg3LLk8Wia", "publish_acl" : [ { "pattern" : "/test/#" }, { "pattern" : "/test2/#" } ], "subscribe_acl" : [ { "pattern" : "/test/#" } ] }
```

2. If I specified a client id it connects fine, without a client id the broker doesn't authorise me
```
root@mosq:~# mosquitto_sub -d -h xxx.yyyy.www.zzz -p 1883 -t /test -u test0 -P somepass_0 -i test0
Client test0 sending CONNECT
Client test0 received CONNACK
Client test0 sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 0)
Client test0 received SUBACK
Subscribed (mid: 1): 0
^C
root@mosq:~# mosquitto_sub -d -h xxx.yyyy.www.zzz -p 1883 -t /test -u test0 -P somepass_0
Client mosqsub/28195-mosq.reke sending CONNECT
Client mosqsub/28195-mosq.reke received CONNACK
Connection Refused: not authorised.
Client mosqsub/28195-mosq.reke sending CONNECT
Client mosqsub/28195-mosq.reke received CONNACK
Connection Refused: not authorised.
^C
root@mosq:~# 
```

Is there a way to specify a client id in a database, so a broker accepts clients with ANY client id?

I would like clients let to generate client id themselves (as `mosquitto` utils do). So, the username/password are enough to get through.

**Comment by larshesel** [comment]
Hi @ig0r 

This is not possible with the current mongodb integration as the client-id is part of the key used to look up the database entry.

You could change the `mongodb.lua` file to do what you want, but I wouldn't recommend using `dynamic` client-ids as not fixing and authenticating the client-id makes it possible for malicious clients to steal each other's sessions. Also, for each connected client the client-id us used as a key to replicate data between cluster nodes and even when the client is gone, the client-id will remain (with a tombstone for a value). That is a non-issue if the clients would reconnect each time with the same client-id, but again, malicious clients could try to reconnect with as many different client-ids as possible and try to overload the replication mechanism of vernemq.

I would really recommend to enforce the client-id to be the same as the username or get the client-id from a client-certificate CN or similar.

Hope this helps.

**Comment by ig0r** [comment]
I get the mongo integration argument.

Regarding the security - Do you require authenticating with client id, if I use the password file authentication instead of mongo? I don't remember it's the case for the 0.15.x release.

**Comment by larshesel** [comment]
You're right that's not a requirement in the password file authentication and it's also a weakness of that plugin IMHO. But the password plugin does one thing and it does it well - it allows to authenticate via user/pass - but it should be supplemented with an extra plugin or hook which ensures that the client-id is makes sense.

Each use case has different needs - it's just important to understand what limitations/possibilities exist - which was why I wanted to mention the trade-offs/dangers for not authenticating/authorizing the client-id.

**Comment by larshesel** [comment]
I guess the question was answered, closing.
