### ISSUE TITLE
Cluster is not ready 

### ISSUE THREAD

**Issue by macleetw** [erlio/vernemq#32]
I start two nodes, but i cannot publish message to broker due to this.
<0.2665.0>@vmq_session:check_user:747 can't register client {[],"mosq_pub_15760_ubuntu"} due to reason not_ready

Why cluster node is not ready for service?

If i change nodename to default setting: VerneMQ@127.0.0.1 , the node can service "publish" command.
But it can not do cluster function.

Mac.Lee

**Comment by dergraf** [comment]
Hi there!

Per default the cluster stops serving requests if it finds a consistency issue. If the output of ```vmq-admin cluster status``` shows at least one node with ```running=false``` the cluster thinks it is inconsistent (because it might have lost connectivity to this node due to e.g. a netsplit situation). 
If you want to get rid of such a node you've to issue ```vmq-admin cluster leave node=<not-running-node>``` which will delete this unused node from the cluster.

Another option would be to stop using these consistency checks by setting ```trade_consistency=on``` in ```vernemq.conf```. However this could lead to unwanted behaviour, especially during netsplit situations.

Hope this helps.

**Comment by macleetw** [comment]
Hi Adre,

Thanks!
i try the options you mentioned, but not working.

I also check another broker "emqttd", it have similar problem.
The emqttd author told me to that "if i changed the node, i have to remove
data in  "data/mnesia".
Sorry, i am not familiar with erlan/OTP, but after remove the files under
"data/mnesia", emitted working fine with clustering function.

Since vernemq an emqqtd are based with erlang, i guesses vernemq may have
the same behavior when i changed nodename.
I check the .deb file, the original files under directory
"/var/lib/vernemq" only two empty directory.
So, remove other directory (generated.configs, meta), and vernemq can join
to with cluster function enabled.
vmq-admin cluster status
+---------------------+-------+
|        Node         |Running|
+---------------------+-------+
|VerneMQ@192.168.2.26 | true  |
|VerneMQ@192.168.2.145| true  |
+---------------------+-------+

But after i publish from one node, and subscribe from other node, it
message cannot forward from one node to other one.
I check the log "/var/log/vernemq/console.log" and got some error as below:

*vmq_cluster_com:loop:70 terminate due to remote_node_not_available*

Pleas help me to check when the message cannot forward from one node to
other node.

Our company may use vernemq to be our IOT solution.
But i don't find any pricing  info from your production site.
May i asking the pricing model  for vernemq solution?
Or vernmq charge for technical support or consultant service?

Regards,

Mac.Lee



2015-07-27 15:46 GMT+08:00 Andre Graf <notifications@github.com>:

**Comment by macleetw** [comment]
Thanks dergraf's great help!

I conclude the situations:

1.The node is not running
   When change nodename, needs to remove meta data.
2.Message is not forwarding to other node
  When run two node in virtual machine, don't bind to 0.0.0.0.
  Bind to 0.0.0.0 may cause node connecting failure.

Mac.Lee

**Comment by dergraf** [comment]
just as a reminder:
this happened on a Macbook using Parallels Desktop Virtualization Software.
