### ISSUE TITLE
Reload/refresh VMQ on CRL change

### ISSUE THREAD

**Issue by gdhgdhgdh** [erlio/vernemq#321]
### Environment

- VerneMQ Version: 0.15.3
- OS: `erlang:19` docker image
- Erlang/OTP version (if building from source):

### Expected behavior

- When I specify `listener.ssl.crlfile=/ssl/revoke.crl` VMQ will read and act as expected - the TLS certificate serial numbers listed in the CRL are denied access.
- I would expect that VMQ notices that the file's timestamp has changed and loads the new version

### Actual behaviour

- The new file is ignored - serial numbers referenced only in the new file are still permitted to connect with TLS.

Is there a refresh / reload command that I've overlooked?

**Comment by larshesel** [comment]
Hi @gdhgdhgdh 

I believe the way currently is to restart the listener using:

```
vmq-admin listener stop address=127.0.0.1 port=1883
vmq-admin listener restart address=127.0.0.1 port=1883
```

New connections should now have picked up the changes to the ssl config.

**Comment by gdhgdhgdh** [comment]
Hm, I did try this when investigating `vmq-admin` earlier - it had no effect and the only thing that worked was doing a `listener delete` and then `listener start` with all ssl options specified :/

We've worked around the problem by changing how our app works. Thanks in any case :)

**Comment by larshesel** [comment]
Hmm, I'll have to look into why that doesn't work - I really think it should. But glad you found another acceptable workaround.

**Comment by larshesel** [comment]
hey @gdhgdhgdh I've created a PR to add periodic refresh of crl lists, see #326 - it's pending review but might help or simplify your use-case. Of course this may not be the final solution and needs to be reviewed and discussed before we can merge it. Let's see.
