### ISSUE TITLE
Registering webhooks at run-time not working.

### ISSUE THREAD

**Issue by tosheer** [erlio/vernemq#325]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Used docker image
- Erlang/OTP version (if building from source): Used docker

### Expected behavior
I need to register webhooks at run-time  following the tutorials of https://vernemq.com/docs/plugindevelopment/webhookplugins.html. But when i try to add a new webhook by executing command

vmq-admin webhooks register hook=auth_on_register endpoint="http://localhost"

It should have registered webhook.

### Actual behaviour
i can see webhooks is not allowed as a subcommand under vmq-admin. 

root@4be0961a1f54:/etc/vernemq# sudo vmq-admin webhooks status
Usage: vmq-admin <sub-command>

  Administrate the cluster.

  Sub-commands:
    node        Manage this node
    cluster     Manage this node's cluster membership
    session     Retrieve session information
    plugin      Manage plugin system
    listener    Manage listener interfaces
    metrics     Retrieve System Metrics
    api         Manage API keys for the HTTP management interface
  Use --help after a sub-command for more details.

can you guys tell me how can i do that?

**Comment by larshesel** [comment]
Hi

You need to enable the webhooks plugin first by setting either 

```
plugins.vmq_webhooks = on
```

in the `vernemq.conf` file, or by enabling at runtime (will not be persisted) using

```
$ vmq-admin plugin enable -n vmq_webhooks
```

When the plugin is enabled the `vmq-admin webhooks` will work and show up in the usage list.

Cheers,
Lars

**Comment by tosheer** [comment]
@larshesel It works thanks a lot.
