### ISSUE TITLE
how to get the user online status?

### ISSUE THREAD

**Issue by dtxlink** [erlio/vernemq#33]
ths?

**Comment by dergraf** [comment]
hi there,
do you mean through MQTT or through an API or similar?

**Comment by dtxlink** [comment]
api

**Comment by dergraf** [comment]
currently not available.

**Comment by RafficMaleo** [comment]
Mqtt solves the offline issue by using Last Will Testament. -- Please refer to the Mqtt doc. it is simple to implement
