### ISSUE TITLE
ACL file doesn't support huge values of topics to be configured

### ISSUE THREAD

**Issue by KnolBee** [erlio/vernemq#330]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Expected behavior

- Millions of topic should be supported in /etc/vernemq/vmq.acl

### Actual behavior

- Added around 14 Million topic into /etc/vernemq/vmq.acl, the File size is around 250 MB. On restarting verne, it consumed more than 5 GB of RAM(from previous consumption of lesser than 1 GB). And CPU consumption crossed 90%. without a single connection being made. System stopped responding thereafter.

**Comment by dergraf** [comment]
Hi @KnolBee, thanks for reporting.

We have never tested `vmq_acl` (and `vmq_passwd`) with such a high number of entries. Multiple speed- and memory related improvements would be required. For this reason we don't recommend to use it that way. Please use either `vmq_webhooks` or connect to a database such as MongoDB, MySQL, PostgreSQL, or Redis via `vmq_diversity` or just implement your own plugin. 

Using webhooks: https://vernemq.com/docs/plugindevelopment/webhookplugins.html
Using database: https://vernemq.com/docs/configuration/db-auth.html
Build your own: https://vernemq.com/docs/plugindevelopment/
Or get in touch with us for development services: https://vernemq.com/contact.html

**Comment by KnolBee** [comment]
Thanks degraf,

Will try with MongoDB integration.
