### ISSUE TITLE
auth_on_register webhook not getting triggered on new connection.

### ISSUE THREAD

**Issue by tosheer** [erlio/vernemq#331]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS: Used docker image
- Erlang/OTP version (if building from source): Used docker image

### Expected behavior
I am running Vernemq with webhooks and below are the configuration.

root@4be0961a1f54:~# vmq-admin plugin show
+------------+-----------+-------+-----+
|   Plugin   |   Type    |Hook(s)|M:F/A|
+------------+-----------+-------+-----+
|vmq_webhooks|application|       |     |
+------------+-----------+-------+-----+

root@4be0961a1f54:~# vmq-admin webhooks status
+-----------------+---------------------------------------+-------------+
|      hook       |               endpoint                |base64payload|
+-----------------+---------------------------------------+-------------+
| on_unsubscribe  | http://192.168.1.78:8080/unsubscribe  |    true     |
|  on_subscribe   |  http://192.168.1.78:8080/subscribe   |    true     |
|   on_register   |   http://192.168.1.78:8080/register   |    true     |
|   on_publish    |   http://192.168.1.78:8080/publish    |    true     |
|auth_on_subscribe|http://192.168.1.78:8080/auth/subscribe|    true     |
|auth_on_register |http://192.168.1.78:8080/auth/register |    true     |
| auth_on_publish | http://192.168.1.78:8080/auth/publish |    true     |
+-----------------+---------------------------------------+-------------+

Other than **auth_on_register** webhook all the other webhooks are working perfectly for me and triggering the micro-services i have for them at the end point. But auth_on_register is not getting triggered. Is this some know issue in 1.0.0rc2 ? 
```
IND00019:my-vertx-first-app tosheer.kalra$ java -jar target/my-first-app-1.0-SNAPSHOT-fat.jar 
Mar 26, 2017 9:29:56 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle

On register{"peer_addr":"172.17.0.1","peer_port":43746,"mountpoint":"","client_id":"tosheer.kalra_002829235","username":"dmmdf"}
Auth on subscribe{"username":"dmmdf","mountpoint":"","client_id":"tosheer.kalra_002829235","topics":[{"topic":"8860005121/recive","qos":0}]}
On subscribe{"username":"dmmdf","mountpoint":"","client_id":"tosheer.kalra_002829235","topics":[]}
Auth on Publish{"username":"dmmdf","mountpoint":"","client_id":"tosheer.kalra_002829235","qos":0,"topic":"9417155744/recive","payload":"YXNhc2FzZGZkZg==","retain":false}
On Publish{"username":"dmmdf","mountpoint":"","client_id":"tosheer.kalra_002829235","qos":0,"topic":"9417155744/recive","payload":"YXNhc2FzZGZkZg==","retain":false}
```

### Actual behaviour
**auth_on_register** webhook should be triggered on new connection.
Let me know if you need any other info

**Comment by larshesel** [comment]
This sounds like you have `allow_anonymous` set to `on` - could that be it?

**Comment by tosheer** [comment]
@larshesel i have started docker instance using docker run -p 1883:1883 -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on" --name vernemq1 -d erlio/docker-vernemq so i think i have already allowed anonymous. Also i am able to connect and able to send messages.

**Comment by larshesel** [comment]
That is the point: when allow_anonymous is set to on the auth_on_register hook will not be called.

**Comment by tosheer** [comment]
@larshesel apologies for missing the point. Thanks mate..!!

**Comment by larshesel** [comment]
No worries :) - I guess we can close this then.
