### ISSUE TITLE
questions regarding "vmq-admin session list"

### ISSUE THREAD

**Issue by jeremylink** [erlio/vernemq#333]
I had a question about the "vmq-admin session list" command.

My goal is to be able to maintain an online/offline status for each device. I can currently send out an online/offline status message each time a device connects or drops off, but that assumes that my external service is online and active all the time. If it ever goes down, then I have the potential to lose the current online/offline status.

The "vmq-admin session list" provides all of the active and inactive sessions the broker has seen. A few questions on it:
1. Does it span all nodes or only the local one?
2. Does the broker flush out old connections?
3. Can I query for just active connections?
4. Can I query for single or wildcard connections?
5. How inefficient is this command?
6. What happens if I run this query with tens of thousands of connections (or more)?

I know about a year ago you said this function was going to go through a major rewrite; is that still the case? Is it close to getting updated?

Thanks.

**Comment by larshesel** [comment]
Hi @jeremylink 

The rewrite has happened, it's however with some caveats (see below). To go through your questions:

1. It spans all nodes by default
2. Yes, but there is a bug where sometimes old sessions are shown after a broker restart (clean session true sessions) - this will be fixed soon
3. If by active you mean 'online', then yes: `vmq-admin session show --is_online=true`.
4. Wildcards are not (yet) supported in the command line interface, although it is supported by the underlying query-language.
5. Good question - worst case is that it will have to iterate over all clients on each node to find what it's looking for, there may, however, be some optimizations - @dergraf can for sure elaborate here.
6. It has a built in limit option which prevent the entire session state to be propated as a result (which could overwhelm the network and the client) - it defaults to 100 results returned from each node.

Note, with the next release this command has been renamed to `vmq-admin session show` for consistency. Also, note that it should be possible to combine filters (--client_id=xyz and --is_online=true) but that is currently not working and it's a known bug which will also be fixed shortly.

**Comment by jeremylink** [comment]
I have 2 use cases:

1. Query for all connected devices at application startup.
    This doesn't really work though since there is a limit of 100 results.
    This will only work if you can add some sorting of paging mechanism on the results.

2. Query for the status on a single device:
    This is not working until a future release that will fix the combo filters (--client_id and --is_online).

Do you have a timeframe for #2? 

Thanks.

**Comment by larshesel** [comment]
Hi @jeremylink 

We want to be able to do both 1 and 2, but I can't say any concrete to when the work will be done. I believe 2 will happen before 1 as it's more low-hanging.

**Comment by larshesel** [comment]
@jeremylink fyi the work to get 2) done is ongoing, see #346 .

**Comment by larshesel** [comment]
Hi @jeremylink #346 was merged to master a while ago and will be part of 1.0.1 as we considered that a bugfix. I suppose I can close this.
