### ISSUE TITLE
make rel error on FreeBSD 10.2 

### ISSUE THREAD

**Issue by hieutmd** [erlio/vernemq#336]
### Environment

- VerneMQ Version: 1.0.0
- OS: FreeBSD 10.2 
- Erlang/OTP version (if building from source): 19.3

### Expected behavior

Build to be successfull

### Actual behaviour

Run gmake sets following errors:

`gmake rel`

`gmake[1]: Leaving directory '/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/leveldb'
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 19: Missing dependency operator
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 24: Missing dependency operator
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 28: Missing dependency operator
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 32: Need an operator
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 65: warning: duplicate script for target "%.o" ignored
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 68: warning: duplicate script for target "%.o" ignored
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 71: warning: duplicate script for target "%.o" ignored
make[1]: "/usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /usr/home/userx/vernemq/_build/default/lib/eleveldb/c_src
===> Hook for compile failed!

gmake: *** [Makefile:56: rel] Error 1
`

**Comment by hieutmd** [comment]
Please advise on the issue.

**Comment by iblis17** [comment]
`cd /path/to/vernemq/_build/default/lib/eleveldb`
and apply this patch:
```
diff --git a/rebar.config b/rebar.config
index 237ef2e..8bb7c5b 100644
--- a/rebar.config
+++ b/rebar.config
@@ -14,6 +14,6 @@

 {pre_hooks, [{'get-deps', "c_src/build_deps.sh get-deps"},
              {compile, "c_src/build_deps.sh"},
-             {compile, "make -C c_src"}]}.
+             {compile, "gmake -C c_src"}]}.

 {post_hooks, [{clean, "c_src/build_deps.sh clean"}]}.
```

**Comment by iblis17** [comment]
and a quick patch for `/path/to/vernemq/_build/default/lib/eleveldb/c_src/Makefile`
```diff
diff --git a/c_src/Makefile b/c_src/Makefile
index 9380ae3..4938563 100644
--- a/c_src/Makefile
+++ b/c_src/Makefile
@@ -35,7 +35,7 @@ CFLAGS += -fPIC -I $(ERTS_INCLUDE_DIR) -I $(ERL_INTERFACE_INCLUDE_DIR) -I leveld
 CXXFLAGS += -fPIC -I $(ERTS_INCLUDE_DIR) -I $(ERL_INTERFACE_INCLUDE_DIR) -I leveldb/include

 LDLIBS += -L $(ERL_INTERFACE_LIB_DIR) -lerl_interface -lei
-LDFLAGS += -shared leveldb/libleveldb.a system/lib/libsnappy.a -lstdc++
+LDFLAGS += -shared leveldb/libleveldb.a snappy-1.0.4/.libs/libsnappy.a -lstdc++

 # Verbosity.

```

**Comment by iblis17** [comment]
I'm on `-CURRENT`
```
└─[iblis@abeing]% uname -a
FreeBSD abeing 12.0-CURRENT FreeBSD 12.0-CURRENT #4 r309367: Mon Dec 12 11:10:09 CST 2016     root@abeing:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by hieutmd** [comment]
Thank you, now it comes to this error:

`===> Compiling vmq_diversity
===> Compiling vmq_server
===> Compiling vmq_bridge
===> Running cuttlefish schema generator
===> Starting relx build process ...
===> Resolving OTP Applications from directories:
          /usr/home/userx/vernemq/_build/default/lib
          /usr/home/userx/vernemq/apps
          /usr/local/lib/erlang/lib
===> Resolved vernemq-1.0.0
===> Including Erts from /usr/local/lib/erlang
===> release successfully created!
===> Unable to copy from /usr/home/userx/vernemq/_build/default/lib/vmq_passwd/priv/vmq_passwd to /usr/home/userx/vernemq/_build/default/rel/vernemq/bin/vmq-passwd because of {copy_failed, enoent}

gmake: *** [Makefile:56: rel] Error 127
`

**Comment by iblis17** [comment]
`cd /path/to/vernemq/apps/vmq_passwd/c_src` and `make` can generate the executable `vmq_passwd`.
Then, back to `gmake rel` again.

**Comment by hieutmd** [comment]
It produces
`gcc -O2 -pipe   vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
make: exec(gcc) failed (No such file or directory)
*** Error code 1

Stop.
make: stopped in /usr/home/userx/vernemq/apps/vmq_passwd/c_src`

**Comment by iblis17** [comment]
Hmm chang gcc -> cc plz

**Comment by hieutmd** [comment]
`===> release successfully created!`
Nice. Thanks iblis17 for prompt guidance.

**Comment by iblis17** [comment]
:ok_hand:

**Comment by ipiku** [comment]
@hieutmd  i am also facing the issue as @iblis17 first stated but when i am trying to apply the patch 
diff --git a/rebar.config b/rebar.config i am getting the following error
diff: unrecognized option '--git'
diff: Try 'diff --help' for more information

Please advise on the issue

**Comment by iblis17** [comment]
@hieutmd 
I guess simply changing
```
diff --git a/rebar.config b/rebar.config
```
to
```
diff rebar.config rebar.config
```
may do the trick.

(I generate this patch from `git diff`)

**Comment by ipiku** [comment]
@hieutmd  diff rebar.config rebar.config would generate an empty file right? How do i generate the patch.
I am new to this. Please bear with me

**Comment by ipiku** [comment]
![image](https://cloud.githubusercontent.com/assets/28555091/25838074/d5ec9eaa-34ae-11e7-9fd3-ab10c1b06aed.png)

**Comment by iblis17** [comment]
@ipiku Oh,
`cd` the correct dir,
save following patch as a file named `rebar.config.patch`
```diff
diff  rebar.config rebar.config
index 237ef2e..8bb7c5b 100644
--- a/rebar.config
+++ b/rebar.config
@@ -14,6 +14,6 @@

 {pre_hooks, [{'get-deps', "c_src/build_deps.sh get-deps"},
              {compile, "c_src/build_deps.sh"},
-             {compile, "make -C c_src"}]}.
+             {compile, "gmake -C c_src"}]}.

 {post_hooks, [{clean, "c_src/build_deps.sh clean"}]}.
```

Then, issue `patch < rebar.config.patch`.

**Comment by ipiku** [comment]
@iblis17 I applied the patch and the output is as below 
![image](https://cloud.githubusercontent.com/assets/28555091/25841252/0a2f857a-34bd-11e7-8a93-e97a08e593c5.png)
The contents of the rebar.config.rej is as below 
@@ -14,6 +14,6 @@

 {pre_hooks, [{'get-deps', "c_src/build_deps.sh get-deps"},
              {compile, "c_src/build_deps.sh"},
-             {compile, "make -C c_src"}]}.
+             {compile, "gmake -C c_src"}]}.

 {post_hooks, [{clean, "c_src/build_deps.sh clean"}]}.

**Comment by iblis17** [comment]
@ipiku wierd. Or... modify the `rebar.config` manually is okay as well.

**Comment by ipiku** [comment]
@iblis17 Should i change the entire rebar.config to what you have specified earlier?

**Comment by iblis17** [comment]
@ipiku The main idea of that patch is change the `make` command to `gmake` on freebsd.
So, please edit the `rebar.config`, find the line contains `make -C ...`, and change it to `gmake -C ...`

**Comment by ipiku** [comment]
@iblis17 thank you so much for your guidance. VerneMQ is compiled
