### ISSUE TITLE
How to Shared Subscriptions and Retained messages work together?

### ISSUE THREAD

**Issue by jeremylink** [erlio/vernemq#337]
### Environment

- VerneMQ Version: 1.0.0rc2
- OS:
- Erlang/OTP version (if building from source):

I'm wondering how Shared Subscriptions and Retained messages work together...

Let's say I have 3 consumers running. If a Retained message is published, I would expect only one of the consumers to receive the message.

But now, what if I add a 4th consumer. Will it receive the last retained message as well?
What if I restart all of my consumers? Will just one of them get the retained message at startup, or all of them?

Thanks.

**Comment by larshesel** [comment]
Hi @jeremylink 

As per the MQTT v5 draft 10 (https://www.oasis-open.org/committees/download.php/59741/mqtt-v5.0-wd10.pdf) retained messages are not delivered to a client subscribing to a shared subscription. They will, however, receive subsequently published messages that are published with the retain flag.

So, in your question above only one of the 3 consumers will get the published retained message but a 4th consumer connecting later will not get the retained message. So, none of the clients will get the retained message if they all reconnect.

Hope that clarifies it a bit.

**Comment by larshesel** [comment]
Let us know if you have other questions or if the above wasn't clear.
