### ISSUE TITLE
Device "eth0" does not exist

### ISSUE THREAD

**Issue by funwun** [erlio/vernemq#338]
### Environment

- VerneMQ Version: 1.0.0
- OS: Docker, erlio/docker-vernemq:1.0.0

\# d run --rm --net=host  erlio/docker-vernemq:1.0.0

error
```
Device "eth0" does not exist.
```

There is no eth0 link, only ens33 link in my os ubuntu 16.04

**Comment by funwun** [comment]
IP_ADDRESS=$(ip -4 addr show eth0 | grep -oP "(?<=inet).*(?=/)"| sed -e "s/^[[:space:]]*//" | tail -n 1)

I found this in Dockerfile

**Comment by dergraf** [comment]
Why is there no eth0, how are you starting the container?

**Comment by funwun** [comment]
Note that I'm passing the '–net=host' flag in the docker run command, so the network is use the host network (ens33)

**Comment by larshesel** [comment]
Right, so we'd have to figure out something more general to get the 'canonical' ip address so it also works with host network adapters. Suggestions are welcome.

**Comment by larshesel** [comment]
Closing this for now as I don't think we'll be adding support for the `--net=host` flag for the time being. We'd be happy if someone contributes a way to support this, though.
