### ISSUE TITLE
webhooks: not trigger

### ISSUE THREAD

**Issue by funwun** [erlio/vernemq#340]
### Environment

- VerneMQ Version: erlio/docker-vernemq:1.0.0

I register all hooks, but the **auth_on_subscribe** and **auth_on_publish** is not triggered, the others is ok

**Comment by funwun** [comment]
I test the lua version, same as webhooks, auth_on_subscribe and auth_on_publish is not triggered

**Comment by funwun** [comment]
After I change the plugins.vmq_acl = on to off, everything is ok, is that right?

**Comment by dergraf** [comment]
Yes, exactly. The default vmq_acl is enabled and must be set to off in
order to use other authorization plugins.

Am 02.04.2017 5:05 vorm. schrieb "Lewis Deng" <notifications@github.com>:
