### ISSUE TITLE
FreeBSD: vernemq failed to start within 15 seconds

### ISSUE THREAD

**Issue by hieutmd** [erlio/vernemq#344]
### Environment

- VerneMQ Version: 1.0
- OS: FreeBSD 11.0
- Erlang/OTP version (if building from source): 19.2

### Expected behavior

- Should start after successful install

### Actual behaviour

`
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
`

When run vernemq console, get:
`
=INFO REPORT==== 4-Apr-2017::01:36:19 ===
    alarm_handler: {set,{{disk_almost_full,"/dev"},[]}}
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plmtrlvld_0,{undef,[{eleveldb,validate_options,[open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{data,[{dir,\"./data\"}]},{data_root,\"./data/leveldb\"},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{included_applications,[]},{limited_developer_mem,false},{sst_block_size,4096},{sync,false},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{verify_checksums,true},{verify_compaction,true},{write_buffer_size,45659641},{write_buffer_size_max,62914560},{write_buffer_size_min,31457280}]],[]},{plumtree_metadata_leveldb_instance,init_state,2,[{file,\"/usr/home/hieu/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_leveldb_instance.erl\"},{line,299}]},{plumtree_metadata_leveldb_instance,init,1,[{file,\"/usr/home/hieu/vernemq/_build/default/lib/plumtree/src/plumtree_metadata_leveldb_instance.erl\"},{line,131}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,247}]}]}}}}}},{plumtree_app,start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,plumtree,{{error,{shutdown,{failed_to_start_child,plumtree_metadata_leveldb_instance_sup,{shutdown,{failed_to_start_child,plm

Crash dump is being written to: ./log/erl_crash.dump...done
`

Please help

**Comment by larshesel** [comment]
Hi @hieutmd 

Does this happen the first time you start VerneMQ (i.e., clean with no data) or have you been running VerneMQ and are restarting it?

Note, that we don't officially support freebsd and we currently don't have access to any freebsd environments, so testing this stuff is not easy for us.

**Comment by hieutmd** [comment]
It is a clean install without data. In my previously reported error, I successfully built on FreeBSD 10.3 on an Amazon EC2 instance and started vernemq without a problem.

This server is brand new (no other software installed).

**Comment by hieutmd** [comment]
You can download the erl_dump here: http://115.146.123.137/crash.tar

**Comment by larshesel** [comment]
I just took a quick look at the crash dump, didn't seem to contain interesting information besides what's already in the console output above. From that error it looks like the issue is with plumtree which uses leveldb which I suppose is the problematic part to get to compile on freebsd in the first place - so maybe something changed between freebsd 10.3 and 11.

Did you build from scratch on freebsd 11 or copy the 10.3 build over? Maybe it'll work if you rebuild from scratch?

**Comment by hieutmd** [comment]
I built it from scratch (just after install OS on new Hard drive). I've been evaluating mosquitto and vernemq. Mosquitto has freebsd ported but it seems vernemq is more interesting.

**Comment by larshesel** [comment]
ok - then I'm afraid I'm out of ideas. Maybe @iblis17 has some idea? (I hope it's OK to pull you into this conversation, if not, just ignore ;) )

**Comment by dch** [comment]
@hieutmd can you provide details on how you built this? which compiler, anything else of interest? I don't get a successful build (admittedly on 12.0-CURRENT but still...).

gcc 5.4.0 & gmake both from ports
```
rm -f libleveldb.a
ar -rs libleveldb.a db/builder.o db/c.o db/db_impl.o db/db_iter.o db/dbformat.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o leveldb_os/warming_stub.o table/block_builder.o table/block.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table_builder.o table/table.o table/two_level_iterator.o util/arena.o util/bloom.o util/bloom2.o util/cache.o util/cache2.o util/coding.o util/comparator.o util/crc32c.o util/db_list.o util/env_posix.o util/env.o util/filter_policy.o util/flexcache.o util/hash.o util/histogram.o util/hot_threads.o util/logging.o util/murmurhash.o util/options.o util/perf_count.o util/status.o util/thread_tasks.o util/throttle.o port/port_posix.o util/lz4.o
ar: warning: creating libleveldb.a
gmake[1]: Leaving directory '/repos/vernemq/_build/default/lib/eleveldb/c_src/leveldb'
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 19: Missing dependency operator
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 24: Missing dependency operator
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 28: Missing dependency operator
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 32: Need an operator
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 65: warning: duplicate script for target "%.o" ignored
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 68: warning: duplicate script for target "%.o" ignored
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 71: warning: duplicate script for target "%.o" ignored
make[1]: "/repos/vernemq/_build/default/lib/eleveldb/c_src/Makefile" line 62: warning: using previous script for "%.o" defined here
make[1]: Fatal errors encountered -- cannot continue
make[1]: stopped in /repos/vernemq/_build/default/lib/eleveldb/c_src
===> Hook for compile failed!

gmake: *** [Makefile:56: rel] Error 1
 /r/vernemq ╍                 
```

**Comment by iblis17** [comment]
@dch please checkout this issue for build detail: #336 

@larshesel Sorry that i missed your tagging....
I will try to catch this up this weekend.

**Comment by larshesel** [comment]
If we can get it to compile and it looks like it's working we could add the recipe to our vagrant file (https://github.com/erlio/vernemq/blob/master/Vagrantfile) so it would be easier for everyone to use/play with/experiment with. Heck, then we might even try to generate the packages... Which version of FreeBSD should ideally be supported?

**Comment by iblis17** [comment]
I guess `eleveldb` hit some dependency issue. I `make` it manually.

To deal with it:
```shell
$ cd ~/vernemq/
$ gmake relclean

$ cd ~/vernemq/_build/default/lib/eleveldb/    # not c_src
$ make clean
$ make

$ cd ~/vernemq
$ gmake rel
```

**Comment by iblis17** [comment]
Not sure why. If i goto `.../eleveldb/c_src` and `make`, the outcome of `eleveldb.so` will corrupt.

**Comment by dch** [comment]
On Thu, 13 Apr 2017, at 07:53, Lars Hesel Christensen wrote:

> If we can get it to compile and it looks like it's working we
> could add
> the recipe to our vagrant file

> (https://github.com/erlio/vernemq/blob/master/Vagrantfile) so it
> would be
> easier for everyone to use/play with/experiment with. Heck, then
> we might
> even try to generate the packages... Which version of FreeBSD should

> ideally be supported?



10 and 11 are needed for ports tree; 12 should work without too much
changes iirc the linker is changing but this should be a small diff
if at all.


I'm happy to add packages to FreeBSD for this I'm away til 19th though.

**Comment by hieutmd** [comment]
Well done iblis17, it now starts as expected

```
$ cd ~/vernemq/
$ gmake relclean

$ cd ~/vernemq/_build/default/lib/eleveldb/    # not c_src
$ make clean
$ make

$ cd ~/vernemq
$ gmake rel
```

**Comment by iblis17** [comment]
> If we can get it to compile and it looks like it's working we could add the recipe to our vagrant file (https://github.com/erlio/vernemq/blob/master/Vagrantfile) so it would be easier for everyone to use/play with/experiment with.

I have not used vagrant before... I will try to sort out some patches for freebsd and work on a freebsd port first.

**Comment by iblis17** [comment]
I guess I found the problem on `eleveldb.so` ... there is some unresolved symbol on it.
I add `--no-undefined` flag for linker.

```diff
diff --git a/c_src/Makefile b/c_src/Makefile
index 9380ae3..fb89b6c 100644
--- a/c_src/Makefile
+++ b/c_src/Makefile
@@ -25,6 +25,7 @@ else ifeq ($(UNAME_SYS), FreeBSD)
     CC ?= cc
     CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
     CXXFLAGS ?= -O3 -finline-functions -Wall
+    LDFLAGS ?= --no-undefined
 else ifeq ($(UNAME_SYS), Linux)
     CC ?= gcc
     CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
```

and got the following build log: https://gist.github.com/iblis17/8a43cf60d193e41722751aa15c417997
I'm not skilled at Cpp. Any idea?

**Comment by ipiku** [comment]
Hi 
I have installed VerneMQ on FreeBSD and it starts. But when i give vernemq ping it says command not found.
![image](https://cloud.githubusercontent.com/assets/28555091/26092360/36a29234-3a2e-11e7-8aaf-05f93e19dfcb.png)
Please let me know if i am going wrong anywhere. Also guide me to setup a cluster and publish message.

**Comment by iblis17** [comment]
simply issue `bin/vernemq ping` ?

**Comment by ipiku** [comment]
@iblis17 Hi 
I am trying to create a cluster but when i execute bin/vmq-admin cluster join discovery-node = vmq1@10.0.2.15, I am getting a usage error as below. Please let me know where I am going wrong
![image](https://cloud.githubusercontent.com/assets/28555091/26146422/bf122096-3b0d-11e7-9066-2899626a907d.png)

**Comment by larshesel** [comment]
Hi @ipiku 

Since this is a new issue I'd recommend opening up a new issue to keep the discussion in this issue focused on a single thing. Secondly, may I ask if you could past the text directly instead of making screenshots? It's impossible to cut and past from screenshots to test out what you did and see if there is a subtle syntax errors somewhere.

That said, I don't see any issues with your syntax and I have no idea why that fails.
