### ISSUE TITLE
VerneMQ Error (max open files reached)

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#354]
Hi All,

Vernemq running on an EC2 instance suddenly stopped responding and on checking the error logs we found the following error :
2017-04-07 13:16:05.296 [error] <0.185.0> can't load acl file "/etc/vernemq/vmq.acl" due to emfile

The file does exist on the instance, though not being used. 
On restarting the vernemq application, this got resolved. Wanted to understand what could have caused this and how to prevent the same in future. 

We are using 0.15.3 version. 

Please let me know if you need anything else. 

Thanks,
Karthik

**Comment by larshesel** [comment]
Hi

`emfile` means the erlang VM can't open any more files or sockets, so this would suggest you've run into a system or user limit. I would look into the allowed number of processes and files for the vernemq user processes and make sure they are set high enough to support your use case. Should this happen again look at the actual files and sockets in use. Even better would be to include the number of open files and sockets in your monitoring to see how they evolve over time and see if something looks strange.

That VerneMQ stopped responding would fit with a system limit being hit as VerneMQ would not be able to accept new connections or sockets to handle `vernemq` or `vmq-admin` commands.

As a side node: If you're not using `vmq_acl` then it also might be a good idea to disable the plugin entirely, then it won't try to periodically access and reload the `vmq.acl` file.

I hope this helps and let us know if you have further questions.

**Comment by odx-tech** [comment]
Hi Larshesel,


Thanks for the prompt reply. We too suspected the same and have increased the limit of ulimit from 1024 to a substantially high number. 

Yes, we are keeping track of the counter - counter.socket_open , counter.socket_close to understand the connections getting created on the broker. 

Sure, will remove the vmq_acl dependency. Thanks for pointing. 

Will reach out to the group if we start to see this again. 

Thanks,
Karthik

**Comment by ranvijayj** [comment]
did everything according to https://vernemq.com/docs/misc/change-open-file-limits.html#_etc_ssh_sshd_config

but still max file not changing for the process
