### ISSUE TITLE
Questions about VerneMQ webhooks caching

### ISSUE THREAD

**Issue by EnCl** [erlio/vernemq#355]
### Environment

- VerneMQ Version: VerneMQ Version: 1.0.0rc2
- OS: :Linux Docker container
- Erlang/OTP version (if building from source):

### Expected behavior

I want to set the limit to indefinite for the webhooks caching.

### Actual behaviour

Hi,

I know how to enable caching and I saw this is working.
I have some questions regarding this.

1. What are the valid values for the cache timeframe ?

2. Is there a limit for the number of seconds ?

3. Can we set the time to indefinite ?

Thank you!

**Comment by larshesel** [comment]
Hi @EnCl 

to answer your questions:

1. Only non-negative integer values.
2. No - it will be parsed and turned into an erlang 'bignum' integer (it doesn't have a max size)
3. No.

Hope that helps,
Lars
