### ISSUE TITLE
Setting plugin specific configuration in vernemq.conf crashes the system

### ISSUE THREAD

**Issue by KnolBee** [erlio/vernemq#361]
### Environment

- VerneMQ Version:1.0.0rc2
- OS:Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Expected behavior

- Should be able to set Plugin specific settings in vernemq.conf
### Actual behaviour

- Setting plugin specific configuration in vernemq.conf crashes the system
As per below release notes, I will be able to set plugin specific settings in /etc/vernemq/vernemq.conf, However it crashes when tried to set the setting

https://github.com/erlio/vernemq/blob/b7cb18779733d73ad9769dce83ce3694c54dc732/changelog.md

### Entries in /etc/vernemq/vernemq.conf
plugins.myplugin = on
plugins.myplugin.path = set to local path
myplugin.testsetting = Test

###Error as below

root# vernemq console
15:41:06.807 [error] You've tried to set myplugin.testsetting, but there is no setting with that name.
15:41:06.807 [error]   Did you mean one of these?
15:41:06.838 [error]     plugins.$name
15:41:06.838 [error]     plugins.$name.path
15:41:06.838 [error]     plugins.vmq_acl
15:41:06.842 [error] Error generating configuration in phase transform_datatypes
15:41:06.842 [error] Conf file attempted to set unknown variable: myplugin.testsetting
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.

###Here is my schema file in priv/myplugin.schema

{mapping, "myplugin.testsetting", "myplugin.testsetting", [
                                               {default, "Test"},
                                               {datatype, string}
                                              ]}.

**Comment by larshesel** [comment]
Hi, thanks for reporting. I think this might be a chicken-and-egg problem we didn't think about where vernemq doesn't know about the schema file of your plugin when booting. As a workaround, could you try and copy your schema file into the `share/schema` folder of vernemq and see if it works then?

**Comment by KnolBee** [comment]
Thanks, Iarshesel, It worked! Will this be fixed in future so this workaround can be avoided? Also, can it be updated in the documentation too for plugins?

**Comment by larshesel** [comment]
I don't think this can be fixed easily as VerneMQ would have to know where to look for the schema file somehow (before it parses the vernemq.conf file). Documenting this might be the best option - but maybe we'll come up with an elegant solution ;)

Thanks again for bringing this to our attention!

**Comment by larshesel** [comment]
We haven't come up with a better solution, so the workaround described is the solution we have to live with for the time being.
