### ISSUE TITLE
Crashing when anonymous turned off

### ISSUE THREAD

**Issue by ssarath** [erlio/vernemq#368]
### Environment

- VerneMQ Version:1.0.0-415f591d
- OS:Ubuntu 16.04.1 LTS Xenial
- Erlang/OTP version (if building from source):

### Expected behavior

when allow_anonymous = off and plugins.vmq_passwd = onand with password file and acl parameters,
either  subscribe or publish client should successfully connect and complete the task.

### Actual behaviour

 I can make connection - both sub and pub using paho c or mosquitto clients when allow_anonymous is turned on. However  I get failed to connect error (return -1)  when I turn off allow_anonymous and turn on passwd. I see following error message in crash log. I used vmq_passwd utility to create user and using the encrypted passwd as argument while using pub / sub . Please let me know if I am missing out any thing in configuration ?
2017-04-17 02:18:53 =CRASH REPORT====
  crasher:
    initial call: vmq_ranch:init/5
    pid: <0.6631.0>
    registered_name: []
    exception error: bad argument: [{ets,lookup,[vmq_passwd,<<"cultgateway">>],[]},{vmq_passwd,check,2,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_passwd/src/vmq_passwd.erl"},{line,106}]},{vmq_plugin_helper,all_till_ok,2,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_plugin/src/vmq_plugin_helper.erl"},{line,27}]},{vmq_mqtt_fsm,auth_on_register,3,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,593}]},{vmq_mqtt_fsm,check_user,2,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,520}]},{vmq_mqtt_fsm,in,3,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,175}]},{vmq_mqtt_fsm,data_in,3,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_server/src/vmq_mqtt_fsm.erl"},{line,143}]},{vmq_ranch,handle_message,2,[{file,"/opt/vernemq/distdir/vernemq-1.0.0-415f591d/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,163}]}]
    ancestors: [<0.354.0>,<0.353.0>,ranch_sup,<0.66.0>]
    messages: []
    links: [<0.354.0>,#Port<0.12449>]
    dictionary: [{socket_open,<<>>},{max_msg_size,0},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[286416865018073090|216516521282390132]}},{bytes_received,<<>>},{mqtt_connect_received,<<>>}]
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 667
  neighbours:
2017-04-17 02:18:53 =ERROR REPORT====
Ranch listener {{172,31,30,224},1884} had connection process started with vmq_ranch:start_link/4 at <0.6631.0> exit with reason: badarg

**Comment by dergraf** [comment]
Hi @ssarath 
Can you share the `error.log`? It looks like the `vmq_passwd` plugin crashed prior the error you're seeing here.

**Comment by ssarath** [comment]
here is the content of error log ..

2017-04-17 02:18:53.512 [error] <0.6631.0> CRASH REPORT Process <0.6631.0> with 0 neighbours crashed with reason: bad argument in call to ets:lookup(vmq_passwd, <<"cultgateway">>) in vmq_passwd:check/2 line 106
2017-04-17 02:18:53.512 [error] <0.6631.0> Ranch listener {{172,31,30,224},1884} terminated with reason: badarg
~

**Comment by dergraf** [comment]
Can you share the logs before this event?

**Comment by ssarath** [comment]
[console_log_0.txt](https://github.com/erlio/vernemq/files/929729/console_log_0.txt)
[console_log_1.txt](https://github.com/erlio/vernemq/files/929730/console_log_1.txt)
[crash_log_1.txt](https://github.com/erlio/vernemq/files/929732/crash_log_1.txt)
[crash_log_0.txt](https://github.com/erlio/vernemq/files/929735/crash_log_0.txt)
[error_log_0.txt](https://github.com/erlio/vernemq/files/929736/error_log_0.txt)
[error_log_1.txt](https://github.com/erlio/vernemq/files/929737/error_log_1.txt)

**Comment by dergraf** [comment]
```
2017-04-16 17:18:05.748 [error] <0.351.0> gen_server vmq_passwd_reloader terminated with reason: no match of right hand value [<<"cult123\n">>] in vmq_passwd:parse_passwd_line/1 line 123
2017-04-16 17:18:05.748 [error] <0.351.0> CRASH REPORT Process vmq_passwd_reloader with 0 neighbours exited with reason: no match of right hand value [<<"cult123\n">>] in vmq_passwd:parse_passwd_line/1 line 123 in gen_server:terminate/7 line 812
2017-04-16 17:18:05.748 [error] <0.350.0> Supervisor vmq_passwd_sup had child vmq_passwd_reloader started with vmq_passwd_reloader:start_link() at <0.351.0> exit with reason no match of right hand value [<<"cult123\n">>] in vmq_passwd:parse_passwd_line/1 line 123 in context child_terminated
```

This is the problem. `vmq_passwd` isn't able to parse your password file and crashes. Are you using the `vmq-passwd` utility?

**Comment by ssarath** [comment]
I tried all the combinations ... the one you see was without using vmq_passwd utility to check if there is an issue with encryption. Any case .. I will create the fresh log files with  exact sequence . .. and send clean log files ...

**Comment by ssarath** [comment]
I changed the ownership of the password file and it is working fine now.
