### ISSUE TITLE
Can't authenticate with MySQL database

### ISSUE THREAD

**Issue by enricodetoma** [erlio/vernemq#369]
### Environment

- VerneMQ Version: 1.0.1
- OS: Ubuntu 16.04

### Expected behavior

- Connecting to VerneMQ using MySQL auth (client:test-cliente, username: test-user, password: 123)

This is my MySQL configuration:
`plugins.vmq_passwd = off`
`plugins.vmq_acl = off`
`plugins.vmq_diversity = on`
`vmq_diversity.mysql.host = 127.0.0.1`
`vmq_diversity.mysql.port = 3306`
`vmq_diversity.mysql.user = myuser`
`vmq_diversity.mysql.password = mypassword`
`vmq_diversity.mysql.database = mydatabase`

I created `test-user` auth record this way:
`INSERT INTO vmq_auth_acl 
    (mountpoint, client_id, username, 
     password, publish_acl, subscribe_acl)
VALUES 
    ('', 'test-client', 'test-user', PASSWORD('123'), 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
     '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
`

### Actual behaviour

- Authentication fails.

This is what I find in `error.log`:
`2017-04-20 04:12:31.959 [error] <0.409.0>@vmq_mqtt_fsm:check_user:535 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found`

**Comment by dergraf** [comment]
Hi there

Have you set `vmq_diversity.auth_mysql.enabled = on` ?

Best,
Andre

**Comment by enricodetoma** [comment]
I didn't set it. Now it is set, but the error is always the same:

`2017-04-20 08:38:14.578 [error] <0.422.0>@vmq_mqtt_fsm:check_user:535 can't authenticate client {[],<<"test-client">>} due to
                                no_matching_hook_found`

**Comment by dergraf** [comment]
Have you restartet your broker after changing the config file?

What is the output of `vmq-admin plugin show`?

**Comment by enricodetoma** [comment]
Yes I did `vernemq stop` then `vernemq start`.

Here is the output:
`# vmq-admin plugin show`
`+-------------+-----------+-------+-----+`
`|   Plugin    |   Type    |Hook(s)|M:F/A|`
`+-------------+-----------+-------+-----+`
`|vmq_diversity|application|       |     |`
`+-------------+-----------+-------+-----+`

**Comment by enricodetoma** [comment]
Ah, never mind: there was an additional line `vmq_diversity.auth_mysql.enabled = off` later on in the file. 
How silly I was.
Thank you again for your support.
