### ISSUE TITLE
Error when subscribing to many topics quickly.

### ISSUE THREAD

**Issue by jemc** [erlio/vernemq#37]
I'm testing VerneMQ with the tests for an existing application that uses `libmosquitto` as a client.  The application and tests work well with mosquitto as the MQTT broker.

The first issue I've run into is with a test that subcribes to 500 topics, publishes a single message on each one, then checks that they were all received by the subscriber.

During the call that makes 500 concurrent subscribe requests from the client to the broker, the VerneMQ broker disconnects the client and I see the following message in the log window:
```
2015-08-17 14:30:54.147 [warning] <0.486.0>@vmq_ranch:teardown:120 [<0.487.0>] session stopped
                       abnormally due to parse_error
```

I'm using git rev 1a9ff2a3071851f4931b8d5761ae5c70cee50bb4, built with `make rel`.

**Comment by dergraf** [comment]
is it one client subscribing to 500 topics or 500 clients? 
We currently have an issue open to generate better parse error logs ;)

**Comment by jemc** [comment]
> is it one client subscribing to 500 topics or 500 clients? 

One single client.

**Comment by dergraf** [comment]
Ok. Can you try if this was fixed by the latest vmq_commons.
./rebar3 upgrade vmq_commons
&
make rel

Should do it

**Comment by jemc** [comment]
@dergraf Thanks, that fixed it, but I'm running into another issue now - I'll open another ticket.
