### ISSUE TITLE
Setting Up SSL

### ISSUE THREAD

**Issue by kevingarman** [erlio/vernemq#373]
Hi,

I'm using your 1.0.1 package for Xenial and I'm trying to get SSL working.  I've got a cert from Lets Encrypt and have set the neccessary config options:

```
listener.ssl.default = 0.0.0.0:1883
listener.ssl.cafile = /etc/vernemq/cacerts.pem
listener.ssl.certfile = /etc/vernemq/cert.pem
listener.ssl.keyfile = /etc/vernemq/key.pem
```

I'm trying to test using the mosquitto_pub app....something like:

`mosquitto_pub -h myhost -p 1883 -u test -P test123 -k 600 -t testrw -m hello --cafile cacerts.pem`

I'm not seeing any errors on either side but the publish just sort of hangs.

What's the simplest way to test a basic SSL setup?  Preferred test client?  Is there certain logging I should turn on?

Any guidance would be much appreciated.

Thanks,
Kevin

**Comment by ioolkos** [comment]
Hi @kevingarman 
thanks for using VerneMQ :) 

Is there absolutely no port conflict on 1883? could a normal VerneMQ TCP listener be running there?

I think `mosquitto_pub` should work in the way you use it. Another option is to test with `openssl s_client` which might give you better TLS error hints.

Have you configure VerneMQ to use client certificates, or not? (in your case apparently not, which is OK)

**Comment by kevingarman** [comment]
Thanks for the reply @ioolkos.  The is no conflict on 1883, I verified by commenting out listener.ssl.default = 0.0.0.0:1883.  When commented out, nothing was listening on 1883.

Correct, I am not using client certs.

I will try the openssl s_client and see what happens.

**Comment by kevingarman** [comment]
@ioolkos...I got it working.  The trick was using the `--insecure` flag on mosquitto so that it would ignore the fact that my server name is not the same as the server name in your test crt.

**Comment by kevingarman** [comment]
Ok...along the same thread...  I have it working with your test crt, but how would I use lets encrypt?  I've got pem files for the chain, server cert, and server key, but when I use them in place of your test cert, `openssl s_client` says `CONNECTED(00000003)` and hangs rather than return back the cert info.

Any thoughts?

**Comment by ioolkos** [comment]
This bugfix is tagged for OTP 19.3.3: https://github.com/erlang/otp/commit/1364c7308e17d43d1a2244e3f2bf11cfec3789ef

Supposed to fix 'hangs' with big SSL handshake messages. Don't ask me what big means :)

But yeah, maybe the reason is also something completely different...

**Comment by dergraf** [comment]
@ioolkos why do you think that the mentioned OTP bugfix is related to this issue?

**Comment by ioolkos** [comment]
It could explain the handshake hangs, under certain conditions (big handshakes, whatever that means). Saw something similar on RabbitMQ mailing list.

Most likely it's unrelated. I had no further ideas what could cause this.

@kevingarman I guess you haven't digged deeper here, in the meantime?

**Comment by kevingarman** [comment]
So I think the vernemq side is working now.  It seems there was a permissions issue with the cert files.  Now `openssl s_client `seems happy connecting.  `mosquitto_pub` is still not working with the let's encrypt setup, but that doesn't seem to be a vernemq issue.  Thanks for your help!

**Comment by dhaval1983** [comment]
I am getting this error
WebSocket connection to 'wss://domainname.com:8443/mqtt' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID in chrome developer console
can you please help
[vernemq.txt](https://github.com/erlio/vernemq/files/2055608/vernemq.txt)

**Comment by mansurali901** [comment]
**your settings are correct** 
The domain certificate is issued by intermediate “Let’s Encrypt Authority X3”, this intermediate is cross-signed by “DST Root CA X3” (from IdenTrust). IdenTrust is widely trusted by most OSes and applications, we will “DST Root CA X3” as root CA.
if you are not on too old OS then you could use this from your local machine 

`cat /etc/ssl/certs/DST_Root_CA_X3.pem /etc/letsencrypt/live/$domain/chain.pem > ca.pem`

`root@ip-20-10-0-7:/etc/letsencrypt/live# mosquitto_pub -h mqtt.host.com -t test -m "hello world" -p 8883 --cafile ca.pem -u username -P password
`
`
root@ip-20-10-0-7:/etc/letsencrypt/live# mosquitto_sub -h mqtt.host.com -p 8883 --cafile ca.pem -t test -u username -P password
hello world
hello world
hello world`
