### ISSUE TITLE
Vernemq Down Suddenly

### ISSUE THREAD

**Issue by VincentNgai86** [erlio/vernemq#377]
### Environment
- VerneMQ Version: 1.0.1
- OS:  ubuntu 16 
- Erlang: esl-erlang_19.2-1 

### Description 
We have encount issue, a vernemq cluster node suddenly go down. 
We have 3 vernemq node in a cluster and 2 of them are access to publicly.
We have check the CPU  are getting higher usage during the issue (But still have room) . 

Anyone can give us some ideal what was happen? 

### Log
The issue happen in 23:27

**Crash Report**
2017-05-05 23:19:35 =ERROR REPORT====
2017-05-05 23:19:56 =ERROR REPORT====
2017-05-05 23:20:18 =ERROR REPORT====
2017-05-05 23:20:40 =ERROR REPORT====
2017-05-05 23:27:31 =ERROR REPORT====
** State machine <0.24423.3> terminating
** Last message in was {'DOWN',#Ref<0.0.1048577.230464>,process,<0.24418.3>,normal}
** When State == online
**      Data  == {state,{[],<<“CLIENTID">>},{queue,{[],[]},{[],[]},fifo,1000,0,0},balance,#{<0.24418.3> => {session,<0.24418.3>,true,notify,{queue,{[],[]},{[],[]},fifo,10000,0,0}}},undefined,500,undefined,100,undefined,#{allow_multiple_sessions => false,clean_session => true,is_plugin => false,max_drain_time => 500,max_msgs_per_drain_step => 100,max_offline_messages => 1000,max_online_messages => 10000,queue_deliver_mode => balance,queue_type => fifo}}
** Reason for termination =
** {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}}
2017-05-05 23:27:31 =CRASH REPORT====
  crasher:
    initial call: vmq_queue:init/1
    pid: <0.24423.3>
    registered_name: []
    exception exit: {{timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}},[{gen_fsm,terminate,7,[{file,"gen_fsm.erl"},{line,559}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [vmq_queue_sup_43,vmq_queue_sup_sup,vmq_server_sup,<0.244.0>]
    messages: []
    links: [<0.311.0>]
    dictionary: [{queue_message_in,<<>>},{queue_teardown,<<>>},{queue_message_out,<<>>},{rand_seed,{#{max => 288230376151711743,next => #Fun<rand.8.41921595>,type => exsplus,uniform => #Fun<rand.9.41921595>,uniform_n => #Fun<rand.10.41921595>},[16800108604894741|138361958222283755]}},{queue_setup,<<>>}]
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 212615
  neighbours:

**Error Log**
2017-05-05 23:27:31.632 [error] <0.24423.3> gen_fsm <0.24423.3> in state online terminated with reason: {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}}
2017-05-05 23:27:31.632 [error] <0.24423.3> CRASH REPORT Process <0.24423.3> with 0 neighbours exited with reason: {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}} in gen_fsm:terminate/7 line 559
2017-05-05 23:27:31.632 [error] <0.311.0>@vmq_queue_sup:report_error:248 vmq_queue process <0.24423.3> exit for subscriber {[],<<"CLIENTID">>} due to {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}}
2017-05-05 23:27:31.642 [error] <0.13298.47> gen_fsm <0.13298.47> in state online terminated with reason: {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}}
2017-05-05 23:27:31.642 [error] <0.13298.47> CRASH REPORT Process <0.13298.47> with 0 neighbours exited with reason: {timeout,{gen_server,call,[<0.744.0>,{call_function,on_client_gone,[{mountpoint,<<>>},{client_id,<<"CLIENTID">>}]}]}} in gen_fsm:terminate/7 line 559
2017-05-05 23:27:31.642 [error] <0.283.0>@vmq_q

**Comment by larshesel** [comment]
The title says VerneMQ down - is the entire VerneMQ node gone or are you experiencing issues with a client getting disconnected? The above logs does not suggest that the entire VerneMQ node crashed. If the entire node has crashed there should be an erlang crash dump file (`erl_crash.dump`) which may contain relevant information.

**Comment by VincentNgai86** [comment]
[erl_crash.zip](https://github.com/erlio/vernemq/files/985043/erl_crash.zip)
I find both public access vernemq server have the erl crash dump file(as attached)
and we have monitor there have huge drop of connected client (around 2.5k drop to 0.5k)

**Comment by dergraf** [comment]
Thanks for the crash dump. Have you developed a Lua plugin which hooks into `on_client_gone`. What is this plugin doing? Given your log files, somthing (maybe database access) is blocking you in `on_client_gone`.

**Comment by ioolkos** [comment]
It seems to me that those 2 crash_dumps are indicating that VerneMQ crashes on trying to boot. Is that correct? If yes, you'll have to find the reason... and unfortunately this might be a lot: from a node name already in use to some external process blocking the application init.

**Comment by VincentNgai86** [comment]
@dergraf 
Yes we have Lua plugin hooks into on_client_gone
Will try request if can post the script in here 

@ioolkos 
Seems not 
We have start working fix at 23:4X or 5X 
But the crash log show 23:27 already logged

**Comment by ioolkos** [comment]
@VincentNgai86 ok, thanks.
@larshesel from vmq_queue_sup_sup to vmq_queue_sup down to the queues and sessions, do you think it's possible there's a possibility of a restart exhaustion escalation?

**Comment by larshesel** [comment]
It's a possibility - but then it doesn't show from the logs above. If the complete log files until shutdown are provided maybe we can spot something.

**Comment by VincentNgai86** [comment]
Hi @larshesel  and @ioolkos 

Here is the function


function on_disconnect(args)
	local clientId = args.client_id
	--log.info("|AuditLog|on_disconnect|"..clientId)

	local resultList = getClientandHomeId(clientId)
	--log.info("|AuditLog|on_disconnect|"..resultList[1].."|"..resultList[2])

	if resultList[1] == 'nil' then
	elseif resultList[2] == 'nil' then
	else
		local userType = ''
  		userType = getUserType(resultList[1])
		if userType == 'lamp' then
			setLampOffline(resultList[2],resultList[1])
		end
		if userType == 'oldlamp' then
			setLampOffline(resultList[2],resultList[1])
		end
	end


function setLampOffline(homeId,userName)
	mysql.execute("wizSQL", [[update certificates set connection_status=connection_status-1 where home_id=? && username=?]],homeId,userName)
	log.info("|AuditLog|setLampOffline|"..console_successful_disconnect.."|"..homeId.."|"..userName)
end



hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    on_client_offline = on_disconnect,
    on_client_gone = on_disconnect
}

**Comment by ioolkos** [comment]
Let's think this through once more:
- what we know so far is that a session is going down and that the corresponding queue encounters a timeout in the handling of the `on_client_gone` functionality. 
- The `on_client_gone` hook goes over the vmq_diversity_script gen_server and should end up calling a Lua script which executes a MySQL query.
- Due to this timeout the queue process crashes.

I think the most important thing to know here is whether this was all about a single session/queue, or about a load of processes crashing around the same time. In the case of a lot of `on_client_gone` events, anything down the road could cause the timeout.

**Comment by dergraf** [comment]
#381 Should fix the crashes.

**Comment by dergraf** [comment]
#404 Gives you further possibilities to increase performance of your Lua script by starting multiple script workers and load balance the plugin hooks among those workers. 
Defining the  currently *undocumented* global variable `num_states = 10` in your Lua script would create 10 instances of the script and apply load balancing among them.

**Comment by larshesel** [comment]
The fixes has been released as part of the VerneMQ 1.1.0 release so I'm closing this - we'd of course appreciate any feedback you might have.
