### ISSUE TITLE
Weird error deploy using ansible

### ISSUE THREAD

**Issue by siscia** [erlio/vernemq#378]
I am using ansible to deploy vernemq in this early stage.

Sometimes, just sometimes, I got this error:

fatal: [ec2-54-93-182-126.eu-central-1.compute.amazonaws.com]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://bintray.com/artifact/download/erlio/vernemq/deb/precise/vernemq_1.0.1-1_amd64.deb, 'NoneType' object has no attribute 'read'"}

The ansible task is just

```
- name: download and install vernemq
  apt: deb=https://bintray.com/artifact/download/erlio/vernemq/deb/precise/vernemq_1.0.1-1_amd64.deb
```

It is definitely nothing blocking or deal-killer, however it is quite annoying and I thought that I need to signal it.

Machine with Ubuntu on EC2

**Comment by dergraf** [comment]
Huh.. interesting, this seems like the error is coming from our download hosting provider bintray.com.

**Comment by siscia** [comment]
Yeah, I think so... 

Just let you guys know.

**Comment by ioolkos** [comment]
appreciate your feedback, thanks!
