### ISSUE TITLE
issues with format of username on connect

### ISSUE THREAD

**Issue by jeremylink** [erlio/vernemq#379]
### Environment

- VerneMQ Version: 1.0.1
- OS: Docker container

I'm having problems with endpoint authentication at connect.

My usernames are of the form: abc_def_ghi.blah000000001, abc_def_ghi.blah000000002, abc_def_ghi.blah000000003... (these are 25 characters in length).
And my client IDs are a 32 character UUID.

I'm using webhooks for authentication (always returns a code of 200).

I'm able to connect with the first endpoint, but subsequent ones fail with the only error in the log file being:
_2017-05-11 20:21:59.151 [error] <0.933.0>@vmq_webhooks_plugin:call_endpoint:476 calling endpoint failed due to {invalid_response_code,500}
2017-05-11 20:21:59.151 [warning] <0.933.0>@vmq_mqtt_fsm:check_user:545 can't authenticate client {[],<<"f812432dd26d4435b35546a0f53f4863">>} due to error
2017-05-11 20:21:59.151 [debug] <0.933.0>@vmq_ranch:teardown:123 session normally stopped_

I see a few potential issues:
1. MQTT spec states that the client ID must support at least 23 characters, but the UUID is 32.
    -> most/all other implementations I've used have no problem with 32 chars. Just want to confirm.
2. The username is supposed to support UTF-8, but maybe that is not true (for '.' and '_')?
3. The username is supported up to 65k characters, but maybe there is an internal server restriction?
4. Why does the log file complain about an error code of 500 when that is not being sent back?

**Comment by ioolkos** [comment]
Hi @jeremylink thanks for your detailled report:

Re the potential issues you mention:
1. You can enforce "at most" 23 chars as per spec if you want to. VerneMQ default is `max_client_id_size=100`.
2. Correct. This should work.
3. I'll check for restrictions, but there's certainly nothing in the range you're currently using for usernames.
4. I don't know currently, @larshesel maybe?

I think the key information to focus on here is that the first client connects, but subsequent not.

**Comment by larshesel** [comment]
The return code is the one the http client has received from the server. So unless the http client we use is buggy, which would be surprising, your server is really sending back a code 500. Can you verify with wireshark or a http analyzer tool what is actually returned from that endpoint?

**Comment by larshesel** [comment]
To further clarify, HTTP code 500 means 'internal server error' which indicates some kind of issue with configured endpoint. This would explain why the code 200 is not returned.

**Comment by jeremylink** [comment]
I will setup wireshark later today to verify, but I'm almost certain that my app is not returning a 500 code:
1. We always return 200. The status is part of the body.
2. I had an earlier issue that required me to upgrade the broker and remove most of the optional return values in the webhook response. Before I did this, the server would still report a 500 failure (and my webhook code was the same as today in that it only returns a 200).

I suspect you have a log message that on auth failure it always reports a 500 even if the response was a 200.


-Jeremy

________________________________

**Comment by ioolkos** [comment]
@larshesel maybe the HTTP client pool (Hackney pool) can hang or something?
https://github.com/erlio/vernemq/blob/master/apps/vmq_webhooks/src/vmq_webhooks_plugin.erl#L329

**Comment by jeremylink** [comment]
Well, I'm looking at in Wireshark and I do see my code returning a 500. Not
sure that is possible, but something must be failing. Still trying to
figure out why.

**Comment by larshesel** [comment]
Ok, then I it seems to not be an issue with Verne and we can go ahead and close this issue.
