### ISSUE TITLE
can't load acl file "./etc/vmq.acl" due to emfile ?

### ISSUE THREAD

**Issue by bayuemu** [erlio/vernemq#38]
tow vernemq cluster, one print "can't load acl file "./etc/vmq.acl" due to emfile" and 

11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[sockets,last_30sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[sockets,last_10sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[connects,received,last_sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[connects,received,last_min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[connects,received,last_5min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[connects,received,last_30sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[connects,received,last_10sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,sent,last_sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,sent,last_min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,sent,last_5min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,sent,last_30sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,sent,last_10sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,received,last_sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,received,last_min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,received,last_5min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,received,last_30sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,received,last_10sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,dropped,last_sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,dropped,last_min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,dropped,last_5min],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,dropped,last_30sec],value,false,[]})
11:13:45.437 [error] No such subscriber (Key={key,vmq_report_systree,[cluster,bytes,dropped,last_10sec],value,false,[]})
11:13:45.439 [error] No such subscriber (Key={key,vmq_report_systree,[sockets,last_sec],value,false,[]})
11:13:45.519 [error] No such subscriber (Key={key,vmq_report_systree,[sockets,last_min],value,false,[]})
11:13:45.519 [error] No such subscriber (Key={key,vmq_report_systree,[sockets,last_5min],value,false,[]})
-----------------------------------
11:13:35.436 [error] CRASH REPORT Process vmq_report_systree with 2 neighbours crashed with reason: no case clause matching false in vmq_reg:publish/1 line 282
11:13:35.436 [info] Systree Reporter initialized; Opts: []
11:13:35.438 [error] CRASH REPORT Process vmq_report_systree with 2 neighbours crashed with reason: no case clause matching false in vmq_reg:publish/1 line 282
11:13:35.438 [info] Systree Reporter initialized; Opts: []
11:13:35.439 [error] CRASH REPORT Process vmq_report_systree with 2 neighbours crashed with reason: no case clause matching false in vmq_reg:publish/1 line 282
-------------------------------------

how can i do?

**Comment by ioolkos** [comment]
Have you by chance deleted the /etc/vmq.acl file on this node? (or changed file permissions on it?)

Note that you also need at least one rule in the file.
As a default this is
topic # 
which allows subscription and publishs to all topics for all clients.

The vmq.acl file also needs to be deployed to all cluster nodes. You can of course use the same everywhere, or use files with different rule sets on each node.

Have a look at the docs here https://verne.mq/docs/apps/vmq_acl/docs/vmq_acl.html

**Comment by dergraf** [comment]
@bayuemu any update on this?

**Comment by dergraf** [comment]
solved, as no response from original poster.
