### ISSUE TITLE
Remove Lua script bottleneck

### ISSUE THREAD

**Issue by dergraf** [erlio/vernemq#382]
Feature Request:

Currently a Lua script and it's Lua state is kept in a gen_server per script. As a consequence a call to the same hook in the script required to go through the same gen_server. 
Therefore, the built-in connection pools for the various database backends don't help to distribute load as long as only a single script is used.
The single-script/single-gen_server case is the approach which is currently in use for all the provided auth_cache solutions.

Solution for this problem:

Assuming no Lua state manipulations happens during the execution of a script (as it is the case for the auth_cache) we could have multiple gen_servers that serve the same script and load balance the Lua function calls. The `keep_state` config variable (https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_script.erl#L82) could indicate whether the script has side-effects wrt. to the Lua state. If it hasn't side-effects we could implement a transparent load balancing.

What do you think @larshesel / @ioolkos

**Comment by larshesel** [comment]
I think this sounds like a good idea. The default value would be to have `keep_state=true` and assume scripts have side-effects (and need to keep the state around)? All the scripts we know have no sid-effects can then be marked `keep_state=false` and we can spawn multiple script executors?
