### ISSUE TITLE
keep-alive for webhooks

### ISSUE THREAD

**Issue by baranga** [erlio/vernemq#383]
We are using webhooks for authentication and authorization of clients. Our first load tests / benchmarks revealed very bad performance using this approach.

I'm aware we could just switch over to a DB based approach, but I wondered why webhooks are so slow. After poking around in webhook sources I seen the http calls are done in a very naive way (at last I believe that). What I've seen every hook opens a new connection but hackney supports keep-alive and connection pooling.

Did you done any benchmarking on webhooks? Would it be possible to implement a bit more clever webhook handling?

Maybe I got it all wrong. I'm a real erlang noob.

**Comment by ioolkos** [comment]
Hi @baranga thanks for speaking up! Let's find out why webhooks are slow for you. What authentication and authorization (publish) rates were you hoping to achieve? is this with or without the webhooks cache?

**Comment by baranga** [comment]
I'm not using the cache yet but will look into it.
Our test scenario is more then 100x slower with webhooks then without. For sure its slower, but right its a bit to slow. Multiple instances of webhook endpoint behind a load balancer increased performance by factor 2.
Using a single keep-alive connection may be slower then massive parallel throw away connections. But in our scenario it looks like connection initialization might be the issue.
Would it be helpful to setup some kind of demo?

**Comment by larshesel** [comment]
Hi @baranga 

vmq_webhooks is already using the keep-alive timeout for all pools, it's defined here: https://github.com/erlio/vernemq/blob/master/apps/vmq_webhooks/src/vmq_webhooks_plugin.erl#L330

There's probably something which can be optimized regarding the http communication between the webhooks and the endpoints, but at the end of the day having to traverse a networks stack a couple of times (even if the webhooks are running locally) will cost between some hundred microseconds to something in the millisecond range. Compared to local code execution which can be in the nano-second range (depending on the work) it's not surprising to have a factor 100 with webhooks vs without.

If you have some suggestions how we can speed up the hackney http requests we'd love to hear about it, but I think as @ioolkos suggests, you should probably look at using the cache.

**Comment by baranga** [comment]
@ioolkos and @larshesel thanks for support. You are completely right. I could verify connection keep alive works and is not source of my performance issue. Caching works great for my synthetic checks.

Sorry for the buzz. :(
