### ISSUE TITLE
VerneMQ stopped accepting connections

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#385]
Hi,

We've been using vernemq for one of our mqtt application on an android app. What we have just observed is that the vernemq application on a node stopped taking in new connections. The client making the connect call wasn't succeeding. On checking, the node had enough room for CPU, connections etc. Also the metrics command was responding at that point in time. I had to restart the vernemq application to have this addressed. Not sure what has happened in here and how to debug the same. Checked the console and error logs. Couldn't understand what has caused the same. The open connections were around 20k when we started to see this. 

Please let me know how to proceed in here to understand what caused this. 

Thanks,
Karthik

**Comment by larshesel** [comment]
Hi - sorry to hear you're running into issues. To have any chance of helping we'd need to know the OS, which version of vernemq you're running as well as see the error and console logs.

Could it be you're running into system limits? Max open files or an issue like that?

**Comment by odx-tech** [comment]
Hi @larshesel,

Here are the details you asked for:
OS: ubuntu
vernemq-version: 0.15.3-b24d5118

No, our service-limits are very high:

ubuntu@ip-172-31-2-95:~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 128642
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 131072
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 131072
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

From what I recollect the metrics during the issue-time, our socket_open count was around 160k and socket_close count was around 140k with around 20k connections connected to the server.

I've attached error and console logs during the event before I had restarted. 
[vernemq_logs.zip](https://github.com/erlio/vernemq/files/1008059/vernemq_logs.zip)

The console and error logs are from 16th May 01:00:00 UTC till current time. The incident we observed was roughly between 16th May 22:30 UTC till 17th May 7:00 AM UTC at which point we restarted the application. 

Please let me know if you need anything else. 


Thanks,
Karthik

**Comment by larshesel** [comment]
I'll try to take a look at he logs when I have time, in the meantime, could you verify it's not an issue with the ephemeral port-range?

**Comment by larshesel** [comment]
Looking at the error logs it looks like there's some issue with the configured endpoints - I think something like this could occur back then if the endpoint config file was changed while Verne was running.

Besides that it also looks like the endpoints are returning 429 error codes - which might also explain why clients can't connect? 

In any case - since 0.15.3 a lot of things happened and all the webhook config got moved into the main VerneMQ config file, so maybe you're also running into some issue that's already been fixed - so I'd recommend that you upgrade to the latest version 1.0.1.

**Comment by odx-tech** [comment]
I don't think its the case, atleast do not have evidence that the webhook end-point was having any issue. Even now we are experiencing the unresponsiveness. Webhook end-point is a simple API gateway end-point on AWS which is running a lambda. No errors reported on the metrics of those APIs.

**Comment by larshesel** [comment]
Well, it's a fact that your endpoint returned 429 - too many requests at some point, because it's in the logs.

What did the logs (error log) say just now when you experienced the problem again?

**Comment by odx-tech** [comment]
We went back and looked at logs of other applications using the same webhook API gateway to understand during the same time have we seen any 429s. So we did see 429 from the same API gateway during the same time. What was alarming is that cloudwatch metrics on AWS did not reflect them at all. We'll follow up with AWS on monitoring as well as increase the limits if needed. 

That said, the 429s were momentary for a few seconds as confirmed in another application. As calls later succeeded to the same end-points. What we saw in vernemq was that the calls did not get initiated and were stuck in connect/publish. Only during re-start and adding the webhooks later-on fixed the problem. Any reason for that .?

**Comment by larshesel** [comment]
It's hard to say - the logs you sent earlier were full of other webhook errors which as I mentioned looked like some inconsistencies in the webhooks internal configuration state. That may be related to the errors you see - I have no idea.

What is in the logs now (after vernemq was restarted) and you're seeing the stuck connections?

**Comment by odx-tech** [comment]
Now there are no stuck connections.

**Comment by larshesel** [comment]
Ok - I guess we can close this then.
