### ISSUE TITLE
Custom plugin loading with ENIF library

### ISSUE THREAD

**Issue by oakad** [erlio/vernemq#388]
When attempting to load a plugin which depends on native ENIF library, the error partially quoted below is reported. It appears, that the vmq loader is not happy about the native library, namely:

"Reload not supported by this NIF library."

This is indeed the case, as neither "reload" nor "upgrade" NIF_INIT callbacks are implemented (passed in as NULL).

We can not trigger the error with manual testing (application:load, start, ensure_all_started - only the expected already_loaded error is reported). So, the question is, what exactly vmq does when plugin is being enabled?

Erlang docs say that "reload" callback for NIFs should be omitted for all new code and we don't expect live "upgrade"s either.

The actual loading function where error originates:
```erlang
load_native() -> case code:priv_dir(vmq_cb_exos) of
	{error, bad_name} ->
		error_logger:error_msg("native driver not present"),
		{error, bad_name};
	Dir -> ok = erlang:load_nif(
		filename:join(Dir, ?CbNativeImpl), {}
	)
end.
```

{'EXIT',
{{badmatch,
{error,
{reload,
"Reload not supported by this NIF library."}}},
[{vmq_cb_exos_app,
load_native,
0,
[{file,
"/home/ec2-user/vmq_cb_exos/_build/default/lib/vmq_cb_exos/src/vmq_cb_exos_app.erl"},
{line,
27}]},
{vmq_cb_exos_app,
start,
2,
[{file,
"/home/ec2-user/vmq_cb_exos/_build/default/lib/vmq_cb_exos/src/vmq_cb_exos_app.erl"},
{line,
16}]},
{application_master,
start_it_old,
4,
[{file,
"application_master.erl"},
{line,
273}]}]}}}}}}},
[{vmq_plugin_mgr,
start_plugin,
1,

**Comment by larshesel** [comment]
When a plugin (application) is being reloaded the modules defined for that application are first purged and then loaded again. Otherwise changes to the module files would not be picked up (which is very annoying when developing a plugin.

**Comment by oakad** [comment]
If I manually do application:stop, unload, then code:delete,purge the nif library gets unloaded (unload callback is invoked). Then if I do application:start again, nif library gets loaded just fine (load callback is invoked).

Yet, when I try to enable that same thing as a plugin, the "Reload not supported by this NIF library." error pops up (even though I now implemented both reload and upgrade callbacks).

**Comment by oakad** [comment]
The issue had yet again magically resolved itself. Sorry for the noise.
