### ISSUE TITLE
Error Messages

### ISSUE THREAD

**Issue by gmonk** [erlio/vernemq#394]
### Environment

- VerneMQ Version: 1.0.1
- OS: ubuntu 16.04 1G RAM  2Core 
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.

### Actual behaviour
With only 2 publishers and a max of four subscribers I get  several log messages with the following.

handle_event:90 monitor busy_port <0.739.0> [{initial_call,{vmq_ranch,init,5}},{almost_current_function,{erts_internal,port_command,3}},{message_queue_len,0}] #Port<0.9513>

session stopped abnormally due to '{send_failed,{error,timeout}}'

the message  stream is frequent each publisher has about 200 devices each publishing to all four subs at once per second.  Im wondering if Vernemq can handle this.

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
So that are 2 * 200 * 4 = 1600 msg/s published?
How big are your messages?

**Comment by gmonk** [comment]
That is correct.  The max payload is 200 bytes

**Comment by ioolkos** [comment]
Well, busy_port events indicate back pressure from the VM for sending to sockets.
I still think you should be able to do 1.6k msg/s even on low spec (1G Ram, 2 cores).
Other things might be relevant: Operating system config, and what kind of test you are actually doing?

Can you give details on your testing approach?

**Comment by gmonk** [comment]
I am currently experimenting with sending traffic signal data to third parties for connected vehicles.  We capture our traffic signal data direct from our polling servers and then publish it to the VPS for the data to be consumed.  So currently there are a little over 400 signals being polled 1 per second. And right now there is only one continous subscriber  in the furture 4 max.   I never see the cpu or ram every really spike. I have tried to tweak some of the buffers 
net.core.rmem_default = 10000000
net.core.wmem_default = 10000000
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

but this does not seem to make a difference  could it simply be  a bad confiuration ? our testing is mainly concerned with latency and not persistence so we are not using Qos 1 or 2   also using clean session flag set to true on the client

**Comment by ioolkos** [comment]
It's hard to tell what's going on overall, especially if TCP configs could play a role. 
"changing stuff" is a way to find out, I guess. (trying on bigger hardware, trying different delivery scenarios).

Also: how do you consume the messages specifically? (what MQTT client?)

**Comment by larshesel** [comment]
Closing this for now as there's not a lot more to be said without more information. As already hinted this is probable a case of hardware that can't keep up with the messages being pushed to the TCP socket layer (hence the busy_port messages). Try bigger hardware or lower the rates and see if the messages go away.
