### ISSUE TITLE
vmq_passwd rejects connects without username/password

### ISSUE THREAD

**Issue by baranga** [erlio/vernemq#396]
### Environment
- VerneMQ Version: 1.0.1
- OS: Debian (jessie)

### Expected behavior
I use a combination of `vmq_passwd` and `vmq_webhooks` to authenticate connections. My system/backend connections get established via username/password and `vmq.passwd` configuration. My clients will be authenticated by client id over webhooks.

I expect `vmq_passwd` to forward to next `auth_on_register` hook in case username/password is absent. In case no `auth_on_register` hook signaled accept and `allow_anonymous = off` the connection should be rejected.

### Actual behaviour
Right now `vmq_passwd` rejects a connection in case username/password is empty. If I set `allow_anonymous = on` all hooks fall through and connection is accepted.

**Comment by ioolkos** [comment]
that's what this ['next'](https://github.com/erlio/vernemq/blob/master/apps/vmq_passwd/src/vmq_passwd.erl#L113) is for, isn't it, @larshesel/@dergraf?
so the idea is that it should work the way @baranga proposes?

**Comment by baranga** [comment]
I can provide a PR as this is a pretty small change. But I'm not sure this brakes something else.

**Comment by ioolkos** [comment]
If you have something ready, please do PR. We'll check it doesn't wreck havoc :)

Maybe the original idea was to keep vmq-passwd completely outside the auth hook chain, as an utility. Discussion needed.

**Comment by ioolkos** [comment]
Note: If vmq_passwd isn't able to find a matching user, it should return next and leave it to the next plugin. However if it finds a matching user, but can't verify the password it has to return some error, to stop evaluating the chain
