### ISSUE TITLE
Publishing messages from authentication plugins - is it possible?

### ISSUE THREAD

**Issue by oakad** [erlio/vernemq#399]
In my custom authentication plugin I would like to publish a custom message to a predefined topic when new client is authenticated (successfully or not) - preferably, the message should be published from `auth_on_register` call back, but a dedicated erlang process will also do. Is it possible to achieve in vmq? If yes, where shall I look for the appropriate API?

**Comment by ioolkos** [comment]
I guess you don't mean over MQTT, but like a privileged internal delivery to a certain topic?
@larshesel I think this is currently not possible, or at least there is no internal interface that plugins could use to publish messages?

**Comment by codeadict** [comment]
you can absolutely use the internal publish function. like:

```erlang
{ok, {M, F, A}} = application:get_env(yourplugin, registry_mfa),
{RegisterFun, PublishFun, SubscribeFun} = apply(M, F, A),
```
and in yourplugin.app.src use the registry mfa as an application environment like:
```erlang
{env [
    {registry_mfa, {vmq_reg, direct_plugin_exports, [yourplugin]}},
]}
```

Then you can use `PublishFun` to publish data: `PublishFun(Topic, Payload, #{qos => QoS, retain => IsRetain}).`

This API is subject to changes in the future.

**Comment by ioolkos** [comment]
awesome, the things I learn here ;)
thanks for the reminder @codeadict!

**Comment by oakad** [comment]
This is most useful.
Thanks a lot.

**Comment by leopucci** [comment]
Is there a way to use this on lua? Any hints on a publish function inside lua?

Thanks

**Comment by dergraf** [comment]
this isn't currently possible

**Comment by leopucci** [comment]
Thanks @dergraf , i could not publish via lua, but i can change a publication on lua via auth_on_publish, so i am being able to save on mysql then changing the content and publishing back to client the response... 
It is ugly but it works 👍

**Comment by kourosko** [comment]
> you can absolutely use the internal publish function. like:
> 
> ```erlang
> {ok, {M, F, A}} = application:get_env(yourplugin, registry_mfa),
> {RegisterFun, PublishFun, SubscribeFun} = apply(M, F, A),
> ```
> 
> and in yourplugin.app.src use the registry mfa as an application environment like:
> 
> ```erlang
> {env [
>     {registry_mfa, {vmq_reg, direct_plugin_exports, [yourplugin]}},
> ]}
> ```
> 
> Then you can use `PublishFun` to publish data: `PublishFun(Topic, Payload, #{qos => QoS, retain => IsRetain}).`
> 
> This API is subject to changes in the future.

I can't get it working. Maybe i do something wrong because i don't know erlang.
Can you help me?
I have this in .src
`  {env,[ 
{registry_mfa, {vmq_reg, direct_plugin_exports, [vmq_clienttopics]}},
       {vmq_plugin_hooks, [
            {vmq_clienttopics, on_register,3,[internal]},
            {vmq_clienttopics, on_client_wakeup,1,[internal]},
            {vmq_clienttopics, on_client_offline,1,[internal]},
            {vmq_clienttopics, on_client_gone,1,[internal]}
        ]}
  ]}`
and in erl i have
`publish_client_status(SubscriberId, Status) ->
    {ok, {M, F, A}} = application:get_env(vmq_clienttopics,
					  registry_mfa),
    {RegisterFun, PublishFun,
     {SubscribeFun, UnsubscribeFun}} =
	apply(M, F, A),
    true = is_function(PublishFun, 3),
    PublishFun(subscriber_id(SubscriberId),
	       subscriber_id(SubscriberId),
	       #{qos => 1, retain => false}),
    ok.
`

**Comment by larshesel** [comment]
Hi, the topic of the publish fun has to be a list of binaries (the type is `[binary()]`). So if the `subscriber_id/1` function returns the client id which is usually a binary, you could publish like this: `PublishFun([subscriber_id(SubscriberId)], subscriber_id(SubscriberId), #{qos => 1, retain => false})`. A better name for `subscriber_id/1` would probably be `client_id/1`. 

So if you want to publish to `a/b/c` then the topic passed to the publish function need to look like this: `[<<a>>, <<b>>, <<c>>]`. Hope this helps.

**Comment by kourosko** [comment]
Thanks that was my error...

**Comment by pewh** [comment]
Hello, I've tried to `subscribe` using function above, but `auth_on_subscribe` is not triggered.
Anyone know how to trigger this?

there's no issue in my `auth_on_subscribe` since it's work if using tool like mqtt-cli
