### ISSUE TITLE
VerneMQ with TLS 1.2 sends Encrypted Alert 21 then disconnects

### ISSUE THREAD

**Issue by enricodetoma** [erlio/vernemq#400]
### Environment

- VerneMQ Version: vernemq_1.0.1-1_amd64.deb
- OS: Ubuntu 16.04 64 bit
- Erlang/OTP version (if building from source): Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]
- Client: Python PAHO MQTT on Windows 10 64 bit

### Expected behavior

- I'm developing a test application with Python PAHO MQTT client, which connects with VerneMQ server, port 8883 using TLS1.2.
I created a certificate authority and issued a server certificate, which I installed in this way:
```
listener.ssl.cafile = /etc/ssl/certs/mqtt_ca.crt
listener.ssl.certfile = /etc/ssl/certs/mqtt.crt
listener.ssl.keyfile = /etc/vernemq/mqtt.key
```
On the client side, I'm setting the CA certificate in PAHO MQTT client like this:
```
self.client.tls_set(ca_certs="mqtt_ca.crt", tls_version=ssl.PROTOCOL_TLSv1_2)
```
I expect that the connection should be made, then be able to publish.

### Actual behaviour

- The connection sometimes is made, and I can publish.
But quite often VerneMQ sends me an "Encrypted alert 21", then disconnects the client. Please see the Wireshark trace below:

![encrypted_alert_21](https://cloud.githubusercontent.com/assets/464156/26485500/9ffb7306-41f7-11e7-96f3-d5584577bf7e.png)

If I restart VerneMQ service, it may work for some time, then start sending Encrypted Alerts again.

In VerneMQ log, I only find records like this:

`2017-05-26 09:20:28.950 [error] <0.5506.0>@vmq_mqtt_fsm:auth_on_publish:659 can't auth publish [<<"test-user">>,{[],<<"test-client">>},1,[<<"box">>,<<"test-client">>,<<"log">>],<<"test message">>,false] due to error
`

**Comment by enricodetoma** [comment]
Never mind, I mistakenly had two separate instances of the same client trying to connect. When I stopped the second instance, the server didn't send Encrypted Alert 21 any more

**Comment by ioolkos** [comment]
Good to hear, thanks for letting us know & thanks for using VerneMQ :)
