### ISSUE TITLE
Misunderstanding: `message_size_limit` and `max_message_size`

### ISSUE THREAD

**Issue by dergraf** [erlio/vernemq#402]
Keep: `max_message_size` to limit TCP parser buffer
New: `max_payload_size` to limit the MQTT payload size,

Alias: `message_size_limit => max_payload_size`

Deprecate `message_size_limit` in 1.1.0

**Comment by larshesel** [comment]
Looking closer at the code I don't see we have anything else than the max size passed to the `vmq_parser:parse/2` function which will implicitly limit the payload size. I don't see that we have anything limiting a TCP parser buffer.

I would therefore just keep `max_message_size` (which will then be the only one passed to `vmq_parser:parse/2`) and deprecate `message_size_limit`.

Maybe I'm missing something ;)

**Comment by dergraf** [comment]
Yes, you're right! We should keep `max_message_size`.
