### ISSUE TITLE
Updated VerneMQ not working during auth_on_register

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#407]
### Environment

- VerneMQ Version: 1.0.1 (Trusty Ubuntu)
- OS: Ubuntu
- Erlang/OTP version (if building from source):

### Expected behavior

We are trying to upgrade vernemq from 0.15.3 to 1.0.1. We've kept everything same, uninstalled the previous version and installed the newer. We later configured the webhooks just like earlier using the plugin. And then we tried to connect to the broker. Our webhook API was working fine, returning 200 OK. But in the logs we are seeing the following error: 
vmq_mqtt_fsm:check_user:545 can't authenticate client {[],<<"mqttjs_102557871497010013671">>} due to error
and the client is not able to connect. 

When we rolled back to 0.15.3 version everything is working fine. Please let us know if I am missing anything in setup when moving to the newer version. 

Thanks,
Karthik

**Comment by larshesel** [comment]
See the changelog for the details on what changed since 0.15.3 and 1.0.1: https://github.com/erlio/vernemq/blob/master/changelog.md

What is probably the most relevant thing which is likely affecting you is that the webhooks plugin is now shipped **as part of VerneMQ** and all configuration of the webhooks must be done in the `vernemq.conf` file.

The above information is not enough to say anything much more concrete I'm afraid. Please have a thorough look at the changelog and make sure you have taken all the changes into account. Let us know if you still have issues.

**Comment by odx-tech** [comment]
Hi @larshesel,

I've updated the Erlang OTP version, ensured webhooks are configured via the conf file itself. Updated ubuntu version as well, still the error persists. Switched off plugins.vmq_passwd and plugins.vmq_acl as well. Not sure what I am missing in here. The API is returning the expected response. 


Thanks,
Karthik

**Comment by odx-tech** [comment]
Hi @larshesel,

We were able to upgrade to 1.0.0 without any problem. Post which we are seeing this error. 

Looking at the change-log we suspect, it is got to do with #332 

Thanks,
Karthik

**Comment by larshesel** [comment]
What exactly are you sending back in your webhook?

**Comment by odx-tech** [comment]
Here is the response of the web-hook:

{'result': 'ok', 'modifiers': {
                        'mountpoint': '',
                        'client_id': client_id,
                        'reg_view': '',
                        'clean_session': False,
                        'max_message_size': 65535,
                        'max_message_rate': 10000,
                        'max_inflight_messages': 100,
                        'retry_interval': 100,
                        'upgrade_qos': False
                        }}

**Comment by larshesel** [comment]
See my comment here: https://github.com/erlio/vernemq/issues/409#issuecomment-307897195

**Comment by odx-tech** [comment]
Hi @larshesel,

I was able to successfully authenticate the user by not sending any modifiers in auth_on_register call. One another question I have is I have web-hooks configured for auth_on_register and on_publish. And when my client is trying to publish the data, vernemq is throwing an error saying no hook found for auth_on_publish. I don't auth on this, so how we do we bypass this check ? 


Thanks,
Karthik

**Comment by tpuza** [comment]
Hello, I have very similar experience like @odx-tech, but upgrading from 1.0.0 to 1.0.1.
We run VerneMQ at Docker, using official erlio/docker-vernemq image.

I've used used `vmq-admin trace client client-id=xxx` recomended by @larshesel with following result.

**Version 1.0.0 (OK)**
```
root@e97169fb59a0:/# vmq-admin trace client client-id=3GwEXQIgPgkXtXh7XFOdRG
No sessions found for client "3GwEXQIgPgkXtXh7XFOdRG"
New session with PID <7244.510.0> found for client "3GwEXQIgPgkXtXh7XFOdRG"
<7244.510.0> MQTT RECV: CID: "3GwEXQIgPgkXtXh7XFOdRG" CONNECT(clientid: 3GwEXQIgPgkXtXh7XFOdRG ver: 4, user: 3GwEXQIgPgkXtXh7XFOdRG, pass: nWUwFGPifv57i1hGr8LVOFoXmxjW
yU68DnHj, cs: 1, ka: 60)
<7244.510.0> Calling auth_on_register({{172,18,0,1},34272},{[],
                                                            <<"3GwEXQIgPgkXtXh7XFOdRG">>},3GwEXQIgPgkXtXh7XFOdRG,nWUwFGPifv57i1hGr8LVOFoXmxjWyU68DnHj,true)
<7244.510.0> Hook returned "ok" with modifiers:
    {client_id,<<"3GwEXQIgPgkXtXh7XFOdRG">>}
<7244.510.0> MQTT SEND: CID: "3GwEXQIgPgkXtXh7XFOdRG" CONNACK(sp: 0, rc: 0)
```

**Version 1.0.1 (Error)**
```
root@24e28dd3e8cc:/# vmq-admin trace client client-id=3GwEXQIgPgkXtXh7XFOdRG
No sessions found for client "3GwEXQIgPgkXtXh7XFOdRG"
New session with PID <7244.591.0> found for client "3GwEXQIgPgkXtXh7XFOdRG"
<7244.591.0> MQTT RECV: CID: "3GwEXQIgPgkXtXh7XFOdRG" CONNECT(clientid: 3GwEXQIgPgkXtXh7XFOdRG ver: 4, user: 3GwEXQIgPgkXtXh7XFOdRG, pass: nWUwFGPifv57i1hGr8LVOFoXmxjW
yU68DnHj, cs: 1, ka: 60)
<7244.591.0> Calling auth_on_register({{172,18,0,1},34150},{[],
                                                            <<"3GwEXQIgPgkXtXh7XFOdRG">>},3GwEXQIgPgkXtXh7XFOdRG,nWUwFGPifv57i1hGr8LVOFoXmxjWyU68DnHj,true)
<7244.591.0> Trace session for 3GwEXQIgPgkXtXh7XFOdRG stopped
New session with PID <7244.592.0> found for client "3GwEXQIgPgkXtXh7XFOdRG"
<7244.592.0> MQTT RECV: CID: "3GwEXQIgPgkXtXh7XFOdRG" CONNECT(clientid: 3GwEXQIgPgkXtXh7XFOdRG ver: 3, user: 3GwEXQIgPgkXtXh7XFOdRG, pass: nWUwFGPifv57i1hGr8LVOFoXmxjW
yU68DnHj, cs: 1, ka: 60)
<7244.592.0> Calling auth_on_register({{172,18,0,1},34156},{[],
                                                            <<"3GwEXQIgPgkXtXh7XFOdRG">>},3GwEXQIgPgkXtXh7XFOdRG,nWUwFGPifv57i1hGr8LVOFoXmxjWyU68DnHj,true)
<7244.592.0> Hook returned {error,error}
<7244.592.0> MQTT SEND: CID: "3GwEXQIgPgkXtXh7XFOdRG" CONNACK(sp: 0, rc: 5)
<7244.592.0> Trace session for 3GwEXQIgPgkXtXh7XFOdRG stopped
```

**Comment by ioolkos** [comment]
Thanks @odx-tech and @tpuza for reporting.

I guess we now have multiple reports for similar problematic behaviour. (updating, then problem with auth_on_register). 
We'll have to look into the changes between 1.0.0. and 1.0.1 as it must be there somewhere. It still could be
misconfiguration rather than a bug, but at this point that's open.

**Comment by dergraf** [comment]
@odx-tech you need a plugin that handles the authorization part. Auth_on_register only deals with authentication. If you only want to authenticate the user and allow all topics for publish/subscribe you can enable vmq_acl with the default rule again.

@ioolkos the issues aren't related OP wanted to upgrade from 0.15.3 to 1.0.1 which introduced breaking changes e.g. regarding configuration and the fact that vmq_webhooks is bundled .

@tpuza can you open a separate issue and describe your complete setup, e.g. which plugins you're using. I think your issue isn't related to the one reported by the OP.

**Comment by odx-tech** [comment]
Been able to successfully publish. Thanks @dergraf  and @larshesel for the support. Closing

**Comment by thanh3d** [comment]
I got the same issue: 

8962.7166.0> Hook returned {error,<<"not_allowed">>}
<8962.7166.0> Trace session for lens_xqQfzLFSd412vRsscPgBf61O8Ja stopped
New session with PID <8962.7167.0> found for client "lens_xqQfzLFSd412vRsscPgBf61O8Ja"
<8962.7167.0> MQTT RECV: CID: "lens_xqQfzLFSd412vRsscPgBf61O8Ja" CONNECT(c: lens_xqQfzLFSd412vRsscPgBf61O8Ja, v: 3, u: undefined, p: undefined, cs: 1, ka: 120)
<8962.7167.0> Calling auth_on_register({{10,0,1,72},64686},{[],
                                                            <<"lens_xqQfzLFSd412vRsscPgBf61O8Ja">>},undefined,undefined,true)
