### ISSUE TITLE
Need help in debugging errors

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#408]
### Environment

- VerneMQ Version: 0.15.3
- OS: ubuntu 16.04
- Erlang/OTP version (if building from source):

### Errors Seen in Logs

We are seeing the following errors in our logs frequently. Wanted help in understading them as well as diagnosing as well:

1)  Error related to webhooks:
CRASH REPORT Process <0.12199.38> with 0 neighbours crashed with reason: no case clause matching undefined in vmq_webhooks_plugin:handle_response/3 line 495
Webhooks are properly registered and configured. Yet we see these errors, not sure how to proceed. 

2) Error related to some listener:
error] <0.11566.38> Ranch listener {{0,0,0,0},1883} terminated with reason: {case_clause,undefined}
Not sure what the cause of this is 

3) Errors because of message-max-size:
<0.30527.43>@vmq_ranch:teardown:125 [<0.30527.43>] session stopped abnormally due to 'packet_exceeds_max_size'

Want to understand why this could be coming in and which parameter in the config controls this. 

Please let me know if you need anything in here to help debug these issues. 

Thanks,
Karthik

**Comment by larshesel** [comment]
Hi - I saw #407 where you tried to update to 1.0.1 - I believe upgrading to 1.0.1 is the right way to go as lots of bugs were fixed since 0.15.3.

**Comment by odx-tech** [comment]
Hi @larshesel,

We were able to solve the errors 1) and 2). It was an issue with the webhooks response. Could you please let us know on the third wrt message-size ? As to which parameters control it. 


Thanks,
Karthik

**Comment by larshesel** [comment]
Are you overriding the `max_message_size` in the webhooks? or is `message_size_limit` or `max_message_size` set in the `vernemq.conf` file?

**Comment by odx-tech** [comment]
Looks like I am setting it during the client auth in webhooks. Does this then override the size for that client ?

**Comment by larshesel** [comment]
Yes, that's the idea - in general you should only override the things you explicitly want to override. Removing everything you don't explicitly need is a good starting point. Also make sure you know what each override means before using it.

**Comment by geri777** [comment]
@odx-tech, could you please tell us how you fixed problem 1 - I have the same issue. Many thanks.

**Comment by salgadobreno** [comment]
@geri777 Ended up here too, following the clue about webhook response, I re-checked documentation and it said response should be {"result": "next"} for on_deliver(in my case), seems it could be part of the solution.
