### ISSUE TITLE
vmq_mqtt_fsm:check_user:545 can't authenticate client due to error

### ISSUE THREAD

**Issue by shail151192** [erlio/vernemq#409]
### Environment

- VerneMQ Version: 1.0.1
- OS: Ubuntu
- Erlang/OTP version (if building from source):

- I have registered a webhook='auth_on_register' for client validation. If client successfully validated returning following 
  {'result': 'ok', 'modifiers': {
                    'mountpoint': '',
                    'client_id': client_id,
                    'reg_view': '',
                    'clean_session': False,
                    'max_message_size': 65535,
                    'max_message_rate': 10000,
                    'max_inflight_messages': 100,
                    'retry_interval': 100,
                    'upgrade_qos': False
                    }}
       And logs throwing following error..
      2017-06-11 08:40:18.004 [warning] <0.2157.0>@vmq_mqtt_fsm:check_user:545 can't authenticate client {[],<<"karthitest11_MTS_Test">>} due to error

- Please help me if I am missing something in the configuration.
Thanks.
Shailendra

**Comment by larshesel** [comment]
Maybe you've run into some kind of bug - but it also looks like you've cut-n-pasted an example response which likely contains a lot of stuff you don't need to change. For instance, changing the mountpoint and client_id is not something you usually need - so to debug this I'd first try to remove **all** the modifiers you don't explicitly need.

Further, to try to debug these things in general it's helpful with 1) doing a dump of the HTTP request sent from VerneMQ to the webhooks to see what is actually being sent and received 2) doing a trace of the client-id connecting, using the trace above it would look like `vmq-admin trace client client-id=karthitest11_MTS_Test`.

I hope this helps.
