### ISSUE TITLE
VerneMQ stopped running

### ISSUE THREAD

**Issue by siscia** [erlio/vernemq#410]
### Environment

- VerneMQ Version: vernemq_1.0.1-1_amd64
- OS: ubuntu 16.04 EC2

A single instance running on a EC2 host

### Expected behavior

VerneMQ should keep running

### Actual behaviour

I experienced a bad downtime caused by vernemq

I looked through some log and what I find out is this:

```
===== ALIVE Sat Jun 10 14:10:25 UTC 2017

===== ALIVE Sat Jun 10 14:25:25 UTC 2017

===== ALIVE Sat Jun 10 14:40:25 UTC 2017
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed
```

Didn't find anything else interesting on the log but I may be wrong.

```
/var/log/vernemq$ ll
total 200
drwxr-xr-x  2 vernemq vernemq  4096 Jun 13 00:04 ./
drwxrwxr-x 13 root    syslog   4096 Jun 13 06:25 ../
-rw-rw-r--  1 vernemq vernemq 15576 Jun 13 09:34 console.log
-rw-r--r--  1 vernemq vernemq 19984 Jun 12 23:54 console.log.0
-rw-r--r--  1 vernemq vernemq  4558 Jun  9 08:43 console.log.1
-rw-r--r--  1 vernemq vernemq  1744 Jun  8 17:28 console.log.2
-rw-r--r--  1 vernemq vernemq   136 Jun  7 02:48 console.log.3
-rw-r--r--  1 vernemq vernemq   135 Jun  6 05:11 console.log.4
-rw-rw-r--  1 vernemq vernemq     0 Jun 12 17:50 crash.log.0
-rw-r--r--  1 vernemq vernemq     0 May 12 13:36 crash.log.4
-rw-r--r--  1 vernemq vernemq 99986 Jun  6 04:09 erlang.log.1
-rw-r--r--  1 vernemq vernemq 21607 Jun 13 09:35 erlang.log.2
-rw-rw-r--  1 vernemq vernemq     0 Jun 12 17:50 error.log.0
-rw-r--r--  1 vernemq vernemq     0 May 12 13:36 error.log.4
-rw-r--r--  1 vernemq vernemq   258 Jun 12 17:50 run_erl.log
```

**Comment by larshesel** [comment]
Hi - that looks strange. What was the load cpu/memory when this happened and is it something that is reproducable?

**Comment by siscia** [comment]
After further investigation, I believed that the system ran out of memory.

Which is quite strange because in the standard condition it uses roughly half of the memory available.

It is possible that the outage was caused by a simple oom ?

**Comment by larshesel** [comment]
It's possible. If it was the OOM killer that picked VerneMQ as it's target you might have something in the system logs. What are the very last logs in the `console.log` file?

**Comment by siscia** [comment]
It was a simple OOM kill.

Thanks.
