### ISSUE TITLE
Combination of allow_anonymous with vmq_passwd & vmq_acl doesn't work

### ISSUE THREAD

**Issue by webfrank** [erlio/vernemq#414]
### Environment

docker inspect vernemq
[
    {
        "Id": "ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a",
        "Created": "2017-05-23T08:02:25.980498175Z",
        "Path": "start_vernemq",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 7524,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-06-15T08:47:49.690652308Z",
            "FinishedAt": "2017-06-15T08:42:49.314505571Z"
        },
        "Image": "sha256:eb8631620adf5969dcf2ecc005990a7a56ea4788960de0c863b30f340f52a238",
        "ResolvConfPath": "/var/lib/docker/containers/ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a/hostname",
        "HostsPath": "/var/lib/docker/containers/ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a/hosts",
        "LogPath": "/var/lib/docker/containers/ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a/ac37087fd25f2c23f6ee78ec9062190d390b42ffaabab860b9aab3940979b33a-json.log",
        "Name": "/vernemq",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/vernemq:/etc/vernemq",
                "/var/log/vernemq:/var/log/vernemq"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "1883/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "1883"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/vernemq",
                "Destination": "/etc/vernemq",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/var/log/vernemq",
                "Destination": "/var/log/vernemq",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "2eceb238b148e05c0e0258ed2eba9a3a81078dd0f282783ae1886bd5f4e59b7a",
                "Source": "/var/lib/docker/volumes/2eceb238b148e05c0e0258ed2eba9a3a81078dd0f282783ae1886bd5f4e59b7a/_data",
                "Destination": "/var/lib/vernemq",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "ac37087fd25f",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1883/tcp": {},
                "4369/tcp": {},
                "44053/tcp": {},
                "8080/tcp": {},
                "8883/tcp": {},
                "8888/tcp": {},
                "9100/tcp": {},
                "9101/tcp": {},
                "9102/tcp": {},
                "9103/tcp": {},
                "9104/tcp": {},
                "9105/tcp": {},
                "9106/tcp": {},
                "9107/tcp": {},
                "9108/tcp": {},
                "9109/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "VERNEMQ_VERSION=1.0.1"
            ],
            "Cmd": [
                "start_vernemq"
            ],
            "ArgsEscaped": true,
            "Image": "erlio/docker-vernemq",
            "Volumes": {
                "/etc/vernemq": {},
                "/var/lib/vernemq": {},
                "/var/log/vernemq": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f97f6c5f27d4a919b1b6933a3d89e186ae3b297eb0b47270316eee66268fd482",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1883/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "1883"
                    }
                ],
                "4369/tcp": null,
                "44053/tcp": null,
                "8080/tcp": null,
                "8883/tcp": null,
                "8888/tcp": null,
                "9100/tcp": null,
                "9101/tcp": null,
                "9102/tcp": null,
                "9103/tcp": null,
                "9104/tcp": null,
                "9105/tcp": null,
                "9106/tcp": null,
                "9107/tcp": null,
                "9108/tcp": null,
                "9109/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/f97f6c5f27d4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "c735070bf689b07f3d31ff7a26aff2f3e3801789566663fddcca4281a59ba813",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f253dbf17f2a695be4b9be0d246181e622fe382a74c046f102a0e8d93ad5fdff",
                    "EndpointID": "c735070bf689b07f3d31ff7a26aff2f3e3801789566663fddcca4281a59ba813",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

### Expected behavior

With anonymous login enabled if a client is using credentials should be checked and if not verified acl should not match

### Actual behaviour

If client provides only username (so is anonymous with username) an acl matching a username is verified but it should not as the user didn't provide correct authorization.

**Comment by dergraf** [comment]
Hello @webfrank, thanks for reporting.
That's not how it works in VerneMQ today.
`allow_anonymous = on` bypasses the authentication hook/plugins (default vmq_passwd), the authorization step is handled by other plugins and is NOT bypassed (however, vmq_acl uses an authorize-everything default rule)
Hope this helps.

**Comment by webfrank** [comment]
Hi,

     I think I didn't understand well. What I would like to achive is to 
have anonymous clients to publish only on one topic but authenticated 
users could subscribe and/or publish on everythings.

I have setup vmq.acl like this:

----

topic VIEWBUTTON/#

user admin
topic #

----

and vernemq.conf:

----

allow_anonymous = on

vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_acl.acl_file = /etc/vernemq/vmq.acl

----

admin has a password of course. If I login with admin/password I could 
subscribe/publish everything, if I do not login at all I could only work 
on VIEWBUTTON/# topics but if I login with admin/- (without password but 
admin user specified) I could login and subscribe/publish every topic. I 
would expect to fail login (no matching password) or at least to not be 
able to subscribe/publish any topic but only the anonymous one VIEWBUTTON/#.


Il 15/06/17 14:05, Andre Graf ha scritto:

**Comment by dergraf** [comment]
Now I do understand. But I am afraid that this isn't possible with the built in `vmq_passwd` and `vmq_acl`.
But I guess a simple Lua script like the following could handle this case (no guarantee that this actually work).
More details about our Lua support is available here https://vernemq.com/docs/plugindevelopment/luaplugins.html.
```lua
function auth_on_register(reg)
    if reg.username == "admin" then
        if reg.password == "mysecret" then
            return true
        else
           log.warning("can't authenticate admin user")
           return false
        end
    else
        -- alllow anonymous
        return true
    end
end

function validate_topic(req)
    if req.username == "admin" then
        return true
    else
        if string.len(req.topic) > 10 and string.sub(req.topic, 1, 10) == "VIEWBUTTON" then
            return true
        else
            return false
        end
    end
end

hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = validate_topic,
    auth_on_subscribe = validate_topic,
}
```

**Comment by larshesel** [comment]
Think this is answered and can be closed.
