### ISSUE TITLE
MySQL auth failed.

### ISSUE THREAD

**Issue by dungxl** [erlio/vernemq#416]
### Environment

- VerneMQ Version: vernemq-1.0.1-1.el7.centos.x86_64.rpm
- OS: CentOS 7.2
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

crash.log
2017-06-17 15:22:27 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_diversity_sup}
     Context:    shutdown_error
     Reason:     killed
     Offender:   [{pid,<0.338.0>},{id,vmq_diversity_plugin},{mfargs,{vmq_diversity_plugin,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

error.log
2017-06-17 15:22:27.627 [error] <0.337.0> Supervisor vmq_diversity_sup had child vmq_diversity_plugin started with vmq_diversity_plugin:start_link() at <0.338.0> exit with reason killed in context shutdown_error

**Comment by larshesel** [comment]
Thanks for reporting.

could you add some more information about what you experience? When does this happen?  What impact does this have? Some context would be very helpful in understanding what is going on here.

**Comment by dungxl** [comment]
very strange. I test it works fine on another CentOS 7, and always failed on this one. The difference is that this one has less memory, only has 2G memory. will it cause the failure?

**Comment by dungxl** [comment]
2017-06-17 21:34:25.332 [warning] <0.403.0>@vmq_mqtt_fsm:check_user:545 can't authenticate client {[],<<"testuser">>} due to chain_exhausted

**Comment by dungxl** [comment]
sorry. I think it is caused by wrong configuration. but the error log doesn't show it.  now it works. thanks.
