### ISSUE TITLE
VermeMQ 1.0.1 - vmq_graphite due to plugin_not_found

### ISSUE THREAD

**Issue by mukesh-sangtani** [erlio/vernemq#417]
### Environment
- VerneMQ Version: 1.0.1
- OS: Ubuntu 14.0.4 (Trusty)
- Erlang/OTP version (if building from source): Installed from debian package
- Host: Hosted on AWS accessible through IP address - http://52.41.116.67/

1. I want to setup graphite plugin and following steps from this [link](https://vernemq.com/blog/2015/10/16/monitoring-vernemq-application-metrics.html).
2. I have completed Step 1 and 2 but stucked on step #3
3. My graphite configuration looks like this
graphite_enabled=on
graphite_host=52.41.116.67
graphite_port=2003
graphite_interval=20000

### Expected behavior
Error - Can't enable plugin: vmq_graphite due to plugin_not_found

### Actual behavior
It should enable graphite plugin from command.

**Comment by larshesel** [comment]
Hi - graphite is no longer distributed as a separate plugin but is built directly into VerneMQ. Just follow the documentation here: http://vernemq.com/docs/monitoring/graphite.html.

I'll update the blog post to mention this. Thanks for bringing it to our attention!
