### ISSUE TITLE
vmq_bridge not detecting loops

### ISSUE THREAD

**Issue by kellycampbell** [erlio/vernemq#419]
Does vmq_bridge try to do any loop detection?

I'm trying to bridge two clusters with the same topics, and the messages are looping.
I'm using `try_private = yes`

The setup is two clusters in two AWS availability zones in the same region. (ultimate goal is to have this in different regions), cluster A, cluster B.

We only need to bridge server-out messages, e.g. sending a command to an external device because the subscriber device could be connected to either cluster. 

Our bridge topic on both clusters is like:

```
vmq_bridge.tcp.br0.topic.1 = +/+/cmd/* out 1
```

Then I publish a message to cluster A: `x/y/cmd/12345` and both cluster A and B start looping sending that message to each other.

What I'd expect to see is just one message on each cluster. The B cluster should be able to tell that the message is from a bridge connection and that it matches a bridge topic, and then not send it over the B->A bridge.

VMQ version = 1.0.1

**Comment by dergraf** [comment]
Loop detection is currently not implemented.

Am 21.06.2017 6:39 nachm. schrieb "Kelly Campbell" <notifications@github.com

**Comment by kellycampbell** [comment]
Thank you for the quick response. We will work out a different solution.
