### ISSUE TITLE
vmq_systree dosen't publish any $SYS messages.

### ISSUE THREAD

**Issue by tidynine** [erlio/vernemq#42]
The setting of sys_interval in vernemq.conf is 10 by default.
Client subscribes '$SYS/clients/total' or other metric in vmq_systree, but got nothing.
Subscriptions of custom topics are working fine.

Broker's os is CentOS 6.7 64bit.

**Comment by dergraf** [comment]
Hi there,

you've to use '$SYS/<NodeName>/clients/total'

Cheers,
Andre
Am 29.08.2015 10:04 schrieb "tidynine" <notifications@github.com>:

**Comment by tidynine** [comment]
Hi dergraf,

Thank you, it's my fault. : )
