### ISSUE TITLE
Get VerneMQ running on Erlang/OTP 20

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#426]
To make VerneMQ run on Erlang/OTP 20 a few things need to be done.

- [x] cuttlefish (export_all warning): https://github.com/tsloughter/cuttlefish/pull/1
- [x] plumtree (gen_fsm deprecated warning) (`gen_statem` is not available in OTP 18)
- [x] vmq_plugin (smerl.erl `filename:find_src/2: deprecated; use filelib:find_source/3 instead`) (`filelib:find_source/3` is not in OTP 18)
- [x] vmq_server (vmq_queue.erl, gen_fsm deprecated warning)
- [x] vmq_diversity (export_all warning in vmq_diversity_utils)
- [x] cuttlefish `-smp disable` not supported on OTP 20
- [x] `crypto:rand_bytes` does not exist on OTP 20 (used in bcrypt)

**Comment by larshesel** [comment]
I've assigned this to 1.3.0 - I believe we'll have to drop Erlang 18 support unless we want to run through a bunch of hoops to keep it compatible and my thinking was we'd announce in 1.2.0 that it will be the last version with erlang 18 support.

**Comment by codeadict** [comment]
Whooha, i promise i'll work on this one :P, i think we can keep it compatible if needed, will be a bit more of work but not a big deal

**Comment by larshesel** [comment]
@codeadict I'm not sure it's worth the trouble to keep VerneMQ erlang 18 compatible - by far the most users won't know anything changed and those who do have only to change trivial things in their plugins. Do you have a feeling people would get very upset if we drop erlang 18?

**Comment by codeadict** [comment]
I don't think is a big deal at all, keeping the compatibility is doable, perhaps in a previous release make an announcement about 18 deprecation

**Comment by syberkitten** [comment]
Hey,

Have closely related issue, I'm unable to compile VerneMQ on Linux (Ubuntu 14.04LTS)
getting this error:
===> Compiling _build/default/lib/cuttlefish/src/cuttlefish_unit.erl failed
_build/default/lib/cuttlefish/src/cuttlefish_unit.erl:4: export_all flag enabled - all functions will be exported

I have Erlang 20 with OTP, already running on the server.

**Comment by ioolkos** [comment]
@syberkitten 
There's ongoing work in PR here for OTP 20 support: https://github.com/erlio/vernemq/pull/431
Although it probably does not the cuttlefish issue specifically.

Thanks for your report!

**Comment by codeadict** [comment]
correct, there is a PR to cuttlefish also but downgrading erlang to 19 will make it work

**Comment by syberkitten** [comment]
If Erlang 20 still does not work properly with VMQ
and Erlang 18 will be deprecated, it leaves only one slice 
of good version, that is 19.

Does it not leave the project in a very fragile state?
It's like saying i need Python 2.74, but python 2.75 will not work.

Well, in Python we have VirtualEnv which allows us to have
multiple versions of Python installed with their own dependencies.

Is there something similar for Erlang?

I cannot be installing and un-installing versions of Erlang all
the time, just to check different versions....

Please advise. :)

**Comment by ioolkos** [comment]
https://github.com/kerl/kerl is the usual way to test/use different OTP versions.

Nothing is decided here. If we support 19 and 20, then we think we can move forward and drop 18... :)

**Comment by larshesel** [comment]
Changes for this is in the #450 PR.

**Comment by larshesel** [comment]
Putting the patched version of plumtree into checkouts #450 can now compile and build a release, but starting the release fails:

```
$ _build/default/rel/vernemq/bin/vernemq console
Argument '-smp disable' not supported. Use "+S 1" instead.
Usage: erl [-version] [-sname NAME | -name NAME] [-noshell] [-noinput] [-env VAR VALUE] [-compile file ...] [-smp [auto|enable]] [-make] [-man [manopts] MANPAGE] [-x] [-emu_args] [-start_epmd BOOLEAN] [-args_file FILENAME] [+A THREADS] [+a SIZE] [+B[c|d|i]] [+c [BOOLEAN]] [+C MODE] [+h HEAP_SIZE_OPTION] [+K BOOLEAN] [+l] [+M<SUBSWITCH> <ARGUMENT>] [+P MAX_PROCS] [+Q MAX_PORTS] [+R COMPAT_REL] [+r] [+rg READER_GROUPS_LIMIT] [+s SCHEDULER_OPTION] [+S NO_SCHEDULERS:NO_SCHEDULERS_ONLINE] [+SP PERCENTAGE_SCHEDULERS:PERCENTAGE_SCHEDULERS_ONLINE] [+T LEVEL] [+V] [+v] [+W<i|w|e>] [+z MISC_OPTION] [args ...]
Error generating config with cuttlefish
  run `vernemq config generate -l debug` for more information.
```

**Comment by larshesel** [comment]
I could hack cuttlefish to work around that (but have to make sure this works on PRE20 version as well) and got the release up and running. Further I found we use `crypto:rand_bytes/1` in various places which does not exist on OTP 20 as well...

**Comment by larshesel** [comment]
Switch the bcrypt dependency for a newer version which is OTP20 compatible

**Comment by larshesel** [comment]
I've opened a PR for the `-smp disable` issue Kyorai/cuttlefish#2

**Comment by larshesel** [comment]
I moved this to the 1.1.1 milestone as it looks like we can keep erlang 18 compatibility after all.

**Comment by larshesel** [comment]
Plumtree changes were merged to master and we're using a custom patched version of cuttlefish which contains Kyorai/cuttlefish#2 until that fix has been merged.

**Comment by larshesel** [comment]
It now compiles and the release seems to be working :)  /cc @codeadict

**Comment by larshesel** [comment]
We merged #450 yesterday

**Comment by codeadict** [comment]
Niice

**Comment by larshesel** [comment]
Thanks for the help @codeadict  :)
