### ISSUE TITLE
Sequence message

### ISSUE THREAD

**Issue by berrywira** [erlio/vernemq#43]
Hi There,

why received message not in sequence order?

**Comment by dergraf** [comment]
Hi there,

can you be more specific? Are you talking about the offline messages? The current version of VerneMQ doesn't deliver them in the same order as they came in, as the standard doesn't requires the messages to be ordered.

**Comment by berrywira** [comment]
yes, that is what I mean, offline messages.
can you give alternative, how to deliver messages with ordered? or actually it's will cannot deliver with order?

**Comment by dergraf** [comment]
In our next release we will heavily improve the queuing mechanism, this might solve your problem. If it doesn't, you could still implement your own message store.

**Comment by berrywira** [comment]
Thanks, when you scheduling next releasse? 
I hope the improve, will be in next release. :D

**Comment by dergraf** [comment]
we hope to release something within the next weeks :)

**Comment by berrywira** [comment]
thank you very much :+1:

**Comment by berrywira** [comment]
Hi @dergraf 

I was test new vernemq with my usecase.
offline message queue isn't sequence. 

Step simple test :
One Server VerneMQ
Two Client, A and B.

The first client test pubsub from client A to client B. 
after that client B offline, where client A still send some message. and client B online again for see new message.

This is screenshot message not sequence :
 
<img width="905" alt="screen shot 2015-09-10 at 5 10 47 pm" src="https://cloud.githubusercontent.com/assets/9605173/9785755/c7ac2512-57de-11e5-8ac1-d24bf7f274e7.png">

**Comment by dergraf** [comment]
Hi there, thanks for reporting!

indeed, this is a bug.. will publish a fix very soon

**Comment by berrywira** [comment]
I will wait for fix sequence message. Thanks :+1:

**Comment by dergraf** [comment]
I've pushed a fix for this.. can you try the following in the vernemq root directory:
<code>./rebar3 upgrade vmq_server</code>
<code>make rel</code>

This should fetch the latest version of the vmq_server (containing the fix) and  generate a new VerneMQ release again.

**Comment by berrywira** [comment]
Thanks, I will test tomorrow and give feedback :+1:

**Comment by berrywira** [comment]
Hi @dergraf 
failed when upgrade vmq_server:
```
===> Locking of git dependency failed in /opt/app/vernemq/_build/default/lib/vmq_systree
```

**Comment by dergraf** [comment]
ok, was this from a fresh VerneMQ clone?

**Comment by berrywira** [comment]
yes, and now I'am try update vmq_server.

```
===> Only existing version of ezmq is 0.2.0 which does not match constraint ~> 0.3.1. Using anyway, but it is not guarenteed to work.
```

**Comment by dergraf** [comment]
what??? ezmq??

**Comment by berrywira** [comment]
I don't what the ezmq, but error when update vmq_server.

<img width="816" alt="screen shot 2015-09-16 at 2 28 36 pm" src="https://cloud.githubusercontent.com/assets/9605173/9898741/fbc251ce-5c7e-11e5-8cd2-88cb82208508.png">

**Comment by berrywira** [comment]
I'm sorry, I wrong command. 
you say "upgrade", but I run command "update".
But, fail upgarde vmq_server still same.

```
===> Locking of git dependency failed in /opt/app/vernemq/_build/default/lib/vmq_systree
```

**Comment by dergraf** [comment]
I did the following, which worked:
``git clone git://github.com/erlio/vernemq``
``cd vernemq``
``make rel``
``./rebar3 upgrade vmq_server``
``make rel``


just seen in your picture that you're using ``update`` instead of ``upgrade``. ``update`` updates the package index and this will print out the warning.

**Comment by dergraf** [comment]
@tsloughter , do you know what could causing the rebar3 upgrade error mentioned by @berrywira

**Comment by berrywira** [comment]
@dergraf actually I wrong again, I think run command upgrade vmq_server before make rel. but when you say,
```
make rel
```
./rebar3 upgrade vmq_server
```
make rel
```

I try that, and success. now I will test offline message. Thanks

**Comment by berrywira** [comment]
@dergraf 

It's work, offline and online message sequence, but how much VerneMQ can handle offline and message queue?

Maybe I found new bugs. it's bugs was on version 0.10.1 and now happen again.
The bugs :

1. VerneMQ compile on Instance A, and start VerneMQ. All service run well.
2. Stop VerneMQ on Instance A and The binary VerneMQ Instance A copy to Instance B. Run VerneMQ on each Instance. All service run well. but when clustering 2 VerneMQ, VerneMQ can join just from Instance B and on cluster status, VerneMQ@IP_InstanceA true, VerneMQ@IP_InstanceB not found.

**Comment by dergraf** [comment]
great. :+1: 

what files do you copy? (maybe better close this bug, and open a new one)

**Comment by berrywira** [comment]
Ok, but how much VerneMQ can handle offline and message queue?

**Comment by dergraf** [comment]
we don't have benchmarks for this, but we tested with thousands of messages.
