### ISSUE TITLE
VerneMQ Not accepting connect

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#430]
Hi,

We are using vernemq 0.15 on production. We just had an outage where in the application server stopped taking in new connections. There is nothing in the logs, console/error/crash, to suggest an actual issue.
Unfortunately we did not capture metrics to exactly the state at that point in time. Not sure how to go about debugging this. We have alarming on the metrics API call. That did not catch this not-responsiveness. In fact atimes it throws in metrics not responding and when we login to the server to check the health, it looks fine.

Additionally couple of more questions:
1) When webhooks give error, timeout or 502, what gets reported as response to the corresponding publish/connect call ?
2) Will too may sockets opened (out of which majority closed) cause this behavior ? 

Thanks,
Karthik

**Comment by larshesel** [comment]
Unfortunately, I don't think we can say anything without more information. Were there no crash dump file generated? Maybe that's not enabled in 0.15 by default - I can't remember. Other things that can cause VerneMQ to stop without a trace is if it was killed by the system such as the OOM killer on Linux.

You can read about what happens when a webhooks fails here: http://vernemq.com/docs/plugindevelopment/webhookplugins.html#webhook-specs. If a timeout happens the client process is terminated and the client disconnected.

I will, as last time, recommend you upgrade to the newest version as soon as possible as many bugs have been fixed since 0.15.x.

**Comment by odx-tech** [comment]
Hi @larshesel,

Yes, there was no crash dump during the period of outage. Also the memory usage and CPU were well within checks of 10-12%. 

Also any idea on the metrics API giving false alarm ? 

Sure, we are in process of updating to latest version. Hopefully will be done this week. 


Thanks,
Karthik

**Comment by larshesel** [comment]
I'm not sure what you mean by false alarm? What exactly happened? What kind of metrics system are you using? In any case I'd recommend to configure an alarm which triggers if you haven't heard from the VerneMQ node for more than a certain time (say 30 secs or 1 minute).

**Comment by odx-tech** [comment]
We hit the /metrics API every 30 seconds and have an alarm if we do not get a response for two consecutive calls. 

What is surprising is that we did not receive alarm for this monitoring during the outage, but we keep receiving these alarms few times in a day when actually there is no issue.

**Comment by larshesel** [comment]
Yes, that doesn't sound good. I have no idea why your monitoring system would report Verne being down it wasn't in reality. Maybe there are some external forces at play there like unreliable networks etc?

**Comment by odx-tech** [comment]
This is happening within AWS.

I've upgraded vernemq to latest version today. Hoping to see it address the issues we were earlier seeing. 


Thanks,
Karthik

**Comment by odx-tech** [comment]
Hi @larshesel ,

We updated to vernemq today morning, post which we saw it going down after a few hours with the following error message:

2017-07-03 06:02:19.798 [error] emulator Error in process <0.8461.2> on node 'VerneMQ@127.0.0.1' with exit value:
{{badmatch,{error,{db_write,"IO error: /var/lib/vernemq/meta/trees/000006.log: Too many open files"}}},[{hashtree,set_disk_bucket,4,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/plumtree/src/hashtree.erl"},{line,637}]},{hashtree,'-update_levels/3-fun-1-',3,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/plumtree/src/hashtree.erl"},{line,575}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{hashtree,update_levels,3,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/plumtree/src/hashtree.erl"},{line,569}]},{hashtree,update_perform,1,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/plumtree/src/hashtree.erl"},{line,356}]},{hashtree_tree,update_dirty,4,[{file,"/opt/vernemq/distdir/1.1.0/_build/default/lib/plumtree/src/hashtree_tree.erl"},{line,369}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{ets,do_foldl,4,[{file,"ets.erl"},{line,585}]}]}
2017-07-03 06:02:19.798 [error] <0.200.0> Supervisor plumtree_sup had child plumtree_metadata_hashtree started with plumtree_metadata_hashtree:start_link() at <0.220.0> exit with reason no match of right hand value {error,{db_write,"IO error: /var/lib/vernemq/meta/trees/000006.log: Too many open files"}} in hashtree:set_disk_bucket/4 line 637 in context child_terminated
2017-07-03 06:02:19.800 [error] <0.8462.2> CRASH REPORT Process <0.8462.2> with 0 neighbours exited with reason: no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in gen_server:init_it/6 line 352
2017-07-03 06:02:19.800 [error] <0.200.0> Supervisor plumtree_sup had child plumtree_metadata_hashtree started with plumtree_metadata_hashtree:start_link() at <0.220.0> exit with reason no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in context start_error
2017-07-03 06:02:19.801 [error] <0.8466.2> CRASH REPORT Process <0.8466.2> with 0 neighbours exited with reason: no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in gen_server:init_it/6 line 352
2017-07-03 06:02:19.801 [error] <0.200.0> Supervisor plumtree_sup had child plumtree_metadata_hashtree started with plumtree_metadata_hashtree:start_link() at {restarting,<0.220.0>} exit with reason no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in context start_error
2017-07-03 06:02:19.801 [error] <0.8468.2> CRASH REPORT Process <0.8468.2> with 0 neighbours exited with reason: no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in gen_server:init_it/6 line 352
2017-07-03 06:02:19.801 [error] <0.200.0> Supervisor plumtree_sup had child plumtree_metadata_hashtree started with plumtree_metadata_hashtree:start_link() at {restarting,<0.220.0>} exit with reason no match of right hand value {error,{db_open,"IO error: /var/lib/vernemq/meta/trees/LOCK: Too many open files"}} in hashtree:new_segment_store/2 line 526 in context start_error


We are also seeing this error: 
can't load acl file "/etc/vernemq/vmq.acl" due to emfile2017-07-03 08:14:13 =ERROR REPORT====
can't load acl file "/etc/vernemq/vmq.acl" due to emfile2017-07-03 08:14:23 =ERROR REPORT====
can't load acl file "/etc/vernemq/vmq.acl" due to emfile2017-07-03 08:14:33 =ERROR REPORT====

But I can see the file to present there. 


Thanks,
Karthik

**Comment by odx-tech** [comment]
Forgot to mention, the ulimit -n value is 819200

**Comment by ioolkos** [comment]
Hm, it still looks like it's related to the number of file descriptors. Under which user do you run Verne?
@dergraf any ideas?

**Comment by odx-tech** [comment]
It is running as vernemq user.

**Comment by ioolkos** [comment]
Good.
We have 2 possibilities: (maybe you see more... :)
- We actually exhaust the 819200 file descriptors (by actually using the resources, or by some faulty behaviour)
- We actually don't have 819200 file descriptors (then we'd have to double check OS configuration)

I'm not sure what to think. My guess is that you probably do not have a number of connections and files that actually are > 819200?

**Comment by odx-tech** [comment]
You are right, we do not have so many files. In fact the net sockets opens (sockets open - sockets close) is roughtly 1k.

**Comment by odx-tech** [comment]
Here are the process limits of the vernemq process:

ubuntu@ip-172-31-9-201:~$ ps -eaf | grep vernemq
vernemq   **8904**     1  0 Jul02 ?        00:00:00 /usr/lib/vernemq/erts-8.2/bin/epmd -daemon
vernemq  **23793**     1  0 12:30 ?        00:00:00 /usr/lib/vernemq/erts-8.2/bin/run_erl -daemon /tmp/vernemq// /var/log/vernemq exec /usr/sbin/vernemq console
vernemq  23795 23793 59 12:30 pts/1    00:00:07 /usr/lib/vernemq/erts-8.2/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /usr/lib/vernemq -progname vernemq -- -home /var/lib/vernemq -- -boot /usr/lib/vernemq/releases/1.1.0/vernemq -config /var/lib/vernemq/generated.configs/app.2017.07.03.12.30.10.config -setcookie vmq -name VerneMQ@127.0.0.1 -smp enable -vm_args /var/lib/vernemq/generated.configs/vm.2017.07.03.12.30.10.args -pa /usr/lib/vernemq/lib/erlio-patches -- console
vernemq  23975 23795  0 12:30 ?        00:00:00 erl_child_setup 1024
vernemq  24040 23975  0 12:30 ?        00:00:00 sh -s disksup
vernemq  24042 23975  0 12:30 ?        00:00:00 /usr/lib/vernemq/lib/os_mon-2.4.1/priv/bin/memsup
vernemq  24043 23975  0 12:30 ?        00:00:00 /usr/lib/vernemq/lib/os_mon-2.4.1/priv/bin/cpu_sup
vernemq  24306 23975  0 12:30 ?        00:00:00 inet_gethost 4
vernemq  24307 24306  0 12:30 ?        00:00:00 inet_gethost 4
ubuntu   24403 22549  0 12:30 pts/0    00:00:00 grep --color=auto vernemq



ubuntu@ip-172-31-9-201:~$ cat /proc/**23793**/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             64125                64125                processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       64125                64125                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us        


Looks like the file limit is not getting applied. But everything looks correct. 
One another process seems to getting the limits correct
ubuntu@ip-172-31-9-201:~$ cat /proc/**8904**/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             64125                64125                processes 
Max open files            819200               819200               files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       64125                64125                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by ioolkos** [comment]
Aha.. :)
the port mapper daemon has enough FDs, but not the VerneMQ process.
I'd stop VerneMQ (if you can do that right now), and then kill the 8904 port mapper daemon. Then make sure to have enough FDs and restart Verne.

**Comment by odx-tech** [comment]
We've got this fixed by increasing the value of DefaultLimitNOFILE in /etc/systemd/system.conf 

Apparently this needs to be updated for ubuntu 16.04 to increase the ulimit values.

**Comment by ioolkos** [comment]
oh...systemd :(

Thank you very much!! I did not know this & will research it. If it seems like the official way to correct problems like this, we'll document it for Ubuntu 16.

Thanks again for your effort & apologies I wasn't a faster/better help ;)

**Comment by odx-tech** [comment]
:) No worries. 

We'll monitor this for sometime to check this as well as the issue mentioned earlier, the main reason to upgrade the version. 


Thanks,
Karthik

**Comment by odx-tech** [comment]
Hi @larshesel, @ioolkos,


 We are seeing our application showing a high amount of open connections than what is typically expected. Is there anyway to debug this - like listing down all open client etc so that we can backtrack from there



Thanks,
Karthik

**Comment by ioolkos** [comment]
Hi @odx-tech 
are you saying VerneMQ is indicating too much (open - closed) sockets? by "our application" you mean the broker component, right?

Unfortunately the vmq-admin session command is not too useful for huge amounts of clients.

**Comment by odx-tech** [comment]
Hi @ioolkos,

I mean the client-application making in a lot of open connections (open-closed) not broker. What I was wondering if there is any way to understand who those clients are ? Like if I can view all open clients ? 


Thanks,
Karthik

**Comment by odx-tech** [comment]
Also @ioolkos is there anyway to retry when the webhook returns an error say in on-publish ?

**Comment by ioolkos** [comment]
@odx-tech do you see an actual error in your webhook for on-publish?
I currently think the broker should not be involved in any possible re-tries here. The publishing client can of course have its own retry logic, supposed QoS > 0.

**Comment by odx-tech** [comment]
Thanks @ioolkos . Yes we do see some errors in our web-hooks, where we have been advised to retry them out. 

Also anything on list of clients connected ?

**Comment by ioolkos** [comment]
@odx-tech maybe you'll find a way to use the `vmq-admin session` command to see what's happening

```bash
➜  vernemq git:(master) ✗ _build/default/rel/vernemq/bin/vmq-admin session show --help
Usage: vmq-admin session show

  Show and filter information about MQTT sessions

Default options:
  --client_id --is_online --mountpoint --peer_host --peer_port --user

Options

  --limit=<NumberOfResults>
      Limit the number of results returned from each node in the cluster.
      Defaults is 100.
  --node
  --mountpoint
  --client_id
  --queue_pid
  --deliver_mode
  --queue_size
  --session_pid
  --is_offline
  --is_online
  --statename
  --deliver_mode
  --offline_messages
  --online_messages
  --num_sessions
  --clean_session
  --is_plugin
  --user
  --peer_host
  --peer_port
  --protocol
  --waiting_acks
  --topic
  --qos
  --msg_ref
  --msg_qos
  --routing_key
  --dup
  --payload

```

**Comment by larshesel** [comment]
I believe the original question was answered here. Closing.
