### ISSUE TITLE
unable to publish

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#432]
### Environment
Ubuntu 14.04 LTS

**- VerneMQ Version:**
Latest from master.

**- OS:**
- Erlang/OTP version (if building from source):
[{release,"Erlang/OTP","19","8.3",
          [{kernel,"5.2","/usr/lib/erlang/lib/kernel-5.2"},
           {stdlib,"3.3","/usr/lib/erlang/lib/stdlib-3.3"},
           {sasl,"3.0.3","/usr/lib/erlang/lib/sasl-3.0.3"}],
          permanent}].

Configuration is Default out of the box with minor changes:
**listener.tcp.default = 0.0.0.0:1883**
(otherwise no connections was made at all)

### Expected behavior
Client should be able to publish since not ACL and
all auth is set to off

using [malaria](https://github.com/remakeelectric/mqtt-malaria) to test the broker:
malaria subscribe -n 1000 -N 20 --host vernemqhost -q 0

### Actual behaviour

Getting This:
2017-06-29 16:04:20.371 [warning] <0.401.0>@vmq_ranch:teardown:127 session stopped abnormally due to 'publish_not_authorized_3_1_1'
2017-06-29 16:04:21.212 [error] <0.477.0>@vmq_mqtt_fsm:auth_on_publish:658 can't auth publish [undefined,{[],<<"beem.loadr-MacBook-Pro.local-36272-17">>},0,[<<"mqtt-malaria">>,<<"beem.

**Comment by larshesel** [comment]
From a **fresh** VerneMQ installation all you need to do is to set `allow_anonymous = on` in the `vernemq.conf` file.

**Comment by dergraf** [comment]
In VerneMQ the `allow_anonymous = on` only affects the authentication part NOT the authorization part. Default authorization is done using the `vmq_acl` plugin which is enabled out of the box and configured with an allow-everything ACL.
For this reason all you have to do when starting with a freshly installed VerneMQ (and you want to allow any connecting client publishing and subscribing to any topic) is to set `allow_anonymous = on` in `vernemq.conf`(as correctly commented by @larshesel).

Hope this helps.

**Comment by syberkitten** [comment]
The first thing I did was `allow_anonymous = on`  :)
It has no effect....

here is a copy paste from my vernemq.conf:
```
## Allow anonymous users to connect, default is 'off'
##
## Default: off
##
## Acceptable values:
##   - on or off
allow_anonymous = on
```

**Comment by syberkitten** [comment]
Ok I got it, the reason it failed was that
i too quickly set  `plugins.vmq_acl = off`

Now I switched it back to `plugins.vmq_acl = on ` and it works :)

**Comment by dergraf** [comment]
Perfect!
