### ISSUE TITLE
 verneMQ broker cannot be connected to any mqtt clients

### ISSUE THREAD

**Issue by aprilsnows** [erlio/vernemq#437]
### Environment

- VerneMQ Version: ubuntu 1.1.0
- OS: ubuntu 16.04.2 LTS xenial
- Erlang/OTP version (if building from source): Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

### Expected behavior

- mqtt client can connect to verneMQ broker and publish/subscribe message. But it's running by 'ping' and 'pong'

### Actual behaviour

- verneMQ broker cannot be connected to any mqtt client

`service vernemq status`

`
vernemq.service - LSB: VerneMQ is a MQTT message broker
   Loaded: loaded (/etc/init.d/vernemq; bad; vendor preset: enabled)
   Active: active (exited) since ke 2017-07-05 16:38:30 EEST; 16h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5680 ExecStart=/etc/init.d/vernemq start (code=exited, status=0/SUCCESS)
    Tasks: 0
   Memory: 0B
      CPU: 0
`

`
systemd[1]: Starting LSB: VerneMQ is a MQTT message broker...
su[5700]: Successful su for vernemq by root
su[5700]: + ??? root:vernemq
su[5700]: pam_unix(su:session): session opened for user vernemq by (uid=0)
vernemq[5680]: vernemq is already running
systemd[1]: Started LSB: VerneMQ is a MQTT message broker.
`

**Comment by ioolkos** [comment]
Hi @aprilsnows thanks for reporting...
can you make sure that you don't have multiple VerneMQ processes started (manually and/or running as service)? Can you take a quick look what's actually running with your `ps` command?

**Comment by aprilsnows** [comment]
Thanks for quick reply. Here is what I get by`ps aux | grep vernemq`:

`
vernemq  11165  0.0  0.0   7540    92 ?        S    10:32   0:00 /usr/lib/vernemq/erts-8.2/bin/epmd -daemon
vernemq  11173  0.0  0.0  14912  1856 ?        S    10:32   0:00 /usr/lib/vernemq/erts-8.2/bin/run_erl -daemon /tmp/vernemq// /var/log/vernemq exec /usr/sbin/vernemq console
vernemq  11175 12.4  1.3 3417420 47844 pts/9   Ssl+ 10:32   0:04 /usr/lib/vernemq/erts-8.2/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /usr/lib/vernemq -progname vernemq -- -home /var/lib/vernemq -- -boot /usr/lib/vernemq/releases/1.1.0/vernemq -config /var/lib/vernemq/generated.configs/app.2017.07.10.10.32.35.config -setcookie vmq -name VerneMQ@127.0.0.1 -smp enable -vm_args /var/lib/vernemq/generated.configs/vm.2017.07.10.10.32.35.args -pa /usr/lib/vernemq/lib/erlio-patches -- console
vernemq  11450  0.0  0.0   4368   688 ?        Ss   10:32   0:00 erl_child_setup 1024
vernemq  11456  0.0  0.0   4508   788 ?        Ss   10:32   0:00 sh -s disksup
vernemq  11458  0.0  0.0   4228   644 ?        Ss   10:32   0:00 /usr/lib/vernemq/lib/os_mon-2.4.1/priv/bin/memsup
vernemq  11459  0.0  0.0   4360   628 ?        Ss   10:32   0:00 /usr/lib/vernemq/lib/os_mon-2.4.1/priv/bin/cpu_sup
tammerf+ 11930  0.0  0.0  15444   960 pts/8    S+   10:33   0:00 grep --color=auto vernemq
`

**Comment by aprilsnows** [comment]
Meanwhile, I get a warning when I start service(`sudo vernemq start`):

`
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
`

**Comment by ioolkos** [comment]
Jep, 1024 file descriptors is way too low to have, that's what the warning is about. You have to configure this to some higher value at OS level.

Also, I'd clean up all those vernemq processes. It's possible that you have one process started manually and one as a service.

**Comment by larshesel** [comment]
Guess we can close this.
