### ISSUE TITLE
Losing messages with shared subscritptions

### ISSUE THREAD

**Issue by jenguidanos** [erlio/vernemq#438]
### Environment

- VerneMQ Version: 1.1.0 (from debian repos)
- OS: Debian 8 Jessie
- Erlang/OTP version (if building from source):

### Expected behavior

- Publish 1000 messages in 10 seconds using 4 subscribers with shared subscriptions

### Actual behaviour

Only 2/3 of messages are received by the subscribers.

### Details

Using mqtt.js client library (Nodejs) i'm publishing messages to a simple topic called "track". In other hand i have another nodejs app subscribed to the topic "$share/tracking/track". No server clusters, direct connection "PUB ---> VERNEMQ ---> SUBS".

There's something interesting, may be ridiculous, but I've been stuck with this for a few hours. See this scenario:

 1 VerneMQ is stopped. Start it with systemctl.
 2 Start 4 nodejs processes susbscribed to the topic "$share/tracking/track"
 3 Start the publisher process and send 1000 messages (in 2/3 seconds). In a tmux session i can see the 4 subscribers printing debug messages (all subscribers are receiving messages). Close publisher process.
 4 My DB shows 1000 new entries. OK!!
 5 Now close 1 subscriber, use only 3.
 6 Launch publisher again to send 1000 new messages.
 7 My DB only shows an increment of 837. ERROR!! Try again (start publisher) and nothing, not 1000 new entries.
 8 Restart VerneMQ with systemctl (keep the 3 subscribers running)
 9 Open again the publisher process and send 1000 msg.
 10 1000 new entries on the DB. OK!!
 11 Goto number 5, history repeats itself.

Tested with the 3 available values of shared_subscription_policy

Resume, when a subscriber stops VerneMQ starts to lose messages and a restart of VerneMQ is required.

I see another issues talking about losing messages when using shared subscriptions, but seems like there's no clean solution and the error is not reproducible by others.

Output from `sudo vernemq config effective`:
[https://pastebin.com/V3UzD9xe](https://pastebin.com/V3UzD9xe)

**Comment by ioolkos** [comment]
@jenguidanos thank you very much for this detailled description!

The issue could be technical, semantical or timing related. But yes, I'm beginning to think there's an issue here: the SubscriberGroup clearly is not updated with that single disconnect, so it keeps randomly sending about 1/4 of the messages to it.
Will have to investigate this with @dergraf and @larshesel

**Comment by dergraf** [comment]
Are your subscribers connecting with `clean_session=false`? Could you repeat your test with different `clean_session` settings?

**Comment by jenguidanos** [comment]
I can confirm than using `clean=true` ([mqttjs client docs](https://github.com/mqttjs/MQTT.js#client)) the problem disappears. Previously i was using `clean=false`.

There is one thing more. On my previus test (with clean=false) i was using the PID of the process as the clientId. This made with every restart a new clientId joining the party. Now I have numbered it with static clientIds, then:

* 4 subscribers started, send 1000 messages
* I get 1000 messages
* Close process with name "client-03", send 1000 message
* I get 760 messages
* Start again client-03, received 240 messages, ok, now i have my 1000 messages

Repeat the operation but in the last point, instead of starting again the process with client-03, set another name, client-05, the 240 messages are NOT received.

Resume: It seems like Vernemq, when clean=false, retains messages for a specific clientId, when is disconnected and a new clientId joins the shared subscription this last doesn't receive the messages retained for the previously.

**Comment by larshesel** [comment]
The above analysis is correct and that is as expected using clean_session false as per the MQTT spec. If you want to use shared subscriptions and offline messages (clean_session false), then you must account for the fact that the messages will be put into the offline queues when the shared subscriber clients are not online and will only be retrieved when the clients come back online.

We have however functionality which is not exposed which could make it possible to only queue messages for clients that are in a specific state (like online). We might look into exposing that and making it into a supported feature at some point.

**Comment by larshesel** [comment]
Closing this. I will however add some more notes to the shared subscriber documentation where we'll try to clarify this a bit.
