### ISSUE TITLE
Rewriting mountpoint in auth_on_register not possible anymore?

### ISSUE THREAD

**Issue by westcode** [erlio/vernemq#439]
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu Xemial 16.04
- Erlang/OTP version (if building from source):

### Expected behavior

We used a mounpoint rewrite in our authentication plugins auth_on_register hook to rewrite a ssl listener back to the 'default' listener to have all clients able to 'talk' to eachother (and circumventing custom authentication for non ssl listener clients):

E.g:

auth_on_register({_IpAddr, _Port} = Peer, {_MountPoint, _ClientId} = SubscriberId, UserName, Password, CleanSession) ->
	case _MountPoint of
		"require_client_cert" -> {ok,[{mountpoint, "default"}]};
		"" ->

This was working fine (think v0.15.3)  but is not with version 1.1.0.  The docs seem to confirm that this is removed: 

http://web.archive.org/web/20160814234347/https://vernemq.com/docs/plugindevelopment/sessionlifecycle.html vs https://vernemq.com/docs/plugindevelopment/sessionlifecycle.html.

How can we solve this? Thanks in advance!

**Comment by ioolkos** [comment]
Hm... thanks @westcode!
@dergraf @larshesel is this related to this commit? https://github.com/erlio/vernemq/commit/5c928fe97c6a0d0c4cc277714334be3555f8f1e5

**Comment by westcode** [comment]
Any ideas? :)

**Comment by ioolkos** [comment]
The experts are kinda on vacation until this weekend, and I'm a little overwhelmed holding the fort...but the ideas and help will come!  :)

**Comment by dergraf** [comment]
This has changed, overwrite the whole `subscriber_id` instead of the mountpoint.

**Comment by larshesel** [comment]
guess we can close this.

**Comment by westcode** [comment]
Thanks for the help
