### ISSUE TITLE
Live update

### ISSUE THREAD

**Issue by berrywira** [erlio/vernemq#44]
Hi @dergraf 

can you update package repo? I want test, feature live update vernemq.
and on documents installation still version 0.10.1

**Comment by dergraf** [comment]
Hi there,

We've updated the debian and ubuntu repos, we've currently facing a problem with the redhat packaging (we have to investigate..). Are you on a rpm based system, or deb? 

Live upgrade won't work here as it we several parts of the update are not backward compatible. I guess that's the luxury of not being 1.0.0 yet. 

Have a look at the changelog.txt to see what has changed.

**Comment by berrywira** [comment]
Ok, I miss read changelog. 
I use rpm based system. 

when I compile source, I got error
===> Compiling /opt/app/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl failed
/opt/app/vernemq/_build/default/lib/plumtree/src/hashtree_tree.erl:141: referring to built-in type set as a remote type; please take out the module name

**Comment by dergraf** [comment]
Ok, will check with the RPMs as soon as possible.

Have you started from a fresh git clone?

**Comment by berrywira** [comment]
Thanks, 
I was started fresh clone from git.

**Comment by dergraf** [comment]
which version of Erlang are you using? It should be one of the 17.x series, 18.0 isn't working.

**Comment by berrywira** [comment]
Erlang from repo epel Centos 7, version R16. 
I will try with 17.x series.

**Comment by berrywira** [comment]
ok, compile success. 
when I compile, vmq_passwd needed openssl-devel.
Thanks

**Comment by dergraf** [comment]
great! please let us know as soon as you run in public, we're eager to showcase your usecase.
