### ISSUE TITLE
update Elixir plugin docs?

### ISSUE THREAD

**Issue by iamyellow** [erlio/vernemq#440]
hi! first of all, I'd just like to say a big thanks for the work on this software. i'm really enjoying how extensible and how well engineered is VerneMQ. a really big kudos!

i'm mostly an elixir developer... quite newbie btw, since i hadn't the chance to work w/ the language in a real project until now. I needed some features that vmq didn't give me out of the box, so I started my own plugin. though I followed your blog post, i found some problems... but, hey! it's not the point of this "issue" talk about them right now! anyway, just writing here to share what i did because maybe someday somebody finds this info useful, or maybe you find useful and want to update the docs :) 

now, what i did:

---

**mix.exs**

```
defmodule TheoVernePlugin.Mixfile do
  use Mix.Project

  def project do
    [app: :theo_verne_plugin,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  defp vmq_plugin_hooks do
    hooks = [
      {TheoVernePlugin, :auth_on_register, 5, []},
      {TheoVernePlugin, :auth_on_subscribe, 3, []},
      {TheoVernePlugin, :auth_on_publish, 6, []},
      {TheoVernePlugin, :on_publish, 6, []},
      {TheoVernePlugin, :on_deliver, 4, []},
      {TheoVernePlugin, :on_offline_message, 5, []}
    ]
    {:vmq_plugin_hooks, hooks}
  end

  def application do
    [
      mod: {TheoVernePlugin, []},
      extra_applications: [:logger],
      env: [vmq_plugin_hooks()]
    ]
  end

  defp deps do
    [{:distillery, "~> 1.4", runtime: false}]
  end
end
```

just a couple of things:

- the way application `env` are set, using tuples like `{TheoVernePlugin, :auth_on_register, 5, []}` -that's the way you do in vmq erlang sources :)- , in the blog post are like `{:on_client_wakeup, MyVMQPlugin, :on_client_wakeup,1,[]}`
- added [distillery](https://github.com/bitwalker/distillery) as dependency

---

**lib/theo_verne_plugin.exs**

```
defmodule TheoVernePlugin.Supervisor do
  use Supervisor

  def start_link do
    Supervisor.start_link(__MODULE__, :ok)
  end

  def init(:ok) do
    children = [
    ]
    supervise(children, strategy: :one_for_one)
  end
end

defmodule TheoVernePlugin do
  use Application

  def start(_type, _args) do
    IO.puts "*** plugin started"
    TheoVernePlugin.Supervisor.start_link()
  end

  def auth_on_register(_peer, {_mountpoint, clientid}, _username, _pw, _clean_session) do
    IO.puts "*** auth_on_register #{clientid}"
    {:ok, []}
  end

  def auth_on_subscribe(_username, {_mountpoint, clientid}, topics) do
    IO.puts "*** auth_on_subscribe #{clientid}"
    {:ok, topics}
  end

  def auth_on_publish(_username, {_mountpoint, clientid}, _qos, topic, payload, _flag) do
    IO.puts "*** auth_on_publish #{clientid} / #{topic} / #{payload}"
    {:ok, payload}
  end

  def on_publish(_username, {_mountpoint, clientid}, _qos, topic, payload, _is_retain) do
    IO.puts "*** on_publish #{clientid} / #{topic} / #{payload}"
    :ok
  end

  def on_deliver(_username, {_mountpoint, clientid}, topic, payload) do
    IO.puts "*** on_deliver #{clientid} / #{topic} / #{payload}"
    :ok
  end

  def on_offline_message({_mountpoint, clientid}, _qos, topic, payload, _is_retain) do
    IO.puts "*** on_offline_message #{clientid} / #{topic} / #{payload}"
    :ok
  end
end
```

---

using the new dependency, we can just execute `MIX_ENV=prod mix release --env=prod`

---

finally, we can add the plugin to `vernemq.conf`:

```
plugins.theo_verne_plugin = on
plugins.theo_verne_plugin.path = /src/verne_plugin/_build/prod/rel/theo_verne_plugin
```
obviously, you'll need to change the absolute path according to your project! but the keys here are 1. we don't need `vmq-admin` to activate the plugin, so 2. we're adding the plugin while vmq starts and not after and 3. distillery bundles **all** the beams vmq will need to execute the project. and it's in release, not development ;)

hope this helps someone!

**Comment by ioolkos** [comment]
Sure this helps someone! THANK YOU SO MUCH :)

Seriously, you just made my day. 

I'll let someone comment on the Elixir side who knows more than me about Elixir. (@larshesel did most some Elixir stuff)
But yeah, so great to see this kind of contribution.

oh, and apologies for the possibly outdated blog posts...

**Comment by guilhermef** [comment]
This should be added to vernemq docs.
I've spent 2 days following the old blog post.
Thanks @iamyellow

**Comment by ioolkos** [comment]
@guilhermef sorry to hear that & many thanks for bringing it to our attention. Glad to see that at least @iamyellow's notes seem to be helpful to you.

**Comment by iamyellow** [comment]
glad to help :) also it's a pleasure where the developers behind a software are so kind and responsive. this is extensible to the erlang/elixir community.
maybe you could consider to open some kind of collaborative wiki w/ community maintained tutorials or something. i think is doable w/ github's wiki.

**Comment by ioolkos** [comment]
Thanks @iamyellow  :) !

A Community Wiki is a great idea...I'll see tomorrow if it's doable with the github wiki. /cc @dergraf, @larshesel

**Comment by larshesel** [comment]
I think this is an interesting idea and I'm 👍 for trying it out.

**Comment by iamyellow** [comment]
morning all! i can confirm a collaborative github's wiki is doable since i contributed long time ago in another one:
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-(a-real-experience)

**Comment by iamyellow** [comment]
FYI and for future issues w/ Elixir integration, i'm integrating my plugin using a different -and hacky- approach.
to put in context, i'm dockerizing a vernemq+plugin installation. when dockerizing apps, and at least is what i read somewhere when i started to work with docker, it seems is a good practice running services in the foreground. i'm pretty sure there're better explanations that 'good practices' :). rebar's version shipped w/ vmq does not ship relx version w/ the foreground option for the startup script. i updated rebar to the latest version but then vmq couldn't load the plugin, i got some POSIX errors. after a few hours, it turns out that erlang vm can run in interactive or embedded mode. i read somewhere again that is a good practice run in embedded in production, but the problem is it cannot dinamically load code after startup. and that was the problem. so i changed the rebar config in order to include the plugin when building vmq. if anyone is interested, i can provide the changes i made to the config file, it was quite easy.

that said, i'm really a newbie in the elixir/erlang world, so forgive if my explanations are quite obvious or something!

**Comment by guilhermef** [comment]
@iamyellow I've started the plugin like this, https://hub.docker.com/r/guilhermef/docker-vernemq/~/dockerfile/ .
Do you think that the plugin should be loaded and started in different way ?

**Comment by iamyellow** [comment]
it -https://github.com/guilhermef/docker-vernemq/blob/master/Dockerfile- seems ok for me... btw, are you facing some problems w/ that dockerfile?

**Comment by guilhermef** [comment]
@iamyellow, I didn't had any issue, the tar.gz generated by distillery works perfectly.
The only thing I had to do was, setting include_erts to false on the plugin.
I was curious about the way you've integrated your plugin.

**Comment by iamyellow** [comment]
got it!

1. update vmq's rebar3 version to latest
2. change rebar.config the relevant part is:
```
{relx,
 [{release, {vernemq, "1.1.0"},
   [
    sasl,
    vmq_server,
    {cuttlefish, load},
    {vmq_passwd, load},
    {vmq_acl, load},
    {vmq_bridge, load},
    {vmq_diversity, load},
    {vmq_webhooks, load},
    {recon, load},
    {eper, load},
    {syslog, load},
    {lager_syslog, load},
    {runtime_tools, load},
    {time_compat, load},
    {tools, load},
    {theo_verne_plugin, load}
   ]},

  {dev_mode, false},
  {include_erts, true},
  {include_src, false},
  {generate_start_script, false},
  {lib_dirs, ["/usr/src/theo_verne_plugin/prod/rel/theo_verne_plugin"]},
```
notice the `theo_verne_` stuff. `lib_dirs` is an absolute path to the release directory generated by distillery. also, in `config.exs` distillery config for `:prod` i added `set include_erts: false`.

3. then `make rel` for build vmq

4. now doing `/usr/src/vernemq/_build/default/rel/vernemq/bin/vernemq foreground` runs vmq in the foreground. you can also do `log.console = console` in `vernemq.conf` to tell vmq to emit logs in the console since it will run inside a docker container.

5. since the plugin is now bundled w/ vmq, no need to tell the plugin path to vmq. so just doing `plugins.theo_verne_plugin = on` it's fine.

this approach is hacky, but not too much.

also, I have a couple docker containers. one is for development, the other is for production. my idea is build w/ the first and, once ready and tested, then make my own production container with the release bundle generated w/ the development container.

sorry, i'm in a hurry i can't extend explanations right now, but let me know if you have any doubts :) i'll try to answer as soon as i can.

**Comment by larshesel** [comment]
Hi, i think we forgot about the wiki idea again, but I just opened it up: https://github.com/erlio/vernemq/wiki/The-VerneMQ-wiki. Let's see how it goes :)

**Comment by larshesel** [comment]
@trarbr was kind enough to contribute a recipe on how to build a complete Elixir plugin using distillery etc: https://github.com/erlio/vernemq/wiki/VerneMQ-plugins-in-Elixir

**Comment by arjun289** [comment]
@iamyellow Thanks for this, saved me lots of effort.
