### ISSUE TITLE
Unable to receive offline message with a sticky session

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#443]
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): 20

### Expected behavior
When a client connects to broker with clean_session=False and persistent_client_expiration is set to 1 week. After some time period, if client disconnects and expectation is that if there are any messages published now should be sent to the client when it connects back again with clean_session=False.

- Please describe the expected behaviour.

### Actual behaviour
Unable to receive the messages.
- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
You need to publish and subscribe with QoS > 0

**Comment by vedavidhbudimuri** [comment]
My bad missed mentioning qos level during subscription. Thank you very much.
