### ISSUE TITLE
Can't enable plugin: due to unknown_module

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#448]
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): 20

### Description
While building the demoplugin facing the below issue. Is this expected if we haven't added any piece of code to the demo_plugin?

#### console.log
`2017-07-19 04:36:20.731 [warning] <0.227.0>@vmq_plugin_mgr:check_plugins:409 can't load application plugin vernemq_demo_plugin due to {unknown_module,vernemq_demo_plugin}`
`2017-07-19 04:36:20.731 [error] emulator beam/beam_load.c(1287): Error loading module
vernemq_demo_plugin:`
`mandatory chunk of type 'Atom' not found`

`2017-07-19 04:36:20.731 [error] <0.36.0> Loading of /home/ubuntu/erlang/vernemq_demo_plugin/_build/default/lib/vernemq_demo_plugin/ebin/vernemq_demo_plugin.beam failed: badfile`
`2017-07-19 04:37:11.605 [error] emulator beam/beam_load.c(1287): Error loading module vernemq_demo_plugin:`
 `mandatory chunk of type 'Atom' not found`

`2017-07-19 04:37:11.605 [error] <0.36.0> Loading of /home/ubuntu/erlang/vernemq_demo_plugin/_build/default/lib/vernemq_demo_plugin/ebin/vernemq_demo_plugin.beam failed: badfile`
`2017-07-19 04:37:11.605 [warning] <0.227.0>@vmq_plugin_mgr:check_plugins:409 can't load application plugin vernemq_demo_plugin due to {unknown_module,vernemq_demo_plugin}`

#### Console output:
`Can't enable plugin: vernemq_demo_plugin due to {unknown_module,
                                                 vernemq_demo_plugin}`

- Steps to reproduce the issue.
Just clone demo_plugin from github mentioned in docs, build the plugin and try to enable it.

**Comment by larshesel** [comment]
VerneMQ does not support Erlang/OTP 20 and I suspect that you've compiled the plugin with that version. Try to compile the plugin with erlang 19 and see if it works then.

**Comment by vedavidhbudimuri** [comment]
Hey @larshesel, thank you it worked fine.

**Comment by riccardoch** [comment]
@larshesel I've compiled your vmq_diversity_utils.erl and succesfully tested! Now it works as expected. Thanks for your help 🙏
