### ISSUE TITLE
vernemq takes 100% CPU -- restart doesn't help

### ISSUE THREAD

**Issue by BertRobbenSony** [erlio/vernemq#45]
After doing some load tests, I managed to get my vernemq server into a state where it always takes 100% CPU (beam.smp process), even when virtually no clients are connected. Once in this state, restarting the server (sudo vernemq restart) doesn't help. I then stopped the server (sudo vernemq stop) and noticed that there is still a vernemq process running (/usr/lib/vernemq/erts-6.4/bin/epmd -daemon). So I killed that one manually and started the server (sudo vernemq start). Same situation with 100% CPU while no connected clients. While in this state, clients have difficulties in connecting to the server but can still send some messages. Note that my load is not that high and I send all message with qos = 0 so theoretically the server should be able to drop all of it.

I have lots of stuff in the logs (crash.log, error.log, etc). E-mail me if you want them (I'd rather not post them here as they contain parts of the messages I sent).

**Comment by dergraf** [comment]
Hi there, thanks for reporting!

I guess you are on 0.11.0, right?
the epmd process is fine, you don't need to restart it.

when your benchmark consisted of thousands of subscribers (every one with a unique client id), it will take some time to rebuild the different indexes in place, this could cause the problem.
How long will it remain in this state?

Could you share the specifics of your benchmark (e.g. how many unique clients with how many subscriptions, clean_session, ..), and please send us the logs?

**Comment by BertRobbenSony** [comment]
Hi Andre,

I’m on 0.10.1-ef5a45b3 (I can easily upgrade). I don’t know how long it will keep on using 99% CPU. Now it seems to crash (process gone) after about 5 minutes or so.

These are the different participants in the test:


(1)    1 “server” component that listens to the main topic, processes each message and publishes a kind of reply to a topic specific to the caller

(2)    About N callers that publish messages to the main topic (one message each minute). These N callers are multiplexed over M mqtt connections.

(3)    About M listeners that listen to a topic specific for one caller

I ran several tests. N is typically somewhere between 100-5000. M is somewhere between 20-200. Ideally N would be equal to M (meaning each caller uses its own mqtt connection), but that would use to much threads (I’m starting tests from a single host) so that’s why I now have a number of callers share a single mqtt connection.

I have the logs ready to send but I don’t want to put them easily accessible on the internet. Can you give me an email address where I can send them to such that they are not shown in github?

Thanks for looking into this,

Bert

**Comment by dergraf** [comment]
Thanks for the details.

Since you're on 0.10.1 it would make a lot of sense to upgrade. I guess your problem might be solved in the new version. It would be great to know how it works on 0.11.0. 
In case you can upgrade now, please make sure to delete the /var/lib/vernemq/[meta|msgstore] folders.

Also, the 0.11.0 packages for CentOS are currently missing in case you are on CentOS, you would need to compile VerneMQ from sources.

We would still be interested in your logs, you can send them to info@verne.mq.

**Comment by BertRobbenSony** [comment]
Ok, log files are sent.

I’ll upgrade to the latest version; I’m on Ubuntu.

I’ll mv the /var/lib/vernemq/m* dirs to some temporary location in case you might need (parts of) them later.

Bert

**Comment by BertRobbenSony** [comment]
Upgrading didn't really help.

After the upgrade to 0.11.0 my server restarted fine. I could connect and publish/receive messages. Then I ran an initial load test (about 20 mqtt connections) which worked well. After that I upped the test to try 100 concurrent connections. This test didn't work. For some reason, I'm no longer able to create any new mqtt connections anymore. What is interesting is that the 3 existing connections that were not part of the test are still working fine. I'm just not able any more to create any new connections.

The ALIVE heart beat is still there in /var/log/vernemq/console.log
In crash.log I see lots and lots of stuff (1.7 Meg) like the following:

    2015-09-11 13:00:15 =CRASH REPORT====
      crasher:
        initial call: vmq_ranch:init/4
        pid: <0.22435.9>
        registered_name: []
        exception error: {{badmatch,{error,enotconn}},[{vmq_ranch,init,4,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,66}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
    ancestors: [<0.265.0>,<0.264.0>,ranch_sup,<0.59.0>]
    messages: []
    links: [<0.265.0>,#Port<0.164247>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 145
      neighbours:
    2015-09-11 13:00:15 =ERROR REPORT====
    Ranch listener {{192,168,116,112},1883} had connection process started with vmq_ranch:start_link/4 at <0.22435.9> exit with reason: {badmatch,{error,enotconn}}

/var/log/vernemq/error.log (0.5 Meg) contains stuff like

    2015-09-11 13:00:12.937 [error] <0.30756.4>@vmq_queue:wait_for_offline:194 got unknown sync event in wait_for_offline state {add_session,<0.19319.9>,#{allow_multiple_sessions => false,clean_session => true,max_drain_time => 500,max_msgs_per_drain_step => 100,max_offline_messages => 1000,max_online_messages => 1000,queue_deliver_mode => fanout,queue_type => fifo,trade_consistency => false}}
    2015-09-11 13:00:12.937 [error] <0.19319.9> gen_fsm <0.19319.9> in state wait_for_connect terminated with reason: no case clause matching {error,wait_for_offline} in vmq_reg:register_subscriber__/3 line 194
    2015-09-11 13:00:12.938 [error] <0.19319.9> CRASH REPORT Process <0.19319.9> with 0 neighbours exited with reason: no case clause matching {error,wait_for_offline} in vmq_reg:register_subscriber__/3 line 194 in gen_fsm:terminate/7 line 611
    2015-09-11 13:00:12.940 [error] <0.19311.9> CRASH REPORT Process <0.19311.9> with 0 neighbours exited with reason: {{{case_clause,{error,wait_for_offline}},[{vmq_reg,register_subscriber__,3,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,194}]},{vmq_reg,rate_limited_op,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,575}]},{vmq_reg,register_subscriber,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,126}]},{vmq_session,check_user,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_s..."},...]},...]},...} in vmq_session:save_sync_send_all_state_event/4 line 161
    2015-09-11 13:00:12.942 [error] <0.19311.9> Ranch listener {{192,168,116,112},1883} terminated with reason: {{{case_clause,{error,wait_for_offline}},[{vmq_reg,register_subscriber__,3,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,194}]},{vmq_reg,rate_limited_op,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,575}]},{vmq_reg,register_subscriber,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,126}]},{vmq_session,check_user,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_s..."},...]},...]},...}
    2015-09-11 13:00:15.065 [error] <0.21666.9> CRASH REPORT Process <0.21666.9> with 0 neighbours crashed with reason: no match of right hand value {error,enotconn} in vmq_ranch:init/4 line 66
    2015-09-11 13:00:15.066 [error] <0.21666.9> Ranch listener {{192,168,116,112},1883} terminated with reason: {badmatch,{error,enotconn}}
    2015-09-11 13:00:15.845 [error] <0.22435.9> CRASH REPORT Process <0.22435.9> with 0 neighbours crashed with reason: no match of right hand value {error,enotconn} in vmq_ranch:init/4 line 66
    2015-09-11 13:00:15.846 [error] <0.22435.9> Ranch listener {{192,168,116,112},1883} terminated with reason: {badmatch,{error,enotconn}}

**Comment by dergraf** [comment]
doesn't this look like #41?

**Comment by BertRobbenSony** [comment]
I’m not sure.

One of the 3 connections that is still alive and kicking is the Japan connection. The other connections that I try to create (and fail) are all from within our own local network. No wireless connections at all.

What’s also a bit strange is that the only log file that still seems to change is the erlang.log.1 (ALIVE messages).

Bert

**Comment by dergraf** [comment]
You are using unique client ids aren't you?

**Comment by BertRobbenSony** [comment]
My different connections use different ids. Different test runs do use the same ids (client id is something like jmeter_${threadNum}).

Trying to connect with a completely unique id also fails now; I just tried this in mqtt spy and it just keeps waiting for the connection to succeed (clean session = true).

Bert

**Comment by BertRobbenSony** [comment]
I just noticed that my publishers and subscribers from the load tests do use the same client id. I’ll fix that.

**Comment by dergraf** [comment]
Great!
Let us know how it goes, and if in case of any bigger errors, it would be great to have the logs again so we can compare them to the ones from 0.10.1.

**Comment by BertRobbenSony** [comment]
I restarted the server. I have this in crash.log (which is different from #41 )

    2015-09-11 14:31:11 =CRASH REPORT====
      crasher:
        initial call: vmq_ranch:init/4
        pid: <0.22905.9>
        registered_name: []
        exception exit: {{{badarg,[{vmq_queue_sup,start_queue,1,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_queue_sup.erl"},{line,67}]},{vmq_reg,register_subscriber__,3,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,184}]},{vmq_reg,rate_limited_op,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,575}]},{vmq_reg,register_subscriber,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,126}]},{vmq_session,check_user,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_session.erl"},{line,694}]},{vmq_session,handle_sync_event,4,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_session.erl"},{line,301}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]},{gen_fsm,sync_send_all_state_event,[<0.22908.9>,{input,{mqtt_connect,3,"nearby-client","!!Digt8ei",1,30,"jmeter_${threadNum}37",undefined,undefined,undefined,undefined}},infinity]}},[{vmq_session,save_sync_send_all_state_event,4,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_session.erl"},{line,161}]},{vmq_ranch,process_bytes,3,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,184}]},{vmq_ranch,handle_message,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,198}]},{vmq_ranch,loop_,1,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_ranch.erl"},{line,99}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
        ancestors: [<0.265.0>,<0.264.0>,ranch_sup,<0.59.0>]
        messages: [{'EXIT',<0.22908.9>,{badarg,[{vmq_queue_sup,start_queue,1,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_queue_sup.erl"},{line,67}]},{vmq_reg,register_subscriber__,3,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,184}]},{vmq_reg,rate_limited_op,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,575}]},{vmq_reg,register_subscriber,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_reg.erl"},{line,126}]},{vmq_session,check_user,2,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_session.erl"},{line,694}]},{vmq_session,handle_sync_event,4,[{file,"/vernemq/distdir/0.11.0/_build/default/lib/vmq_server/src/vmq_session.erl"},{line,301}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,503}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}}]
        links: [<0.265.0>,#Port<0.164467>]
        dictionary: []
        trap_exit: true
        status: running
        heap_size: 4185
        stack_size: 27
        reductions: 809
     neighbours:

**Comment by BertRobbenSony** [comment]
I've just mailed the logs. 

After I restarted my server I it seems to work again (using 50 producer connections and 50 consumer connections now). Beefing up the number after this.

**Comment by BertRobbenSony** [comment]
Nice! After I've made sure my publisher and subscriber using different client ids (which they should since they have different mqtt connections) everything rolls again as it should. 

Using 500 producers and 500 consumers simulating traffic for 25000 users, vernemq now takes less than 5% CPU. The majority of CPU is now taken by my own debug logging to the console.  :smiley: 

So it might indeed have been the reuse of the same client id by different connections that screwed the system.

**Comment by ioolkos** [comment]
Nice :-)
One thing to not forget is also  the max_client_id_size. It's only 23 characters following MQTT spec.
You can increase it in vernemq.conf:
max_client_id_size = 30

**Comment by BertRobbenSony** [comment]
Good tip. 

My first attempt to change the client_id was to use jmeter_subscriber_${threadNum} and jmeter_publisher_${threadNum}. I immediately got invalid client_id exceptions thrown at me ...

**Comment by dergraf** [comment]
Using allow_multiple_sessions=on you would be able to share the same queue
among multiple clients using the same clientid. However that is probably
not what you want.
Am 11.09.2015 15:21 schrieb "BertRobbenSony" <notifications@github.com>:

**Comment by BertRobbenSony** [comment]
Very interesting! This is certainly not what I want in my clients (real or load test). But this might be what I want in my server. 

The thing is that in my server I want to get all of the messages of a certain topic. That topic will be heavily used since all my clients will be publishing to it. Suppose I would like to distribute the load of handling the messages over multiple servers, would it be a good idea then to have all my servers subscribe to that topic, each with their own mqtt connection but all using the same clientId? The semantics I need would be that the message is delivered once (in the meaning of the qos parameter that I provide) to one of the servers. Would that match with allow_multiple_sessions=on ?

**Comment by dergraf** [comment]
Those features aren't well documebted yet, but yes you would be able to
adjust the deliver type from fanout to balance. This will balance the
messages among all attached client sessions.

Very interesting! This is certainly not what I want in my clients (real or
load test). But this might be what I want in my server.

The thing is that in my server I want to get all of the messages of a
certain topic. That topic will be heavily used since all my clients will be
publishing to it. Suppose I would like to distribute the load of handling
the messages over multiple servers, would it be a good idea then to have
all my servers subscribe to that topic, each with their own mqtt connection
but all using the same clientId? The semantics I need would be that the
message is delivered once (in the meaning of the qos parameter that I
provide) to one of the servers. Would that match with
allow_multiple_sessions=on ?

—
Reply to this email directly or view it on GitHub
<https://github.com/erlio/vernemq/issues/45#issuecomment-139546779>.

**Comment by BertRobbenSony** [comment]
Hi Andre,

I just tried out "allow_multiple_sessions=on", as you suggested somewhat earlier in this thread, while connecting with two clients with the same client_id subscribing to the same topic. But I see that both clients get all messages delivered that are published to the topic. I understood from your explanation that the messages would be more or less balanced over the two clients. Did I misunderstand or do I need to change more configuration?

thanks,

Bert

**Comment by dergraf** [comment]
Hi there,

per default all the clients receive all messages, we call this ``queue_deliver_mode=fanout``. For balancing you have to set ``queue_deliver_mode=balance`` in the ``vernemq.conf``.

**Comment by BertRobbenSony** [comment]
Nice, that works! Thanks.

**Comment by dergraf** [comment]
Great!
