### ISSUE TITLE
Testing vmq_diversity app - related to issue (447)

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#451]
Having a very bad issue of not being able to run the diversity mongo plugin.
https://github.com/erlio/vernemq/issues/447

While I'm new Erlang and the whole rebar3 eco-system

Can someone please elaborate how to test / run
the diversity app, either via command line or via IntelliJ idea ?
https://github.com/erlio/vernemq/tree/master/apps/vmq_diversity

when running: 
```$ rebar3 eunit
===> Verifying dependencies...
===> Compiling vmq_diversity
===> Performing EUnit tests...

Finished in 0.320 seconds
0 tests```

**Comment by dergraf** [comment]
@syberkitten The VerneMQ is quite busy atm, or in holidays ;)
I guess get in touch over email and we schedule a one day remote workshop and see that we can bring your setup running.

Debugging vmq_diversity requires a decent understanding of Erlang and its whole ecosystem as well as the VerneMQ plugin system. GitHub Issues is the wrong format to teach you about those topics.

**Comment by syberkitten** [comment]
Thanks, I'd be happy to have this option.
will contact you via email.
