### ISSUE TITLE
Unable to setup cluster

### ISSUE THREAD

**Issue by GibliX** [erlio/vernemq#452]
I'v setup 2 AWS instances in the same subnet.
I'v downloaded "vernemq_1.1.0-1_amd64.deb" to both and changed the followings in the conf file:
```
allow_anonymous = on
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 0.0.0.0:44053
```
Nodename on the serves are:
```
nodename = VerneMQ@127.0.0.1
nodename = VerneMQ2@127.0.0.1
```

When I try to add them to the same cluster i'm using the following command
sudo vmq-admin cluster join discovery-node=VerneMQ@<EXTERNAL_IP>
And I get
`
Couldn't join cluster due to not_reachable
`

In the logs I see:
```
2017-07-20 12:35:14.571 [info] <0.417.0>@plumtree_peer_service:attempt_join:50 Sent join request to: 'EXTERNAL_IP'
2017-07-20 12:35:14.571 [info] <0.417.0>@plumtree_peer_service:attempt_join:53 Unable to connect to 'EXTERNAL_IP'
```

I have checked the port with telnet and it's open, server is answering pings, ports 44053, 1883, 4369 are open on the Security Group.

**Comment by larshesel** [comment]
Try using explicit IP adresses instead of 0.0.0.0 addresses.

**Comment by larshesel** [comment]
And also make sure you have a security group allowing the nodes taking to each other on the required ports. See http://vernemq.com/docs/clustering/communication.html

**Comment by GibliX** [comment]
@larshesel 
Thank you for the fast reply.
I have tried using the explicit IP when using the "join cluster" command.
I have also tried using the explicit IP (in each node's conf file under the vmq listener on port 44053).

Regarding the security groups I even tried allowing all traffic, all ports, anywhere :-\

**Comment by larshesel** [comment]
In the above you don't write that you opened the ports for the erlang distribution as described here: http://vernemq.com/docs/clustering/communication.html

**Comment by GibliX** [comment]
@larshesel As I said on last answer.. I tried opening all traffic from anywhere on the Security group :-(

**Comment by ioolkos** [comment]
AWS really is a pain... ;)
You could deploy withing a VPC, then traffic should be good for all ports & nodes within that VPC.
Or without VPC, then you'd need to setup the Security group. Also there's the question of external IP, internal IP and dynamic hostname. In principle cluster communication should run over internal IPs. 
But this then might lead to the problem that internal IPs probably change on re-start of the node.

But I guess this is the step to go for: don't use 0.0.0.0 anywhere, and configure only the MQTT listener with the external IP, everything else internal.

thanks for your efforts @GibliX ... 
(disclaimer: I'm no AWS expert and everytime I touch EC2 I struggle like hell but in the end manage to do what I need)

**Comment by syberkitten** [comment]
Hey Guys
Perhaps if we succeed with setting up a cluster, we can document
the steps so it would be easier for others and ourselves to follow
next time we forget what we've done. ?

**Comment by GibliX** [comment]
@ioolkos  
Thank you for your help!
I did try what you suggested..
I did:
`
listener.vmq.cluster = PRIVATE_IP:44053
`
on both nodes.
They are on the same VPC.
When I try telnet it's working..
`
ubuntu:~$ telnet 10.1.1.155 44053
Trying 10.1.1.155...
Connected to 10.1.1.155.
Escape character is '^]'.
`

**Comment by GibliX** [comment]
@ioolkos @larshesel 
Maybe i'm missing something in the config file?
Because as you can see the communication is good..

This is my config file (shortened):
```
allow_anonymous = on
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_inflight_messages = 200
max_online_messages = 10000
max_offline_messages = 1000
message_size_limit = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 10.1.1.155:44053
listener.http.default = 127.0.0.1:8888
listener.mountpoint = off
systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local
plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = on
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
```

**Comment by kotky** [comment]
ports that you need to open are 4369, 44053 (if you didn't change it in the config), 6000 - 7999 if you have set up this in vernemq.conf which you will need: 
erlang.distribution.port_range.minimum = 6000
erlang.distribution.port_range.maximum = 7999

**Comment by GibliX** [comment]
Hi @kotky 
I have opened all ports coming from anywhere.. Still same thing :-(

**Comment by kotky** [comment]
@GibliX 
I think that you need to change nodenames to something like this
nodename = VerneMQ@<INTERNAL_IP>
I did it for my instances and it worked, I think that it uses those ip to find the instances. They should be in the same VPC so that they can see each other

**Comment by GibliX** [comment]
@larshesel @ioolkos @kotky 

I managed to cluster the 2 nodes!

That is the first thing I found,
Ports I have open in my SG on AWS
```
4369 from 0.0.0.0/0
44053 from 0.0.0.0/0
6000 - 7999 from 0.0.0.0/0
0-65535 from 0.0.0.0/0
```

nodename in .conf file `“VerneMQ@NODE1_EXTERNAL_IP”` and `“VerneMQ2@NODE2_EXTERNAL_IP”` on the other node

Used the command **sudo vmq-admin cluster join discovery-node=VerneMQ@NODE1_EXT_IP** and the join was successful

I then removed the line 0-65535 from 0.0.0.0/0 from the AWS SG, - Result is, I can’t even restart the VerneMQ service. its hanging failing:
```
ubuntu@ip-10-1-1-155:~$ sudo service vernemq restart
 * Restarting vernemq                                                                                Node 'VerneMQ@NODE1_EXT_IP’ not responding to pings.
Node is not running!
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
vernemq failed to start within 15 seconds,
see the output of 'vernemq console' for more information.
If you want to wait longer, set the environment variable
WAIT_FOR_ERLANG to the number of seconds to wait.
                                                                                              [fail]
```

Not even talking about joining a cluster.. The service didn’t even start.

I re-added the **0-65535 from 0.0.0.0/0** rule to the SG and the restart was OK.
```
ubuntu@ip-10-1-1-155:~$ sudo service vernemq restart
 * Restarting vernemq                                                                                ok
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
                                                                                              [ OK ]
```


The second thing I have found was,
**All tasks here are trying to join from NODE2 to NODE1**
Join cluster - Done
Leave cluster (with -k flag) - Done
Join cluster (again) - Couldn't join cluster due to not_reachable
Restart VerneMQ service - Done on NODE1
Join cluster (again) - Done

Besides the question of “What is going on here?” another question is,
If I have 2 nodes in a cluster and one leaves the cluster, according to scenario 2 we can see that until a restart I to the service on NODE1 I cannot join again with NODE2.
What will happen if I try to join NODE3 to the cluster of NODE1? Will that work? Or the restart is required anyway?

Hope this helps us debug the problem a little more..

**Comment by ioolkos** [comment]
Some more verification for EC2 clustering:

**Security Group:**

 Allow all outbound and allow inbound ssh (22), mqtt (1883), mqttws (8000)
    Internally allow for epmd (4369), epmd port range (6000-7999), cluster port (44053)
    Prometheus port range (9100-9110) 
Public Access to the Prometheus Web UI over Port 9090

You can use the group name to allow only access within this group, if I remember correctly. Then you don't have to use stuff like "from 0.0.0.0/0"

**IPs:**

listener.tcp.listener = _external_ip_:port

listener.vmq.clustering = _private_ip_:44053

listener.http.metrics = _private_ip_:9100

nodename = VerneMQ@fully_qualified_domain_name, or as @kotky said, possibly also the _private_ip_

Furthermore, as I guess this is a test deployment anyway, I would at this point throw away the metadata/data of the cluster nodes at /var/lib/vernemq/* (data will be lost, but the files will be re-created). You have probably re-named nodes by now, and this might cause problems.

Thanks a lot you guys for your efforts & help! @GibliX, @kotky

**Comment by GibliX** [comment]
@ioolkos 
As you suggested I set my AWS Security Group as follows:
22 (Management) - Inbound from My IP only
8000, 1883 - Inbound from 0.0.0.0/0
44053, 4369, 6000-7999 - Inbound only from the same VPC
Nodenames are "VerneMQ@INTERNAL_IP", I don't have a domain for those instances yet..

With this scenario I can't even start the VerneMQ service, It fails..

**Comment by larshesel** [comment]
Hi @GibliX did you solve your issue?

**Comment by GibliX** [comment]
@larshesel 
Nope,
I moved to other brokers for now..

**Comment by larshesel** [comment]
ok, sorry to hear that, of course. Closing.

**Comment by endorama** [comment]
Hello, while trying to setup clustering for 2 vernemq instances I had the same problem mentioned in #472.

After setting `listener.vmq.clustering` to `<internal ip>:<port>` instead of `0.0.0.0:<port>` instances were able to properly setup clustering.

I expected that `0.0.0.0` was more forgiving than any other ip address, but probably this is not how it works? [Inter-node cluster documentation ](https://vernemq.com/docs/clustering/communication.html) suggests 
```
listener.vmq.clustering = 0.0.0.0:44053
```
is a proper configuration, would be nice to have at least a notice about this. I'm pretty sure that in my case the problem was related to this configuration, as has been the only thing I needed to change to make it work.

Thanks

**Comment by ioolkos** [comment]
@endorama thanks for the reminder about this!
The vernemq.conf files have to provide sample configs for the listeners, but I think we'll have to change from `0.0.0.0` to `127.0.0.1` here as a default. I don't remember atm why the `0.0.0.0` might not work with Docker/EC2 etc cases.
