### ISSUE TITLE
Check OffLine Messages.

### ISSUE THREAD

**Issue by SumitFlochat** [erlio/vernemq#453]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source)..

How can i check the offline messages of a particular client?
Example:
A connect to server with clean session false
A has subscribed to topic A
A disconnects
B connect to server
B publishes message to Topic A

Now , the message is stored so that A can receive it once A is connected.
so i want to check these offline messages stored at vernemq.
Provide me with the steps.
If they are stored in process mailbox you can give detail to that and if they are stored in LevelDB can give detail about that.

**Comment by larshesel** [comment]
You can use something like `vmq-admin session show --client_id --offline_messages` to list the offline messages together with the client_id.

**Comment by syberkitten** [comment]
@larshesel 
Would be glad if you can clarify the mapping between the vmq-admin and HTTP API

Would this command
```
vmq-admin session show --client_id --offline_messages
```
Translate to this ? Because it does not work. Only the part up to the "show" works.
```
http://key@localhost:8888/api/v1/session/show?client_id=12334&offline_messages=1
```

Adding

**Comment by larshesel** [comment]
You need to do as on the commandline and add the `--` so it becomes:

```
http://key@localhost:8888/api/v1/session/show?--client_id=12334\&--offline_messages=1
```

Also, if executing via curl or similar from the shell,, remember to possibly escape the `&` like above as it otherwise get's eaten by the shell.
