### ISSUE TITLE
Vernemq Hanging

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#454]
- VerneMQ Version: 1.1.0
- OS: ubuntu 16.04
- Erlang/OTP version (if building from source):

There are couple of issues we have just seen after a 20 days of stable running on production:

1) We continue to see that vernemq hangs and stops receiving requests. I have attached console.log and error.log and metrics at that point in reference. Also attached vernemq config as well. ulimit is set to a very high number 819200

2) When the application hangs, we tried to restart vernemq during which we received this error: 

Jul 21 09:10:20 ip-172-31-9-201 systemd[1]: Starting VerneMQ is a MQTT message broker...
Jul 21 09:10:42 ip-172-31-9-201 vernemq[21600]: vernemq failed to start within 15 seconds,
Jul 21 09:10:42 ip-172-31-9-201 vernemq[21600]: see the output of 'vernemq console' for more information.
Jul 21 09:10:42 ip-172-31-9-201 vernemq[21600]: If you want to wait longer, set the environment variable
Jul 21 09:10:42 ip-172-31-9-201 vernemq[21600]: WAIT_FOR_ERLANG to the number of seconds to wait.
Jul 21 09:10:42 ip-172-31-9-201 systemd[1]: vernemq.service: Control process exited, code=exited status=1
Jul 21 09:10:42 ip-172-31-9-201 systemd[1]: Failed to start VerneMQ is a MQTT message broker.
Jul 21 09:10:42 ip-172-31-9-201 systemd[1]: vernemq.service: Unit entered failed state.
Jul 21 09:10:42 ip-172-31-9-201 systemd[1]: vernemq.service: Failed with result 'exit-code'.

Please advice on both these errors. Let us know if you need anything else. 
[instance1.zip](https://github.com/erlio/vernemq/files/1165489/instance1.zip)

Thanks,
Karthik

**Comment by dergraf** [comment]
Regarding Point 1:
The error logs show that the call to your webhook ended in a timeout. Maybe your webserver was experiencing some interruption? Again looking at the logs it was previously reporting HTTP status 502 which indicates that the web server has difficulties handling our HTTP requests. It can take up to 60 seconds until we receive a timeout, during this time this client is blocked as it is waiting for a response from the Webhook. This is probably what you're experiencing as VerneMQ hangs or stops when serving requests, isn't it?

Regarding Point 2: 
Restarting a VerneMQ node can in fact take up quite some time, as well as consume quite some CPU during this time. The reason for this is, that it rebuilds its internal Hashtree that is used to sync subscriber metadata and retained messages with other cluster nodes. This is usually the main reason why the start script prints out the message `vernemq failed to start within 15 seconds`. However, if you do a `vernemq status` you see that VerneMQ is perfectly running. This is a known issue btw.

**Comment by odx-tech** [comment]
@dergraf 

The HTTP timeouts is a known issue. They've occured in the past as well not impact the health of the vernemq server. Attaching error logs from the past days. 
[error.log.2.txt](https://github.com/erlio/vernemq/files/1165939/error.log.2.txt)
[error.log.1.txt](https://github.com/erlio/vernemq/files/1165940/error.log.1.txt)

Also for the second case, we saw that the vernemq was not running on those nodes when the restart failed. I checked with the metrics command.

**Comment by dergraf** [comment]
Those logs show essentially the same like the logs you've posted above. ;) Your Server is returning 502 for whatever reason and you have the timeouts again. See my "Regarding Point 1".
The console.log you've attached earlier confirms this behaviour too. Thousands of `can't authenticate client` as well as thousands of `stopped due to keepalive expired`. It looks like your clients are DDoS-ing your Webhook Server.

To further investigate I'd say use the provided `vmq_passwd` (or use `allow_anonymous=on`) and `vmq_passwd` and make sure VerneMQ won't hit your webserver for every new client connection.

Can you check with a `ps aux | grep vernemq` or similar next time?

**Comment by odx-tech** [comment]
@dergraf : Let me take a step back and explain our scenario and why those statements in logs are valid and what the actual issue is, I see some gap in here. 

We are a logistics company where in there are on-ground executives who would be delivering parcels to customers. We are using mqtt to track their movement and inturn are using vernemq for the broker. 

It is completely valid for folks on ground to turn of their internet/go through areas without net which would result in expiration of the client with backend and hence the **keep alive is expired**. Secondly the **can't authenticate client** happens when the auth token expires, which is again a very valid scenario - as the token expiration is for a short duration. We cannot use vmq_passwd as we have turned on **auth_on_register** check which calls the webhook api for authentication. 

Coming to the issue of hanging. The timeouts are not the reason for the hanging. During timeouts, which occurs occasionally has impact only on that particular client for a minute. But what we are seeing is that after a certain point in time, not sure what it is, vernemq doesn't accept new connection nor is accepting messages on_publish. I did check that vernemq is still "running", metrics command is responding by calling the server. Unfortunately we are reactive for this issue and not-proactive in catching it. 
Post which the only way to resolve this we need to restart. And on restart we are seeing the second error. 
Hence the questions on what is happening for the hanging and two what needs to be done for restarting it properly. We have currently run vernemq with the console command, so not sure for how long will it continue to run. 

Please let me know if you need anything else. 

Thanks,
Karthik

**Comment by dergraf** [comment]
At the moment where the hanging kicks in, can you make sure that you're not running into any OS/Network resource limits. When VerneMQ hangs, is it using all CPU (this could indicate an other OS level resource limit)?

Otherwise, can you get in touch with us over email info[at]vernemq.com and we can agree on a way we can help you out remotely or on-site.

**Comment by odx-tech** [comment]
@dergraf :


There was a spike in CPU during the period of restart, but otherwise majority of the time during the hanging the CPU utilization was very low. 

We did reach out on the support section for production support. Did not get any revert from the team. 


Thanks,
Karthik

**Comment by dergraf** [comment]
I've just checked our CRM and I figured there was an issue during the last couple of days. Just checked again, please resubmit your information. Thanks for your patience.

**Comment by odx-tech** [comment]
I was out for a while, just reached out to the support. 


Thanks,
Karthik

**Comment by larshesel** [comment]
Guess we can close this then.
