### ISSUE TITLE
kind of -why this work?-

### ISSUE THREAD

**Issue by iamyellow** [erlio/vernemq#456]
1st, i'm sorry if this is not the place to ask for help in order to understand something. i'm developing a plugin and using the registry_mfa approach to access registration/publish/subscribe/etc. as is explained somewhere here and stackoverflow. also, i cannot access to a computer here and i can't wait til tuesday to get my hand dirty and auto-answer my question.
so, i can't understand this:
https://github.com/erlio/vernemq/blob/60a8e478b881ca1587664c70851d2c76cbec160a/apps/vmq_server/src/vmq_reg.erl#L462

i mean, i understand what the function does, but I cannot understand why its result is used as subscriber_id which is a tuple w/ mount point and client_id, right? eg inside SubscribeFun:
SubscriberId(CallingPid)

thanks for your time!

**Comment by larshesel** [comment]
When an MQTT client is subscribing to a topic T it is registered together with the subscriber-id (Mountpoint + ClientId) in the routing table. When a message is published to topic T the subscriber-id is found and is in turn used to look up the PID to which the message is subsequently sent.

When using the functions you point to this also has to happen and a client-id is generated from the caller PID and together with the mountpoint (hardcoded to "") is added to the routing table when the `SubscribeFun/1` is executed.

I hope that makes sense.

**Comment by iamyellow** [comment]
it makes sense :) thank you!
btw, what i'm looking for is to subscribe in behalf of another client. eg chat rooms, user a wants user b to join a multi user chat room. right now, you need to wait for user b to connect and subscribe to the chat room, so user a losts messages if he/she is offline.
since i already made some changes to vmq sources because i'm dockerizing vmq+mu plugin, my idea is modify SubscribeFun/1 to SubscribeFun/2 adding a client_id to subscribe in behalf of.
after your explanation it seems this idea could break something, but i need to test.
another approach i actually tried is using libmosquitto in a nif, but the problem was what happens if it receives some message during the connection+subscription process. i somehow solved that modifying the mosquitto client sources in order to dismiss publish flow (not sending acks), but it's kindof dirty... not sure.

**Comment by larshesel** [comment]
Hi - closing this issue as it's not really an bug-report but more support/discussion type and would be better suited for the slack channel.

Using libmosquitto in a nif sounds like quite an interesting approach :) Just beware and make sure you understand the dangers of doing that as problems with a nif can make the entire erlang VM unstable.
