### ISSUE TITLE
Chain exhausted

### ISSUE THREAD

**Issue by vedavidhbudimuri** [erlio/vernemq#457]
### Environment

- VerneMQ Version: 1.1.0
- OS: 16.04
- Erlang/OTP version (if building from source): 18

`/var/log/vernemq/console.log`
`2017-07-23 11:31:17.258 [warning] <0.444.0>@vmq_mqtt_fsm:check_user:546 can't authenticate client {[],<<"client_1">>} due to chain_exhausted`

If Im settings allow_anonymous = on then its working fine but other than that its giving me that above issue

below is that script im trying to call the server. 
[my_script_new.txt](https://github.com/erlio/vernemq/files/1168042/my_script_new.txt)

My vernemq conf
[vernemq.txt](https://github.com/erlio/vernemq/files/1168041/vernemq.txt)

**Comment by ioolkos** [comment]
It seems you are testing Client Certificates. A quick look has not revealed anything wrong in the config for me.
As you have `listener.ssl.require_certificate` enabled, other authentication plugins should be ignored. (<- is that correct @dergraf / @larshesel ?)

Have you tested the client certs work, btw?

**Comment by vedavidhbudimuri** [comment]
I guess the certs are working fine as it is working fine if I enable allow_anonymous = on. I guess this implies that certificates are working fine, aren't they?

**Comment by ioolkos** [comment]
No! 
`allow_anonymous = on` does exactly what it says, it allows anonymous access. It should not be enabled if client certs are enabled. 
I agree that this is not an optimal situation in terms of config semantics.

**Comment by vedavidhbudimuri** [comment]
@ioolkos wouldn't it raise some ssl related error?

**Comment by ioolkos** [comment]
Wait... I apologize! apparently it's OK to have `allow_anonymous = on` while requiring client certs.
I'll have to look into this later.

**Comment by vedavidhbudimuri** [comment]
@ioolkos is it possible to use certificate base authentication and redis based authorisation?

**Comment by vedavidhbudimuri** [comment]
Hey @ioolkos any update on this issue?

**Comment by larshesel** [comment]
@vedavidhbudimuri your initial question is the same as I've explained in #446 - this happens because you have `vmq_passwd = on` and the client is not being handled by the `vmq_passwd` plugin and no other plugins is available to authenticate the client. This also explains why it works when you set `allow_anonymous = on`, since then client authentication is completely disabled.

Regarding your second question: yes you can use certificate based authentication together with redis based authorization - but you you can't do it with the build in `vmq_diversity` redis script as this implements the hooks for both authentication (`auth_on_register`) and authorization (`auth_on_publish` / `auth_on_subscribe`). See the logic here: https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/priv/auth/redis.lua.

To use client certs + redis authorization (but not authentication) you'll have to either customize the lua script, build your own lua script or build an erlang plugin from scratch.

I hope this helps.

**Comment by vedavidhbudimuri** [comment]
@larshesel I didn't understand "client is not being handled by the vmq_passwd plugin " as I have set `vmq_passwd = on` and sending valid username and password isn't this sufficient?

I have verified that my username and password by connecting to 1883 port without certificates and disabling `allow_anonymous`

I hope this logs are helpful
with `allow_anonymous = off`
vmq-admin trace using certificates and password 
`ubuntu@ip-172-31-21-14:~$ sudo vmq-admin trace client client-id=client_1`
`Starting trace for 1 existing sessions for client "client_1" with PIDs`
 `[<7244.493.0>]`
`New session with PID <7244.541.0> found for client "client_1"`
`<7244.541.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.541.0> Calling auth_on_register({{172,31,21,14},34013},{[],
                                                              <<"client_1">>},ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com,client_1,true) `
`<7244.541.0> Hook returned {error,chain_exhausted}`
`<7244.541.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.541.0> Trace session for client_1 stopped`
`New session with PID <7244.543.0> found for client "client_1"`
`<7244.543.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.543.0> Calling auth_on_register({{172,31,21,14},43968},{[],
                                                              <<"client_1">>},ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com,client_1,true) `
`<7244.543.0> Hook returned {error,chain_exhausted}`
`<7244.543.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.543.0> Trace session for client_1 stopped`
`New session with PID <7244.545.0> found for client "client_1"
<7244.545.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.545.0> Calling auth_on_register({{172,31,21,14},48491},{[],
                                                              <<"client_1">>},ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com,client_1,true) `
`<7244.545.0> Hook returned {error,chain_exhausted}`
`<7244.545.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.545.0> Trace session for client_1 stopped`
`<7244.493.0> Trace session for client_1 stopped`

Without certificates on 1883 port

`New session with PID <7244.561.0> found for client "client_1"`
`<7244.561.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.561.0> Calling auth_on_register({{172,31,21,14},60290},{[],
                                                              <<"client_1">>},client_1,client_1,true) `
`<7244.561.0> Hook returned "ok"`
`<7244.561.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 0)`
`<7244.561.0> MQTT RECV: CID: "client_1" SUBSCRIBE(m1) with topics:`
`    q:1, t: "topic/write/source/client_1"`
`<7244.561.0> Calling auth_on_subscribe(client_1,{[],<<"client_1">>}) with topics:
    q:1, t: "topic/write/source/client_1"`
`<7244.561.0> Hook returned "ok"`
`<7244.561.0> MQTT RECV: CID: "client_1" PUBLISH(d0, q1, r0, m2, "topic/write/source/client_1") with payload:`
`    Message from client client_1-1`
`<7244.561.0> Calling auth_on_publish(client_1,{[],<<"client_1">>},1,topic/write/source/client_1,false) with payload:
    Message from client client_1-1`
`<7244.561.0> Hook returned "ok"`
`<7244.561.0> MQTT RECV: CID: "client_1" PUBLISH(d0, q1, r0, m3, "topic/write/source/client_1") with payload:`
 `   Message from client client_1-2`
`<7244.561.0> Calling auth_on_publish(client_1,{[],<<"client_1">>},1,topic/write/source/client_1,false) with payload:`
`    Message from client client_1-2`
`<7244.561.0> Hook returned "ok"`
`Trace rate limit trigged.`
`Done.`

`

**Comment by larshesel** [comment]
Before you edited it I saw the the username between the two traces are differently. The username when using the client certificate is likely not a username which exists in the `vmq_passwd` password database.

This occurs because you have `listener.ssl.use_identity_as_username = on`.

**Comment by vedavidhbudimuri** [comment]
Hey @larshesel I guess u might have overlooked it as i have removed my public ip from the logs. Anyways i have added the logs here again

vmq-admin trace using certificates and password

`ubuntu@ip-172-31-21-14:~$ sudo vmq-admin trace client client-id=client_1`
`No sessions found for client "client_1"`
`New session with PID <7244.1748.0> found for client "client_1"`
`<7244.1748.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.1748.0> Calling auth_on_register({{172,31,21,14},34210},{[],
                                                               <<"client_1">>},ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com,client_1,true) `
`<7244.1748.0> Hook returned {error,chain_exhausted}`
`<7244.1748.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.1748.0> Trace session for client_1 stopped`
`New session with PID <7244.1750.0> found for client "client_1"`
`<7244.1750.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.1750.0> Calling auth_on_register({{172,31,21,14},46972},{[],
                                                               <<"client_1">>},XXXXXXXXX,client_1,true) `
`<7244.1750.0> Hook returned {error,chain_exhausted}`
`<7244.1750.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.1750.0> Trace session for client_1 stopped`
`New session with PID <7244.1752.0> found for client "client_1"`
`<7244.1752.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.1752.0> Calling auth_on_register({{172,31,21,14},56218},{[],
                                                               <<"client_1">>},XXXXXXXXX,client_1,true) `
`<7244.1752.0> Hook returned {error,chain_exhausted}`
`<7244.1752.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.1752.0> Trace session for client_1 stopped`
`New session with PID <7244.1754.0> found for client "client_1"`
`<7244.1754.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.1754.0> Calling auth_on_register({{172,31,21,14},47459},{[],
                                                               <<"client_1">>},XXXXXXXXX,client_1,true) `
`<7244.1754.0> Hook returned {error,chain_exhausted}`
`<7244.1754.0> MQTT SEND: CID: "client_1" CONNACK(sp: 0, rc: 5)`
`<7244.1754.0> Trace session for client_1 stopped`
^Z
`[8]+  Stopped                 sudo vmq-admin trace client client-id=client_1`

Without certificates on 1883 port

`No sessions found for client "client_1"`
`New session with PID <7244.503.0> found for client "client_1"`
`<7244.503.0> MQTT RECV: CID: "client_1" CONNECT(c: client_1, v: 3, u: client_1, p: client_1, cs: 1, ka: 60)`
`<7244.503.0> Calling auth_on_register({{172,31,21,14},41928},{[],
                                                              <<"client_1">>},client_1,client_1,true) `
`<7244.503.0> Hook returned "ok"`
`<7244.503.0> MQTT RECV: CID: "client_1" SUBSCRIBE(m1) with topics:`
`    q:1, t: "topic/write/source/client_1"`
`<7244.503.0> Calling auth_on_subscribe(client_1,{[],<<"client_1">>}) with topics:`
`    q:1, t: "topic/write/source/client_1"`
`<7244.503.0> Hook returned "ok"`
`<7244.503.0> MQTT RECV: CID: "client_1" PUBLISH(d0, q1, r0, m2, "topic/write/source/client_1") with payload:`
  `  Message from client client_1-1`
`<7244.503.0> Calling auth_on_publish(client_1,{[],<<"client_1">>},1,topic/write/source/client_1,false) with payload:`
`    Message from client client_1-1`
`<7244.503.0> Hook returned "ok"`
`<7244.503.0> MQTT RECV: CID: "client_1" PUBLISH(d0, q1, r0, m3, "topic/write/source/client_1") with payload:`
 `   Message from client client_1-2`
`<7244.503.0> Calling auth_on_publish(client_1,{[],<<"client_1">>},1,topic/write/source/client_1,false) with payload:`
`    Message from client client_1-2`
`<7244.503.0> Hook returned "ok"`
`<7244.503.0> MQTT RECV: CID: "client_1" PUBLISH(d0, q1, r0, m4, "topic/write/source/client_1") with payload:`
`    Message from client client_1-3`
`Trace rate limit trigged.`
`Done.`

**Comment by larshesel** [comment]
It's clear as day:

```
<7244.1748.0> Calling auth_on_register({{172,31,21,14},34210},{[], <<"client_1">>},ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com,client_1,true)
```
 vs

```
<7244.503.0> Calling auth_on_register({{172,31,21,14},41928},{[], <<"client_1">>},client_1,client_1,true)
```

In the first the username is `ec2-54-254-230-31.ap-southeast-1.compute.amazonaws.com` and in the second `client_1`.

Internally when a client is authenticated it is doing by a plugin implementing the `auth_on_register` hook which looks like: `auth_on_register(Peer, SubscriberId, UserName, Password, CleanSession).

**Comment by vedavidhbudimuri** [comment]
Thank you @larshesel for the support. So if the username doesn't exist it throws chain exhausted am I right ?

**Comment by larshesel** [comment]
It works like this: Each plugin implements a set of hooks. In the `vmq_passwd` plugin case it implements the `auth_on_register` hook. VerneMQ supports hook chains, i.e., the same hook can be registered multiple times by different plugins and thus forms a list. In the case of the `auth_on_register` hook implemented by the `vmq_passwd` plugin it can return three values: `ok`, `next` or `{error, Reason}`. When `vmq_passwd` cannot find a user in it's user/password file it returns `next` and since no other plugin (that you currently have enabled) has registered a `auth_on_register` handler, VerneMQ has no other callbacks to call and thus it returns `chain_exhausted`.

I hope this makes sense.
