### ISSUE TITLE
Detailed logging (more then 'debug') ?

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#458]
Using the 'debug' level for the console.log, I don't see enough data for the traffic, 
such new new connections / subscribe / publish and messages sent.

is there an option to make logging more detailed?
or to have certain kind of filters over the output of the logs?

I know it very bad for production especially in high loads -)

but for development purposes it would really help us
see what's going on for every connected client, and
thus help us debug the connecting clients.

**Comment by ioolkos** [comment]
I like to trace with erlyberly https://github.com/andytill/erlyberly
But the vmq-admin trace command might be helpful too. 

```
➜  vernemq git:(master) ✗ _build/default/rel/vernemq/bin/vmq-admin trace client --help
Usage: vmq-admin trace client client-id=<client-id>

  Trace client activities.

  Note, tracing has a performance impact on the running system and
  as such care should be taken, especially when running high load.
  This is also the reason for the low default rate limit settings.

Options

  --mountpoint=<Mountpoint>
      the mountpoint for the client to trace.
      Defaults to "" which is the default mountpoint.
  --rate-max=<RateMaxMessages>
      the maximum number of messages for the given interval,
      defaults to 10.
  --rate-interval=<RateIntervalMS>
      the interval in milliseconds over which the max number of messages
      is allowed. Defaults to 100.
  --trunc-payload=<SizeInByts>
      control when the payload should be truncated for display.
      Defaults to 200.
```

**Comment by syberkitten** [comment]
thanks 👍  I'll look into the erlyberly, and the ability track specific clients
via vmq-admin sounds very good as well.
