### ISSUE TITLE
Observing topics

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#459]
What would be the most direct and simple way
to observe the ongoing topic mesh inside VerneMQ?

(rephrasing the question)

**Comment by larshesel** [comment]
Currently you can use the `vmq-admin session show` command to inspect the state of sessions and queues which includes topics subscribed to. See `vmq-admin session show --help` for the detailed information. This can be executed via the http interfaces as well. See http://vernemq.com/docs/http-administration/ for more information about that.

Note `vmq-admin session show` is powered internally by a (much more powerful) SQL-like query language which we plan to expose externally in the near future.

**Comment by syberkitten** [comment]
@larshesel 
When I'm doing:
```
./vmq-admin session show --topic
```

I don't get a list of all the topics just a small subset,
is this the idea?

My client subscribes to around 5000 topics,
which i can trace via ``` vmq-admin trace client client-id```
and see the whole list.

but when doing session show, i get only a small list of around 100 items.

**Comment by larshesel** [comment]
It is described in `vmq-admin session show --help` - you can set the limit on the returned number of result using `--limit=<Number>`.

**Comment by syberkitten** [comment]
yeah, it was on top so i missed it, great ! :)

**Comment by syberkitten** [comment]
@larshesel 
I don't know if it's the same issue but when doing:
```
./vmq-admin trace client client-id="myclientID"
```

I'm getting this all the time, and the command stops:

```
Trace rate limit trigged.
Done.
```

**Comment by larshesel** [comment]
See `vmq-admin trace client --help`

**Comment by larshesel** [comment]
I just created #467 which will make it easier to discover the available flags which were a bit too well hidden for this command.
