### ISSUE TITLE
Ubuntu 12.10 build vernemq from sources

### ISSUE THREAD

**Issue by virtustilus** [erlio/vernemq#46]
I have server with ubuntu 12.10 installed.
First I built erlang latest (18) version, but I can't build vernemq with it. 
Then I removed erlang and installed 17.5 version. Now I can build vernemq, but after build I can't start it. I get this error message:

    ubuntu@ip-10-80-162-94:~/vernemq/_build/default/rel/vernemq$ bin/vernemq start
    vm.args needs to have a -name parameter.
      -sname is not supported.

Also I can't find any vernemq.conf file.
I tried latest version of vernemq and also 0.10.1 version.
What I'm doing wrong?

**Comment by dergraf** [comment]
Hi there.

thanks for reporting.

yes, you need 17.5, unfortunately 18 isn't yet working.
can you start from a fresh clone of 0.11.1 using 17.5.

the ``vernemq.conf`` should be in ``_build/default/rel/vernemq/etc/vernemq.conf``
