### ISSUE TITLE
Querying VMQ for specific client - connected or not ?

### ISSUE THREAD

**Issue by syberkitten** [erlio/vernemq#468]
How would it be possible theoretically (or in practice)
to query VMQ for specific client to know whether it
is connected or not?

It comes to serve cases where clients try to connect to one another
but one of them is offline.

In this case we need to initiate and APN message to wake up the device (IOS)
and resume the MQTT session.

(Eventually this should be cluster wide, since under the MQTT specs,
there cannot be more then one unique client instance connected to the cluster)

**Comment by ioolkos** [comment]
I understand you want to enable an MQTT client to query for the presence of a specific other client?

Theoretically, this could be done with a plugin that tracks offline/online state (and is queryable over MQTT or REST).
Or possibly also by just doing a REQUEST/RESPONSE to the client directly, if the topic layout would allow this anyway.

Practically, I don't think there's an exposed way to do this over MQTT currently.

**Comment by ryanpresciense** [comment]
Yes this is doable, assuming you have predictable session ids  vmq_queue_sup_sup 

```
queue_for_subscriber(SubscriberId) ->
    case vmq_queue_sup_sup:get_queue_pid({[],SubscriberId}) of
        not_found -> not_found;
        QPid ->
            case vmq_queue:status(QPid) of
                {online, _Mode, _TotalStoredMsgs, _Sessions, _IsPlugin} -> {online,QPid};
                _ -> offline
            end
    end.
```
Will get you a queue pid, and whether it is on or offline. You can rewrite the session id on login with whatever terms you need to be able to identify the session later. by using returning ` {ok,[{subscriber_id,..}]}` from auth_on_register
