### ISSUE TITLE
Throughput Limits of a single node cluster

### ISSUE THREAD

**Issue by alifirat** [erlio/vernemq#469]
### Environment

- VerneMQ Version:1.1.0
- OS: Debian Jessie 

### Hardware 
The benchmark was made between 2 AWS instances and our broker was installed on a M4.XLARGE machine.

### Expected behavior

We're thinking about using VerneMQ to reach a high number of connected devices publishing data to a MQTT broker. Our goal is to scale more than 10 000 devices and reading your documentation, VerneMQ seems promising and can help us.

In our use case, a device has a throughput of 100 / sec with a payload size of 1.3 KB.

So, we did a little benchmark using mqtt-bench  allowing to simulate a high level of devices publishing data on our broker. We are running this tool like this : 

```mqtt-bench -action="pub" -qos=1 -topic="foo" -clients=300  -count=10000 -size=1322 -intervaltime=50```                             

We defined a cluster of 1 node with a single consumer. What we expect from the benchmark is to reach a high throughput for a single node and then to define a cluster with a number of nodes matching our expectations.

### Actual behaviour

 First we run the benchmark with 300 concurrent devices publishing data during few minutes. The reached throughput was 3000 msg / seconds without lost. For us, it represents 30 devices publishing on a single broker.
Using this tool with 600 clients, we met issues  : using the vmq-admin metrics, we  see that we have dropped messages.We change three settings in order to fix dropped message but nothing changed : 

max_online_messages=1000000
allow_multiple_sessions = on
queue_deliver_mode = balance

Putting several consumers didn't change the dropped messages.

So we have some interrogations about VerneMQ : 

1. Did we change the good options to reach a better throughput than 3000 msg / sec ?
2. Is 3000 msg / sec the limit of a cluster composed by one node ?

- Please include minimal steps to reproduce the issue, if possible.

1. Install the vernemq on the same OS and the machine described at top of this messages.
2. Download mqtt-bench : [https://github.com/takanorig/mqtt-bench]
3. Run the same line command that in the message.
4. Check every seconds metrics using vmq-admin.

Many thanks,
Alifirat.

**Comment by dergraf** [comment]
Have you restarted the node after changing the `max_online_messages`. This should help against the dropped messages.

As you're using qos1 please keep in mind that every message hits our LevelDB backed message store.

**Comment by ioolkos** [comment]
Hi @alifirat thanks for your questions!

You will scale to more than 10k connections without any problems. You will not scale to 10k * 100 msg/s = 1M msg/s fan-in on a single M4.XLARGE , and certainly not with QoS 1 (what @dergraf just said)
A single consumer will not sustainably consume this throughput. Also keep in mind that `max_online_messages` will really use RAM with a lot of clients (do the math!)

You probably need to address 2 things: the 100msg/s (batching?) and the single consumer idea.

**Comment by alifirat** [comment]
Hi guys, thanks for your quick responses ! 

@dergraf 

I changed the configuration in ```/etc/vernemq/vernemq.conf``` and then restart the service. To be sure that I have the good value for ```max_online_messages```, I show the value using vmq-admin tool and it's the good one. 

@ioolkos 

There is two things that I cannot change : 
1. 100 msg / sec 
2. Qos : must be 1 because I want to be sure to receive the message at least once. I can have duplicates but not really a problem. 

Before to run the benchmarks, I knew that I cannot load 10K publishing data on a single node. It's the benchmark idea : how many msg / second a single node can support. 

This is why I put 3 consumers in front of my MQTT broker in order to avoid dropped messages. But l still have the issue. And my question comes here : how did you decide to drop a message ? I put a high value for the max_online_messages, I' m publishing less than this value but I got dropped messages. How can it be possible ?

**Comment by larshesel** [comment]
This can be because your consumers can't keep up or because the VerneMQ internal process distributing msgs to your consumers can't keep up and therefore the messages pile up and when hitting the configured limit it has to start dropping messages.

In any case you may wanna look into using shared subscriptions as an alternative to `allow_multiple_sessions`, see http://vernemq.com/docs/configuration/shared_subscriptions.html.

**Comment by ioolkos** [comment]
@alifirat's question is this: if I basically set `max_online_messages` to unlimited, why do I still see dropped messages? shouldn't I run out of memory first (due to the filling of the online queue)?

**Comment by alifirat** [comment]
Yes @ioolkos, I'm expecting a such behaviour in the case I hit memory limits. Without errors or warns, it gives the impression messages must not be dropped.

@larshesel, The thing is that in the 2nd load test, I'm sending exactly 600 000 msg which is less than the max_online_messages (equals to 1 million) so how can I hit this limit in this scenario ? I will have a look to shared subscriptions.

**Comment by ioolkos** [comment]
The VMQ queue is a complex state machine, but you are correct that `max_online_messages` basically define when a session starts dropping messages.

As you test for dropped messages with `vmq-admin metrics show`, please make sure that the dropped counter actually goes up. If not, you don't have actual messages dropping. It's a counter, not a gauge or average per second or sth similar.

**Comment by alifirat** [comment]
We are sure that the dropped counter goes up. 

When we sum the metrics ``queue_messages_dropped`` and ``queue_message_out``, it equals to the metric ``queue_message_in`` value. So for us, we're receiving all the packets from the benchmark but got the wrong result.

**Comment by ioolkos** [comment]
OK, thanks.
I just tried to install mqtt-bench, but weirdly enough it always asks me for a password I don't have. (`go get github.com/takanorig/mqtt-bench`)

**Comment by alifirat** [comment]
We didn't fetch the project using ``go get ... `` but download the binary to use ``mqtt-bench``.  Can you try like this ?

**Comment by ioolkos** [comment]
Quickly tried it. This kinda works for me, although I find testing this way cumbersome.

What client library do you use to subscribe? to what topic do you subscribe? do you always start with a fresh VerneMQ? if not, try starting completely fresh by removing the /var/lib/vernemq/data/*. Caution: this will delete all messages and data from the broker.

**Comment by alifirat** [comment]
In my vernemq version, the data seems to be located in ``var/lib/vernemq/msgstore/``. I should flush this one ?

**Comment by ioolkos** [comment]
Jep, sorry. I'd delete or rename 'meta' and 'msgstore' there.

**Comment by alifirat** [comment]
Hi, 

I started from a fresh installation of verneMQ and I did not have

**Comment by alifirat** [comment]
Hi, 

I tried with a new fresh installation of verneMQ and I think that I found why we saw ``dropped_messages``. We did the following mistake in our benchmark : between two tests, we reset the metrics and it gives us the impression that the queue was empty. But as the command indicated, it reset only the metrics. 

Sorry, I closed the issue by mistake.

**Comment by alifirat** [comment]
Thank you guys for the support. I will continue my benchmarks. 

Juste a quick question : restarting vernemq is enough to flush data from the queue ?

**Comment by ioolkos** [comment]
Glad to hear you got a step further! :)

For persistent session state (like QoS 1 msgs) re-starting is not enough, as the broker will rebuild and re-fill the queues. (it has to, as it has guaranteed the persistency).

So, the best way to have empty queues is to consume them... :)

**Comment by larshesel** [comment]
I think this issue was resolved. Closing.
