### ISSUE TITLE
Auto restart

### ISSUE THREAD

**Issue by berrywira** [erlio/vernemq#47]
Hi @dergraf ,
How detect VerneMQ is crash or down?
I have usecase for autorestart service if VerneMQ down or just error.

**Comment by dergraf** [comment]
Hi there!

the most common in the Erlang world would be to use the 'heart'. This would ensure that VerneMQ gets automatically restarted in case the process goes down abnormally.

To try it out, you've to create a ``vm.args`` file in ``_build/default/rel/vernemq/etc/``. The simplest way is to copy one from ``_build/default/rel/vernemq/data/generated.configs/vm.YYYY.MM.DD.H.M.S.args`` and add the line ``-heart`` to it. 

Now VerneMQ gets restarted even in case of a ``kill -9``. Make sure to familiarize with the heart documentation http://erlang.org/doc/man/heart.html

**Comment by berrywira** [comment]
Ok thanks
