### ISSUE TITLE
Memory leak on cluster mode running with containers

### ISSUE THREAD

**Issue by felipejfc** [erlio/vernemq#470]
### Environment

- VerneMQ Version: 1.1.0
- OS: debian docker base
Kubernetes

### Expected behavior

The containers should run without leaking memory

### Actual behaviour

We are seeing huge memory leak, we are running 6 pods, each of them with a 2gb memory limit and they are getting constantly killed by OOM:

![image](https://user-images.githubusercontent.com/285782/28741923-e6df0058-73f7-11e7-8c07-a55379f4f817.png)

VM args is configured as follow:
```
    +P 256000
    -env ERL_MAX_ETS_TABLES 256000
    -env ERL_CRASH_DUMP /erl_crash.dump
    -env ERL_FULLSWEEP_AFTER 1000
    -env ERL_MAX_PORTS 65536
    +A 64
    -setcookie vmq
    -name VerneMQ@127.0.0.1
    +K true
    +W w
    -smp enable
    +zdbbl 32768
```

And our use case is:

We use vernemq as a chat service for like 10K concurrent connected users and some hundreds of thousands of unique users daily, always with the same clientid(one per user), with very few offline/retained messages...

Any Hint?

**Comment by ioolkos** [comment]
Hi @felipejfc thanks for asking!

What comes to my mind is the size of TCP buffers server side. Can you see how much memory is used per connection?

**Comment by felipejfc** [comment]
Hi @ioolkos, and where can I get this information?
Here is the output of vmq-admin metrics show:

```
root@vernemq-0:/# vmq-admin metrics show
gauge.queue_processes = 9530
gauge.retain_memory = 162512
gauge.retain_messages = 335
gauge.router_memory = 29863512
gauge.router_subscriptions = 12782
gauge.system_utilization_scheduler_4 = 68
gauge.system_utilization_scheduler_3 = 94
gauge.system_utilization_scheduler_2 = 18
gauge.system_utilization_scheduler_1 = 21
gauge.system_utilization = 50
counter.system_wallclock = 4747047
counter.system_runtime = 3246680
gauge.system_run_queue = 0
counter.system_reductions = 6702347912
counter.system_io_out = 2047287583
counter.system_io_in = 1403369049
counter.system_words_reclaimed_by_gc = 21227066588
counter.system_gc_count = 8970201
counter.system_exact_reductions = 6702347704
counter.system_context_switches = 68502469
counter.socket_open = 76627
counter.socket_close = 69361
counter.socket_error = 0
counter.bytes_received = 33679091
counter.bytes_sent = 414431066
counter.mqtt_connect_received = 72743
counter.mqtt_publish_received = 17502
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 18983
counter.mqtt_pubrel_received = 16049
counter.mqtt_pubcomp_received = 18837
counter.mqtt_subscribe_received = 89888
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 232536
counter.mqtt_disconnect_received = 37904
counter.mqtt_connack_accepted_sent = 67330
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_connack_server_unavailable_sent = 2223
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 680272
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 16074
counter.mqtt_pubrel_sent = 19088
counter.mqtt_pubcomp_sent = 15839
counter.mqtt_suback_sent = 88525
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 232536
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 77
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 5
counter.mqtt_publish_error = 2
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 66361
counter.queue_teardown = 56831
counter.queue_message_drop = 0
counter.queue_message_unhandled = 41
counter.queue_message_in = 681413
counter.queue_message_out = 679795
counter.client_expired = 0
counter.cluster_bytes_received = 25548755
counter.cluster_bytes_sent = 14029482
counter.cluster_bytes_dropped = 0
```

**Comment by felipejfc** [comment]
I've set 

advanced.config:

```
    [{vmq_server, [
          {tcp_listen_options,
          [{sndbuf, 4096},
           {recbuf, 4096}]}]}].
```

but memory keeps increasing like before

**Comment by ioolkos** [comment]
Hi @felipejfc thanks for trying out the `advanced.config`

if you don't see the slightest difference in RAM use, then your buffer must've been extremely small already.

At this point I'd start to look into it with recon:

1. Attach to the VerneMQ process by using `vernemq attach` on a node.
2. Have a look around to find processes using a lot of memory
`recon:proc_count(message_queue_len, 5).`
Find the 5 processes using a lot of memory (what kind ever)
`recon:proc_count(memory, 3).`
Then inspect the processes more that you found.
`recon:info("<0.217.0>", memory_used).`
3. Detach/quit with 'ctrl + g' (user switch command), then type 'q'

Do you know the Erlang in Anger book? It goes much deeper into recon, and has a chapter on Finding Memory leaks in Erlang applications)
https://www.erlang-in-anger.com/

Don't forget that the reason you run out of memory might actually be that 2G might be simply too low for your use case.

**Comment by ioolkos** [comment]
Hello @felipejfc have you been able to collect more information on this?

**Comment by dergraf** [comment]
@felipejfc how big are your messages?

**Comment by ioolkos** [comment]
@felipejfc have you been able to gain more insight in this? I'm interested to what kind of problems it points.
(just asking, enjoy your weekend! :)

**Comment by felipejfc** [comment]
hi @ioolkos @dergraf sadly I had to rollback and vernemq is no longer in production, it was restarting every couple of hours, and I think even after I stopped sending clients to the cluster I was still seeing memory usage growing.

**Comment by ioolkos** [comment]
@felipejfc thanks for letting us know. Sorry to hear this happened.
OOM kills VerneMQ before it can release memory, or there is a memory leak for QoS 2. (I don't believe there is but will observe). We can probably conclude that 10k queues with QoS 2 messages is safer to run with > 2G RAM.
Again, sincere thanks for your efforts to support an Open Source project! I'll try to keep you updated if we find any explanation here.

**Comment by larshesel** [comment]
as I don't suppose we'll get more data to investigate this issue I'll go ahead and close it.

**Comment by ioolkos** [comment]
@felipejfc just to let you know...I think you've very probably also been affected by this https://github.com/erlio/vernemq/issues/486#issuecomment-322408092

feeling more than a little stupid right now... but yeah, sic transit gloria mundi.
