### ISSUE TITLE
Unable to set message with Redis cluster

### ISSUE THREAD

**Issue by edwinAtWiz** [erlio/vernemq#471]
### Environment

- VerneMQ Version: 1.1.0
- OS: CentOS 7
- Erlang/OTP version (if building from source): 19
- Redis: 4.0 with cluster mode enabled

### Actual behaviour
Cannot set the message with the cluster mode enabled due to the redis redirect.
Confirm that if the key doesn't need to be redirected, the SET command is work.
I have tried to execute the "redis-cli" in the lua script but it doesn't work (it will break the sub/pub)

Any way to solve it ? Thanks.

**Comment by ioolkos** [comment]
Hi @edwinAtWiz thanks for your report! 
You're obviously referencing this script: https://github.com/erlio/vernemq/blob/a5aefa7bde1c16848ec4bce1196334b00ddc188b/apps/vmq_diversity/priv/auth/redis.lua

I take you use Redis as described in the notes of the script above. Then what you are saying is that the script works with a single Redis but not with Redis cluster 4.0? is that correct rephrasing?

**Comment by edwinAtWiz** [comment]
@ioolkos 
Not related to the redis version but it is related to the cluster issue. But yes without the sharding, there is no node redirect, so it works fine, until I have setup the cluster mode.

**Comment by ioolkos** [comment]
I'm not too familiar with Redis cluster design. I guess any application that talks to Redis shards has to talk to a single point, either a load balancer or a Redis master. Does this makes sense?
(compare the Redis documentation if needed)

**Comment by edwinAtWiz** [comment]
@ioolkos thanks for your reply. I guess the easiest way to due with it is run the command using redis-cli provided by redis itself. So I am wondering if there are any way to call the linux command / bash script inside the lua script?

**Comment by ioolkos** [comment]
I see. Well, take the Lua script, it's up for experimentation :)
I don't know what's the best way to call bash scripts from Lua.

**Comment by larshesel** [comment]
I guess the 'right thing' to do would be for us to add support for redis clusters or redis redirects somehow. It looks like the current redis client we use in VerneMQ does not support the `MOVED` or `ASK` commands. No idea when we could get around to do that or what would be required to do it. We'd like in general to make the redis/mongo/... lua drivers support clustered versions of the databases at some point, but it's always a question about priorities...

At the moment you can't call out to the OS from a lua script and it would be very expensive to do so if you could as each OS cmd would spawn an OS process which is dangerous as it is slow takes a lot of resources (and could effectively kill your server if it's on a heavily used code-path).

I'm sorry not to be of more help here. I think at the moment your best options are to not use redis in cluster mode or to build a full blown erlang plugin adding the redis support you need (including a redis client supporting `MOVED` and `ASK`.

**Comment by edwinAtWiz** [comment]
@larshesel  Maybe I need to find another way to solve this then. Thanks for the reply.
