### ISSUE TITLE
Load testing of subscription

### ISSUE THREAD

**Issue by tremoteye** [erlio/vernemq#474]
Hello,

Is there any load testing result of subscription (not publishing messages)?
If yes, please share the information.

The result simply is like that
10k subscriptions per sec can be accepted.

Appreciate in advance.

**Comment by ioolkos** [comment]
@tremoteye thanks for asking...good question. I have no clear cut number to give you, but let's try to find out.
Are you interested in any specific scenario (number of subscribers etc)? Are you interested in any specific kind of server/cpu size?
Meanwhile I'll try to come up with a loadtest that can give you some preliminary comparative answer.

**Comment by dergraf** [comment]
I think it really depends on how those subscriptions enter VerneMQ, e.g.:

1. [10'000 Clients send CONNECT, every client issues SUBSCRIBE with one topic/qos pair]/Second
2. [100 Clients send CONNECT, every client issues SUBSCRIBE with 100 topic/qos pairs]/Second

The way VerneMQ currently works Scenario 1 will produce a much higher load wrt. to CPU, Memory, Network IO than Scenario 2.

**Comment by tremoteye** [comment]
Thanks for quick responses :)

The first scenario @dergraf  is suitable for the our target solutions.
I will carry out the load test soon and share with VerneMQ team.

**Comment by hbahn** [comment]
Share the first Load Test Result under the condition below.
Please find the attachment and can see the grafana graph during the test.

**[10'000 Clients send CONNECT, every client issues SUBSCRIBE with one topic/qos 1 pair]/Second**

Could you give me some performance tuning tips for this load services?
and we will try 20'000 Clients send CONNECT case tomorrow.

[VerneMQ Load Test Result_r1.pdf](https://github.com/erlio/vernemq/files/1204575/VerneMQ.Load.Test.Result_r1.pdf)

**Comment by ioolkos** [comment]
@hbahn thanks!
did you also disconnect and re-connect the clients multiple times? or do they only connect once, and then constantly subscribe and unsuscribe?
I'm asking because the connection accepted rated stays at 4k in scenario 2.

**Comment by hbahn** [comment]
@ioolkos 

Sure. each thread disconnect the session after unsubscription and repeat the sequence in the same thread.

**Comment by ioolkos** [comment]
Are the Client IDs the same everytime or random? I guess you connect with clean_session = true?

So the limits you hit are at sustainably (for 20 minutes):
- connecting about 4k clients / s
- disconnecting about 4k clients / s
- doing 4k SUBSCRIBES / s (btw: to individual topics?)
- doing 4k UNSUBSCRIBES / s

What would you actually like to optimize for? just linearly better with exactly this scenario?

**Comment by tremoteye** [comment]
Yes. Each server has the limit you mentioned.

Is there any way to improve (linerly) the performance for this scenario? Using venremq.conf.

**Comment by ioolkos** [comment]
There are no magic configs, I fear.
Non-exhaustive tuning guide is here: https://vernemq.com/docs/misc/tuning-vernemq.html

**General remarks:**
- Optimise the scenario first. Optimising the scenario means optimising the topic tree!
- Performance is often limited by bottlenecks. Apart from OS resource contention, processes (gen_server) can be bottlenecks. IO can be a bottleneck.
- CPU overload = all bets are off.
- RAM exhaustion will kill the VM.

**What is faster:**
- HIPE is faster than BEAM (VerneMQ doesn't hipe-compile currently)
- Using the same ClientID on every connect is faster than using random IDs. (Verne then reuses the hash keys)
- Using clean_session false is faster than subscribing (to always the same topics)
- Separating CONNECT and SUBSCRIBE phases is faster than mixing (this only matters in synthetic workloads tbh)
- An Erlang runtime tuned to your scenario is faster than a runtime started with default flags.
- TCP only is faster than TLS. You should always use TLS.
- Running VerneMQ on a dedicated server is faster than running it shared with other software.

**Your tools for config experimentation:**
- vernemq.conf
- advanced.config file: supplementary config file
- vm.args file: VM configuration file, replaces the autogenerated vm.args file, and overrides
some configurations in the vernemq.conf file.


All needs to be measured. There is no quick fix for anything performance related.

I'll shortly open the Wiki for user contributions here on github. We can collect further performance ideas there.
/cc @larshesel @dergraf @tremoteye

**Comment by tremoteye** [comment]
Thanks for the answer.

Attached the load test result carried on today,

* The Graph shows that Connection Accept is around 30K each server. (two server clustered) and subscribe individual topics 30K
**(if prometheus collect the VerneMQ metric every 5 secs, is 30K / 5secs (6K/sec) right?)**
* The cluster maintained the status for 17 minutes and went down which means that any client could not connect the clustered broker.

![messages image 727024425](https://user-images.githubusercontent.com/29115186/29068641-9d3e946c-7c72-11e7-9edd-a44480545086.png)

* The Graph shows that Connection Accept is around 20K each server. (two server clustered)
* The cluster maintained the status for around 20 minutes and went down.

![screenshot 2017-08-08_19-00-37](https://user-images.githubusercontent.com/29115186/29068881-7d9019b4-7c73-11e7-873c-46c512ae56fe.png)

**After the graphs showed that brokers were down, netSplit situation occurred. in this situation, to overcome service out situation, is this okay to set true to all the trade consistency values, allow_register_during_netsplit, allow_publish_during_netsplit, allow_subscribe_during_netsplit, and allow_unsubscribe_during_netsplit. ? **

**Comment by dergraf** [comment]
@tremoteye we cannot tell you if it is ok to set `allow_*_during_netsplit = on` this is a trade-off you have to decide for your particular case. Please read https://vernemq.com/docs/clustering/netsplits.html.

**Comment by tremoteye** [comment]
Could you review the log above?
Keep facing the log during the load test.

**Comment by ioolkos** [comment]
`monitor busy_dist_port <0.5406.66>` indicates that the Erlang Cluster distribution port is overloaded.
This goes as far as a timeout between the nodes, so that in fact a partition is created.

The network partition then explains the `can't register client` event. (this is depending on netsplit configuration).

The third error from the plumtree metadata manager is unclear to me atm. It says it can't find certain subscribers.

You could increase the max distribution buffer size (let's say to 32MB), by adding
`erlang.distribution_buffer_size = 32MB` to your `vernemq.conf` file.
This might delay the problem (or introduce other problems)

**Comment by larshesel** [comment]
Closing this as it seems to have gone inactive

**Comment by Akashlv7** [comment]
@tremoteye can you please tell me how to conduct these tests on verneMq.
Anyone please show me how to conduct a load test.

Thanks in Advance
