### ISSUE TITLE
VerneMQ does not reconnect to mongoDB if Database is restarted

### ISSUE THREAD

**Issue by KnolBee** [erlio/vernemq#475]
### Environment

- VerneMQ Version: 1.1.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Expected behavior

- Restart of MongoDB shouldn't force restart of VerneMQ

### Actual behaviour

- If MongoDB is restarted, VerneMQ stops authenticating until restarted.

**Comment by ioolkos** [comment]
@KnolBee thanks for pointing that out. That's totally unfortunate.
@larshesel @dergraf Is there some trick to restart the connection pool? or should it work out of the box anyway?

**Comment by larshesel** [comment]
This looks like a bug - I'll investigate soon.

**Comment by larshesel** [comment]
I can confirm this - the child connections are restarted until the supervisor reaches its max restart intensity and shuts down taking vmq_diversity with it.

**Comment by KnolBee** [comment]
Thanks @larshesel are there plans to fix this? This is definitely a blocker for production use of MongoDB authentication module.

**Comment by larshesel** [comment]
It will be fixed but I can't give a time frame ATM.

**Comment by larshesel** [comment]
Btw. I forgot to answer if there was some workaround to this. I would expect - but haven't tested it - that if you restart the `vmq_diversity` plugin then the pools should get reinitialized. I'll try to spend some time on this issue today.

**Comment by larshesel** [comment]
Hi @KnolBee , I've a branch in #491 which should fix this issue. Could you test that out? Next I'd try to bring in an upgraded mongodb driver.

**Comment by larshesel** [comment]
Merged

**Comment by KnolBee** [comment]
Hi @larshesel Ok great, Will test over the weekend.
