### ISSUE TITLE
client_id modifier for auth_on_register webhook cause error

### ISSUE THREAD

**Issue by tpuza** [erlio/vernemq#476]
### Environment

- VerneMQ Version: 1.0.1
- OS: erlio/docker-vernemq
- Erlang/OTP version (if building from source):

### Expected behavior

When using webhooks for "auth_on_register", we expect broker to consume modifier "client_id" as was working prior version 1.0.1

Example of  working "auth_on_register" http response:
```
{
  "result": "ok",
  "modifiers": {
     "client_id": "3GwEXQIgPgkXtXh7XFOdRG"
  }
}
```
results in
`
<7244.510.0> Hook returned "ok" with modifiers:
    {client_id,<<"3GwEXQIgPgkXtXh7XFOdRG">>}
`

This option is documented here https://github.com/erlio/vernemq/tree/master/apps/vmq_webhooks#auth_on_register. On this place is client_id modifier not mentioned http://vernemq.com/docs/plugindevelopment/webhookplugins.html#auth_on_register.

### Actual behaviour

Starting version 1.0.1 "client_id" modifier is not supported for "auth_on_register" hook and broker does not authenticate client to connect due to webhook error. This behaviour is also at v1.1.0.

```
{
  "result": "ok",
  "modifiers": {
     "client_id": "3GwEXQIgPgkXtXh7XFOdRG"
  }
}
```
`
<7244.592.0> Hook returned {error,error}
`

When we remove "client-id" modifier, so response looks like this
```
{
  "result": "ok"
}
```
client gets authenticated correctly on the broker.

This is detailed description of problem, that was reported in my comment lately https://github.com/erlio/vernemq/issues/407#issuecomment-308638461

**Comment by ioolkos** [comment]
@tpuza thanks for bringing this back up again!
I guess this is related to commit:
https://github.com/erlio/vernemq/commit/5c928fe97c6a0d0c4cc277714334be3555f8f1e5
subscriber id = mountpoint + clientid.

@larshesel @dergraf is this a breaking change that was not documented? or is there no change in API, but the commit maybe introduced a bug?

**Comment by larshesel** [comment]
You need to override *both* the `client_id` and the `mountpoint` for the `client_id` change to have an effect. We changed this as the mountpoint override was not working and chose to do it this way to make it consistent with how the subscriber-id (client_id + mountpoint) is handled internally in VerneMQ.

**Comment by tpuza** [comment]
OK, we've updated modifier like this and problem is solved.

```
{
  "result": "ok",
  "modifiers": {
     "client_id": "3GwEXQIgPgkXtXh7XFOdRG",
     "mountpoint": ""
  }
}
```
Is this proper/intended solution @larshesel?

**Comment by ioolkos** [comment]
looks good to me!

**Comment by larshesel** [comment]
@tpuza looks good to me as well. Apologies for the inconvenience.
