### ISSUE TITLE
Use webhooks to detect ungraceful client disconnects

### ISSUE THREAD

**Issue by mrname** [erlio/vernemq#482]
### Environment

- VerneMQ Version: N/A
- OS: N/A
- Erlang/OTP version (if building from source): N/A

I apologize in advance if this belongs somewhere else (a forum, mailing list, etc.).

I would like to create a system that keeps track of client activity and sends notifications (email, twilio, etc.) when a client disconnects ungracefully. Of course, part of this is that I also want to be able to send a "resolved" message when the client reconnects. I was originally planning on using the last will feature of MQTT protocol to send to a "something bad happened" topic, and have a listener on that topic that sends the alert, but as I mentioned, I would also like to be able to detect the reconnection.

I understand that this could be implemented by allowing the client to publish messages regarding their state, but I would like the functionality to be opaque to the clients.

So, I have started working on a small REST API that receives and stores messages from VerneMQ webhooks.

My question is two-fold:

1) Am I missing a feature that I could use instead of building this out?
2) Is there a webhook that gets triggered when a client disconnects ungracefully? (the same event that would cause the broker to execute LWT). I understand that I can look at `on_client_gone` and `on_client_disconnect` but those are also triggered on graceful disconnects.

Thanks!

**Comment by larshesel** [comment]
There currently exists no plugin hooks which conveys the information that the client was ungracefully disconnected. See also http://vernemq.com/docs/plugindevelopment/sessionlifecycle.html (which is the basis for all plugins).

Maybe an ungraceful disconnect hook would be nice addition (if possible...), I'll take a look. /cc @dergraf 

For the moment I think you'd have to stick with the 'normal' way of handling this, namely having the client publish it's status using (possibly retained) LWT messages.

**Comment by mrname** [comment]
Excellent, thanks for the quick response @larshesel, I assumed this would be the case.

I will brush up on my erlang so that I can try to look into assisting with implementing this hook.

**Comment by larshesel** [comment]
I'll close this for now - let us know if you start on sth like this as I think it would be good to discuss the approach taken.

**Comment by arvindr21** [comment]
Hello @larshesel, on the similar topic, I am now able to get the presence with `auth_on_register` and `on_client_offline`/`on_client_gone` hooks. 

Taking a simple scenario of a client connecting to the broker: on connect the `auth_on_register` hook is fired, which indicates a client is online and is requesting for access.  Now, I know if the client was allowed, denied - hence online or offline or banned.

Similarly, if the client goes offline, depending on the `keep alive` and `clean session` values defined by the client, `on_client_offline` or `on_client_gone` hooks get fired and I know that the client is offline.

If the device is offline and I publish a data to that device with `retain` as `false`, `on_offline_message` would be fired indicating that client is offline and we are trying to publish data to it.

Now the actual scenario.
```
Client A -> Keep Alive - 30seconds, clean session - true, QoS - 2
Client B -> Keep Alive - 30seconds, clean session - true, QoS - 2

Client A & Client B -> Connect to broker. 

Client A -> Publish -> Client B // Data Received `on_deliver` fired
Client A -> Publish -> Client B // Data Received `on_deliver` fired
Client A -> Publish -> Client B // Data Received `on_deliver` fired

Client B  -> Goes offline // keep alive is 30 seconds

Broker doesn't know if Client B is offline

Client A -> Publish -> Client B // `on_deliver` fired
Client A -> Publish -> Client B // `on_deliver` fired
Client A -> Publish -> Client B // `on_deliver` fired

30 seconds passed

Broker detects Client B is offline // `on_client_offline` fired

Client A -> Publish -> Client B // `on_deliver` not fired & `on_offline_message` fired
```
Question: How to handle this time between the device actually going offline and the broker detecting it? And if any data is published to the device, how to be sure if it was delivered or not.

Any help/thought process is appreciated

Thanks,
Arvind.

**Comment by larshesel** [comment]
With QoS>0 then any message for client B will be kept by the broker (up to the configured max) and if you have set clean_session=false then they will be kept as offline messages when the broker detects the client has gone offline.

If you need to *know* that the message was delivered to a client you have to build that into your messageing patterns. One of the fundamental properties of MQTT is that the broker delivers on behalf of the publishing client.

**Comment by abhitheawesomecoder** [comment]
Whats the difference between on_client_offline and on_client_gone. I didn't find any case when on_client_offline endpoint was called even once.
