### ISSUE TITLE
Memory Keep Increasing

### ISSUE THREAD

**Issue by tremoteye** [erlio/vernemq#486]
### Environment

- VerneMQ Version: 1.1
- OS: CentOS 7
- Server: 8 cores / 16G RAM VM (not AWS instance)
- Test Environment : 30K concurrent connections to a single vernemq node and each connection thread disconnects after 1 minute sleep and reconnect repeatdely.

About clientID, in this test we use ONLY 30K clientID window under the same username.

We have been carry out this test for around 10 hours.

### Expected behavior

- VerneMQ should keep maintaining consistent memory level

### Actual behaviour

1. TCP open numbers : maintaining around 30K connections

[broker@BPV-TRE-DV02 ~]$ netstat -anp|grep 1883|wc

  29213  197496 2849507

2. Memory usage is keep increasing

* After 2 hours test measurement
: Using 2.2G RAM consumption

              total        used        free shared  buff/cache   available
Mem:   16252224     2274356    13255092  67536      722776    13620544
Swap:       8388604           0     8388604

* After 10 hours test measurement
: Using 4.4G RAM consumption. I can see that the Memory Usage keep increasing very slowly.

total        used        free      shared  buff/cache   available
Mem:       16252224     4457216    10903600       67536      891408    11415376
Swap:       8388604           0     8388604

**Comment by larshesel** [comment]
Hi @tremoteye , a couple of followup questions:

1) are you running a cluster or testing against a single node?
2) If I understand it correctly no messages are published?
3) Are there any subscriptions made or do the clients only connect?
4) Only 30K unique client-ids are used? Or do the clients generate a new client-id when reconnecting?
5) Could you share your vernemq.conf file with us?

Thanks

**Comment by tremoteye** [comment]
Here is the answers. Thanks for the response.

1. are you running a cluster or testing against a single node?
-> Just test against a single node (no cluster)

2. If I understand it correctly no messages are published?
-> nope. only connection burst.

3. Are there any subscriptions made or do the clients only connect?
-> nope. only connections.

4. Only 30K unique client-ids are used? Or do the clients generate a new client-id when reconnecting?
-> only 30K unique client-ids are used.

5. Could you share your vernemq.conf file with us?
`allow_anonymous = on
allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off

max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
message_size_limit = 0
upgrade_outgoing_qos = off

listener.max_connections = 500000
listener.nr_of_acceptors = 1000
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
listener.mountpoint = off

systree_enabled = on
systree_interval = 20000

graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local

plugins.vmq_passwd = on
plugins.vmq_acl = on
plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off

vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
vmq_passwd.password_file = /etc/vernemq/vmq.passwd
vmq_passwd.password_reload_interval = 10
vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off

log.console = file
log.console.level = debug

log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5

nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144

leveldb.maximum_memory.percent = 70`

6. Could you share the output of vmq-admin metrics show as well?
-> 

`gauge.queue_processes = 25000
gauge.retain_memory = 21152
gauge.retain_messages = 0
gauge.router_memory = 11920
gauge.router_subscriptions = 0
gauge.system_utilization_scheduler_8 = 3
gauge.system_utilization_scheduler_7 = 7
gauge.system_utilization_scheduler_6 = 5
gauge.system_utilization_scheduler_5 = 8
gauge.system_utilization_scheduler_4 = 5
gauge.system_utilization_scheduler_3 = 6
gauge.system_utilization_scheduler_2 = 5
gauge.system_utilization_scheduler_1 = 100
gauge.system_utilization = 17
counter.system_wallclock = 3607264
counter.system_runtime = 1306340
gauge.system_run_queue = 0
counter.system_reductions = 2980584179
counter.system_io_out = 84821889
counter.system_io_in = 36595433
counter.system_words_reclaimed_by_gc = 17433549491
counter.system_gc_count = 11720320
counter.system_exact_reductions = 2980584052
counter.system_context_switches = 37752622
counter.socket_open = 314755
counter.socket_close = 289755
counter.socket_error = 0
counter.bytes_received = 20986936
counter.bytes_sent = 9192216
counter.mqtt_connect_received = 314742
counter.mqtt_publish_received = 0
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 3966624
counter.mqtt_disconnect_received = 231938
counter.mqtt_connack_accepted_sent = 314742
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 3966624
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 0
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 314742
counter.queue_teardown = 289742
counter.queue_message_drop = 0
counter.queue_message_unhandled = 0
counter.queue_message_in = 0
counter.queue_message_out = 0
counter.client_expired = 0
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 0
counter.cluster_bytes_dropped = 0`

7. Do the clients connect with clean_session true or false?
-> all connections has set to clean_session == true

**Comment by tremoteye** [comment]
Plus

Metric information after 4 hours running

gauge.queue_processes = 35000
gauge.retain_memory = 21152
gauge.retain_messages = 0
gauge.router_memory = 11920
gauge.router_subscriptions = 0
gauge.system_utilization_scheduler_8 = 11
gauge.system_utilization_scheduler_7 = 11
gauge.system_utilization_scheduler_6 = 8
gauge.system_utilization_scheduler_5 = 10
gauge.system_utilization_scheduler_4 = 5
gauge.system_utilization_scheduler_3 = 12
gauge.system_utilization_scheduler_2 = 100
gauge.system_utilization_scheduler_1 = 46
gauge.system_utilization = 25
counter.system_wallclock = 18630317
counter.system_runtime = 5154220
gauge.system_run_queue = 1
counter.system_reductions = 15762537008
counter.system_io_out = 637218441
counter.system_io_in = 145452027
counter.system_words_reclaimed_by_gc = 89426563775
counter.system_gc_count = 66331161
counter.system_exact_reductions = 15762536713
counter.system_context_switches = 165724118
counter.socket_open = 1972467
counter.socket_close = 1937467
counter.socket_error = 0
counter.bytes_received = 81250360
counter.bytes_sent = 8011416
counter.mqtt_connect_received = 1972464
counter.mqtt_publish_received = 0
counter.mqtt_puback_received = 0
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 0
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 60782
counter.mqtt_disconnect_received = 1115085
counter.mqtt_connack_accepted_sent = 1972463
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 0
counter.mqtt_publish_sent = 0
counter.mqtt_puback_sent = 0
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 0
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 60782
counter.mqtt_publish_auth_error = 0
counter.mqtt_subscribe_auth_error = 0
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 1972464
counter.queue_teardown = 1937464
counter.queue_message_drop = 0
counter.queue_message_unhandled = 0
counter.queue_message_in = 0
counter.queue_message_out = 0
counter.client_expired = 0
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 0
counter.cluster_bytes_dropped = 0

**Comment by larshesel** [comment]
Could I get you to monitor the os memory usage of the vernemq process over time (say 24 hours) and plot a graph of it (keeping the load constant). VerneMQ is not always releasing memory even if it's no longer using memory it previously allocated. So the memory increase should reach a stable plateau over time.

**Comment by larshesel** [comment]
It would be good if the plot consists of datapoints sample relatively often, say once a minute (not every hour) or so, just to have a good resolution.

**Comment by larshesel** [comment]
Hi @tremoteye we're investigating if we can find some kind of memory leak - doing this takes some time as most experiments need to run for a long time. We'll report back here with our findings. Of course, any further information or datapoints you may have would be very useful for us.

**Comment by larshesel** [comment]
Hi again.

A thing I'd forgotten about, and I apologize for that, is that eleveldb/leveldb has an internal cache which is allowed to use up to 70% of total system memory by default. This is controlled by the `leveldb.maximum_memory.percent` setting in the `vernemq.conf` file. This is likely the explanation for the memory growth you see as we've been running experiments to see if we have memory growth when this setting is set to low and we haven't been able to detect any leaks. What we see when we set the setting to, say X is a pretty stable memory usage of X + some percent for VerneMQ, sockets etc.

I hope this helps.

**Comment by larshesel** [comment]
Hi @tremoteye I hope the above explanation helped. Let us know if you run into other problems.
