### ISSUE TITLE
What is the recommended way to persist the messages?

### ISSUE THREAD

**Issue by KrishnaPG** [erlio/vernemq#49]
We need to store every message that is arriving (say, sensor readings) - what is the best way to go about it?

Clearly, having a subscriber subscribe to *all* and make it write to backend DB is not a good solution (unnecessary I/O, scalability issues .. so on). 

Any way this could be supported on the server ?

**Comment by dergraf** [comment]
Hi there,

Sure, this can be done using a custom plugin. The plugin can hook in to ``on_publish`` and store every message that gets published. Reach out to us over email if you need help developing such a plugin.
