### ISSUE TITLE
Erlang Crash during vernemq start

### ISSUE THREAD

**Issue by odx-tech** [erlio/vernemq#495]
### Environment

- VerneMQ Version: 1.1.0
- OS: ubuntu 16.06
- Erlang/OTP version (if building from source): 20

When we are starting vernemq with the following command:
sudo vernemq console

we are getting the following error
(VerneMQ@127.0.0.1)1> [os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_terminated,vmq_server,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,vmq_server,shutdown})

Crash dump is being written to: /var/log/vernemq/erl_crash.dump...done

Any reason for this ?Previously it was working fine.

**Comment by larshesel** [comment]
1.1.0 is not Erlang/OTP 20 compatible. Try to upgrade to 1.1.1 and clean out your old build (`rm -rf _build`) and try to build a release again with `make rel`.
