### ISSUE TITLE
Trying to build VerneMQ for a custom ARM board with Yocto

### ISSUE THREAD

**Issue by slavslavov** [erlio/vernemq#498]
- VerneMQ Version: 1.1.1 (or the latest master)
- OS: Custom Linux image build with Yocto for i.MX6
- Erlang/OTP version (if building from source): 20

I have no experience with Erlang

I am trying to build VerneMQ for a custom Linux OS with Yocto. Tried adding a recipe in Yocto and cross compiling on my host machine (64 bit running Fedora 25) without success. The issue is some of the C  Makefiles (syslog for example) use Erlang commands to set the LINK Directory and it is set to the host (x86_64) and not the target (ARM 32).

I saw you have built it for Raspberry Pi and decided to try to build on the board using the rpi32 configuration. So I created an Yocto development image with all development tools and libraries in it. I successfully compiled and installed Erlang 20. But when I try to compile VerneMQ (running "make rpi32") I get this error at some point:

===> Compiling epgsql
_build/default/lib/epgsql/src/epgsql_fdatetime.erl:110: Warning: ambiguous call of overridden auto-imported BIF floor/1
 - use erlang:floor/1 or "-compile({no_auto_import,[floor/1]})." to resolve name clash

===> Compiling vernemq_dev
===> Compiling eredis
===> Compiling vmq_ql
===> Running neotoma...
ln: target '_build/default/lib/' is not a directory: No such file or directory
===> Hook for compile failed!

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1

**Comment by larshesel** [comment]
I don't believe the rpi32 branch is currently working (also not on rpi). There's an effort to try to get general ARM support for VerneMQ in this issue #461, but I think it has stalled.

**Comment by slavslavov** [comment]
@larshesel Thanks for your prompt reply. If there is any progress in that other issue, I am quite happy to participate or at least test on an ARM32 board.

**Comment by larshesel** [comment]
That would be great, though looking closer that issue is really about ARM64 support,... I just tried out the rpi32 build on rpi3 and it gives the same error you had, so it's current state is just not very good. Unfortunately it's not a focus for us to repair it, so it probably has to wait for either someone to contribute time to fix it. Sorry for not being of more help here.

**Comment by slavslavov** [comment]
Is it possible to identify the tag/branch/commit which was building on Raspberry Pi?

**Comment by larshesel** [comment]
You'd have to go back to see when the target was introduced and work your way forward from there. Some kind of binary search would likely be the most efficient. I guess. But my guess is that it's likely quite a long time since it's been working properly.

Btw, not having proper CI for rpi/ARM is one of the reasons why we haven't spent time trying to keep it working.

**Comment by slavslavov** [comment]
I was able to build version 0.14.2 with Erlang 18.3 for ARM32. I tried different combinations of Erlang and VerneMQ versions but this was the only one that succeeded. 

It might be possible to use QEMU to emulate ARM on Intel architecture. I'll see if I can get more information on this.

**Comment by slavslavov** [comment]
The link below has a step-by-step tutorial how to run a raspbian image with quemu. Tested it and it works fine.
https://azeria-labs.com/emulate-raspberry-pi-with-qemu/

Another approach is listed here:
https://wiki.debian.org/RaspberryPi/qemu-user-static

**Comment by larshesel** [comment]
You could try this branch to see if it works for you: https://github.com/larshesel/vernemq/tree/fix-rpi32-build

I might try to get that merged into master one of the following weeks.

**Comment by slavslavov** [comment]
Thanks @larshesel ! I was able to build it with Erlang 20 on our ARM32 board. We'll test it tomorrow and will let you know the results.

**Comment by slavslavov** [comment]
Tested the fix-rpi32-build on our ARM32 boards and it worked as expected. Thanks again.
