### ISSUE TITLE
Last Will published late

### ISSUE THREAD

**Issue by ertanden** [erlio/vernemq#50]
Hi,

When I abruptly disconnect my client, VerneMQ sends the Last Will message a little late, like more than a minute later.

The disconnect is immediate, I think the "last will" should be sent immediately. Is there a configuration for this?

Thanks.

**Comment by dergraf** [comment]
Hi there,

This looks like VerneMQ isn't getting the TCP close right after abruptly disconnecting the client, and fires the last will either after the TCP or MQTT keepalive timeouts.

Can you verify using netstat that your connection is 'really' in closed  state?

**Comment by ertanden** [comment]
In Chrome browser with Eclipse Paho JavaScript 1.0.1, I close the browser tab, which immediately closes the connection.

I can say that with other brokers (hivemq, emqttd), this works as expected. But with VerneMQ it does not.

**Comment by dergraf** [comment]
Ohhh.. your connecting via Websockets..  I've checked and indeed this is a bug.  Thanks for reporting! Will be fixed ASAP.

**Comment by dergraf** [comment]
should be fixed in 0.12.0
@ertanden can you test with 0.12.0 release?

**Comment by dergraf** [comment]
I close this for now. Feel free to reopen it if required.
