### ISSUE TITLE
Memory fragmentation due to binary allocator leads to OOM.

### ISSUE THREAD

**Issue by imamitjain** [erlio/vernemq#501]
### Environment

- VerneMQ Version: 1.1
- OS: Ubuntu 16.04 64-bit
- Erlang/OTP version (if building from source): Ubuntu repo (Erlang/OTP 20)

We are building Android GCM fallback service where some set of server threads publish ~10KB of notification (QoS 1) in each user's topic (topic size ~100B). Currently, we see 1.5K active clients with 1M vernemq queue size i.e. sessions. Client connects to same topic with clean session set to false. Our vernemq cluster has two machines with 8 Core/32 GB RAM/100 GB SSD.
We see a memory growth which eventually leading us to OOM. Upon doing some investigation, we found following
I believe, binary allocator is contributing to memory fragmentation. 
```
(mqtt@10.0.17.196)4> lists:keysort(2, [{A, B/(1024.0 *1024 * 1024)} || {A, B}<- recon_alloc:memory(allocated_types)]).
[{temp_alloc,0.0010986328125},
 {sl_alloc,0.013946533203125},
 {ll_alloc,0.17431640625},
 {driver_alloc,0.267852783203125},
 {std_alloc,0.3016700744628906},
 {fix_alloc,0.736602783203125},
 {ets_alloc,1.390899658203125},
 {eheap_alloc,2.8594512939453125},
 {binary_alloc,20.299102783203125}]
(mqtt@10.0.17.196)5> lists:keysort(2, [{A, B/(1024.0*1024*1024)} || {A, B}<- memory()]).
[{atom_used,4.3340306729078293e-4},
 {atom,4.621604457497597e-4},
 {code,0.009581664577126503},
 {ets,1.1171618327498436},
 {processes_used,2.875397764146328},
 {processes,2.8755118921399117},
 {binary,16.97364318370819},
 {system,18.320594273507595},
 {total,21.196106165647507}]
(mqtt@10.0.17.196)6> recon_alloc:fragmentation(max).
[{{binary_alloc,7},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9234485653534151},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2852659744},
   {mbcs_carriers_size,3089137664}]},
 {{binary_alloc,8},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9251134643941222},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2919886160},
   {mbcs_carriers_size,3156246528}]},
 {{binary_alloc,4},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9203893377135719},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2657910520},
   {mbcs_carriers_size,2887811072}]},
 {{binary_alloc,3},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9241322098169762},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2732674736},
   {mbcs_carriers_size,2957017088}]},
 {{binary_alloc,1},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9278476733791667},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2523781776},
   {mbcs_carriers_size,2720038912}]},
 {{binary_alloc,2},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9336210295008054},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2602139776},
   {mbcs_carriers_size,2787147776}]},
 {{eheap_alloc,8},
  [{sbcs_usage,0.999966815227185},
   {mbcs_usage,0.7149294163974357},
   {sbcs_block_size,63641536},
   {sbcs_carriers_size,63643648},
   {mbcs_block_size,431896616},
   {mbcs_carriers_size,604110848}]},
 {{binary_alloc,6},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9256598690184182},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,2143169720},
   {mbcs_carriers_size,2315288576}]},
 {{binary_alloc,5},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.9114284787690099},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,1683976840},
   {mbcs_carriers_size,1847623680}]},
 {{eheap_alloc,6},
  [{sbcs_usage,0.9999727421351162},
   {mbcs_usage,0.7078207415179188},
   {sbcs_block_size,52533864},
   {sbcs_carriers_size,52535296},
   {mbcs_block_size,335568912},
   {mbcs_carriers_size,474087424}]},
 {{eheap_alloc,1},
  [{sbcs_usage,0.9765346271421601},
   {mbcs_usage,0.7408466096798435},
   {sbcs_block_size,65586128},
   {sbcs_carriers_size,67162112},
   {mbcs_block_size,374531080},
   {mbcs_carriers_size,505544704}]},
 {{eheap_alloc,2},
  [{sbcs_usage,0.999951583274485},
   {mbcs_usage,0.7610215693209992},
   {sbcs_block_size,84099096},
   {sbcs_carriers_size,84103168},
   {mbcs_block_size,384730424},
   {mbcs_carriers_size,505544704}]},
 {{eheap_alloc,3},
  [{sbcs_usage,0.9999961929449348},
   {mbcs_usage,0.7793423446392892},
   {sbcs_block_size,75648736},
   {sbcs_carriers_size,75649024},
   {mbcs_block_size,421777184},
   {mbcs_carriers_size,541196288}]},
 {{eheap_alloc,7},
  [{sbcs_usage,0.990628441739034},
   {mbcs_usage,0.7901801420532555},
   {sbcs_block_size,64012920},
   {sbcs_carriers_size,64618496},
   {mbcs_block_size,424328304},
   {mbcs_carriers_size,537001984}]},
 {{eheap_alloc,5},
  [{sbcs_usage,0.9999586671723486},
   {mbcs_usage,0.7177138936041121},
   {sbcs_block_size,67159336},
   {sbcs_carriers_size,67162112},
   {mbcs_block_size,269516840},
   {mbcs_carriers_size,375521280}]},
 {{eheap_alloc,4},
  [{sbcs_usage,0.9999727421351162},
   {mbcs_usage,0.7964330212823276},
   {sbcs_block_size,52533864},
   {sbcs_carriers_size,52535296},
   {mbcs_block_size,402632496},
   {mbcs_carriers_size,505544704}]},
 {{ets_alloc,2},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.7282890606126188},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,148175152},
   {mbcs_carriers_size,203456512}]},
 {{ets_alloc,3},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.7479290709554679},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,152171040},
   {mbcs_carriers_size,203456512}]},
 {{ets_alloc,8},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.7518834491765984},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,152975584},
   {mbcs_carriers_size,203456512}]},
 {{ets_alloc,4},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.770265244692684},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,156715480},
   {mbcs_carriers_size,...}]},
 {{ets_alloc,5},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.753532387596432},
   {sbcs_block_size,0},
   {sbcs_carriers_size,0},
   {mbcs_block_size,...},
   {...}]},
 {{ets_alloc,6},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.7942654498402845},
   {sbcs_block_size,0},
   {sbcs_carriers_size,...},
   {...}|...]},
 {{binary_alloc,0},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.09300771385732323},
   {sbcs_block_size,...},
   {...}|...]},
 {{ll_alloc,7},[{sbcs_usage,1.0},{mbcs_usage,...},{...}|...]},
 {{ll_alloc,5},[{sbcs_usage,...},{...}|...]},
 {{std_alloc,5},[{...}|...]},
 {{std_alloc,...},[...]},
 {{...},...},
 {...}|...]
(mqtt@10.0.17.196)8> recon_alloc:average_block_sizes(max).
[{binary_alloc,[{mbcs,5458.8702940612175},{sbcs,0}]},
 {driver_alloc,[{mbcs,697.421283057067},{sbcs,0}]},
 {eheap_alloc,[{mbcs,3531.8129650194337},
               {sbcs,8254816.492307693}]},
 {ets_alloc,[{mbcs,293.20205353991247},{sbcs,0}]},
 {fix_alloc,[{mbcs,239.50840665496312},{sbcs,0}]},
 {ll_alloc,[{mbcs,3800.5709981167606},{sbcs,0}]},
 {sl_alloc,[{mbcs,482.76874138479485},{sbcs,3567646.0}]},
 {std_alloc,[{mbcs,111.18067051249895},{sbcs,655392.0}]},
 {temp_alloc,[{mbcs,65961.08108108108},{sbcs,0}]}]
```

LevelDB memory set 30% of RAM, persistent session duration to 1d. Erlang VM's settings
```
+P 2097152
-env ERL_MAX_ETS_TABLES 2097152
-env ERL_CRASH_DUMP /erl_crash.dump
-env ERL_FULLSWEEP_AFTER 0
-env ERL_MAX_PORTS 1048576
+A 64
-setcookie XXXXXX
-name mqtt@10.0.17.196
+K true
+sbt db
+sbwt very_long
+swt very_low
+sub true
+Mulmbcs 32767
+Mumbcgs 1
+Musmbcs 2047
```

Also, there is an issue with recon:bin_leak/1

```
(mqtt@10.0.17.196)1> recon:bin_leak(100).
** exception error: an error occurred when evaluating an arithmetic expression
     in function  recon:'-bin_leak/1-lc$^1/1-1-'/1 (/opt/vernemq/distdir/1.1.0/_build/default/lib/recon/src/recon.erl, line 324)

```

**Comment by ioolkos** [comment]
Thanks a lot for reporting, @imamitjain 
I see that the latest commit for recon.erl is an arithmetics fix: https://github.com/ferd/recon/commit/84bf1d4d1f9cae337a0b7039c055c18f03b87a01
Have to check the version we use, we might be on an older commit.

Other than that I'll have to go through your data carefully to maybe get an idea what's going on.

**Comment by ioolkos** [comment]
@imamitjain Do you have crashdumps btw? how and how many messages are you distributing? do you have problems while peak load? what are the biggest processes? [you seem to know the excellent 'Erlang in Anger' guide ;)] 

You could of course re-load the recon stuff in a VerneMQ console, after you have copied the latest files (from github.com/ferd/recon)

```
(VerneMQ@127.0.0.1)38> code:soft_purge(recon).
true
(VerneMQ@127.0.0.1)39> c(recon).
Recompiling /home/afa/Erlang/20vernemq/vernemq/_build/default/lib/recon/src/recon.erl
{ok,recon}
(VerneMQ@127.0.0.1)40> l(recon).
{module,recon}
(VerneMQ@127.0.0.1)41> recon:module_info().
```

**Comment by amitjain-lr** [comment]
We are publishing around 14M message daily. Right now, it seems entire publishing is going to single node (Need to work with HAProxy). However, we see similar behaviour on both nodes wrt memory increase. We publish on our system in batches mode at every 4 hours. We have not seen any issue on peak load.
I don't have crash dump right now. 

Please find top 3 processes 
```
(mqtt@10.0.17.196)2> recon:proc_count(memory, 3).
[{<0.125.0>,13819896,
  [memsup,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.364.0>,4451936,
  [{current_function,{ranch_conns_sup,loop,4}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.365.0>,642872,
  [{current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]}]
(mqtt@10.0.17.196)3> recon:info("<0.125.0>", memory_used).
{memory_used,
    [{memory,13819896},
     {message_queue_len,0},
     {heap_size,1727361},
     {total_heap_size,1727361},
     {garbage_collection,
         [{max_heap_size,#{error_logger => true,kill => true,size => 0}},
          {min_bin_vheap_size,46422},
          {min_heap_size,233},
          {fullsweep_after,0},
          {minor_gcs,0}]}]}
```
Thanks for pointing out patch for recon:bin_leak/1.

**Comment by imamitjain** [comment]
We are publishing around 14M message daily. Right now, it seems entire publishing is going to single node (need to work with HAProxy). However, we see similar behavior on both nodes wrt memory increase. We publish on our system in batch mode at every 4 hours. We have not seen any issue on peak load.

We are pro-actively killing VerneMq on 98% memory usage since we need cover for next batch of notification so don't have crash dump :-(
Please find top 3 processes 
```
(mqtt@10.0.17.196)2> recon:proc_count(memory, 3).
[{<0.125.0>,13819896,
  [memsup,
   {current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.364.0>,4451936,
  [{current_function,{ranch_conns_sup,loop,4}},
   {initial_call,{proc_lib,init_p,5}}]},
 {<0.365.0>,642872,
  [{current_function,{gen_server,loop,6}},
   {initial_call,{proc_lib,init_p,5}}]}]
(mqtt@10.0.17.196)3> recon:info("<0.125.0>", memory_used).
{memory_used,
    [{memory,13819896},
     {message_queue_len,0},
     {heap_size,1727361},
     {total_heap_size,1727361},
     {garbage_collection,
         [{max_heap_size,#{error_logger => true,kill => true,size => 0}},
          {min_bin_vheap_size,46422},
          {min_heap_size,233},
          {fullsweep_after,0},
          {minor_gcs,0}]}]}
```
Thanks for pointing out patch for recon:bin_leak/1.

**Comment by ioolkos** [comment]
OK, that process has 13 MB, so we're looking in the wrong place.

What is the batching you do, exactly? do you use QoS 0? anymore information is potentially useful. what does `vmq-admin metrics show` tell? have you setup prometheus/grafana? 

Pro-actively restarting is certainly not a solution, and we need to find what causes the memory growth.

**Comment by imamitjain** [comment]
We publish messages in one go with QoS 1. Yes, we have setup Prometheus with Grafana. You may use it, I can share credentials.
Due to this problem, we have moved to the older solution. But looking forward to resolving this issue and use it.

**Comment by larshesel** [comment]
Could we get you to test this with a build from master - we just merged a few more metrics pertaining to memory/resource usage in the VM, all of them are called something with `vm_memory`. Could you do a run where you track and graph these over time with 30s intervals or similar? Having that information might be insightful.

**Comment by amitjain-lr** [comment]
@larshesel Sure! We will do that and report here once done. 

Does every message having retained flag set to true cause an issue, here we are writing 14M messages daily?

**Comment by larshesel** [comment]
every retained message published to a unique topic will be persisted and replicated to all other nodes. Not sure if that is a problem. 14M/24h is ~162/s on average which sounds like a manageable load.

**Comment by larshesel** [comment]
Btw in the first post you mention you think it has to do with the binary allocator causing memory fragmentation. What makes you say that?

**Comment by amitjain-lr** [comment]
Very low of mbcs_usage under binary_alloc
```
{{binary_alloc,0},
  [{sbcs_usage,1.0},
   {mbcs_usage,0.09300771385732323},
   {sbcs_block_size,...},
```

**Comment by larshesel** [comment]
ok - never had to look at the allocators in that detail before.

I think it would be good to go though section 7.3 of https://s3.us-east-2.amazonaws.com/ferd.erlang-in-anger/text.v1.1.0.pdf and report what you get with `recon_alloc:memory(usage)` and `recon_alloc:memory(allocated)` etc to get some more clues.

**Comment by larshesel** [comment]
It looks like you have 20GB of binary memory in use (which is quite a lot) are you sure there aren't a lot of published messages sitting in the offline queue for clients that are not offline?

**Comment by amitjain-lr** [comment]
I need to monitor on queue size. If it helps, we have set max offline messages to 10, max message size around 100KB and generally push 5-6 messages per user per day with session persistent set to 1d.

Difference between allocated and used binary memory is of 3G and still growing concerns us.

**Comment by ioolkos** [comment]
One thing I wonder about is the high number of dropped messages in the stats you posted.

**Comment by amitjain-lr** [comment]
In our service, we are publishing messages to our entire Android user base. Some of the users even don't have the persistent session at the time we publish that's why drop number is big. To overcome this issue (partially), we are setting retained message flag to every message in the system.
I think this can be solved once we have a stable cluster.

**Comment by larshesel** [comment]
Have you made any progress with this? Any new findings?

**Comment by larshesel** [comment]
Closing this for now.
