### ISSUE TITLE
Unreachable node cleanup in a cluster

### ISSUE THREAD

**Issue by concurrent88** [erlio/vernemq#503]
With two nodes in a cluster, if one of the node falls off the network, we see that, after about 60 secs it is shown as false in the cluster status. But can we configure it to fall off the cluster automatically after some time? Is that possible/ configurable? Or do we need to make it leave the cluster ourselves?

**Comment by larshesel** [comment]
Cluster leave is on operation that has important consequences and it's therefore not automatic, see also http://vernemq.com/docs/clustering/. So yes, you need to issue the cluster leave command yourselves to get out of a netsplit situation.

**Comment by concurrent88** [comment]
That's great, thanks for the quick response!
