### ISSUE TITLE
Too many Webhook cache misses 

### ISSUE THREAD

**Issue by wingsofovnia** [erlio/vernemq#505]
### Environment

- VerneMQ Version:  1.1.1
- OS: Ubuntu 16.0.4 (VirtualBox on MacOS)
- Erlang/OTP version (if building from source): N/A

### Expected behavior

- VerneMQ auth-z and auth-d users as expected
- VerneMQ caches {result: ok} responses according to Cache-Control given in the response
- VerneMQ uses cached auth-z/auth-d response for the same user next time

### Actual behaviour

- VerneMQ auth-z and auth-d users as expected
- VerneMQ misses on retrieving cached auth-z/auth-d response and redo webhook call for the same user

```
root@vernemq:/home/superuser# vmq-admin webhooks cache show
+-------+----------------------------------------------------------+----------------+-----+
| stat  |                         endpoint                         |      hook      |value|
+-------+----------------------------------------------------------+----------------+-----+
|misses |http://192.168.0.11:8080/api/auth/vernemq/auth_on_register|auth_on_register| 24  |
|entries|http://192.168.0.11:8080/api/auth/vernemq/auth_on_register|auth_on_register| 5  |
+-------+----------------------------------------------------------+----------------+-----+
```

In fact, there are a couple of entries but I'm not sure why they work and others don't. 

Webhook curl:
```
$ curl -d '{"peer_addr":"192.168.0.11","peer_port":51409,"mountpoint":"","client_id":"iovchynnikov220503239","username":"root","password":"root","clean_session":true}' -H "Content-Type: application/json" -X POST http://192.168.0.11:8080/api/auth/vernemq/auth_on_register -v
*   Trying 192.168.0.11...
* TCP_NODELAY set
* Connected to 192.168.0.11 (192.168.0.11) port 8080 (#0)
> POST /api/auth/vernemq/auth_on_register HTTP/1.1
> Host: 192.168.0.11:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 155
>
* upload completely sent off: 155 out of 155 bytes
< HTTP/1.1 200
< Cache-Control: max-age=86400 # !!!! SET
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Wed, 06 Sep 2017 21:43:15 GMT
<
* Connection #0 to host 192.168.0.11 left intact
{"result":"ok"}
```

Config:
```
allow_anonymous = off
plugins.vmq_passwd = off
plugins.vmq_acl = off
plugins.vmq_webhooks = on
vmq_webhooks.terminal_auth_on_register.hook = auth_on_register
vmq_webhooks.terminal_auth_on_register.endpoint = http://192.168.0.11:8080/api/auth/vernemq/auth_on_register
vmq_webhooks.terminal_auth_on_publish.hook = auth_on_publish
vmq_webhooks.terminal_auth_on_publish.endpoint = http://192.168.0.11:8080/api/auth/vernemq/auth_on_publish
vmq_webhooks.terminal_auth_on_subscribe.hook = auth_on_subscribe
vmq_webhooks.terminal_auth_on_subscribe.endpoint = http://192.168.0.11:8080/api/auth/vernemq/auth_on_subscribe

// other are default or irrelevant
```

**Comment by larshesel** [comment]
Are you always using the same client-id? Note from the documentation:

```
All data passed to these hooks is used to look if the call is in the cache, except in the case of the auth_on_publish where the payload is omitted.
```

Which means for the `auth_on_register` hook all of peer host/port, client-id, username, password and clean-session flag has to be the same for the cache entry to be found

**Comment by wingsofovnia** [comment]
@larshesel "Are you always using the same client-id? ...host/port, client-id, username, password and clean-session flag..."
I do. I tested with MQTT.fx just by clicking connect/disconnect with no val changes. I also noticed that each connect generates 2 calls: one entires cache record, other misses.
For example, 7 connect/disconnect cycles will cause this:
```
root@vernemq:/home/superuser# vmq-admin webhooks cache show
+-------+-----------------------------------------------------------+----------------+-----+
| stat  |                         endpoint                          |      hook      |value|
+-------+-----------------------------------------------------------+----------------+-----+
|misses |http://192.168.0.107:8080/api/auth/vernemq/auth_on_register|auth_on_register|  8  |
|entries|http://192.168.0.107:8080/api/auth/vernemq/auth_on_register|auth_on_register|  8  |
+-------+-----------------------------------------------------------+----------------+-----+
```

**Comment by wingsofovnia** [comment]
Any ideas?

**Comment by larshesel** [comment]
Sorry, haven't had time to look into this yet

**Comment by larshesel** [comment]
ok - thinking a bit about this I would expect that this is because the cache entry for the `auth_on_register` hook contains the client port which likely changes on each invocation.

I think I remember considering this back when we implemented the webhooks cache, and I think it had to do with the original requirements where the clients had to always use the same port (due to firewalls etc), but I'm not completely sure.

Do you see this behaviour with other hooks, like auth_on_publish?

**Comment by kedarundale17** [comment]
> Are you always using the same client-id? Note from the documentation:
> 
> ```
> All data passed to these hooks is used to look if the call is in the cache, except in the case of the auth_on_publish where the payload is omitted.
> ```
> 
> Which means for the `auth_on_register` hook all of peer host/port, client-id, username, password and clean-session flag has to be the same for the cache entry to be found

As per documents the hook cache entries are not actively disposed after expiry.
The memory consumption will keep on increasing until a point where we might face OOM. 
FYI
As per my understanding, hook data means client id, username, password,peer address, peer host. 
In my case the client id , username, password remain same without any change.
Few doubts : 
1. Does a new entry get saved in cache when the peer host / peer port changes, when the client reconnects ?
2. Does "not actively disposed" mean the cache entries are NEVER deleted/evicted from in memory? 

Anything would be helpful here.
Thanks
