### ISSUE TITLE
How can we handle auth/acl in the case of clustered env?

### ISSUE THREAD

**Issue by ssivakumar-wisilica** [erlio/vernemq#506]
### Environment

- VerneMQ Version: Latest
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): NA

### Expected behavior

For clustered environment, and in cases where we need to dynamically add/revoke access to clients and modify ACLs; Which one's is the preferred authentication method? Going through the docs, it seems that only DB authentication can solve this scenario!
Is this possible with the file based auth as well, if I put the pass/acl files in a clustered FS, and give the same file mounts to each node in vernemq.conf?

I suggest grouping common set of configurations which should be same across nodes in a clustered environment in a separate file/store, and have it sync between nodes, i.e. a change in one node should sync it across to all cluster joined nodes. Right now all configurations seem to be in one single file, which needs to be manually synced.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by dergraf** [comment]
Hi there.
A clustered FS could be used for syncing acl and passwd files.. however, personally I'd prefer a DB backed solution in this case. 
Regarding the single file issue... you could use some external templating to build the `vernemq.conf` this way you could separate shared from non-shared configuration. Or just use a solution like Ansible, Chef, or Puppet to configure your VerneMQ nodes.
