### ISSUE TITLE
Automatic discovery of cluster nodes

### ISSUE THREAD

**Issue by ertanden** [erlio/vernemq#51]
Is it possible to automatically discover cluster nodes?

Think about a setup using Amazon Auto Scale, which can automatically instantiate new instances. It would be nice to somehow auto-discover the cluster and join it.

**Comment by dergraf** [comment]
If it is possible to configure a post-startup script as well as a post-teardown script you should be able to do that.

**Comment by ertanden** [comment]
But wouldn't I need to "know" at least one of the node's name, which shall already be running?

Maybe multicast can be used for auto-discovery, or S3 buckets can be used on AWS since there's no multicast...

**Comment by dergraf** [comment]
my recommendation would be to keep a spare VerneMQ node around. This could be useful for cluster diagnosis and analytics.. and in this could also serve as a discovery node.

**Comment by ertanden** [comment]
Well, that's not much of an option for me. Moreover, that spare node will be a single point of failure.

For example look at another product called Hazelcast supports AWS discovery by checking EC2 tags etc. Seems like a nice feature:
http://docs.hazelcast.org/docs/3.3/manual/html/ec2autodiscovery.html


By the way, is there a way to register other nodes with a plugin? If there is maybe I can work on implementing such a plugin for AWS discovery...

**Comment by dergraf** [comment]
interesting.. this could certainly build using a plugin. 
the plugin could use the following functions to register and unregister itself with the cluster. 
https://github.com/erlio/vmq_server/blob/master/src/vmq_server_cmd.erl#L28-L34

**Comment by wrouesnel** [comment]
Doing this with consul would also be nice. That supports a DNS SRV interface, so it would be nice on startup to be able to just pass in the DNS SRV record to lookup for discovery nodes.

**Comment by dergraf** [comment]
Yeah a DNS based solution would be great. But again I think for now this should be part of a plugin.

**Comment by dergraf** [comment]
as an alternative approach you could theoretically do something using ``-eval`` at startup. Using a plugin would be much cleaner, but this should work. Create a custom ``vm.args`` file in ``_build/default/rel/vernemq/etc`` and add the following line:

    -eval "vmq_server_cmd:node_join(list_to_atom(element(4, hd(inet_res:lookup(\"_xmpp-client._tcp.jabber.org\", in, srv)))))"

of course replace ``_xmpp-client._tcp.jabber.org`` whith your own DNS name. 

decomposed this is what happens:

    // get all SRV records
    Var1 = inet_res:lookup("_xmpp-client._tcp.jabber.org", in, srv") 
    // get the first SRV record
    Var2 = hd(Var1)
    // get the last element of the tuple containing the SRV name string
    Var3 = element(4, Var2)
    // convert SRV name string to atom type
    Var4 = list_to_atom(Var3)
    // internal API call to join a cluster
    vmq_server_cmd:node_join(Var4)

Now of course you must make sure that the SRV name contains the proper name of a node.

As I said, I would create a plugin, this approach can work, but it won't if any of the above calls fails. Hope this helps.

**Comment by dergraf** [comment]
I close this for now. Feel free to reopen it if required.

**Comment by hoangleanhtu** [comment]
Hi Andre,

Do you create plugin to join cluster nodes automatically?

**Comment by dergraf** [comment]
We don't have this on our roadmap currently. 
In https://github.com/erlio/vernemq/issues/54 we keep track of the whole VerneMQ on Docker discussion, which will eventually require some sort of autoscaling built-in.

But for now you'd have to build it yourself, unless you'd consider to sponsor this feature (please get in touch over email) ;)

**Comment by hoangleanhtu** [comment]
Sorry for late response, I'm too busy in these dates.

Currently I do it manually.

I'll try to contribute if possible.

Thank you very much.
