### ISSUE TITLE
Crash subscribing to topics after upgrade from 1.1.0

### ISSUE THREAD

**Issue by codeadict** [erlio/vernemq#513]
### Environment
- VerneMQ Version: 1.2.0 and 1.1.1 Binary packages
- OS: Debian GNU/Linux 8 (jessie) inside Docker.

### Expected behavior

- Client should be able to subscribe to topics.

### Actual behaviour

- When I try to subscribe to any topic, the server crashes. Looks like `vmq_reg_trie` is calling `vmq_topic:contains_wildcard()` that cannot be found.

**Traceback**

```
2017-10-02 16:22:26.549 [error] <0.323.0> CRASH REPORT Process vmq_reg_trie with 0 neighbours exited with reason: call to undefined function vmq_topic:contains_wildcard([<<"mytopic">>]) in gen_server2:terminate/3 line 995
2017-10-02 16:22:26.549 [error] <0.315.0> Supervisor vmq_reg_sup had child {reg_view,vmq_reg_trie} started with vmq_reg_trie:start_link() at <0.323.0> exit with reason call to undefined function vmq_topic:contains_wildcard([<<"mytopic">>]) in context child_terminated
2017-10-02 16:22:26.551 [error] emulator Error in process <0.764.0> on node 'VerneMQ@172.17.0.3' with exit value:
{undef,[{vmq_topic,contains_wildcard,[[<<"mytopic">>]],[]},{vmq_reg_trie,initialize_trie,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,287}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{plumtree_metadata,fold_it,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata.erl"},{line,130}]},{vmq_reg_trie,'-init/1-fun-1-',1,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,130}]}]}
2017-10-02 16:22:26.551 [error] <0.315.0> Supervisor vmq_reg_sup had child {reg_view,vmq_reg_trie} started with vmq_reg_trie:start_link() at <0.763.0> exit with reason call to undefined function vmq_topic:contains_wildcard([<<"mytopic">>]) in context child_terminated
2017-10-02 16:22:26.553 [error] emulator Error in process <0.767.0> on node 'VerneMQ@172.17.0.3' with exit value:
{undef,[{vmq_topic,contains_wildcard,[[<<"mytopic">>]],[]},{vmq_reg_trie,initialize_trie,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,287}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{plumtree_metadata,fold_it,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata.erl"},{line,130}]},{vmq_reg_trie,'-init/1-fun-1-',1,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,130}]}]}
2017-10-02 16:22:26.553 [error] <0.315.0> Supervisor vmq_reg_sup had child {reg_view,vmq_reg_trie} started with vmq_reg_trie:start_link() at <0.766.0> exit with reason call to undefined function vmq_topic:contains_wildcard([<<"mytopic">>]) in context child_terminated
2017-10-02 16:22:26.555 [error] emulator Error in process <0.770.0> on node 'VerneMQ@172.17.0.3' with exit value:
{undef,[{vmq_topic,contains_wildcard,[[<<"mytopic">>]],[]},{vmq_reg_trie,initialize_trie,2,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,287}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{plumtree_metadata,fold_it,3,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/plumtree/src/plumtree_metadata.erl"},{line,130}]},{vmq_reg_trie,'-init/1-fun-1-',1,[{file,"/opt/vernemq/distdir/1.2.0/_build/default/lib/vmq_server/src/vmq_reg_trie.erl"},{line,130}]}]}
```

**Comment by dergraf** [comment]
@larshesel are you able to reproduce this bug?

**Comment by codeadict** [comment]
I suspect it can be the Debian package, will compile it and test to verify my assumption @dergraf

**Comment by larshesel** [comment]
With a binary 1.2.0 package I couldn't reproduce this behaviour so far.

The stacktrace above indicates that this is not happening when subscribing, but when starting the vernemq node.

Can you start the vernemq node at all? If so, could you 1) show the output of `vernemq version` and 2) attach to the node and run `vmq_topic:contains_wildcard([<<"mytopic">>]).` ?

**Comment by larshesel** [comment]
aargh - I just did:

```
$ docker run -p 1883:1883 --name vernemq1 -d erlio/docker-vernemq
e1a7fd0cf20a6b415a541d23f1343459b372b7dc73eba74803a19c7bbd020e7a
$ docker exec vernemq1 vernemq version
0.15.2
```

0.15.2? How did that happen? Obviously, something went wrong when I pushed the new release and generated the docker images, but what? @dergraf any ideas how to solve this?

**Comment by larshesel** [comment]
It seems it's only the `latest` package that's broken. If I explicitly ask for 1.2.0 I seem to get the right version:

```
$ docker run -p 1883:1883 --name vernemq1 -d erlio/docker-vernemq:1.2.0
Unable to find image 'erlio/docker-vernemq:1.2.0' locally
1.2.0: Pulling from erlio/docker-vernemq
aa18ad1a0d33: Pull complete 
fe4c2ff6f969: Pull complete 
387435b8e289: Pull complete 
1c9a0e937c53: Pull complete 
f77d366b3622: Pull complete 
f1dbe599be90: Pull complete 
5ab6342de1c3: Pull complete 
9c84776d747d: Pull complete 
Digest: sha256:135afa33c72d2c9156f042f340a9733a1e4ab457df822e0b04906ff3f949a6fc
Status: Downloaded newer image for erlio/docker-vernemq:1.2.0
bfbd5c517e6846477ab6a2d25de3453148b88137b606bf43e2aa5cd980860b7b
20.1 lhc@algol ~/.../package/packages (master) $ docker exec vernemq1 vernemq version
1.2.0
```

**Comment by larshesel** [comment]
So, I don't really know what I'm doing when working with docker - but apparently my local latest tag was pointing to some old package. I could update it with `docker tag erlio/docker-vernemq:1.2.0 erlio/docker-vernemq:latest` and afterwards I could just run `docker run -p 1883:1883 --name vernemq1 -d erlio/docker-vernemq`. So maybe my finding above with `0.15.2` was just a red herring.

In any case it would be great if you can reproduce this with the binary 1.2.0 package.

**Comment by codeadict** [comment]
It happens to me with 1.1.1 and 1.2.0, I have my own docker image, not the Erlio one. I can provide more information for you to debug, the server starts and I can publish to it but when i subscribe then it crashes

**Comment by larshesel** [comment]
Do you use our debian packages or do you compile vernemq yourself? Is it reproducible if you delete the persisted data? (maybe move it instead of deleting). I could not reproduce this when I installed 1.2.0 on a vagrant debian jessie machine... :/

**Comment by codeadict** [comment]
The issue was https://github.com/erlio/vernemq_dev not being updated and having a different vmq_topic.erl from the one in `vernemq/apps/vmq_commons`. This was causing the file not being loaded in the Erlang VM when I had custom plugins. Is solved now for me but will probably bite other folks with custom plugins. I'm closing this issue now but will open a proposal to basically remove `vmq_commons` from the vernemq core and move the code there to the `vernemq_dev` repo and reuse the same code for the server core and third-party plugins. `vernemq_dev` needs to be tagged along with VerneMQ versions in order to avoid incompatibilities.

**Comment by codeadict** [comment]
Props to @larshesel for the help debugging that. 🎉
