### ISSUE TITLE
Clarify/fix plugin development flow

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#514]
Currently some developers use `vernemq_dev` as a dependency when developing plugins. `vernemq_dev` contains a copy of `vmq_topic.erl` which is also distributed as part of VerneMQ itself and this can lead to issues like #513 as `vernemq_dev` contained an old copy of `vmq_topic.erl`.

This should be fixed somehow as it's not clear to most people out there what is the 'right' way to build plugins.

In general there are two possibilities for building plugins:

1. Build plugins separetely from VerneMQ without any dependencies or with something like `vernemq_dev` which contains a minimal & official set of helper functions as well as hook behaviours. The advantages of this approach is easy CI and fast build times. The disadvantages is one is limited to only the functionality exposed via `vernemq_dev`.

2. Build plugins 'inside' vernemq (eg. put it into `./apps/pluginname`) and build it as part of VerneMQ (and then package up the result as a separate package). This has the benefit that one has access to everything, but as we don't expose a public API it's impossible to developers to know what it's OK to use to avoid breaking changes in the future.

I think we should move to support option 1 officially and document the public functions (not this does not exclude building plugins using option 2). Challenges here are:

- Currently `vernemq_dev` is broken as it contains some of the same files as in VerneMQ itself. I don't see that we can remove a file like `vmq_topic.erl` from within VerneMQ as that would break plugins relying on `vmq_topic:unword/1` from working on future versions of VerneMQ. For a case like that I would keep `vmq_topic.erl` in VerneMQ and create a new api in `vernemq_dev` exposing the public API (in the case of `unword` just calling into `vmq_topic`).

- Changing `vernemq_dev` by removing `vmq_topic` and doing other changes may prevent existing plugins from compiling and code would require changes to the plugin code. Note this should not break plugins that already work - they would keep working. This would suck, but I think this would be the long term best solution.

Thanks to @codeadict for surfacing this issue and getting a
discussion started.

Comments? /cc @dergraf @ioolkos

**Comment by codeadict** [comment]
heh mentioned the wrong guy, its all lower @codeadict

**Comment by codeadict** [comment]
My approach would be: keep `vernemq_dev` updated and separated from the main repo and used as a dependency for both VerneMQ server and people developing plugins. `vernemq_dev` can be tagged with the same version as VerneMQ and this way the incompatibilities can be avoided.

**Comment by ioolkos** [comment]
Well... I'd say we just want the best plugin system. So that the best people can develop the best plugins for the best broker.
With the best programming languages (Elixir, Erlang, Lua). Best of the worlds.

Any objections?

**Comment by larshesel** [comment]
Hard to argue with that goal @ioolkos 🚀

**Comment by larshesel** [comment]
@codeadict the latest release (1.2.1) now depends on the `vernemq_dev` dependency... I still haven't thought much about tags on `vernemq_dev` - it is kind if implicit as the dependency is written in the rebar.lock file for any vernemq version... If you have a good (and easy) proposal then I'm all ears :)
