### ISSUE TITLE
Can't connect to broker when broker is in auth-on-subscribe or auth-on-register state (webhook)

### ISSUE THREAD

**Issue by acsdkquery** [erlio/vernemq#515]
### Environment

- VerneMQ Version: sudo vernemq version
1.1.0
- OS: Ubuntu
- Erlang/OTP version (if building from source):

### Expected behavior
Can't connect to broker when broker is in auth-on-subscribe or auth-on-register state. 
For example
1. Clint id (CID1) is subscribing to broker (webhook authentication is enabled for auth-on-subscribe or auth-on-register)
2. calling webhook endpoint for auth-on-register and got success return.
3. now calling auth-on-subscribe...
4. before responding to the auth-on-subscribe for CID1, in the endpoint , we try to connect to the same broker with different client (CID2)
5. Here its the issue, CID2 is not connecting and getting timeout.

Note: if we try to connect to different broker its getting success. if we try to connect to the same broker where webhook enabled, issue is seen. And we not trying to subscribe/publish, when try to connect to the broker only we seeing this.

we have enabled debug trace for CID2, but no traces on broker.

### Actual behaviour

CID2 should get the mqtt success connection atleast.

**Comment by larshesel** [comment]
This sounds to me like your webhook endpoint is not longer replying to the `auth_on_register` hook when client number 2 tries to connect. Can you verify that your endpoint is working?

**Comment by acsdkquery** [comment]
Thanks for your feedback, auth_on_register hook is working fine and its not invoking for CID2

**Comment by larshesel** [comment]
Can you, before connecting with client 2 do:

```
vmq-admin trace client client-id=<client-id-of-client2>
```

And show what the output is? (remember to substitute in the correct client id of CID2)

**Comment by acsdkquery** [comment]
Before connecting with CID2 to broker,
ubuntu@:~$ sudo vmq-admin trace client client-id=CID2
No sessions found for client "CID2"

**Comment by larshesel** [comment]
right - and what happens when you connect with CID2? Nothing?

**Comment by acsdkquery** [comment]
Nothing,

**Comment by larshesel** [comment]
Are you able to make a TCP connection to VerneMQ at all then? Are there any errors in the logs?

**Comment by acsdkquery** [comment]
Yes, TCP is fine, with CID1 am subscribing outside of broker and its connecting fine, No error logs in trace,
ubuntu@~$ sudo vmq-admin trace client client-id=CID2
No sessions found for client "CID2"

**Comment by acsdkquery** [comment]
This is the error in endpoint,
Client ID:: CID2
Connecting to broker: tcp://52.90.228.166:1883
reason 0
msg MqttException
loc MqttException
cause java.net.SocketTimeoutException: connect timed out
excep MqttException (0) - java.net.SocketTimeoutException: connect timed out
MqttException (0) - java.net.SocketTimeoutException: connect timed out

**Comment by larshesel** [comment]
Are you not using webhooks http://vernemq.com/docs/plugindevelopment/webhookplugins.html?

The above looks like a network reachability problem - can you check that you can connect to the port at all from where client 2 connects?

**Comment by acsdkquery** [comment]
Yes, You are correct, its because of n/w reachable issue, RCA found, Thanks much for you inputs.
