### ISSUE TITLE
Setting `listener.tcp.proxy_protocol = on` has no effect

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#516]
### Environment

- VerneMQ Version: master
- OS: debian
- Erlang/OTP version (if building from source): 20.1.1

### Expected behavior

When setting listener.tcp.proxy_protocol = on I expect it to apply for all tcp listeners.

### Actual behaviour

It seems it has no effect. If I do a trace on the vmq_ranch_proxy_protocol module it is never called when connecting to the listener. Also I can connect with an non-proxy aware client...

**Comment by ioolkos** [comment]
Context from the docs: 
"To enable the PROXY protocol for tcp listeners use `listener.tcp.proxy_protocol = on` or for a specific listener use `listener.tcp.LISTENER.proxy_protocol = on`."

The latter works, I suppose? but not the configure all switch, apparently.

**Comment by larshesel** [comment]
the latter works. It's just the general 'default' that doesn't work.
