### ISSUE TITLE
Plugin enabling documentation is wrong

### ISSUE THREAD

**Issue by anonymouse64** [erlio/vernemq#518]
### Environment

- VerneMQ Version: 1.1.1
- OS: CentOS
- Erlang/OTP version (if building from source): N/A

### Expected behavior

Docs are wrong when talking about how to enable plugins from the `vernemq.conf` file. They say that the correct way to enable a plugin is like this:

```
plugins.vmq_passwd = PathToPlugin
```

The correct spec is for mentioned in the changelog:

```
plugins.myplugin = on 
plugins.myplugin.path = /path/to/plugin
```

Note the missing `.path` in the docs version.

**Comment by anonymouse64** [comment]
Specifically the docs here : https://vernemq.com/docs/configuration/plugins.html

**Comment by ioolkos** [comment]
@anonymouse64 thanks for pointing this out, and apologies in case you ran into friction/frustration. 

I'll assign myself to clean up the doc. Maybe some more stuff needs and update in the plugin docs.

**Comment by codeadict** [comment]
I found the same issue but figured it out myself looking at the code and forgot to report heh :)

**Comment by ioolkos** [comment]
@codeadict @anonymouse64 thanks a lot guys! I fixed the doc as suggested.
