### ISSUE TITLE
User proxy_protocol with websocket 1883 port

### ISSUE THREAD

**Issue by funwun** [erlio/vernemq#524]
### Environment

- VerneMQ Version: 1.2.0
- OS: alpine
- Erlang/OTP version (if building from source): 19

### Expected behavior

When I open proxy_protocol of aws elb, and set the config:
```
listener.tcp.default.proxy_protocol = on
listener.tcp.default = 0.0.0.0:1883
listener.ws.default.proxy_protocol = on
listener.ws.default = 0.0.0.0:1884
```
The 1883 mqtt is work fine, but 1884 ws is not.
Disable aws elb proxy_protocol and remove listener.ws.default.proxy_protocol = on, the ws works fine.

there is no error log, but this warning:

```
2017-10-13 01:33:21.438 [warning] <0.341.0> Transport option {ip,{0,0,0,0}} unknown or invalid.
2017-10-13 01:33:21.438 [warning] <0.341.0> Transport option {port,1884} unknown or invalid.
```

**Comment by ioolkos** [comment]
Thanks @funwun.
what is the conclusion here? 
the proxy protocol should work over WebSocket, right? /cc @dergraf @larshesel

**Comment by funwun** [comment]
Proxy protocol can’t work with websocket

**Comment by larshesel** [comment]
It should work - haven't had time to look at it, though

**Comment by larshesel** [comment]
@funwun could you do a wireshark trace at what arrives on port 1884 on the broker when connecting with websockets + proxy?

**Comment by larshesel** [comment]
Hi @funwun any news here?
