### ISSUE TITLE
log client connects/disconnects

### ISSUE THREAD

**Issue by trehn** [erlio/vernemq#529]
Maybe I'm missing something, but is there no way for me to find out when a specific client connected and disconnected?

Even with `log.console.level = debug` I don't see anything that tells me which clients are connecting and disconnecting, just this:

```
[debug] <0.645.0>@vmq_queue:state_change:913 transition from offline --> online because of add_session
```

I previously used EMQ and subscribed to `$SYS/brokers/+/clients/+/+` so I would get messages for each connect/disconnect event. That was helpful for tracking active vs. inactive clients without client cooperation.

I understand that when you have a ton of clients, it may not be desirable to log such events, but at modest scale or when developing, it can be very helpful.

**Comment by trehn** [comment]
This was previously mentioned in #458, but I dont always know the client ID in advance for `vmq-admin trace client`.

**Comment by larshesel** [comment]
This doesn't exist because of the reasons you mention. You could, however, make a small plugin which logs in the `auth_on_register` and `on_client_gone`/`on_client_offline` hooks and this should do what you want I think.

**Comment by MattyCZ** [comment]
Hi, I am solving a similar issue. I've written a small plugin as you are suggesting, but can I somehow change the target log file to log into? I can't find any way how to configure my own plugin. Thanks in advance
