### ISSUE TITLE
how to reload Reids acl?

### ISSUE THREAD

**Issue by mao2080** [erlio/vernemq#538]
### Environment

- VerneMQ Version:
- OS:Linux
- Erlang/OTP version (if building from source):

### Expected behavior

Now I authorization using the Reids, but there is a problem：We define one publish_acl [{"pattern":"client/device/json/0"}], we can pusblish the "client/device/json/0" topic，now we change the publish_acl to [{"pattern":"client/device/json/2"}] , If you don't reconnect the MQTT-Server(VerneMQ), we 
still can pusblish the "client/device/json/0" topic。

### Actual behaviour

we cannot pusblish the "client/device/json/0" topic.

Is there a way to make the publish_acl work right now?

**Comment by ioolkos** [comment]
Hi @mao2080 thanks for asking, I guess this intended behaviour though with Redis? Any publish will check the ACLs live.

**Comment by mao2080** [comment]
@ioolkos thanks for answer，but now it doesn't work. If the client reconnect the MQTT-Server(VerneMQ) the ACLs worked well. 
Is there a problem with the vernemq.conf?

**Comment by mao2080** [comment]
The vernemq.conf description is:
## set the acl reload interval in seconds, the value 0 disables
## the automatic reloading of the acl file.
## 
## Default: 10
## 
## Acceptable values:
##   - an integer
vmq_acl.acl_reload_interval = 10

It looks like only use the vmq_acl.acl_file？How abort the redis acl reload？

**Comment by larshesel** [comment]
Hi - is this still an issue?

If so could you provide a bit more information? It seems you're using both the `vmq_acl` plugin but you also mention `redis` which is available via the `vmq_diversity` plugin. Note that the `vmq_acl` plugin and the `vmq_acl.acl_reload_interval` has nothing to do with the behaviour of the `vmq_diversity` `redis` functionality.

**Comment by larshesel** [comment]
Also note this quote from https://vernemq.com/docs/configuration/db-auth.html

```
Note: the database integrations will cache the ACLs when the client connects avoiding expensive database lookups for each publish or subscribe message. The cache entries are evicted when the client disconnects.
```

So this means ACLs are fetched from Redis when a client connects and are not refreshed until the client reconnects. If you need a different behaviour you'd need a custom plugin.

**Comment by mao2080** [comment]
@larshesel ok,thanks
