### ISSUE TITLE
Confuse about configuration to make it just work

### ISSUE THREAD

**Issue by amrishodiq** [erlio/vernemq#539]
### Environment

- VerneMQ Version: 1.2.0
- OS: Centos 7
- Erlang/OTP version (if building from source): 

### Expected behavior

- Just work for a client id (with or without username and password, even anonymous) to publish a message.

### Actual behaviour

- I use mqtt-spy to connect to my Verne installation from remote computer. 

This is my config:
allow_anonymous = on
listener.tcp.default = 0.0.0.0:1883
Others are default.

I always have there logs:

```
2017-11-07 16:57:14.779 [error] <0.664.0>@vmq_mqtt_fsm:auth_on_publish:658 can't auth publish [undefined,{[],<<"bob">>},0,[<<"sembarang">>,<<"pokoknya">>],<<"terserah">>,false] due to no_matching_hook_found
2017-11-07 16:57:14.779 [warning] <0.664.0>@vmq_ranch:teardown:127 session stopped abnormally due to 'publish_not_authorized_3_1_1'
```

I don't set any hook, cause I don't understand what hook is. 
What does that log means? Am I missing a required configuration?

**Comment by dergraf** [comment]
it seems you have disabled the default vmq_acl plugin, which implements the authorization hooks required for publishing and subscribing.
the allow_anonymous=on only bypasses the authentication steps but not authorization.

**Comment by amrishodiq** [comment]
Hi Andre, thanks for the response. I will try to fix it later. But now, since I have my EMQTT up and running, I will focus on it first. I will re-visit later. Thanks anyway.
