### ISSUE TITLE
Allow non-interactive foreground launch

### ISSUE THREAD

**Issue by wrouesnel** [erlio/vernemq#54]
I'm wanting to run VerneMQ in a docker container (or as a systemd service) and the launch options aren't entirely conducive to this.

Specifically, it would be nice to force all logging to go to the console and to keep the VerneMQ process in the foreground with a non-interactive console - since both these two systems take care of log collection via that mechanism.

**Comment by dergraf** [comment]
If you install the deb or rpm package VerneMQ can be started as a systemd service.

Regarding your second thought..
I am not sure how you would do this with the Erlang VM. Moreover I am not sure if you would loose all the great benefits of runtime inspectability, realtime debugging... but as you are in a Docker container you probably don't care about such features, right?

**Comment by teodor-pripoae** [comment]
Hi,

I'm having the same problem, trying to run vernemq under a docker container. I'm running on OSX and vernemq fails to compile natively. 

Also, if I decide to use vernemq for my project, each member in our team will need to have it installed. Distributing as a docker image is easier, instead of forcing each team member to install it from source (no homebrew package available).

**Comment by dergraf** [comment]
as we're using several similar building blocks as the guys from the Riak database I am sure we can take a similar path.. Can you have a look at https://github.com/hectcastro/docker-riak and tell me if this is something you'd like to see for VerneMQ as well?

**Comment by wrouesnel** [comment]
This is the docker file I use to build Verne at the moment:
```
# Dockerfile to build MQTT

FROM debian:jessie

RUN apt-get update && apt-get install -y erlang build-essential git
RUN apt-get install -y libssl-dev

# Install VerneMQ from source
RUN git clone https://github.com/erlio/vernemq.git
WORKDIR vernemq
RUN make rel

# Move the installation to its real location
WORKDIR /
RUN mv /vernemq/_build/default/rel/vernemq /vernetmp
# Note: cleanup source code here
RUN rm -rf vernemq
RUN mv /vernetmp /vernemq

# Consul clustering
RUN apt-get install -y wget jq dnsutils

ADD vernemq.conf /vernemq/etc/vernemq.conf
ADD vernemq_consul_launch.bsh /vernemq/bin/vernemq_consul_launch.bsh

EXPOSE 1883
EXPOSE 44053
EXPOSE 51174

WORKDIR /vernemq/bin
CMD ["/bin/bash", "vernemq_consul_launch.bsh"]
```

The script there is how I'm handling auto-cluster discovery with consul:
```
#!/bin/bash
# Script to launch and cluster Verne MQ via Consul
# Depends on wget, jq and the container needs to be running as --net=host

# Query Consul for our node name
NODENAME=$(wget -O - http://localhost:8500/v1/agent/self 2> /dev/null | jq -r .Config.NodeName)

# Query Consul for a fellow VerneMQ server
SRV=$(dig +short vernemq-1883.service.consul SRV | head -n1 | cut -d' ' -f3,4)
HOST=$(echo $SRV | cut -d' ' -f2)
PORT=$(echo $SRV | cut -d' ' -f1)

# Assign the nodename we need
sed -i "s:nodename.*:nodename = VerneMQ@$NODENAME:" ../etc/vernemq.conf

# Start vernemq
./vernemq start
VMQPID=$!

function graceful_stop {
    echo "Leaving cluster"
    #./vmq-admin cluster leave node=$NODENAME
    ./vernemq stop
}
trap graceful_stop EXIT

# Join the cluster
if [ ! -z $HOST ]; then
    ./vmq-admin cluster join discovery-node=$HOST:$PORT
fi

tail -f --retry ../log/error.log ../log/console.log ../log/crash.log
```

**Comment by dergraf** [comment]
@wrouesnel so is this VerneMQ docker setup working for you?

**Comment by wrouesnel** [comment]
This setup I have running on EC2 at the moment, though locally its a bit glitchy with wanting to shutdown when launched on a pseudo-tty). The part of it I don't like is those unconstrained log files - they'll fill up the disk eventually and technically need a separate rotation script.

**Comment by dergraf** [comment]
Would using syslog help with that?

**Comment by wrouesnel** [comment]
The syslog documentation was a bit sparse. And in a container no, since containers mostly emit logs to stdout/stderr and you collect them from there.

Ideally you'd be able to set everything to log to those two streams.

**Comment by dergraf** [comment]
ok. just checked VerneMQ syslog isn't currently working... 

so what you can try:
copy a ``vm.args`` file into the ``/vernemq/_build/default/rel/vernemq/etc/`` folder.

This file per default would look like this

    +P 256000
    -env ERL_MAX_ETS_TABLES 256000
    -env ERL_CRASH_DUMP /erl_crash.dump
    -env ERL_FULLSWEEP_AFTER 0
    -env ERL_MAX_PORTS 65536
    +A 64
    -setcookie vmq
    -name VerneMQ@127.0.0.1
    +K true
    +W w
    -smp enable
    +zdbbl 32768

append a ``-noinput`` to this file, of course you probably want to change the ``-name`` too. Now VerneMQ is started in non-interactive mode and all output gets forwarded to stdout. As a next step you probably want to disable the file logging. In ``vernemq.conf`` you can set ``log.console = console`` and now if you start VerneMQ with ``./bin/vernemq console`` everything should go to stdout. However the error.log file would still be generated. If you dont want the file containing the crash dump you could set ``log.crash = off`` .

Does this help?

**Comment by wrouesnel** [comment]
Ok that seems to be working great. Is there a way to specify the cluster join path on startup (since otherwise you need to do docker exec into the container in order to command it).

**Comment by dergraf** [comment]
just tried out something... if you add the following line to ``vm.args``
``-eval "vmq_server_cmd:node_join('test@127.0.0.1')"``
it will try to cluster with the provided node. However, it won't fail if it cant.

to use ``vmq_server_cmd`` interface directly isn't documented and might change in the future.

**Comment by jemc** [comment]
+1 to this - it would be great to end up with an official `Dockerfile` out of this work once some of the kinks are ironed out.

**Comment by dergraf** [comment]
I close this for now. Feel free to reopen it if required. Regarding a generalized docker image lets have the discussion elsewhere.

**Comment by ephimee** [comment]
If I compile vernemq inside docker, I don't have any issues. But when I install the rpm, everything looks fine, but I cannot connect with MQTT. vernemq ping does work.
This is my Dockerfile:
```
FROM centos:latest
MAINTAINER "foobar" me@something.net

# systemd fix
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
FROM milcom/centos7-systemd
RUN yum -y install openssh-server; systemctl enable sshd.service

# yum
FROM centos:latest
RUN rpm --import /etc/pki/rpm-gpg/*GPG*
RUN yum install -y wget bind-utils net-tools ntp gcc glibc-devel make ncurses-devel openssl-devel autoconf

# ssh
RUN mkdir /var/run/sshd
RUN echo 'root:mypassword' | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN /usr/bin/ssh-keygen -A
# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

# env
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

# erlang
RUN cd /home;wget http://erlang.org/download/otp_src_17.5.tar.gz;tar zxvf otp_src_17.5.tar.gz;
RUN cd /home/otp_src_17.5;./configure
RUN cd /home/otp_src_17.5;make
RUN cd /home/otp_src_17.5;make install

# build latest git
RUN yum install -y curl-devel expat-devel gettext-devel openssl-devel perl-devel zlib-devel
RUN yum install -y asciidoc xmlto docbook2X gcc-c++ which
RUN ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
RUN git config --global url.https://github.com/.insteadOf git://github.com/
RUN git clone git://git.kernel.org/pub/scm/git/git.git
RUN cd git;make configure
RUN cd git;./configure
RUN cd git;make all
RUN cd git;make install

# build VerneMQ
#RUN cd /home;git clone git://github.com/erlio/vernemq.git
#RUN cd /home;mv vernemq vernemq_source;cd vernemq_source;make rel

# install VerneMQ
COPY vernemq-0.12.5p4-1.el7.centos.x86_64.rpm /home
RUN yum install -y /home/vernemq-0.12.5p4-1.el7.centos.x86_64.rpm

# configure VerneMQ
RUN echo "PATH=\$PATH:/home/vernemq/bin" >> ~/.bashrc
RUN echo "*                hard   nofile         65536" >> /etc/security/limits.conf
RUN echo "*                soft   nofile         65536" >> /etc/security/limits.conf
COPY vm.args /home/vernemq/etc/
COPY vernemq.conf /home/vernemq/etc/vernemq.conf

# ports
EXPOSE 22
EXPOSE 1883

# services
CMD vernemq start
```

**Comment by jemc** [comment]
@ephimee not relevant to your question, but I'd add that there's usually no reason to expose an SSH server in your docker container, as all the use cases I can think of for SSH in your container can be accomplished using plain docker commands.

For example, you can use `docker exec -ti my-container-name sh` to get a shell inside the container.

**Comment by ephimee** [comment]
@jemc yes I know, but I needed it to transfer files for troubleshooting. I use the docker command above to login as well because it's faster too.

**Comment by jemc** [comment]
I don't want to hijack this thread any more than I already have, but you can use [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/) to transfer files :grin:.

**Comment by ephimee** [comment]
@jemc Thanks for the tip.
Now to stay on topic. How can I further troubleshoot why MQTT cannot connect to vernemq?
Are there any commands/configuration to enable verbose logging?

**Comment by larshesel** [comment]
Hi @ephimee would it be possible to install the rpm outside of docker to see if it's docker or the rpm that's the issue?

Regarding troubleshooting, then you can:
- add debug logging in vernemq.conf (default is info)
- Check the console.log for any error messages (there shouldn't be any)
- check that vernemq is running on port 1883:
```
$ lsof -i  | grep 1883
beam.smp  7998  lhc  126u  IPv4 1139804      0t0  TCP localhost:1883 (LISTEN)
$ ps 7998
  PID TTY      STAT   TIME COMMAND
 7998 pts/14   Ssl+   0:03 /home/lhc/dev/erl.io/vernemq/_build/default/rel/vernemq/bin/../erts-7.3/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /home/lhc/dev/erl.io/vernemq/_build/default/rel/vernemq/bin/.. -progname vernemq --...
```

- verify if you can talk to the vernemq from within the docker image using clients like `mosquitto_pub` and `mosquitto_sub` (but it sounds like you already did that).

Let us know what your findings are.

**Comment by ephimee** [comment]
@larshesel I installed on Ubuntu (bare metal host) and in virtualbox (rhel 7.2). Both have no issues.
-  debug is already on, but nothing interesting is added to the logs
-  I don't see what is wrong by looking at the logs. Attached logs from both working compile by hand and rpm. One log is a lot bigger than the other one.
[vernemq_rpmlog.txt](https://github.com/erlio/vernemq/files/273124/vernemq_rpmlog.txt)
[vernemq_log.txt](https://github.com/erlio/vernemq/files/273125/vernemq_log.txt)
-  netstat does not show any process attached, but is LISTEN, however your lsof command does not show anything.
```
netstat -nalep | grep 1883
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      997        1352546    -    
```
- I'm using MQTT spy, which turns green if the connection is ok.

**Comment by ioolkos** [comment]
In self compiled log: 
```
17:08:46.229 [debug] Supervisor {<0.264.0>,ranch_listener_sup} started ranch_conns_sup:start_link({{0,0,0,0},1883}, worker, 5000, ranch_tcp, 5000, vmq_ranch) at pid <0.265.0>
```
In rpm log:
```
2016-05-19 17:29:54.552 [debug] <0.260.0> Supervisor {<0.260.0>,ranch_listener_sup} started ranch_conns_sup:start_link({{127,0,0,1},1883}, worker, 5000, ranch_tcp, 5000, vmq_ranch) at pid <0.261.0>
```

I'm not the Docker expert here...but a listener on 127.0.0.1 wouldn't work, right?

**Comment by ephimee** [comment]
@ioolkos At first I thought this should not matter, but apparently it does. Thanks for the tip! It seems to work now.

**Comment by dergraf** [comment]
We started a public repo for VerneMQ on Docker, which is also available on the Docker hub. Please check it out! https://github.com/erlio/docker-vernemq
