### ISSUE TITLE
HTTPS is not working in vernemq

### ISSUE THREAD

**Issue by ak-91** [erlio/vernemq#540]
### Environment

- VerneMQ Version:1.1.1
- OS: Ubuntu 16.04 LTS
- Erlang/OTP version (if building from source):

### Expected behavior

I Configured HTTPS in Vernemq. I am already using SSL,So I am using same port for HTTPS.
I am not able to get the broker metrics through HTTPS. It prints empty results.

This is my config file
--------------------------
allow_anonymous = off
listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile = /home/ubuntu/myCA/aa-keychain.crt
listener.ssl.certfile = /home/ubuntu/myCA/aa-cert.crt
listener.ssl.keyfile = /home/ubuntu/myCA/aa.key

listener.http.default = 0.0.0.0:8888
listener.https.default= 0.0.0.0:8883

I tried to print the metrics like this

curl --insecure --cacert aa-keychain.crt https://192.168.1.10:8883/metrics

output: curl: (52) Empty reply from server

I dont know where I am making wrong.Any help will be appreciated.

**Comment by dergraf** [comment]
you have already defined the 0.0.0.0:8883 Listener for MQTT over SSL/TLS. You have to choose a different port for HTTPS.

**Comment by dergraf** [comment]
And you have to also specify the cafile,certfile,keyfile for HTTPS.

**Comment by ak-91** [comment]
Okay I also mentioned different port like this. 'listener.https.default= 0.0.0.0:8883'
How to specify the certificates for HTTPS port.I didn't see any option for that.Can you help me to fix this issue.

**Comment by dergraf** [comment]
it would be `listeners.https.default.[cafile,keyfile,certfile]`

**Comment by ak-91** [comment]
I tried with the above setting,It shows there is no option like that.
error message : Conf file attempted to set unknown variable

I tried like this 
listeners.https.default.cafile = /home/ubuntu/ssl_certificates/aa-keychain.crt  
and like this
listeners.https.cafile = /home/ubuntu/myCA/aa-keychain.crt

The above both option not works for me.

**Comment by ak-91** [comment]
Hi, Kindly let me know any other way is there to configure HTTPS in vernemq ?

**Comment by larshesel** [comment]
Hi, we just tried to configure it like this (note that it really is `listener` and not `listeners`):

```
listener.https.default = 127.0.0.1:8889
listener.https.default.cafile = /home/lhc/dev/erl.io/vernemq/apps/vmq_server/test/ssl/all-ca.crt
listener.https.default.certfile = /home/lhc/dev/erl.io/vernemq/apps/vmq_server/test/ssl/server.crt
listener.https.default.keyfile = /home/lhc/dev/erl.io/vernemq/apps/vmq_server/test/ssl/server.key
```
(using the test certificates we use for our VerneMQ SSL tests)

And then did:

```
curl --cacert ./apps/vmq_server/test/ssl/all-ca.crt -i https://localhost:8889/metrics
```

And got the following (abbreviated):
```
HTTP/1.1 200 OK
server: Cowboy
date: Tue, 05 Dec 2017 14:10:12 GMT
content-length: 13275
content-type: text/plain

# HELP queue_processes The number of MQTT queue processes.
# TYPE queue_processes gauge
queue_processes{node="VerneMQ@127.0.0.1"} 0
# HELP retain_memory The number of bytes used for storing retained messages.
# TYPE retain_memory gauge
retain_memory{node="VerneMQ@127.0.0.1"} 21184
.
.
.
# HELP queue_message_out The number of PUBLISH packets sent from MQTT queue processes.
# TYPE queue_message_out counter
queue_message_out{node="VerneMQ@127.0.0.1"} 0
# HELP client_expired Not in use (deprecated)
# TYPE client_expired counter
client_expired{node="VerneMQ@127.0.0.1"} 0
# HELP cluster_bytes_received The number of bytes recevied from other cluster nodes.
# TYPE cluster_bytes_received counter
cluster_bytes_received{node="VerneMQ@127.0.0.1"} 0
# HELP cluster_bytes_sent The number of bytes send to other cluster nodes.
# TYPE cluster_bytes_sent counter
cluster_bytes_sent{node="VerneMQ@127.0.0.1"} 0
# HELP cluster_bytes_dropped The number of bytes dropped while sending data to other cluster nodes.
# TYPE cluster_bytes_dropped counter
cluster_bytes_dropped{node="VerneMQ@127.0.0.1"} 0
```

So it seems to work ok - hope this helps.
