### ISSUE TITLE
How to upgrade a VerneMQ production cluster in Docker Swarm without data loss?

### ISSUE THREAD

**Issue by MarsWarrior** [erlio/vernemq#541]
### Environment

- VerneMQ Version: None
- OS: Docker Swarm (Docker images based on Alpine or Ubuntu)
- Erlang/OTP version (if building from source):

### Expected behavior

- 3 node VerneMQ cluster running in Docker Swarm
- Cluster can be automatically upgraded by updating the Docker VerneMQ service image. Docker Swarm updates the three VerneMQ nodes one by one **WITHOUT** any loss of (published) messages.

### Actual behaviour

- Unknown. I can't find this use case in the documentation and it would be very, very nice to have it!
- There is some documentation about leaving & joining a cluster, but this does not address the "cluster upgrade" use case.

### Notes
- We have experience upgrading a RabbitMQ cluster. This is very difficult and time consuming, sometimes caused by incompatible Erlang/OTP versions and/or incompatible RabbitMQ versions preventing the step-by-step cluster upgrade.
- Currently researching VerneMQ and Emqtt about this "cluster upgrade" use case and hope you have a nice working solution for this.

**Comment by larshesel** [comment]
Upgrading is a fairly manual process where you need to first migrate all clients away from a node using the cluster leave functionality which can force migrate client queues to other nodes or await natural migration (client-reconnects). When the node is 'empty' you can upgrade it and remove any leftover data so the node starts from a clean slate and the rejoin the cluster. For actual support with this you should get in contact with us at https://vernemq.com/contact.html as we do provide support contracts where we supply detailed instructions on how to upgrade between vernemq versions.

**Comment by yob** [comment]
Is there any chance of basic upgrade steps being included in the public documentation?

We're looking into upgrading a reasonable old vernemq install, and some guidance would be super helpful.
