### ISSUE TITLE
Number of topics limitations 

### ISSUE THREAD

**Issue by YossiShasha** [erlio/vernemq#545]
Is there any limitation on number of topics that a vernemq cluster can handle?
If there is a limit, does it change in respect of number of nodes in the cluster?

My system will potentially have millions of topics.

**Comment by larshesel** [comment]
There are no real limitations. The factor to keep in mind is that all topics (subscriber data) has to be replicated to all nodes and this of course takes longer depending on how much data there is (when for instance a new node joins the cluster).

Millions of topics should in principle be no problem, but it's always advisable to take a hard look at the design of the MQTT system to see if something can be optimized - it will save resources in the long run.
