### ISSUE TITLE
Cluster mode does not work

### ISSUE THREAD

**Issue by yyguo1986** [erlio/vernemq#552]
### Environment

- VerneMQ Version: vernemq-1.2.1-1.el7.centos.x86_64.rpm
- OS:
- Erlang/OTP version (if building from source):

### Expected behavior

1. I have 2 vernemq node in a cluster, such as:
_[root@localhost vernemq]# vmq-admin cluster show
_+--------------------+-------+
_|        Node        |Running|_
_+--------------------+-------+_
_|VerneMQ@IP01| true  |_
|_VerneMQ@IP02| true  |_
_+--------------------+-------+___

2. subscribe same topic on different cluster nodes:
mosquitto_sub -h IP01 -t "topic" -d -i client01 -q 1
mosquitto_sub -h IP02 -t "topic" -d -i client02 -q 1

3. publish a message with this topic "topic" on node with IP01 or on node with IP02, these two subscribers client01 and client02 should receive this message.

### Actual behaviour
But only client01 received this message when the message was published on IP01 node. only client02 received message when the message was published on IP02 node.

**Comment by yyguo1986** [comment]
Some settings here (same on 2 cluster nodes) and others still are default:
_allow_anonymous = on
allow_multiple_sessions = on
queue_deliver_mode = balance
listener.tcp.default = 0.0.0.0:1883
listener.vmq.clustering = 0.0.0.0:44053_

**Comment by ioolkos** [comment]
@yyguo1986 welcome & thanks for asking!

Do you see anything in the VerneMQ logs? Your 2 nodes probably cannot communicate through the ports that should be open for inter-node message delivery. Look for `listener.vmq.clustering` in your vernemq.conf.

the other possibility could be shared subscription with a 'prefer-local' strategy, but it doesn't look like that from your topic names anyway.

**Comment by yyguo1986** [comment]
Two cluster nodes are same:
listener.vmq.clustering = 0.0.0.0:44053

Here is the crash.log, how to resolve it? Besides, the the subscription is just a common subscription, not shared subscription. In this case, does "prefer-local" strategy also work?

[root@localhost vernemq]# cat /var/log/vernemq/crash.log
2017-12-08 01:23:24 =CRASH REPORT====
  crasher:
    initial call: vmq_cluster_com:init/4
    pid: <0.10663.0>
    registered_name: []
    exception error: bad argument: [{vmq_cluster_com,process_bytes,3,[{file,"/opt/vernemq/distdir/BUILD/1.2.1/_build/default/lib/vmq_server/src/vmq_cluster_com.erl"},{line,139}]},{vmq_cluster_com,handle_message,2,[{file,"/opt/vernemq/distdir/BUILD/1.2.1/_build/default/lib/vmq_server/src/vmq_cluster_com.erl"},{line,96}]},{vmq_cluster_com,loop,1,[{file,"/opt/vernemq/distdir/BUILD/1.2.1/_build/default/lib/vmq_server/src/vmq_cluster_com.erl"},{line,67}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]
    ancestors: [<0.366.0>,<0.365.0>,ranch_sup,<0.66.0>]
    messages: []
    links: [<0.366.0>,#Port<0.16689>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 324
  neighbours:
2017-12-08 01:23:24 =ERROR REPORT====
Ranch listener {{0,0,0,0},44053} had connection process started with vmq_cluster_com:start_link/4 at <0.10663.0> exit with reason: badarg

**Comment by ioolkos** [comment]
Can you make sure that port 44053 is not used by any other process (or set `listener.vmq.clustering` to another port).
And configure with the IP instead of 0.0.0.0, although this should work in general.

**Comment by yyguo1986** [comment]
I followed your suggestion to configure listener.vmq.clustering with the IP instead of 0.0.0.0 and another different port. Now it works. Thanks.
