### ISSUE TITLE
unknown_module for Elixir.VernemqElixirPlugin

### ISSUE THREAD

**Issue by mwilliford** [erlio/vernemq#557]
### Environment

- VerneMQ Version:  (1.2.2, actually master)
- OS:  OSX 10.11.6 ElCapitan
- Erlang/OTP version (if building from source): 9.3 (from brew) brew install erlang@19
Erlang/OTP 19 [erts-8.3.5.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
elixir version (build from src w/ 19.3)
Elixir 1.4.5 (also attempted 1.5.2)

Config:
plugins.vernemq_elixir_plugin = on
plugins.vernemq_elixir_plugin.path = /Users/marcus/projects/lumigrow/vernemq/apps/vernemq_elixir_plugin/_build/prod/rel/vernemq_elixir_plugin

flounder:vernemq marcus$ ls /Users/marcus/projects/lumigrow/vernemq/apps/vernemq_elixir_plugin/_build/prod/rel/vernemq_elixir_plugin
bin		lib		releases

built plugin like this:
MIX_ENV=prod mix release --env prod .

built vernemq from "make rel"

quick modification required for osx (works for vmq_passwd)
--- a/apps/vmq_passwd/c_src/Makefile
+++ b/apps/vmq_passwd/c_src/Makefile
@@ -1,4 +1,4 @@
 CC?=   gcc

 compile:
-       $(CC) $(CFLAGS) vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
+       $(CC) $(CFLAGS) vmq_passwd.c -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lcrypto -o ../priv/vmq_passwd

### Expected behavior

- Expected demo plugin to load, 
from this:  https://github.com/trarbr/vernemq_elixir_plugin

### Actual behaviour

2017-12-14 16:53:01.509 [warning] <0.954.0>@vmq_plugin_mgr:check_plugins:409 can't load application plugin vernemq_elixir_plugin due to {unknown_module,'Elixir.VernemqElixirPlugin'}
2017-12-14 16:53:01.509 [warning] <0.1048.0>@vmq_server_app:start_user_plugin:60 could not start plugin vernemq_elixir_plugin due to {unknown_module,'Elixir.VernemqElixirPlugin'}

plugin not registered:

flounder:vernemq marcus$ ./bin/vmq-admin plugin show
+----------+-----------+-----------------+-----------------------------+
|  Plugin  |   Type    |     Hook(s)     |            M:F/A            |
+----------+-----------+-----------------+-----------------------------+
| vmq_acl  |application| auth_on_publish |  vmq_acl:auth_on_publish/6  |
|          |           |auth_on_subscribe| vmq_acl:auth_on_subscribe/3 |
|vmq_passwd|application|auth_on_register |vmq_passwd:auth_on_register/5|
+----------+-----------+-----------------+-----------------------------+

Any ideas?  I tried 4 different erlangs (binary from site, 9.3, 9.2, 10.somthing), brew, asdf, lol
I build elixir from src, so I could try both 1.4.5 and 1.5.2 (brew didn't have 1.4.5 avail).

rebuild vernemq every time I changed my erlang version, etc...

I'm not that experienced with erlang or elixir, but can't get the equiv of a hello world working with plugins...

**Comment by mwilliford** [comment]
more info:

It seems I can't use this plugin either:
https://github.com/dergraf/vernemq_demo_plugin

seems to compile ok, again with same 9.3 erlang above.

flounder:vernemq_demo_plugin marcus$ ../../_build/default/rel/vernemq/bin/vmq-admin plugin enable --name vernemq_demo_plugin --path /Users/marcus/projects/lumigrow/vernemq/apps/vernemq_demo_plugin
Can't enable plugin: vernemq_demo_plugin due to {unknown_module,
                                                 vernemq_demo_plugin}

**Comment by ioolkos** [comment]
Hi @mwilliford thanks for asking & your effort. I see you proceeded according to https://github.com/erlio/vernemq/wiki/VerneMQ-plugins-in-Elixir
@trarbr if you find a second, maybe you quickly see what's up here: 

```2017-12-14 16:53:01.509 [warning] <0.954.0>@vmq_plugin_mgr:check_plugins:409 can't load application plugin vernemq_elixir_plugin due to {unknown_module,'Elixir.VernemqElixirPlugin'}```

**Comment by mwilliford** [comment]
Notice above, I can't load even straight erlang OTP plugin, must be something w/ my setup on OSX?

**Comment by larshesel** [comment]
Hi @mwilliford I just tried to build and install the https://github.com/dergraf/vernemq_demo_plugin plugin on Debian linux and had no issues enabling it, so I'm afraid it might be some issue with your setup :/.

Btw, in any case you should use https://github.com/erlio/vernemq_demo_plugin instead of the other repo as the one from @dergraf is outdated.

Do you have the possibility to try on another platform to see if you can reproduce it there?

**Comment by mwilliford** [comment]
Yes, I can confirm that it works fine with ubuntu (in docker container).  I believe the problem now only occurs using mac osx.  Is OSX supported, if so do you have any specific build instructions for it?

Meanwhile, I can use ubuntu inside docker, as ubuntu is my target anyways.  I probably need to figure out how to workout remote erlang debugging from my IDE into the container, etc...

It seems vernemq has most of the functionality i need via webhooks anyways, however I am stuck trying to find a way to query all sessions.  My server needs an initial list of sessions connected on startup.  I have business logic which requires me to know who is connected in a performant way.  So, it looks like I might still need to build some sort of plugin.

**Comment by larshesel** [comment]
Building VerneMQ on macosx has always been a bit of a trial and there's an open issue for it where you might find some information: https://github.com/erlio/vernemq/issues/119. We don't really support it as none of us are using macs, but for some it just works.

Can't you use `vmq-admin session show`? If so then maybe you can use the http interface which exposes the same functionality as the command line interface: http://vernemq.com/docs/http-administration/.

Depending on what you need that might work - otherwise you may have to build a plugin.

Btw. Are you sure you didn't for some reason build the plugins with erlang 20? Erlang 20 modules wouldn't be able to be loaded into a VerneMQ built with Erlang 19. See #448 which reports the same error as yours.

**Comment by mwilliford** [comment]
@larshesel 

Ok, I'll revisit the mac issue only if I need to build a plugin of my own and can't live without local debugging. 

I will try to use the http interface to vqm-admin session show.  I will have around 10,000 active sessions, so i didn't know if the http interface was appropriate.  For example:  can i do --limit=10000 via the URI somehow, etc...  I'll try to look through docs and code and test it out.

**Comment by larshesel** [comment]
The http interface is a bit limited in that it doesn't support pagination. This will make it less than ideal for some queries, but for some it will be fine...

I guess I can close this issue for now, then. Let us know if you run into other issues!
