### ISSUE TITLE
VerneMQ SSL authenticaiton on Linux RedHat

### ISSUE THREAD

**Issue by tomcis** [erlio/vernemq#562]
Hello everyone,

I am currently implementing SSL authentication for VerneMQ broker which I have made already work for Ubuntu environment however when I have tried to migrate and implement exactly the same setup on Linux RedHat, it seems not to work.

### Environment

- VerneMQ Version: 1.2.2
- OS: Amazon Linux AMI (which is RedHat distribution)
- Erlang/OTP version (if building from source):

### Expected behavior

vernemq.conf:

```
allow_anonymous = on
listener.ssl.cafile = /home/ec2-user/certs/all-ca.crt
listener.ssl.certfile = /home/ec2-user/certs/server.crt
listener.ssl.keyfile = /home/ec2-user/certs/server.key
listener.ssl.default = 172.31.29.25:8883
nodename = VerneMQ@127.0.0.1
distributed_cookie = vmq
```

I use your generated certificates which you have provided over here:

https://github.com/erlio/vernemq/issues/151

### Actual behaviour

Running command:

`sudo openssl s_client -showcerts -connect ec2-54-190-193-6.us-west-2.compute.amazonaws.com:8883 -CAfile certs/all-ca.crt -state -nbio -debug`

Results in (and halts):

```
....
0110 - 06 02 06 03 05 01 05 02-05 03 04 01 04 02 04 03   ................
0120 - 03 01 03 02 03 03 02 01-02 02 02 03 00 0f 00 01   ................
0130 - 01  
SSL_connect:SSLv2/v3 write client hello A
read from 0x239c2a0 [0x23a1880] (7 bytes => -1 (0xFFFFFFFFFFFFFFFF))
SSL_connect:error in SSLv2/v3 read server hello A
write R BLOCK
```

It seems that I have tried everything and read most of the posts however it still does not work. I wonder what is the difference between these two environments. I was not even close to authentication with RedHat however I have implemented a complex structure in Ubuntu myself..

**Comment by ioolkos** [comment]
@tomcis sorry to hear this!
At this point I have no idea why RedHat/VerneMQ/SSL refuses to work here.

Do you have some further hypothesis? could you in any way narrow down a little?

**Comment by tomcis** [comment]
@ioolkos 
Sorry for the late reply, I was still trying to figure out what might be the issue. It is quite difficult to narrow it down since exactly the same configuration works on Ubuntu 16.04 so I thought you might have an idea or have discovered before what might be different between the two OSes. Most of the initial issues on Ubuntu were related to folder and files' permissions of the certificates - for what Erlang is sensitive, however even giving all the right permissions - it still does not work on RedHat.

**Comment by ioolkos** [comment]
Hi @tomcis thanks for your report and efforts!
I'll try to see if I can reproduce this one of these days with a RedHat image.

**Comment by tomcis** [comment]
@ioolkos 
Great, let me know!

**Comment by tomcis** [comment]
@ioolkos,
I guess one more important thing to note: it gives exactly the same output even if I write completely arbitrary/fake paths to CA/CERT/KEY, thus the problem might be somewhere deeper. Exactly the same configuration file works on the Ubuntu 16.04. Did you have some time to look into it?

**Comment by larshesel** [comment]
This sounds like it could be a permission problem. Can you check that the VerneMQ user is allowed to read the certificate files?

**Comment by tomcis** [comment]
@larshesel ,
As I have already previously mentioned, in order to try to make it work I have even given 777 rights to every file and certs/ folder - however this does not change the situation and it still does not work. Maybe the paths have to be defined differently in RedHat?

**Comment by larshesel** [comment]
I've never come across that RedHat hasn't just worked, even with SSL and some of our clients are using RedHat (though not the Amazon Linux AMI), so there should be a way to get it to work. What about the permissions on the files themselves? I've experienced things like SSH not wanting to use files with too open restrictions (as those files would be insecure) - not sure that could be the case at all, just grasping at straws.

**Comment by tomcis** [comment]
@ioolkos, @larshesel 
Wow, that was a lot of wasted time.
I have figured out that putting certificate files to `/etc/vernemq/` solved all the issues and VerneMQ started recognising the files (even with 644). Thanks for all the support!

**Comment by ioolkos** [comment]
Hi @tomcis sorry bout that wasted time... I apologise I haven't been able to help faster!

I'm glad this works... but as a recap: is VerneMQ doing something it shouldn't or not doing something it should on RedHat? can we improve/change anything?

Thanks again for your tremendous effort and sharing the learnings!

**Comment by tomcis** [comment]
Dear @ioolkos.
I am not sure if there is any specific issue with VerneMQ for RHEL/CENTOS distribution however I do not see any reason (cannot think of any why) it should not be able to access files from `/home/` directory, even when giving public rights on the folder and certificates.

**Comment by larshesel** [comment]
I could be due to an SELinux policy: http://fedora.12.x6.nabble.com/location-of-postfix-ssl-certificates-td2644453.html - there's nothing in VerneMQ itself or Erlang for that matter which restricts where the files can be located.

**Comment by tomcis** [comment]
@larshesel 
This explanation would make the most sense in this case. Thank you for sharing!
Do you think/know if (by any means) it would be possible to put certificate files in some other directory (te.g. `/home/user`) (to be able to use them for some other application) and make VerneMQ access those files in RedHat?

**Comment by larshesel** [comment]
If my guess above was right you'd have to change the SELinux rules to allow for it - I really have no idea how to do that, I'm afraid - never tried. One experiment could be to try to disable SELinux all together and see if that works - then it's clearly SELinux that's playing tricks with us.

**Comment by tomcis** [comment]
@larshesel 
Indeed, I think in this case, SELinux is playing tricks with us. I also haven't had too much interaction with it before but maybe I will have to look into that. Thanks a lot! I guess this topic can be close for now.

**Comment by larshesel** [comment]
You're welcome! Let us know if you run into other issues.
