### ISSUE TITLE
Question: New connection with "duplicate" ClientID

### ISSUE THREAD

**Issue by Eric24** [erlio/vernemq#569]
What is the default expected behavior of VerneMQ (stand-alone or clustered), when a new connect is attempted with a ClientID that is already connected (regardless of whether the new connection comes into a different cluster node than the existing one, in case of a cluster)?

My assumption is that the existing connection will be dropped and the new one established (assume good auth, etc.). Is that correct? Is this behavior configurable in any way?

Note that the use-case here is simply that a remote device disconnects unexpectedly (from the remote's perspective, but not--yet--from the broker's perspective), so the remote initiates a new connection. Some MQTT brokers I've tested with will reject the new connection (due to the duplicate). I could just use a new ClientID to prevent that, but I need the same one because I want to reconnect to the persistent session, and not loose any messages in the process.

**Comment by ioolkos** [comment]
Hi @Eric24 thanks for asking!
Yes, the default behaviour is that the existing connection (ClientID) is kicked out and that the new connection is accepted (this behaviour is required by the MQTT spec).
This the case both for the single node as for a cluster.

You can configure `allow_multiple_sessions = on` to allow the same ClientID to be connected multiple times (non-standard feature).

**Comment by Eric24** [comment]
Thanks for the quick response! The default behavior you describe is exactly what I was hoping for (I've seen other MQTT implementations that do not behave in this way).

I did see your `allow_multiple_sessions` config option, and I can see where it might be useful, but it's not in my case.

By the way, if there is documentation on this behavior somewhere, I couldn't find it after several passes through the docs.

**Comment by ioolkos** [comment]
@Eric24 thanks for pointing out the documentation is unclear. I'll try to make it better!

**Comment by moscara** [comment]
> Hi @Eric24 thanks for asking!
> Yes, the default behaviour is that the existing connection (ClientID) is kicked out and that the new connection is accepted (this behaviour is required by the MQTT spec).
> This the case both for the single node as for a cluster.
> 
> You can configure `allow_multiple_sessions = on` to allow the same ClientID to be connected multiple times (non-standard feature).

Hi @ioolkos does this then mean that if a client disconnects unexpectedly with the client_id "123", when it reconnects it gets a new client_id "456" from the broker and loose any messages in process or queue? Sorry if I am asking a stupid question, I am new to Mqtt and learning it through VerneMQ.

**Comment by ioolkos** [comment]
@moscara note that the client sets the ClientID. It should use the same ClientID normally, for the reason you mention: it wouldn't have access to stored messages otherwise.

**Comment by moscara** [comment]
> @moscara note that the client sets the ClientID. It should use the same ClientID normally, for the reason you mention: it wouldn't have access to stored messages otherwise.

Thank you for the reply. It reasoning is clear to me now.
