### ISSUE TITLE
Add support for topic rewriting similar to apache mod_rewrite

### ISSUE THREAD

**Issue by Hades32** [erlio/vernemq#57]
For details please have a look at https://github.com/emqtt/emqttd/issues/126

**Comment by dergraf** [comment]
@Hades32 this can be simply done using a plugin. However one would need to write Erlang or Elixir code for that.

**Comment by Hades32** [comment]
Is there some kind of template for an Elixir based plugin?Is there some kind of template for an Elixir based plugin?

**Comment by dergraf** [comment]
Your plugin should probably implement the ``auth_on_publish`` and ``auth_on_subscribe`` hooks.
@larshesel put something together a while ago: https://github.com/larshesel/vmq_elixir_plugin, I am not sure how it will work with the new topic-format coming in 0.12.0. 

In 0.12.0 the topic ``/hello/world/`` will be passed as ``[<<>>,<<"hello">>, <<"world">>, <<>>]`` to the plugin hooks. 

If the ``auth_on_publish`` hook returns the Erlang term ``{ok, [{topic, [<<"new">>, <<"topic">>]}]`` the publish gets authorized using the rewritten topic. 
If the ``auth_on_subscribe`` hook returns the Erlang term ``{ok, [{[<<"new">>, <<"topic">>], 2}]}`` the subscription gets authorized using the rewritten topic and QoS.

**Comment by Hades32** [comment]
I see, thanks for the hint. Is there some docs on the Details of 0.12? Also, how are Wildcards expressed in this structure and are there helper functions to ease handling them?

**Comment by dergraf** [comment]
for plugin development we currently have no 'real' documentation, I must admit. This is something we've on our todo list. 

the wildcard topic ``/hello/+/world/#`` will be passed as ``[<<>>, <<"hello">>, <<"+">>, <<"world">>, <<"#">>]``

**Comment by dergraf** [comment]
@Hades32 how did it go?

**Comment by Hades32** [comment]
Not at so, I'm in vacation :)
But I'll try some time in the future and will post my results here.

**Comment by dergraf** [comment]
great. enjoy your holidays! :)

**Comment by dergraf** [comment]
I close this for now. Feel free to reopen it if required.

**Comment by testark** [comment]
@dergraf I'm trying to implement a `auth_on_publish` hook but it doesn't seem to be called. I have other hooks (like `on_client_wakeup`) on the same plugin and they are called as expected, but not the `auth_on_publish` hook. I'm using 0.12.2. What can I be doing wrong?
