### ISSUE TITLE
Question: Two SSL Listeners?

### ISSUE THREAD

**Issue by Eric24** [erlio/vernemq#570]
It is possible to configure two SSL Listeners, one with and one without the requirement for client certificates?

Alternatively, is it possible for this requirement to be controlled/modified by a webhook handler, or some other means?

**Comment by dergraf** [comment]
first question, yes. second no.

**Comment by ioolkos** [comment]
Look at the examples in the vernemq.conf. You can specify configs on a protocol level or on a listener level. To do this on a listener level, you need to name your listeners, then you can use that name in the configs, like this: `listener.ssl.my_ssl_listener.require_certificate` etc.
