### ISSUE TITLE
error: unknown event in wait_for_offline state

### ISSUE THREAD

**Issue by michaelfung** [erlio/vernemq#571]
### Environment

- VerneMQ Version:  commit a97b351
- OS: both ubuntu 17.10
- Erlang/OTP version (if building from source):  20.0.4

The client was disconnected by the server. The client side error is:
```
Error: Connection reset by peer 
```

The broker had the following in the log:
```
2018-01-07 18:17:43.370 [error] <0.455.0>@vmq_queue:wait_for_offline:254 got unknown event in wait_for_offline state {change_state,notify,<0.451.0>}
```

Is this a broker side problem?

**Comment by larshesel** [comment]
Hi @michaelfung 

The log message above means that there's an unexpected event happening while the queue is shutting down. It may or may not be an actual problem.

I suppose you experience an unexpected disconnect from the server? Can you tell us more about what your configuration is and what is happening when this occurs?

**Comment by michaelfung** [comment]
Yes, the disconnect was unexpected. It only happened a few times so far.

I am writing a perl script to stress test my system. It uses AnyEvent::MQTT to make thousands of connections to the broker and do periodic publishing. The configuration file is almost default with these web hooks configurations:
```
vmq_webhooks.hub_auth.hook = auth_on_register
vmq_webhooks.hub_auth.endpoint = http://localhost:3000/hooks/auth_on_register

vmq_webhooks.hub_register.hook = on_register
vmq_webhooks.hub_register.endpoint = http://localhost:3000/hooks/on_register

vmq_webhooks.hub_sub_auth.hook = auth_on_subscribe
vmq_webhooks.hub_sub_auth.endpoint = http://localhost:3000/hooks/auth_on_subscribe

vmq_webhooks.hub_pub_auth.hook = auth_on_publish
vmq_webhooks.hub_pub_auth.endpoint = http://localhost:3000/hooks/auth_on_publish
```

Nothing unusual observed at the webhooks log files. 

It also can be the AnyEvent::MQTT library at fault. It would be helpful if vmq show more details in the error log.
