### ISSUE TITLE
auth_on_publish:658 can't auth publish 

### ISSUE THREAD

**Issue by hejinhong** [erlio/vernemq#576]
### Environment

- VerneMQ Version: 1.2.2
- CentOS Linux release 7.4.1708
- Erlang/OTP version (if building from source): Erlang/OTP 20

### Expected behavior

-I'm try to make a VerneMQ server on my vps for test.
When I auth using file, the server goes well. But with mysql auth, I got some problem.

### Actual behaviour
The sub works well. When pub the message, it cannot work. the log like this:

2018-01-10 02:15:59.682 [error] <0.492.0>@vmq_mqtt_fsm:auth_on_publish:658 can't auth publish [<<"hejh">>,{[],<<"test-client">>},0,[<<"new">>],<<"dfdsadsdfaaaaaaaaaaaaaaaaa">>,false] due to error

I use the mosquitto_pub to pub message. 

the datebase : 
publish_acl   is  [{"pattern":"new"}]
subscribe_acl  is  [{"pattern":"a/b/c"},{"pattern":"c/b/#"}]

help me please. 

conf   file:

plugins.vmq_diversity = on
plugins.vmq_acl = off
plugins.vmq_passwd = off

**Comment by larshesel** [comment]
From the [documentation](http://vernemq.com/docs/configuration/db-auth.html#mysql) you also need the following:

```
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 127.0.0.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = vernemq
vmq_diversity.mysql.password = vernemq
vmq_diversity.mysql.database = vernemq_db
```

Hope that helps.

**Comment by hejinhong** [comment]
thank you for replay. my config file had added this. but also have problem. 
it seems user auth passed, but the pub  topic auth failure. because if i used another usee name and pub a message, it will tell me the auth failure.

**Comment by larshesel** [comment]
Could you post the complete row verbatim from the MySQL database? Just to see if there's something which looks strange.

**Comment by hejinhong** [comment]
[vmq_auth_acl.pdf](https://github.com/erlio/vernemq/files/1617799/vmq_auth_acl.pdf)

this is the data ex port from  my database

**Comment by jurgel** [comment]
any answer about this?

I have the exact same problem.

**Comment by larshesel** [comment]
Hi, I just tried following the recipe on our docs and I didn't have any problems. Getting it to work. 

I created a database and inserted two users: 

```
mysql> CREATE TABLE vmq_auth_acl
    -> (
    ->   mountpoint VARCHAR(10) NOT NULL,
    ->   client_id VARCHAR(128) NOT NULL,
    ->   username VARCHAR(128) NOT NULL,
    ->   password VARCHAR(128),
    ->   publish_acl TEXT,
    ->   subscribe_acl TEXT,
    ->   CONSTRAINT vmq_auth_acl_primary_key PRIMARY KEY (mountpoint, client_id, username)
    -> )
    -> 
    -> ;
Query OK, 0 rows affected (0.04 sec)

mysql> INSERT INTO vmq_auth_acl 
    ->     (mountpoint, client_id, username, 
    ->      password, publish_acl, subscribe_acl)
    -> VALUES 
    ->     ('', 'test-client', 'test-user', PASSWORD('123'), 
    ->      '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
    ->      '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO vmq_auth_acl 
    ->     (mountpoint, client_id, username, 
    ->      password, publish_acl, subscribe_acl)
    -> VALUES 
    ->     ('', 'test-client2', 'test-user', PASSWORD('123'), 
    ->      '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]', 
    ->      '[{"pattern":"a/b/c"},{"pattern":"c/b/#"}]');
Query OK, 1 row affected (0.00 sec)
```

And afterwards I could publish and subscribe as the two different users without problems for instance I subscribed to the `c/b/what` topic and published to the `c/b/what` topic and I received a message.

I used this config in `vernemq.conf`:

```
plugins.vmq_diversity = on
vmq_diversity.auth_mysql.enabled = on
vmq_diversity.mysql.host = 127.0.0.1
vmq_diversity.mysql.port = 3306
vmq_diversity.mysql.user = root
vmq_diversity.mysql.password = root
vmq_diversity.mysql.database = vernemq_db
```

All other plugins were disabled.

**Comment by larshesel** [comment]
@jurgel in your example I see you use the same client-id for the subscriber and for the publisher - that's not allowed in the MQTT spec: when a client connects and there is always the a session for that client-id, the existing client will be disconnected.

**Comment by jurgel** [comment]
@larshesel OMG, I didn't know about that, there's no error whatsoever on log or client debug output.
I'll try again tomorrow morning.

**Comment by jurgel** [comment]
@larshesel now it working after I tried using different clientId, thanks a lot.

If clientId should be unique, can I use wildcard on client_id field on db?

**Comment by larshesel** [comment]
No it has to be an exact match. You can see the query used here: https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/priv/auth/mysql.lua#L59.

**Comment by namjithwisilica** [comment]
Is there any option to use same client id for subscribing different topics in a same tree?

**Comment by dergraf** [comment]
@namjithwisilica No this isn't possible. This is also forced by the specification.
