### ISSUE TITLE
Detailed Information of Webhooks

### ISSUE THREAD

**Issue by Mojo90** [erlio/vernemq#577]
### Environment

- Website Docs

### Expected behavior

- A detailed information of the web hooks events.

### Actual behaviour

- On the Webhooks site it states `You can see all the details in the [vmq_webhooks](http://vernemq.com/docs/plugindevelopment/webhookplugins.html) github repository.` --> obsolete repo.
- It also states `For detailed information about the hooks and when they are called, see the [Plugin Development Guide ](http://vernemq.com/docs/plugindevelopment/)and the relevant subsections.` --> I can't find any information there about the hooks in detail when they are called.
So where can I find information which webhook is called when?

**Comment by Mojo90** [comment]
Found it in the subsections.

**Comment by larshesel** [comment]
Thanks for noticing - I'll update the docs so it doesn't contains invalid links etc..

**Comment by larshesel** [comment]
I removed the two links and reworded the text a bit. Thanks again!

**Comment by Mojo90** [comment]
Not a problem :) thx for the fast updates!
