### ISSUE TITLE
vmq-admin session show --client_id=xxx not working

### ISSUE THREAD

**Issue by masayoshi1978** [erlio/vernemq#580]
### Environment

- VerneMQ Version:1.1.0
- OS:CentOS Linux release 7.3.1611
- Erlang/OTP version (if building from source):
Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

### Expected behavior

```
vmq-admin session show --client_id
+------------------------+
|       client_id        |
+------------------------+
|   connect_pub_client   |
|      001EC048EA92      |
|      001EC03067D4      |
+------------------------+
```
first, I specified client_id connect_pub_client. 

```
vmq-admin session show --client_id=connect_pub_client
+-----+------+----------+-----+----+----+----+----+-------+-----+-------+-------+------+------+----+
|__mou|clean_|client_id |deliv|is_o|is_o|is_p|moun| node  |num_s|offline|online_|queue_|sessio|stat|
+-----+------+----------+-----+----+----+----+----+-------+-----+-------+-------+------+------+----+
|     | true |connect_pu|fanou|fals|true|fals|    |VerneMQ|  1  |   0   |   0   |<7652.|<7652.|onli|
+-----+------+----------+-----+----+----+----+----+-------+-----+-------+-------+------+------+----+
ok.
```

next, I specified client_id 001EC048EA92. 

```
vmq-admin session show --client_id=001EC048EA92
```

### Actual behaviour
 not showing 001EC048EA92...

### Details
My question is:
Please tell me how to specify for client_id.

Thank You.

**Comment by larshesel** [comment]
Hi, thanks for reporting. Could I get you to try the newest VerneMQ version (1.2.3) and report back if it works with that version? 1.1.0 is quite old.

**Comment by masayoshi1978** [comment]
Hi. answer thanks.
I will try newest version next week.

Thank you .

**Comment by masayoshi1978** [comment]
Hi,
tried newest version(1.2.3)
It's worked --client_id=xxx . 

Thank you very much.
