### ISSUE TITLE
SSL listeners doesn't inherit protocol cert options

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#583]
### Environment

- VerneMQ Version: 1.2.3
- OS: Debian

### Expected behavior

According to the documentation in the `vernemq.conf` file it should be possible to specify SSL certificate options at the protocol level, like:

```
listener.ssl.default = 127.0.0.1:8883
listener.ssl.cafile = /etc/vernemq/all-ca.crt
listener.ssl.certfile = /etc/vernemq/server.crt
listener.ssl.keyfile = /etc/vernemq/server.key
```

And it should work.

### Actual behaviour

It doesn't work - the certfile options are not applied to the `default` listener

**Comment by tomcis** [comment]
Same holds for CentOS/RHEL 7.

**Comment by ioolkos** [comment]
@tomcis thanks for checking!

**Comment by codeadict** [comment]
I'm having this issue

**Comment by larshesel** [comment]
We just merged a fix which adds a testsuite for most inheritable options. Hopefully this won't be an issue for ssl-type options in the future...

**Comment by tomcis** [comment]
@larshesel, indeed, it works without any flaws so far! Thank you for all the work
