### ISSUE TITLE
Cluster won't "connect"

### ISSUE THREAD

**Issue by nik736** [erlio/vernemq#593]
### Environment

- VerneMQ Version: 1.3.0
- OS: Ubuntu 16.04

### Expected behavior

I am trying to setup a cluster but I always get
`@vmq_cluster_com:loop:74 terminate due to remote_node_not_available`

As stated in the docs I try to connect them to each other using:
`vmq-admin cluster join discovery-node=blabla@public_ip`
Which gives me "Done." back. But looking at the cluster:

```
+-----------------------+-------+
|         Node          |Running|
+-----------------------+-------+
| name@public_ip | false |
| name@ public_ip | true  |
+-----------------------+-------+
```

I also tried stopping vernemq, deleting the metadata (/var/lib/vernemq/meta/*) and starting verne again. Same issue.

Any idea what I could try to get it running?

Edit: Some more details:
nmap public_ip -p 44053 tells me that the port is open, so there is no firewall or anything like that involved.

Thank you.

**Comment by ioolkos** [comment]
Thanks for opening the issue! Is this on Amazon, @nik736? Can you review your security group settings?

**Comment by nik736** [comment]
Thanks for getting back to me. It's running on DigitalOcean not AWS.

**Comment by ioolkos** [comment]
On Digital Ocean, I suppose there is a difference between the public and private IPs and I guess, in principle, on should use the private IPs to form a cluster. Can you test that? (if it makes sense, I derive things from the Amazon way)

**Comment by nik736** [comment]
Well, the problem is that I want to use two locations to form the cluster and private IPs are only available throughout one location.

I also don't think that it makes a difference, what would cause this behaviour?

**Comment by ioolkos** [comment]
It's easy to forget the VPC security group settings on Amazon, that's why I mentioned it.
But yeah, as long as everything works on network level, clustering should work (https://vernemq.com/docs/clustering/communication.html)

is this a completly fresh install? have you changed nodenames in the vernemq.conf? do you have multiple VerneMQ processes running on the same node? can you stop VerneMQ, and then also kill the EPMD process on that node?
Thanks for your patience...It WILL work in the end! :)

**Comment by nik736** [comment]
Yes, I tried several fresh installs already. I have changed the cookie and nodenames, I also tried rebooting everything which should fix if any processes were messed up. I also tried several other things in the config to look if it would change anyhting...

I also tried installing it on two bare metal servers with the same result. (Installed UBuntu 16.04 from the official .isos) 

I am not sure what to do anymore...

Reproducing is easy:

Fresh Ubuntu 16.04 server (seems to be it doesn't matter if DigitalOcean, ISO install, etc.):
Getting the .deb from 
`https://bintray.com/artifact/download/erlio/vernemq/deb/xenial/vernemq_1.3.0-1_amd64.deb`

Installing it:
`sudo dpkg -i vernemq_1.3.0-1_amd64.deb`

Adjust `nodename` in the config. For example in my case:
Name1@this_servers_public_ip

On the 2nd server:
Name2@this_servers_public_ip

Running the cluster command on Server 1:
`vmq-admin cluster join discovery-node=Name2@this_servers_public_ip`

Cluster now shows up, but 2nd Server is set to "false", Log shows:
`terminate due to remote_node_not_available`

Am I doing something wrong?

**Comment by ioolkos** [comment]
No, I think you do everything correctly.
Can you run `sudo vmq-admin listener show` on both nodes to see that you actually have a listener of type 'vmq' running on 44053?

**Comment by nik736** [comment]
Yep:

`|vmq |running| 0.0.0.0 |44053|          |  10000  |`

**Comment by ioolkos** [comment]
Last shot: can you try setting the `listener.vmq.clustering` to the actual IP instead of 0.0.0.0, in the vernemq.conf

**Comment by nik736** [comment]
I tried this earlier already without success but I tried it again now and it worked! Yay, thanks. 

I don't understand why though, any idea? :D

**Comment by larshesel** [comment]
Great it works! I don't have any really good ideas, maybe one of the nodes had a different config or wasn't restarted after changing the configuration or something?
