### ISSUE TITLE
rpi32 build error

### ISSUE THREAD

**Issue by rastomatti** [erlio/vernemq#598]
### Environment

- VerneMQ Version:  1.3.0
- OS: Raspbian 9 Stretch
- Erlang/OTP version (if building from source):
18.3

I have tried building Vernemq using different versions of Erlang/OTP and Vernemq, but none seem to build. 
This is the error I get:

`fatal: Not a git repository (or any of the parent directories): .git
/home/pi/vernemq1.3/vernemq-1.3.0/rebar3 as rpi32 release --overlay_vars vars.config
===> Verifying dependencies...
===> Compiling vmq_ql
===> Running neotoma...
===> Getting log of git dependency failed in /home/pi/vernemq1.3/vernemq-1.3.0. Falling back to version 0.0.0
ln: target '_build/default/lib/' is not a directory: No such file or directory
===> Hook for compile failed!

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
`

Can anyone point me in a direction so I can successfully compile on a Raspberry pi 3 running Rasbian.

- Please include minimal steps to reproduce the issue, if possible.

**Comment by ioolkos** [comment]
@rastomatti thanks for coming here! 
RPI, ARM needs a couple of tricks to run VerneMQ, due to LevelDB. Many people have managed to run it, but with different levels of pain for different releases of VerneMQ. I can't say atm whether it shoud be possible or not for the current release.

Have you seen https://github.com/erlio/vernemq/issues/498? 
-> @larshesel you had a fix for the RPI32 build  there but we didn't merge that, it seems?

**Comment by rastomatti** [comment]
Thanks for your reply, @ioolkos !
I am going to use Vernemq as a part of a bachlor-project, so any assistance would be greatly appriciated.


I have read post #498 , and unfortunatly I still could not build it on my RPI.

@larshesel , In this post you have made a branch called fix-rpi-build. Is this merged into master?

Thanks for any help. :)

**Comment by rastomatti** [comment]
Hi again,

I have successfully built vernemq for the raspberry pi now. Previously I thought I built the fix-rpi32-build branch, but it was the master I previously built from.
When cloning the correct branch, I successfully built Vernemq. Note that I needed OTP 18.3 for it to build.

I will close the issue, but I sugest to merge this branch into master.

Thanks alot!

**Comment by ioolkos** [comment]
@rastomatti OK, great. Thanks for letting us know! we'll investigate if the fix-rpi32 branch can and should be merged.
