### ISSUE TITLE
allow anonymous off, require cerificates on, can still publish with no user/pass and no certs

### ISSUE THREAD

**Issue by Akenne** [erlio/vernemq#602]
Does anyone know why this is?

**Comment by ioolkos** [comment]
@Akenne welcome here & thanks for asking :)

What kind of listeners are configured? are the clients directed at the correct listener? are you using the config file you think you're using? have you restarted VerneMQ?
if in doubt, please post an anonymized config file.

**Comment by Akenne** [comment]
o
