### ISSUE TITLE
Question about order of plugin lifecycle events when client disconnected due to multiple sessions

### ISSUE THREAD

**Issue by kellycampbell** [erlio/vernemq#603]
### Environment

- VerneMQ Version: 1.2.3
- OS: Debian Jessie

We are using lua script for authentication, and we store some state per client in the kv table during the auth_on_register hook. We clean this state up in the on_client_offline and on_client_gone hooks. 

When a duplicate client connects, what is the order of hook calls? 

I'm guessing it needs to perform the auth first before it can remove the first client, otherwise a non-authed client could DoS authed ones. If this is true, then our cleanup will remove the new session's info from the kv table. We could use the peer info in the key, but the offline and gone hooks only have the ClientId, I think issue #169 is related here.

**Comment by ioolkos** [comment]
@kellycampbell Hi, thanks for your question.
Are you saying that the order of hooks for the duplicate client is the same, or that it SHOULD have another order?
Before I send you in a wrong direction, I'll ping @larshesel and @dergraf here.

**Comment by kellycampbell** [comment]
My question is what is it expected to do in the current implementation. 

My "guess" is regarding what I think it currently does and why it has to be that way, but I don't have exact test data about it.

If it works as my guess postulates, then our cleanup for disconnecting clients won't work for the case of a client replacing an existing session.

**Comment by larshesel** [comment]
Hi @kellycampbell the auth_on_register hook is evaluated before the client is registered and it is the registration which will disconnect any existing clients with the same client id. So the `on_client_` hooks on the existing session are called after the `auth_on_register` hook for the new session with the same client id.
