### ISSUE TITLE
Having trouble getting ssl working

### ISSUE THREAD

**Issue by Akenne** [erlio/vernemq#604]
attempting to connect with python paho, and I get ('_ssl.c:645: The handshake operation timed out',) on client.connect. require client certs is off, I am not sure if I set up the cacerts up properly. I am using an aws server so I created it myself using openssl. Can anyone help me with this?

**Comment by ioolkos** [comment]
I'd like to... but I can't debug your environment ;)
This sounds so generic that you probably want to look on how to produce more details. As far as VerneMQ you could look for anything special in the logs.

**Comment by Akenne** [comment]
ok, i got a different error now: 

ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)

doing:  client.tls_set("ca2.pem", tls_version=ssl.PROTOCOL_TLSv1_2)

**Comment by Akenne** [comment]
some more progress made: 

I can now connect if I use these:

            client.tls_set("ca5.pem", tls_version=2, cert_reqs=ssl.CERT_NONE)
            client.tls_insecure_set(True)

if not, I get [SSL: CERTIFICATE_VERIFY_FAILED]

I think this has something to do with the CA common name. I am running vernemq in a docker container, within a ec2 instance. what should I be using for the common name? neither localhost or the ec2 domain worked

**Comment by Akenne** [comment]
ok i fixed it.

for the paho tls set, you must use your server crt from vernemq

you must forward your amazon ports

you need to use 0.0.0.0 for ip

you use the ip of the ec2 instance

you need to forward the docker port

you need to set tls_version = 2

you need to disable allow anonymous users

you cant use port 22
