### ISSUE TITLE
Websocket compression extension support

### ISSUE THREAD

**Issue by swinterberger** [erlio/vernemq#607]
### Environment

- VerneMQ Version: 1.3.0
- OS: Debian (vernemq docker img)

### Expected behavior

- The possibility to support websocket compression such as permessage-deflate which is supported by cowboy https://ninenines.eu/docs/en/cowboy/2.2/guide/ws_protocol/

### Actual behaviour

- Since cowboy defaults to compress:false it doesn't seem possible to enable this

Curious as to why this isn't allowed to be passed in as a parameter to the cowboy websocket listener.  Granted I am a full fledged Erlang newbie so maybe I am interpreting the code wrong but it does not seem possible at the moment to enable this option.  

I have noticed it seems all of the popular ws-mqtt brokers have this disabled with no ability to enable it, is there a reason for this?  I understand mqtt is meant for low power devices but even if you enable compression a websocket server doesnt require it, so it could be used on a per-client basis depending on what the client supports via ws extension headers.

Thoughts?  Or am I being ignorant in regards to the codebase?

**Comment by larshesel** [comment]
Hi, thanks for the question!

I think this is mostly an oversight and I don't see any reason why it shouldn't be possible to enable if one wants to use compression. A PR which makes it possible to enable compression (but defaulting to no compression) would be welcome!

Note we're still using Cowboy 1.x (https://ninenines.eu/docs/en/cowboy/1.0/guide/ws_protocol/) but it looks like it works in the same way.

**Comment by swinterberger** [comment]
Thanks for the quick reply!  I was able to add the option however I overlooked the fact that cowboy 1.x only supports the deprecated compression extension x-webkit-deflate-frame and the PR to add permessage-delate was never added to 1.x for some reason.  Testing the deprecated compression algorithm will take a bit longer since I have to find a client that still supports it.

Are there any plans to move to 2.x at some point?  I am sure that is a large undertaking, just curious if it's on the roadmap.

**Comment by larshesel** [comment]
We've thought about it, but we didn't have any good technical arguments to do so yet. I don't think it would be too much trouble as we only use cowboy for our HTTP api, metrics and to server MQTT over websockets. Though, we'd also have to check if Cowboy 2.x pulls in newer dependencies and if they're compatible with the versions we use today (ranch, is one dependency which comes to mind, maybe there are others).

I don't know when we'd get around to take a serious look at switching to Cowboy 2.x, though.

**Comment by swinterberger** [comment]
Makes sense, appreciate the info.  I will still open a pr when I get around to running a client supporting deflate frame for proper testing.

**Comment by larshesel** [comment]
Great. I'll close this for now. We will probably upgrade to cowboy 2.x when we release VerneMQ 2.0 (no ETA yet).

**Comment by felixphew** [comment]
@larshesel since it appears cowboy 2.x has been in use since db3de05 and VerneMQ 1.9 - any chance of another look at enabling compression?

**Comment by mohzah** [comment]
@felixphew Started a thread in discussions, feel free to comment
https://github.com/vernemq/vernemq/discussions/2102
