### ISSUE TITLE
A few questions on VerneMQ

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#61]
We are in the process of choosing an MQTT broker to use as a basis for our messaging infrastructure, and I would love to obtain an answer to the following questions:

1. Does VerneMQ support a clustered mode so that we can have multiple nodes to which clients can connect?
1. In case it does, will nodes forward `PUBLISH` packets from clients in one node to subscribed clients in different nodes?
1. Also in case clustering is supported, if a client disconnects and connects to a different node, will "offline" messages for this client's subscriptions still be delivered?
1. Are retained and "offline" messages persisted somehow (some Cassandra or LevelDB)?
1. How easy it is to write custom plugins?

I hope these are not too many questions :-) VerneMQ definitely looks very promising, and we are pending towards its adoption.

**Comment by dergraf** [comment]
Hi there!

Questions 1-4: Definitely yes!
Question 5: we think it's easy, check out the guide https://verne.mq/docs/plugin_development.html 

Hope that helps!
Cheers

**Comment by testark** [comment]
@dergraf Thank you so much for your quick answer. Could I ask one last question for now? I read the following in the docs:

> Currently the persisted QoS 1 & QoS 2 messages aren’t replicated to the other nodes by the default message store backend. Currently you will loose the offline messages stored on the leaving node.

Is there currently any way to get around this (perhaps using a different storage backend)?

**Comment by dergraf** [comment]
That's exactly what you can do, however the process isn't very streamlined yet. Get in touch with us over email, we do provide such services.

**Comment by testark** [comment]
@dergraf That's great. Thank you very much!

**Comment by elhamkazemi** [comment]
Hi there, 
In danger for case (make a stopped node leave), how we can save the offline messages stored on the leaving node. is there a way to replicate offline messages to the other nodes?
