### ISSUE TITLE
Webhooks auth stop working

### ISSUE THREAD

**Issue by zapotek6** [erlio/vernemq#612]
### Environment

- VerneMQ Version: docker image erlio/docker-vernemq:1.3.0
- OS: COS (Container optimized OS image from Google) that run on Google Kubernetes Engine (GKE)
- Erlang/OTP version (if building from source):

It's a cluster of three nodes. Node are made with the official docker image. Every container run on the Google's Kubernetes gke enviroment.
Nodes are configured to use webhooks plugin for the authentication/authorization of:
- register
- subscribe
- publish

node config is availables here https://gist.github.com/zapotek6/a4d4732c89f56d1ea478cbd4a4c289e2

### Expected behavior

- I'm expecting from the webhooks_plugin a consistent behaviour by the time.

### Actual behaviour
I'm running some load test prior to put in production the systems. I'm running about 6k devices, every devices has it's own credentials set. Some times I run the devices with a low publish rate, about 1 publish/hour, others time 1 publish every 2/3 minutes (time is random per device).
Sometimes I got authentication/authorization problem with the devices. For devices already connected I can not publish anymore and new devices can't connect because not authorized.

The strange things is that I get many errors in the error.log file:
```
2018-02-16 12:53:29.620 [error] <0.18216.7>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
```
My first though was to check the auth backend, but further analysis show me that my backend did not receive any http request. VerneMQ reports timeouts, but it do not makes any http request toward the backend.
I've used tcpdump and wireshark to see that behaviour.

One time when the problem happened, I was able to immediately run a simple test. I successfully run a curl directed to and endpoint an it worked. Moreover I was able to see the http traffic generated by the curl call, but I was not able to see the http traffic that the webhooks was supposed to generate.
Currently I'm using the webhooks with cache (300 seconds), but I've experienced this issue also without.  

In order to recover the cluster, I've to deregister and register again the webhooks endpoints. Or a more brutal solution is to restart every VerneMQ instance.

Thanks in advance to anyone that is willing to share ideas or give suggestions

**Comment by ioolkos** [comment]
@zapotek6 thanks for reporting!
Do you only get the errors you mentioned in the log? no reports of any crashed processes? is the internal HTTP client crashed?
@larshesel @dergraf have we seen anything like that? it seems pretty weird that the plugin doesn't even issue any HTTP requests here.

**Comment by larshesel** [comment]
The connect_timeout normally happens when the endpoint is not able to keep up with the requests. If the connection pool gets exhausted and all the connections are blocked waiting for the timeout to happen then something like what you describe could happen. If no requests arrive at the endpoint at all, then there is likely something wrong with the setup - what does the outgoing requests from the vernemq node look like?

In any case it sounds quite similar to: https://github.com/erlio/vernemq/issues/556#issuecomment-351919749

**Comment by zapotek6** [comment]
thanks for your reply. I had got again the authentication problem and I made some more test.
First I reduced the cluster size to one instance (just to reduce noise and simplify the debug), without affecting the instance 0.
After the resize I checked that the instance 0 still had the authentication problem.
I run in the instance 0 container tcpdump, I made it listening on any interface. To avoid noise I filtered out the traffic between kubectl and the container.
I configured one client to use the clear text mqtt connection on port 1883. 
As I'm using the webhooks with a cache of 300s, I kept the client stopped for about 25
[test.log](https://github.com/erlio/vernemq/files/1743324/test.log)
 minutes. 
Finally I started only that mqtt client. Suddenly it started failing with mqtt.conack.val = 5 (connection refused: not authorized).
I let the client made 6 connection attempts, then I stopped it. 
Then I've analyzed with wireshark the traffic captured. In between of any connection attempt, so from the very first SYN packet to the RST sent sent by the server, there's no http traffic directed to the backend.
I tested the connectivity to the backend with curl and it was working.

For sure there are situations during the test in which the auth backend became slow, but the fact that webhooks_plugin does not recover is the main concern.

![capture](https://user-images.githubusercontent.com/5347769/36470500-53614a9c-16eb-11e8-8c0b-0817646316b0.png)
[test.log](https://github.com/erlio/vernemq/files/1743335/test.log)

===============================================================
I did not find any crash evidence searching in current files logs.
I've reactivated the authentication deregistering and registering again the hooks.

**Comment by ioolkos** [comment]
@zapotek6 allright, thanks for the detailled problem report!
We'll try to analyse it and come up with ideas what might be happening here.

**Comment by ioolkos** [comment]
What is he status of the cache at the point of failure? `vmq-admin webhooks cache show`
https://vernemq.com/docs/plugindevelopment/webhookplugins.html

Do you have some further insights or hunches where this could come from?

**Comment by zapotek6** [comment]
@ioolkos first of all thanks for your time.
Yesterday with the operation of deregister and register the webhooks I've restored the service.
This morning I've got again the problem. So I've tried to collect more information.

## VerneMQ Debug info

### VerneMQ webhooks status
```
root@vernemq-sts-0:/# vmq-admin webhooks show
+--------------+-----------------------------------------------------------------------+-----------+
|     hook     |                               endpoint                                |base64paylo|
+--------------+-----------------------------------------------------------------------+-----------+
|auth_on_subscr|http://webauth.myserver.dom/subscr|   true    |
|auth_on_regist|http://webauth.myserver.dom/regist|   true    |
|auth_on_publis|http://webauth.myserver.dom/publis|   true    |
+--------------+-----------------------------------------------------------------------+-----------+
```


### VerneMQ webhooks cache status
```
root@vernemq-sts-0:/# vmq-admin webhooks cache show
+------+----------------------------------------------------------------------+--------------+-----+
| stat |                               endpoint                               |     hook     |value|
+------+----------------------------------------------------------------------+--------------+-----+
|misses|http://webauth.myserver.dom/subsc|auth_on_subscr|16064|
|misses|http://webauth.myserver.dom/regis|auth_on_regist|21094|
|misses|http://webauth.myserver.dom/publi|auth_on_publis|53002|
| hits |http://webauth.myserver.dom/subsc|auth_on_subscr| 40  |
|entrie|http://webauth.myserver.dom/subsc|auth_on_subscr|14704|
|entrie|http://webauth.myserver.dom/regis|auth_on_regist|8071 |
|entrie|http://webauth.myserver.dom/publi|auth_on_publis|7649 |
+------+----------------------------------------------------------------------+--------------+-----+
```

### VerneMQ cluster status
```
root@vernemq-sts-0:/# vmq-admin cluster show
+----------------------------------------------------+-------+
|                        Node                        |Running|
+----------------------------------------------------+-------+
|VerneMQ@vernemq-sts-2.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-1.hub2.default.svc.cluster.local| true  |
|VerneMQ@vernemq-sts-0.hub2.default.svc.cluster.local| true  |
+----------------------------------------------------+-------+
```


### VerneMQ listerners status
```
root@vernemq-sts-0:/# vmq-admin listener show
+-------+-------+----------+-----+----------+---------+
| type  |status |    ip    |port |mountpoint|max_conns|
+-------+-------+----------+-----+----------+---------+
| http  |running|10.28.1.15|8888 |          |  50000  |
|  vmq  |running|10.28.1.15|44053|          |  50000  |
|mqttwss|running| 0.0.0.0  |8083 |          |  50000  |
|mqttws |running|10.28.1.15|8080 |          |  50000  |
| mqtts |running|10.28.1.15|8883 |          |  50000  |
| mqtt  |running|10.28.1.15|1883 |          |  50000  |
+-------+-------+----------+-----+----------+---------+
```


### VerneMQ sessions
```
root@vernemq-sts-0:/# vmq-admin session show
*** does not return any value ***
```


### VerneMQ metrics
```
root@vernemq-sts-0:/# vmq-admin metrics show
gauge.queue_processes = 0
gauge.retain_memory = 21152
gauge.retain_messages = 0
gauge.router_memory = 11920
gauge.router_subscriptions = 0
gauge.system_utilization_scheduler_4 = 35
gauge.system_utilization_scheduler_3 = 8
gauge.system_utilization_scheduler_2 = 38
gauge.system_utilization_scheduler_1 = 46
gauge.system_utilization = 32
gauge.vm_memory_ets = 62914464
gauge.vm_memory_code = 12841712
gauge.vm_memory_binary = 6906136
gauge.vm_memory_atom_used = 560029
gauge.vm_memory_atom = 586369
gauge.vm_memory_system = 91476192
gauge.vm_memory_processes_used = 32414088
gauge.vm_memory_processes = 32447728
gauge.vm_memory_total = 123923920
counter.system_wallclock = 210170994
counter.system_runtime = 13165180
gauge.system_run_queue = 0
counter.system_reductions = 21045359270
counter.system_io_out = 11119135999
counter.system_io_in = 8487062970
counter.system_words_reclaimed_by_gc = 95792628168
counter.system_gc_count = 376784151
counter.system_exact_reductions = 21045359142
counter.system_context_switches = 101319044
counter.socket_open = 296881
counter.socket_close = 296717
counter.socket_error = 0
counter.bytes_received = 29247063
counter.bytes_sent = 10305463
counter.mqtt_connect_received = 212314
counter.mqtt_publish_received = 53002
counter.mqtt_puback_received = 43665
counter.mqtt_pubrec_received = 0
counter.mqtt_pubrel_received = 0
counter.mqtt_pubcomp_received = 0
counter.mqtt_subscribe_received = 16104
counter.mqtt_unsubscribe_received = 0
counter.mqtt_pingreq_received = 3391803
counter.mqtt_disconnect_received = 0
counter.mqtt_connack_accepted_sent = 8077
counter.mqtt_connack_unacceptable_protocol_sent = 0
counter.mqtt_connack_identifier_rejected_sent = 0
counter.mqtt_connack_server_unavailable_sent = 0
counter.mqtt_connack_bad_credentials_sent = 0
counter.mqtt_connack_not_authorized_sent = 204076
counter.mqtt_publish_sent = 43665
counter.mqtt_puback_sent = 50836
counter.mqtt_pubrec_sent = 0
counter.mqtt_pubrel_sent = 0
counter.mqtt_pubcomp_sent = 0
counter.mqtt_suback_sent = 15797
counter.mqtt_unsuback_sent = 0
counter.mqtt_pingresp_sent = 3391803
counter.mqtt_publish_auth_error = 2835
counter.mqtt_subscribe_auth_error = 307
counter.mqtt_invalid_msg_size_error = 0
counter.mqtt_puback_invalid_error = 0
counter.mqtt_pubrec_invalid_error = 0
counter.mqtt_pubcomp_invalid_error = 0
counter.mqtt_publish_error = 0
counter.mqtt_subscribe_error = 0
counter.mqtt_unsubscribe_error = 0
counter.queue_setup = 8077
counter.queue_teardown = 8077
counter.queue_message_drop = 0
counter.queue_message_unhandled = 0
counter.queue_message_in = 43665
counter.queue_message_out = 43665
counter.client_expired = 0
counter.cluster_bytes_received = 0
counter.cluster_bytes_sent = 826279
counter.cluster_bytes_dropped = 0
```

### Tracking a client session
```
root@vernemq-sts-0:/# vmq-admin trace client client-id=76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001
No sessions found for client "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001"
New session with PID <7251.4953.23> found for client "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001"
<7251.4953.23> MQTT RECV: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNECT(c: 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001, v: 4, u: TT-cDZ1Z2szaWpsaWxhMg==, p: , cs: 1, ka: 60)
<7251.4953.23> Calling auth_on_register({{10,95,20,4},42946},{[],
                                                              <<"76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001">>},TT-cDZ1Z2szaWpsaWxhMg==,,true)
<7251.4953.23> Hook returned {error,error}
<7251.4953.23> MQTT SEND: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNACK(sp: 0, rc: 5)
<7251.4953.23> Trace session for 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001 stopped
New session with PID <7251.5321.23> found for client "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001"
<7251.5321.23> MQTT RECV: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNECT(c: 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001, v: 3, u: TT-cDZ1Z2szaWpsaWxhMg==, p: , cs: 1, ka: 60)
<7251.5321.23> Calling auth_on_register({{10,28,1,1},44032},{[],
                                                             <<"76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001">>},TT-cDZ1Z2szaWpsaWxhMg==,,true)
<7251.5321.23> Hook returned {error,error}
<7251.5321.23> MQTT SEND: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNACK(sp: 0, rc: 5)
<7251.5321.23> Trace session for 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001 stopped
New session with PID <7251.5990.23> found for client "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001"
<7251.5990.23> MQTT RECV: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNECT(c: 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001, v: 4, u: TT-cDZ1Z2szaWpsaWxhMg==, p: , cs: 1, ka: 60)
<7251.5990.23> Calling auth_on_register({{10,28,1,1},46106},{[],
                                                             <<"76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001">>},TT-cDZ1Z2szaWpsaWxhMg==,,true)
<7251.5990.23> Hook returned {error,error}
<7251.5990.23> MQTT SEND: CID: "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001" CONNACK(sp: 0, rc: 5)
<7251.5990.23> Trace session for 76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001 stopped
New session with PID <7251.6267.23> found for client "76a6c58b-ae27-403a-b5cb-397d9a7ef5ec-00001"
```

### Looking for crash in log files
```
root@vernemq-sts-0:/var/log/vernemq# ls -ltr
total 76400
-rw-r--r-- 1 vernemq vernemq      250 Feb 20 00:39 run_erl.log
-rw-r--r-- 1 vernemq vernemq        0 Feb 20 00:39 crash.log.1
-rw-r--r-- 1 vernemq vernemq 10296821 Feb 21 00:00 error.log.2
-rw-r--r-- 1 vernemq vernemq 10488693 Feb 21 04:14 console.log.4
-rw-r--r-- 1 vernemq vernemq 10487625 Feb 21 12:04 console.log.3
-rw-r--r-- 1 vernemq vernemq 10486114 Feb 21 14:15 error.log.1
-rw-r--r-- 1 vernemq vernemq    23193 Feb 21 23:27 error.log.0
-rw-r--r-- 1 vernemq vernemq  3201995 Feb 21 23:27 console.log.2
-rw-r--r-- 1 vernemq vernemq 10487654 Feb 22 10:48 console.log.1
-rw-r--r-- 1 vernemq vernemq 10489456 Feb 22 11:21 console.log.0
-rw-r--r-- 1 vernemq vernemq    10615 Feb 22 11:25 erlang.log.1
-rw-r--r-- 1 vernemq vernemq 10141087 Feb 22 11:29 error.log
-rw-r--r-- 1 vernemq vernemq  2058712 Feb 22 11:30 console.log
root@vernemq-sts-0:/var/log/vernemq# grep -i crash *
*** no results ***
root@vernemq-sts-0:/var/log/vernemq#
```

### Tail error.log
```
root@vernemq-sts-0:/var/log/vernemq# tail error.log
2018-02-22 11:28:29.319 [error] <0.19245.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:29.340 [error] <0.19250.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:29.358 [error] <0.19254.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:29.376 [error] <0.19262.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:29.422 [error] <0.19258.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:29.460 [error] <0.19256.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:41.210 [error] <0.19401.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:28:41.214 [error] <0.19406.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:29:45.694 [error] <0.20439.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout
2018-02-22 11:29:59.053 [error] <0.20950.24>@vmq_webhooks_plugin:call_endpoint:480 calling endpoint failed due to connect_timeout


[debug-info.md.txt](https://github.com/erlio/vernemq/files/1747750/debug-info.md.txt)

**Comment by ioolkos** [comment]
@zapotek6 ok, thanks!
What is your maximum register rate per second?
Let's suppose for a moment that every connection in the pool is blocked (100 connections). Then no connection would be available to call the configured WebHooks.

The next thing would then be the question why the connections are blocked for longer than 60 seconds, because that's the default timeout value too <- @larshesel is this correct? Should we try some other values there, or make them configurable?

I'm refering to the following code:
https://github.com/erlio/vernemq/blob/320192be1cde04d7656f42a12a4f63b0880437cb/apps/vmq_webhooks/src/vmq_webhooks_plugin.erl#L333

**Comment by zapotek6** [comment]
@ioolkos in the latest test I did not reach 10 connection/publish per second. But the backend serves also a lot of other requests made directly from the clients. So when I start 6k clients I generate a lot of load.
For sure we need to improve the capacity of our the http backend, but this would not eliminate my concern.
I think that it's normal that if the http auth backend cannot step up the request rate coming from VerneMQ the client requests cannot be fulfilled, and it's not a problem of the broker.
I understand that the pool has a finite dimension, but my question is if there's some way to avoid to end up in the situation in which the webhook_plugin stall and can not recover. This situation maybe could also be reached in case of network problems along the path VerneMQ - auth backend.
For instance, is it possible to reply with a nack any request that need to be forwarded to the backend if there's no available connection in the pool?


Last week I've built a VerneMQ built from source with an increased pool size. Until yesterday I didn't give to it a try. Yesterday after your reply I deployed the cluster with the new image and I started a new test session. This would not eliminate the concern but I think could help in sending away the critical situation.

![pool size change](https://user-images.githubusercontent.com/5347769/36617787-1b2f8c92-18e9-11e8-8a80-ef2dae21ee53.png)

Have a good weekend
Mirko

**Comment by codeadict** [comment]
I had some troubles with hackney pool before, not with this specific plugin but making the max_connections configurable seems like a wise move.

**Comment by larshesel** [comment]
yeah, and the timeout should be configurable as well..

**Comment by codeadict** [comment]
Added a PR for this one https://github.com/erlio/vernemq/pull/640

**Comment by michaelfung** [comment]
@zapotek6 , I was having the same issue as you. Are you still having this problem now after the PR #640 ?

**Comment by larshesel** [comment]
Another fix was merged recently where the bug could cause the connection pool to fill up and cause the connection timeouts. It's probably what was causing this in the first place. See #708 .

Closing this one for now.
