### ISSUE TITLE
Shared subscriptions support for clustered mode? (question)

### ISSUE THREAD

**Issue by mikestov** [erlio/vernemq#613]
Hello,

Just a quick question: Does VerneMQ support shared subscriptions in clustered mode? I'm evaluating different MQTT brokers for our advanced use case (500k devices) and couldn't find a direct answer to this question in the documentation.

Thanks!

**Comment by ioolkos** [comment]
@mikestov thanks for asking :)
Yes, Shared subscriptions are supported in clustered mode. In fact, you can configure what policy you prefer for message routing to shared subscribers on different cluster nodes (`random`, `prefer_local` or `local_only`).
This is mentioned in the doc here https://vernemq.com/docs/configuration/shared_subscriptions.html

**Comment by mikestov** [comment]
I'm having another issue -- I'm running VerneMQ in docker and sending/receiving messages is working fine. However, if I use the sample topic name for shared subscriptions ($share/sharename/topic), the message does not come through. I've used mosquitto_pub and sub for this with the syntax:
mosquitto_sub -t '$share/sharename/topic' and
mosquitto_pub -t '$share/sharename/topic' -m "Testing"

I also tested with Paho 1.2 and still could not get it to work when prefixing the topic name. I have the current shared subscription policy as:

➜  ~ docker exec vernemq1 vmq-admin show shared_subscription_policy
+------------------+--------------------------+
|       node       |shared_subscription_policy|
+------------------+--------------------------+
|VerneMQ@172.17.0.2|          random          |
+------------------+--------------------------+

And I am not running as a cluster at the moment:

➜  ~ docker exec vernemq1 vmq-admin cluster show
+------------------+-------+
|       Node       |Running|
+------------------+-------+
|VerneMQ@xxx.xxx.xxx.xxx| true  |
+------------------+-------+

Any advice would be very helpful! Thanks.

**Comment by mikestov** [comment]
Also wanted to add I'm using the 1.3.0 docker image:
erlio/docker-vernemq       1.3.0               bebb034fa97e        3 weeks ago         255MB

**Comment by ioolkos** [comment]
Hi @mikestov you need to publish using a topic name without the $share and sharename of the subscription:
mosquitto_pub -t 'topic' -m "Testing"

Look up the sections in the MQTT5 spec for an explanation.

**Comment by mikestov** [comment]
That was it. It's working as expected now. I'm going to read the MQTT 5 spec to understand things better. Thanks for the help!
