### ISSUE TITLE
Support for WebSockets permessage-deflate extension?

### ISSUE THREAD

**Issue by Eric24** [erlio/vernemq#615]
Does the current version of VerneMQ support the permessage-deflate extension (https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-19)? If not, are there any plans for this in the future?

**Comment by larshesel** [comment]
Hi, compression for websockets is currently no supported, though it would not be a hard thing to add. However, the websocket server (cowboy 1.x) we currently use does not support the permessage-deflate and we'd have to upgrade to cowboy 2.x to do that which isn't planned for VerneMQ 1.x at the moment and VerneMQ 2.x doesn't have a set release date yet other than 'some time during 2018'. See also this issue for more information https://github.com/erlio/vernemq/issues/607
