### ISSUE TITLE
Logging in Elixir Plugin

### ISSUE THREAD

**Issue by NickNeck** [erlio/vernemq#621]
Hello,

I have some errors to log and I do this with Elixirs default backend console and some metadata. 
```
config :logger, backends: [:console]

config :logger, :console,
  format: "$time [$level] $message - $metadata",
  metadata: [:foo, :bar, :baz],
  level: :info
```
If i call
```
Logger.error("Uups", [foo: "foo"])
```
I find my log in `erlang.log.*`
```
14:44:03.257 [error] Uups
```
without the metadata.

Can I config VerneMQ that the log goes to the `console` or `console.log`?

It seems `log.console = console` has no effect.

**Comment by ioolkos** [comment]
@NickNeck thanks, that's a really good question. I have no real answer though.

In case we haven't done any general thinking on this, we could start a discussion here.
- How should plugins do logging?
- Should plugins be allowed to log to the VerneMQ logs?
- Are there any specifics for Elixir plugins?
- What is the current situation?
and of course hopefully clear up your questions.

**Comment by larshesel** [comment]
VerneMQ uses Lager to do all logging and it is likely the interplay between the Elixir default backend and Lager which is causing problems. I do not know how this should work, but I would look into what existing problems/issues/solutions people have come up with for making logging work from Elixir together with Lager.  One possible solution could maybe be to use a Lager backend for the Elixir logger. I found some information about that here: https://github.com/erlang-lager/lager#elixir-support, though I've never tried it.

**Comment by NickNeck** [comment]
Thank you, for your answer.

I have tried [LoggerLagerBackend](https://github.com/jonathanperret/logger_lager_backend) but with no success. The plugin compiles and the server can be started. But the logs go still to `erlang.log.*`.
My config:
```
config :logger, backends: [LoggerLagerBackend]

config :logger, LoggerLagerBackend,
  format: "$time [$level] $message - $metadata",
  metadata: [
    :foo
  ],
  level: :warn
```
From the LoggerLagerBackend docu:
> This sends all messages of level debug or higher to lager. They will then be subject to filtering and routing according to whichever lager config you have in place.

How can I figure out the lager config?

**Comment by NickNeck** [comment]
The next try. To be flexible I have written my own [LogLagerBacken](https://github.com/hrzndhrn/log_lager_backend). The test worked fine. If I do the same in my plugin I get a crash report.
The code in my plugin:
```
Logger.add_backend LogLagerBackend
``` 
The crash report:
``` 
19:10:07.448 [error] CRASH REPORT Process <0.397.0> 
with 0 neighbours exited with reason: 
no case clause matching {'EXIT',{undef,[{'Elixir.LogLagerBackend',
init,['Elixir.LogLagerBackend'],[]},{gen_event,server_add_handler,4,
[{file,"gen_event.erl"},{line,429}]},{gen_event,handle_msg,5,
[{file,"gen_event.erl"},{line,274}]},{proc_lib,init_p_do_apply,3,
[{file,"proc_lib.erl"},{line,247}]}]}} in'Elixir.Logger.Watcher':init/1 line 25 
in gen_server:init_it/6 line 352
``` 
Let's see what I try next.

**Comment by NickNeck** [comment]
It is logging! I have learned the last day's something about `umbrella` apps and `distillery`. I will publish my package today and write a little howto in my next comment. I am sure that `LoggerLagerBackend` will also work in a `VerneMQ` plugin, but I will do some things in a little bit different way.

**Comment by larshesel** [comment]
That's great! Very cool. If you feel like it you're very welcome to add the howto to the wiki section: https://github.com/erlio/vernemq/wiki

**Comment by NickNeck** [comment]
[LogLagerBackend](https://hex.pm/packages/log_lager_backend) is available on hex.
The backend can be configured in an Elixir Plugin like this: 
```
defmodule MyVernePlugin.Application do
...
  def start(_type, _args) do
    Logger.remove_backend(:console)
    Logger.add_backend(LogLagerBackend)
    Logger.configure_backend(
      LogLagerBackend,
      format: "$message - $metadata",
      metadata: [:foo],
      level: :info
    )   
...
  end
end
```
I will add this info to the wiki if I find a little bit time.

A configuration via `config/config.exs` does not work. I guess the `sys.config` will be not read when the plugin starts.

`console.log:`
```
2018-03-05 15:26:22.873 [warning] <0.499.0>@Elixir.MyVernePlugin:on_publish/6:31 How Do You Do - foo=bb-8
2018-03-05 15:26:22.873 [error] <0.499.0>@Elixir.MyVernePlugin:on_publish/6:31 Da, Gefahr! - foo=bb-8
```

**Comment by NickNeck** [comment]
Next update, last update 😉 
### Logging in your Elixir Plugin
 Add [LogLagerBackend](https://github.com/hrzndhrn/log_lager_backend) to your plugin deps `{:log_lager_backend, "~> 0.0.1"}`.
Add an `advanced.config` file next to your `vernemq.conf` file (same folder eg. `/etc/vernemq`). 

```erlang
%% advanced.config
[
 {logger,
     [{backends,['Elixir.LogLagerBackend']},
      {handle_otp_reports,false},
      {level,debug},
      {'Elixir.LogLagerBackend',
          [{format,<<"$message - $metadata">>},
           {metadata,[fool]},
           {level,warn}]}]}
].
```
If you don't want metadata, delete it. 
The option `{handle_otp_reports, false}` prevents that otp reports will be logged twice.

Use `Logger` as usual.

**Comment by ioolkos** [comment]
You rock! :smile: :+1:
