### ISSUE TITLE
Bridge remapping of topics

### ISSUE THREAD

**Issue by rastomatti** [erlio/vernemq#622]
### Environment

- VerneMQ Version: Rpi-build, fork
- OS: Raspbian
- Erlang/OTP version (if building from source):

Hi folks,

I have 2 vernemq-brokers in my system, one acting as a bridge, and one as a normal broker.
I can't seem to find a solution to a problem I have:
When I send data from a client in one end (i.e. Topic: Kitchen/Temperature) to my bridge-broker, I want this bridge to remap the topic so it sends data to the normal broker with a new root-topic (i.e. House1/Kitchen/Temperature). Is there any way of doing this? Also I need this the other way (removing when being sent from the normal broker).

Illustration:
![image](https://user-images.githubusercontent.com/36088995/36854382-27ae5e76-1d71-11e8-8b58-2e6f8d7a0c9a.png)

**Comment by larshesel** [comment]
Hi @rastomatti, I'm not sure if this is achievable with the bridge plugin, but I'm not certain. It would certainly be possible with a custom plugin, though. You could try and as the question on the slack channel, maybe someone there has more experience with the bridge configuration there: http://slack-invite.vernemq.com/

Closing this issue as it is not a VerneMQ issue or feature request.
