### ISSUE TITLE
Will message

### ISSUE THREAD

**Issue by medaboub** [erlio/vernemq#627]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):

### Expected behavior

- publish WILL message will be authenticated on time of publish when client disconnected
or add Modifiers on on_publish event.
### Actual behaviour

- I would like to do background job in auth_on_publish then change message payload before publishing it since on_publish method can't edit topic and payload and on_deliver method will do background job for every user subscribed to topic. the problem is for WILL message because the  auth_on_publish  will do background job before publishing it later when client disconnected and then the changed payload will have no sence at this time. haw can I do in this senario ?

**Comment by ioolkos** [comment]
@medaboub thanks for your question!
Hm, I kind of see what you'd like to do. Still, do you see another way to achieve what you like than with a WILL message? 
@larshesel @dergraf should we add modifiers to the on_publish event? what was the reasoning there?

**Comment by medaboub** [comment]
auth_on_publish will check if user has right to publish in specific topic and payload.  this is good to check that WILL message is ok. but we can not do tasks related to WILL message because it will be published later when device disconnect. we need some event to do work related to WILL message at publish time.
we can not do tasks in on_deliver event because server overhead tasks will be repeated for every subscribed user to WILL message.

**Comment by medaboub** [comment]
also i need to change payload of WILL message to take into consideration some informations carried from database. so on_publish event can be used to do tasks but can not change payload and topic.

**Comment by medaboub** [comment]
I changed on_publish_hook on vernemq_dev and edit  vmq_mqtt_fsm.erl to this :
`-spec on_publish_hook(flag(), module(), msg(), list()) -> ok | {error, _}.
on_publish_hook(A, RegView, Msg,HookParams) ->
case vmq_plugin:all_till_ok(on_publish, HookParams) of
  ok ->NewMsg=Msg; 
  {ok, ChangedPayload} when is_binary(ChangedPayload) -> NewMsg= Msg#vmq_msg{payload=ChangedPayload}; 
  {ok, Args} when is_list(Args) ->
  #vmq_msg{routing_key=Topic,
  payload=Payload,
  qos=QoS,
  retain=IsRetain,
  mountpoint=MP} = Msg,  
  ChangedTopic = proplists:get_value(topic, Args, Topic),
  ChangedPayload = proplists:get_value(payload, Args, Payload),
  ChangedQoS = proplists:get_value(qos, Args, QoS),
  ChangedIsRetain = proplists:get_value(retain, Args, IsRetain),
  ChangedMountpoint = proplists:get_value(mountpoint, Args, MP),
  NewMsg=Msg#vmq_msg{routing_key=ChangedTopic,
                  payload=ChangedPayload,
                  qos=ChangedQoS,
                  retain=ChangedIsRetain,
                  mountpoint=ChangedMountpoint}  
  end,
  vmq_reg:publish(A, RegView, NewMsg).
%%on_publish_hook(Other, _) -> Other.

`

is this has effect on the vernemq performance and bihaviours ???

**Comment by larshesel** [comment]
Hi, thanks for the proposal.

We can't change the way the hook behaves as that would be a breaking change. Changing the `on_publish` from an `all` hook to an `all_till_ok` hook changes the semantics as the `all` hook would execute all hooks registered, whereas the `all_till_ok` will stop if the one of the registered hooks in the chain returns success or an error.

I don't see at the moment how we could change this behaviour in a backwards compatible way, but it's certainly something we should take into consideration while preparing VerneMQ 2.0. Proposals are of course very welcome!
