### ISSUE TITLE
ws on port 800 doesn't work, ws :8888 does

### ISSUE THREAD

**Issue by ozra** [erlio/vernemq#628]
### Environment

- VerneMQ Version: 1.2.0
- OS: Ubuntu 17.10

### Expected behavior

- Configured `listener.ws.default = 127.0.0.1:800`
- Vernemq should listen to port 800 for websocket connection

### Actual behaviour

- It did not. Two developers here actually spent 9 hours each trying to figure out why the project didn't work when ran from browser with ws, instead of tcp, like from the node-clients, android, etc. Using the "idiot-method", I followed the examples, and baam, it worked when using 8888.

**Comment by ioolkos** [comment]
@ozra thanks for your effort & info, great to see you using VerneMQ.

The problem has to do with Linux privileged ports (< 1024), I think; unless I misunderstand what you wish to achieve.

**Comment by ozra** [comment]
Aha, I'll forward that information! This was clearly a lack of knowledge in the team and on my part - I'll close the issue in shame and gratitude XD.

**Comment by ioolkos** [comment]
It's certainly not your fault :)
& it's an example from the template: https://github.com/erlio/vernemq/blob/master/apps/vmq_server/priv/vmq_server.schema#L524
I'll add a note about that right there or in the docs.

Thanks again for bringing it to our attention!
