### ISSUE TITLE
Verbose Logging

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#63]
(First, sorry if I'm opening many issues but we are very close to adopting VerneMQ and I just need to clear a few things out.)

I changed the logging level to `debug` and the logging target to `both`, but I still don't get a lot of logging. For example, it would be great for debugging purposes if I could increase logging so that every communication (`CONNECT`, `CONNACK`, `PUBLISH` and the contents, `SUBSCRIBE` and the contents, etc) is logged. Is there any out-of-the-box way of getting these events logged? Or do I have to implement "logging hooks" to achieve this?

**Comment by dergraf** [comment]
No problem! Every issue gives us a chance to improve VerneMQ! Thank you for that.

We haven't implemented those low level debug calls yet as we typically debug the system using Erlang traces instead of Debug logs.

**Comment by testark** [comment]
@dergraf  thanks for your quick answer! i ser... I'm really no Erlang expert... Could you kindly point out to me how to do it?

**Comment by dergraf** [comment]
If you can attach to a VerneMQ shell e.g. through ``vernemq attach`` you could dig into tracing. We've packaged some interesting tools for that as well, namely ``recon`` and ``eper`` both libraries that simplifies operating an Erlang node.

``eper`` comes with an interesting module called ``redbug``, which gives a great abstraction to the Erlang tracing and debugging utilities. Moreover ``redbug`` has been built to be used to debug/trace a production system.

However, setting up the correct traces requires to know the code and this is not something we should expect the 'average' user to know. 
We add more debug statements in a future release!

**Comment by testark** [comment]
@dergraf I see. Thank you very much.
