### ISSUE TITLE
Fatal - Handshake Failure - malformed_handshake_data with SSL listener

### ISSUE THREAD

**Issue by jimfunk** [erlio/vernemq#632]
### Environment

- VerneMQ Version: 1.3.0
- OS: openSUSE Leap 15 (same as tumbleweed at this point)
- Erlang/OTP version (if building from source): 20.2.2

I tried with my own certificates, and for testing I am using the certificates from the test directory in the repo. Here are the relevant configuration items:

    listener.ssl.default = 0.0.0.0:8883
    listener.ssl.cafile = /etc/vernemq/ssl/all-ca.crt
    listener.ssl.certfile = /etc/vernemq/ssl/server.crt
    listener.ssl.keyfile = /etc/vernemq/ssl/server.key

### Expected behavior

Should be able to connect to socket using an mqtt client or openssl s_client.

### Actual behaviour

The following log message in console.log:

    2018-03-15 07:38:44.056 [info] <0.649.0> TLS server: In state hello at tls_connection.erl:721 generated SERVER ALERT: Fatal - Handshake Failure - malformed_handshake_data

The following output from openssl:

    # openssl s_client -connect 127.0.0.1:8883 -CAfile /etc/vernemq/ssl/all-ca.crt
    CONNECTED(00000003)
    139678904256320:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1399:SSL alert number 40
    ---
    no peer certificate available
    ---
    No client certificate CA names sent
    ---
    SSL handshake has read 7 bytes and written 176 bytes
    Verification: OK
    ---
    New, (NONE), Cipher is (NONE)
    Secure Renegotiation IS NOT supported
    Compression: NONE
    Expansion: NONE
    No ALPN negotiated
    SSL-Session:
        Protocol  : TLSv1.2
        Cipher    : 0000
        Session-ID:
        Session-ID-ctx:
        Master-Key:
        PSK identity: None
        PSK identity hint: None
        SRP username: None
        Start Time: 1521125659
        Timeout   : 7200 (sec)
        Verify return code: 0 (ok)
        Extended master secret: no
    ---

**Comment by ioolkos** [comment]
@jimfunk thanks a lot for opening this issue.
The configuration and procedure as you described it works for me. As this information doesn't really help you ... let's think what could go wrong here.
The client process seems to be unable to read the all-ca.crt, so how do the file permissions on that file look?

**Comment by jimfunk** [comment]
644 for the files and 755 for the leading paths. I can confirm the client is successfully opening the CA using strace:

    openat(AT_FDCWD, "/etc/vernemq/ssl/all-ca.crt", O_RDONLY) = 3

**Comment by larshesel** [comment]
The openssl output seems to indicate there are no ciphers available. I would expect it to say something like:

```
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
```

Can you verify that both client and server have usable ciphers available?

**Comment by jimfunk** [comment]
Client ciphers:

    # openssl ciphers
    ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA

I'm not sure how to get the server ciphers.

**Comment by larshesel** [comment]
on the server attach to the Erlang shell and execute the command `rp(vmq_ssl:opts([])).` On my local machine it looks as follows (you might have to switch to the vernemq user or be root to be able to attach):
```
$ vernemq attach
[SNIP]..
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:64] [hipe] [kernel-poll:true]

Eshell V9.2.1  (abort with ^G)
(VerneMQ@127.0.0.1)1> rp(vmq_ssl:opts([])).
[{cacertfile,undefined},
 {certfile,undefined},
 {keyfile,undefined},
 {ciphers,["ECDHE-ECDSA-AES256-GCM-SHA384",
           "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
           "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
           "ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384",
           "ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384",
           "DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256",
           "AES256-GCM-SHA384","AES256-SHA256",
           "ECDHE-ECDSA-AES128-GCM-SHA256",
           "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
           "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
           "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
           "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
           "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256",
           "ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA",
           "DHE-DSS-AES256-SHA","ECDH-ECDSA-AES256-SHA",
           "ECDH-RSA-AES256-SHA","AES256-SHA","ECDHE-ECDSA-AES128-SHA",
           "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
           "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","AES128-SHA"]},
 {fail_if_no_peer_cert,false},
 {verify,verify_none},
 {verify_fun,{#Fun<vmq_ssl.0.79469420>,no_crl}},
 {depth,1},
 {versions,['tlsv1.2']}]
```

**Comment by jimfunk** [comment]
This is what I get:

```
(VerneMQ@127.0.0.1)1> rp(vmq_ssl:opts([])).
[{cacertfile,undefined},
 {certfile,undefined},
 {keyfile,undefined},
 {ciphers,["ECDHE-ECDSA-AES256-GCM-SHA384",
           "ECDHE-RSA-AES256-GCM-SHA384","ECDHE-ECDSA-AES256-SHA384",
           "ECDHE-RSA-AES256-SHA384","ECDHE-ECDSA-DES-CBC3-SHA",
           "ECDH-ECDSA-AES256-GCM-SHA384","ECDH-RSA-AES256-GCM-SHA384",
           "ECDH-ECDSA-AES256-SHA384","ECDH-RSA-AES256-SHA384",
           "DHE-DSS-AES256-GCM-SHA384","DHE-DSS-AES256-SHA256",
           "AES256-GCM-SHA384","AES256-SHA256",
           "ECDHE-ECDSA-AES128-GCM-SHA256",
           "ECDHE-RSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES128-SHA256",
           "ECDHE-RSA-AES128-SHA256","ECDH-ECDSA-AES128-GCM-SHA256",
           "ECDH-RSA-AES128-GCM-SHA256","ECDH-ECDSA-AES128-SHA256",
           "ECDH-RSA-AES128-SHA256","DHE-DSS-AES128-GCM-SHA256",
           "DHE-DSS-AES128-SHA256","AES128-GCM-SHA256","AES128-SHA256",
           "ECDHE-ECDSA-AES256-SHA","ECDHE-RSA-AES256-SHA",
           "DHE-DSS-AES256-SHA","ECDH-ECDSA-AES256-SHA",
           "ECDH-RSA-AES256-SHA","AES256-SHA","ECDHE-ECDSA-AES128-SHA",
           "ECDHE-RSA-AES128-SHA","DHE-DSS-AES128-SHA",
           "ECDH-ECDSA-AES128-SHA","ECDH-RSA-AES128-SHA","AES128-SHA"]},
 {fail_if_no_peer_cert,false},
 {verify,verify_none},
 {verify_fun,{#Fun<vmq_ssl.0.79469420>,no_crl}},
 {depth,1},
 {versions,['tlsv1.2']}]
```

**Comment by larshesel** [comment]
Hmm, then I don't have a good idea what's going on, I'm afraid. It looks like both the client and the server has compatible cipher suites available.

**Comment by codeadict** [comment]
Can you try only `openssl s_client -connect 127.0.0.1:8883` without providing the CAFile?

**Comment by jimfunk** [comment]
Same result:

```
# openssl s_client -connect 127.0.0.1:8883
CONNECTED(00000003)
140053043574592:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1399:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1521233526
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
```

**Comment by dergraf** [comment]
@jimfung can you try with the newest Erlang release 20.3. They fixed several bugs in the SSL application a few days ago.

**Comment by JimFung** [comment]
@dergraf I think you tagged the wrong person 😅 
yo @jimfunk you've got mail bud.

**Comment by ioolkos** [comment]
Oh...ok :)
Actually, the issue now assigned to you, @JimFung. You have to come up with a solution!  :gift: :balloon: :smile:

**Comment by jimfunk** [comment]
Seems the latest my distro has is 20.2.2. I ended up using Mosquitto instead. I may Come back and look again later.

**Comment by larshesel** [comment]
ok, sorry to hear you didn't get it to work - you'll be welcome back any time!
