### ISSUE TITLE
Configuration Recommendation & Usage Pattern Concerns

### ISSUE THREAD

**Issue by tpiecora** [erlio/vernemq#634]
This is primarily an inquiry, not an actual problem.  We are considering using this implementation of MQTT for one of our production systems.  Reading through some of the issues, I have some concerns about disk usage and memory stabilization.  Our use case would involve somewhere in the neighborhood of 50k-100k unique clients a day  (2 million a month and roughly 1000 concurrently).  Almost all of these clients would be only subscribing to a small number of topics.  Most messages would be published by only a handful of clients.  Each subscribing client would only ever receive about 50 or so messages.  Most clients and topics they subscribe to will never be used again.  Also we have a handful of clients that will subscribe to and receive messages from thousands of topics over time.

Running 3-5 nodes in the cluster and allocating a decent amount of resources is not a problem.  
Are there any specific concerns you have with this usage pattern?
Are there any configuration settings you would recommend?

I plan on simulating actual usage patterns for an extended period of time in order to demonstrate the stability of the system before moving it to production, but if there is any helpful input you have, it would be greatly appreciated.

**Comment by ioolkos** [comment]
@tpiecora Hi, thanks for asking.
For the current VerneMQ implementation at least, we consider it a kind of  'antipattern' to never re-use ClientIDs (that is, using one-time, throwaway ClientIDs exclusively). 

If this is an essential feature of your concept/architecture that you can't work around, get in touch with us over e-mail. (You're welcome to do that in any case to discuss more details)

**Comment by tpiecora** [comment]
I submitted the contact form on the website.  Was that what you meant by email?
