### ISSUE TITLE
How can i do all clients of the same user subscribe a topic?

### ISSUE THREAD

**Issue by snowyu** [erlio/vernemq#635]
I want support the multi clients with same account, an account can login on any device(win, linux, mobile...)).

**Comment by ioolkos** [comment]
Hi @snowyu thanks... 
`allow_multiple_sessions = on`, is that what you mean?

**Comment by snowyu** [comment]
Not exactly.  How to transfer file each other if they all are the same client id?

**Comment by larshesel** [comment]
MQTT doesn't support multiple clients with the same client-id (as per the spec) and a new client which connects and is authorized with the same client id will cause the old client to be disconnected. MQTT doesn't support file transfers directly, something like this would have to be modeled by an appropriate topic structure.

I'm closing this as it is a support question and not a feature request or bug report.

Feel free to join our community on slack http://slack-invite.vernemq.com/ or get in touch with us for support: https://vernemq.com/services.html.
