### ISSUE TITLE
Client Keepalive expire

### ISSUE THREAD

**Issue by gmonk63** [erlio/vernemq#639]
I keep getting the following logs for a client

client {[],<<"anon-dGeA+y2x5Z0lgNaqFB0gcqXHssc=">>} with username <<"redacted">> stopped due to keepalive expired

Is this due to configuration on my end or does the client for some reason just lose connection?  How can I see what keeplive values each client is using when they connect

Thanks

**Comment by ioolkos** [comment]
@gmonk63 thanks for asking... is it a client within your realm? that is do you know with what settings it connects? the client obviously doesn't talk within the keepalive period hence the server disconnect.
@larshesel @dergraf is there a way to make connection settings/flags visible server side, given a Client ID?

**Comment by gmonk63** [comment]
Thanks for the quick reply.  No the client is external but according to them the keep alive is at defaults 60  which is why i would like see if i can verify on the broker side. So then it is somthing on there side where they have not sent a keep alive within the time period and the broker kicked the connection.

**Comment by ioolkos** [comment]
Do you happen to know what MQTT library the client is using?

**Comment by gmonk63** [comment]
No i dont sorry I will find out and report back

**Comment by gmonk63** [comment]
Issues was on client side thanks for all your help

**Comment by jurek7** [comment]
Hi @gmonk63,
Could you please provide more details how did you solve issue in client ?

**Comment by gmonk** [comment]
@jurek7  I'm sorry I didn't have control over that client so I'm not sure if they had switched client libraries or it was simply a network related issues.
