### ISSUE TITLE
Hostname-based nodename

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#64]
In other Erlang projects that I make use of, I can usually set something like `-sname vernemq` and have nodes discovering themselves through hostnames and DNS (the full name, in this case, would be `vernemq@my_hostname.my_local_domain`). I see that VerneMQ uses `-name` instead of `-sname`. Would it possible to use the same technique (`-sname`) in VerneMQ?

Also, is it possible to override configuration options with environment variables?

**Comment by ioolkos** [comment]
Heya,
you can override vm args by creating a vm.args file in `_build/default/rel/vernemq/etc`.
So by adding
`-sname test` 
to that file, you'll end up with a broker using shortnames. We were always using `-name` though, so I'm not a 100% sure of any further implications with shortnames.

Can you give an example of which configuration options you'd like to override?
Thanks!

**Comment by testark** [comment]
@dergraf Thank you very much. I would like to override the nodename (dynamically, as described) and also the clustering interface as a means of working around #32 and #34.

**Comment by ioolkos** [comment]
Actually, you can also set the nodename in vernemq.conf (as an sname, so just as a name string).
But, are you actually running into the node rename problems? how so?

**Comment by testark** [comment]
@dergraf I tried setting `nodename = vernemq` (so as an `sname`) and got the following:

```
{error_logger,{{2015,11,3},{16,45,35}},"Can't set long node name!\nPlease check your configuration\n",[]}
```

**Comment by ioolkos** [comment]
Is `hostname` giving you a full resolution on your host? 
The problem may be caused by a local hostname config problem. 
It also could be related to the node rename problem, I'll look into that.

**Comment by testark** [comment]
@ioolkos `hostname` doesn't output a FQDN. It only outputs a single "word". If I change the hostname to the FQDN, it works.

**Comment by dergraf** [comment]
@testark can we close this issue?

**Comment by testark** [comment]
@dergraf I'm now using FQDN as hostnames and it's working great with `nodename = vernemq`. So yes, I'm closing this issue now.
