### ISSUE TITLE
High CPU load on startup lasting longer each time broker is restarted.

### ISSUE THREAD

**Issue by joboscribe** [erlio/vernemq#641]
### Environment

- VerneMQ Version:1.3.0
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source): n/a

### Expected behavior
When the broker starts up for the first time there is very little delay before it's available.

### Actual behaviour
After several starts and stops on the same instance we're noticing increased delay between `vernemq start` and when the broker is actually able to respond to clients. We're using an EC2 m5.large and at this point what we're seeing is almost 20 minutes of CPU at roughly 200%, then the CPU tapers off to well below 100% and we're able to connect. I installed the broker on another (smaller) instance just to do a sanity check and the startup was nearly instantaneous, without any noticeable CPU load.

We're conducting load tests of roughly 100k clients all subscribing to various topics so i thought perhaps it was loading of session data that was slowing down the startup, but our clients are supposedly using clean sessions. 

Is there a way to see what's causing the CPU load on startup and/or make sure clients are in fact asking for clean sessions?

**Comment by ioolkos** [comment]
Hi @joboscribe thanks for asking!
Yes, the broker has to load a lot of state from your previous test runs. So it's building up a hash tree for a lot of useless state here. If you want clean test runs, restart AND delete broker state between test runs.

**Comment by joboscribe** [comment]
Are we talking about the folders in `/var/lib/vernemq/msgstore` or are there more/other things to get rid of? 

Is this going to be a concern on a long-running broker with 100k to 200k clients connected for extended periods of time? Meaning, are we going to periodically clean out certain directories every week or month or so?

**Comment by ioolkos** [comment]
Apologies, I was not being clear & helpful!

Yes, either `/var/lib/vernemq/msgstore` if you have lotsa offline messages. Or `/var/lib/vernemq/meta` if you have lotsa subscriptions and client IDs. Compare what the directory sizes are.
VerneMQ will re-create the directories during a restart, after you have deleted or moved them. Beware all state is then gone, but this is what you want here.

Normally this should not be a concern. The one exception is when you only use one-time, random ClientIDs.

**Comment by joboscribe** [comment]
Just to be sure i got rid of both (though `msgstore` was a lot smaller than `meta`) and startup was indeed much faster.

Thanks for the help!
