### ISSUE TITLE
Cluster high availability issue

### ISSUE THREAD

**Issue by slavomirdittrich** [erlio/vernemq#65]
Dear friends, 

let me describe a recent problem with vernemq running in cluster environment.
I have a cluster consisting of 3 nodes which run vernemq configured against documentation https://verne.mq/docs/clustering.html.
When all nodes are up, it works ("vmq-admin cluster status" says so).

* If I pub, sub to each node, it works.
* Even if I put layer 4 LB before the cluster, it works.

BUT as soon as I stop vernemq service on one (no matter which) node (I can see the running status of that node as false using "vmq-admin cluster status") THEN **I can't pub/sub to any of the remaining nodes**. When I turn the vernemq service back on, the vernemq service is available on every node back again.

Is it a misconfiguration problem or haven't anyone experienced similar behaviour?

**Comment by ioolkos** [comment]
Heya,
thanks so much for checking out VerneMQ :)
Look at the Dealing with Network partitions part in the clustering guide: [clustering guide](https://verne.mq/docs/clustering.html#dealing-with-network-partitions)
in short: it's intended, but look at trade_consistency = on setting.

**Comment by slavomirdittrich** [comment]
Hi, thank you. Maybe I understand better. But still don't understand what's the purpose of such behaviour? If I want a highly available MQTT cluster to ensure that my clients will always connect, even though one of the nodes are down, how to achieve this with VerneMQ then?

**Comment by ioolkos** [comment]
Hi Slavomir,
sorry for my incomplete answer! The context here is the MQTT protocol itself, it's hard to make it distributable.
To achieve what you want, you'd have to set `allow_multiple_sessions = on`, in addition to trade_consistency.

Against the MQTT spec, you could end up having multiple sessions for the same client ID in that case.

tradeoffs, tradeoffs ;)

**Comment by ioolkos** [comment]
I suppose `allow_multiple_sessions=on` is working for you.
Feel free to re-open the issue in case of need.

**Comment by slavomirdittrich** [comment]
Hey, I wanted to thank you for the great answer on my questions.

I was wondering, is it possible to set the vernemq cluster up so that
published messages are not resend between all the nodes? This approach is
because I want to handle each messages on each of the nodes separately with
local subscriber on each node. Do you think its feasible?

Thank you.

**Comment by ioolkos** [comment]
Forgive me if I misunderstand. VerneMQ does not send a published message to all nodes, only to nodes where it finds out a subscriber lives. So you don't seem to want that?!

Can you give me the point I'm missing here? ;)

**Comment by slavomirdittrich** [comment]
My environment looks like this: vernemq cluster on 3 nodes with load
balancer, which load balnaces incoming mqtt connections in round robin
schedule to the nodes. I would like to achieve handling mqtt message on
each of the nodes only once (on one of the nodes), thus I have a python
script handling the messages, subscribed to the particular node's IP. BUT
when I send mqtt message to LB, then it forwards it to one of the node, but
even though every python script is listening on it's own IP address of that
node, every node (and every python script) will receive that message - and
I want to be processed by only one node.
Maybe I am misunderstanding the whole vernemq cluster concept. I also
apologize if the question is out of the box. But thank you for your time!!!
:)

**Comment by slavekdittrich** [comment]
Hey @ioolkos, I am just wondering whether you got my point, or if am I missing something. Thanks!

**Comment by ioolkos** [comment]
@slavekdittrich apologies, Slavek, this slipped my attention! 

I don't really understand the problem description though. Can you possibly re-phrase?
(where are the python scripts running? in what way are you seeing "multiple handling" of messages?)

**Comment by slavekdittrich** [comment]
I have 3 nodes running VerneMQ, IP addresses are 10.1.1.201-203. In front of this cluster I have LB, which LB incoming MQTT connections to one of the nodes. LB from outside has 192.168.1.91 IP address. Thus I can have multiple nodes while preserving availability. On each node there is Python script, subscribed to local VerneMQ instance, i.e. subscribed to 10.1.1.201 on NODE1. So if I send MQTT message to LB, it will move it to one of the nodes, where I want the message to be handled by the subscribed Python agent. BUT somehow, the message is handled by every agent on every node.

NOW I UNDERSTAND. That's because every agent is subscribed to the same topic. Sorry about that. 

Do you think there is a way how to handle the message only on one of the nodes?

**Comment by ioolkos** [comment]
Oh, I see what you want. You basically want subscriber balancing on a single topic, instead of fanout.

You can only do this by having the same clientID configured to use multiple sessions and then set the `queue_delivery_mode` to balance.

To balance *different* subscribers for the same topic, you'd probably have to write a plugin atm.

**Comment by slavekdittrich** [comment]
May I know where can I find the queue_delivery_mode parameter?

**Comment by ioolkos** [comment]
You can add the following lines to vernemq.conf
`allow_multiple_sessions=on`
`queue_deliver_mode=balance`

(@dergraf any comments?)

**Comment by ioolkos** [comment]
Hm, I have to correct myself, currently the balancing of a queue is per node, so this is not automatically a cluster wide topic balancing.
So we might be out of luck here for your current use case.

**Comment by slavekdittrich** [comment]
Alright, thus I will need to find some other solutions. Anyways, thank you
for your time and for your help.

**Comment by ioolkos** [comment]
Let me thank you for your effort. And again, my apologies for the delay in answering.
BTW, I'm not sure any MQTT broker can do what you need out of the box. 

Maybe you'll find away to split your traffic with an appropriate topic tree. Or with 3 single nodes instead of a cluster.
