### ISSUE TITLE
Strange session balancing behavior

### ISSUE THREAD

**Issue by monoton** [erlio/vernemq#650]
### Environment

- VerneMQ Version: 1.3.1
- OS: Official docker image running on Centos 7

Preface:
1. inserted client to mongoDB with some clientID, creds and acl to subscribe pattern `services/+/IN`
2. turned on:
```
 allow_multiple_sessions = on
 queue_deliver_mode = fanout
```
3. Subscribed with same clientID and creds
from subscriber1 to topic `services/test1/IN`
from subscriber2 to topic `services/test2/IN`

4. Published message to topic `services/test1/IN`
### Expected behavior
Only subscriber1 must get the message

### Actual behaviour
All subscribers (subscriber1 & subscriber2) gets the message
If publishing to `services/test2/IN` - behavior is the same

**Comment by dergraf** [comment]
Hi there,
fanout means all attached sessions will receive the message, use 'balance'
instead.

monoton <notifications@github.com> schrieb am Do., 5. Apr. 2018, 17:02:

**Comment by monoton** [comment]
> fanout means all attached sessions will receive the message, use 'balance'
instead.

So how can we configure to mandatory deliver message to multiple subscribers with one clientID on single topic such as `services/test/IN` ?

**Comment by dergraf** [comment]
If you're using `queue_deliver_mode = fanout` both subscribers will receive the messages, it doesn't matter in this case which subscriber is actually subscribing to the topics. 

> I think that its missing condition: clients must subscribed on the same topic to get the message in fanout mode

That's partially correct, both subscribers will automatically use the same subscriptions IF they are connected to the same cluster node. If you're in a clustered setup and using `allow_multiple_sessions = on` and your subscribers are connected to different nodes you must ensure that either those clients are re-subscribing (when using `clean_session = true`) or check the `session_present`-bit in the `CONNACK`. Hope that makes sense.

**Comment by monoton** [comment]
Ok. Understand. Will be use different ClientIDs for our case
This issue can be closed
