### ISSUE TITLE
Vernemq bridge flooding

### ISSUE THREAD

**Issue by rastomatti** [erlio/vernemq#652]
### Environment

- VerneMQ Version: Rpi fork
- OS: Raspbian
- Erlang/OTP version (if building from source):

Hi all,

I've set up two Vernemq brokers, one acting as a bridge and communication with the other.
We are experiencing flooding on both brokers when publishing to the bridge. I want to "re-publish" all messages going both ways, but I belive that the problem is that the bridge also subscribes to itself. Is there any way to fix this, ie subscribing to all topics but discard all messages sent by itself. Any help would be greatly appriciated.

vmq_bridge.tcp.br0.try_private = on
vmq_bridge.tcp.br0.topic.1 = * both 1
vmq_bridge.tcp.br0.cleansession = off

Best regards, Kenneth

**Comment by ioolkos** [comment]
Hi @rastomatti apologies for my delay in answering & thanks for opening the issue.

Currently there is no automatic loop detection in the VerneMQ bridging implementation. I'll have to look into your case to see what to do best here.
