### ISSUE TITLE
Allow "next" to modify a message's payload

### ISSUE THREAD

**Issue by ghost** [erlio/vernemq#66]
It would be great to have VerneMQ allowing for the `auth_on_publish` hook to return something like

```
{next, ModifiedPayload}
```

in addition to the current possible return values. That would allow people to write plugins which modify a message's contents without performing authorization (effectively delegating authorizations on plugins sitting later in the chain).

Currently, the way I read and experience it, if an `auth_on_publish` returns `{ok, ModifiedPayload}`, the `PUBLISH` is automatically authorized and no further plugins are queried.

**Comment by ioolkos** [comment]
Thanks, this sounds very interesting. One thing to think about is the hook, i.e is auth_on_publish really the best hook to go with here.
We'll discuss this.

**Comment by bmcustodio** [comment]
@ioolkos Yes, I agree that it may not be the best hook (the name will sound a bit misleading). Anyway, it would be great to have this feature in an upcoming version.

**Comment by testark** [comment]
@ioolkos I second this request. It would be very useful in our setup too. :-)

**Comment by dergraf** [comment]
Hi there,

thanks for your patience guys.
Chaining plugins exists for one reason, to find the specific plugin that implements the business logic of the plugin. The chaining itself should not be part of the business logic (it's not forbidden, but it isn't a design goal).
If you require a workaround for this please get in touch over email.

Cheers,
Andre
