### ISSUE TITLE
can't connect to web sockets

### ISSUE THREAD

**Issue by khoshbin** [erlio/vernemq#660]
### Environment

- VerneMQ Version:vernemq-1.3.1-1.el7.centos.x86_64.rpm
- OS: centos7
- Erlang/OTP version (if building from source):

### Expected behavior
listener.tcp.default = 0.0.0.0:1883
listener.ws.default = 0.0.0.0:1884

- Please describe the expected behaviour.
I can connect to port 1883 by mqtt.fx but i can not connect to 1884 for websockets connection
### Actual behaviour
Firefox can’t establish a connection to the server at ws://37.153.110.0:1884/mqtt.
- Please include minimal steps to reproduce the issue, if possible.

this is my test html

```
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>

<script type="application/javascript">
    // Create a client instance: Broker, Port, Websocket Path, Client ID
    client = new Paho.MQTT.Client("37.153.110.0", Number(1884), "clientId");

    // set callback handlers
    client.onConnectionLost = onConnectionLost;
    client.onMessageArrived = onMessageArrived;

    // connect the client
    client.connect({onSuccess:onConnect});


    // called when the client connects
    function onConnect() {
        // Once a connection has been made, make a subscription and send a message.
        console.log("onConnect");
        client.subscribe("/iran");
        message = new Paho.MQTT.Message("Hello");
        message.destinationName = "World";
        client.send(message);
    }

    // called when the client loses its connection
    function onConnectionLost(responseObject) {
        if (responseObject.errorCode !== 0) {
            console.log("onConnectionLost:"+responseObject.errorMessage);
        }
    }

    // called when a message arrives
    function onMessageArrived(message) {
        console.log("onMessageArrived:"+message.payloadString);
    }
</script>
</body>
```

**Comment by larshesel** [comment]
What errors do you see in the browser console? Do you see any errors in the vernemq logs? Does tracing using `vmq-admin trace` give you any output when tracing for the clientid you use?

**Comment by khoshbin** [comment]
this is error in firefox:
Firefox can’t establish a connection to the server at ws://
37.153.110.0:1884/mqtt.
mqttws31.js:979:17
Firefox can’t establish a connection to the server at ws://
37.153.110.0:1884/mqtt.

output of vmq-admin trace is :

=INFO REPORT==== 17-Apr-2018::05:25:33 ===
Can't set long node name!
Please check your configuration
escript: exception error: no match of right hand side value
                 {error,
                     {{shutdown,
                          {failed_to_start_child,net_kernel,
                              {'EXIT',nodistribution}}},
                      {child,undefined,net_sup_dynamic,
                          {erl_distribution,start_link,
                              [[mqtt1_maint_17458,longnames],false]},
                          permanent,1000,supervisor,
                          [erl_distribution]}}}




there was no error in log. the following was in console.log

2018-04-16 18:05:55.876 [info] <0.31.0> Application lager started on node '
VerneMQ@127.0.0.1'
2018-04-16 18:05:55.898 [info]
<0.198.0>@plumtree_peer_service_manager:maybe_load_state_from_disk:131 read
state from file
{[{[{actor,<<127,171,243,149,6,33,222,12,124,25,64,52,96,153,253,196,241,92,196,181>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[['
VerneMQ@127.0.0.1
',{[{actor,<<127,171,243,149,6,33,222,12,124,25,64,52,96,153,253,196,241,92,196,181>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}
2018-04-16 18:05:55.902 [info]
<0.198.0>@plumtree_peer_service_manager:write_state_to_disk:100 writing
state
{[{[{actor,<<127,171,243,149,6,33,222,12,124,25,64,52,96,153,253,196,241,92,196,181>>}],1}],{dict,1,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[['
VerneMQ@127.0.0.1',{[{actor,<<127,171,243,149,6,33,222,12,124,25,64,52,96,153,253,196,241,92,196,181>>}],1}]],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},{dict,0,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]}}}}
to disk
<<75,2,131,80,0,0,0,247,120,1,203,96,206,97,96,96,96,204,96,130,82,41,12,172,137,201,37,249,69,185,64,81,145,250,213,159,167,178,41,222,227,169,145,116,48,73,152,249,247,200,199,152,35,91,179,18,25,179,50,56,83,24,88,82,50,147,75,18,25,19,5,128,144,35,49,32,209,32,67,32,11,13,100,48,2,197,192,230,130,8,166,20,6,193,176,212,162,188,84,223,64,7,67,35,115,61,3,32,52,36,205,94,116,243,225,206,96,32,232,12,52,173,0,173,10,78,81>>
2018-04-16 18:05:55.939 [info]
<0.206.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/0 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,33280278}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.947 [info]
<0.208.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/1 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,56343766}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.955 [info]
<0.209.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/2 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,36881427}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.965 [info]
<0.210.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/3 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,46915316}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.971 [info]
<0.211.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/4 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,58534002}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.977 [info]
<0.212.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/5 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,51663641}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.983 [info]
<0.213.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/6 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,54530913}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.990 [info]
<0.214.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/7 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,56482667}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:55.996 [info]
<0.215.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/8 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,57433454}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:56.002 [info]
<0.216.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/9 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,47829613}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:56.008 [info]
<0.217.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/10 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,36936609}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:56.015 [info]
<0.218.0>@plumtree_metadata_leveldb_instance:init_state:322 Datadir
/var/lib/vernemq/meta/meta/11 options for LevelDB:
[{open,[{block_cache_threshold,33554432},{block_restart_interval,16},{block_size_steps,16},{compression,true},{create_if_missing,true},{delete_threshold,1000},{eleveldb_threads,71},{fadvise_willneed,false},{limited_developer_mem,false},{sst_block_size,4096},{tiered_slow_level,0},{total_leveldb_mem_percent,6},{use_bloomfilter,true},{write_buffer_size,56288610}]},{read,[{verify_checksums,true}]},{write,[{sync,false}]},{fold,[{verify_checksums,true},{fill_cache,false}]}]
2018-04-16 18:05:56.111 [info] <0.31.0> Application plumtree started on
node 'VerneMQ@127.0.0.1'
2018-04-16 18:05:56.152 [info] <0.31.0> Application vmq_plugin started on
node 'VerneMQ@127.0.0.1'
2018-04-16 18:05:56.152 [info] <0.31.0> Application ssl_verify_fun started
on node 'VerneMQ@127.0.0.1'
2018-04-16 18:05:56.152 [info] <0.31.0> Application epgsql started on node '
VerneMQ@127.0.0.1'
2018-04-16 18:05:56.207 [info] <0.31.0> Application hackney started on node
'VerneMQ@127.0.0.1'
2018-04-16 18:05:56.853 [info] <0.322.0>@vmq_reg_trie:handle_info:183
loaded 0 subscriptions into vmq_reg_trie
2018-04-16 18:05:56.875 [info] <0.220.0>@vmq_cluster:init:114 plumtree peer
service event handler 'vmq_cluster' registered
2018-04-16 18:05:57.546 [info] <0.31.0> Application vmq_acl started on node
'VerneMQ@127.0.0.1'
2018-04-16 18:05:57.662 [info] <0.31.0> Application vmq_passwd started on
node 'VerneMQ@127.0.0.1'
2018-04-16 18:05:57.829 [info] <0.31.0> Application vmq_server started on
node 'VerneMQ@127.0.0.1'

**Comment by larshesel** [comment]
The first error indicates that either 1) a firewall issue or other network issue 2) there is no listerner running on that port (you can check that with tools like `netstat` or similar or simply telnet to the port (from the outside or inside) to see if something is actually there.

The second part indiciates that your vernemq installation is somehow misconfigured/or something else is going wrong. The error indicates that the system isn't using erlang distribution. Is this per change a single core machine? What does your nodename in the vernemq.conf look like?

**Comment by larshesel** [comment]
I guess we can close this? If not let us know and we'll reopen.
