### ISSUE TITLE
sudo vernemq top

### ISSUE THREAD

**Issue by ioolkos** [erlio/vernemq#661]
I guess we could add etop, so that folks could use the quick `sudo vernemq top` command. Was there any specific reason we left this out?

**Comment by larshesel** [comment]
I know of no reason why we left that out. We could include it in 1.4.0.

**Comment by codeadict** [comment]
I will add this, promise :)

**Comment by codeadict** [comment]
Working on this, I think it will make more sense to go with `vmq-admin top`. What are your thoughts @ioolkos ?

**Comment by ioolkos** [comment]
I'd like to actually support what the `vernemq` script advertises. Which doesn't exclude adding top to `vmq-admin` too, of course.. and possibly extende the filtering or sorting opts there.

```
➜  vernemq git:(master) ✗ vernemq

Usage: vernemq «command»
where «command» is one of the following:
    { help | start | stop | restart | ping | console | attach
      attach-direct | ertspath | chkconfig | escript | version | getpid
      top [-interval N] [-sort { reductions | memory | msg_q }] [-lines N] } |
      config { generate | effective | describe VARIABLE } [-l debug]

Run `vernemq help` for more detailed information.

```

**Comment by codeadict** [comment]
That makes lot of sense

**Comment by larshesel** [comment]
As it's a debug tool I think it's fine to only have it in the `vernemq` command. It's likely not a tool one would use often(hopefully never), but nice to have in a pinch.

**Comment by codeadict** [comment]
Pull requests submitted! 🎉

**Comment by larshesel** [comment]
I think I'd keep it in the erlio/node_package repo for now. Then it's easy to understand where the runner script comes from and if upstream changes at some point we don't have to remember to bring those things over to our copy of the runner script. So I'd say we should keep it in the erlio/node_package repo.
