### ISSUE TITLE
redis auth plugin error

### ISSUE THREAD

**Issue by charliexp** [erlio/vernemq#662]
auth_on_register(reg) function does not trigger, the callback regardless of the new connetion coming in.

**Comment by ioolkos** [comment]
Hi @charliexp thanks for opening the issue!
Is the file based auth still activated? Can your try setting
`plugins.vmq_passwd = off`
`plugins.vmq_acl = off`

**Comment by dergraf** [comment]
and allow_anonymous is disabled?

charliexp <notifications@github.com> schrieb am Do., 19. Apr. 2018, 09:24:

**Comment by charliexp** [comment]
that's what caused it, thank you! @dergraf
