### ISSUE TITLE
MQTTWSS throwing error (mqttws, mqtts, mqtt are fine)

### ISSUE THREAD

**Issue by mikestov** [erlio/vernemq#665]
### Environment

- VerneMQ Version: 1.3.1
- OS: docker (mac os x)
- Erlang/OTP version (if building from source):

### Actual behaviour

I've been testing a MQTTWSS connection and it keeps throwing an error upon connection and terminates it. I've been able to get all other types of connections working. I'm using the test certificates provided in the VerneMQ github to ensure I didn't screw something up with the ones I generated. Here's all the config info which I think is applicable:

These two lines was added to the 1.3.1 VerneMQ docker:
echo "listener.ssl.default = ${IP_ADDRESS}:8883" >> /etc/vernemq/vernemq.conf
echo "listener.wss.default = ${IP_ADDRESS}:8443" >> /etc/vernemq/vernemq.conf

These are in my docker compose file for environment and port mappings:
      - "1883:1883"
      - "8883:8883"
      - "8080:8080"
      - "8443:8443"
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /etc/certs/all-ca.crt
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /etc/certs/server.crt
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /etc/certs/server.key

I tested SSL with OpenSSL as well as a eclipse paho client configured to use SSL and no issues. When I try to connect to wss://localhost:8443 -- This is dumped in the VerneMQ log and paho throws a Caused by: java.io.EOFException: SSL peer shut down incorrectly:

vernemq_1                  | 2018-04-20 19:40:44.072 [error] <0.454.0> CRASH REPORT Process <0.454.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list(undefined) in ssl_config:file_error/2 line 137
vernemq_1                  | 2018-04-20 19:40:44.072 [error] <0.170.0> Supervisor tls_connection_sup had child undefined started with {tls_connection,start_link,undefined} at <0.454.0> exit with reason badarg in context child_terminated
vernemq_1                  | 2018-04-20 19:40:44.073 [error] <0.389.0> Supervisor {<0.389.0>,ranch_acceptors_sup} had child {acceptor,<0.389.0>,1} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8649>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.388.0>) at <0.391.0> exit with reason {badarg,{gen_statem,call,[<0.454.0>,{new_user,<0.388.0>},infinity]}} in context child_terminated
vernemq_1                  | 2018-04-20 19:40:44.079 [error] <0.456.0> CRASH REPORT Process <0.456.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list(undefined) in ssl_config:file_error/2 line 137
vernemq_1                  | 2018-04-20 19:40:44.080 [error] <0.170.0> Supervisor tls_connection_sup had child undefined started with {tls_connection,start_link,undefined} at <0.456.0> exit with reason badarg in context child_terminated
vernemq_1                  | 2018-04-20 19:40:44.080 [error] <0.389.0> Supervisor {<0.389.0>,ranch_acceptors_sup} had child {acceptor,<0.389.0>,2} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8649>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.388.0>) at <0.392.0> exit with reason {badarg,{gen_statem,call,[<0.456.0>,{new_user,<0.388.0>},infinity]}} in context child_terminated
vernemq_1                  | 2018-04-20 19:40:44.080 [error] <0.389.0> Supervisor {<0.389.0>,ranch_acceptors_sup} had child {acceptor,<0.389.0>,2} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8649>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.388.0>) at <0.392.0> exit with reason reached_max_restart_intensity in context shutdown
vernemq_1                  | 2018-04-20 19:40:44.080 [error] <0.387.0> Supervisor {<0.387.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link({{172,18,0,2},8443}, 10, ranch_ssl, [{ip,{172,18,0,2}},{port,8443},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,...},...]) at <0.389.0> exit with reason shutdown in context child_terminated

Let me know if you need more info. Thanks!

**Comment by ioolkos** [comment]
@mikestov thanks for opening the issue!
Can you show your connecting code, if possible? (Are you really connecting over WebSocket?)

**Comment by mikestov** [comment]
I uploaded the code I used for normal websocket:
https://github.com/mikestov/testrepo/blob/master/test/TestMqttWS.java

And then this is the one for SSL websockets:
https://github.com/mikestov/testrepo/blob/master/test/TestMqttWSS.java

The SSL one works if its it's the mqtts connection (just change the string to ssl://localhost/8883), so I know the certs are working properly. Here's also the running listeners in VerneMQ:

➜  ~ docker exec geminilocal_vernemq_1 vmq-admin listener show
+-------+-------+----------+-----+----------+---------+
| type  |status |    ip    |port |mountpoint|max_conns|
+-------+-------+----------+-----+----------+---------+
| http  |running|127.0.0.1 |8888 |          |  10000  |
| http  |running|172.18.0.2|8888 |          |  10000  |
|  vmq  |running|172.18.0.2|44053|          |  10000  |
|mqttwss|running|172.18.0.2|8443 |          |  10000  |
|mqttws |running|172.18.0.2|8080 |          |  10000  |
| mqtts |running|172.18.0.2|8883 |          |  10000  |
| mqtt  |running|172.18.0.2|1883 |          |  10000  |
+-------+-------+----------+-----+----------+---------+

**Comment by mikestov** [comment]
Alright, so I did a bit of an experiment. I downgraded to VerneMQ 1.30 and normal SSL MQTT works, still no luck with websockets SSL. I then downgraded to 1.2.3 and this time both SSL MQTT breaks and websockets SSL does too. My gut feeling is something was fixed with SSL in 1.3.0 that didn't make it over to the websocket code. Here is the error I get when doing a normal SSL MQTT connection under 1.2.3:

vernemq_1                  | 2018-04-20 21:36:47.400 [error] <0.458.0> CRASH REPORT Process <0.458.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list(undefined) in ssl_config:file_error/2 line 137
vernemq_1                  | 2018-04-20 21:36:47.400 [error] <0.170.0> Supervisor tls_connection_sup had child undefined started with {tls_connection,start_link,undefined} at <0.458.0> exit with reason badarg in context child_terminated
vernemq_1                  | 2018-04-20 21:36:47.401 [error] <0.362.0> Supervisor {<0.362.0>,ranch_acceptors_sup} had child {acceptor,<0.362.0>,1} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8604>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.361.0>) at <0.364.0> exit with reason {badarg,{gen_statem,call,[<0.458.0>,{new_user,<0.361.0>},infinity]}} in context child_terminated
vernemq_1                  | 2018-04-20 21:36:47.405 [error] <0.460.0> CRASH REPORT Process <0.460.0> with 0 neighbours crashed with reason: bad argument in call to erlang:binary_to_list(undefined) in ssl_config:file_error/2 line 137
vernemq_1                  | 2018-04-20 21:36:47.405 [error] <0.170.0> Supervisor tls_connection_sup had child undefined started with {tls_connection,start_link,undefined} at <0.460.0> exit with reason badarg in context child_terminated
vernemq_1                  | 2018-04-20 21:36:47.405 [error] <0.362.0> Supervisor {<0.362.0>,ranch_acceptors_sup} had child {acceptor,<0.362.0>,2} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8604>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.361.0>) at <0.365.0> exit with reason {badarg,{gen_statem,call,[<0.460.0>,{new_user,<0.361.0>},infinity]}} in context child_terminated
vernemq_1                  | 2018-04-20 21:36:47.406 [error] <0.362.0> Supervisor {<0.362.0>,ranch_acceptors_sup} had child {acceptor,<0.362.0>,2} started with ranch_acceptor:start_link({sslsocket,nil,{#Port<0.8604>,{config,{ssl_options,tls,[{3,3}],verify_none,{#Fun<vmq_ssl.0.12387311..>,...},...},...}}}, ranch_ssl, <0.361.0>) at <0.365.0> exit with reason reached_max_restart_intensity in context shutdown
vernemq_1                  | 2018-04-20 21:36:47.406 [error] <0.360.0> Supervisor {<0.360.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link({{172,18,0,2},8883}, 10, ranch_ssl, [{ip,{172,18,0,2}},{port,8883},{nodelay,true},{linger,{true,0}},{send_timeout,30000},{send_timeout_close,...},...]) at <0.362.0> exit with reason shutdown in context child_terminated

**Comment by mikestov** [comment]
Alright, I figured it out. I looked up this issue which was fixed in 1.3.0:

https://github.com/erlio/vernemq/issues/583

And then I got the idea -- what if wss needs you to define the exact same info again? Turns out you do. When I updated my compose file to:

      DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT: 172.18.0.2:8443
      DOCKER_VERNEMQ_LISTENER__WSS__CAFILE: /etc/certs/all-ca.crt
      DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE: /etc/certs/server.crt
      DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE: /etc/certs/server.key
      DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: 172.18.0.2:8883
      DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /etc/certs/all-ca.crt
      DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /etc/certs/server.crt
      DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /etc/certs/server.key

It's working fine now.

Glad it's working, but this probably should be added to the documentation on the websockets section for people like me. =)

**Comment by ioolkos** [comment]
@mikestov thank you so much for your time and effort!
I'll add your contribution to the documentation.

**Comment by whizyrel** [comment]
> Alright, I figured it out. I looked up this issue which was fixed in 1.3.0:
> 
> [#583](https://github.com/vernemq/vernemq/issues/583)
> 
> And then I got the idea -- what if wss needs you to define the exact same info again? Turns out you do. When I updated my compose file to:
> 
> ```
>   DOCKER_VERNEMQ_LISTENER__WSS__DEFAULT: 172.18.0.2:8443
>   DOCKER_VERNEMQ_LISTENER__WSS__CAFILE: /etc/certs/all-ca.crt
>   DOCKER_VERNEMQ_LISTENER__WSS__CERTFILE: /etc/certs/server.crt
>   DOCKER_VERNEMQ_LISTENER__WSS__KEYFILE: /etc/certs/server.key
>   DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT: 172.18.0.2:8883
>   DOCKER_VERNEMQ_LISTENER__SSL__CAFILE: /etc/certs/all-ca.crt
>   DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE: /etc/certs/server.crt
>   DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE: /etc/certs/server.key
> ```
> 
> It's working fine now.
> 
> Glad it's working, but this probably should be added to the documentation on the websockets section for people like me. =)

The same applies outside of the docker environment.
