### ISSUE TITLE
Warning when trying to run vernemq

### ISSUE THREAD

**Issue by mohamed-elsabagh** [erlio/vernemq#667]
### Environment

- VerneMQ Version: latest
- OS: Ubuntu
- Erlang/OTP version (if building from source): 20

I am getting this warning when trying to run Vernemq from source 
```
!!!!
!!!! WARNING: ulimit -n is 1024; 65536 is the recommended minimum.
!!!!
```
and  I status of vernemq is failed

**Comment by larshesel** [comment]
Hi, see http://vernemq.com/docs/misc/change-open-file-limits.html
