### ISSUE TITLE
Store All received Messages into file or DB

### ISSUE THREAD

**Issue by YahiaZZ** [erlio/vernemq#668]
### Environment

- VerneMQ Version:1.3.1
- OS:Ubuntu 15.10
- Erlang/OTP version (if building from source):

### Expected behavior

- Store all received messages into a file or MySQL database

### Actual behaviour
- Nothing

Hi, 
Please, is there a way to store all received messages (online/offline) into a file or Mysql Database in VerneMQ?

Thanks

**Comment by larshesel** [comment]
Not directly but it should be fairly easy to create a message archive by building a native plugin a lua plugin or using the webhooks plugin by implementing the relevant hooks (`on_publish` for example). See also our documentation for building plugins here: http://vernemq.com/docs/plugindevelopment/

**Comment by YahiaZZ** [comment]
thank you @larshesel  for your answer,
Is there an example to do this?

**Comment by larshesel** [comment]
You can take a look at the example Erlang plugin: https://github.com/erlio/vernemq_demo_plugin
Or the built-in lua plugins: https://github.com/erlio/vernemq/tree/master/apps/vmq_diversity/priv/auth
Or the docs for vmq_webhooks: https://github.com/erlio/vernemq/tree/master/apps/vmq_diversity/priv/auth

**Comment by YahiaZZ** [comment]
Thank you @larshesel 
I choosed the lua way 
I create the lua script and put it in its specific folder
I have this error
`@vmq_diversity_app:load_script:96 could not load script "/usr/share/vernemq/lua/insert_mysql.lua" due to {{'EXIT',{{badmatch,{error,{normal,{child,undefined,{vmq_diversity_script_state,1}`

**Comment by leopucci** [comment]
@YahiaZZ 
Could you share your lua plugin?

I am trying to receive some data from the client and save important statistcs into mysql using lua

Thanks

**Comment by YahiaZZ** [comment]
Hi @leopucci ;
please find the code below; it depends on your table attributes; it's optimal, but give the result

```
require "auth/auth_commons"
function on_publish(reg)

  results = mysql.execute(pool, 
            [[INSERT INTO vmq_messages
              VALUES (DEFAULT,?,?,?,?,?,?) 
            ]], 
            reg.payload, 
            reg.username,
            reg.topic,
            reg.qos,
			reg.retain,
			reg.subscriber_id)
			
end

pool = "database_name"
config = {
    pool_id = pool
}
mysql.ensure_pool(config)
hooks = {
    on_publish = on_publish,
    
}
```

**Comment by leopucci** [comment]
Thanks @YahiaZZ

**Comment by leopucci** [comment]
@YahiaZZ Have you found a way to publish a message from mysql into a topic?

**Comment by YahiaZZ** [comment]
@leopucci, 
Sorry, unfortunately not

**Comment by leopucci** [comment]
BTW, i have tried using the mysql LAST_INSERT_ID() but it returns 0

**Comment by YahiaZZ** [comment]
Hi @leopucci 
Have you tried to put LAST_INSERT_ID() at the end of the file ?

**Comment by leopucci** [comment]
@YahiaZZ , i have tried the select of  LAST_INSERT_ID but it did not worked

**Comment by leopucci** [comment]
I went sniffing around to understand, the erlang is already returning the id. But it seems that the mysql execute is not proper molded to return it. 
https://github.com/erlio/vernemq/issues/833
