### ISSUE TITLE
How to enable the status page?

### ISSUE THREAD

**Issue by akdj** [erlio/vernemq#669]
Hi

On the git repository main page, it explains that there is a status page for vernemq broker: http://localhost:8888/status

However, I tried to open this page for a running docker vernemq container (erlio/docker-vernemq:1.3.1)
And I get an empty page.   (White pages)

I guess I need to enable this feature, but how to enable it?  By using vmq-admin or editing vernemq.conf ?

**Comment by larshesel** [comment]
You need to run the nightly build as that has not yet been relesed in a tagged version. See https://github.com/erlio/vernemq/blob/master/changelog.md#not-yet-released-vernemq-140

**Comment by akdj** [comment]
Hi @larshesel 
Thank you.

**Comment by akdj** [comment]
@larshesel 
Another question: if this status page will be released, it that means some new metrics about cluster status and the cluster's node status will be available with Prometheus and Grafana too?

**Comment by larshesel** [comment]
The status page will be released. There are no new metrics available though. Are there some in particular you would like?

**Comment by akdj** [comment]
@larshesel  yes, it will be nice to have metrics for knowing how many nodes are in the cluster, these nodes' vernemq version, and a timestamp for when  a node leave and join.  Information like what we get with "vmq-admin cluster show' command.

**Comment by larshesel** [comment]
The timestamp and vernemq version is currently not included in the `vmq-admin cluster show` command but I think it's a nice idea. Those won't fit well into metrics as the metrics are counters/gauges only. The number of nodes in the cluster would however fit as a gauge. /cc @dergraf

**Comment by gitnwana** [comment]
@larshesel I am having the same problem. Not able to connect to the status page of VerneMQ.

**Comment by larshesel** [comment]
@gitnwana please open up a new issue and describe *exactly* what you're doing when this fails to work. Simply writing that something doesn't work doesn't help figuring out what the problem is.
