### ISSUE TITLE
Keepalive issue

### ISSUE THREAD

**Issue by adriangalera** [erlio/vernemq#676]
Hello, I have observed a weird behaviour concerning the keepalive implementation. I am not exactly sure if the issue is related with vernemq.

### Environment

- VerneMQ Version: Last Docker image
- OS: AWS ECS AMI
- Erlang/OTP version (if building from source): ?

### Expected behavior
When the client is not sending any message to the broker, the client must count the last message difference and when this is greater than the keepalive period, it should send a PING request.

### Actual behaviour
We were using a paho mqtt python client and mosquitto broker before migrating to vernemq. The keepalive period worked well (keepalive configure to 60 seconds)
```
Last packet sent 56.2421600819
Last packet sent 57.2435801029
Last packet sent 58.244893074
Last packet sent 59.2452421188
Last packet sent 60.2466518879
Inside keepalive condition
1 0
Request pingsend
DEBUG:__main__:Sending PINGREQ
Last packet sent 0.000925064086914
DEBUG:__main__:Received PINGRESP
Last packet sent 0.0433781147003
Last packet sent 1.04460906982
```
Exactly the same configuration but changing the URL to a vernemq broker, we get:
```
Last packet sent 56.1633839607
Last packet sent 57.1645710468
Last packet sent 58.1658949852
Last packet sent 59.1672990322
Sending disconnect
<paho.mqtt.client.Client object at 0x7fc5cdb830d0>
None
1
DEBUG:__main__:Sending CONNECT (u0, p0, wr0, wq0, wf0, c1, k60) 
```

**Comment by larshesel** [comment]
Hi,

Thanks for the question.

In the second output who is sending the disconnect? Is that the client or the broker? In any case the PINGREQ must be sent from the client, otherwise the broker will disconnect the client after about 1.5*keepalive time.

Maybe you could do a trace on the broker using `vmq-admin trace` to see what's going on there or verify the behaviour with another client like the `mosquitto_sub` or `mosquitto_pub` command line clients using the `-d` flag to get verbose information.

**Comment by adriangalera** [comment]
Looking at the network packets with wireshark, I cannot see any MQTT packet indicating the disconnection. So I guess the issue is in the client.

I can reproduce the same issue with mosquitto_sub:
```
gal@gal-Lenovo-B590 ~/workspace/dpu.mqttcli (master) $ mosquitto_sub -h xxxxx -t /test -d -i "test-ka"
Client test-ka sending CONNECT
Client test-ka received CONNACK
Client test-ka sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 0)
Client test-ka received SUBACK
Subscribed (mid: 1): 0
Client test-ka sending CONNECT
Client test-ka received CONNACK
Client test-ka sending SUBSCRIBE (Mid: 2, Topic: /test, QoS: 0)
Client test-ka received SUBACK
Subscribed (mid: 2): 0

```
Looking at vmq-admin trace:
```
root@ip-10-0-0-158:/# vmq-admin trace client client-id="test-ka"
No sessions found for client "test-ka"
New session with PID <7251.3748.0> found for client "test-ka"
<7251.3748.0> MQTT RECV: CID: "test-ka" CONNECT(c: test-ka, v: 3, u: undefined, p: undefined, cs: 1, ka: 60)
<7251.3748.0> MQTT SEND: CID: "test-ka" CONNACK(sp: 0, rc: 0)
<7251.3748.0> MQTT RECV: CID: "test-ka" SUBSCRIBE(m1) with topics:
    q:0, t: "/test"
<7251.3748.0> Calling auth_on_subscribe(undefined,{[],<<"test-ka">>}) with topics:
    q:0, t: "/test"
<7251.3748.0> Hook returned "ok"
<7251.3748.0> MQTT SEND: CID: "test-ka" SUBACK(m1, qt[0])


<7251.3748.0> Trace session for test-ka stopped
New session with PID <7251.3767.0> found for client "test-ka"
<7251.3767.0> MQTT RECV: CID: "test-ka" CONNECT(c: test-ka, v: 3, u: undefined, p: undefined, cs: 1, ka: 60)
<7251.3767.0> MQTT SEND: CID: "test-ka" CONNACK(sp: 0, rc: 0)
<7251.3767.0> MQTT RECV: CID: "test-ka" SUBSCRIBE(m2) with topics:
    q:0, t: "/test"
<7251.3767.0> Calling auth_on_subscribe(undefined,{[],<<"test-ka">>}) with topics:
    q:0, t: "/test"
<7251.3767.0> Hook returned "ok"
<7251.3767.0> MQTT SEND: CID: "test-ka" SUBACK(m2, qt[0])
```

However, if i set the keepalive to 59 seconds it works as expected:
```
gal@gal-Lenovo-B590 ~/workspace/dpu.mqttcli (master) $ mosquitto_sub -h xxxx -t /test -d -i "test-ka" -k 59
Client test-ka sending CONNECT
Client test-ka received CONNACK
Client test-ka sending SUBSCRIBE (Mid: 1, Topic: /test, QoS: 0)
Client test-ka received SUBACK
Subscribed (mid: 1): 0
Client test-ka sending PINGREQ
Client test-ka received PINGRESP
```
and vmq-admin trace:
```
root@ip-10-0-0-158:/# vmq-admin trace client client-id="test-ka"
No sessions found for client "test-ka"
New session with PID <7251.3804.0> found for client "test-ka"
<7251.3804.0> MQTT RECV: CID: "test-ka" CONNECT(c: test-ka, v: 3, u: undefined, p: undefined, cs: 1, ka: 59)
<7251.3804.0> MQTT SEND: CID: "test-ka" CONNACK(sp: 0, rc: 0)
<7251.3804.0> MQTT RECV: CID: "test-ka" SUBSCRIBE(m1) with topics:
    q:0, t: "/test"
<7251.3804.0> Calling auth_on_subscribe(undefined,{[],<<"test-ka">>}) with topics:
    q:0, t: "/test"
<7251.3804.0> Hook returned "ok"
<7251.3804.0> MQTT SEND: CID: "test-ka" SUBACK(m1, qt[0])
<7251.3804.0> MQTT RECV: CID: "test-ka" PINGREQ()
<7251.3804.0> MQTT SEND: CID: "test-ka" PINGRESP()
```
I searched at the configuration to look at some default value set to 60 and I could only saw something related with bridge (which is currently disabled)

**Comment by larshesel** [comment]
Interesting. Do you perhaps have some kind of proxy or firewall between the client and VerneMQ which disconnects idle connects after 60 seconds?

**Comment by adriangalera** [comment]
Bingo! The brokers were behind a load balancer in EC2 configure with an idle timeout of 60 seconds.
I've configured to 120 seconds and now I could see the PING being sent and everything works as expected.
Thank you so much!

**Comment by larshesel** [comment]
Awesome! Happy to help!
