### ISSUE TITLE
SSL/TLS (X.509 Certificate) not working

### ISSUE THREAD

**Issue by tradduong** [erlio/vernemq#680]
### Environment

- VerneMQ Version:
- OS: Ubuntu 16.04
- Erlang/OTP version (if building from source):

### Expected behavior
I am expecting a connection via TLS would be working after following this doc for SSL.
https://vernemq.com/docs/configuration/listeners.html
listener.ssl.cafile = /etc/ssl/cacerts.pem
listener.ssl.certfile = /etc/ssl/cert.pem
listener.ssl.keyfile = /etc/ssl/key.pem
listener.ssl.default = vernemq_host:8883

### Actual behaviour
- Failed connect to vernemq_host at port 8883 with SSL/TLS option using mqttfx
- Trying to connect using mosquitto client, it gets into halting state
mosquitto_pub -h vernemq_host -p 8883 --capath certs_directory -t testing/tra -m foo

##### Generate the root 
openssl genrsa  -out ca.key 2048
openssl req -new -x509 -days 7300 -key ca.key -sha256 -extensions v3_ca -out ca.crt

##### Generate the domain key:
openssl genrsa -out domain.key 2048

##### Generate the certificate signing request
openssl req -sha256 -new -key domain.key -out domain.csr

##### Sign the request with root key
openssl x509 -sha256 -req -in domain.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out domain.crt -days 7300

##### Verify signed cert valid:
openssl verify -CAfile ca.crt domain.crt
Notes domain here is mqtt host.

#### Config VerneMQ with the certs
- Drop ca.key in /etc/ssl in as /etc/ssl/cacerts.pem
- Drop domain.com.crt  in /etc/ssl as /etc/ssl/cert.pem
- Drop domain.key in /etc/ssl/ as  /etc/ssl/key.pem

**Comment by ioolkos** [comment]
@tradduong thanks for the report! 
file permissions?
and what does something like `openssl s_client -connect your_vernemq_host:8883` indicate?

**Comment by tradduong** [comment]
we don't want to do client certificate authentication, you just want to verify the server cert.
To do this with mosquitto_pub or mosquitto_sub I just have to specify a CA cert or a path to a directory of multiple certificates in order to enable ssl/tls for the connection. For ex
mosquitto_sub --cafile cacerts.pem -t "test" -h vernemq_host -p 8883

**Comment by ioolkos** [comment]
Apologies for being unclear. My point was that a command like `openssl s_client -connect 127.0.0.1:8883 -CApath "/etc/vernemq/ssl"` gives a better trail of what's happening and better error messages.

Does your mosquitto_pub command work with the --insecure option btw?

**Comment by tradduong** [comment]
The response I got from openssl s_client -connect <mqtt_host>:8883 -CApath <certs_directory> :
CONNECTED(00000003)

**Comment by tradduong** [comment]
Another thought...if you happen to have any unexpired CAs for testing purpose or set of instructions to create the CAs for testing we can give it a try to narrow down the causes. Thanks again.

**Comment by larshesel** [comment]
We have some test ssl certificates stored in: https://github.com/erlio/vernemq/tree/master/apps/vmq_server/test/ssl

Here's an example for the http listener:
https://github.com/erlio/vernemq/issues/540#issuecomment-349316122

**Comment by tradduong** [comment]
thanks @larshesel . You have many ssl certs in there. And that is for https 
Kindly let me know if we should use [test-root-ca.crt, test-signing-ca.crt,test-signing-ca.key] OR [all-ca.crt,server.crt,server.key]
for  **listener.ssl** configuration i.e [cafile,certfile,keyfile]?

**Comment by tradduong** [comment]
Hi @ioolkos . I am able to connect via TLS using the --cafile option and --insecure flag as below
$ mosquitto_pub -d --cafile cacerts.pem -t "test" -m "hello" -h <mqtt_host> -p 8883 --insecure.
My question is if I have many devices that need to be authenticated into VerneMQ, we have only 1 CA file configuration  (listener.ssl.cafile=cacerts.pem). Does it mean we need to add all CA certs that will be used in clients to connect to in this cacerts.pem file? Correct? If not, please give us what is the approach we should take.

**Comment by ioolkos** [comment]
I'm no TLS expert, but I think the clients have to be able to validate the server cert, that's all. That is, they check it's signed by a trusted CA and that it's not expired. 
The problems here seem to come mostly from the self-signed certs.

**Comment by uiue** [comment]
This url maybe help you.
https://www.cnblogs.com/Anker/p/6018032.html
