### ISSUE TITLE
Running VerneMQ as a systemd service

### ISSUE THREAD

**Issue by AnHellTe** [erlio/vernemq#685]
Hello,

How running VerneMQ as a systemd service in centOS 7 ?

Thanks

**Comment by ioolkos** [comment]
@AnHellTe  thanks, does this help? https://github.com/erlio/vernemq/wiki/Running-VerneMQ-as-a-systemd-service
or is your point that this is docs for Ubuntu?

**Comment by ioolkos** [comment]
I guess it would be similar on CentOS. You'll have to figure it out. But if there is a difference, it would be great to document it on the Wiki too.

**Comment by ioolkos** [comment]
@AnHellTe did you manage to get it to work? if not, what step exactly seems to cause problems?

**Comment by ioolkos** [comment]
glad to hear ;)
