### ISSUE TITLE
Vernemq crashes out more or less  on every 7 days 

### ISSUE THREAD

**Issue by tamilhce** [erlio/vernemq#687]
Environment
- VerneMQ Version: 1.3.0
- OS: ubuntu 16.04
- Erlang/OTP version (if building from source): Using  binary to install 
Issue : 
Vernemq crashes after a running for a week time.I'm constituently  facing this issue.
I have 20 active connections( shared subscription with Qos1), with web-hook authentication. I have attached the error logs and my configuration for your reference.

[###]
[vernemq issue log](https://github.com/erlio/vernemq/files/1982509/vernemq.issue.log)
[vernemq_conf.txt](https://github.com/erlio/vernemq/files/1982513/vernemq_conf.txt)

**Comment by larshesel** [comment]
Hi, 

Could you share the `erl_crash.dump` file. Also, what's the memory load on the server when this happens?

**Comment by ioolkos** [comment]
@tamilhce I suspect the `leveldb.maximum_memory.percent = 70` default setting could be the problem here, especially if it's a smaller server. I'd set this to something much lower and observe what happens (to 15 or 20%).
Also, look at the findings here for more insights into stabilizing LevelDB memory usage:
https://github.com/erlio/vernemq/issues/591

**Comment by tamilhce** [comment]
@ioolkos sure, I am using aws t2.mirco(1 GB RAM, 1 VCPU), seems like  a memory issue.
is there any way i can check the LevelDB  usage percentage at real-time.
@larshesel  erl_crash.dump  has 656 MB  of data.

**Comment by larshesel** [comment]
@tamilhce can you post the first 100 lines of the crash dump - it usually is enough to tell if it the VM terminated due to an OOM issue.

**Comment by tamilhce** [comment]
Hi @larshesel  attached t last 200 lines of the crash dump
[vernemq_erl_crash.log](https://github.com/erlio/vernemq/files/1983364/vernemq_erl_crash.log)

**Comment by larshesel** [comment]
Hi,

I meant the *first* 100 lines :)

**Comment by tamilhce** [comment]
I have attached first 100 lines :)
[vernemq_erl_crash.log](https://github.com/erlio/vernemq/files/1983665/vernemq_erl_crash.log)

**Comment by larshesel** [comment]
Hi,

Based on the high memory usage and this reply on the Erlang mailing list: http://erlang.org/pipermail/erlang-questions/2017-February/091721.html I'd guess it's the Linux OOM killer which terminates VerneMQ.

I'd try to set the setting described in the thread @ioolkos linked earlier to limit the resources leveldb can use and see if that helps.

**Comment by tamilhce** [comment]
thanks for quick reply
