### ISSUE TITLE
Improvement: Include other libraries from the Erlang standard library in the releases

### ISSUE THREAD

**Issue by codeadict** [erlio/vernemq#696]
### Environment

- VerneMQ Version: Any released version.
- OS: Any
- Erlang/OTP version (if building from source): -

### Expected behavior

This is really an improvement for plugin development. While developing some plugins I had to use a library that manipulates XML and that requires `xmerl` from the standard library and that is not shipped when VerneMQ is released and there is no way to get it into the plugin because is not a third party dependency that can be installed by rebar3. Will be great to have a chat about what libraries, more specifically for file manipulation can be added to the releases in order to make plugin development easier.

### Actual behaviour

- There are some crucial packages from the standard library that can be needed for plugin development and they are not shipped with the release, making some useful plugins not possible to develop(In my case i'm adding an AWS cloudwatch plugin to report VerneMQ metrics that will be opensource to help the community here).

**Comment by ioolkos** [comment]
Good point. I see 2 possibilities:
- Go full monty (what would that mean?)
- Choose a reasonable set of useful libraries to include (and what would that mean?)

How important is a minimal footprint? What libs should we exclude deliberately? (for security or whatever reasons)

**Comment by codeadict** [comment]
Yeah that analysis sounds reasonable @ioolkos, what I can think about from looking at other Erlang-based projects like RabbitMQ, eJabberd, and MongoseIM, this is pretty much what folks include:

- sasl
- crypto
- public_key
- ssl
- mnesia
- inets
- compiler
- syntax_tools
- os_mon
- xmerl

I'm don't personally think mnesia is needed in the context of VerneMQ.

**Comment by larshesel** [comment]
I also don't think we should add `mnesia` which leaves `xmerl` and `inets` which we don't already include with VerneMQ I'm ok for adding those. As mentioned in another issue we could also include `etop` if people think that's a handy tool.

**Comment by codeadict** [comment]
cool @larshesel I will add `inets` to my PR, it can also be useful. I have another branch for etop, will PR after GDPR madness.

**Comment by codeadict** [comment]
Think we can close this now that is merged on https://github.com/erlio/vernemq/pull/697
