### ISSUE TITLE
Can't download packages from bintray due to Forbidden error

### ISSUE THREAD

**Issue by codeadict** [erlio/vernemq#698]
### Environment

- VerneMQ Version: Any
- OS: Any

### Expected behaviour

- The links on https://vernemq.com/downloads/index.html should be able to download OS packages.

### Actual behaviour

- The bintray site responds with a Forbidden! error. Can be checked at https://dl.bintray.com/erlio/vernemq/deb/jessie/vernemq_1.3.2-1_amd64.deb

**Comment by larshesel** [comment]
Thanks for reporting, we're working on getting it resolved!

**Comment by ioolkos** [comment]
Resolved. Apologies & thank you for your patience!

**Comment by codeadict** [comment]
no problem, thanks for being so fast
