### ISSUE TITLE
"On behalf" subscriptions

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#70]
We have a scenario where we would greatly benefit from being able to subscribe a topic "on behalf" of a given client, so that offline messages would be stored and later delivered to that same client.

The scenario involves the need to receive offline messages from a "dynamically generated" topic, of which clients have no previous knowledge.

Is there anything that can be done in VerneMQ (maybe via a custom plugin) that could be used to implement this?

**Comment by testark** [comment]
@dergraf @ioolkos Could `vmq_reg:subscribe` and `vmq_reg:unsubscribe` be used directly from within a plugin to achieve this? Or maybe a slightly tweaked version of `vmq_reg:direct_plugin_exports`?

**Comment by ioolkos** [comment]
Let me try to describe this in the most general way, so that I can make sure I understand.

You need to "force" clients (= clients that exist in the broker, no matter if online or offline) to subscribe to a given topic. Correct?
is the context discovery? is the context a request/reply mechanism? or device management?

**Comment by testark** [comment]
@ioolkos

> You need to "force" clients (= clients that exist in the broker, no matter if online or offline) to subscribe to a given topic. Correct?

Correct.

> is the context discovery? is the context a request/reply mechanism? or device management?

Sorry, but I am not entirely sure of what you mean by "context".

**Comment by ioolkos** [comment]
Technically, it's of course possible to call `vmq_reg:subscribe` as its a function exported from its module.
It's internal functionality subject to change though. Also, note that `vmq_reg:subscribe` does cluster consistency checks.

we might think about some `internal_subscribe` at some point in the future.

**Comment by testark** [comment]
@ioolkos I see. Can you just confirm that calling `vmq_reg:subscribe` is functionally equivalent to a client sending a `SUBSCRIBE` packet?

**Comment by ioolkos** [comment]
Have a look at https://github.com/erlio/vmq_server/blob/master/src/vmq_mqtt_fsm.erl#L343
The state machine calls `vmq_reg:subscribe` too.

**Comment by testark** [comment]
@ioolkos Many thanks! :-)

**Comment by larshesel** [comment]
Closing this as it looks like it was resolved. Feel free to reopen if that is not the case.
