### ISSUE TITLE
Consider integration with Kafka/Google Cloud PubSub

### ISSUE THREAD

**Issue by hanmd82** [erlio/vernemq#705]
Hi erlio team, thanks for the great work with VerneMQ! So far, we have tried many of the key features of VerneMQ and found that it fits our MQTT messaging use case quite well.

We are building an enterprise product for data ingestion of network telemetry data (which can have very large spikes during the day), so we think that a message queue would be a suitable layer between the MQTT firehose and our worker processes, which can catch up on processing at a later time.

However, we were unable to find any information on whether VerneMQ supports integration with a message queue, e.g. Kafka. Is it on VerneMQ's roadmap to consider plugin support for Kafka? This was briefly mentioned in an earlier issue https://github.com/erlio/vernemq/issues/197.

We are also considering bridging/backing up messages to Google Cloud PubSub, as an alternative to Kafka, so I was wondering if you have any plans to support a cloud-based message queue.

Would appreciate any feedback on whether there is another approach we can be considering. Thanks!

**Comment by codeadict** [comment]
I actually have one implementation for AWS Kinesis, I guess adding a plugin for Kafka will not be that bad.

**Comment by hanmd82** [comment]
thanks @codeadict ... took a look at your plugin for reference 👍

**Comment by crisrise** [comment]
Hi @codeadict , @hanmd82 I have started a plugin implementation to stream all mqtt messages to kafka, still in early stage but fully testable. You can check it here https://github.com/crisrise/vmq_kafka
