### ISSUE TITLE
Replication of subscriptions

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#71]
(This is somehow related to #70, so I've reopened it.)

I have a cluster with two nodes, and I'm trying to "manually" subscribe clients to topics using `vmq_reg:subscribe` as described in #70.

However, I am noticing that if I issue the `vmq_reg:subscribe/4` command (either from the console or a plugin) in a node different from the node the client has last been connected to, the subscription won't take effect and no offline messages will be stored. Here's a picture for a better understanding:

![vernemq-71-1](https://cloud.githubusercontent.com/assets/15380492/11129467/59f55bae-8977-11e5-9010-65dbcc5a1064.png)

If, however, the subscription is directed to the last node the client was connected to, everything goes smoothly:

![vernemq-71-2](https://cloud.githubusercontent.com/assets/15380492/11144854/cd43b68e-89f7-11e5-93cc-c8cb9e54c006.png)

**Comment by testark** [comment]
@ioolkos Is there anything that can be done to mitigate this?

**Comment by ioolkos** [comment]
Thank you for this great issue report!

Just realized this might actually be related to queues. you try a subscription, but there is no queue there. if you do the same process, but from a regular mqtt client, does it work like expected? 
You might use the gen_mqtt from the vmq_commons package programmatically.

This would make `vmq_reg:subscribe` only "functionally" similar on the same node unfortunately.
I'll have to look deeper into this.

**Comment by testark** [comment]
@ioolkos You're most welcome :-) I'll have a try at that and report back. In the meantime, would it "hurt" if I somehow broadcasted the `vmq_reg:subscribe` request to all the nodes? Could there be any problem with that later (during session migration, for example)?

**Comment by testark** [comment]
@ioolkos I tried running

```
gen_emqtt:subscribe(Pid, [<<"a">>, <<"b">>], 1).
```

But I am not entirely sure if I got it correctly since I got some errors. Should `Pid` be the queue PID? I got this:

```
11:09:05.830 [error] got unknown event in online state {subscribe,[{[<<"c">>,<<"351914403106">>,<<"1">>],1}]}
```

**Comment by testark** [comment]
@ioolkos I've got new input which may be useful. If I broadcast the subscription to every node and call `vmq_reg:subscribe` without checking if there is a local queue for that particular client ID, no more messages will be received (even if one of those `subscribe`s was issued to the correct node).

**Comment by ioolkos** [comment]
does any log show that the queue crashes if you do the broadcast?
if you want to trace this a little, erlyberly is very easy to use

the pid from gen_emqtt is the pid of the client state machine itself (you have to start the client with one of the start functions in gen_emqtt).
But you figured probably more out than I have by now

**Comment by ioolkos** [comment]
You definitely need a queue. So the broadcast won't work.
Can you post how you actually start the client? We need to do a connection there (to a certain host), otherwise no queue is created.

**Comment by testark** [comment]
@ioolkos I'm starting a bunch of clients from a Java app (using Paho). Then I disconnect one of them, force a subscription and later reconnect it and check whether offline messages are being delivered.

**Comment by testark** [comment]
@ioolkos My current workaround is to use a `gen_server` in the plugin and use `gen_server:multicall/3` to the result of `vmq_cluster:nodes()`. Then, in the `handle_call` callback I use `vmq_reg:status` to check if the client has a queue in the current node and, in case it does, do the subscription (ignoring the request otherwise). Do you think this is a good idea?

**Comment by ioolkos** [comment]
No too fond of doing it this way, but I can't offer better right now :)

**Comment by testark** [comment]
@ioolkos Yes, I'm too not too fond of this. But do you see any possible issues with this?

**Comment by dergraf** [comment]
@testark you shouldn't use vmq_reg:subscribe directly as multiple edge-cases aren't considered.
As you know we currently don't expose a 'real' internal interface for doing such things so I would stick to using the 'external' interface, MQTT. Our bundled simple MQTT client gen_emqtt should be enough for that, we currently use it in the erlio/vmq_bridge.

**Comment by testark** [comment]
@dergraf for a couple of reasons I cannot resort to MQTT for doing these subscriptions (as I would have to connect with the target client's ID and would start receiving offline messages right away, which is not acceptable in our use case). It would be great if in the future you could provide an API for this, but until then I must really resort to calling `vmq_reg:subscribe` directly.

**Comment by dergraf** [comment]
ok. Probably you've already dig into the vmq_reg details but this is something you must be aware of when using it. Currently subscriptions are replicated in our internal distributed subscriber store (using plumtree). The subscriber store is essentially a key value store storing entries in the following format

    Key:                    Value:
    SubscriberId1     [{Topic1, QoS, NodeA}, {Topic2, QoS, NodeA}]
    SubscriberId2     [{Topic1, QoS, NodeB}, {Topic2, QoS, NodeB}]

Calling ``vmq_reg:subscribe(false, User, SubscriberId1, [{Topic3, QoS}])``  on  NodeB will transform the Subscriber entries to:

    Key:                    Value:
    SubscriberId1     [{Topic1, QoS, NodeB}, {Topic2, QoS, NodeB}, {Topic3, QoS, NodeB}]
    SubscriberId2     [{Topic1, QoS, NodeB}, {Topic2, QoS, NodeB}]

At this moment the routing process will relay messages for SubscriberId1 to NodeB, but won't find a matching queue process. I think one can conclude that prior to manually calling ``vmq_reg:subscribe`` for the first time a ``vmq_reg:register_subscriber(SubscriberId, QueueOpts)``  should be issued on the same node. ``vmq_reg:register_subscriber`` will then check the other nodes for already existing queues and migrate them (and its messages) to the new node. 

Hope this makes sense.

**Comment by testark** [comment]
@dergraf I deeply appreciate and thank you for your explanation. Yes, that's more or less what I ended up doing—I implemented a `gen_server` behaviour and broadcast to all nodes the request for subscription. Then I have each node checking if there is a local queue for that client and only issue the `vmq_reg:subscribe` call in case there is one. Is this acceptable?

**Comment by dergraf** [comment]
Probably. However, keep in mind that in case of a consistent cluster (no network partition) as well as ```allow_multiple_sessions=false (default)``` is used only one queue per clientid can exist at anytime in the cluster. In short, ensure that you are very sure that ```vmq_reg:subscribe``` is issued on the proper node, otherwise you're going to loose messages without knowing it.

**Comment by testark** [comment]
@dergraf I understand. Thank you very much for your thorough explanation!

**Comment by larshesel** [comment]
Closing this for now, feel free to reopen if you have further questions.
