### ISSUE TITLE
Not possible to add listener with ipv6 address

### ISSUE THREAD

**Issue by suiluj** [erlio/vernemq#711]
### Environment

- VerneMQ Version: rpi32-fix branch
- OS: raspberry pi Raspbian Stretch 2018-04-18
- Erlang/OTP version (if building from source): otp 20.2

My interface ifconfig:

```
pi@3pi1:~/mqtt_scripts $ ifconfig
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 1.0.0.1  netmask 255.255.255.0  broadcast 1.0.0.255
        inet6 fe80::ba27:ebff:fe77:3d38  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::4c65:34ff:fe31:dfc7  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:77:3d:38  txqueuelen 1000  (Ethernet)
        RX packets 480  bytes 26833 (26.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 92  bytes 10362 (10.1 KiB)
        TX errors 0  dropped 119 overruns 0  carrier 0  collisions 0
```
### Expected behavior

I want to add a ipv6 listener because in my setup the ipv4 addresses can change all the time.

I was successful in adding a listener for the ipv4 address:
```
vmq-admin listener start address=1.0.0.1 port=1883 --mountpoint /test --nr_of_acceptors=10 --max_connections=1000
```
(Output `Done`)

I was not successful in adding the ipv6 address:
```
vmq-admin listener start address=fe80::ba27:ebff:fe77:3d38 port=1883 --mountpoint /test2 --nr_of_acceptors=10 --max_connections=1000
```
### Actual behaviour

The command outputs an error:
```
can't start listener due to '{{shutdown,
                               {failed_to_start_child,ranch_acceptors_sup,
                                {listen_error,
                                 {{65152,0,0,0,47655,60415,65143,15672},1883},
                                 einval}}},
                              {child,undefined,
                               {ranch_listener_sup,
                                {{65152,0,0,0,47655,60415,65143,15672},1883}},
                               {ranch_listener_sup,start_link,
                                [{{65152,0,0,0,47655,60415,65143,15672},1883},
                                 10,ranch_tcp,
                                 [{ip,{65152,0,0,0,47655,60415,65143,15672}},
                                  {port,1883},
                                  {nodelay,true},
                                  {linger,{true,0}},
                                  {send_timeout,30000},
                                  {send_timeout_close,true}],
                                 vmq_ranch,
                                 [{mountpoint,"/test2"}]]},
                               permanent,infinity,supervisor,
                               [ranch_listener_sup]}}'
```

Is it even possible to add a ipv6 listener?

**Comment by ioolkos** [comment]
@suiluj thanks for reporting... this should work with normal IPv6 addresses.
"fe80::" are link_local addresses that probably always need a scope ID, which obviously does not work here.
I'm not even sure how Erlang handles those addresses, but I'll try to find out.

**Comment by suiluj** [comment]
@ioolkos ah okay thanks for your fast answer.
Yes at the moment i added ipv6.local addresses because it was easier to get connected to my devices in my local batman ad hoc mesh network.
I am not an expert with ipv6 yet. So i will just try a "unique local unicast" address with the range `"fc00::/7 -- fc00:: - fdff::"` and should be able to use the command above without any special brackets?
Do i have to add the ipv6 address to the nodename in the `vernemq.conf` then too?

**Comment by larshesel** [comment]
Hi, did you find a solution to your question?

**Comment by suiluj** [comment]
@larshesel sorry not yet. (i worked on something else. )
i will try in a few days and report back.

**Comment by larshesel** [comment]
I just looked into this bit further and I was able to add a listener with a global ipv6 address (2a02:.....) without any issues. The issue with link-local ipv6 addresses seems to be that the scope-ids are not supported in Erlang, at least as far as I can tell.

I'll close this for now.

**Comment by suiluj** [comment]
Ah thanks for your research. still had do work on different parts of my network but will try the global ipv6 address in the future.

**Comment by larshesel** [comment]
I couldn't help look a bit further into this as ipv6 is one if the things I still need to learn a lot about, especially in Erlang. So as mentioned Erlang doesn't seem to support specifying a link-local address as it doesn't have support for scope-ids/zones, but it does support using `::/0` (similar to ipv4's `0.0.0.0`). So if I add a listener like this:

```
vmq-admin listener start address=:: port=8007
```

Then the listener also is available on the link-local address. Of course the caveat here is that that listener is available on *all* ipv6 address, which could be a security problem. But for testing I think it'll do nicely.
