### ISSUE TITLE
Stop does not kill all processes

### ISSUE THREAD

**Issue by drasko** [erlio/vernemq#712]
### Environment

- VerneMQ Version: master
- OS: Debian Buster
- Erlang/OTP version (if building from source): 20

### Expected behavior
`vernemq stop` stops all VerneMQ processes

### Actual behaviour
```
drasko@Marx:~/vernemq/vernemq-broker/_build/default/rel/vernemq/bin$ ./vernemq stop
ok
drasko@Marx:~/vernemq/vernemq-broker/_build/default/rel/vernemq/bin$ ps aux | grep verne
drasko   22372  0.0  0.0  28676   212 ?        S    02:38   0:00 /home/drasko/vernemq/vernemq-broker/_build/default/rel/vernemq/bin/../erts-9.3/bin/epmd -daemon
drasko   23983  0.0  0.0  12904  1016 pts/4    S+   02:46   0:00 grep verne
```

**Comment by ioolkos** [comment]
Hi @drasko thanks for asking!
What you're seeing is the Erlang port mapper daemon. This is an addressing service used by all Erlang apps, so stopping VerneMQ will not kill the EPMD (as VerneMQ does not know whether other Erlang systems are running on your machine). This is standard behaviour.

To kill EPMD, you can safely use the `epmd` script, and run `epmd -kill`after you have stopped VerneMQ.
