### ISSUE TITLE
Not able to delete client with particular client-id and mountpoint using( vmq-admin session disconnect, or equivalent http api)

### ISSUE THREAD

**Issue by TestFirebaseLogin** [erlio/vernemq#714]
### Environment

- VerneMQ Version:
- OS: OS X EI Captain,10.11.4
- Erlang/OTP version (if building from source): Erlang/OTP 20

### Actual behavior

- Please describe the actual behaviour.
When i try to disconnect a client with given client id and having a particular mount point,it returns true as output of command but that client is not disconnected.But if i dont pass --mountpoint or pass --mountpoint=  (empty),then it disconnects that client.
Also if i have 2 clients with similar clientids but different mount points and if i try to disconnect them using mountpoints it doesn't disconnect them,but if i don't specify mountpoint or specify it as empty,then it disconnect one of the 2 clients with that client id(the one which was connected last).

### Expected behaviour
When i pass --mountpoint,then i should be able to disconnect the client with the matching clientid and mountpoint

- Please include minimal steps to reproduce the issue, if possible.
Connect a client by overriding mountpoint in on_register_auth plugin,then try to disconnect it using the api or vmq-admin session disconnect command.

**Comment by ioolkos** [comment]
@TestFirebaseLogin Thanks, I confirmed it's a bug.
'Mountpoint' is interpreted as a binary, instead of a string, drilling down from the calls in the vmq-admin commands.
We'll fix this.

**Comment by TestFirebaseLogin** [comment]
Thanks sir for you reply,do you have a workaround so that we can proceed until you release the updated code with issue resolved?

**Comment by larshesel** [comment]
Hi, we just merged a fix for this (see #716) into the master branch. It'll be available in the nightly build shortly.

**Comment by TestFirebaseLogin** [comment]
Thanks a lot sir.
