### ISSUE TITLE
doing self-referential cluster leave doesn't correctly propagate to other cluster nodes

### ISSUE THREAD

**Issue by larshesel** [erlio/vernemq#717]
### Environment

- VerneMQ Version: master
- OS: linux
- Erlang/OTP version (if building from source):

### Expected behavior

In a cluster doing cluster leave `vmq-admin cluster leave node=nodename` on node `nodename` should remove node `nodename` from the cluster.

### Actual behaviour

The node `nodename` becomes a stand-alone node, but the rest of the nodes in the cluster still thinks `nodename` is part of the cluster.

**Comment by codeadict** [comment]
I'm actually experiencing this issue, I may contribute some time to it.

**Comment by larshesel** [comment]
I've been wondering about how to fix this. What happens is I think the node shuts down 'too fast' - i.e. before the cluster change was propagated to other nodes in the network via plumtree. If that's correct then I guess there are two ways out: somehow ensure that at least one other node has seen the change or ensure that it's not possible for a node to remove itself from the cluster (though that would be kind of annoying).

**Comment by larshesel** [comment]
Fixed by #731
