### ISSUE TITLE
SUBACK not returned when subscriptions are denied.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#72]
I came accross this while developing a custom ACL plugin based on `vmq_pgauth_demo`, but this behaviour happens on a vanilla VerneMQ deployment as well (as of `0.12.2`) with `vmq_acl`.

If a client issues a `SUBSCRIBE` and it is denied by some `auth_on_subscribe` plugin, no `SUBACK` packet is returned to the client (leaving the client without any feedback and blocking synchronous clients).

@ioolkos @dergraf could you reproduce this behaviour? Is there any workaround?

**Comment by ioolkos** [comment]
Hm, yes, you could be correct in that the `SUBACK` should always return the failure code here.

@ckrey could you kindly confirm this from a client or protocol spec perspective?

**Comment by testark** [comment]
@ioolkos I ran some ErlyBerly on this, and thought this may be helpful. My `vmq.acl`:

```
user testark
topic read a/b
```

Now, `SUBSCRIBE`ing to `a/b` yields

```
<0.11266.0> +1098us vmq_reg:subscribe(false, <<"testark">>, {[], <<"mqtt-client-1">>}, [{[<<"a">>, <<"b">>], 1}]) => ok
<0.11266.0>   +24us vmq_acl:auth_on_subscribe(<<"testark">>, {[], <<"mqtt-client-1">>}, [{[<<"a">>, <<"b">>], 1}]) => ok
```

while `SUBSCRIBE`ing to `a/c` yields

```
<0.11266.0>   +46us vmq_reg:subscribe(false, <<"testark">>, {[], <<"mqtt-client-1">>}, [{[<<"a">>, <<"c">>], 1}]) => {error, not_allowed}
<0.11266.0>   +27us vmq_acl:auth_on_subscribe(<<"testark">>, {[], <<"mqtt-client-1">>}, [{[<<"a">>, <<"c">>], 1}]) => next
```

but no `SUBACK` is returned.

**Comment by testark** [comment]
@ioolkos As for the protocol,

> When the Server receives a SUBSCRIBE Packet from a Client, the Server MUST respond with a SUBACK Packet [MQTT-3.8.4-1]

**Comment by ckrey** [comment]
Yes correct, the server MUST always respond with SUBACK.

The SUBACK contains either the maximum granted QoS level or 0x80 indicating a failed subscription per topic filter.

The spec is a bit weak by not explicitly stating what a "failed subscription" is. But a "failed subscription" is *not* a subscription which is denied by the authorization process. An acl may change over time and the permission for a specific message topic cannot be checked at the time of SUBSCRIBE to a topic filter in all cases.

E.g. mosquitto does `not`return 0x80 even if access is not allowed to the requested topic.

In general, there is no feedback from the server defined regarding authorisation except in CONNECT/CONNACK. Even a PUBLISH to a topic the user has no access to (and is therefore denied by the broker) is handled as a positive flow between client and broker.

aclfile
```
topic MQTTClient

user MQTTClient
topic MQTTclient/private
```

client
```
$ mosquitto_sub -t 'MQTTClient/private' -v -d -q 2
Client clientID sending CONNECT
Client clientID received CONNACK
Client clientID sending SUBSCRIBE (Mid: 1, Topic: MQTTClient/private, QoS: 2)
Client clientID received SUBACK
Subscribed (mid: 1): 2
^C
$ mosquitto_pub -t 'MQTTClient/private' -m 'xxx' -d -r -q 2
Client clientID sending CONNECT
Client clientID received CONNACK
Client clientID sending PUBLISH (d0, q2, r1, m1, 'MQTTClient/private', ... (3 bytes))
Client clientID received PUBREC (Mid: 1)
Client clientID sending PUBREL (Mid: 1)
Client clientID received PUBCOMP (Mid: 1)
Client clientID sending DISCONNECT
```

mosquitto
```
New connection from ::1 on port 1883.
New client connected from ::1 as clientID (c1, k60).
Sending CONNACK to clientID (0, 0)
Received SUBSCRIBE from clientID
MQTTClient/private (QoS 2)
clientID 2 MQTTClient/private
Sending SUBACK to clientID
Socket error on client clientID (0, 0)
Denied PUBLISH from clientID (d0, q2, r1, m1, 'MQTTClient/private', ... (3 bytes))
Sending PUBREC to clientID (Mid: 1)
Received PUBREL from clientID (Mid: 1)
Sending PUBCOMP to clientID (Mid: 1)
Received DISCONNECT from clientID
Client clientID disconnected.
```

If the topic level requested in the SUBSCRIBE is invalid (e.g. "abc/#/def"), it should be handled as a protocol violation (close connection).

**Comment by testark** [comment]
> But a "failed subscription" is not a subscription which is denied by the authorization process.

@ckrey from where did you draw this conclusion?

**Comment by ckrey** [comment]
Correct:

a) server MUST return a SUBACK
b) SUBACK should state the granted QoS level (00, 01, 02)

**Comment by testark** [comment]
@ckrey:

> b) SUBACK should state the granted QoS level (00, 01, 02)

**OR** `0x80` to indicate failure (whish *is* the case).

**Comment by testark** [comment]
@ckrey to quote the spec again,

> [MQTT-3.8.4-5] The SUBACK Packet sent by the Server to the Client MUST contain a return code for each Topic Filter/QoS pair. This return code MUST either show the maximum QoS that was granted for that Subscription or indicate that the subscription failed.

**Comment by ioolkos** [comment]
@ckrey thanks for this thorough description! 
So, in short, Mosquitto doesn't return the failure either.

In fact, we might have [overlooked 0x80 completely]
(https://github.com/erlio/vmq_commons/blob/master/src/vmq_parser.erl#L402)

**Comment by testark** [comment]
@ioolkos thanks for taking the time :-) So, please let me ask if this is something you are planning to "fix" in a near future?

**Comment by ckrey** [comment]
To be honest, I do not know what a "failed subscription" is. Will ask paho-dev

**Comment by ioolkos** [comment]
@testark if this needs to be fixed, we're certainly planning to fix it.
Can't promise a new release within 2 weeks though.

Also, I'm really curious too what a failed subscription is :)

**Comment by testark** [comment]
@ioolkos OK, thank you so much :-)

@ioolkos @ckrey pardon me if I'm wrong, but ain't a "failed subscription" a subscription that didn't actually succeed?

**Comment by ckrey** [comment]
https://dev.eclipse.org/mhonarc/lists/paho-dev/msg03124.html

**Comment by ralight** [comment]
mosquitto disconnects you if you provide an invalid subscription string.

Access control is currently limited to PUBLISH only (so your subscription may have been successful, but you won't receive any messages due to a denial). This is because matching a topic against a wildcard sub is easy, but matching a wildcard sub against a wildcard acl is more difficult. I had to disable returning 0x80 so it wasn't producing incorrect behaviour and have only had bugfix releases since.

mosquitto 1.5 will return 0x80 when a subscription is denied.
If access to the topic is denied

**Comment by testark** [comment]
@ralight Thank you very much for your input :-)

**Comment by ckrey** [comment]
The answer from ralight was triggered by my request to paho-dev

**Comment by testark** [comment]
@ioolkos That's great :-)
