### ISSUE TITLE
Dropped messages

### ISSUE THREAD

**Issue by monoton** [erlio/vernemq#721]
### Environment

- VerneMQ Version: 1.4.0
- Erlang/OTP version: 20.3
- OS: docker image running on Centos 7

### Preface
Testing Performance
Scheme:
publisher ---message---> broker ---> subscriber
Publisher generates around 70k rps

HW(Publisher): 4Core, 4RAM, SSD, ~ 30% LOAD
HW(Broker): 8Core, 8RAM, NON-SSD ~ 60% LOAD
HW(Subscriber): 4Core, 4RAM, NON-SSD, ~30% LOAD

Sometimes i have "dropped messages" in logs  like:                                  
`[warning] subscriber {[],<<"subscriber">>} dropped 705 messages`
Its subscriber hardware problem or it posibble to tune?

**Comment by ioolkos** [comment]
@monoton thanks for asking!
The knob to tune for "dropped messages" is `max_online_messages`. This is a per queue setting (but set globally). When the queue has more than the configured number of messages at some point, it will drop messages. See docs here: https://vernemq.com/docs/configuration/options.html

Setting `max_online_messages` is not your silver bullet though, as it might load to high RAM requirements.
Now why does the queue fill up in the first place? Yes, maybe slow consumer. Maybe CPU bound by broker. Maybe bandwidth.

I'm interested what and how you are testing exactly. Let's exchange learnings in any case!

**Comment by monoton** [comment]
Thanks, that tweak helps

But now we have another strange behavior
Publisher send messages to broker around 70k msg/s.
Scheme:
publisher ---message---> broker ---> restreamer ---> broker

Publisher generates around 70k msg/s to some topics
Restreamer gets all messages from this topics, do some business logic and pushing to another topic
When restreamer subscribed and publish with different clientIDs everything right
When restreamer subscribed and publish with same clientIDs both messages are not published without any errors. But if simulate same case without high load - everything fine.
Something happens only on high load.

**Comment by ioolkos** [comment]
@monoton what does "published without any error" entail?

You're sending the same amount of messages over one TCP connection (same ClientID), or two TCP (different ClientIDs) connections. I think this is the base explanation for different behaviour under high load in this scenario.

**Comment by monoton** [comment]
We tryed subscribe and publish in same TCP connection (((
When split this operations by each unique connections - everything works fine. It seems kernel restriction.
Issue can bew closed
