### ISSUE TITLE
vernemq cluster

### ISSUE THREAD

**Issue by medaboub** [erlio/vernemq#729]
In case of using a cluster composed of two vernemq nodes.  I should only call  the master ip address  for all my mqtt clients ?
Is vernemq handle node over load and then forward requests to other node automatically when master node raise process limit ?
thanks

**Comment by ioolkos** [comment]
Hi @medaboub thanks for your question.
It's not exactly as you describe... the cluster normally would run behind a loadbalancer (like HAProxy). The loadbalancer can be configure to use different routing way, but you'd probably go for round robin routing here.
Does this clear things up?

**Comment by medaboub** [comment]
yes thanks for reponse.
