### ISSUE TITLE
CONNACK not returning "session present" flag

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#73]
( Sorry if I am opening many issues, but we're heavily testing VerneMQ and I find this can be an opportunity for improvements :-) )

I found that VerneMQ isn't correctly returning the "session present" flag on `CONNACK` packets when using "clean session" set to false. It is always returned as false even though

```
vmq_reg:status({"", <<"some-client">>}).
```

returns

```
{ok,{offline,fanout,0,0,false}}
```

i.e., a session is indeed present.

Currently this isn't much of a problem for us, but anyway it would be great if you could have a look at this :-)

**Comment by ioolkos** [comment]
Thank you very much for opening any issues! very welcome :)

**Comment by dergraf** [comment]
Working on it here, still some more work necessary.
https://github.com/erlio/vmq_server/pull/30

**Comment by testark** [comment]
@dergraf Great to hear that! Many thanks!

**Comment by dergraf** [comment]
@testark is it possible that you could get in touch with us over email? we'd love to know more about you and your usecase as it helps us to better promote VerneMQ (which eventually results in an even better product)! What do you think?
