### ISSUE TITLE
Authentication with client certificates and ACLs

### ISSUE THREAD

**Issue by alessandrocarminati** [erlio/vernemq#744]
### Environment

- VerneMQ Version: 1.4.0-1
- OS: debian stretch/sid

I'm trying build a solution where VerneMQ should be the hub of the communication between my devices and the back end. Each device is equipped with a client certificate and key and it should connect  the broker. My requirement states that each device must be able to publish and subscribe  only its topic.
My guess is that the following configuration do the trick
```
allow_anonymous = off
listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile   = /etc/vernemq/ca.crt.pem
listener.ssl.certfile = /etc/vernemq/vernemq01.crt.pem
listener.ssl.keyfile  = /etc/vernemq/vernemq01.key.pem
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on
plugins.vmq_acl = on
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10

```
but all I got is 
```
VerneMQ# vmq-admin trace client client-id=GwAgent-1c497beffecab36d
No sessions found for client "GwAgent-1c497beffecab36d"
New session with PID <7251.422.0> found for client "GwAgent-1c497beffecab36d"
<7251.422.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" CONNECT(c: GwAgent-1c497beffecab36d, v: 4, u: 1c497beffecab36d, p: 1c497beffecab36d, cs: 0, ka: 30)
<7251.422.0> Calling auth_on_register({{192,168,97,67},33735},{[],
                                                               <<"GwAgent-1c497beffecab36d">>},1c497beffecab36d,1c497beffecab36d,false) 
<7251.422.0> Hook returned {error,no_matching_hook_found}
<7251.422.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" CONNACK(sp: 0, rc: 5)
<7251.422.0> Trace session for GwAgent-1c497beffecab36d stopped

```
the CN within the certificate is 1c497beffecab36d, it exists a user "1c497beffecab36d" ant its password is "1c497beffecab36d", just to be sure.
and the vmq.acl is as follows
```
topic dummy
user backend
topic #
user 1c497beffecab36d
topic %u/#
```

When "**listener.ssl.use_identity_as_username**" is turned to "on", are the username and password necessary? I read somewhere that only the password is needed. Anyhow in spite a day of tests I couldn’t manage to get my client authenticated ad regulated via access list. 

At any rate the only way I found to get my clients authenticated and make them exhange messages is to disable ACLs "**plugins.vmq_acl = off**" and allow anonymous clients "**allow_anonymous = on**"

**Comment by ioolkos** [comment]
Hi @alessandrocarminati thanks for opening the issue.
I apologise for any friction & effort. I think we have to improve the documentation* and possibly also the config. 
@dergraf @larshesel can you give us a quick reminder of the hook logic/order here?
Specifically: What should be the config values if one wants to:

- use client certs
- use common name as username
- don't use passwords in addition
- still use ACLs to configure topic permissions, obviously using the username-from-common-name

*https://vernemq.com/docs/configuration/listeners.html

**Comment by codeadict** [comment]
Seems like you don't have the vmq_passwd module installed with `plugins.vmq_passwd = on`? What happens is that you need to have that or any authentication mechanism enabled. When your client tries to connect it is triggering the `auth_on_register` hook but there is no authentication plugin to call.

**Comment by dergraf** [comment]
Hi @alessandrocarminati
Yes, VerneMQ is able to handle this case... First, what you want to achieve is bypassing the VerneMQ authentication mechanism and leaving authentication completely to TLS client certificates. In this case you'd require to use:
```
allow_anonymous = on
listener.ssl.require_certificate = on
plugins.vmq_passwd = off
```
`allow_anonymous = on` is a global option and is set on all existing and future listeners, so *always* ensure that your listeners are protected using `listener.ssl.require_certificate = on`. Managing a certificate revocation list (CRL) is usually more cumbersome than managing the client credentials somewhere else we always recommend to use an additional authentication plugin such as `vmq_passwd`, `vmq_webhooks`, or a custom one. Your scenario however, requires to disable any authentication plugin, which is in this case the default one `plugins.vmq_passwd = off`.

**Important:** Because `allow_anonymous = on` is a global option we discourage from using it in a production setting.

As a side note: VerneMQ is not known to be the fastest when handling TLS, that doesn't mean it isn't fast enough for your purpose. However in case you need high performance we always recommend to terminate TLS in the load balancer such as HAProxy and configure the TLS client certificate handling over there. Then use the Proxy Protocol feature in HAProxy and VerneMQ to pass client certificate details from HAProxy to VerneMQ. See here https://vernemq.com/docs/configuration/listeners.html#proxy-protocol

**Comment by alessandrocarminati** [comment]
Hello @dergraf, 
thank you for the precious details I gave me. 
I would bet I tried your suggestion as my first try, but I can't exclude I made mistakes all around, invalidating my test. 
I'll give another try in the next few  minutes, because it seems to me this is the solution I were looking for. 
About the ACL, as I state before, in my ideal solution I 'd like to refer my clients using the CN contained in the certificate, could you please confirm again this is the way to fine tune my clients?
Also, thanks for the hint of using HAPROXY in front of the VerneMQ. For now performance is not an issue in my scenario, but if it would, I'll sure follow your suggestion.
I hope I can confirm your hints are the solution I were looking for.
Thank you, I'll write the outcome of my test in the next few minutes.

**Comment by alessandrocarminati** [comment]
Hello @dergraf,
I follow your suggestion and I felt again in the problem I firstly faced. Clients get correctly logged in, the intended client get no error when it publishes things on the topic of the client that should receive the message, but at last the latter do not actually receive anything. It sounds like a problem in the ACL, but I can't be sure of that.
To be more specific I have to fall in my specific scenario, I hope to not abuse of your patience.
I have a client named **console** which has the right to publish any topic; I also have another client which is allowed to publish and subscribe only in its specific topic, this latter is named **1c497beffecab36d**.
**console** publishes things on the **1c497beffecab36d** topic.

```
# vmq-admin trace client client-id=GwMasterPW 
No sessions found for client "GwMasterPW"
New session with PID <7251.549.0> found for client "GwMasterPW"
<7251.549.0> MQTT RECV: CID: "GwMasterPW" CONNECT(c: GwMasterPW, v: 4, u: console, p: console, cs: 0, ka: 30)
<7251.549.0> MQTT SEND: CID: "GwMasterPW" CONNACK(sp: 1, rc: 0)
<7251.549.0> MQTT RECV: CID: "GwMasterPW" SUBSCRIBE(m1) with topics:
    q:2, t: "1c497beffecab36d/response/sys_get_ver"
<7251.549.0> Calling auth_on_subscribe(console,{[],<<"GwMasterPW">>}) with topics:
    q:2, t: "1c497beffecab36d/response/sys_get_ver"
<7251.549.0> Hook returned "ok"
<7251.549.0> MQTT SEND: CID: "GwMasterPW" SUBACK(m1, qt[2])
<7251.549.0> MQTT RECV: CID: "GwMasterPW" PUBLISH(d0, q2, r0, m2, "1c497beffecab36d/request/sys_get_ver") with payload:
    {"id":"d551e0ba83df1ddac14ab8320ed9e549","identity":"1c497beffecab36d","masterpsw":"@data"}
<7251.549.0> Calling auth_on_publish(console,{[],<<"GwMasterPW">>},2,1c497beffecab36d/request/sys_get_ver,false) with payload:
    {"id":"d551e0ba83df1ddac14ab8320ed9e549","identity":"1c497beffecab36d","masterpsw":"@data"}
<7251.549.0> Hook returned "ok"
<7251.549.0> MQTT SEND: CID: "GwMasterPW" PUBREC(m2)
<7251.549.0> MQTT RECV: CID: "GwMasterPW" PUBREL(m2)
<7251.549.0> MQTT SEND: CID: "GwMasterPW" PUBCOMP(m2)
<7251.549.0> MQTT RECV: CID: "GwMasterPW" DISCONNECT()
```
Trace seems to suggest that console is allowed to publish, but **1c497beffecab36d** do not receive anything.
my acl file is as follows:
```
topic dummy
user provision
topic read provision/request/prov_set_identity
topic write provision/response/prov_set_identity
user dashboard
topic #
user AppBe
topic #
user console
topic #
user 1c497beffecab36d
topic %u/#
user 58a0cbeffe015564
topic %u/#
```
I manage to get message from  **1c497beffecab36d** only changing the first line of the ACL from `topic dummy` in `topic # `, but in this way I have no ACL at all.
I'm confused. Could you please point to something I did wrong in what I've done?
Thank you again.

**Comment by dergraf** [comment]
Actually your trace is showing that the client used the username `console` and not `1c497beffecab36d`, which I guess is the one from the CN. 
Btw. you're restarting VerneMQ everytime you change the `vernemq.conf` right?

**Comment by alessandrocarminati** [comment]
Hello,
Yes I traced the client which published the data, not the one which is subscribed.
And yes, I restart the daemon each time I change the conf.
Now I traced the not receiving client:

```
# vmq-admin trace client client-id=GwAgent-1c497beffecab36d
Starting trace for 1 existing sessions for client "GwAgent-1c497beffecab36d" with PIDs
    [<7251.503.0>]
<7251.503.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBLISH(d0, q2, r0, m4, "1c497beffecab36d/request/sys_get_ver") with payload:
    {"id":"848d1f746f0ab036df551fc58c94ecc2","identity":"1c497beffecab36d","masterpsw":"@data"}
<7251.503.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBREC(m4)
<7251.503.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBREL(m4)
<7251.503.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBCOMP(m4)
<7251.503.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PINGREQ()
<7251.503.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PINGRESP()
<7251.503.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PINGREQ()
<7251.503.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PINGRESP()
```
Please help me to correctly interpret this.
It seems to tell me that it actually sent the data to my client, but it did not receive anything. Is that correct?
Is problem in my client side?
If so, actually could be, why if I put a more permissive ACL my client receives data as I expected?
following the trace with a permissive ACL
```
# vmq-admin trace client client-id=GwAgent-1c497beffecab36d
<7251.426.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBLISH(d0, q2, r0, m1, "1c497beffecab36d/request/sys_get_ver") with payload:
    {"id":"41b0344516d14959d2afe065e30b2c5f","identity":"1c497beffecab36d","masterpsw":"@data"}
<7251.426.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBREC(m1)
<7251.426.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBREL(m1)
<7251.426.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBCOMP(m1)
<7251.426.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBLISH(d0, q2, r0, m1, "1c497beffecab36d/response/sys_get_ver") with payload:
    {"id":"41b0344516d14959d2afe065e30b2c5f","response":"done","firmware":"Version 0.5-Unidata.1529662520","agent":"agentMQTT 0.1.MIPSEL.1529910030"}

<7251.426.0> Calling auth_on_publish(1c497beffecab36d,{[],
                                                       <<"GwAgent-1c497beffecab36d">>},2,1c497beffecab36d/response/sys_get_ver,false) with payload:
    {"id":"41b0344516d14959d2afe065e30b2c5f","response":"done","firmware":"Version 0.5-Unidata.1529662520","agent":"agentMQTT 0.1.MIPSEL.1529910030"}

<7251.426.0> Hook returned "ok"
<7251.426.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBREC(m1)
<7251.426.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" PUBREL(m1)
<7251.426.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" PUBCOMP(m1)
```

**Comment by dergraf** [comment]
Given your first trace... your client is receiving the publish and is properly responding with PUBREC and PUBCOMP, as well as it is sending proper PINGREQ s... so this could indeed be a client issue.

**Comment by alessandrocarminati** [comment]
Ok, assuming it is a client issues, as it appears to be, which is the difference between the first trace, where the client reports nothing and the second where it actually receive the payload and responds?
Please, if it is a client issue, give me an hint of what can be the difference in those two, apparently equals publishes.

**Comment by dergraf** [comment]
AFAICT the only differences in the traces are that the client has sent a Publish towards the broker.

**Comment by larshesel** [comment]
Maybe it would be possible to try with the `mosquitto_sub` client (mosquitto tools)? If one passes the `-d` flag it will print output to the command line similar to the trace output showing what it receives.

**Comment by alessandrocarminati** [comment]
Thank you a lot for your help. I'll start a session for debug the library I used to build my client. The publish seen in the trace is the intended behaviour of this particular application. The client received a request, therefore responds to it, publishing the answer. My question was more deep, not related with the trace, or at least not direly.  I meant, you you're informed of any difference in the publish the server produces in the two situation. But maybe I'm asking too much, an it would be better see, if I can fix this on client side.
If I will come out with a solution or at least with an explanation for this behaviour, I will add a post in this thread,  thank you for the moment.

**Comment by alessandrocarminati** [comment]
Going deep into the library, it appears to me that my problem is laying in the fact that the library I'm using react to **suback** failure event not registering the callback function.
```
w acl
DEBUG SUBACK <------------------------- 9003 000180
wo acl
DEBUG SUBACK <------------------------- 9003 000100
```
Remaining the fact that I must find a way to handle this situation, is there any reason why the server answer me with **suback** failure while behave as if the client is subscribed? I mean if I got **suback** failure shouldn’t I expect the client not registered therefore not receive any published data?

**Comment by larshesel** [comment]
How does the concrete subscription look that gets rejected and where a negative ack is sent, and which user sent it? A negative ack means that the plugin handling the subscription request couldn't authorize it. So this would mean that the acl is somehow not matching the subscription.

How does the trace output look when doing the subscriptions?

**Comment by alessandrocarminati** [comment]
Hello, 
here the subscription **with acl**
```
DEBUG SUB <------------------------- 821f 0001 001a316334393762656666656361623336642f726571756573742f2300
DEBUG SUBACK <------------------------- 9003 000180
```
here the same **without acl**
```
DEBUG SUB <------------------------- 821f 0001 001a316334393762656666656361623336642f726571756573742f2300
DEBUG SUBACK <------------------------- 9003 000100
```
Subscription is done in the same way, I wonder what's happen server side. Could you plesa suggest me a way to debug this server side? Please consider I have no Erlang knowledge.

**Comment by larshesel** [comment]
What does `vmq-admin trace` output when the subscriptions are done?

**Comment by alessandrocarminati** [comment]
Here's the twos:
with acl
```
<7251.427.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" CONNECT(c: GwAgent-1c497beffecab36d, v: 4, u: 1c497beffecab36d, p: 1c497beffecab36d, cs: 0, ka: 30)
<7251.427.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" CONNACK(sp: 1, rc: 0)
<7251.427.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" SUBSCRIBE(m1) with topics:
    q:0, t: "1c497beffecab36d/request/#"
<7251.427.0> Calling auth_on_subscribe(1c497beffecab36d,{[],
                                                         <<"GwAgent-1c497beffecab36d">>}) with topics:
    q:0, t: "1c497beffecab36d/request/#"
<7251.427.0> Hook returned {error,chain_exhausted}
<7251.427.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" SUBACK(m1, qt[not_allowed])
```
without acl
```
<7251.433.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" CONNECT(c: GwAgent-1c497beffecab36d, v: 4, u: 1c497beffecab36d, p: 1c497beffecab36d, cs: 0, ka: 30)
<7251.433.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" CONNACK(sp: 1, rc: 0)
<7251.433.0> MQTT RECV: CID: "GwAgent-1c497beffecab36d" SUBSCRIBE(m1) with topics:
    q:0, t: "1c497beffecab36d/request/#"
<7251.433.0> Calling auth_on_subscribe(1c497beffecab36d,{[],
                                                         <<"GwAgent-1c497beffecab36d">>}) with topics:
    q:0, t: "1c497beffecab36d/request/#"
<7251.433.0> Hook returned "ok"
<7251.433.0> MQTT SEND: CID: "GwAgent-1c497beffecab36d" SUBACK(m1, qt[0])
```

**Comment by alessandrocarminati** [comment]
hello, 
I realized I do not explicitly wrote what I mean with  "with acl" and "without acl".
In fact in both situation I have the same conf file, which is the one I added in previous posts, and that I paste here for your convenience
```
allow_anonymous = off

allow_register_during_netsplit = off
allow_publish_during_netsplit = off
allow_subscribe_during_netsplit = off
allow_unsubscribe_during_netsplit = off
allow_multiple_sessions = off
max_inflight_messages = 20
max_online_messages = 1000
max_offline_messages = 1000
max_message_size = 0
upgrade_outgoing_qos = off
listener.max_connections = 10000
listener.nr_of_acceptors = 10
#listener.tcp.default = 127.0.0.1:1883
listener.vmq.clustering = 0.0.0.0:44053
listener.http.default = 127.0.0.1:8888
listener.mountpoint = off

listener.ssl.default = 0.0.0.0:8883
listener.ssl.cafile   = /etc/vernemq/ca.crt.pem
listener.ssl.certfile = /etc/vernemq/vernemq01.crt.pem
listener.ssl.keyfile  = /etc/vernemq/vernemq01.key.pem
listener.ssl.require_certificate = on
listener.ssl.use_identity_as_username = on

systree_enabled = on
systree_interval = 20000
graphite_enabled = off
graphite_host = localhost
graphite_port = 2003
graphite_interval = 20000
shared_subscription_policy = prefer_local

plugins.vmq_acl = on
vmq_acl.acl_file = /etc/vernemq/vmq.acl
vmq_acl.acl_reload_interval = 10
plugins.vmq_passwd = on
vmq_passwd.password_file = /etc/vernemq/vmq.passwd

plugins.vmq_diversity = off
plugins.vmq_webhooks = off
plugins.vmq_bridge = off

vmq_diversity.script_dir = /usr/share/vernemq/lua
vmq_diversity.auth_postgres.enabled = off
vmq_diversity.auth_mysql.enabled = off
vmq_diversity.auth_mongodb.enabled = off
vmq_diversity.auth_redis.enabled = off
log.console = file
log.console.level = debug
log.console.file = /var/log/vernemq/console.log
log.error.file = /var/log/vernemq/error.log
log.syslog = off
log.crash = on
log.crash.file = /var/log/vernemq/crash.log
log.crash.maximum_message_size = 64KB
log.crash.size = 10MB
log.crash.rotation = $D0
log.crash.rotation.keep = 5
nodename = VerneMQ01@127.0.0.1
distributed_cookie = vmq
erlang.async_threads = 64
erlang.max_ports = 262144
leveldb.maximum_memory.percent = 70
```
and the followings acl files:
with acl:
```
topic #
user provision
topic read provision/request/prov_set_identity
topic write provision/response/prov_set_identity
user dashboard
topic #
user AppBe
topic #
user console
topic #
user 1c497beffecab36d
topic %u/#
user 58a0cbeffe015564
topic %u/#
```
without acl:
```
topic dummy
user provision
topic read provision/request/prov_set_identity
topic write provision/response/prov_set_identity
user dashboard
topic #
user AppBe
topic #
user console
topic #
user 1c497beffecab36d
topic %u/#
user 58a0cbeffe015564
topic %u/#
```

**Comment by larshesel** [comment]
I think I spotted the problem. Pattern rules are prefixed with `pattern`, not `topic`. See description here: https://vernemq.com/docs/configuration/authorization.html

**Comment by larshesel** [comment]
Note, the docs also says that pattern rules apply to *all* users, so I'm not completely sure you can do what you're trying to do above with different pattern rules for each user.

**Comment by alessandrocarminati** [comment]
So my problem were sitting in pattern variables?!
Not such a big problem for me, it is not mandatory for my use case use them, I can easily replace that things (pattern variables) with full strings in my ACLs.
I'm currently testing how the new ACLs are performing.
Replacing
```
user 1c497beffecab36d
topic %u/#
```
with
```
user 1c497beffecab36d
topic 1c497beffecab36d/#
```
It seems to work a little better than before. Until now, it match my expectations.
I think I'll reserve some time to test this new solution.

By the way, how the subscriptions really work in VerneMQ?
I mean, yesterday the behaviour of sending me data in spite the previous subscription were denied confused me a lot.
Is that an intended behaviour?
By the way, I observed during one of the many testes I did, that subscriptions survived also the server restart, which puzzled me a lot.
Please throw an eye on this:
The following is what is appearing to me with my client online and subscribed.
```
# vmq-admin session show --topic --user
+----------------------------------------+----------------+
|                 topic                  |      user      |
+----------------------------------------+----------------+
|  provision/response/prov_set_identity  |      null      |
|   CN=provision/response/sys_get_ver    |      null      |
|CN=provision/response/prov_set_identity |      null      |
|CN=1c497beffecab36d/response/sys_get_ver|      null      |
| 1c497beffecab36d/response/sys_get_ver  |      null      |
|          provision/request/#           |      null      |
| 1c497beffecab36d/response/sys_get_ver  |      null      |
|         CN=provision/request/#         |1c497beffecab36d|
|       1c497beffecab36d/request/#       |1c497beffecab36d|
+----------------------------------------+----------------+
```
After it quits (and unsubscribes) all the topics the situations appears as following.
```
# vmq-admin session show --topic --user
+----------------------------------------+----+
|                 topic                  |user|
+----------------------------------------+----+
|  provision/response/prov_set_identity  |null|
|   CN=provision/response/sys_get_ver    |null|
|CN=provision/response/prov_set_identity |null|
|CN=1c497beffecab36d/response/sys_get_ver|null|
| 1c497beffecab36d/response/sys_get_ver  |null|
|          provision/request/#           |null|
| 1c497beffecab36d/response/sys_get_ver  |null|
|         CN=provision/request/#         |null|
|       1c497beffecab36d/request/#       |null|
+----------------------------------------+----+
```
My use case expects that, an out of the box device subscribes a common topic, (because it is equipped only with the provisioning certificate) and fetch its new certificate using that channel.
After this, it quits, unsubscribes its provisional account and it is not meant it to use that account any further. If my interpretation's correct, when it start again with the previously fetched certificate, it remains subscribed also to the provisional account. While I can surely fix this behaviour client side, it looks to me that this behaviour is not an intended behaviour. Could you please cast some light on this?
Really thanks for the support.

**Comment by larshesel** [comment]
MQTT specifies that if the client connects with clean_session=false then the session state is stored on the server. To achieve that no date is stored between reconnects you need to pass `clean_session=true`  when the connects.

It is normal MQTT behaviour to deny a subscription and accept others depending on the ACL. The client has to realize that some subscription attempts were rejected and act accordingly as this means it will not get any messages for those subscriptions.

I hope this helps.

Let us know if you have further questions.
