### ISSUE TITLE
Use Cowboy to serve HTML app

### ISSUE THREAD

**Issue by cmnstmntmn** [erlio/vernemq#746]
hey, 

i have the following needs:

- agregate IoT data with VerneMQ
- store ACL and sensors metadata inside Postgres
- manage everytinhg via an interface

my question is: Is it possible to make use of Cowboy (via plugins) to serve a custom html app that consumes both **internal** and a **PostgREST** APIs ?

<img width="306" alt="arch" src="https://user-images.githubusercontent.com/2312755/41978393-6dc23584-7a2a-11e8-828d-e816b556de6b.png">

somehow the way `/status` page is beeing served

**Comment by dergraf** [comment]
@cmnstmntmn this is possible... however it's not really documented and is subject to change.
The magic happens in here https://github.com/erlio/vernemq/blob/master/apps/vmq_server/src/vmq_http_config.erl.. where we get the HTTP handler modules from the application environment and call the `routes` callback, so we can dynamically set up the cowboy routes.

The modules are configured via the hidden config variable `http_modules`, see https://github.com/erlio/vernemq/blob/a9b666ad042f493fc9cea32c06afac5241b4d0c9/apps/vmq_server/priv/vmq_server.schema#L281

I hope this helps.

**Comment by cmnstmntmn** [comment]
it does! thank you @dergraf

**Comment by dergraf** [comment]
Great. Keep in mind that we're not yet on Cowboy 2.0
