### ISSUE TITLE
Compiling on Raspian fails

### ISSUE THREAD

**Issue by cmnstmntmn** [erlio/vernemq#747]
### Environment

- VerneMQ Version: 1.4.0
- OS: Raspbian GNU/Linux 9 (stretch)
- Erlang/OTP version (if building from source): Erlang/OTP 19 [erts-8.2.1]
- OpenSSL: 1.1.0f-3+deb9u2

### Expected behavior

I'm trying to install VerneMQ from source running 

`make rpi32`

### Actual behaviour

the compilation process ends with this err:

```
make[1]: Entering directory '/home/vernemq/apps/vmq_passwd/c_src'
cc   vmq_passwd.c -lcrypto -o ../priv/vmq_passwd
vmq_passwd.c:32:25: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
                         ^
compilation terminated.
Makefile:13: recipe for target 'compile' failed
make[1]: *** [compile] Error 1
make[1]: Leaving directory '/home/vernemq/apps/vmq_passwd/c_src'
===> Hook for compile failed!

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1
```

**Comment by larshesel** [comment]
Hi, I believe you need to install the openssl developer libraries. I can't remember off the top of my head what they're called though (`apt get install ...`).

**Comment by cmnstmntmn** [comment]
indeed @larshesel 

`apt-get install libssl-dev` solved that.

thank you.
