### ISSUE TITLE
install vernemq in 32-bit PC (i386) ubuntu server 

### ISSUE THREAD

**Issue by medaboub** [erlio/vernemq#749]
haw to install vernemq in 32-bit PC (i386) ubuntu server  installed in 32bits intel Desktop for local development purpose. all destributions are for amd64 and when i try to compile source code i got errors in eleveldb and mzmetrics. I try to use differents versions of  g++ and gcc I secceed to compile mzmetrics with g++ 5.0 but always erros for eleveldb (g++ 4.8 & 5.0 & 6.0).

**Comment by larshesel** [comment]
Hi, you could try with the rpi32 target instead: `make rpi32`. Not sure if it will work, but it contains some patches which are needed for 32 bit compilation.

**Comment by medaboub** [comment]
OK compilation succeed .
