### ISSUE TITLE
Subscribing to $share/topic is killing the node

### ISSUE THREAD

**Issue by cmnstmntmn** [erlio/vernemq#756]
### Environment

- VerneMQ Version: 1.4.0-21c68522
- OS: Debian Stretch

### Expected behavior

Subscribe to a shared topic

### Actual behaviour

When i try to subscribe to `$share/topic` the verne node is going down.

1. with a test client try to subscribe to `$share/topic`
2. verne node is going offline right after you try to subscribe to the topic

![jul-04-2018 23-17-06](https://user-images.githubusercontent.com/2312755/42293125-732d2734-7fe0-11e8-8fa8-86ce31f46b2c.gif)

**Comment by cmnstmntmn** [comment]
in a cluster setup, all nodes dies

**Comment by ioolkos** [comment]
@cmnstmntmn can you try with a topic according to doc? subscribe to $share/name/topic, publish to topic?

Crashing the nodes should not happen, of course. Can you give me the exact steps you're doing?

**Comment by cmnstmntmn** [comment]
@ioolkos 

indeed using `$share/name/topic` doesn't kill the node.

steps to reproduce (single node or cluster behave the same):

1. try to subscribe to `$share/topic`
2. the node will go offline

**Comment by ioolkos** [comment]
Confirmed for 'master'. This has my vote for bug of the year :)
Thanks @cmnstmntmn !!

**Comment by ioolkos** [comment]
Fix incoming: https://github.com/erlio/vernemq/pull/757

**Comment by dergraf** [comment]
Closing, fixed in 1.4.1
