### ISSUE TITLE
CockroachDB auth plugin

### ISSUE THREAD

**Issue by cmnstmntmn** [erlio/vernemq#759]
I'm facing the following scenario:

1. a VerneMQ node with ACLS stored inside a postgres db
2. an **html interface** consumming data from the same db via a PostgREST API (ACLS, device meta, locations meta, etc)

all good so far; but at some point in time, a new node joins the cluster and we face the issue not having
db data from node A available for interface in node B and vice-versa.

![couchdb-auth-plugin](https://user-images.githubusercontent.com/2312755/42314043-cc020520-804c-11e8-828b-0c003eb17caa.jpg)

any plans to create a CouchDB auth plugin?

as benefits:

* it's also written in Erlang
* it expose an REST API
* it's easy to keep data in sync

thanks in advance

**Comment by ioolkos** [comment]
Hi @cmnstmntmn thanks for those colourful pictures! 

I like how you say CouchDB is trivial :) it might be in this case. Quick question: why multiple PostGres instances at all? is there a performance issue with those ACLs?

**Comment by ioolkos** [comment]
By the way, I'm no expert at CouchDB, but it might be relatively low hanging to do a vmq_diversity Lua script for it, maybe with the examples of the existing ones.

**Comment by cmnstmntmn** [comment]
the problem is not with VerneMQ cluster but with the **interface** (an html app).

If VerneMQ scales well (ACLSs beeing cached at the cluster level) the interface can't scale --> so a new cluster over that database to expose data to the interface is needed; that's why, i thought that having multi master databases in sync that serves both ACLS for VerneMQ clients and interface related data will make the architecture lot easier.

the ideea is to have to separate zones fully redundant

**Comment by dergraf** [comment]
@cmnstmntmn I don't understand the case with a new node joining the cluster. IMO the ACLs should be node agnostic. As a result every node can fetch the same ACLs from a DB given the client ID. Furthermore this allows that every client can connect to every node in the cluster.

Every VerneMQ node caches the ACLs independently, so no coordination is required. Moreover the caching happens at `auth_on_register`-time... so worst case scenario would be one DB request per new client connection. A single Postgres-Instance/Cluster should be good enough for most cases, if it's not, multiple tricks exist to speedup Postgres read performance.

**Comment by cmnstmntmn** [comment]
@dergraf thank you for your time!

i might be wrong, but as i said is not a VerneMQ related issue;

having the following scenario:

1. two locations Portland and New York;
2. employees in each location with different roles;
3. sensors in each location with different acces level;
4. a dashboard interface served locally inside intranet;
5. a PostgresSQL database where i store: sensors ACL, sensors metadata, employees roles, interface related data.

i expect to:

1. let an employee to see/controll sensors from any location;
2. if a location is offline (no VPN connection available) everything is fine.


my issues so far:

1. sensors can easly benefit of VerneMQ cluster communication; as you said their ACLs is node agnostic - all good here;
2. employees and the interface on the other hand, can consume data only from local PostgresSQL;

that's why i was thinking at a master/master replication solution

<img width="757" alt="master-master" src="https://user-images.githubusercontent.com/2312755/42345371-c79e7f80-80a7-11e8-9a0a-58c55fec34aa.png">

thanks in advance :)

**Comment by cmnstmntmn** [comment]
huh, that's complex.
it seems that CockroachDB solves a problem i've got, regarding replication

https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html

**Comment by cmnstmntmn** [comment]
@ioolkos any plans to support CockroachDB 
or the ball is in their field (to implement pgcrypto module functions) ?

**Comment by cmnstmntmn** [comment]
@knz started a prototype for a CockroachDB here https://github.com/knz/vernemq/commit/70ae05ad99f29389a09896a4570048d906072a3f

console.log

```
2018-07-13 02:11:21.991 [info] <0.390.0>@vmq_diversity_app:start:71 enable auth script for crdb "./share/lua/auth/crdb.lua"
2018-07-13 02:11:22.114 [info] <0.33.0> Application vmq_server started on node 'VerneMQ@127.0.0.1'
2018-07-13 02:11:28.341 [error] <0.396.0>@vmq_diversity_script_state:handle_info:175 can't call function auth_on_register with args [{addr,<<"127.0.0.1">>},{port,60897},{mountpoint,<<>>},{client_id,<<"test-client">>},{username,<<"test-user">>},{password,<<"123">>},{clean_session,false}] in "./share/lua/auth/crdb.lua" due to {error,function_clause}
2018-07-13 02:11:28.341 [warning] <0.480.0>@vmq_mqtt_fsm:check_user:555 can't authenticate client {[],<<"test-client">>} due to error
```

error.log
```
2018-07-13 02:11:28.341 [error] 
<0.396.0>@vmq_diversity_script_state:handle_info:175 can't call function auth_on_register with args [
{addr,<<"127.0.0.1">>},
{port,60897},{mountpoint,<<>>},
{client_id,<<"test-client">>},
{username,<<"test-user">>},
{password,<<"123">>},
{clean_session,false}] 
in "./share/lua/auth/crdb.lua" due to {error,function_clause}
```

config:

```
allow_anonymous = off
plugins.vmq_passwd = off
plugins.vmq_diversity = on

vmq_diversity.auth_crdb.enabled = on
vmq_diversity.postgres.host = localhost
vmq_diversity.postgres.port = 26257
vmq_diversity.postgres.user = root
vmq_diversity.postgres.database = vernemq_db
```

as far as i could debug, VerneMQ is not touching the database when the error is fired.

thank you in advance

**Comment by cmnstmntmn** [comment]
i managed to make VerneMQ authenticate with CockroachDB; 
still, unable to use encripted passwords.

https://github.com/knz/vernemq/compare/20180712-crdb-auth...cmnstmntmn:patch-1

**Comment by ioolkos** [comment]
@cmnstmntmn how do you save the encrypted password though? mustn't happen the error there?

**Comment by cmnstmntmn** [comment]
@ioolkos 

well, since `crypt()` is not available for CockroachDB, i tryed to use `sha256()`
but it seems is not available in lua.

i did a small test with `123` encoded as sha256
```
log.debug(sha256("a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3"))
```

and i don't get `123` back

error.log

```
2018-07-17 14:14:03.669 [error] <0.412.0>@vmq_diversity_script_state:handle_info:171 can't call function auth_on_register with args [{addr,<<"127.0.0.1">>},{port,51136},{mountpoint,<<>>},{client_id,<<"test-client">>},{username,<<"test-user">>},{password,<<"123">>},{clean_session,false}] in "./share/lua/auth/crdb.lua" due to {undef_function,nil}
```

**Comment by knz** [comment]
Wait I think you do not understand how password authentication works. 

Both `crypt` in the original code and `sha256` in my suggestion are **one-way** functions. You are not supposed to recover the password from the hash!

You also do not need the sha256 function in **lua** to make this work. It should only be present in the SQL query inside the `[[...]]` block.

**Comment by cmnstmntmn** [comment]
@knz i see what you're saying ..

well, in this case, when the sql block includes `password=sha256($4)` the error is this:

```
2018-07-17 14:34:33.604 [error] <0.413.0>@vmq_diversity_script_state:handle_info:171 can't call function auth_on_register with args [{addr,<<"127.0.0.1">>},{port,51571},{mountpoint,<<>>},{client_id,<<"test-client">>},{username,<<"test-user">>},{password,<<"123">>},{clean_session,false}] in "./share/lua/auth/crdb.lua" due to {badarg,'#',[false]}
```

and the CockroachDB is not even touched.

**Comment by cmnstmntmn** [comment]
hmm

```
password=sha256($4, password)
```

doing so, 

1. i can see the logs in crdb

```
I180717 11:38:33.749972 75940 sql/exec_log.go:168  [n1,client=127.0.0.1:51629,user=root] 4000 exec "" {} "SELECT publish_acl, subscribe_acl FROM vmq_auth_acl WHERE (((mountpoint = $1) AND (client_id = $2)) AND (username = $3)) AND (password = sha256($4, password))" {$1:"''", $2:"'test-client'", $3:"'test-user'", $4:"'123'"} 12.052 0 "
```

2. no errors in verne
3. but user is not authenticated

**Comment by knz** [comment]
Oh I see what is perhaps wrong. Try this in the SQL query: `sha256($4:::TEXT)`

**Comment by cmnstmntmn** [comment]
@knz that works!

**Comment by cmnstmntmn** [comment]
with @knz help, i've created this pull request https://github.com/erlio/vernemq/pull/770

i'm going to close this.

**Comment by larshesel** [comment]
Hi @cmnstmntmn I've started investigating if we can bring cockroach support into VerneMQ again. I've got a local crdb cluster running in minikube, but I get an error `Could not connect to postgresql due to <<"08P01">>` was this something you ever encountered?

**Comment by cmnstmntmn** [comment]
Hi @larshesel , well i managed to connect via the [modified postgress lua plugin](https://github.com/vernemq/vernemq/pull/770); however, things may not be the same due to crdb updates.

you can enable the sql execution log and see what the result of the lua plugin is.

https://www.cockroachlabs.com/docs/stable/query-behavior-troubleshooting.html#cluster-wide-execution-logs

**Comment by cmnstmntmn** [comment]
oh, now that i see you're not even touch the database. hmm.. ports, ip ?

**Comment by larshesel** [comment]
port and IP should be fine - I can connect with the postgresql `psql` tool - but it obviously does something else than what the erlang `epgsql` driver does ... I'll try to add the logs you  mentioned above - that might reveal sth. Thanks!

**Comment by larshesel** [comment]
opened up an issue on the epgsql driver: https://github.com/epgsql/epgsql/issues/192

**Comment by cmnstmntmn** [comment]
@larshesel may be related with this https://github.com/brianc/node-postgres/issues/503 ?
is the same error code `08P01`

**Comment by larshesel** [comment]
Seems the error there shows up doing the query and not while connecting. Btw, found this in the `epgsql` driver changelog for the 4.0.0 release: `* Redshift and CockroachDB users might expirience some problems. Please, report bugs!` (we use 4.2.1). Will try with the 3.4.0 version.

**Comment by larshesel** [comment]
3.4.0 gave me the same error - perhaps it's a change on crdb - which version are you using where it works? I'm on .2.1.6

**Comment by cmnstmntmn** [comment]
is was 2.1.0 beta

**Comment by cmnstmntmn** [comment]
@larshesel any luck?

**Comment by larshesel** [comment]
Yes, I just got it to work. I had to tell the `eqgsql` client to use ssl, like this:

```
epgsql:connect("localhost","vmq_test_user","vmq_test_password", #{ssl => true, database => "vmq_test_database", port => 26257}).
```

Then I'm able to connect.

**Comment by danielGz** [comment]
I know this is closed but I wanted to add, in case someone stumbles upon this, if using postgresql make sure you're using bcrypt as hashing method in your vernemq conf. Also make sure to import the extension in your database: "CREATE EXTENSION pgcrypto;"

I faced this issue because I had a database backup that I used to restore the database but it never installed the extension so I was going nuts.

**Comment by ioolkos** [comment]
@danielGz thanks for letting the community know!
