### ISSUE TITLE
Retained messages also delivered as offline.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#76]
This is again one of those areas where, IMHO, the spec isn't as clear as it could be, so I'd like to ask for your view on this.

Currently, both VerneMQ and Mosquitto deliver retained messages also as offline ones. So, for example, if
- `client-1` is subscribed to `a/b`;
- `client-1` is offline;
- `client-2` is publishing messages to `a/b` with `retained=true`;

when `client-1` re-connects _and_ re-subscribes `a/b`, it will
- receive all messages `client-2` published to `a/b` as offline _and_ with `retained=false`;
- receive the very last message published by `client-2` to `a/b` with `retained=true`;

We have a use case where it would be great to be able to only keep the retained message itself and discard the others, past ones (i.e., no messages published as `retained` would be delivered as offline ones for that topic). Would it be possible to support this behaviour in VerneMQ (maybe as an option)?

**Comment by ioolkos** [comment]
So `max_offline_messages = 0` is not what you want here? (this is a system wide config value)

**Comment by testark** [comment]
@ioolkos not quite exactly. What I would need, and that I think the protocols leaves open, is something like

"If a given message `M` is `PUBLISH`ed as *retained* to topic `T`, previous messages that have been `PUBLISH`ed to topic `T` as *retained* are *discarded*.".

In other words,

"Messages sent to a topic `T` as *retained* are not placed on the clients' queues. Rather, they are associated with the topic itself, not with a session."

Would it be easy to make this an optional behaviour?

**Comment by ioolkos** [comment]
OK, thanks :) I totally see what you mean.
This is interesting. The spec is unclear, yes, but I'm beginning to think that retained messages shouldn't go into an offline queue at all. Wondering what Mosquitto's thinking is on this.

"Retained messages do not form part of the Session state in the Server, they MUST NOT be deleted when the Session ends [MQTT-3.1.2.7]."

This seems to implicitly tell us that a retained message has absolutely nothing to do with session state (and offline QoS 1 message are part of session state).

**Comment by testark** [comment]
@ioolkos Yes, that's exactly what I mean. Mosquitto shows the same behaviour as VerneMQ at the moment. Do you think this could be easily achieved?

i'm unfortunately too short of time and can't promise delivering, but if I were to work on a PR could you please point out to me what the necessary changes would likely be?

**Comment by ioolkos** [comment]
I guess something like this for skipping retained messages totally. (Look at [https://github.com/erlio/vmq_server/blob/e229b5a0e05509f0b916bcbfcafa6df486cbbfff/src/vmq_queue.erl#L583](https://github.com/erlio/vmq_server/blob/e229b5a0e05509f0b916bcbfcafa6df486cbbfff/src/vmq_queue.erl#L583) )
```erlang
insert({deliver, _, #vmq_msg{retain=true}}, #state{sessions=Sessions} = State)
  when Sessions == #{} ->
    %% no session online, skip retained message
    State;
```
But yeah, we'd need to make a decision on how to read that spec first :)

**Comment by mherle** [comment]
If the publisher publishes with QoS = 0 and retained = true, then wouldnt this be working as what's required ?
* publishers publish as many values as needed for a topic with QoS = 0.
* live subscribers get as and when the publishers publish.
* new/returning subscribers get only the latest publish for the topic.

**Comment by testark** [comment]
@ioolkos thank you so much, really.

@mherle yes, but the spec also says that those retained QoS0 messages can be dropped by the broker if needed. We can't afford that.

**Comment by ioolkos** [comment]
I see that @testark actually never mentioned QoS at all, but I automatically supposed you need QoS 1.

If not, then of course @mherle's idea is the way to go.

**Comment by testark** [comment]
@ioolkos Yes :-) But I do need QoS 1 :-)

**Comment by ckrey** [comment]
@testark I think you misread the spec here

It does not say "If a given message M is published as retained to topic T, previous messages that have also been published to topic T as retained are discarded.".

It just says the broker "MUST discard any message previously retained for that topic" when it receives a QoS0/Retained message on the given topic. After that it SHOULD store the new payload, but it MAY choose not to do so.

The spec doesn't say to drop any previous messages (plural!).

The example you describe in the original issue differs depending on QoS level and on the CleanSession flag used by client-1:

If client-1 uses CleanSession = YES, only the retained messages are sent with retained=TRUE at re-subscribe.

If client-1 uses CleanSession = TRUE
- it does not need to resubscribe
- it will receive all messages sent by client-2 while offline, which had QoS > 0
- it will NOT receive a QoS 0 message sent during offline, even if it had retained = YES.
If this is your desired scenario, fine!

Summary:
- Retained messages are send only when a client SUBSCRIBEs
- Messages are queued in offline and sent after reconnect only if PUBLISH QoS>0 and SUBSCRIBE>0 and client re-connects with CleanSession=FALSE.

**Comment by testark** [comment]
@ckrey I did not misread the spec, but you surely misread what I wrote before that quote (the context!). That being, what you say does not really improve the discussion here. I was suggesting an (optional, VerneMQ-specific!) improvement / extension / new behaviour about something the spec leaves open.

**Comment by ioolkos** [comment]
@ckrey I apologise, I missed the opportunity to thank you & to go through your comment thoroughly. Were you saying that the current retain/offline situation was in fact correct according to spec?

**Comment by ckrey** [comment]
yep, retained messages are stored independent from the offline situation of the aubscribers. They are only sent after a SUBSCRIBE.
Messages are queued in offline of the subcriber if PUBLISH and subscription have  habe QoS > 0

**Comment by testark** [comment]
@ckrey @ioolkos I, of course, agree. However, I was suggesting that an option be provided to modify this behaviour in order to, optionally, prevent retained messages from being queued (just like there's an option to allow client IDs larger than 23 characters and another one to allow multiple clients to connect using the same ID).

**Comment by dergraf** [comment]
Can we conclude that we have the same understanding of the specification regarding this issue, and what @testark has proposed is a non-standard feature.

afaict @testark aims to setup offline clients without going through MQTT but rather uses the internal Erlang API see erlio/vernemq#70. Of course a setup of an offline client involves a manual call to the internal Erlang subscribe API, which properly triggers the delivery of the retained messages to those 'offline' clients. However, in a perfect world where all Clients are going through MQTT the mentioned case will never occur and can be neglected. E.g. a client that issues a SUBSCRIBE can never be offline at the same time and therefore the retained messages are properly enqueued.

I suggest to close this issue here, and start talking about shaping the internal API somewhere else.

**Comment by testark** [comment]
@dergraf:

> afaict @testark aims to setup offline clients without going through MQTT but rather uses the internal Erlang API see erlio/vernemq#70.

This is not the case with this issue :-) It's just that I believe that messages published as retained should not be sent to the subscribers' queues (as the spec clearly states they're not part of the session), and so shouldn't be delivered as offline. Could we please reopen this for discussion?

**Comment by dergraf** [comment]
we are always open for discussions ;)
I guess the spec you're mentioning is this one:

> [MQTT-3.1.2.7] Retained messages do not form part of the Session state in the Server, they MUST NOT be deleted when the Session ends.

But have a look at:
> [MQTT-3.3.1-9] It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received. 

Reading the spec above we think that VerneMQ has to treat the message as a 'normal' message for all other subscribers, and at this point we don't have to distinguish between offline and online subscriptions. 

Do you know of another open source MQTT broker that implements the retain functionality the way you're describing it?

**Comment by testark** [comment]
@dergraf I don't know of any, really, but it would be great to have such behaviour as an option.

**Comment by dergraf** [comment]
@testart is this still an issue for you or have you found a workaround?

**Comment by testark** [comment]
@dergraf No workaround found yet :-\

**Comment by dergraf** [comment]
@testark is this still an issue?

**Comment by syberkitten** [comment]
Is this Ok to assume then, that if we want retained topics to persist
even after all subscribers are disconnected, the next subscriber
will get a retained message from a topic only when the retained message
was published with Qos 1. ?

**Comment by dergraf** [comment]
No. QoS isn't considered for retained messages.

**Comment by dergraf** [comment]
From the spec:
[MQTT-3.3.1-7]
If the Server receives a QoS 0 message with the RETAIN flag set to 1 it MUST discard any message previously retained for that topic. It SHOULD store the new QoS 0 message as the new retained message for that topic, but MAY choose to discard it at any time - if this happens there will be no retained message for that topic.

VerneMQ currently chooses to not discard those messages.

**Comment by syberkitten** [comment]
Thank for clearing this Up :)

One other thing, Is there a configuration for a TTL for such
retained message? will it stay forever? until restart?
can this be configured?

**Comment by ioolkos** [comment]
There is no time to live configuration for retained messages. It is up to the clients to delete (or rather cancel out) retained messages, so the broker has to keep them indefinitely.

**Comment by larshesel** [comment]
Closing this as it's unlikely we'll implement this as we haven't had other people asking for it.
