### ISSUE TITLE
Broker does not respond to Client while Broker waits for PUBACK from QoS1 message

### ISSUE THREAD

**Issue by kevin-andium** [erlio/vernemq#764]
### Environment

VerneMQ Version: 1.3.2
OS: Ubuntu 16.04.4
Erlang/OTP version (if building from source): N/A

### Expected behavior
- The Broker sends PUBACKS (QoS1) and ping responses to Client A while waiting for PUBACK from Client A on message B (QoS1).

### Actual behaviour

-I'm currently seeing traces (through wireshark) where the Broker will attempt to Publish a message (QoS1). Due to an unreliable network, the Client does not receive the message. While the Broker is waiting for the PUBACK, the Client will send its own message (QoS1), but the Broker will not send a PUBACK, nor will it respond to a ping request. The client will then timeout and reconnect. This has occurred while to Broker and Client are attempting to send to the same topic and different topics.

  1. Broker sends a publish message with QoS1
  2. Due to a poor network, the Client does not immediately receive the message
  3. The Client attempts to Publish a message using QoS1
  4. Client's internal timeout triggers due to no PUBACK
  5. Client will send ping request
  6. Client's ping request will timeout and will reconnect

**Comment by ioolkos** [comment]
@kevin-andium thanks for opening this issue!

- do you happen to have max_inflight set to 1? 
- Where do you do the wireshark traces? (client or broker). Could you send us the wireshark lines in question per mail?
- Could you please do a MQTT trace for the ClientId on the broker? 
(like this `sudo vmq-admin trace client client-id=yourconsumer`)

**Comment by kevin-andium** [comment]
- max_inflight is set to 20

- I did the wireshark traces on the client. What email address is best to send the traces to?

- In further testing, I forced the Client to not send a PUBACK to any QoS1 messages from. I saw the broker was able to respond to all Client Publishes correctly even though it did not receive a PUBACK from the Client. This situation seems to only occur when the Broker's message has not been received by the Client due to a poor network. It seems like all Broker socket writes to the Client are blocked until the current message it is sending is received by the Client.

**Comment by ioolkos** [comment]
@kevin-andium apologies...missed your answer here! to send E-mail 'contact at octavolabs.com' would work.

**Comment by dergraf** [comment]
@kevin-andium we haven't received your message so far and assume the issue has been resolved. I close it for the moment, please open it again if the problem persists.
