### ISSUE TITLE
Lost messages when client abnormal disconnection 

### ISSUE THREAD

**Issue by boboxiaodd** [erlio/vernemq#768]
### Environment

- VerneMQ Version:1.4.0
- OS: centos7
- Erlang/OTP version (if building from source):

### Expected behavior

- Recv all messages (Qos = 2 )

### Actual behaviour

Shutdown client all network connect,
i check the logs , client is online
publish some messages to client  (Qos=2), 
i check the logs , client offline after 1 min 

when client open network ,
it don't recv offline messages

**Comment by ioolkos** [comment]
Hi @boboxiaodd thanks a lot for opening the issue!
I'm not 100% sure I understand the actual steps your're going through.
As a first question, do you do the following 3 things to ensure that VerneMQ will store offline messages for you?
-   connect the subscriber with clean session false.
-   subscribe with QoS > 0 and
-   publish with QoS > 0

**Comment by boboxiaodd** [comment]
@ioolkos 
clean_session = false
Qos = 2

i kill the client process ， client is disconnect immediately (vmq-admin session ...) ，and send message to client,
client wakeup , can recv all message

but  client abnormal disconnection, offline message lost In 1 minutes

**Comment by larshesel** [comment]
Can you show us how to reproduce this with the mosquitto_pub/mosquitto_sub commands and list the complete list of steps how to do it?

**Comment by boboxiaodd** [comment]
@larshesel
keepalive = 60s   clean_session =false  Qos=2
This is my test 1 :  
00:00  Shutdown client all network connect,
00:00  vmq-admin session show this client is online
00:00  pushlish msg1 to client 
00:01   pushlish msg2 to client 
00:02  pushlish msg3 to client
...
00:10  Open client network , and  client don't recv msg1,msg2,msg3
it's wrong


This is my test 2:
00:00  Shutdown client all network connect,
00:00  vmq-admin session show this client is online
00:00  pushlish msg1 to client 
00:01   pushlish msg2 to client 
00:02  pushlish msg3 to client
01:00  console show : @vmq_mqtt_fsm:connected:418 client   .....    stopped due to keepalive expired
01:01   pushlish msg4 to client
01:02  pushlish msg5 to client
...
01:10  Open client network , and  client recv all of msg1 - msg 5
it's correct

**Comment by boboxiaodd** [comment]
@ioolkos 
Shutdown client all network connect is mean：
client is phone , setting phone in Airplane mode ,or close wiffi and Mobile network

the server can't catch the network disconnect 
Is it the only when trigger  keepalive expired , then vernemq  save offline message ?

**Comment by ioolkos** [comment]
@boboxiaodd ok, thanks, got what you mean.
For test 1, try to determine what the Client lib does.
Are you sure it's setting up a new connection? Does the client do correct session state handling related to QoS 2? (can you tell us what Client lib it is?)

**Comment by larshesel** [comment]
You could also try to trace the client-id of the client which is supposed to receive the messages using `vmq-admin trace client client-id=<theclientid>`. That might shed some light on what's happening in the two scenarios.

**Comment by boboxiaodd** [comment]
@ioolkos @larshesel 
this is trace log ..
```bash
vmq-admin trace client client-id=c_41671194_744869294


#client is phone , setting phone in Airplane mode ,or close wifi and Mobile network
#send msg1 , msg2 to client
<7251.31844.3> MQTT SEND: CID: "c_41671194_744869294" PUBLISH(d0, q2, r0, m2, "u_41671194/message") with payload: msg1
<7251.31844.3> MQTT SEND: CID: "c_41671194_744869294" PUBLISH(d0, q2, r0, m3, "u_41671194/message") with payload: msg2

#client open wifi and Mobile network
#client  reconnect to vernemq
New session with PID <7251.32209.3> found for client "c_41671194_744869294"
<7251.32209.3> MQTT RECV: CID: "c_41671194_744869294" CONNECT(c: c_41671194_744869294, v: 4, u: 41671194, p: f26b4f027d5c0d64237e1e47489c941c, cs: 0, ka: 60)
<7251.32209.3> Calling auth_on_register({{58,37,40,29},64891},{[],<<"c_41671194_744869294">>},41671194,f26b4f027d5c0d64237e1e47489c941c,false) 
<7251.32209.3> Hook returned "ok"
<7251.32209.3> MQTT SEND: CID: "c_41671194_744869294" CONNACK(sp: 1, rc: 0)

#client don't recv msg1 and msg2
```

**Comment by boboxiaodd** [comment]
@chriswue 
i did't see "Trace session for my_client stopped"
mybe the reason is  i set: 
````ini
allow_multiple_sessions = on
````

**Comment by chriswue** [comment]
@boboxiaodd: What is queue_deliver_mode set to? The way I understand allow_multiple_sessions  is that vernemq will distribute messages to both client sessions. In your first case the first session is still active since the keep alive hasn't expired. I suspect that the messages sent while only the first session was active are allocated to that session.

What happens in the first case after the keep-alive timeout - will the first session eventually disappear?

I think you should probably just disable that setting. Form the docs:

> Sometimes consumers get overwhelmed by the number of messages they receive. VerneMQ can loadbalance between multiple consumer instances subscribed to the same topic with the same ClientId.

Given that your clients are mobile phones this seems an unlikely use-case (since you probably can't push a huge amount of messages to a phone client anyway)

**Comment by larshesel** [comment]
If you're using `allow_multiple_session=on` then I think the behaviour makes sense. In the case where the session expires you have only one session for the client id at a time. When the session expires the offline messages are stored in the queue. In the other case you have two sessions for the same client-id at the same time and the offline messages are likely still being held by the first session.

**Comment by boboxiaodd** [comment]
but  new session connected , old connection did't tagger keepalive timeout,  then msg lost.

**Comment by larshesel** [comment]
Hi,

I think there's an issue there alright, though not sure exactly what the problem is yet. Everything works if I reconnect the client (same client-id) after the first has timed out - then the messages are delivered. If another client with the same client-id is online while the first is timing out then it (or a later client with the same client-id) won't receive the messages.

Anyway, that said, I'd recommend using shared subscriptions for client load-balancing instead of multiple-sessions as it's a standard feature (albeit backported from MQTTv5), is simpler to understand (as there's a spec for it) and scales better (each subscriber has it's own queue process).

**Comment by chriswue** [comment]
@larshesel: Just as a last comment to this:

I think it would be good to at least update the documentation for the option to label it with a clear warning that if it is being used and multiple clients are connected that in the event of one client becoming disconnected for some reason messages loss is inevitable and that therefor this setup should only ever be used with QoS 0 messages.
