### ISSUE TITLE
offline message stored in LevelDB

### ISSUE THREAD

**Issue by elhamkazemi** [erlio/vernemq#769]
How to determine the number of offline messages stored for each client?
and is there a way to notify us when an offline message has been droped for a particular client?

**Comment by ioolkos** [comment]
Hi @elhamkazemi thanks.
You can see the options for the `vmq-admin session` command with:

`sudo vmq-admin session show --help`

Something like the following will show you the number of offline_messages for one or more client IDs.

`sudo vmq-admin session show --client_id=consumer1 --offline_messages`

**Comment by ioolkos** [comment]
@elhamkazemi 
`--online_messages` are the messages currently queued in the session, but for an online client. It's normal to see 0 there.

**Comment by elhamkazemi** [comment]
@ioolkos, thank you. 
Is there anyway to notify us when the max_offline_messages queue is full ?

**Comment by ioolkos** [comment]
@elhamkazemi currently there is no event that gets triggered at this point.
@dergraf @larshesel any ideas how this would be possible? (max_offline_message full event)

**Comment by larshesel** [comment]
Currently we only log sth when we drop messages (so after the queue has run full). It would be possible to create a hook for when the queue is full, but the question is how useful it would be in a running system where messages are flowing all the time: what kind of reaction can be done from a hook to prevent the next message from being dropped? In general I'd think the better solution is to over-dimension the size of the queues (so they never should get full during normal operation) and then monitor for dropped messages (and also the dropped message counter metric).

That said it would be interesting to know how you would use a queue full notification as it might reveal some use cases we haven't thought about :)

**Comment by elhamkazemi** [comment]
hi @larshesel thanks.
We are developing a messaging system and no messages should be deleted. To this end, we store all the published messages in the database. The problem with this is that when a client is online, we do not know which messages has been removed from the queue, and which message are in the queue so that they no longer need to be retrieved from database. If we are notified when a message is drop, we can specify it in the database.
If there is a way to manage the queue, we can prioritize clients that if the client is not online for a long time, the queue will be erased and we will retrieve the corresponding client messages from the database.

**Comment by behrad** [comment]
@elhamkazemi Are you using vernemq in Tehran?

**Comment by elhamkazemi** [comment]
@behrad yes.

**Comment by behrad** [comment]
Great to hear that, we can discuss more details if you like to email me

**Comment by behrad** [comment]
behradz AT gmail @elhamkazemi

**Comment by dergraf** [comment]
hey guys, let's close this for now! cheers!
