### ISSUE TITLE
UNSUBSCRIBE "unsubscribes" all clients

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#77]
I'm running into a strange behaviour with `UNSUBSCRIBE`. I noticed this in a two-node cluster setup, but the issue is reproducible in a single-node setup, so let's assume that for simplicity.

1. Connect four clients—let's say `client-1`, `client-2`, `client-3`, `client-4`—to the broker.
2. Subscribe all clients to the `t/0` topic.
3. Subscribe `client-1` to `t/1` as well.
4. Make `client-1` enter a loop and start publishing to `t/0` and `t/1` every 5 seconds.

So far so good—at this point, all four clients receive a message in `t/0` every 5 seconds. Now, if `client-2` unsubscribes from `t/0`, *all other three clients stop receiving messages*—even `client-1`, which had subscribed and is still publishing.

(At this point, `client-1` still publishes to and receives back from`t/1`, for the matter).

What's even more strange is that as soon as I re-subscribe `client-2` to `t/0`, *all four clients (and not only `client-2`) start receiving messages again on `t/0`*.

**Comment by testark** [comment]
In case it matters, I can reproduce this on both `0.12.2` and `0.12.3`. In case it also matters, neither Mosquitto nor EMQTT show this behaviour.

**Comment by ioolkos** [comment]
Thanks for reporting.
Confirmed this quickly. Whatever it is, it's highly critical misbehaviour.

**Comment by testark** [comment]
@ioolkos good you could reproduce :-) are you planning on a fix any soon?

**Comment by ioolkos** [comment]
Will start looking into this tomorrow/asap.

**Comment by testark** [comment]
@ioolkos Great to hear that :-) Thank you very much.

**Comment by ioolkos** [comment]
This line in [`vmq_reg_trie`](https://github.com/erlio/vmq_server/blob/master/src/vmq_reg_trie.erl#L181). We  falsely delete the topic in the ETS cache in case of any unsubscribe. But of course, we should only do this if we are the last existing subscriber.

I'll test later and see if it has more ramifications, but something along the lines like this should fix it:

```erlang
handle_delete_event({MP, _} = SubscriberId, [{Topic, QoS, Node}|Rest]) when Node == node() ->
	del_subscriber(MP, Topic, SubscriberId, QoS),
 	case ets:lookup(vmq_trie_subs, {MP, Topic}) of
        	[] ->
        	    del_topic(MP, Topic, Node);
        	_ ->
        	    ignore
    	end,	
    handle_delete_event(SubscriberId, Rest);
```

**Comment by testark** [comment]
@ioolkos Many thanks :-) Just please tell me... There's a branch of that function on line 185 (https://github.com/erlio/vmq_server/blob/master/src/vmq_reg_trie.erl#L185) where `del_topic` is also used. Should this fix you provided be placed on both branches or just on the first one?

**Comment by testark** [comment]
@ioolkos I've placed that both in lines 181 and 185 and it seems to indeed fix this behaviour :-) Nonetheless, I'd like to hear about the results of your tests and those other ramifications :-)

**Comment by ioolkos** [comment]
@testark sorry to keep you waiting...you did the correct thing. Still have to test the clustered case.

**Comment by testark** [comment]
@ioolkos No problem at all. Thank you very much :-) I'll be waiting on your results then :-)

**Comment by dergraf** [comment]
@testark can you please verify that this fixes the issue in your deployment.

@ioolkos the fix might also improve routing performance as the one of the ets bag in vmq_reg_trie could be ditched in favor of an ets set.

**Comment by testark** [comment]
@dergraf will try to do it tomorrow. Thank you very much.

**Comment by testark** [comment]
@dergraf sorry I didn't have the time to test this the other day. Will try to do it today and report back.

**Comment by testark** [comment]
@dergraf working as expected as of `0.12.4`. Thank you veru much!
