### ISSUE TITLE
Subscriber message delivery performance

### ISSUE THREAD

**Issue by chriswue** [erlio/vernemq#771]
### Environment

- VerneMQ Version:  1.4.1 deployed from official docker-hub container
- OS: Ubuntu 18.04 with docker 18.06.0-ce
- Erlang/OTP version (if building from source): whatever the official docker container ships

Running on a bare metal box with an i7-4790 and 16GB of RAM (hyperthreading enabled). Disk is an Samsung 850 Evo 250GB

I've been doing some load testing on brokers and noticed a weird behavior when using vernemq: The publishing client always seems to outperform the subscription client. In particular subscriptions seems to top out at around 7,000msg/sec while a publisher can deliver in excess of 8,000/sec.

Publishers and subscribers and broker all run on the same box, communication is via TLS and all pub/sub is QoS level 1
I'm using the python paho-mqtt library for pub/sub which defaults to 20 max inflight messages same as VerneMQ.
max_offline_messages is set to 0 in VerneMQ

If I reduce the max inflight messages on the publish client to about 6 then the subscriber can just about keep up (not quite though in the long run). Disk-I/O during testing is moderate (iostat reports ~5% disk utilization)

When running emqtt instead the subscribers can easily keep up with the publisher using the same client script and environment (just swapping out the container).

Is there something in VerneMQ which throttles the subscriber delivery? How many inflight messages does VerneMQ keep around on the delivery side (when publishing towards subscribed clients)?

Some basic benchmarks:

VerneMQ (max_inflight_messages = 20, max_offline_messages = 0, max_online_messages = 1000 (default)) with clients set to have max inflight messages of 6

 Payload bytes | max inflight messages client | Number of clients pub | Number of clients sub | rate pub msg/sec (bytes/sec) | rate sub  msg/sec (bytes/sec)
-|-|-|-|-|-
128 | 6 | 1 | 1 | 6851 (856 KiB/sec) | 6804 (850 KiB/sec)
1024 | 6 | 1 | 1 | 6237 (6237 KiB/sec) | 5931 (5931 KiB/sec)
16384 | 6 | 1 | 1 | 5097 (79.6 MiB/sec) | 4880 (76.2 MiB/sec)
128 | 6 | 2 | 2 | 10733 (1341 KiB/sec) | 7539 (942 KiB/sec)
1024 | 6 | 2 | 2 | 9936 (9936 KiB/sec) | 6873 (6873 KiB/sec)
16384 | 6 | 2 | 2 | 7588 (118.6 MiB/sec) | 5126 (80.1 MiB/sec)
128 | 20 | 1 | 1 | 8097 (1012 KiB/sec) | 6834 (854 KiB/sec)
1024 | 20 | 1 | 1 | 7956 (7956 KiB/sec) | 6489 (6489 KiB/sec)
16384 | 20 | 1 | 1 | 6315 (98.7 MiB/sec) | 4904 (76.6 MiB/sec)
128 | 20 | 2 | 2 | 14025 (1753 KiB/sec) | 7120 (890 KiB/sec)
1024 | 20 | 2 | 2 | 13362 (13362 KiB/sec) | 6766 (6766 KiB/sec)
16384 | 20 | 2 | 2 | 10015(156.5 MiB/sec) | 4617 (72.1 MiB/sec)

Same tests with emqtt (max message queue size 1000, all other settings default)

 Payload bytes | max inflight messages client | Number of clients pub | Number of clients sub | rate pub msg/sec (bytes/sec) | rate sub  msg/sec (bytes/sec)
-|-|-|-|-|-
128 | 6 | 1 | 1 | 7632 (954 KiB/sec) | 7611 (951 KiB/sec)
1024 | 6 | 1 | 1 | 7856 (7856 KiB/sec) | 7865 (7865 KiB/sec)
16384 | 6 | 1 | 1 | 3894 (60.8 MiB/sec) | 3892 (60.8 MiB/sec)
128 | 6 | 2 | 2 | 10312 (1289 KiB/sec) | 10327 (1291 KiB/sec)
1024 | 6 | 2 | 2 | 9954 (9954 KiB/sec) | 9951 (9951 KiB/sec)
16384 | 6 | 2 | 2 | 6056 (94.6 MiB/sec) | 6046 (94.5 MiB/sec)
128 | 20 | 1 | 1 | 8290 (1036 KiB/sec) | 8286 (1036 KiB/sec)
1024 | 20 | 1 | 1 | 8075 (8075 KiB/sec) | 8076 (8076 KiB/sec)
16384 | 20 | 1 | 1 | 3797 (59.3 MiB/sec) | 3797 (59.3 MiB/sec)
128 | 20 | 2 | 2 | 11064 (1383 KiB/sec) | 11054 (1383 KiB/sec)
1024 | 20 | 2 | 2 | 10652 (10652 KiB/sec) | 10653 (10653 KiB/sec)
16384 | 20 | 2 | 2 | 6088 (95.1 MiB/sec) | 6083 (95.0 MiB/sec)

Given that pub/sub is well balanced when using emqtt seems to point towards an issue with the broker and not the client.

**Comment by ioolkos** [comment]
@chriswue thanks for the issue!
Can you share your paho mqtt test script with us?

**Comment by dergraf** [comment]
>When running emqtt instead the subscribers can easily keep up with the publisher using the same client script and environment (just swapping out the container).

In VerneMQ every QoS 1/2 message is written to disk (LevelDB) and deleted as soon as all subscribers have consumed the message. Last time I checked emqtt didn't persist the message on every publish, giving them a performance advantage when comparing side-by-side.

>Is there something in VerneMQ which throttles the subscriber delivery? How many inflight messages does VerneMQ keep around on the delivery side (when publishing towards subscribed clients)?

For QoS1 messages the `max_inflight_messages` parameter is only relevant for the delivery side. It's possible that this slows down the delivery, as it is mainly a feature to protect slow consuming clients. If you use `max_inflight_messages=0` VerneMQ should push messages out as fast as possible.

**Comment by chriswue** [comment]
@ioolkos It's unfortunately not self-contained (contains some tooling from internal libraries)

@dergraf Ah, I misunderstood - I assumed max_inflight_messages is on the incoming side. I will try changing that

**Comment by chriswue** [comment]
So after setting max_inflight_messages to 0 performance on the subscriber side improved a little bit - tops out at 8,000/sec on the subscriber side now. But the skew is still there, in particular with 2 publishers and 2 subscribers.

Now I just got access to another computer - same spec. ANd after moving the publish and subscriber client onto the box I can see that vernemq can keep up with a single publisher and a single subscriber but once I move to 2-2 the subscribers start lagging again.

Is there a way to bypass the leveldb?

**Comment by larshesel** [comment]
Hi

There isn't a configuration option (we'll likely add this at some point - also to make it possible to configure this on a per client basis) but you can disable the msg store plugin at runtime. First do `vmq-admin plugin show --internal`. This shows all registered hooks. You can then disable the ones concerning the message store (the ones named sth with vmq_lvldb_store) by issuing sth like `vmq-admin plugin disable  -m vmq_lvldb_store -f msg_store_write -a 2` for each of them.

**Comment by ioolkos** [comment]
```
sudo vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_write -a 2
sudo vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_find -a 1
sudo vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_read -a 2
sudo vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_delete -a 2
```
to make this explicit. This will disable LevelDB message persistence completely and store QoS > 0 messages only in RAM.

**Comment by chriswue** [comment]
Alright, that made it fly. I can now push 25,000msg/sec through the broker with 3 pub and 3 sub without dropping any. The system load stays under 4 (with 8 logical cores). emqtt is running a system load of 7 in this scenario and I can push about 21,000msg/sec.

**Comment by chriswue** [comment]
Hm, I managed it with a wrapper running a loop in the background until vernemq seems to be up and running. In case someone else needs it:

Wrapper script:

    #!/bin/sh

    disable_leveldb() {
        while [ : ]; do
            vmq-admin metrics show > /dev/null
            if [ $? -eq 0 ]; then
                echo "found running vernemq, disabling leveldb ..."
                vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_write -a 2
                vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_find -a 1
                vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_read -a 2
                vmq-admin plugin disable -m vmq_lvldb_store -f msg_store_delete -a 2
                echo "... leveldb disabled"
                exit 0
            fi
            echo "vernemq not yet running, waiting a few secs ..."
            sleep 3
        done
    }

    disable_leveldb &

    start_vernemq

Minimal `Dockerfile` to use it:

    FROM erlio/docker-vernemq:1.4.1
    COPY vernemq_wrapper.sh /usr/sbin/vernemq_wrapper.sh
    CMD ["sh", "/usr/sbin/vernemq_wrapper.sh"]
