### ISSUE TITLE
Crash due to vmq_ql_query

### ISSUE THREAD

**Issue by davionxiang** [erlio/vernemq#772]
### Environment

- VerneMQ Version: 1.0.1
- OS: CentOS 7.5
- Erlang/OTP version (if building from source): 19

I've set a vernemq cluster with 8 nodes, and these nodes crashed frequently

### Expected behavior

vernemq instance should not crash

### Actual behaviour

2018-07-24 19:37:33 =ERROR REPORT====
** Generic server <0.1448.0> terminating
** Last message in was timeout
** When Server state == {state,<12342.5868.0>,"SELECT client_id, user FROM sessions WHERE is_online=true",undefined,undefined}
** Reason for termination ==
** {{error,{badmatch,{error,normal}}},[{vmq_ql_query,select,5,[{file,"/home/ms/vernemq/_build/default/lib/vmq_ql/src/vmq_ql_query.erl"},{line,187}]},{vmq_ql_query,handle_info,2,[{file,"/home/ms/vernemq/_build/default/lib/vmq_ql/src/vmq_ql_query.erl"},{line,83}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-07-24 19:37:33 =CRASH REPORT====
  crasher:
    initial call: vmq_ql_query:init/1
    pid: <0.1448.0>
    registered_name: []
    exception exit: {{error,{badmatch,{error,normal}}},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [vmq_ql_query_sup,vmq_ql_sup,<0.85.0>]
    messages: []
    links: [<0.87.0>]
    dictionary: [{{parse_memo_table,vmq_ql_parser},17301640}]
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 7121
  neighbours:
2018-07-24 19:37:33 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_ql_query_sup}
     Context:    child_terminated
     Reason:     {error,{badmatch,{error,normal}}}
     Offender:   [{pid,<0.1443.0>},{id,vmq_ql_query},{mfargs,{vmq_ql_query,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

2018-07-24 19:37:33 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_ql_query_sup}
     Context:    child_terminated
     Reason:     {error,{badmatch,{error,normal}}}
     Offender:   [{pid,<0.1444.0>},{id,vmq_ql_query},{mfargs,{vmq_ql_query,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

2018-07-24 19:37:33 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_ql_query_sup}
     Context:    child_terminated
     Reason:     {error,{badmatch,{error,normal}}}
     Offender:   [{pid,<0.1449.0>},{id,vmq_ql_query},{mfargs,{vmq_ql_query,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

2018-07-24 19:37:33 =SUPERVISOR REPORT====
     Supervisor: {local,vmq_ql_query_sup}
     Context:    child_terminated
     Reason:     {error,{badmatch,{error,normal}}}
     Offender:   [{pid,<0.1448.0>},{id,vmq_ql_query},{mfargs,{vmq_ql_query,start_link,undefined}},{restart_type,temporary},{shutdown,1000},{child_type,worker}]

**Comment by larshesel** [comment]
Hi,

A lot of fixes was done since VerneMQ 1.0.1 for the vmq_ql application. Can you upgrade to a newer version?

**Comment by davionxiang** [comment]
thanks, will try upgrade
