### ISSUE TITLE
Find VerneMQ nodes without hardcoded IP

### ISSUE THREAD

**Issue by cmnstmntmn** [erlio/vernemq#778]
## Context

- network with 1k devices
- VerneMQ node in the same network

## Problem

It's impossible to handle the credentials on two fronts; device config, vernemq ACL

## Question

I was thinking to the following scenario:

0. devices will find VerneMQ node using mDNS or simmilar 
1. devices wil subscribe to a generic topic `unauthorised` by default
2. an interface will list all sessions/clients subscribed to topic `unauthorized`
3. the administrator will authorise each device by creating a database ACL entry

<img width="808" alt="devices" src="https://user-images.githubusercontent.com/2312755/43317001-e15abaee-91a3-11e8-801f-dbd48295f95e.png">

All good so far, but i don't find a way to make VerneMQ take the following decision (pseudo code)

```
if device is registered
  pub/sub it to it's ACL
else
  pub/sub to default topic
```

I'm curious if you faced this issue and how you've solved id.

thank you

**Comment by dergraf** [comment]
hello @cmnstmntmn 
sounds like an interesting idea.. At first sight this looks like something that could be done in a plugin.
Something which is currently missing is that an administrator could subscribe a topic in the name of a client. Therefore after authorizing a client (entering the proper ACL to some store) the client must be notified to establish the subscription.

**Comment by cmnstmntmn** [comment]
@dergraf what if the administrator is sending the credentials to the client via `/credentials/%u`, so it can store them locally?

Would that be problematic regarding security?

**Comment by dergraf** [comment]
@cmnstmntmn thank you for your patience and please excuse my delay.

First, I am not a security expert... but the model you mentioned is likely problematic. As it requires that a user is able to establish a connection and subscribe to `/credentials/%u` without being properly authenticated/authorized.

It's a 'basic' client bootstrap problem, which is often solved by using a different channel like HTTP where the human user of the device has to manually authenticated or some credentials that have been previously deployed with the device (client cert, OTP token, ...).

I'd like to close this issue for now, as the actual solution for the client bootstrap problem is out of scope for VerneMQ. Maybe reach out to the community over Slack to figure out how other people solve this challenge.

**Comment by cmnstmntmn** [comment]
thank you @dergraf ;)

**Comment by dergraf** [comment]
@cmnstmntmn could you ping me on the Slack channel, it would be great if we can get in touch over there.
