### ISSUE TITLE
monitoring via graphite

### ISSUE THREAD

**Issue by elhamkazemi** [erlio/vernemq#779]
Hi,
I am trying to monitor vernemq, and I made the following settings:
graphite_enabled = on
graphite_host = carbon.hostedgraphite.com
graphite_port = 2003
graphite_interval = 20000
graphite_api_key = YOUR-GRAPHITE-API-KEY

is the graphite_api_key the output of  `vmq-admin api-key create` command?
but nothing shows at localhost:2003. how can i fix it?

**Comment by ioolkos** [comment]
Hi @elhamkazemi thanks for asking.

The graphite_api_key in not the vmq api key. The configs you find in vernemq.conf are just an example. 
If you want to see graphite results on your localhost you have to run a graphite service on your localhost and then configure vernemq.conf accordingly.
