### ISSUE TITLE
Achieve listener replication in a verneMQ cluster

### ISSUE THREAD

**Issue by mpalestini** [erlio/vernemq#784]
### Environment

- VerneMQ Version: 1.4.0
- OS: Ubuntu 16.04 LTS

Hi there,

I've succesfully created a VerneMQ cluster with three different phsycal nodes.
The three nodes are all Running:true if i launch the ```vmq-admin cluster show``` command.

However, when I start a listener on one node, this is not shared between the others. How can I achieve listener replication within the cluster? Is it possible?

**Comment by mpalestini** [comment]
Ok thanks for the info. 

Let's say i create three topics on each node with same port and topic. 

So for instance:
```
Node #1: <node1_ip>:1884, mountpoint: machine/topic/test
Node #2 <node2_ip>:1884, mountpoint: machine/topic/test
Node #3 <node3_ip>:1884, mountpoint: machine/topic/test
```
Then let's assume I start sending sensor metrics to ```Node #1```. After few minutes, the node crashes. Will the others rise up to avoid the interruption of data transmission? 
Do I need something coordinating the nodes (like ZooKeeper in a Kafka distributed environment).

Thanks again! Have a nice day.

**Comment by ioolkos** [comment]
You'll want a single endpoint your clients are going to connect to. This component is a proxy or load balancer (like HAProxy) in front of the VerneMQ cluster. If a cluster node goes down, all the TCP connections to clients will be cut. They are going to re-connect, and they will be routed to an online node by the loadbalancer.

**Comment by mpalestini** [comment]
Oh okay. Many thanks for pointing that out.

Cheers,

Michele
