### ISSUE TITLE
vernemq-hook: auth_on_publish  don't need  payload.

### ISSUE THREAD

**Issue by boboxiaodd** [erlio/vernemq#787]
### Environment

- VerneMQ Version: 1.4.1
- OS: Centos7
- Erlang/OTP version (if building from source):

I use one user to publish msg , so payload is needn't
Add a config option  like: 
```ini
vmq_webhooks.mywebhook1.take_payload = off
```

**Comment by codeadict** [comment]
I'll start this one. will call it `mq_webhooks.mywebhook1.send_payload = off`

**Comment by boboxiaodd** [comment]
@codeadict thank you!

**Comment by larshesel** [comment]
Hey codeadict, awesome you wanna take a stab at it! There are, IIRC, three hooks which include payloads: `auth_on_publish`, `on_publish` and `on_deliver` should it be possible to omit the payload on all of these or only in `auth_on_publish`?

Other possible config names could be: `include_payload` or `omit_payload`. Not sure which one of the suggested ones read better when defining a webhook :)

**Comment by codeadict** [comment]
Hey, it can be included for all the hooks, omit_payload sounds perfect.
Thanks!
