### ISSUE TITLE
"UNSUBSCRIBE" on wildcard topic unsubscribes all clients

### ISSUE THREAD

**Issue by Deric1111** [erlio/vernemq#79]
Hi, after upgrading vernemq to version 0.12.4, I noticed there is something weird as in the situation below:

Client A subscribes to "my/topic/here"
Client B constantly publishes data to topic "my/topic/here/"
Client C subscribe to "my/topic/# "

Client A, B and C has their own unique id respectively. When client C unsubscribes from my/topic/#, Client A stops receiving data.

Client A and C should not be sharing the same session. 

When client C resubscribes back to "my/topic/#", client A starts to receives data again. 

This situation quite similar with issue #77 .

**Comment by dergraf** [comment]
Thanks for reporting this error. Can you ensure that you're running 0.12.4 (e.g. via ```sudo vernemq version```) as exactly this issue was fixed in this version. I wasn't able to reproduce this on our test setup.

**Comment by dergraf** [comment]
@Deric1111 any news on this?

**Comment by Deric1111** [comment]
Hi Sorry for the late reply. I could not replicate the error after I restarted it. I think I will close the issue. Its been running great for a month and thanks for the effort .. :)
