### ISSUE TITLE
Vernemq start and stop fails with systemd unit

### ISSUE THREAD

**Issue by endorama** [erlio/vernemq#793]
Hello, while testing a vernemq instance I found something that I think is a bug ( or at least an unexpected behaviour ) in vernemq integration with systemd.

### Environment

- VerneMQ Version: 1.4.1
- OS: ubuntu 18.04 bionic
- Erlang/OTP version (if building from source): using deb package

### Expected behavior

Using vernemq systemd unit:
```
$ cat /lib/systemd/system/vernemq.service 
[Unit]
Description=VerneMQ is a MQTT message broker

[Service]
ExecStart=/usr/sbin/vernemq start
ExecStop=/usr/sbin/vernemq stop
User=vernemq
Type=forking
PIDFile=/var/run/vernemq/vernemq.pid
EnvironmentFile=-/etc/default/vernemq
RuntimeDirectory=vernemq

[Install]
WantedBy=multi-user.target
```

I was expecting this unit to:
1. start vernemq succefully
1. noop if vernemq is already running
1. stop vernemq succefully
1. noop if vernemq is already stopped

### Actual behaviour

1. works as expected
1. do not work. `vernemq start` exit `1` when is already running, systemd reports this as a failure
1. works as expected
1. do not work. `vernemq stop` exit `1` when is already stopped, systemd reports this as a failure

Points 2 and 4 create some difficulties in operating `vernemq` with `systemd`, as the unit is reported in failing state even if that's not the case.  
In my particular case I'm using an ansible playbook to ensure `vernemq` is running and the step fails because of the `exit 1` if `vernemq` is already running.

I would expect that `vernemq start` and `vernemq stop` do not consider a node in the desired state as an error.

**Comment by larshesel** [comment]
Hi,

I tried to reproduce this problem with your unit file, but systemd
doesn't seem to have any issue with this. For instance calling `sudo
systemctl start vernemq` twice doesn't fail here (on Debian testing).

Could it be that the Ansible script isn't actually using systemd to
control the service? Ansible has a `service_module` which can be used
to control and manage services statefully and idempotently which might
help: https://docs.ansible.com/ansible/latest/modules/service_module.html

**Comment by larshesel** [comment]
Hi, closing this for now - if you have more information feel free to comment / reopen.

**Comment by endorama** [comment]
Hello Lars, sorry for the late reply.

I tested this on 1.5.0 on ubuntu 18.04.1 and is working as expected, so either has been a glitch due to other problem or the problem is not there anymore.

Thank you for looking into this anyway.
