### ISSUE TITLE
disk_almost_full alarm handler is set for snap loop devices

### ISSUE THREAD

**Issue by endorama** [erlio/vernemq#794]
### Environment

- VerneMQ Version: 1.4.1
- OS: ubuntu 18.04 bionic
- Erlang/OTP version (if building from source): using deb package

Hello, looking in `vernemq` logs folder I found the `erlang.log` files.
On my servers in those files there are reported these lines multiple times:
```
    alarm_handler: {set,{{disk_almost_full,"/snap/amazon-ssm-agent/295"},[]}}
    alarm_handler: {set,{{disk_almost_full,"/snap/core/4917"},[]}}
    alarm_handler: {set,{{disk_almost_full,"/snap/core/5145"},[]}}
```

Running a `df -h` shows:
```
$ df -h
udev            2.0G     0  2.0G   0% /dev
tmpfs           395M  796K  394M   1% /run
/dev/xvda1      7.7G  2.4G  5.4G  31% /
tmpfs           2.0G  4.0K  2.0G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/loop0       13M   13M     0 100% /snap/amazon-ssm-agent/295
/dev/loop1       87M   87M     0 100% /snap/core/4917
tmpfs           395M     0  395M   0% /run/user/1000
/dev/loop2       87M   87M     0 100% /snap/core/5145
```

`/snap/*` devices are all 100% usage, but AFAICT this is expected for snap packages, as the snap fs will always be exactly the needed dimension ( see [here](https://unix.stackexchange.com/questions/406534/snap-dev-loop-at-100-utilization-no-free-space) for an explanation ).

I suspect the mentioned message are not affecting node operations in any way.

Would be possible to avoid reporting an alert for snap loop devices? As they will always be false positives, they could be a bit confusing if you are not used to how snaps work.

Thank you!

**Comment by ioolkos** [comment]
@endorama thanks for opening this issue, good hint. I think the OS_Monitor checks for all mounted disks on Linux automatically. The alarms will not interfere with normal operation. If you have setup alarms to trigger further events, yeah, this will create false positives. 

I'll try to find out whether this is somehow configurable in a better way.

**Comment by ioolkos** [comment]
Got some help from @codeadict and @dergraf: Thanks!

Apparently there is no way to select which mounted disk to monitor with the Erlang OS_Mon (disk sup). Out of luck then.

Might be the reason the RabbitMQ folks implemented a custom disk monitor: 
https://github.com/rabbitmq/rabbitmq-server/blob/6b13679b725ec12aee2569f07ac15618eb99a34b/src/rabbit_disk_monitor.erl

**Comment by dergraf** [comment]
Closing this issue and mark it for 2.0.
