### ISSUE TITLE
Must not accept password w/o username

### ISSUE THREAD

**Issue by ckrey** [erlio/vernemq#8]
Compatibility testing `vernemq` on OS X with https://github.com/ckrey/MQTT-Client-Framework

> [MQTT-3.1.2-22]
> If the User Name Flag is set to 0, the Password Flag MUST be set to 0

**Comment by ckrey** [comment]
confirmed: still in 0.9.4

**Comment by larshesel** [comment]
@dergraf did we do anything to fix this issue? If not, I'll put it on the backlog, seems like a rather easy one to fix.

**Comment by codeadict** [comment]
I can help with this one, is it still an issue? I created a plugin that handles that, so probably just need a small copy paste Pull Request.

**Comment by dergraf** [comment]
Thanks for your offer. And your fix is very much appreciated. I'd start im
erlio/vmq_commons src/vmq_parser.erl for fixing this bug as it is related
to the MQTT parser.

Am 15.09.2016 5:22 vorm. schrieb "Dairon Medina C." <
notifications@github.com>:
