### ISSUE TITLE
Getting vernemq to compile and run on Erlang 18

### ISSUE THREAD

**Issue by marianoguerra** [erlio/vernemq#80]
hi, first of all I know that erlang 18 is not supported, but I was trying to make it run on it and here is what I found.

context: building from source, master on ubuntu 15.10.

changes I did for it to build:

	diff --git a/rebar.config b/rebar.config
	index fa661ec..e8937c5 100644
	--- a/rebar.config
	+++ b/rebar.config
	@@ -6,6 +6,7 @@
		   ]}.
	 
	 {deps, [
	+        {edown, {git, "git://github.com/uwiger/edown.git", {tag, "0.7"}}},
		 {lager, {git, "git://github.com/basho/lager.git", {tag, "3.0.1"}}},
		 {cuttlefish, {git, "git://github.com/tsloughter/cuttlefish.git", {branch, "develop"}}},
		 {node_package, {git,"git://github.com/dergraf/node_package.git", {branch, "rebar3-support"}}},
	@@ -27,6 +28,9 @@
	 
	 {overrides, [{override, setup, [{post_hooks, []}]},
		      {override, vmq_passwd, [{post_hooks, [{compile, "make -C c_src"}]}]},
	+             {override, plumtree, [{erl_opts, [debug_info, {parse_transform, lager_transform}]}]},
	+             {override, vmq_server, [{erl_opts, [{platform_define, "^[0-9]+", namespaced_types}, {parse_transform, lager_transform}, debug_info]}]},
	+             {override, eper, [{erl_opts, [debug_info]}]},
		      {override, syslog, 
		       [{so_name, "syslog_drv"},
		        {port_sources, ["c_src/*.c"]},
	@@ -56,6 +60,7 @@
	     {vmq_snmp, load},
	     {recon, load},
	     {eper, load},
	+    {setup, load},
	     {syslog, load},
	     {lager_syslog, load},
	     {runtime_tools, load},

* the edown dependency at the top is to have a newer version that doesn't produce an error on v18, another version can be chosen but it's harmless since it's a dep for documentation from a dep afaik.
* then some overrides to turn off warnings as errors, all related to the deprecation of now/0
  + two of which can be fixed since are yours (vmq_server, plumtree) using https://github.com/lasp-lang/time_compat/
  + the remaining one (eper) is for debugging and profiling so the override should be harmless
* then added setup to relx config otherwise I get {undef, [{setup, find_env_vars, [...]}]}

steps to build with this changes:

* clone master
* apply changes on rebar.config
* make rel (will fail)
* ./rebar3 upgrade edown
* make rel
* ./_build/default/rel/vernemq/bin/vernemq console

and it works :)

**Comment by marianoguerra** [comment]
don't know if related, but it doesn't seem to start the listener (trying to send a message with mosquitto_put, telnet to the port or using nmap doesn't show the port to be open).

I tried to run some vmq-admin commands but I get this error:

    $ ./vmq-admin cluster status
    Invalid command 'vmq-adminclusterstatus'

or

    $ ./vmq-admin plugin show
    Invalid command 'vmq-adminpluginshow'

I'm using zsh, tried using bash or changing the hashbang to bash but it doesn't seem to fix anything.

**Comment by larshesel** [comment]
Hi there - thanks for checking VerneMQ out!

This is a strange error. Could you try to build VerneMQ with erlang 17.x without your changes and see if you can reproduce this problem? Then we can see if it's related to your changes.

**Comment by marianoguerra** [comment]
@larshesel made it work :)

this is the correct set of changes to rebar.config to make it work

	diff --git a/rebar.config b/rebar.config
	index fa661ec..3ed98e2 100644
	--- a/rebar.config
	+++ b/rebar.config
	@@ -6,6 +6,7 @@
		   ]}.
	 
	 {deps, [
	+        {edown, {git, "git://github.com/uwiger/edown.git", {tag, "0.7"}}},
		 {lager, {git, "git://github.com/basho/lager.git", {tag, "3.0.1"}}},
		 {cuttlefish, {git, "git://github.com/tsloughter/cuttlefish.git", {branch, "develop"}}},
		 {node_package, {git,"git://github.com/dergraf/node_package.git", {branch, "rebar3-support"}}},
	@@ -27,6 +28,9 @@
	 
	 {overrides, [{override, setup, [{post_hooks, []}]},
		      {override, vmq_passwd, [{post_hooks, [{compile, "make -C c_src"}]}]},
	+             {override, plumtree, [{erl_opts, [debug_info, {parse_transform, lager_transform}]}]},
	+             {override, vmq_server, [{erl_opts, [{platform_define, "^[0-9]+", namespaced_types}, {parse_transform, lager_transform}, debug_info]}]},
	+             {override, eper, [{erl_opts, [debug_info]}]},
		      {override, syslog, 
		       [{so_name, "syslog_drv"},
		        {port_sources, ["c_src/*.c"]},
	@@ -47,6 +51,7 @@
	    [
	     sasl,
	     vmq_server,
	+    setup,
	     {cuttlefish, load},
	     {vmq_passwd, load},
	     {vmq_acl, load},

notice the last change (setup) is not {setup, load} but setup.

now it works :)

would you accept this as a PR? do you prefer to apply it yourself?

**Comment by larshesel** [comment]
Very cool. Yes, please make a PR, then we'll check it out!

Getting ready for Erlang 18 is on our road map so this may help push that forward - thank you!

**Comment by larshesel** [comment]
fixed via #100
