### ISSUE TITLE
Feature request: ACL and Auth via webhooks

### ISSUE THREAD

**Issue by arrowcircle** [erlio/vernemq#806]
Hi! Thanks for the great project.
I have read about webhooks and auth, its really good solution to have ability to use third party auth without directly accessing database. It will be also great to allow third party solution for ACLs

Is it possible to add ACL with webhook response for each auth request?

**Comment by arrowcircle** [comment]
@dergraf Yes, something like that. When client tries to connect, authdata is passed to third party service, that returns result of auth and acl for the connection.

**Comment by dergraf** [comment]
Sounds like a great idea, we were actually discussing something similar earlier this week.
We'll keep you posted.

**Comment by codeadict** [comment]
I actually created a similar plugin that does this. The trick is the data we want to send, it cloud actually be something like:

```json
{
    "user": "somebody",
    "client_id": "kdskkhdskhso",
    "topic": "foo/bar/baz"
}
```

Probably also have an option to send the `password` as some people use tokens as the password. Thoughts?

**Comment by arrowcircle** [comment]
Actually I thought this thing is already working and made a auth endpoint in my app.

It responds something like:

```
{
    "publish_acl": [],
    "result": "ok",
    "subscribe_acl": [
        {
            "pattern": "data/sensors"
        }
    ]
}
```

**Comment by codeadict** [comment]
Yeah will be nice to  define if we want this on every `auth_on_publish`/`auth_on_subscribe` or just to happen on `auth_on_register` and make one request that gets all the topics ACL for a user, its tricky to design this plugin as many people will have different requirements and will be good to design something that is flexible enough.

**Comment by dergraf** [comment]
I was thinking about the possibility to reuse some of the logic of our DB Auth plugins... I haven't tested the following Lua auth plugin, but it might be all that is required.

https://gist.github.com/dergraf/e1149165832804c84ff875218f28852f

**Comment by arrowcircle** [comment]
@dergraf could you please make some comments about how to use it? As I seen in the code, it requires Redis, for cache?
As I think, auth and ACL with external calls are the most common features for almost every deployment. Using DB is ok, but use of http endpoint is much more convenient and requires much less deps for both auth app and vernemq.

**Comment by dergraf** [comment]
@arrowcircle You were right,   I forgot to remove those, when copying the Redis script. ;)
Please have a look at the updated gist. https://gist.github.com/dergraf/e1149165832804c84ff875218f28852f

**Comment by ertanden** [comment]
I guess the request here is to have this directly integrated with Webooks plugin, instead of using a custom Lua script.

**Comment by arrowcircle** [comment]
@dergraf Any ideas?

**Comment by dergraf** [comment]
Hmm.. if you don't see any errors in error.log the script should behave correctly... in that case it might be that the Json has a wrong format.

**Comment by arrowcircle** [comment]
@dergraf Json format is:
```json
{
    "publish_acl": [],
    "result": "ok",
    "subscribe_acl": [
        {
            "pattern": "data/sensors"
        }
    ]
}
```

and there are no errors in the console of vernemq.

Here is also output of plugin list

```bash
# vmq-admin plugin show
+-------------+-----------+-----------------+-----------------------------+
|   Plugin    |   Type    |     Hook(s)     |            M:F/A            |
+-------------+-----------+-----------------+-----------------------------+
|vmq_plumtree |application|                 |                             |
|   vmq_acl   |application| auth_on_publish |  vmq_acl:auth_on_publish/6  |
|             |           |auth_on_subscribe| vmq_acl:auth_on_subscribe/3 |
|vmq_diversity|application|                 |                             |
| vmq_passwd  |application|auth_on_register |vmq_passwd:auth_on_register/5|
+-------------+-----------+-----------------+-----------------------------+
```

Do I need to disable or enable some plugins?
Or what is wrong with json format?

**Comment by dergraf** [comment]
Could you disable vmq_passwd and vmq_acl and see how it goes?

**Comment by arrowcircle** [comment]
@dergraf Now I can connect, but can't publish or subscribe to any topic.

Here is the vernemq log message (first for subscribe, two last for publish)

```log
06:33:06.500 [warning] can't authenticate client {[],<<"MQTT_FX_Client">>} due to error
...
06:33:45.952 [error] can't auth publish [<<"1">>,{[],<<"MQTT_FX_Client">>},0,[<<"data">>,<<"sensors">>],<<"123">>,false] due to no_matching_hook_found
06:33:45.952 [warning] session stopped abnormally due to 'publish_not_authorized_3_1_1'
```

Docker command
```docker
docker run -p 1883:1883 \
  --rm --name vernemq \
  -e "DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off" \
  -e "DOCKER_VERNEMQ_PLUGINS__VMQ_PASSWD=off" \
  -e "DOCKER_VERNEMQ_PLUGINS__VMQ_ACL=off" \
  -e "DOCKER_VERNEMQ_PLUGINS__VMQ_DIVERSITY=on" \
  -e "DOCKER_VERNEMQ_VMQ_DIVERSITY__HTTP_AUTH__file=/auth_http.lua" \
  -v $(pwd)/auth_http.lua:/auth_http.lua \
  erlio/docker-vernemq
```
auth_http.lua:
```lua
require "auth/auth_commons"

URL = "http://docker.for.mac.localhost:3000/api/v1/vernemqs"

function auth_on_register(reg)
    if reg.username ~= nil and reg.password ~= nil then
        key = json.encode({
            mountpoint = reg.mountpoint,
            client_id = reg.client_id, 
            username = reg.username,
            password = reg.password
        })
        headers = {}
        headers["x_post_header"] = "X-POST-HEADER"
        headers['Accept'] = "application/json"
        headers["Content-Type"] = "application/json"
        ret = http.post(pool, URL, key, headers)
        if ret.status == 200 and ret.ref then
            body = http.body(ret.ref)
            json = json.decode(body)
            cache_insert(
                reg.mountpoint, 
                reg.client_id, 
                reg.username,
                json.publish_acl,
                json.subscribe_acl
                )
            return true
        else
            return false
        end
    end
    return false
end

pool = "auth_http"
config = {
    pool_id = pool
}

http.ensure_pool(config)
hooks = {
    auth_on_register = auth_on_register
}
```

JSON responses are the same as above.
Any ideas?

**Comment by arrowcircle** [comment]
@dergraf Is there any way to look at the acl list in the runtime?

**Comment by arrowcircle** [comment]
@dergraf ?

**Comment by ioolkos** [comment]
He's on a short vacation... apologies & thanks for you effort & patience @arrowcircle.
If I follow this correctly, you can register, but not publish? Just to make sure, the auth_on_publish hook is implemented though in your Lua script?
/cc @larshesel

**Comment by ioolkos** [comment]
Ah, ok, I see that the point was discussing about leaving out the auth_on_publish and auth_on_subscribe hooks, kind of. And the auth_http.lua script was from @dergraf. 
Hm then.

**Comment by arrowcircle** [comment]
@dergraf Hey, any thought about that?

**Comment by dergraf** [comment]
@arrowcircle, can you get in touch over Slack?

**Comment by arrowcircle** [comment]
@dergraf Sure. what address for registration?

**Comment by arrowcircle** [comment]
Great Thanks to @dergraf 
Problem was in the hooks section of lua. Here is the full working example:

```lua
require "auth/auth_commons"

-- In order to use this Lua plugin your webhook must return a JSON Object containing 
-- the following properties:
--
--  - passhash: STRING (bcrypt)
--  - publish_acl: [ACL]  (Array of ACL JSON Objects)
--  - subscribe_acl: [ACL]  (Array of ACL JSON Objects)
--
-- 	The JSON array passed as publish/subscribe ACL contains the ACL objects topic
-- 	for this particular user. MQTT wildcards as well as the variable 
-- 	substitution for %m (mountpoint), %c (client_id), %u (username) are allowed
-- 	inside a pattern. 
-- 
-- IF YOU USE THE KEY/VALUE SCHEMA PROVIDED ABOVE NOTHING HAS TO BE CHANGED 
-- IN THE FOLLOWING SCRIPT.

URL = "http://docker.for.mac.localhost:3000/api/v1/vernemqs"

function auth_on_register(reg)
    if reg.username ~= nil and reg.password ~= nil then
        key = json.encode({
            mountpoint = reg.mountpoint,
            client_id = reg.client_id, 
            username = reg.username,
            password = reg.password
        })
        headers = {}
        headers["x_post_header"] = "X-POST-HEADER"
        headers['Accept'] = "application/json"
        headers["Content-Type"] = "application/json"
        ret = http.post(pool, URL, key, headers)
        if ret.status == 200 and ret.ref then
            body = http.body(ret.ref)
            json = json.decode(body)
            cache_insert(
                reg.mountpoint, 
                reg.client_id, 
                reg.username,
                json.publish_acl,
                json.subscribe_acl
                )
            return true
        else
            return false
        end
    end
    return false
end

pool = "auth_http"
config = {
    pool_id = pool
}

http.ensure_pool(config)

hooks = {
    auth_on_register = auth_on_register,
    auth_on_publish = auth_on_publish,
    auth_on_subscribe = auth_on_subscribe,
    on_unsubscribe = on_unsubscribe,
    on_client_gone = on_client_gone,
    on_client_offline = on_client_offline,

    auth_on_register_m5 = auth_on_register_m5,
    auth_on_publish_m5 = auth_on_publish_m5,
    auth_on_subscribe_m5 = auth_on_subscribe_m5,
}
```

**Comment by micw** [comment]
Hello,
I wonder why that's closed because the script is just a workaround. If the normal webhooks would support this, it would be much easier to use and include features like caching, configuring the URLs and such.

One remark to the script above: The comment is wrong regarding passhash, because the passwort must be checked on server-side and is not processed in any way within the script.

Kind regards,
Michael.
