### ISSUE TITLE
Clients can't register client due to "action_timeout"

### ISSUE THREAD

**Issue by eladnava** [erlio/vernemq#809]
### Environment

- VerneMQ Version: 1.4.0
- OS: Ubuntu 16.04 LTS
- Erlang/OTP version (if building from source): 19

### Actual behaviour

Upon connecting clients to a single VerneMQ node (no cluster) running on AWS, eventually the server hangs up and won't accept new connections (at around 40k connections):

```
2018-08-26 04:49:59.669 [warning] <0.4406.66>@vmq_mqtt_fsm:check_user:546 can't register client {[],<<"abcd">>} with username <<"abcd">> due to action_timeout
```

This seems to occur when the concurrency of connections increases. When I stresstest the server with 5 connections being established at a time, the server can reach 250k simultaneous connections.

Looking at the source, it appears `vmq_reg_sync:sync(SubscriberId` is returning `action_timeout`. Timeout of what?

**Comment by ioolkos** [comment]
Hi @eladnava, thanks for opening the issue.
How many client connections are you setting up per second, in the failing case?

**Comment by dergraf** [comment]
@eladnava my guess is that VerneMQ was too busy setting up the connections, resulting in timeouts. What was the rate you're setting up the clients, how much RAM, CPU?

**Comment by eladnava** [comment]
@ioolkos It must have been something like 50 connections a second on a `r5.large` EC2 instance (16GB RAM, 2 vCPU).

 What if we can't control the rate of clients connecting?

**Comment by dergraf** [comment]
Can you test the identical test case with a better machine like a m5.4xlarge.. Alternatively/Additionally run the same tests on the r5.large and observe the CPU and Memory profile throughout the test. If you hit 100% you may need a better machine.

Connection setup rate could be usually controlled on the load balancer.

**Comment by eladnava** [comment]
Can no longer test this as I have decided to go for another solution. Will close this as I cannot be of further help.

**Comment by rahulwinzo** [comment]
@eladnava I'm also facing the same issue. Can you please tell what solution did you finally switch to?

**Comment by larshesel** [comment]
@rahulwinzo a lot has happened since VerneMQ 1.4.0 - so the issue you may be facing isn't necessarily the same - have you been testing with 1.9.0? If not please try it out and/or ask for help in the VerneMQ community slack channel https://slack-invite.vernemq.com/

**Comment by nguyenduybinh** [comment]
i have the same issue with vernemq 1.11.0 latest, have any solution for this issue?

**Comment by nguyenduybinh** [comment]
@ioolkos @dergraf
