### ISSUE TITLE
auth_on_subscribe and auth_on_publish Lua hooks not called

### ISSUE THREAD

**Issue by okofish** [erlio/vernemq#810]
### Environment

- VerneMQ Version: 1.5.0
- OS: Debian (Docker image erlio/docker-vernemq:1.5.0)
- Erlang/OTP version (if building from source): N/A

vernemq.conf:
```
[...]
plugins.vmq_diversity = on
vmq_diversity.CF_auth.file = /etc/vernemq/plugins/CF_auth.lua
vmq_diversity.CF_proxy.file = /etc/vernemq/plugins/CF_proxy.lua
[...]
```

CF_proxy.lua: (simplified)
```Lua
-- omitted: a couple of functions and variables that shouldn't affect anything

-- these don't get called :(
function my_auth_on_subscribe(sub)
  log.info('my_auth_on_subscribe: ' .. json.encode(sub))
  -- some auth logic, but essentially:
  return true
end
function my_auth_on_publish(pub)
  log.info('my_auth_on_publish: ' .. json.encode(pub))
  -- some auth logic, but essentially:
  return true
end

-- but these do...
function my_on_subscribe(sub)
  log.info('my_on_subscribe: ' .. json.encode(sub))
end
function my_on_publish(pub)
  log.info('my_on_subscribe: ' .. json.encode(pub))
end

hooks = {
  auth_on_subscribe = my_auth_on_subscribe,
  auth_on_publish = my_auth_on_publish,
  on_subscribe = my_on_subscribe,
  on_publish = my_on_publish
}
```

CF_auth.lua defines only an `auth_on_register` hook that (essentially) returns true. It gets called and runs fine.

### Expected behavior

I expect to see in my logs something like:
```
[info] my_auth_on_subscribe: {[sub table]}
[info] my_on_subscribe: {[sub table]}
[info] my_auth_on_publish: {[publish table]}
[info] my_on_publish: {[publish table]}
```

### Actual behaviour

I only see:
```
[info] my_on_subscribe: {[sub table]}
[info] my_on_publish: {[publish table]}
```

I know CF_proxy.lua is loaded and functioning because (among other things) the on_subscribe and on_publish hooks are called perfectly. It's just the two auth hooks that don't get called at all.
I haven't tried this on bare metal, but I can't imagine why the results would be different from those with Docker.
Any suggestions would be greatly appreciated. Thanks!

**Comment by dergraf** [comment]
Is it possible that the default `vmq_acl` plugin is still enabled?

**Comment by okofish** [comment]
That was it, thank you! I didn't realize `vmq_acl` was on by default - I guess I should have checked `vmq-admin plugin show` to see what else was on those hooks.

**Comment by kag0** [comment]
Just ran into this same issue with webhooks which got me thinking.
Should the default ACL be so permissive and should the ACL be enabled by default at all? I would think the ideal behavior would be to have no access allowed by default. That way if there is some misconfiguration (acl doesn't get turned off in the config) the system will fail-closed instead of open.

**Comment by larshesel** [comment]
Hi @kag0 that is a good question and one we've thought about often. It's a hard balance to strike between lowering the friction to getting started and having a completely secure system by default. Changing the defaults is difficult now as this would likely break existing and running systems out there, so we couldn't easily do this until VerneMQ 2.0 - maybe we can improve the docs?

**Comment by kag0** [comment]
Holding off until the next major version makes sense. 
There are a few places people might look in the docs where we could drop a hint.
1. https://docs.vernemq.com/plugin-development/introduction#chaining down near the comment about call chain ordering, we could note that the ACL plugin is loaded first by default, and that the default ACL is permissive and therefore any other added auth on publish and subscribe plugins will never be invoked. 
2. https://docs.vernemq.com/plugin-development/subscribeflow and https://docs.vernemq.com/plugin-development/publishflow we can note that nothing but the default ACL will be called for the auth hooks.
3. https://docs.vernemq.com/plugin-development/webhookplugins#auth_on_subscribe and https://docs.vernemq.com/plugin-development/webhookplugins#auth_on_publish just a note on each of these that the default ACL needs to be changed or ACL plugin disabled for these hooks to be invoked.

**Comment by okofish** [comment]
I agree with @kag0's suggestions on placing hints for this in the plugin docs.

It's definitely work considering disabling `vmq_acl` by default. Anonymous access is disabled by default, and the docs give clear instructions in multiple places (see https://docs.vernemq.com/configuring-vernemq/introduction#minimal-quickstart-configuration) for enabling it if you so desire - the same could be done with the ACL.

**Comment by larshesel** [comment]
Thanks for the suggestions! I'll see how we can incorporate them into the docs!
