### ISSUE TITLE
on_client_wakeup happens before on_register

### ISSUE THREAD

**Issue by doubliez** [erlio/vernemq#815]
### Environment

- VerneMQ Version: 1.5.0
- OS: Docker/Kubernetes
- Erlang/OTP version (if building from source):

### Expected behavior

According to https://vernemq.com/docs/plugindevelopment/sessionlifecycle.html, the on_client_wakeup webhook should be called after the on_register webhook.

### Actual behaviour

In my Node.js service where I implemented the webhook endpoints, I can see that on_client_wakeup is called about 10ms before on_register when I connect a client to the broker.

**Comment by dergraf** [comment]
Hello @doubliez , thank you for reporting.
You're absolutely correct, the `on_client_wakeup` is called before `on_register`. We'll change the flow chart accordingly.

**Comment by dergraf** [comment]
I've just updated the diagrams on the website.
Again thanks for reporting.
