### ISSUE TITLE
Shared subscriptions not working

### ISSUE THREAD

**Issue by tienthanh7992** [erlio/vernemq#816]
Environment
VerneMQ Version: 1.5.0
OS: CentOS
Tool: MQTT.fx

Expected behavior
My app needs to use load balancing mechanism, I have followed the guideline as below
but it does not work
https://vernemq.com/docs/configuration/shared_subscriptions.html

Actual behaviour
I use 2 subscriber and 1 publisher
I publish in the topic: $share/group/employee and subscribe to the topic: $share/group/employee
But 2 subscriber receives a duplicate message

**Comment by larshesel** [comment]
Hi, can you reproduce this behaviour with the `mosquitto_pub` and `mosquitto_sub` clients and if so guide us through the steps one by one?

Note that shared subscriptions are a subscriber side feature and the publisher has no knowledge of it, so in the above example you should only publish to `employee` not `$share/group/employee`.

**Comment by larshesel** [comment]
Hi, as we weren't able to reproduce this I'm closing this.
