### ISSUE TITLE
More detailed logging on authentication errors

### ISSUE THREAD

**Issue by weeco** [erlio/vernemq#831]
### Environment

- VerneMQ Version: 1.5.0
- OS: Docker (Debian:jessie)
- Erlang/OTP version (if building from source):

### Expected behavior

More logs on authentication errors if desired (maybe a config option). Why? Because it's quite hard to figure out why authentication is not working anymore after enabling SSL authentication.

### Actual behaviour

Nothing but these lines:

```
14:48:34.251 [warning] can't authenticate client {[],<<"abc1536674476260">>} due to error
14:48:37.549 [warning] can't authenticate client {[],<<"abc1536674476260">>} due to error
14:48:38.618 [warning] can't authenticate client {[],<<"abc1536674476260">>} due to error
```

**Comment by larshesel** [comment]
Hi @weeco thanks for opening this issue. I agree this is not very helpful. Which plugin are you using to authenticate the client - it's likely that plugin which returns the `error` reason.

**Comment by weeco** [comment]
I am using the MySQL authentication method

**Comment by larshesel** [comment]
The entire TLS handshake happens before the first MQTT frame (CONNECT) is sent, so in this case the certificate would be valid. It might help to trace what is happening with `vmq-admin trace client client-id=<clientid>`

**Comment by larshesel** [comment]
Are there any other errors or warnings before the warning you listed above?

**Comment by weeco** [comment]
> Are there any other errors or warnings before the warning you listed above?
No there are no errors or warnings directly related to the clients, I also didn't see any errors during startup. I'll try to trace a client now

**Comment by weeco** [comment]
@larshesel The trace client command returns for each authentication attempt:

> New session with PID <7251.3571.4> found for client "abc1536745189013"
> <7251.3571.4> MQTT RECV: CID: "abc1536745189013" CONNECT(c: abc1536745189013, v: 4, u: kinexon, p: u571yp7VEQGcNMi8, cs: 1, ka: 10)
> <7251.3571.4> Calling auth_on_register({{10,90,205,8},57499},{[],
>                                                               <<"abc1536745189013">>},kinexon,u571yp7VEQGcNMi8,true)
> <7251.3571.4> Hook returned {error,error}
> <7251.3571.4> MQTT SEND: CID: "abc1536745189013" CONNACK(sp: 0, rc: 5)
> <7251.3571.4> Trace session for abc1536745189013 stopped
> New session with PID <7251.3583.4> found for client "abc15367

**Comment by larshesel** [comment]
Hi, @dergraf, I think we could make this experience nicer by changing the code here: https://github.com/erlio/vernemq/blob/master/apps/vmq_diversity/src/vmq_diversity_plugin.erl#L395-L398

Maybe return `{error, not_authorized}` instead of just `error` - though maybe this should be handled up in the `auth_on_register/5` function and not in `all_till_ok/3`. We could also add sth like `{error, check_modifiers_failed}` if the `vmq_plugin_util:check_modifiers/2` failed.

What do you think?

**Comment by dergraf** [comment]
good idea
