### ISSUE TITLE
Struggling with SSL setup

### ISSUE THREAD

**Issue by weeco** [erlio/vernemq#837]
Do you have any tutorials about how to properly create certificates for a TLS setup on VerneMQ? Unfortunately I am struggling with the TLS setup and I only succeeded connecting to VerneMQ using TLS when I do a port-forward from my kubernetes pod to localhost. If I try to connect to the cluster using the ingress hostname or loadbalancer IP I always get ECONREFUSED.

I am not sure why this is happening, I am convinced by LoadBalancer is properly configured as I was able to access the metrics endpoint for instance.

Apparently VerneMQ doesn't show any logs for failed handshakes / connection attempts with invalid certs or similiar.

**Comment by larshesel** [comment]
I'm afraid we don't have any tutorials on that. Can you get it to work on a local setup without a load balancer etc - with less moving parts? That way you may be able to draw some conclusions where the problem may be.

There's also a lot of hints in the closed issues here on github and you're of course also welcome to ask on our slack forum http://slack-invite.vernemq.com/

**Comment by nickfloop** [comment]
I would like to reopen this issue. I have been struggling for some time now to get a simple SSL listener set up with the VerneMQ test certificates. It would help a lot of people out if you were able to provide a simple working example of how to set up SSL.

**Comment by ioolkos** [comment]
Hi @nickfloop allright, thanks!

For a simple configuration with our test certificates, the following lines in you `vernemq.conf` should be enough. If this works, you can then configure with your own certs and find out where any differences might be in case your own certs don't work.

```
listener.ssl.default = 127.0.0.1:8883

listener.ssl.cafile = /etc/vernemq/ssl/all-ca.crt
listener.ssl.certfile = /etc/vernemq/ssl/server.crt
listener.ssl.keyfile = /etc/vernemq/ssl/server.key
```
Do you see any specific errors or behaviours?

**Comment by nickfloop** [comment]
I have opened a new issue and put together my own SSL example as a Github repo in order to demonstrate the issues I am having. Please see here: https://github.com/erlio/vernemq/issues/856 . Thanks so much for your quick reply!
