### ISSUE TITLE
How to enable retained messages TTL? (MQTT 5)?

### ISSUE THREAD

**Issue by wsw70** [erlio/vernemq#839]
### Environment

- VerneMQ Version: 1.5.0
- OS: Linux (Ubuntu)

### Expected behavior

Ability to set a Time To Live for retained messages (a feature of MQTT 5)

### Actual behaviour

The README page mentions that 

> VerneMQ implements the MQTT 3.1, 3.1.1 and 5.0 specifications

and lists `Message expiration` in the implemented features (for "MQTT 5 clients", which is not clear as, if my understanding is correct, this is a server feature) .

I could not find any information about this in the docs, notably in https://vernemq.com/intro/features/

**Comment by larshesel** [comment]
Hi,

The MQTT 5.0 features has not yet been released but will be in VerneMQ 1.6.0 - to make use of the MQTT 5.0 features you can download one of the nightly builds based on 1.5.0. There's a bit more information about how to get started here: https://vernemq.com/mqtt5_getting_started.html

Message expiration is set by the client when publishing the message as a property. Read more about it here: http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs02/mqtt-v5.0-cs02.html#_Toc514345384

So to make use of the message expiry interval you need to use an MQTT 5.0 compatible client.

Let me know if this helps.

**Comment by wsw70** [comment]
It does help a lot, thank you.

It is a shame the TTL is a client feature (in the sense that it is requested by the client), I was hoping for the ability to remove retained messages after some time. I guess I will code this on the side but it will never be as reliable as if it was part of a server. 

Thanks again for the help and information.

**Comment by larshesel** [comment]
As with many other features in VerneMQ message expirations can be overriden(or added) by a plugin during the publish process. In this case one would have to override the `message_expiry_interval` property in the `auth_on_publish_m5` hook. We haven't had time to properly document this yet, though.
