### ISSUE TITLE
High Availability of a Cluster

### ISSUE THREAD

**Issue by DawoonC** [erlio/vernemq#84]
I have a cluster with two nodes (**node A** and **node B**).
And I had **node B** joined the cluster of **node A**.
e.g. vmq-admin cluster join discovery-node=**node A**

Below is the tests I've done to check high availability of my cluster.

## test 1
a client is connected and subscribed to **node B**
published to **node A**
successfully got message on a client

## test 2
manually stopped **node B**
published to **node A** again
successfully got message on a client (which was connected to **node B** in test 1)

## test 3
while **node B** remain stopped
published to **node B**
successfully got message on a client

## test 4
restarted **node B**
manually stopped **node A**
published to **node B**
successfully got message on a client

## test 5
while **node A** remain stopped
published to **node A**
failed to publish due to connection error (**node A** is not available)

The tests were successful until test 4, but when I stopped **node A**, it did not work as in previous tests.
So I'm guessing, since **node B** joined the cluster by discovering **node A**, it made **node A** some kind of **"main node"** in a cluster. And when the **"main node"** is not available, remapping of subscription/connection is not working as perfect as other **"sub nodes"**.

So I'm wondering if this was an intended behavior, or a misconfiguration of myself.

**Comment by dergraf** [comment]
Hi there
thanks for reporting.

how did you stop the node? Through ```vernemq stop```? 
Is your client connecting via a load balancer, is it auto-reconnecting?
how is your settings for ```trade_consistency```?

**Comment by DawoonC** [comment]
@dergraf Thanks for quick response! :)

Yes I did stop the node via `vernemq stop`
My client was connecting to the node directly via public IP
(when I stopped **node B**, auto-reconnecting was not triggered, but when I stopped **node A**, auto-reconnecting was triggered and it failed to reconnect)
And my setting is `trade_consistency = on`

**Comment by dergraf** [comment]
In theory your test results should look like the following:

- Test 1 MUST pass: because Cluster is consistent
- Test 2 SHOULD fail due to: If a client is connected to NodeB and you stop VerneMQ on NodeB, the connection to the client MUST break. I wonder how it was possible that you got the message.
- Test 3 MUST pass: because ```trade_consistency = on``` and Cluster is inconsistent
- Test 4 MUST pass: because actually same as Test 3 just in opposite direction
- Test 5 MUST fail: because you cannot publish to a dead node

Does this make sense?

**Comment by DawoonC** [comment]
It seems I made a mistake in my client's connect option for **node B**.
I've solved the issue with load balancer and everything works great now.

Sorry for false alarm :p 
And thanks :)

**Comment by dergraf** [comment]
Great!

Let us know if any other question come up. And if you like please share with us your use case. We are always looking for great stories! 

Cheers!
Andre
