### ISSUE TITLE
Recommendations for supervising and restarting VerneMQ

### ISSUE THREAD

**Issue by brucepom** [erlio/vernemq#851]
Thanks for the great work on this project. I'm interested in recommendations on monitoring and restarting VerneMQ when running in production on Ubuntu. My goal is to have VerneMQ restart if it crashes and if the server is rebooted. Folks who are running VerneMQ in production, do you prefer SystemD, Monit, Heart or something else? Does anyone have example SystemD unit files, Monit config or instructions for enabling Heart? Thanks!

**Comment by larshesel** [comment]
Hi, there's an example systemd file on our wiki: https://github.com/erlio/vernemq/wiki/Running-VerneMQ-as-a-systemd-service you could take a look at.

**Comment by brucepom** [comment]
Great, thanks @larshesel !
