### ISSUE TITLE
Enable SSL Listener with VerneMQ Docker Image Using Test Certificates and Keys

### ISSUE THREAD

**Issue by nickfloop** [erlio/vernemq#856]
### Environment

- VerneMQ Version:
1.5.0
- OS:
Ubuntu 16.04 running the erlio/docker-vernemq Docker image within Docker Compose
- Erlang/OTP version (if building from source):
N/A

### Expected behavior

- Please describe the expected behavior.
I am trying to enable an SSL listener so I can process MQTTS on port 8883 of the broker. I expect that when I start the broker with only an SSL listener configured on 0.0.0.0:8883 to use the VerneMQ test certificates that the broker will only have an MQTTS listener on 0.0.0.0:8883 (no MQTT listener on the default port 1883) and that broker will only accept connections authenticated with client certificates signed by the broker test CA certificate.

I am setting this up in Docker Compose using the erlio/docker-vernemq image for the broker and then using a Debian Jessie image with mosquitto-clients installed to run the pub and sub clients to test the connection. 

These are the test certificates I am referring to: https://github.com/erlio/vernemq/tree/master/apps/vmq_server/test/ssl

### Actual behavior
The broker service starts without error. The subscriber client hangs silently and never connects. The publisher client (publishing in a while loop with sleeps) hangs and never connects, though it does keep trying to reconnect periodically. I cannot tell if there is no connection because of networking issues, authentication issues with the CA cert, or ACL issues.

Despite the fact that my vernemq.conf file does not define a listener.tcp.default, there is still an MQTT listener on port 1883, though I cannot get the pub or sub client to connect to this listener.

- Please include minimal steps to reproduce the issue, if possible.

To make reproducing the issue more convenient, I have published a Github repo with a minimum example. You can easily run the example by building and running with Docker Compose. Find the code here: https://github.com/nickfloop/vernemq_ssl_example

Thanks for your help. I'm really looking forward to getting Dockerized VerneMQ to work correctly with SSL authentication.

**Comment by ioolkos** [comment]
@nickfloop thanks! your cert files in sub and pub are HTML files, so this won't work.
We have to look into some deeper issue though. Things seem to work with the `openssl s_client` command, but not the mosquitto clients.

**Comment by nickfloop** [comment]
@ioolkos Thanks for your quick reply! 

I fixed the silly HTML mix up, so now the certs are legitimate. You are correct that the `openssl s_client` command returns `CONNECTED(00000003)`.

With the correct certs in place, I now receive a `Error: Connection refused` error whenever I try to connect with the pub or sub clients through mosquitto. What am I missing?

**Comment by ioolkos** [comment]
Can't look into your example into detail right now, but it seems your VerneMQ is not using the vernemq.conf file you think it is. (the 1883 listener is a hint in that direction).
Have a look here:
https://github.com/erlio/docker-vernemq/blob/master/bin/vernemq.sh#L55-L87

A file named `vernemq.conf.local` file should be there if you want to replace the configs globally.

**Comment by ioolkos** [comment]
Additional notes: (this is with a local broker,not you docker example).

1) This works. "localhost" is verified by client.
```
➜  vernemq_ssl_example git:(master) ✗ mosquitto_pub -h localhost -p 8885 -t test/test -m "test" -d --cert ./sub/client.crt --key ./sub/client.key --cafile /etc/vernemq/ssl/all-ca.crt
Client mosqpub|2608-capo sending CONNECT
Client mosqpub|2608-capo received CONNACK (0)
Client mosqpub|2608-capo sending PUBLISH (d0, q0, r0, m1, 'test/test', ... (4 bytes))
Client mosqpub|2608-capo sending DISCONNECT
```

2) This does not work. Client cannot verify "127.0.0.1"
```
➜  vernemq_ssl_example git:(master) ✗ mosquitto_pub -h 127.0.0.1 -p 8885 -t test/test -m "test" -d --cert ./sub/client.crt --key ./sub/client.key --cafile /etc/vernemq/ssl/all-ca.crt
Client mosqpub|2886-capo sending CONNECT
Error: host name verification failed.
OpenSSL Error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Error: A TLS error occurred.
```
3) This works: client does not verify server, by using `--insecure` flag (not recommended):
```
➜  vernemq_ssl_example git:(master) ✗ mosquitto_pub -h 127.0.0.1 -p 8885 -t test/test -m "test" -d --cert ./sub/client.crt --key ./sub/client.key --cafile /etc/vernemq/ssl/all-ca.crt --insecure
Client mosqpub|3051-capo sending CONNECT
Client mosqpub|3051-capo received CONNACK (0)
Client mosqpub|3051-capo sending PUBLISH (d0, q0, r0, m1, 'test/test', ... (4 bytes))
Client mosqpub|3051-capo sending DISCONNECT
```

**Comment by nickfloop** [comment]
@ioolkos Thanks for providing examples of working behavior outside of Docker.

I am still looking for the source of that TCP listener on 1883. Is there any way to get VerneMQ to provide more detailed debug messages about where configurations are stored or how authentication handshakes are taking place? I'm still stuck behind the `Connected refused` message with no more information to push me ahead.

To give you more information about the listener situation, here are the current listeners running inside of the broker container:
 ```root@ae6cb341cd0e:/broker# vmq-admin listener show
+------+-------+----------+-----+----------+---------+
| type |status |    ip    |port |mountpoint|max_conns|
+------+-------+----------+-----+----------+---------+
| http |running|127.0.0.1 |8888 |          |  10000  |
| http |running|172.18.0.2|8888 |          |  10000  |
| vmq  |running|172.18.0.2|44053|          |  10000  |
|mqttws|running|172.18.0.2|8080 |          |  10000  |
|mqtts |running| 0.0.0.0  |8883 |          |  10000  |
| mqtt |running|172.18.0.2|1883 |          |  10000  |
+------+-------+----------+-----+----------+---------+```

**Comment by nickfloop** [comment]
I realized that Docker has been caching my running containers and not reloading the vernemq.conf correctly. If I run `docker-compose rm -f && docker-compose up` then it loads the config correctly. Here is my updated list of listeners with the TCP listener at 1883 now gone:
```
root@eeb4f4582cdc:/broker# vmq-admin listener show
+-----+-------+---------+-----+----------+---------+
|type |status |   ip    |port |mountpoint|max_conns|
+-----+-------+---------+-----+----------+---------+
|http |running|127.0.0.1|8888 |          |  10000  |
| vmq |running| 0.0.0.0 |44053|          |  10000  |
|mqtts|running| 0.0.0.0 |8883 |          |  10000  |
+-----+-------+---------+-----+----------+---------+
```

**Comment by nickfloop** [comment]
@ioolkos Can you please share the vernemq.conf/vernemq.conf.local you used for your examples outside of Docker? I want to make sure that I am not misunderstanding some of the settings. Thanks for your help!

**Comment by ioolkos** [comment]
To configure a TLS listener with test certs on localhost this is enough:

```
listener.ssl.default = 127.0.0.1:8883

listener.ssl.default.cafile = /etc/vernemq/ssl/all-ca.crt
listener.ssl.default.certfile = /etc/vernemq/ssl/server.crt
listener.ssl.default.keyfile = /etc/vernemq/ssl/server.key
```

Btw: can you try not using `0.0.0.0` but IP for the listener config?

**Comment by nickfloop** [comment]
@ioolkos Is the Docker erlio/docker-vernemq image environment different from your configuration outside of Docker? I have to manually install the cert files from the VerneMQ repo because they are not included in the Docker image. What else is different?

**Comment by larshesel** [comment]
> Client mosqpub/750-53f8140d6b1 sending CONNECT Client mosqpub/750-53f8140d6b1 received CONNACK Connection Refused: not authorised.

That you get a connack means that the TLS handshake was completed. That you get `Connection Refused: not authorised.` means that you have nothing configured to authenticate the user in question.

**Comment by ioolkos** [comment]
@nickfloop my apologies... I posted only the part of the vernemq.conf file related to the TLS listener. You still need the full vernemq.conf file. Without a full conf file the paths to the vmq_passwd and vmq_acl will not be configured. 

(thank you for your patience and effort!)

**Comment by nickfloop** [comment]
@larshesel Now I get it. Adding `allow_anonymous = on` lets the publisher connect and publish.

@ioolkos No need for apologies! You have been very helpful all along.

I am pleased to report that I have updated my code repo and the example now works as expected. For future people with the same questions about using VerneMQ, SSL, and Docker, I repost the link: https://github.com/nickfloop/vernemq_ssl_example

Thank you for your time and your help. SSL works as expected.

**Comment by ioolkos** [comment]
@nickfloop great to hear things work!
thanks for referencing & updating the link :+1:

**Comment by toritsejuFO** [comment]
This thread has really helped me. Thanks y'all, so much.
