### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by drasko** [erlio/vernemq#858]
### Environment

- VerneMQ Version: latest master
- OS: Debian
- Erlang/OTP version (if building from source): 20

### Expected behavior

Enable plugin

### Actual behaviour

```
drasko@Marx:~/vernemq/vernemq-broker/_build/default/rel/vernemq/bin$ ./vmq-admin plugin enable -n vernemq_demo_plugin -p /home/drasko/vernemq/vernemq_demo_plugin
Can't enable plugin: vernemq_demo_plugin due to plugin_not_found
```

**Comment by drasko** [comment]
I am getting this:
```drasko@Marx:~/vernemq/vernemq-broker$ ./_build/default/rel/vernemq/bin/vmq-admin plugin enable -n vernemq_demo_plugin -p /home/drasko/vernemq/vernemq_demo_plugin/_build/default
Can't enable plugin: vernemq_demo_plugin due to {unknown_module,
                                                 vernemq_demo_plugin}
```

**Comment by larshesel** [comment]
This is being discussed on the slack channel - closing this to not have a double conversation.

**Comment by alishir** [comment]
Dear @larshesel, 

Unfortunately I can not read slack archive, would you please post to solution here?

Regards,

**Comment by ioolkos** [comment]
@alishir when you can't enable a plugin, the reason is likely that you can't access the path, where you have your plugin.
If your error persists, please open a new issue, with detailled information.
