### ISSUE TITLE
vernemq failed to start within 15 seconds.......

### ISSUE THREAD

**Issue by baites1** [erlio/vernemq#860]
### Environment

- VerneMQ Version: 1.5.0-1 (amd64)
- OS: Ubuntu 16.04 Xenial, running on Google Compute Instance
- Erlang/OTP version (if building from source): N/A, Pre-built binary package

### Expected behavior

- When executing command "sudo vernemq start", vernemq should start (and if successful will report no output on the console).

### Actual behavior

- When attempting to start VerneMQ on the console, the console reports back "vernemq failed to start within 60 seconds, see the output of 'vernemq console' for more information"

My setup:
1) I have a fresh install of VerneMQ on a clean google compute instance (2 vCPU, 6 GB Mem, 10 GB SSD).
2) I have altered the vernemq.conf configuration file to attach the tcp listener to 0.0.0.0:1883, and alter the node name.
3) I have added 2 users to the wmq.acl and vmq.passwd files, on with full read/write access to all topics, and another with limit privileges.
4) I have added an OS environmental variable to increase the VerneMQ start timeout from 15 seconds, to 60 seconds.

When I execute the command to start VerneMQ, I receive the timeout message mentioned above, HOWEVER, it appears as if the MQTT broker is actually operational, as I can use a MQTT client (Node-Red in this case, running on my laptop) to connect, publish and subscribe to topics on the VerneMQ broker.

From a MQTT client perspective, it looks like the VerneMQ broker is operational.
At this time, if I execute the command "sudo vernemq ping" I receive the error message "Node 'VerneMQ@GCP' is not responding to pings".
If I execute the command "sudo vernemq stop", I am told the "Node is not running!" (yet, I am able to use a MQTT client, Node-Red in this case, to publish and subscribe to topics).

Logs attached

[Logs.zip](https://github.com/erlio/vernemq/files/2417324/Logs.zip)

**Comment by larshesel** [comment]
Hi, did you happen to change the node name while the broker was running? The node name in the config file is the identifier used by the tooling to contact the node via Erlang distribution so if it is changed while the broker is running things will stop working like you report.

In this case you have to either change the nodename back to the original and stop VerneMQ, then change the nodename and then start VerneMQ up again.

You can check which nodename VerneMQ is currently using by doing a `ps -ef | grep beam.smp` which should show something a vernemq process running and one of the options is the nodename  `-name VerneMQ@127.0.0.1` 

Hope this helps.

**Comment by baites1** [comment]
Hi Lars,

Apologies, I thought I had stopped the node before changing it's name, but I mustn't have. I've done as you said and everything is working perfectly again. Thank you for you help, it's greatly appreciated.

**Comment by larshesel** [comment]
Perfect, glad I could help - I think I'll write this into FAQ in the wiki :)
