### ISSUE TITLE
Cluster failure. Node cannot start, clustered node in "not ready" state

### ISSUE THREAD

**Issue by mhball** [erlio/vernemq#866]
### Environment

- VerneMQ Version: 1.4.1
- OS: Ubuntu 16.04.4
- Erlang/OTP version (if building from source): N/A

### Expected behavior

- Clustered nodes should continue to function with bad nodes in the cluster.

### Actual behaviour

- We have a two node cluster, and a node stops responding completely. Nothing can connect to the cluster or send messages.  Any attempt to connect to the cluster fails.  The running node shows the following in the console.log
```
2018-10-01 10:38:18.944 [warning] <0.1747.0>@vmq_mqtt_fsm:check_user:569 can't register client {[],<<"mqttjs_c170b81d">>} due to reason not_ready
2018-10-01 10:38:19.105 [warning] <0.1748.0>@vmq_mqtt_fsm:check_user:569 can't register client {[],<<"mqttjs_79dfa312">>} due to reason not_ready
```

When restarting the bad node, console.log show the following
```
2018-10-01 10:52:36.456 [info] <0.31.0> Application plumtree started on node 'VerneMQ@10.61.91.131'
2018-10-01 10:52:36.480 [info] <0.31.0> Application hackney started on node 'VerneMQ@10.61.91.131'
2018-10-01 10:52:36.544 [info] <0.31.0> Application inets started on node 'VerneMQ@10.61.91.131'
2018-10-01 10:52:36.544 [info] <0.31.0> Application xmerl started on node 'VerneMQ@10.61.91.131'
2018-10-01 10:52:36.609 [info] <0.31.0> Application vmq_plumtree started on node 'VerneMQ@10.61.91.131'
2018-10-01 10:52:36.627 [info] <0.248.0>@vmq_metadata:start:27 Try to start vmq_plumtree: ok
```
And nothing more, the node fails to start.

In order to get it to start I deleted the /var/lib/vernemq/msgstore directory (noticed it was 1.3GB, which seemed large but confirmed the machine had disk space available). After this the node restarted fine.

**Comment by ioolkos** [comment]
@mhball thanks. for the first part, please have a look at the blue note here: https://vernemq.com/docs/clustering/netsplits.html ie set `allow_register_during_netsplit`, `allow_publish_during_netsplit`, `allow_subscribe_during_netsplit`, and `allow_unsubscribe_during_netsplit` to on.

The second part (node fails to start) is probably related to the crash (was it a crash?). Do you have any information/logs what happened there?

**Comment by mhball** [comment]
The crash.log file has the following from today; however, I believe issue arrised earlier than the first timestamp.
```
2018-10-01 08:08:13 =ERROR REPORT====
** Generic server <0.13940.2486> terminating 
** Last message in was timeout
** When Server state == {state,<12740.345.0>,<0.13884.2486>,<0.14041.2486>}
** Reason for termination == 
** {{{nodedown,'VerneMQ@10.61.47.100'},{gen_server,call,[{vmq_reg_sync,'VerneMQ@10.61.47.100'},{done,<0.13940.2486>,{error,action_timeout}},infinity]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{vmq_reg_sync_action,handle_info,2,[{file,"/opt/vernemq/distdir/1.4.1/_build/default/lib/vmq_server/src/vmq_reg_sync_action.erl"},{line,64}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-10-01 10:49:03 =ERROR REPORT====
** Generic server memsup terminating 
** Last message in was {'EXIT',<0.126.0>,{port_died,normal}}
** When Server state == [{data,[{"Timeout",60000}]},{items,{"Memory Usage",[{"Allocated",557584384},{"Total",4142133248}]}},{items,{"Worst Memory User",[{"Pid",<0.3.0>},{"Memory",601856}]}}]
** Reason for termination == 
** {port_died,normal}
2018-10-01 10:49:03 =CRASH REPORT====
  crasher:
    initial call: memsup:init/1
    pid: <0.125.0>
    registered_name: memsup
    exception exit: {{port_died,normal},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [os_mon_sup,<0.122.0>]
    messages: []
    links: [<0.123.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 11534
  neighbours:
2018-10-01 10:49:03 =SUPERVISOR REPORT====
     Supervisor: {local,os_mon_sup}
     Context:    child_terminated
     Reason:     {port_died,normal}
     Offender:   [{pid,<0.125.0>},{id,memsup},{mfargs,{memsup,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]
```

**Comment by ioolkos** [comment]
For some quick context: what kind of server specs is this running on? (cpus, ram)

**Comment by mhball** [comment]
Regarding the allow_register_during_netsplit, allow_publish_during_netsplit, allow_subscribe_during_netsplit, and allow_unsubscribe_during_netsplit parameters, is there any drawback to setting them to on? 
I'm really wondering why these aren't set to on by default?

**Comment by mhball** [comment]
> For some quick context: what kind of server specs is this running on? (cpus, ram)

It's an AWS EC2 t2.medium
The specs are:
2 CPUs - Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
4GB RAM

**Comment by ioolkos** [comment]
Re the 'allow-*' settings: I agree. I'll see that we set this to default settings.

**Comment by larshesel** [comment]
I'd guess the crash was due to an out of memory situatuion. Do you have some monitoring in place which can keep track of cpu/memory over time?

**Comment by mhball** [comment]
Unfortunately not. Is there a tool you'd recommend for monitoring this on VerneMQ nodes?

**Comment by larshesel** [comment]
For monitoring we like prometheus http://vernemq.com/docs/monitoring/prometheus.html and basically having all the metrics available would reveal a lot of details about memory usage. Prometheus also has a node_exporter which can export os metrics.

**Comment by mhball** [comment]
Thanks for the advise. We'll investigate our memory usage

**Comment by ranvijayj** [comment]
Any update on this? We got same crash logs but memory usage was 30%

**Comment by larshesel** [comment]
Hi @ranvijayj could you open another issue detailing what you see?

**Comment by agenteDserrano** [comment]
I have same problem here. My server was working out of problem and afeter restart I cant start node

**Comment by larshesel** [comment]
@agenteDserrano if this is the issue you reported on slack then it doesn't look like the same problem (besides not being able to start). Could I ask you to open a new issue with all details filled out?
