### ISSUE TITLE
ERLang make rel fails due to old try-catch syntax

### ISSUE THREAD

**Issue by xbugster** [erlio/vernemq#869]
### Environment

- VerneMQ Version: 1.5.0
- OS: ubuntu 16.04
- Erlang/OTP version (if building from source):
[{release,"Erlang/OTP","21","10.0.5",
          [{kernel,"6.0","/usr/lib/erlang/lib/kernel-6.0"},
           {stdlib,"3.5.1","/usr/lib/erlang/lib/stdlib-3.5.1"},
           {sasl,"3.2","/usr/lib/erlang/lib/sasl-3.2"}],
          permanent}]

### Expected behavior
Expected to build from latest commits using `make rel`, exactly as stated in documentation.

### Actual behaviour
After cloning the repo and building, the erland redbug.erl throws error on `erlang:get_stacktrace/0` stating the call is deprecated.
```
$ make rel
/tmp/vernemq/rebar3  release --overlay_vars vars.config
===> Verifying dependencies...
===> Compiling eper
===> Compiling _build/default/lib/eper/src/redbug.erl failed
_build/default/lib/eper/src/redbug.erl:141: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace
_build/default/lib/eper/src/redbug.erl:267: erlang:get_stacktrace/0: deprecated; use the new try/catch syntax for retrieving the stack backtrace

Makefile:56: recipe for target 'rel' failed
make: *** [rel] Error 1

```
Following is the documentation on erlang which explains about updated functionality and deprecation of get_stacktrace: http://erlang.org/eeps/eep-0047.md

**Comment by larshesel** [comment]
Hi, VerneMQ doesn't yet support Erlang/OTP 21, see #738. Use Erlang/OTP 20 for now.
