### ISSUE TITLE
Can't build 0.12 - Error 

### ISSUE THREAD

**Issue by Reddone** [erlio/vernemq#87]
Hi, I have a problem building the last version with 17.5. I tried ./rebar3 upgrade, but I still can't solve the problem. Thx in advance for any help you are able to provide :-)

===> Upgrading cuttlefish
===> Failed to fetch and copy dep: {git,
                                  "git://github.com/tsloughter/cuttlefish.git",
                                  {ref,
                                      "f5f6fdc1b0dd8ebe909b81f0b38f5715d4e869e6"}}

**Comment by ioolkos** [comment]
Hi Simone, thanks for reporting!
`./rebar3 upgrade` will try to upgrade all deps, which is not what you'll want to do, because lock the dependencies per release. (see rebar.lock).

But the reason why it failed to just *fetch* cuttlefish must be somewhere else.
@dergraf any more thoughts?

**Comment by dergraf** [comment]
Difficult to say from here.. But 'upgrade' is not the needed here.
Cheers

**Comment by larshesel** [comment]
To me it looks like you're either having network problems or the network you're on is restricted. I get the very same error if I try to build VerneMQ on a network that doesn't allow the port (9418 I think) for the git protocol through.

Can you try on another network?

**Comment by ejaigom** [comment]
a similiar issue when running #make rel on my macbook

─$ make rel                                                                                                                                                                                            1 ↵
/Users/jgomes/Repositories/Github/vernemq/rebar3 release --overlay_vars vars.config
===> Verifying dependencies...
===> Fetching cuttlefish ({git,
                                  "git://github.com/tsloughter/cuttlefish.git",
                                  {ref,
                                   "f5f6fdc1b0dd8ebe909b81f0b38f5715d4e869e6"}})
===> Failed to fetch and copy dep: {git,
                                  "git://github.com/tsloughter/cuttlefish.git",
                                  {ref,
                                      "f5f6fdc1b0dd8ebe909b81f0b38f5715d4e869e6"}}
make: *** [rel] Error 1

**Comment by larshesel** [comment]
@ejaigom can you verify if you can telnet to github.com at port 9418:

If your network allows the git protocol/port 9418 it should look like this
```
$ telnet github.com 9418
Trying 192.30.252.130...
Connected to github.com.
Escape character is '^]'.
```

If not it looks like this:
```
$ telnet github.com 9418
Trying 192.30.252.130...
telnet: Unable to connect to remote host: Connection refused
```
In which case you should try to again from a network with less restrictions.

@dergraf do you see an issue if we change our dependencies to use https instead of git? The likelihood of https being blocked on a network is probably much lower than git being blocked...

**Comment by larshesel** [comment]
@ejaigom @Reddone I've now seen the same error on a network without restrictions and tracked it down to a problem with the cuttlefish dependency/git repo. We've upgraded the cuttlefish dependency which removes the problem for us, so please try and fetch vernemq from master and see if you still have the problem. This fix will of course be included in the next official release.

**Comment by ejaigom** [comment]
@larshesel yeap, It works!

**Comment by Reddone** [comment]
yeah, it works. Thank you very much!!!

**Comment by larshesel** [comment]
Thanks for confirming the fix!
