### ISSUE TITLE
Tracing mqtt_publish_auth_error

### ISSUE THREAD

**Issue by weeco** [erlio/vernemq#879]
### Environment

- VerneMQ Version: 1.5.0
- OS: Docker
- Erlang/OTP version (if building from source):

I saw that multiple VerneMQ nodes return mqtt_publish_auth_errors in their metrics endpoint:

```
# HELP mqtt_publish_auth_error The number of unauthorized publish attempts.
# TYPE mqtt_publish_auth_error counter
mqtt_publish_auth_error{node="VerneMQ@vernemq-0.vernemq.messaging.svc.cluster.local",mqtt_version="4"} 3
```

How can I figure out where these auth errors come from? Is there some way to trace them? I tried `vmq trace client client-id` but I didn't find any messages about failed publish auths or similiar? I am using publish acls and I could only imagine the client who's restricted to publish in a specific topic tree tries to publish messages into another topic tree.

**Comment by larshesel** [comment]
This should be visible in the error logs:

```
[error] <0.444.0>@vmq_mqtt_fsm:auth_on_publish:691 can't auth publish [undefined,{[],<<"client">>},0,[<<"illegal">>,<<"topic">>],<<"payload">>,false] due to no_matching_hook_found
```
of course the reason is likely different.

Hope this helps!

**Comment by weeco** [comment]
I don't see this or a similiar message on any of my nodes, however the metrics indicate a constant auth_publish_error count of 3 on all of my nodes.

So unfortunately your response doesn't help me :(.

**Comment by weeco** [comment]
Yes I do see other warnings and logs, however I don't think they are related at all (also because they don't show up frequently and make sense to me):

> 08:43:15.100 [warning] can't authenticate client {[],<<"test-client">>} due to error
> 08:43:17.009 [warning] can't authenticate client {[],<<"test-client">>} due to error
> 15:10:55.325 [warning] Broadcast overloaded, 291ms mailbox traversal, schedule next lazy broadcast in 41338ms, the min interval is 10000ms
> 18:17:00.200 [warning] client {[],<<"test-client">>} with username <<"testuser">> stopped due to keepalive expired
> 20:05:27.534 [warning] Broadcast overloaded, 269ms mailbox traversal, schedule next lazy broadcast in 40536ms, the min interval is 10000ms
> 11:26:13.739 [info] completed metadata exchange with 'VerneMQ@vernemq-3.vernemq.messaging.svc.cluster.local'. repaired 0 missing local prefixes, 0 missing remote prefixes, and 1 keys
> 11:27:14.989 [warning] can't authenticate client {[],<<"client2">>} due to error

**Comment by weeco** [comment]
Yes I do use vmq_diversity and I also reported the due to error message roughly 1 month ago. However I didn't know that this will impact the above logging as well.

Any chance to know when you'll release a new version including this fix? I am waiting for a better logging for so long now :(

Also could you explain the meaning of "due to chain_exhausted" ?

**Comment by larshesel** [comment]
about chain_exhausted: https://github.com/erlio/vernemq/issues/446#issuecomment-315614348

We'll likely release 1.6.0 in one or two weeks.

**Comment by weeco** [comment]
Hmm chain_exhausted is very weird because I didn't restart the server/node for a long time and it does work fine with SQL authentication.

As of the can't auth publish error:

Can you explain the message format of my givene xample? Did the client "test-client" try to publish a message in the topic "position"? The ACL authorizes only publishing messages into "/topictree/#" hence I am asking if this is the problem?

Also: Why doesn't show up the error message 3 times / second when the metrics indicate this publish auth error happens 3 times / second??

**Comment by larshesel** [comment]
```
09:11:50.449 [error] can't auth publish [<<"test">>,{[],<<"test-client">>},1,[<<"test">>,<<"position">>],<<"{\n "timestamp": "2018-10-05T09:11:44.548Z",\n "objectId": 221,\n "x": 50.8988,\n "y": 19.4928\n}">>,false] 
```

This means that the client with username `test`, the empty mountpoint `[]`, client id `test-client` tried to publish a qos 1 message to the topic `test/position`.

The metrics doesn't have any notion of time. They just record that it happened (in this case 3 times) but has no knowledge of when it happened.

**Comment by weeco** [comment]
Thanks, that explains why the value doesn't change. I am a bit surprised that it is 3 for all of my nodes. Anyways I assume that this is not the overall error count of all cluster nodes or? In Grafana I sum all values reported by all of the nodes.

**Comment by larshesel** [comment]
Metrics are node-local and are not replicated across the cluster
