### ISSUE TITLE
Add information about CFLAGS env variable in build from source documentation

### ISSUE THREAD

**Issue by gausby** [erlio/vernemq#88]
I just made vernemq build use Erlang 18 on OS X by doing the following.

  1. I checked out the currently open pull-request that resolves the Erlang 18 build issues. https://github.com/erlio/vernemq/pull/81
  2. I merged the current master into this branch, as it resolves an issue with Cuttlefish
  3. I ran `make rel`, but it failed at vmq-passwd, as it couldn't find the openssl headers on my system
  4. I fixed this by adding `-L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include` to the Makefile in vmq-passwd/c_src and run a build in that directory.
  5. Then I ran the `make rel` again and it made it all the way through.

I later found out that I could specify the headers using CFLAGS. I think that CFLAGS would be worthy of a mention in the build from source instructions.

**Comment by gausby** [comment]
I forgot to mention; I have openssl installed via Homebrew. A package manager for OS X.

**Comment by larshesel** [comment]
Hey @gausby sorry for letting this issue stew for so long, thank you for contributing it. Maybe @ioolkos can adapt the docs to include something about this as he actually owns a mac. If not I'll try and write something up, but full disclosure: I'm no mac user so I'm hardly qualified :)

**Comment by dergraf** [comment]
closing this issue in favor of erlio/vernemq#119

**Comment by syberkitten** [comment]
@gausby This works for me as well, adding this line into the MakeFile:
-L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include

final result:
```
CC?=	gcc

compile:
	$(CC) $(CFLAGS) vmq_passwd.c -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -lcrypto -o ../priv/vmq_passwd
```

Now the code compiles on El-Capitan using Erlang OTP/19.3 (with Kerl)

**Comment by gausby** [comment]
@syberkitten I got it running now, thanks :)
