### ISSUE TITLE
vmq-admin usage output should include vernemq version number

### ISSUE THREAD

**Issue by chriswue** [erlio/vernemq#885]
- VerneMQ Version: 1.5.0

`vmq-admin` output shows:

    Usage: vmq-admin <sub-command>

    Administrate the cluster.

    Sub-commands:
      node        Manage this node
      cluster     Manage this node's cluster membership
      session     Retrieve session information
      plugin      Manage plugin system
      listener    Manage listener interfaces
      metrics     Retrieve System Metrics
      api-key     Manage API keys for the HTTP management interface
      trace       Trace various aspects of VerneMQ
    Use --help after a sub-command for more details.

I was experimenting with various versions and containers and it's not that easy from the command line to figure out which version is running. So adding the version number to the output of the above command would make life little bit easier, like:

    VerneMQ 1.5.0
    Usage: vmq-admin <sub-command>

    Administrate the cluster.

    Sub-commands:
      node        Manage this node
      cluster     Manage this node's cluster membership
      session     Retrieve session information
      plugin      Manage plugin system
      listener    Manage listener interfaces
      metrics     Retrieve System Metrics
      api-key     Manage API keys for the HTTP management interface
      trace       Trace various aspects of VerneMQ
    Use --help after a sub-command for more details.

**Comment by larshesel** [comment]
It's in `vernemq version` - arguably it would be helpful to include it in `vmq-admin` as well

**Comment by dergraf** [comment]
Closing for now, as `vernemq version` already serves this purpose.

**Comment by vijapandey** [comment]
> Closing for now, as `vernemq version` already serves this purpose.

By this , still not able to see version .....

**Comment by ioolkos** [comment]
@vijapandey hm, I think you should see a version, even with self-compiled approach.
What version do you try to compile? (if that's not recursively impossible to answer :)

```
➜  vernemq git:(master) ✗ _build/default/rel/vernemq/bin/vernemq version
1.12.6.2-2-ge33f7ab
```

---
:point_right: Thank you for supporting VerneMQ: https://github.com/sponsors/vernemq
:point_right: Using the binary VerneMQ packages commercially (.deb/.rpm/Docker) requires a paid subscription.
