### ISSUE TITLE
vmq-admin session show

### ISSUE THREAD

**Issue by acsdkquery** [erlio/vernemq#887]
### Environment

- VerneMQ Version:1.5.0
- OS:Ubuntu
- Erlang/OTP version (if building from source):

### Expected behavior

clear session - TRUE
client id - Client1 

step:1 
========
Client1 ----connected---->VerneMQ

root@ip-172-31-3-65:/home/ubuntu/vernmq# vmq-admin session show
+----------------------+---------+----------+-------------+---------+--------+
|      client_id       |is_online|mountpoint|  peer_host  |peer_port|  user  |
+----------------------+---------+----------+-------------+---------+--------+
|Client1                |  true   |          |121.242.39.66|  44796  |asds|
+----------------------+---------+----------+-------------+---------+--------+

step:2 (internet issue at client side, and no proper disconnect from Client1)
========
(internet issue at client side, and no proper disconnect from Client1)

Client1 ----not connected---->VerneMQ

(Broker still showing Client1 is active)
root@ip-172-31-3-65:/home/ubuntu/vernmq# vmq-admin session show
+----------------------+---------+----------+-------------+---------+--------+
|      client_id       |is_online|mountpoint|  peer_host  |peer_port|  user  |
+----------------------+---------+----------+-------------+---------+--------+
|Client1                |  true   |          |121.242.39.66|  44796  |asds|
+----------------------+---------+----------+-------------+---------+--------+

### Actual behaviour

Broker should show Client1 is not active

**Comment by dergraf** [comment]
Hello @acsdkquery 
Thank you for opening the issue. 
Without knowing more about your setup I guess that either your TCP timeout or MQTT keepalive timers haven't triggered the removal of the client on the broker.

**Comment by acsdkquery** [comment]
Thank you @dergraf for your prompt response,
By default, the TCP connection timeout is 15 minutes(its bit expensive), my requirement is find the state of the client when ASAP of the client disconnect from the broker (b'coz i am using clear session - TRUE)

**Comment by dergraf** [comment]
ok. what is the MQTT keep alive time in that case?

**Comment by acsdkquery** [comment]
Vernmq side,
 cat /etc/vernemq/vernemq.conf | grep keepalive
## vmq_bridge.tcp.br0.keepalive_interval = 60

**Comment by acsdkquery** [comment]
I have modified the TCP timeout, still session shows active after TCP timeout (i have restared the vernmq too),
root@ip-172-31-3-65:/home/ubuntu# cat /proc/sys/net/ipv4/tcp_keepalive_probes 
3
root@ip-172-31-3-65:/home/ubuntu# cat /proc/sys/net/ipv4/tcp_keepalive_intvl 
5
root@ip-172-31-3-65:/home/ubuntu# cat /proc/sys/net/ipv4/tcp_keepalive_time 
10
root@ip-172-31-3-65:/home/ubuntu#  (timeout will be 10 + (15) 3*5 = 25sec )

root@ip-172-31-3-65:/home/ubuntu# date
Mon Oct  8 10:40:00 UTC 2018
root@ip-172-31-3-65:/home/ubuntu# vmq-admin session show
+----------------------+---------+----------+-------------+---------+--------+
|      client_id       |is_online|mountpoint|  peer_host  |peer_port|  user  |
+----------------------+---------+----------+-------------+---------+--------+
|Client1|  true   |          |121.242.39.66|  45094  |wioadmin|
+----------------------+---------+----------+-------------+---------+--------+

root@ip-172-31-3-65:/home/ubuntu# date
Mon Oct  8 10:43:26 UTC 2018
root@ip-172-31-3-65:/home/ubuntu# vmq-admin session show
+----------------------+---------+----------+-------------+---------+--------+
|      client_id       |is_online|mountpoint|  peer_host  |peer_port|  user  |
+----------------------+---------+----------+-------------+---------+--------+
|Client1|  true   |          |121.242.39.66|  45094  |wioadmin|
+----------------------+---------+----------+-------------+---------+--------+

root@ip-172-31-3-65:/home/ubuntu#

**Comment by dergraf** [comment]
which MQTT client library are you using? Is `60` in seconds or minutes or ...?
Can you use `netstat` or similar to figure out the state of the TCP session that is lingering around? From a VerneMQ perspective it looks like we haven't received either a TCP Close or some TCP Error.... obviously this is only true if the `error.log` doesn't show otherwise.

**Comment by acsdkquery** [comment]
its 60 in seconds, i think i will check the TCP packet capture and update more on this,
by the way, how to clear the existing sessions(connected with clear session=false)? 
i tried restarting the service, uninstall/install the vernmq again, but still its showing lots of my old sessions, (also i tried vmq-admin session disconnect, but not clearing at all)

**Comment by acsdkquery** [comment]
i think we can close the original issue, Client1 keepalive is not 60 sec its some random value and high and so session timeout not happened,   and can you help me on the other one,
how to clear the existing sessions(connected with clear session=false)?
i tried restarting the service, uninstall/install the vernmq again, but still its showing lots of my old sessions, (also i tried vmq-admin session disconnect, but not clearing at all)

**Comment by dergraf** [comment]
Great!
You must use the `vmq-admin session disconnect client-id=<YourClientId> -c` .. the `-c` is required to force delete any accumulated state for this client.

A more brutal way to reset VerneMQ is to stop it and to delete the `meta` and `msgstore` directory from the disk, most probably under `/var/lib/vernemq`.

**Comment by acsdkquery** [comment]
Thank you so much @dergraf , Appreciate it!!!
