### ISSUE TITLE
vernemq file based authentication

### ISSUE THREAD

**Issue by rnrdevops** [erlio/vernemq#900]
### Environment

- VerneMQ Version:  vernemq-1.5.0-1
- OS: Redhat
- Erlang/OTP version (if building from source):

### Expected behavior

Hi i am testing user based authentication using password file, i have created user henry and password as henry  bu using command 
vmq-passwd -c /etc/vernemq/vmq.passwd henry
### Actual behaviour

I am able to connect to vernemq without user authentication, but I want to connect to vernemq only when username and password is specified. is there anything I am doing wrong. please help.
 Thanks in advance!!

- Please include minimal steps to reproduce the issue, if possible.
i have changed config file 
plugins.vmq_passwd = off
allow_anonymous = on
vmq_passwd.password_file = /etc/vernemq/vmq.passwd

**Comment by chriswue** [comment]
This is your problem: `allow_anonymous = on` - you need to set this to `off`

**Comment by rnrdevops** [comment]
I turned off allow_anonymous = off, and tried to connect using usernme and password, but no luck

i am getting below error in error.log

2018-10-17 03:32:07.208 [error] <0.441.0>@vmq_mqtt_fsm:check_user:547 can't authenticate client {[],<<"clientId-DHCVLlBC07">>} due to
                                no_matching_hook_found

**Comment by rnrdevops** [comment]
Hey Thank you

i have add below in config file and it started working

plugins.vmq_passwd = on
plugins.vmq_webhooks = on

**Comment by dergraf** [comment]
Closing the issue! Thanks @chriswue for answering the question.

**Comment by dergraf** [comment]
Closing, thank you @chriswue for anwering the question.
