### ISSUE TITLE
 can't call function auth_on_register with args in "/usr/share/vernemq/lua/auth/postgres.lua" due to {badarg,'#',[false]}

### ISSUE THREAD

**Issue by agenteDserrano** [erlio/vernemq#904]
### Environment

- VerneMQ Version: vernemq_1.5.0-1_amd64.deb
- OS: debian 9 Linux web1 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

- Erlang/OTP version (if building from source):

### Expected behavior

- user authentication using postgres

### Actual behaviour

2018-10-23 10:35:49.662 [error] <0.378.0>@vmq_diversity_script_state:handle_info:171 can't call function auth_on_register with args [{addr,<<"10.0.51.128">>},{port,55441},{mountpoint,<<>>},{client_id,<<"test-client1540299189799">>},{username,<<"test-user">>},{password,<<"123">>},{clean_session,true}] in "/usr/share/vernemq/lua/auth/postgres.lua" due to {badarg,'#',[false]}

**Comment by larshesel** [comment]
Hi @agenteDserrano 

Are there any errors earlier in the logs before this one?

**Comment by agenteDserrano** [comment]
[err.log](https://github.com/erlio/vernemq/files/2511961/err.log)

Hello. I attach the the log from console and error files mixed.

Thanks

**Comment by agenteDserrano** [comment]
@larshesel Hello!

Any help about this issue ?

**Comment by larshesel** [comment]
Hi, sorry, quite busy with other things as well.

Were the lua scripts modified in any way?

Can you check with the postgresql tools and the postgresql logs if the client was able to connect and authenticate properly or if there are any issues executing the queries?

**Comment by agenteDserrano** [comment]
do not worry and thank you very much for the help.
Doing a postgres logging I found that it was authenticated but there was a problem of permissions in the table.

It is already solved and working.

As a suggestion I would recommend passing the database responses to the verneMQ log for faster detection of problems of this type.

Greetings.

**Comment by larshesel** [comment]
In VerneMQ 1.6 we tried to improve the error messages coming from the databases. It's probably not perfect, but hopefully better.
