### ISSUE TITLE
Can't publish message

### ISSUE THREAD

**Issue by miptildar** [erlio/vernemq#915]
### Environment

- VerneMQ Version: 1.5.0
- OS: Ubuntu 18 (AWS EC2)
- Erlang/OTP version (if building from source):

### Expected behavior

I am trying to implement a messenger on Android. I've configured VerneMQ server using official documentation and used PostgreSQL as an auth server.
I used [this query](https://docs.vernemq.com/configuring-vernemq/db-auth#postgresql) to add a new user.
As an Android client I used [Eclipse Paho Android Service](https://github.com/eclipse/paho.mqtt.android).

What is the result: both Android clients are able to connect to server. But when I try to send a message from one to another, the sender fails: 
`java.net.SocketException: Connection reset`
`at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:146)`
`at java.lang.Thread.run(Thread.java:784)`
`Caused by: java.net.SocketException: Connection reset ...`

How I send messages:
Lets say there are 2 clients with the following client IDs: `first_client_id `and `second_client_id`.
When application starts, each client subscribes to **himself**. 
Example: If `first_client_id` wants to send message to `second_client_id`, the first one have to publish message to channel "**second_client_id**".

MQTT client configuration:
```
setAutomaticReconnect - true
setCleanSession - true
```

What could be the problem?

**Comment by larshesel** [comment]
Hi, does it work if you publish with the same client-ids using the  `mosquitto_pub` and `mosquitto_sub` clients?

Above it looks like the  client is being disconnected when publishing - this usually happen if the client isn't authorized to publish to the topic. So you could look into that.

You could try to use `vmq-admin trace client client-id=<clientidofpublisher>` to see what happens between the client and the broker.

Also, there might be something in the log files which could hint at the problem.

**Comment by miptildar** [comment]
Thank for you for your quick reply!
I used the following PostgreSQL query to add a new user :
```
WITH x AS (
    SELECT
        ''::text AS mountpoint,
           'first_client_id'::text AS client_id,
           'first'::text AS username,
           '123'::text AS password,
           gen_salt('bf')::text AS salt,
         '[{ "pattern": "u2u/#" }]'::json AS publish_acl,
           '[{ "pattern": "u2u/#" }]'::json AS subscribe_acl
    ) 
INSERT INTO vmq_auth_acl (mountpoint, client_id, username, password, publish_acl, subscribe_acl)
    SELECT 
        x.mountpoint,
        x.client_id,
        x.username,
        crypt(x.password, x.salt),
        publish_acl,
        subscribe_acl
    FROM x;
```

I thought to use `u2u/{clientID}` pattern to publish and receive messages

Running the command: `sudo vmq-admin trace client client-id=first_client_id` returns the following messages when I try to send message as `first_client_id`:

1. `Starting trace for 1 existing sessions for client "ildar_client_id" with PIDs [<7251.1551.0>]`
2. `<7251.1551.0> Trace session for ildar_client_id stopped`
3. `New session with PID <7251.1569.0> found for client "ildar_client_id"`
4. `<7251.1569.0> MQTT RECV: CID: "ildar_client_id" CONNECT(c: ildar_client_id, v: 4, u: ildar, p: 123, cs: 1, ka: 60)`
5. `<7251.1569.0> Calling auth_on_register({{176,59,37,217},39698},{[], <<"first_client_id">>},first,123,true)`                                  
6. `<7251.1569.0> Hook returned "ok"`
7. `<7251.1569.0> MQTT SEND: CID: "first_client_id" CONNACK(sp: 0, rc: 0)`

Message number 2 - is when I sent a message

Maybe there is something wrong with publish/subscribe patterns in the PostgreSQL query?

**Comment by miptildar** [comment]
@larshesel thank you!
This was the solution:
> this usually happen if the client isn't authorized to publish to the topic

I thought there is no difference between channels `u2u/something` and `/u2u/something`

**Comment by larshesel** [comment]
Happy it worked.
