### ISSUE TITLE
PostgreSQL Store for Sessions, Subscriptions and Messages.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#92]
Are there any plans to support PostgreSQL as a store for sessions, subscriptions and offline messages?

**Comment by ioolkos** [comment]
His testark,

while there are currently no clear plans for this, we've been discussing some sort of full consistency modes for VerneMQ lately. This would imply making the backend database replacable or switchable, and would be the first step in any case (PostgreSQL or other).
Let's see.

Great to see you back here btw :)

**Comment by testark** [comment]
@ioolkos have there been any developments regarding this?

**Comment by larshesel** [comment]
hi @testark! Unfortunately not. Our priorities have been elsewhere lately. I think the best chance of getting a feature like this at the moment would be if someone contributes it - it doesn't have a very high priority on our roadmap at the moment. That is, of course, subject to change ;)
