### ISSUE TITLE
Able to Publish and Subscribe But Metrics is not updating.

### ISSUE THREAD

**Issue by namjitharavind** [erlio/vernemq#929]
### Environment
localhost
- VerneMQ Version: 1.4.1
- OS: Ubuntu 18.04
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.
Metrics should be updated while publish or subscribe messages.
### Actual behaviour
Able to Publish and Subscribe with database Auth But metrics is not updating. And With Wrong password also we could publish and subscribe.
- Please include minimal steps to reproduce the issue, if possible.

**Comment by larshesel** [comment]
I'm not able to reproduce this - are you 100% sure you're not having another broker running which you're accidentally connecting to?

You can list the currently connected clients and session by running `vmq-admin session show` - does your clients show up there?

you can also trace your clients to see what's going using `vmq-admin trace client client-id=<clientid>` - this would be very helpful in understanding what's going on.

**Comment by namjitharavind** [comment]
while running 

> vmq-admin session show
nothing  diplayes

 while running 

> vmq-admin  trace client client-id=pubclient
No sessions found for client "pubclient"

**Comment by namjitharavind** [comment]
sudo netstat -tulpn | grep 1883
===============================
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      1482/mosquitto      
tcp6       0      0 :::1883                 :::*                    LISTEN      1482/mosquitto

vmq-admin listener show
=======================
+----+-------+-------+-----+----------+---------+
|type|status |  ip   |port |mountpoint|max_conns|
+----+-------+-------+-----+----------+---------+
|http|running|0.0.0.0|8888 |          |  10000  |
|vmq |running|0.0.0.0|44053|          |  10000  |
+----+-------+-------+-----+----------+---------+

**Comment by larshesel** [comment]
right, so you're not hitting VerneMQ, but mosquitto which is running on port 1883, please stop mosquitto and restart vernemq - that should help.

**Comment by namjitharavind** [comment]
Thanks a lot for your kindness. I have removed mosquitto. Its working.
