### ISSUE TITLE
Cannot reach 30k concurrent connections

### ISSUE THREAD

**Issue by dophlin** [erlio/vernemq#93]
Hi guys,
I experianced a weird behaviour of vernemq. I try to connect 30k clients with vernemq but when the number of clients reachs 28k they start to be disconnected. Is there any limitation or I am doing something wrong!?
I should mention that I did exactly the same test with mosquitto and there is not any problem with that and I can easily reach 60k concurrent connections.

Thanks

**Comment by ioolkos** [comment]
Hello,
this is most certainly configuration related. 

In vernemq.conf, have a look at `listener.max_connections` and maybe `max_client_id_size`. 
Look at `erlang.max_ports`.

What is `ulimit -n` in the shell when you started VerneMQ?

Other than that it's hard to tell without more information. 
Feel free to send your vernemq.conf to info@verne.mq, or ask on the public VerneMQ mailing list.

**Comment by larshesel** [comment]
Hi @dophlin are you still experiencing these issues? If you do please feel free to reopen.
