### ISSUE TITLE
Is there any way to balance consumers spread over different cluster nodes.

### ISSUE THREAD

**Issue by onlywangyh** [erlio/vernemq#932]
### Environment

- VerneMQ Version:
- OS:
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.

**Comment by larshesel** [comment]
Hi, I'm not sure exactly what it is you're asking here.  Are you asking if messages flowing over a topic can be shared between multiple subscribers connected to different nodes? In that case you're likely looking for the shared subscription feature https://docs.vernemq.com/configuring-vernemq/shared_subscriptions.

Hope this helps.

**Comment by onlywangyh** [comment]
Thanks a lot . I noticed that the Consumer Session Balancing  cannot balance consumers spread over different cluster nodes. So I want to shared subscriptions firstly. Then each node can use the session balancing. I think we can do it that way to balance consumers spread over different cluster nodes. But now, we can't receive messages from the "$share/sharename/topic" .

**Comment by larshesel** [comment]
It's not clear to me there's a different issue here than #937 so I'll close this for now to keep the discussion in a single place.
