### ISSUE TITLE
What is the TLS protocol version used? 

### ISSUE THREAD

**Issue by froy001** [erlio/vernemq#936]
### Environment

- VerneMQ Version:  1.3.1
- OS: debian jessie
- Erlang/OTP version (if building from source):

### Expected behavior

- Please describe the expected behaviour.

### Actual behaviour

- Please include minimal steps to reproduce the issue, if possible.
What is the TLS protocol version TLS 1.2 or TLS 1.3?

**Comment by larshesel** [comment]
Hi,
Thanks for the question.

VerneMQ supports TLS 1.2 (and 1.1) as this is what Erlang/OTP supports. TLS 1.3 is in the works, but not yet supported.

Hope that helps.

**Comment by endorama** [comment]
Hello, I wasn't able to find more information on TLS version supported in the docs and this issue is quite old.

Did TLS 1.3 support landed?

Thanks!

**Comment by ioolkos** [comment]
@endorama VerneMQ TLS support is completely based on what Erlang/OTP supports (as mentioned).
TLSv1.3 just landed in OTP Release 23.0, so we'll hopefully be able to support this in the future. (VerneMQ does not yet fully support OTP 23.0)

**Comment by endorama** [comment]
Thanks @ioolkos, I'll keep an eye on the changelog!

**Comment by mladen-djordjevic** [comment]
In VerneMQ [1.10.4](https://github.com/vernemq/vernemq/blob/master/changelog.md#vernemq-1104) release, one of the features is:
- Add compatibility with Erlang/OTP 23

Does it mean that VerneMQ now supports TLS 1.3?

**Comment by ioolkos** [comment]
@mladen-djordjevic in theory, yes. feel free to test and report back.

**Comment by mladen-djordjevic** [comment]
Hi @ioolkos,

I have tested TLS 1.3 on VerneMQ versions 1.10.4.1 and 1.11.0 and **I wasn't able to make it work with TLS 1.3**.

### VerneMQ configuration
I didn't find any TLS version reference in the official VerneMQ documentation. Inspecting _vernemq.conf_ file I saw this part:
`## Configure the TLS protocol version (tlsv1, tlsv1.1, or tlsv1.2) to be`
`##`
`## Default: tlsv1.2`
`##`
`## Acceptable values:`
`##   - text`
`## listener.ssl.tls_version = tlsv1.2`
In the first line from the code above there is no TLS 1,3 in the list.

I tried with:
`listener.ssl.tls_version = tlsv1.3`
but I am receiving a handshake error.

Here is my config:
`########## Start ##########`
`accept_eula=yes`
`log.console.level=debug`
`listener.ssl.certfile=/vernemq/data/certs/vernemq-localhost.crt`
**`listener.ssl.tls_version=tlsv1.3`**
`listener.ssl.cafile=/vernemq/data/certs/vernemq-chain.pem`
`listener.ssl.keyfile=/vernemq/data/certs/vernemq-localhost.key`
`listener.ssl.require_certificate=on`
`listener.ssl.default=0.0.0.0:8884`
`log.console=console`
`vmq_passwd.password_file = /vernemq/etc/vmq.passwd`
`erlang.distribution.port_range.minimum = 9100`
`erlang.distribution.port_range.maximum = 9109`
`listener.tcp.default = 172.17.0.2:1883`
`listener.ws.default = 172.17.0.2:8080`
`listener.vmq.clustering = 172.17.0.2:44053`
`listener.http.metrics = 172.17.0.2:8888`
`########## End ##########`

### My tests
As an MQTT client, I have used Java application that supports both TLS 1.2, and TLS 1.3 (it is configurable).
I monitored TLS handshake using Wireshark app. Here are some test cases with results:
| Client supported TLS versions| Broker TLS version| Connection established|Explanation|
| ------------- |:-------------:| -----:|------:|
| TLS 1,2 & TLS 1.3      | not set in vernemq.conf (default to TLS 1.2)| TLS 1.2 |OK - maximum TLS version that both client and server support|
| TLS 1,2 & TLS 1.3      | TLS 1.2| TLS 1.2 |OK - maximum TLS version that both client and server support|
| TLS 1,2 & TLS 1.3      | TLS 1.3| FAILED |**NOT OK - connection should be stablished with TLS 1,3**|

For additional TLS version validation, I have also used openssl command (example for mosquitto):
`openssl s_client -connect test.mosquitto.org:8883 -tls1_3`

Can you please validate that VerneMQ works with TLS 1.3 or give me some tips on how to make it work?

**Comment by ioolkos** [comment]
Hi @mladen-djordjevic there's no support for TLS 1.3 in the packages, as they are compiled with OTP 22.3. 
TLS 1.3 is supported from Erlang OTP 23.0 upwards. If you want to give this a try, you'll need to compile Verne with OTP 23.0.

**Comment by mladen-djordjevic** [comment]
@ioolkos  thank you for the info. If I decide to go with compiling, I'll post the result here.

**Comment by ioolkos** [comment]
@mladen-djordjevic great, thanks. I think TLS 1.3 should work, although no further testing has been done. So it could still be that see issues surfacing due to protocol differences. Let's see.

**Comment by mladen-djordjevic** [comment]
Hi @ioolkos, I have compiled Verne with Erlang/OTP 23.0 and run the same tests, but behavior and outcome is the same as before (as shown in the table in my earlier comment [here](https://github.com/vernemq/vernemq/issues/936#issuecomment-721281452))

**Comment by ioolkos** [comment]
Ok, thanks for testing. Can you provide the potential output or logs from Verne console.logs, client logs or `openssl_client` logs?

**Comment by jforge** [comment]
As this story is closed: Is this meanwhile working from scratch in VerneMQ?
Having this (as a default) would add more security and increases at least the handshake performance.

**Comment by ioolkos** [comment]
@jforge Thanks, So far, I've done no further testing on TLS v1.3, so essentially my same answer as before. OTP 23+ has v1.3 support. We need to determine whether this comes for free to Verne or whether we have to actually adapt code.
