### ISSUE TITLE
Unable to publish message with qos(1 | 2 ) from plugin 

### ISSUE THREAD

**Issue by sunnyjain1** [erlio/vernemq#95]

**Comment by larshesel** [comment]
fixed via #100

**Comment by sunnyjain1** [comment]
Can you please tell me why the Qos value is upgrading when I am using this function. If a subscriber is subscribed with Qos 2 and I am publishing with Qos 1 then the subscriber is receiving the message at Qos 2.

**Comment by dergraf** [comment]
Which function are you using, how do the passed args look like?

**Comment by sunnyjain1** [comment]
The problem is due to the type of argument. I checked it after you asked and the qos was of string type. Thanks.
