### ISSUE TITLE
Update rebar3.

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#96]
I have a few plugins which depend on a recent version of https://github.com/benoitc/hackney and I'm being told that `rebar3` cannot build them (`certifi-0.4.0` for example). Would it be possible to update the bundled version of `rebar3` now that `3.0.0-stable` seems to have been released?

**Comment by testark** [comment]
@dergraf thank you very much :-) Do you have any idea on when it will be released?

**Comment by larshesel** [comment]
closed via #100
