### ISSUE TITLE
Debugging VerneMQ

### ISSUE THREAD

**Issue by testark** [erlio/vernemq#97]
(Not exactly an issue, so please forgive me if this is not the right place to ask.)

I'm not very familiar with Erlang, and as such I'd like to ask how would I go about setting up VerneMQ in an IDE (for instance, IDEA) and setting breakpoints and inspect variables. Is this possible at all? Could you please shed some light on this? :-)

**Comment by ioolkos** [comment]
I sometimes use Intellij IDEA for Erlang too (and I like it actually!)
There is experimental debugger support in the Erlang plugin.

But a better way might be to just start an Erlang shell and run the debugger utility, `debugger:start()`
Then load vmq_server modules into it.

Read up a little on it here: http://erlang.org/doc/apps/debugger/debugger_chapter.html

Depending on what you want to do, don't forget about tracing!

Any further questions are always welcome! :)

**Comment by larshesel** [comment]
closing for now - feel free to reopen should you have further questions.
