### ISSUE TITLE
Documentation: Authentication

### ISSUE THREAD

**Issue by yves-ledermann** [erlio/vernemq#98]
I just startet to try vernemq for a project.
Installed everything acc. the getting started docs on an ubuntu 14.04 server.

In the Docs on Page [https://verne.mq/docs/configuration/authentication.html] (authentication) are some "stumbling blocks".
It took some minutes to till i moved the file to the right place with the right name :)

1.
> VerneMQ periodically checks the specified password file.
> password_file = /etc/vmq.passwd

2.
> Examples
> Add a user to a new password file:
> vmq-passwd -c /etc/vernemq/passwd henry

3.
in the config file (vernemq.conf) the default is:

> Set the path to a password file.
> Default: /etc/vernemq/vmq.passwd

**Comment by ioolkos** [comment]
Apologies for any frustration. I'll remove the stumbling blocks tomorrow. Thanks a lot Yves! :)
