### ISSUE TITLE
[Question] About queue_deliver_mode

### ISSUE THREAD

**Issue by taemin77** [erlio/vernemq#99]
I am doing a test with queue_deliver_mode option.
I have set two verneMQ broker.  
These brokers were connected with each broker using [MQTT Bridge] function.
I will call each brokers as A broker, B broker.
one client(clientID=ID1) connected with A broker (Subscribe Topic : TOPIC1).
another client(clientID=ID1) connected with B broker (Subscribe Topic : TOPIC1).
in this case, when I send a message to TOPIC1, two client received the message.
But I want only one client receive the message.

I did a test that It is possible when I use one verneMQ broker.
but when I use two verneMQ broker and each client (same clientID) are connected with each broker,
It dosen't works well.

**Comment by ioolkos** [comment]
Hi, 
thanks for asking. The queue can't be load balanced this way. In fact the 2 bridged brokers are unaware of respective clientIDs, so you can't do session balancing over a bridge.

Does this make sense?

**Comment by taemin77** [comment]
Thank you for your prompt reply.
